### ISSUE TITLE
Is that possible to config collectd via network rather than config file?

### ISSUE THREAD

**Issue by tianchao-haohan** [collectd/collectd#1005]
As titled, I want to integrate collectod with web, and config collectd from web page.
Is that possible to config the collectd from tcp socket?
Is so, could you please help to share the link to howto? 

Besides, is that possible to load plugin with dynamic loading, without re-compile and re-start collectd?
It seems that the feature works well in collectd-4.10.9.rpm.

The third question, collectd need to be installed in server if I want to get the cpu, memory message from the server, is that possible to query those data from server remotely, for example snmp?

**Comment by tokkee** [comment]
It's currently not possible to configure collectd remotely. There was some talk around making configuration plugable, which would allow to do so but there wasn't any actual work done yet.

Loading plugins dynamically at runtime, likewise, isn't possible. That's just one aspect of the configuration.

collectd supports SNMP just fine. You can query remote systems using the "SNMP" plugin. See the collectd-snmp manpage and the wiki for details.

**Comment by michaelsalmon** [comment]
collectd is pretty light weight, probably lighter than snmpd. You can collect the data on a central machine or machines using the network client and server.

Updating the config files using a web server should be easy but you have to restart the server to read those files. I'm not sure that you would win much by reloading the config over restarting. Not without making collected much more complicated anyway.

**Comment by rafaelpsouza** [comment]
This project can help:
https://github.com/rafaelpsouza/orc

**Comment by aishasimran21** [comment]
can collectd can be reconfigured dynamically. if yes how plzzz reply
