### ISSUE TITLE
Location of libjvm.so needs to be specified explicitly to allow 32/64 bit building

### ISSUE THREAD

**Issue by dago** [collectd/collectd#1007]
On Solaris it is possible to build both 32 and 64 bit on the same platform due to a hybrid OS API. Additionally, it is also necessary sometimes to use the 32 bit version as some libraries may only be available in 32 bit while other may only be available in 64 bit. The layout looks essentially like this:
```
/opt/csw/java/jdk1.7.0_75/jre/lib/i386/server/libjvm.so
/opt/csw/java/jdk1.7.0_75/jre/lib/amd64/server/libjvm.so
```
The current code in configure.ac uses find and just gets the first one which is unfortunately not enough in this case.

**Comment by mfournier** [comment]
I'm aware there are a couple of environment variables that can be used to point the build system to the correct jvm installation. Take a look at how the collectd debian package handles this:

https://github.com/collectd/pkg-debian/blob/master/debian/rules#L42-L52
https://github.com/collectd/pkg-debian/blob/master/debian/rules#L186-L187

Hope that helps !

**Comment by dago** [comment]
Hi Marc, this was indeed what I was looking for. Thanks! -- Dago
