### ISSUE TITLE
Source download files don't match collectd-master on GitHub

### ISSUE THREAD

**Issue by allyunion** [collectd/collectd#1011]
There are some files missing, because I get the following build errors:
error: File not found: /builddir/build/BUILDROOT/collectd-5.4.2-1.el6.fbit.x86_64/usr/lib64/collectd/drbd.so
error: File not found: /builddir/build/BUILDROOT/collectd-5.4.2-1.el6.fbit.x86_64/usr/lib64/collectd/ipc.so
error: File not found: /builddir/build/BUILDROOT/collectd-5.4.2-1.el6.fbit.x86_64/usr/lib64/collectd/write_log.so
error: File not found: /builddir/build/BUILDROOT/collectd-5.4.2-1.el6.fbit.x86_64/usr/lib64/collectd/write_sensu.so
Executing(%doc): /bin/sh -e /var/tmp/rpm-tmp.2zxzgn
error: File not found: /builddir/build/BUILDROOT/collectd-5.4.2-1.el6.fbit.x86_64/usr/lib64/collectd/write_tsdb.so
error: File not found: /builddir/build/BUILDROOT/collectd-5.4.2-1.el6.fbit.x86_64/usr/lib64/collectd/zookeeper.so

Some of these files are not listed when you unzip from:
https://collectd.org/files/collectd-5.4.2.tar.bz2

**Comment by mfournier** [comment]
I assume you have this error while building RPM packages? You should use the specfile in the collectd-5.4 branch if using 5.4.2.

**Comment by allyunion** [comment]
Yes.  And I happen to be using the specfile from the collectd 5.4 branch.
