### ISSUE TITLE
cant get auth headers using write_http

### ISSUE THREAD

**Issue by loadavg** [collectd/collectd#1012]
When installing collectd using base packages on centos 6, 7 and ubuntu 13 the auth headers arent sent when activated in the write_http plugin

 <Plugin write_http>
        <URL "http://localhost:8080/api">
                User "loaduser"
                Password "loadpass"
                Format "JSON"
        </URL>
</Plugin>

the plugin functions and sends data over to the destination - however the auth data is not there ?

**Comment by loadavg** [comment]
i have also now compiled from source and started to look at write_http.c

in wh_callback_init

after

                ssnprintf (cb->credentials, credentials_size, "%s:%s",
                                cb->user, (cb->pass == NULL) ? "" : cb->pass);
                
                curl_easy_setopt (cb->curl, CURLOPT_USERPWD, cb->credentials);

cb->credentials is setting the correct username / password for CURL to use ? so not sure why its not being set over when data is pushed out ?

**Comment by loadavg** [comment]
I have checked out the code in wh_send_buffer and it seems that auth data is being sent - just cant access it on the client side ?

I built a small node.js server to grab the header data and it always comes up with no auth data when pushed form collectd ?

var http = require('http');
 
var server = http.createServer(function(req, res) {
  
      var auth = req.headers['authorization'];  // auth is in base64(username:password)  so we need to decode the base64
      console.log("Authorization Header is: ", auth);
 
});
 
 
server.listen(8080, function() { console.log("Server Listening on http://localhost:8080/"); });

**Comment by loadavg** [comment]
So after more diggin i have found that if i change

                curl_easy_setopt (cb->curl, CURLOPT_HTTPAUTH, CURLAUTH_ANY);

to
                curl_easy_setopt (cb->curl, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);

in

wh_callback_init

I am able to access the auth header when pushed to my server... ????

**Comment by loadavg** [comment]
maybe you can add a option to the write_http module settings to let the user choose the auth mode ? that way we can set it to Basic there and change it as need be ?

**Comment by loadavg** [comment]
actually figured out how to do this server side :)

https://stormpath.com/blog/the-problem-with-api-authentication-in-express/

your implementation is fine

thanks!

**Comment by yanc0** [comment]
Hi I have the same issue with Golang, can you explain how you finally get through this?

Thanks !
