### ISSUE TITLE
Collecting statistics  from AWS RDS mysql

### ISSUE THREAD

**Issue by ppoornima** [collectd/collectd#1013]
Hi,
I used mysql plugin to collect statistics for one of my AWS RDS mysql instance. I was not able to collect any statistics. I would like to know if this is possible ? If, then is there any other configurations that I should be doing other than the ones mentioned in collectds wiki page?
Thanks

**Comment by rubenk** [comment]
Hi,

There's no explicit support for AWS RDS in Collectd's MySQL plugin, so I guess it depends on how much alike MySQL and RDS are.

I'm afraid you'll have to see for yourself.
