### ISSUE TITLE
collectd.service times out on systemd startup on CentOS7

### ISSUE THREAD

**Issue by mbolek** [collectd/collectd#1021]
It seems that systemd is not able to start collectd properly due to a small typo in the init.d script. The pidfile in the comment is different than in the code:
pidfile: /var/run/collectd.pid
and the variable is:
COLLECTDMONPIDDIR="/var/run"
COLLECTDMONPID="$COLLECTDMONPIDDIR/collectdmon.pid"

This generates a following message in messagelog:
systemd[1]: PID file /var/run/collectd.pid not readable (yet?) after start

The process was working ok but systemd timed out the service and marked it as failed.

**Comment by mfournier** [comment]
No "official" init script is part of collectd releases. Merely suggestions in the contrib/ directory.

Are you using the collectd package from EPEL7 ? In this case http://bugzilla.redhat.com/ is probably where you should report this. /cc @rubenk

**Comment by mbolek** [comment]
k, thx
