### ISSUE TITLE
write_graphite write wrong cpu data

### ISSUE THREAD

**Issue by mingqi** [collectd/collectd#1022]
I use write_graphite write data to graphite. I compared the graphite data and raw data recored by csv plugin. I found written graphite data is very wrong. the cpu value in csv is usually below 100 which look normal. But graphite is very larger than millions. 

This is csv plugin data:
-------------------------------
root@mingqi-dev:/tmp/collectd.csv/localhost/cpu-0# tail -f ./cpu-system-2015-05-07
1430971962.348,10.889844
1430971972.339,9.408761
1430971982.344,9.594901
1430971992.339,10.905786
1430972002.339,11.299982
1430972012.352,11.484738
1430972022.348,9.903713
1430972032.340,9.507743
1430972042.339,10.301426
1430972052.339,11.000034

this is graphite data I captured it by network sniffer tool:
-------------------------
write error to stdout
localhost.cpu.0.cpu.system 12161118 1430972102

write error to stdout
localhost.cpu.0.cpu.system 12161118 1430972102

write error to stdout
localhost.cpu.0.cpu.system 12161118 1430972102

**Comment by mimaison** [comment]
I'm seeing the same issue, What did you do to fix it ?

**Comment by mingqi** [comment]
You need change the StoreRates to True in graphite write plugin configuration.
