### ISSUE TITLE
Want to limit how long write_http buffers (not just how much)

### ISSUE THREAD

**Issue by cep21** [collectd/collectd#1028]
Hi,

A system was setup using the write_http plugin and reporting very few metrics.  Even though we set the interval to 10 seconds, it took 30 seconds to see any data and data only came every 30 seconds.  The issue was that the buffer took 30 seconds to fill up.  I understand the need to have a buffer, but want to also not wait up to 30 seconds to send any collected data.

What are your thoughts on some sort of max delay on any flushed data for the write_http plugin. I would implement this as a MaxDelay parameter for the write_http plugin that spawns a thread that every X seconds wakes up and executes a flush for MaxDelay.

This could also be done as a global configuration for all write plugins.  Thoughts?

**Comment by mfournier** [comment]
Seems like #1044 is a step in this direction. Would you mind taking a look and maybe testing out the patch @cep21 ? Thanks !

**Comment by cep21** [comment]
Hi,

In your patch does this mean I configure a global FlushInterval and it will call every plugin's flush(), including the write_http plugin?

**Comment by manuelluis** [comment]
No, it's per plugin. For example:

    <LoadPlugin write_http>
        FlushInterval 2
        FlushTimeout 1
    </LoadPlugin>

I did not do it global because the plugin rrdtool has a cache to reduce the disk I/O and flushing this cache results in a serious performance problem.

**Comment by octo** [comment]
Fixed in #1067
