### ISSUE TITLE
Can I have two write_graphite and filter data to them by difference condition

### ISSUE THREAD

**Issue by mingqi** [collectd/collectd#1029]
I want to have two difference write_graphite config. One is StoreRates=True and another is False. I want to data write them by condition. for example, the cpu, memory plugin will write A and other plugin write to B.  I look through chain document. it's seem the writer filter is plugin level, instead of plugin instance level. Is possible do that? thanks

**Comment by aww-yiss** [comment]
I have a similar use case in mind, where some plugins I wish to have the values writes at the rate, and other not. This is specifically a problem when using the Tail plugins and DSTypes of CounterInc and Type counter are being reported as the average rate of the counter per interval, which is very inaccurate.

**Comment by octo** [comment]
Hi, you can use the *filter chain* mechanism to achieve this. This wiki page demonstrates how to do this with a fairly complete example: https://collectd.org/wiki/index.php/Match:Hashed/Config
