### ISSUE TITLE
"make distclean" fails.

### ISSUE THREAD

**Issue by octo** [collectd/collectd#1042]
This is a problem in the *collectd-5.5* and *master* branches. I believe the problem is that "distclean" descends into `src/daemon/` first, which will `rm -rf .deps`. Then, back in `src/`, it tries to include a bunch of `.Po` files, which no longer exist.

```
make[2]: Entering directory `/home/octo/collectd/src/daemon'
rm -rf .libs _libs
 rm -f collectd
rm -f *.o
rm -f *.lo
rm -f *.tab.c
test -z "" || rm -f 
test . = "." || test -z "" || rm -f 
rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
rm -rf ./.deps  # <--- 
rm -f Makefile
make[2]: Leaving directory `/home/octo/collectd/src/daemon'
make[2]: Entering directory `/home/octo/collectd/src'
Makefile:4023: daemon/.deps/collectd_tg-utils_heap.Po: No such file or directory
Makefile:4024: daemon/.deps/test_common-common.Po: No such file or directory
Makefile:4025: daemon/.deps/test_utils_avltree-utils_avltree.Po: No such file or directory
Makefile:4026: daemon/.deps/test_utils_heap-utils_heap.Po: No such file or directory
Makefile:4027: daemon/.deps/test_utils_mount-common.Po: No such file or directory
make[2]: *** No rule to make target `daemon/.deps/test_utils_mount-common.Po'.  Stop.
make[2]: Leaving directory `/home/octo/collectd/src'
make[1]: *** [distclean-recursive] Error 1
make[1]: Leaving directory `/home/octo/collectd/src'
make: *** [distclean-recursive] Error 1
```

Unfortunately, this also means that "make distcheck" also fails, currently blocking a release. :(

**Comment by rubenk** [comment]
This is one of the disadvantages of recursive make.
You should be able to work around it with --disable-dependency-tracking.

**Comment by mfournier** [comment]
Thanks for looking into this @rubenk ! So I guess you're referring to https://www.gnu.org/software/automake/manual/html_node/Dependency-Tracking.html ?

I don't have much time now, but at least `./clean.sh && ./build.sh  && ./configure --disable-dependency-tracking && make distcheck` against the current `collectd-5.5` branch doesn't seem to solve the problem.

**Comment by mfournier** [comment]
Digging in the direction of @rubenk's hint, it looks like this change works around the problem:

```diff
--- src/Makefile.am
+++ src/Makefile.am
@@ -21,7 +21,7 @@ endif
 AM_CPPFLAGS += -DPLUGINDIR='"${pkglibdir}"'
 AM_CPPFLAGS += -DPKGDATADIR='"${pkgdatadir}"'
 
-AUTOMAKE_OPTIONS = subdir-objects
+AUTOMAKE_OPTIONS = subdir-objects no-dependencies
 
 sbin_PROGRAMS = collectdmon
 bin_PROGRAMS = collectd-nagios collectdctl collectd-tg
```

With this, `./clean.sh && ./build.sh && ./configure && make distcheck` works, the generated tarballs are valid (ie: `tar -x && ./configure && make && make install` works) and running `make && make install` in the git repo also works.

That said, I don't fully understand the implications & side effects this could have, and from what I understand, the correct fix would be to have a dedicated `src/tests/Makefile.am`. @octo, is there any reason why this was done this way when adding the test suite ?

**Comment by octo** [comment]
Ohai, sorry, didn't see your comments early enough.

Disabling dependency tracking entirely is probably fine for a release tarball, but it would be a bit annoying when doing development: If I make a change in, say, `utils_avltree.h`, I want all parts who use this to be rebuilt when I type `make`. Without dependency tracking, you'd end up doing `make clean all` in that case – if you remember to do so.

What I ended up doing is far more frightening: the build system is now building a couple of binary libraries and stitches them together to form the binaries, shared objects and tests. This removes files from other directories from the `_SOURCES` lines, i.e. stuff like this is no longer happening:

```
foo_SOURCES = foo.c daemon/bar.c
bar_SOURCES = bar.c ../tests/qux_test.c
```

I sincerely hope this doesn't break too bad.

@mfournier Well, no good reason behind any of this, really. But putting a `Makefile.am` into the `src/tests/` directory wouldn't fix the problem in itself. The two `.c` files, `foo.c` and `foo_test.c`, need to be linked into one binary at the end of the day, and putting them both on the `_SOURCES` line will cause this kind breakage. The problem is a fundamental one, imho: when compiling the dependency information is created in a *foreign* directory, and `make clean` will clean up *all local* dependencies, not only the ones also created locally. This asymmetry is the root cause I think.

What do you think?

**Comment by rubenk** [comment]
sorry for the late response.

@mfournier make distcheck picks the default configure flags, and not the ones you pass with ./configure.
If you want that you need to 'make distcheck DISTCHECK_CONFIGURE_FLAGS=--dependency-tracking'

@octo the issue is indeed that you have files from other directories in your _SOURCES. The order in which everything is cleaned depends on the order of SUBDIRS. We're in exactly the same situation with powerdns. I think this is a bug in automake, but I found some posts on the automake mailing lists that basically say 'don't do that then, and use recursive make'. I think what you're doing with convenience libraries is a good workaround. Another one would be to disable dependency tracking globally and do it by hand, i.e. add utils_avltree.h to all _SOURCES that need that header, but that's almost undoable for sucj a large project as this.
