### ISSUE TITLE
wrong cpu data over network plugin

### ISSUE THREAD

**Issue by alchris** [collectd/collectd#1045]
Hi,
I use the network-plugin to send cpu data to logstash as described on https://www.elastic.co/blog/logstash-collectd-input-plugin.

The cpu values are usually below 100 but the values I see after logstash are greater than one million. Data recorded by the csv-plugin are seems to be correct. If I use wireshark to investigate the transmitted packets I get the same values ​​as in logstash. 

The problem seems to be similar to that described at https://github.com/collectd/collectd/issues/1022

I use debian jessie with collectd version 5.4.1.

Thanks for help!

**Comment by mfournier** [comment]
The network plugin doesn't calculate rates, see #949. You'll need to do this calulation in logstash/kibana.
