### ISSUE TITLE
 write_graphite plugin: Invalid configuration option: Node.

### ISSUE THREAD

**Issue by dumolibr** [collectd/collectd#1048]
Hi,

Restarting statistics collection and monitoring daemon: collectd[2015-05-25 20:32:35] write_graphite plugin: Invalid configuration option: Node.
[2015-05-25 20:32:35] ping plugin: MaxMissed < 0, disabled re-resolving of hosts
[2015-05-25 20:32:37] write_graphite plugin: Invalid configuration option: Node.
[2015-05-25 20:32:37] ping plugin: MaxMissed < 0, disabled re-resolving of hosts

From standard config:
> ` LoadPlugin "write_graphite"`
 ` <Plugin "write_graphite">`
`  <Node "example">`
`    Host "localhost"`
`    Port "2003"`
`    #Prefix "collectd."`
`    #Postfix ""`
`    #Protocol "udp"`
`    #LogSendErrors false`
`   EscapeCharacter "_"`
`    SeparateInstances true`
`    StoreRates false`
`    AlwaysAppendDS false`
`  </Node>`
` </Plugin>`

Builtin defaults:
  Config file       /etc/collectd/collectd.conf
  PID file          /var/run/collectd.pid
  Plugin directory  /usr/lib/collectd
  Data directory    /var/lib/collectd

collectd 5.1.0, http://collectd.org/

Am I missing something?

**Comment by dumolibr** [comment]
On IRC and in the man page it says that Node has been replaced with Carbon.
That solved my issue.

Please update the relevant documentation on the wiki and the config file that ships with the lastest source.
Those still show "Node" instead of "Carbon".

**Comment by mfournier** [comment]
Yes, it's the other way round: collectd up to 5.2 this parameter named `<Carbon>`. Since 5.3 you should use `<Node>` although backwards compatibilty will be guaranteed until version 6.0.

The manpage & the wiki is already correct, so closing.
