### ISSUE TITLE
Can I use one type of aggregation result to calculate another type result?

### ISSUE THREAD

**Issue by qihuagao** [collectd/collectd#1055]
Can I use one kind of aggregation result to calculate another type result, for example below, 
we want to calc out total cpu result based on user, system..:  below is my config, seems not working.
Should I use filter? I am new to collectd.

Note: this calculation is only an example, not precise.
  ```
<Plugin "aggregation">
  <Aggregation>
    #Host "unspecified"
    Plugin "cpu"
    #PluginInstance "unspecified"
    Type "cpu"
    #TypeInstance "unspecified"
    SetPluginInstance "cpu-%{aggregation}"
    GroupBy "Host"
    GroupBy "TypeInstance"
    CalculateNum false
    CalculateSum false
    CalculateAverage true
    CalculateMinimum false
    CalculateMaximum false
    CalculateStddev false
  </Aggregation>
 <Aggregation>
   # Host "unspecified"
    Plugin "aggregation"
    PluginInstance "cpu-average"
    Type "cpu"
    SetPluginInstance "cpu-total"
    TypeInstance "^(?! idle)"
    GroupBy "Host"
    CalculateSum true
 </Aggregation>
</Plugin>
```

**Comment by octo** [comment]
No, that's currently not possible. Can you explain a bit what your use-case would be?

—octo

**Comment by qihuagao** [comment]
Thank you for answer, respond later because my mail notification has some problem. 
It's mainly out of curiosity, I'll close this now.
