### ISSUE TITLE
swap-plugin reports blocks instead of bytes (CentOS 6)

### ISSUE THREAD

**Issue by Lightning-** [collectd/collectd#1062]
hey everyone,

I'm about to upgrade from 5.4 to 5.5 and discovered that the swap-plugin now seems to report swap as blocks instead of bytes whereas documentation still states bytes as it did before. As well, this seems to be caused by the swap-plugin itself, as unixsock, write_graphite and other write-plugins get the same data.
I need to know, what's wrong here: documentation or code (as my monitoring-system relies on collectd-data and, for now, is configured/coded to use bytes as docu says and 5.4 also did). As well I would prefer the byte-reporting, as "thinking in filesystem blocks" is rather embarrassing when looking at graphs and so on ;).

My setup is a CentOS 6.6; configuring/compiling was straighforward.

CentOS 6.6 with collectd 5.4 (outputs filtered to only provide relevant infos):
```
testhost1 # rpm -qa | grep collectd
collectd-5.4.2-1.el6.x86_64
collectd-swap-5.4.2-1.el6.x86_64
collectd-unixsock-5.4.2-1.el6.x86_64

testhost1 # cat /etc/collectd.conf
[...]
<Include "/etc/collectd.d">
	Filter		"*.conf"
</Include>

testhost1 # cat /etc/collectd.d/unixsock.conf
LoadPlugin "unixsock"

<Plugin "unixsock">
	SocketFile		"/var/run/collectd.sock"
	SocketGroup		"root"
	SocketPerms		"0770"
	DeleteSocket	true
</Plugin>

testhost1 # cat /etc/collectd.d/swap.conf
LoadPlugin "swap"

<Plugin "swap">
	ReportByDevice	false
	ReportBytes		true
</Plugin>

testhost1 # free -m
             total       used       free     shared    buffers     cached
Swap:         2047          6       2041

testhost1 # free
             total       used       free     shared    buffers     cached
Swap:      2097148       7056    2090092

testhost1 # nc -U /var/run/collectd.sock
getval testhost1/swap/swap-free 
1 Value found
value=2.140254e+09
```

CentOS 6.6 with collectd 5.5 (outputs filtered to only provide relevant infos):
```
testhost2 # rpm -qa | grep collectd
collectd-5.5.0-1.el6.x86_64
collectd-swap-5.5.0-1.el6.x86_64
collectd-unixsock-5.5.0-1.el6.x86_64

testhost2 # cat /etc/collectd.conf
[...]
<Include "/etc/collectd.d">
	Filter		"*.conf"
</Include>

testhost2 # cat /etc/collectd.d/unixsock.conf
LoadPlugin "unixsock"

<Plugin "unixsock">
	SocketFile		"/var/run/collectd.sock"
	SocketGroup		"root"
	SocketPerms		"0770"
	DeleteSocket	true
</Plugin>

testhost2 # cat /etc/collectd.d/swap.conf
LoadPlugin "swap"

<Plugin "swap">
	ReportByDevice		false
	ReportBytes			true
	ValuesAbsolute		true
	ValuesPercentage	true
</Plugin>

testhost2 # free -m
             total       used       free     shared    buffers     cached
Swap:         2047          0       2047

testhost2 # free
             total       used       free     shared    buffers     cached
Swap:      2097148          0    2097148

testhost2 # nc -U /var/run/collectd.sock
getval testhost2/swap/swap-free 
1 Value found
value=2.097148e+06
```

If you need any further information or debugging-help, just ask :)

**Comment by mfournier** [comment]
Thanks for the bugreport @Lightning- !

I didn't look into this in details, but it would be the code which would be wrong, not the doc. The changes to this plugin have been pretty important between 5.4 and 5.5, so it's quite possible a mistake slipped in :(

**Comment by mfournier** [comment]
@Lightning- it seems @marekbecka submitted a fix for this: #1071

Would you mind giving the patch a try and report back if it solves the problem ? Thanks !

**Comment by Lightning-** [comment]
@mfournier sure, i'll have a look and try this out

**Comment by octo** [comment]
#1071 has been merged, marking this as fixed.

**Comment by Lightning-** [comment]
finally, i managed to verify this in my testing-environment: patch works for me, thx :)

having a look at the patch itself, i have a little note about it: i don't know whether there are systems that use a (possibly tweakable) swap-blocksize larger/other than 1024 bytes; so a hardcoded value of 1024.0 might not be applicable/correct on all systems that collectd might run on. trying to detect swap-blocksize with a default of 1k would be the perfect way (but don't ask me how to do this in a wise way ;)).
