### ISSUE TITLE
Tail plugin doesn't handle well with autoload

### ISSUE THREAD

**Issue by marekbecka** [collectd/collectd#1069]
Hi,
I have noticed issue in collectd 5.5.0 with tail plugin, If autoloading is enabled and "LoadPlugin tail" nor Interval is specified in tail instances I got message:

Jun  9 16:20:19 host collectd[14697]: plugin_value_list_clone: Unable to determine interval from context for value list "host.example.com/tail-logger/log_event-oom_killer". This indicates a broken plugin. Please report this problem to the collectd mailing list or at <http://collectd.org/bugs/>.

If tail plugin is implicitly loaded with LoadPlugin or all tail instances have set Interval option, no error message is shown and plugin works.

**Comment by octo** [comment]
Thanks for reporting this @marekbecka! I think the above commit fixes the issue.

**Comment by marekbecka** [comment]
Patch works great, thank you.
