### ISSUE TITLE
zone plugin: Build fails on Solaris 11

### ISSUE THREAD

**Issue by octo** [collectd/collectd#1077]
Looks like `procfs.h` is unhappy about us using a large `off_t` or something …

```
  CC       zone_la-zone.lo
In file included from /usr/include/procfs.h:26:0,
                 from zone.c:31:
/usr/include/sys/procfs.h:45:2: error: #error "Cannot use procfs in the large file compilation environment"
 #error "Cannot use procfs in the large file compilation environment"
  ^
Makefile:4576: recipe for target 'zone_la-zone.lo' failed
```

**Comment by octo** [comment]
cc @dago

**Comment by octo** [comment]
A quick Google search seems to suggest that this is due to `_FILE_OFFSET_BITS=64` while compiling on a 32-bit architecture.

**Comment by octo** [comment]
We can likely steal this from `src/swap.c`:

```c
/* avoid swap.h error "Cannot use swapctl in the large files compilation environment" */
#if HAVE_SYS_SWAP_H && !defined(_LP64) && _FILE_OFFSET_BITS == 64
#  undef _FILE_OFFSET_BITS
#  undef _LARGEFILE64_SOURCE
#endif
```

**Comment by dago** [comment]
I noticed that also yesterday and wanted to recommend to use the same construct as for swap:
  https://github.com/collectd/collectd/blob/master/configure.ac#L397-L407

**Comment by octo** [comment]
SGTM, but I have a feeling that notice never gets printed – the configure script should have printed this, right? The previous `AC_CHECK_HEADERS` already contains `#undef _FILE_OFFSET_BITS` which prevents the check from failing …

**Comment by octo** [comment]
Let's see how this commit works out …

**Comment by dago** [comment]
We should see that the notice gets printed as 32 bit applications cannot inspect procfs for 64 bit applications: http://docs.oracle.com/cd/E18752_01/html/816-5138/advanced-10.html

**Comment by octo** [comment]
Are there 64bit processes on a x86 platform?

**Comment by octo** [comment]
FYI, it compiles now past the zone plugin but failes ultimately due to #978.

**Comment by dago** [comment]
Yes, since Solaris 10 the kernel is 64 bit on x86 and Solaris 11 does not even offer 32 bit, but as Solaris has a 32 bit ABI for the 64 bit kernel it is still customary to run 32 bit applications.

**Comment by octo** [comment]
So, the **i386** platform that the build bot advertises is a 64bit platform, aka x86-64? I was assuming it was 32bit, meaning that 64bit kernel / userland would not be able to run there.

Do I understand this correctly that the only time we will have problems is when we run a 32bit *collectd* binary on a 64bit kernel? If so, we should try to catch that in the configure script and actually disable the *zone plugin* in there.

**Comment by dago** [comment]
All Solaris 10+ hosts and all Sparc hosts on the farm run a 64 bit kernel. The only hosts that have a 32 bit kernel only are Solaris 8 x86 and Solaris 9 x86. However, without -m64 the compiler generates 32 bit code which can also run on a 64 bit kernel.

So the kernel always runs 64 bit. To allow processes to run in 32 bit the access to /proc is mimicked to look differently with 32 bit data types when accessed from a 32 bit application. 32 bit applications can not access /proc for 64 bit processes (which may exist, although not all processes are necessarily 64 bit processes). When large files is enabled the file access data structures are enhanced to use 64 bit again which is not possible when the /proc structures are 32 bit, hence the problem.

The correct way is to compile in 64 bit, however, from my work as a downstream packager, configure should not set -m32 or -m64, that should be to the discretion of the packager. Printing warnings or disabling dysfunctional plugins is a good idea. One reason to build collectd in 32 bit would be if you only have a library in 32 bit, e.g. we don't have 64 bit Perl and Python at the moment. My plan is to build both 32 and 64 bit binaries for the package and let the user run either version with SMF instances.

I have added extra 64 bit builds in buildbot to take care of checking these issues.

**Comment by octo** [comment]
Thanks for the explanation @dago, it makes sense now!

So what happens right now is that the compiler builds 32bit binaries, the plugin detects that and disables the large file support. Because the kernel does magically return appropriate structs from `/proc` to 32bit and 64bit binaries, this will work okay.

However, the more elegant solution would be to add the `-m64` CFLAG. We should therefore emit a warning from the configure script when we detect this.

Does that about sum it up?

**Comment by dago** [comment]
It will work partly ok as 32 bit processes can not stat 64 bit processes, so this will most certainly return inaccurate results. The warning would be perfect. The packager can then decide to add -m64 or disable the plugin during the compilation if needed.

**Comment by octo** [comment]
> checking whether compiler builds 64bit binaries... no
> configure: Solaris detected. Please consider building a 64-bit binary.

\o/

**Comment by dago** [comment]
Unfortunately the test does not properly detect when it builds on 64 bit. This is on amd64:
```
checking for kernel type (solaris2.10)... Solaris
checking whether compiler builds 64bit binaries... no
configure: Solaris detected. Please consider building a 64-bit binary.
checking for ANSI C header files... (cached) yes
```
The problem seems to be that neither CFLAGS nor LDFLAGS is used during this test and hence `-m64` is not set at all:
```
configure:15818: result: Solaris
configure:15891: checking whether compiler builds 64bit binaries
configure:15908: /opt/csw/bin/gcc -E -I/opt/csw/include conftest.c
conftest.c:50:9: error: #error "Compiler not in 64bit mode."
       # error "Compiler not in 64bit mode."
         ^
configure:15908: $? = 1
```
Full logs for 64 bit are available at https://buildfarm.opencsw.org/buildbot/builders/collectd-solaris10-amd64/builds/3
