### ISSUE TITLE
missing kvm_read error handling leading to infinite loop in tcpconns.c

### ISSUE THREAD

**Issue by landryb** [collectd/collectd#1094]
In certain circumstances, kvm_read in tcpconns.c can fail, and some error handling is missing from some kread() calls are not handling an error... this can lead to an infinite loop, resulting in collectd consuming all ressources and needing to be killed. Experienced it 4 or 5 times with collectd 5.4.1 on OpenBSD 5.6.

    Jun 12 19:11:44 rocket collectd[15811]: tcpconns plugin: kvm_read failed (got -1, expected 360): invalid address (deafbeaddeafbead) 
    Jun 12 19:11:44 rocket collectd[15811]: tcpconns plugin: kvm_read failed (got -1, expected 560): invalid address (0) 
    Jun 12 19:11:44 rocket collectd[15811]: tcpconns plugin: kvm_read failed (got -1, expected 360): invalid address (deafbeaddeafbead) 
    Jun 12 19:11:44 rocket collectd[15811]: tcpconns plugin: kvm_read failed (got -1, expected 560): invalid address (0) 

I'll prepare a pull request hopefully handling all missing error cases. if it can be backported to 5.4...

**Comment by rubenk** [comment]
This was merged as 924c9af
