### ISSUE TITLE
'uc_update: Value too old' error in 'interface-mac'

### ISSUE THREAD

**Issue by dago** [collectd/collectd#1099]
I get repeated errors of the following form:
```
Jun 29 07:24:10 spstha002 collectd[29592]: [ID 702911 daemon.notice] uc_update: Value too old: name = <host>/interface-mac/if_errors; value time = 1435555450.880; last cache update = 1435555450.880;
```
From https://collectd.org/faq.shtml I checked that
* the `interface` plugin is loaded only once
* the host is properly tied via NTP

Also this is the only metric that is reported with `Value too old`, all other metrics (`cpu, disk, load, memory, zfs_arc, zone`) don't have any reports of this kind, even the other metrics from `interface` are fine. I already checked the code in `interface.c` for issues about `if_errors` but can't seem to find anything suspicious.

**Comment by rubenk** [comment]
Hi!
Do you happen to have multiple interfaces with the same name?
Can you share some more details, the platform your on, collectd version and possibly ifconfig -a /ip l output?

**Comment by rubenk** [comment]
Closing this due to lack of feedback. Please reopen if you can provide more details.
