### ISSUE TITLE
virt plugin: Unable to connect: virConnectOpenReadOnly failed

### ISSUE THREAD

**Issue by sheikh-qzaman** [collectd/collectd#1121]
Hi All,
I'm trying to configure virt plugin in collectd but I'm getting the following error log.

    virt plugin: Unable to connect: virConnectOpenReadOnly failed.
    read-function of plugin `virt' failed. Will suspend it for 20.000 seconds.    

The system configuration is as follows:

    Operating System: RHEL 6.6
    Collectd: 5.5.0
    Collectd-virt: 5.5.0
    libvirt: 0.10.2

This is plugin settings in /etc/collectd.conf

    LoadPlugin virt
    <Plugin virt>
        Connection "qemu:///system"
        RefreshInterval 60
        HostnameFormat name
    </Plugin>

I get following output for virsh

    [root@localhost ~]# virsh -c qemu:///system list
    Id    Name                           State
    --------------------------------------------
    1     f5342079-b852-49b5-81cc-0528d8c9ec14_escVM running

Is any configuration in libvirt require? Would really appreciate any suggestion.

**Comment by rubenk** [comment]
Are you running SELinux in Enforcing mode?

**Comment by sheikh-qzaman** [comment]
Hi rubenk. Thank you very much for your reply. Yeah I checked SELinux is running in enforcing mode. And after I put it in disabled mode, virt plugin seems to be working. But I need to run SELinux in enforcing mode. What do I have to do to use collectd-virt plugin in enforcing mode?

Thanks

**Comment by rubenk** [comment]
Fedora has policy for this, but I don't know if it backported to RHEL.
https://bugzilla.redhat.com/show_bug.cgi?id=1071505

**Comment by mfournier** [comment]
Yes it is (on EL7 at least):
```
$ rpm -q --changelog selinux-policy-targeted
[...]
* Mon Mar 17 2014 Miroslav Grepl<mgrepl@redhat.com> 3.12.1-139
- Allow collectd to talk to libvirt
[...]
```

EL6 seems to come with an older version of the package which I assume doesn't have the fix.

**Comment by rubenk** [comment]
thanks @mfournier. @sheikh-qzaman, can you share the AVC you are getting when you run in Enforcing mode?

**Comment by sheikh-qzaman** [comment]
@rubenk , my bad. The operating system I was working on is actually RHEL 6.6. I was working in parallel to migrate my system to RHEL 7, hence the mistake. However I haven't fully tested it in RHEL 7.0 yet.
As it seems selinux policy in RHEL 6.6 "doesn't allow collectd to talk to libvirt", what measures needs to be taken to configure collectd-virt? Let me know if you still need the AVC for RHEL 6.6.

Thanks,

**Comment by rubenk** [comment]
This isn't really an upstream collectd issue, please open a bug report at Red Hat against the selinux-policy component.

You can also write custom policy, here's mine for reference:
```
cat tilaa-collectd-libvirt.te 
policy_module(tilaa-collectd-libvirt,1.0.6);

gen_require(`
        type collectd_t;
')

optional_policy(`
	virt_read_config(collectd_t)
	virt_stream_connect(collectd_t)
	virt_getattr_exec(collectd_t)
')
```

**Comment by paulstuart** [comment]
I'm seeing the same problem on CentOS 6.6 with collectd 5.5.0.
SELinux is disabled and I am able to make a similar query with "virsh -c qemu:///system list" and it successfully returns a list of the vms.

# virsh version
Compiled against library: libvirt 0.10.2
Using library: libvirt 0.10.2
Using API: QEMU 0.10.2
Running hypervisor: QEMU 0.12.1

Any thoughts on further debugging?

**Comment by rubenk** [comment]
@paulstuart if you are sure SELinux is disabled, the only thing I can think of is a permission issue.
Are you running both libvirt and collectd as root?

**Comment by paulstuart** [comment]
@rubenk -- it is disabled. After fudging with the config and several restarts it's now working. Very odd.
Thank you for your quick response!

**Comment by 91pavan** [comment]
+1
