### ISSUE TITLE
Multiple loads of plugins with AutoLoadPlugin

### ISSUE THREAD

**Issue by michaelsalmon** [collectd/collectd#1122]
While I was investigating a problem with threshold callbacks I discovered that if AutoLoadPlugin is true then the plugin is loaded for every plugin block. I don't use AutoLoadPlugin so I can't say that this is a problem but it seems to me that it isn't a good thing to do.

**Comment by octo** [comment]
That doesn't sound like the intended behavior. Need to reproduce.

**Comment by rpv-tomsk** [comment]
Not reproduced.
