### ISSUE TITLE
 statsd error: address already in use

### ISSUE THREAD

**Issue by michaelsalmon** [collectd/collectd#1126]
I intend to use collected as a statsd receiver but I am seeing:

`[error] statsd plugin: bind(2) failed: Address already in use`

Despite that error I see that collectd is listening on `0.0.0.0:8125`. My conclusion so far is that getaddrinfo() is returning both `INADDR_ANY` and `in6addr_any` as I have not defined a hostname for statsd.

If I have understood everything correctly the problem is that an error is reported when none exists in practice and I would like to downgrade the ERROR to an INFO if fds_num > 0.

**Comment by moofish32** [comment]
Any update on this issue? I am seeing the same error, but the socket is listening.

**Comment by michaelsalmon** [comment]
I submitted a pr but it didn't make it into any release, I'm not sure why. It's purely cosmetic.

https://github.com/collectd/collectd/pull/1187/files

**Comment by rpv-tomsk** [comment]
Hit similar problem.

I have `/etc/hosts` with:
```
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
```
Also I have `net.ipv6.conf.all.disable_ipv6 = 1` and option `Host localhost` is in `statsd` plugin config.

Collectd was patched with line added:
```
@@ -525,6 +525,7 @@ static int statsd_network_init(struct pollfd **ret_fds, /* {{{ */
     memset(tmp, 0, sizeof(*tmp));
     tmp->fd = fd;
     tmp->events = POLLIN | POLLPRI;
+    INFO("statsd plugin: Listening on [%s]:%s ...", str_node, str_service);
   }
```

With all these, Collectd complaints:

```
[2018-10-18 19:27:10] statsd plugin: Listening on [127.0.0.1]:8125 ...
[2018-10-18 19:27:10] statsd plugin: bind(2) to [127.0.0.1]:8125 failed: Address already in use
```
So, listening was started on first FD, and second FD has failed.
In my case, that is configuration error, and nothing has to be changed in Collectd code (maybe, except adding `INFO()`).

**Comment by rpv-tomsk** [comment]
>Despite that error I see that collectd is listening on 0.0.0.0:8125. My conclusion so far is that 
>getaddrinfo() is returning both INADDR_ANY and in6addr_any as I have not defined a hostname for 
>statsd.

Yes, that is reproducible too. When I set `net.ipv6.conf.all.disable_ipv6=0` and no `Host` option in config file, I have following output in logs:

```
[2018-10-18 19:32:43] statsd plugin: Listening on [0.0.0.0]:8125 (ipv4)...
[2018-10-18 19:32:43] statsd plugin: bind(2) to [::]:8125 (ipv6) failed: Address already in use
```

I think adding `INFO("statsd plugin: Listening on [%s]:%s ...", str_node, str_service);` will be suficient for admin to understand what happens?

**Comment by rpv-tomsk** [comment]
@octo,

We have SO_REUSEADDR on datagram socket in `network.c`. Should we add/use SO_REUSEADDR in the `statsd.c` too? I found no problems using statsd w/o this option, restarts are successfull.

```
  /* allow multiple sockets to use the same PORT number */
  if (setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &yes, sizeof(yes)) == -1) {
    ERROR("network plugin: setsockopt (reuseaddr): %s", STRERRNO);
    return -1;
  }
```

**Comment by octo** [comment]
@rpv-tomsk sounds good to me
