### ISSUE TITLE
DNS:  utils_dns: handle_dns: rfc1035NameUnpack failed with status 3

### ISSUE THREAD

**Issue by TomGudman** [collectd/collectd#1128]
Hi,

Usually the dns plugin works fine but on some of our Centos 6 running with collectd 5.5 we have this constant error message in our log files:

```
utils_dns: handle_dns: rfc1035NameUnpack failed with status 3
```

When looking at [util_dns.c](https://github.com/collectd/collectd/blob/master/src/utils_dns.c#L336) I am not able to understand the meaning of the comment nor why we land in this section. What is RFC1035_MAXLABELSZ aka 63... Why some centos6 are affected and the majority is not?

Cheers

**Comment by rubenk** [comment]
Hey Tom,

That message is indeed a bit cryptic, but my guess is that you are sending or receiving dns requests where the label (so the part between the dots) is longer than 63 characters.

From RFC 1035:

> The labels must follow the rules for ARPANET host names.  They must
> start with a letter, end with a letter or digit, and have as interior
> characters only letters, digits, and hyphen.  There are also some
> restrictions on the length.  Labels must be 63 characters or less.
> 
> For example, the following strings identify hosts in the Internet:
> 
> A.ISI.EDU XX.LCS.MIT.EDU SRI-NIC.ARPA

Does that help?

**Comment by rubenk** [comment]
Closing stale issue.

**Comment by backplanellc** [comment]
I'm having the same issue on two debian squeeze 9.2 boxes running collectd 5.7. Thoughts?

**Comment by qayshp** [comment]
(years later, sorry) I'm also seeing this or something similar on OpenWRT 22.03
```<TIME> <HOST> collectd utils_dns: handle_dns: rfc1035NameUnpack failed with status 3.```
