### ISSUE TITLE
Package collect for IBM AIX and RHEL on PPC

### ISSUE THREAD

**Issue by fbo** [collectd/collectd#1145]
I struggled to install collectd our AIX & Redhat systems on the PPC (Power 7 and 8), as there is no documentation, no clear and precise procedure for the deployment goes smoothly . I wish there was a package for AIX and Redhat complile to facilitate large-scale deployment of this super collectd tools.
Thank you very much !

**Comment by michaelsalmon** [comment]
Did you check the spec files in contrib? For redhat at least the only hard part in the spec file was deciding the arguments to configure.

Building from a clone is harder, especially on RHEL as it packages some files differently.

**Comment by rubenk** [comment]
The packages from EPEL are at least built for ppc64:
http://koji.fedoraproject.org/koji/buildinfo?buildID=664350

**Comment by rubenk** [comment]
One issue is that as far as I know none of us has access to an AIX PPC system. I'd love for that to change.
If you run into specific issues with compiling collectd, let us know and we'll do our best to help. Other than that (with my upstream hat on) we leave packaging to our downstream distributors.
