### ISSUE TITLE
build failure with musl libc due to struct shm_info.used_ids

### ISSUE THREAD

**Issue by ncopa** [collectd/collectd#1147]
With musl libc it fails to build with the error:
```
ipc.c:154:49: error: 'struct shm_info' has no member named 'used_ids'
   ipc_submit_g("shm", "segments", NULL, shm_info.used_ids);
                                                 ^
```

You need to define _GNU_SOURCE on musl libc for the member 'used_ids', probably due to it is not required in POSIX.

I have two different suggestions on how to fix it:
```diff
diff --git a/configure.ac b/configure.ac
index 6ee6e9a..a0e35b6 100644
--- a/configure.ac
+++ b/configure.ac
@@ -49,6 +49,7 @@ AC_PROG_LEX
 AC_PROG_YACC
 PKG_PROG_PKG_CONFIG
 
+AC_GNU_SOURCE
 AC_CHECK_PROG([have_protoc_c], [protoc-c], [yes], [no])
 AC_CHECK_HEADERS([google/protobuf-c/protobuf-c.h],
                  [have_protobuf_c_h="yes"],
```

or:

```diff
diff --git a/src/ipc.c b/src/ipc.c
index 3763f24..b403847 100644
--- a/src/ipc.c
+++ b/src/ipc.c
@@ -32,6 +32,9 @@
 #include "configfile.h"
 
 #if KERNEL_LINUX
+  /* _GNU_SOURCE is needed for struct shm_info.used_ids on musl libc */
+# define _GNU_SOURCE
+
   /* X/OPEN tells us to use <sys/{types,ipc,sem}.h> for semctl() */
   /* X/OPEN tells us to use <sys/{types,ipc,msg}.h> for msgctl() */
   /* X/OPEN tells us to use <sys/{types,ipc,shm}.h> for shmctl() */
```

I can prepare a signed-off patch that you can git am if you tell me which way you prefer.

**Comment by rubenk** [comment]
I can confirm that this fixes the build on musl.
Can you also #define _DEFAULT_SOURCE? Not sure about musl, but glibc is deprecating _GNU_SOURCE.

If you could send a pull request that would be great.

**Comment by ncopa** [comment]
>  Not sure about musl, but glibc is deprecating _GNU_SOURCE.

Where did you get that from? I can not see anything in [documentation](http://man7.org/linux/man-pages/man7/feature_test_macros.7.html) that indicates that _GNU_SOURCE is deprecated.

Are you sure you don't mean _BSD_SOURCE?

I can `#define _DEFAULT_SOURCE` too if you want but I can not see why that would be needed on any system, so I don't know how to explain that in the commit message.

On musl the only effect it has is that it enables _BSD_SOURCE in addition:
```C
#if defined(_DEFAULT_SOURCE) && !defined(_BSD_SOURCE)
#define _BSD_SOURCE 1
#endif
```

**Comment by rubenk** [comment]
Ah yes you're right, I confused _GNU_SOURCE with _BSD_SOURCE.
If you define _BSD_SOURCE and not _DEFAULT_SOURCE, you'll get warnings with glibc (60124c7da3a9fccdc610d804755a5f27398d0951), but that doesn't apply here.
