### ISSUE TITLE
SNMP module doesn't like mismatched column lengths

### ISSUE THREAD

**Issue by nward** [collectd/collectd#1155]
Hi,

I'm not sure if this is strictly a bug in collectd, or if it's a bug in the router I'm talking to (Cisco ASR9000).

Essentially, the ASR9k for some reason returns less entries in the ifInOctets column (and other columns) than the ifIndex/ifDescr etc. columns.

This means that collectd reaches the end of the walk of the ifInOctets column before the end of ifDescr.

Collectd should, I think, check that the index of each requested variable is the same as the ifIndex in the getNextResponse, and if not then ignore the row and not attempt to request the next ifInOctets etc.

In parellel I'm going to work with the vendor to try get this working in a way that it would be more expected to.

If anyone is interested, each TenGigE interface on an ASR9000 has a corresponding `dwdm'  interface, and it's these interfaces that show in ifDescr/ifIndex/ifAdminStatus etc. but not in counters.

I will work on a patch for this myself, but, if anyone has guidance on this it would be appreciated.

**Comment by nward** [comment]
Actually I suspect that this is fixed by 080f01b95a5f6006438e2ffee6ae3d093263d148 - in reading the code it seemed to be the case.. I'll compile the latest version and check.

**Comment by rubenk** [comment]
@nward did you get a change to check if this is fixed?

**Comment by rubenk** [comment]
I'm going to close this issue. Please open a new one if you can reproduce this with the latest version of collectd.
