### ISSUE TITLE
LogLevel debug should act like LogLevel info if debugging not enabled

### ISSUE THREAD

**Issue by timbunce** [collectd/collectd#117]
Currently if debugging isn't enabled (the default for rpm's) then LogLevel debug produced _no output at all_ which is pretty surprising, to me at least.

The docs say "Please note that debug is only available if collectd has been compiled with debugging support." but that doesn't really explain what happens. 

Setting LogLevel debug should should act like LogLevel info if debugging is not enabled.

**Comment by mighq** [comment]
It is little bit confusing. I would appreciate, if the daemon at least told, that debug log level is not available in this build. Then it is straightforward to set the info level in the config file.
