### ISSUE TITLE
Make ping plugin pings gateway by default

### ISSUE THREAD

**Issue by BarthV** [collectd/collectd#1176]
Hi,

Currently we must specify a ip/host to the ping plugin.
What do you think about pinging default gateway (if existing) by default ?

**Comment by rubenk** [comment]
Hi,

I don't think this functionality belongs in Collectd.
There's also the issue that a host can have multiple default gateways, both for IPv4 and IPv6.

You can just specify the IP of your gateway in collectd.conf. If you need to do this on a large scale, best use a configuration management system.
