### ISSUE TITLE
rrdtool: metric names are cut unnecessarily

### ISSUE THREAD

**Issue by bubenkoff** [collectd/collectd#1194]
Looks like rrd file name generated by rrdtool plugin is limited to 71 character
Looking at the C code of the plugin i see 512 as the limit of the file name
what goes wrong and where then?

**Comment by rubenk** [comment]
Perhaps a limitation in librrd or rrdtool itself?

**Comment by bubenkoff** [comment]
Unfortunately it's by design :(
https://collectd.org/wiki/index.php/Naming_schema

**Comment by bubenkoff** [comment]
Each field has a fixed maximum length. Currently this limit is 63 characters, but may be extended in the future.
