### ISSUE TITLE
collectd-core 5.5.0 and varnish 4.0.3

### ISSUE THREAD

**Issue by Cactusbone** [collectd/collectd#1230]
Hello !
I'm using `varnish 4.0.3-2~trusty` (from http://repo.varnish-cache.org/ubuntu/ trusty varnish-4.0 )
and `collectd-core 5.5.0.169.g9ad5eef-1~trusty` (from http://pkg.ci.collectd.org/deb/ trusty collectd-5.5 )

and it seems like activating the collectd varnish plugin makes collectd kinda crash (could not get a core dump though :/)

starting manually `collectd -f`
I got `collectd: relocation error: /usr/lib/collectd/varnish.so: symbol VSC_Setup, version LIBVARNISHAPI_1.0 not defined in file libvarnishapi.so.1 with link time reference`

also activating CollectVSM (new data only available in varnish 4) in the plugin configuration raises a warning.

which looks like it have been fixed in https://github.com/collectd/collectd/issues/618

So i was wondering if the CI was building against varnish 3 and so i wasn't getting the "latest" version ?

changelog says that collectd 5.5 ships with varnish 4 compatibility. 

any tips ?

**Comment by mfournier** [comment]
Yes, unfortunaltely trusty ships with varnish 3.x, so this version of libvarnishapi is used when building these packages.

You need to rebuild the package on trusty against the correct varnish version. Fortunately this shouldn't be too difficult:
* upgrade libvarnishapi-dev to the version from repo.varnish-cache.org
* `apt-get build-dep collectd`
* `dget -u http://pkg.ci.collectd.org/deb/dists/trusty/collectd-5.5/binary-amd64/collectd_5.5.0.169.g9ad5eef-1~trusty.dsc`
* `cd collectd-5.5.0.169.g9ad5eef`
* `dpkg-buildpackage`

Have fun !

**Comment by jazzzz** [comment]
Thanks! I just had to replace `apt-get build-dep collectd` with `mk-build-deps --install debian/control` after `cd collectd-5.5.0.169.g9ad5eef`.

**Comment by Cactusbone** [comment]
Thanks a lot !
