### ISSUE TITLE
TypesDB behavior is not intuitive.

### ISSUE THREAD

**Issue by jamtur01** [collectd/collectd#1241]
In the collectd configuration I don't define the TypesDB option and rely on the default. If I add a custom plugin and use the TypesDB option in its configuration, for example:

```
TypesDB "/usr/share/collectd/docker-collectd/dockerplugin.db"
LoadPlugin python

<Plugin python>
  ModulePath "/usr/share/collectd/docker-collectd"
  Import "dockerplugin"

  <Module dockerplugin>
    BaseURL "unix://var/run/docker.sock"
    Timeout 3
  </Module>
</Plugin>
```
It overrides the default and ignores the core TypesDB file.

This means I need to update my configuration to explicitly add:

```
TypesDB "/usr/share/collectd/types.db"
```

This feels odd to me and I'd recommend the default not get overriden if you specify a custom TypesDB. (I am conscious this default isn't ideal either but I can't see a use case where someone wouldn't want to always use the core types.db file?)

**Comment by rubenk** [comment]
I agree, and this has bitten me as well recently.

**Comment by octo** [comment]
Won't fix: this makes it impossible to use custom types only, so such a change is not backwards compatible.

**Comment by jamtur01** [comment]
Thanks. Then I'd recommend a docs update explaining that the behavior is not what you'd expect.

**Comment by octo** [comment]
That's a fair point; doc update coming up.
