### ISSUE TITLE
df-plugin fails with btrfs and ReportInodes true

### ISSUE THREAD

**Issue by bemeyert** [collectd/collectd#1243]
Hi all,

Allthough we use Collectd 5.4.2, this problem probably affects 5.5. too. AFAIK there is no diff between `df.c` from 5.4 and 5.5.

When the df plugin is running with `ReportInodes` on a host with a Btrfs-partition it just fails with the error:
```
read-function of plugin `df' failed. Will suspend it for 20.000 seconds. 
```
My wild guess is that's because Btrfs doesn't report inode usage (at least not via df command):
```
[root@host collectd.d]# df -i /var/lib/docker                   
Filesystem                    Inodes IUsed IFree IUse% Mounted on
/dev/mapper/vg01-docker--data      0     0     0     - /var/lib/docker
```

To work around this problem one could either ignore the partition, e.g.:
```
<Plugin "df">
  MountPoint "/var/lib/docker"
  IgnoreSelected true
```
or no longer measure inodes via `ReportInodes false`.

Since both are not quite optimal, it would be nice if you could look into this.

Cheers

**Comment by mfournier** [comment]
This issue was fixed by #1096 and will be in the 5.4.3 and 5.5.1 releases.

**Comment by bemeyert** [comment]
@mfournier Thanks for the info.When do you think is the release?

**Comment by mfournier** [comment]
@bemeyert no ETA yet. The patch should be fairly straightforward to backport to 5.4.2 though, or alternatively you can give the [nightly builds](https://github.com/collectd/collectd-ci/blob/master/README.md) a try.

**Comment by bemeyert** [comment]
@mfournier Ta. Will try the patch. Cheers
