### ISSUE TITLE
collectd master fails to build on OSX

### ISSUE THREAD

**Issue by rubenk** [collectd/collectd#1247]
```
  CC       collectd_tg-collectd-tg.o
../../collectd/src/collectd-tg.c:107:7: error: implicit declaration of function 'clock_gettime' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  if (clock_gettime (CLOCK_MONOTONIC, &ts) != 0)
      ^
../../collectd/src/collectd-tg.c:107:22: error: use of undeclared identifier 'CLOCK_MONOTONIC'
  if (clock_gettime (CLOCK_MONOTONIC, &ts) != 0)
                     ^
2 errors generated.
make[3]: *** [collectd_tg-collectd-tg.o] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1
```

**Comment by maikelvdh** [comment]
Reported this directly on the source file earlier, is there any plan to solve this? For now I have added workaround locally to get it compiling ie defining CLOCK_REALTIME and CLOCK_MONOTONIC and an implementation of clock_gettime()

**Comment by octo** [comment]
Yeah, we had to fix the same issue with *clock_gettime(3)* in the daemon itself, too. It sucks that Mac OS/X is the only UNIX I know that doesn't have this function :(

**Comment by rubenk** [comment]
@octo Thanks for the fix, but you missed the declaration of gettimeofday:

```
collectd-tg.c:119:7: error: implicit declaration of function 'gettimeofday' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  if (gettimeofday (&tv, /* timezone = */ NULL) != 0)
      ^
1 error generated.
make[3]: *** [collectd_tg-collectd-tg.o] Error 1
```

**Comment by intensifi** [comment]
I'm not sure how helpful this is, but I have a fix for this issue on Mac OS X in pending pull request #1240.  It was something I needed to fix when I built the fifo plugin on Mac OS X

**Comment by rubenk** [comment]
Oh, I think just #including `<sys/time.h>` is enough.

**Comment by mfournier** [comment]
Do you actually have a Mac where you can test this @rubenk ? Would you mind submitting a pull-request with this fix (if it's indeed just this include which is missing) ? Thanks !

**Comment by rubenk** [comment]
@mfournier, sure, just tested this on my Mac.

**Comment by octo** [comment]
@rubenk meh, thanks for fixing!
