### ISSUE TITLE
Is it true that with the collectd SNMP plugin, Interval can't be less than 10?

### ISSUE THREAD

**Issue by zack-perry** [collectd/collectd#1248]
I have been using the SNMP plugin of collectd 5.4.0 on a server running CentOS 6.7 x86_64 to monitor two Arista 7280SE-68 switches and two QCT LY8 switches.

Recently, to my surprise, I found that anytime I set the Interval value for the SNMP block from 10 seconds to something less, e.g. 2 seconds, the relevant whisper files never show any value (`whisper-fetch --pretty tx|rx.wsp`). But once I reset the Interval back to 10, things are back to normal.  I am puzzled by this and would love to know why.  Any hints/pointers are much obliged.

Relevant `/etc/collectd.conf`:

    [...]
    <LoadPlugin snmp>
          Interval 10
    </LoadPluging>
     [...]
    <Plugin snmp>
       <Data "ifmib_if_octets64">
          Type "if_octets"
          Table true
          Instance "IF-MIB::ifName"
          Values "IF-MIB::ifHCInOctets" "IF-MIB::ifHCOutOctets"
       </Data>
       <Host "top-quanta-221">
          Address "192.168.10.221"
          Version 2
          Community "..."
          Collect "ifmib_if_octets64"
       </Host> 
       <Host "top-arista-231">
          Address "192.168.10.231"
          Version 2
          Community "..."
          Collect "ifmib_if_octets64"
       </Host> 
    </Plugin>
    [...]

**Comment by falzm** [comment]
Based on your observations this looks like a whisper-related issue, this probably doesn't have anything to do with collectd itself. Try to use another write backend such as CSV, and check if values are output according to the frequency configured?

**Comment by zack-perry** [comment]
Thanks for the suggestion. If it were a whisper-related issue, why other plugins, such as CPU frequency, are working well with even with Interval set at 1 second?

Regardless, I will try out your suggestion and circle back.

**Comment by falzm** [comment]
Other lead: is it possible that your switches take a long time to respond to SNMP requests? I've experienced this with some appliances – especially busy ones such as core routers –, as the SNMP daemon is running in low priority, and can take up to seconds to process requests.

**Comment by rubenk** [comment]
@zack-perry where you able to test @falzm suggestion?

**Comment by calebcall** [comment]
I know this is closed (popped up on search for another issue) but this issue is probably due to the whisper retention.  It depends on what the storage-schema is setup to define these as.  If it's defined as data every 10s, even if you shove it in every second, it'll only keep the last value for each 10s period.  You would need to resize (whisper-resize) the whisper files to get them to have a new retention.
