### ISSUE TITLE
ValuesPercentage param in df plugin not reporting data unless FSType rootfs is ignored

### ISSUE THREAD

**Issue by erikanderson** [collectd/collectd#1255]
I was having an issue with certain mount points not reporting data from collectd. I thought it was because the partition was bound to another (ie `/media on /bind type none (rw,bind)`) and that might still be part of the problem. However I was able to fix it for now by adding the following to my config: 

```   
# ignore rootfs; else, the root file-system would appear twice, causing
# one of the updates to fail and spam the log
FSType rootfs
IgnoreSelected true 
```

I would like to suggest this be added to the df plugin page as a requirement.

**Comment by erikanderson** [comment]
It turns out that ignoring rootfs was not the solution. 

Setting ReportInodes to false actually resolved the issue with the bound filesystem: 

` ReportInodes true `

**Comment by szop85** [comment]
Any idea how to get both inodes and percentage/volume values? Any experience with other collectd versions?

Cheers

**Comment by erikanderson** [comment]
I am actually going to close this issue and make another one with more information (and research)
