### ISSUE TITLE
write_riemann plugin may cause many NaN values for cpu-idle 

### ISSUE THREAD

**Issue by kamalakarv** [collectd/collectd#1267]
Collectd version : 5.5
OS : Ubuntu 12.04 

write_riemann is pushing metric value as NaN  for cpu-idle and for other metrics? it is a bug ?
#riemann.codec.Event{:host xxxx :service cpu-average/cpu-idle, :state critical, :description nil, :metric NaN, :tags #{collectd}, :time 1441361259, :ttl 20.0, :ds_index 0, :ds_name value, :ds_type derive:rate, :type_instance idle, :type cpu, :plugin_instance average, :plugin cpu}

Your help appreciated

**Comment by mfournier** [comment]
NaN values are typically seen with counter/derive types and `StoreRates` enabled. collectd needs 2 values to calculate a rate. In situations where only one is available (for example at startup time) the value results in a NaN.

**Comment by mfournier** [comment]
See #1174 for arguments around NaN values.
