### ISSUE TITLE
bind plugin: timezone offset

### ISSUE THREAD

**Issue by tmalkowski** [collectd/collectd#1268]
I'm having the same issue with the bind plugin as described here: http://mailman.verplant.org/pipermail/collectd/2011-June/004593.html
http://mailman.verplant.org/pipermail/collectd/2012-February/004929.html

Basically, the bind statistics-channel output uses UTC date/time values, but the bind plugin assumes this is in local time, so the end result is all data appearing to be (for me) 5 hours too late. (US/Central timezone)

Example from statistics-channel XML output from 11:10AM:

```
        <current-time>2015-09-09T16:10:39Z</current-time>
```

This is incorrectly interpreted by collectd as 4:10PM CDT.

I built from master and the issue persists, I've reviewed the changes to bind.c since v5.4.2 (where I discovered the bug), and didn't notice any significant changes to the time-related code, so I wanted to verify there wasn't some other workaround I'd missed and make sure the bug report got filed if it was in fact still a bug and not some obscure flag/config I needed to set somewhere.

---

For what it's worth, setting ParseTime to false does resolve the issue, sort of, but I've noticed my metrics are slightly off due to this using the system time instead of what BIND is reporting. I'd prefer to use BIND's own timestamps if possible, since that's accurate.

**Comment by tmalkowski** [comment]
Just thought I'd update this -- issue persists when building from master as well.

**Comment by tmalkowski** [comment]
Found another thread that seems to identify this issue as well: http://mailman.verplant.org/pipermail/collectd/2011-June/004593.html

**Comment by velotraveler** [comment]
I'm also having this issue.  Here's a possible patch.  Ideally we would call tzset() in the global context just once instead of every time we get the data from bind, but for demonstration purposes it should work:

 $ diff bind.c bind2.c
0a1
> 
432c433,434
<   *ret_value = mktime(&tm);
---
>   tzset();
>   *ret_value = mktime(&tm) - timezone;

**Comment by octo** [comment]
Hi @velotraveler,

after reading the POSIX spec for a while, I think that there is no way to teach `strptime()` to honor the timezone information ("Z") provided by BIND. The returned `struct tm` is assumed to contain local time by `mktime()`, causing this offset.

On the bright side, according to POSIX:
> Local timezone information shall be set as though mktime() called tzset().
So it appears that after calling `mktime()` `timezone` should be set to the timezone information used by `mktime()` to convert from "local time" to UTC, so using that same information to undo the localization appears sane to me. If I understand the spec correctly, the separate call to `tzset()` is not necessary.

Calling `tzset()` only once would not work, as *collectd* tends to run for a long time and you'd get wrong timestamps when entering or leaving DST.

Would you be willing to send a pull request with your change? It'd be much appreciated!

Best regards,
—octo

**Comment by velotraveler** [comment]
It's a safe bet that the timestamps BIND reports via its statistics server are always in UTC.  I followed the Unix code back to gettimeofday(), which is always in UTC, and there does not seem to be any attempt to localize it. The Windows code uses GetSystemTimeAsFileTime() which is also documented as returning the time in UTC.

After a close reading of the Linux mktime() man page, I think you're right that tzset() is optional because mktime() is probably using it behind the scenes, but the code will be more readable if we leave it in.

I will submit a pull request, but I don't have the resources to give it a full test.

**Comment by octo** [comment]
Fixed by #2265

**Comment by octo** [comment]
Reopening because by trying to fix this we introduced the following build issue on FreeBSD:

```
src/bind.c: In function 'bind_xml_read_timestamp':
src/bind.c:433:28: error: invalid operands to binary - (have 'time_t' and 'char * (*)(int,  int)')
   *ret_value = mktime(&tm) - timezone;  /* fix strptime() misinterpretation */
```

**Comment by octo** [comment]
POSIX says `timezone` is an `extern long`: http://pubs.opengroup.org/onlinepubs/9699919799/functions/tzset.html

**Comment by octo** [comment]
My favorite libc / BSD guru, @EdSchouten, has pointed me to `strptime()` / `timegm()` to do that string to `time_t` conversion. Thank you!

**Comment by octo** [comment]
Cherry-picked 23963a8b9fae668376dd55917afbb38d759dd1d0 into the *collectd-5.6* branch as 938d6380a94cd898a28c5ad1a37c19e7bd47db4c
