### ISSUE TITLE
Python Collectd module always uses the system python version always. 

### ISSUE THREAD

**Issue by sbose78** [collectd/collectd#1271]
What is the procedure for running Python modules with a version different than that of the system version.
Example, my system python version is 2.6
However I wish to use Python2.7 for running the customer modules written in Python.

Please assist.

**Comment by appetito** [comment]
you can compile collectd with any python with ./configure --with-python=/path/to/your/binary/python

**Comment by torrencj** [comment]
`configure: WARNING: unrecognized options: --with-python`
?

**Comment by rpv-tomsk** [comment]
`./configure --help`
