### ISSUE TITLE
Unable to log metrics to file

### ISSUE THREAD

**Issue by willemdh** [collectd/collectd#1272]
I've been trying all sorts of things, but I seem to be unable to get collectd working properly on CentOS 7. The goal is to try make it write metrics to InfluxDB 0.9.4. As I was not able to get that working, I tried configuring a logfile /var/log/collectd , but whatever I do, this logfile is not created.

This is my current config:

Hostname    "servername"
BaseDir     "/var/lib/collectd"
PIDFile     "/var/run/collectd.pid"
PluginDir   "/usr/lib64/collectd"
TypesDB     "/usr/share/collectd/types.db"

AutoLoadPlugin true
CollectInternalStats true

Interval     10

MaxReadInterval 86400
Timeout         2
ReadThreads     5
WriteThreads    5

LoadPlugin syslog
LoadPlugin logfile

<Plugin logfile>
        LogLevel info
        File "/var/log/collectd.log"
        Timestamp true
</Plugin>

<Plugin syslog>
        LogLevel info
</Plugin>

LoadPlugin cpu
LoadPlugin interface
LoadPlugin load
LoadPlugin memory
LoadPlugin network

<Plugin network>
        <Server "127.0.0.1" "8096">
                Interface "ens32"
        </Server>
</Plugin>

Include "/etc/collectd.d"

**Comment by rubenk** [comment]
Can you try what happens if you do not load the syslog plugin? I'm not sure if you can log to both syslog and a file.

Just another thought, are you running SELinux in enforcing mode? Any AVCs?

**Comment by willemdh** [comment]
Thanks for your answer Ruben.

I made a backup and cleaned up my collectd.conf for easier reading. Apparently the system was indeed in selinux enforcing mode. I set it to disabled and removed the syslog plugin. I do get some info in the collect.log file:

[2015-09-21 11:09:49] Initialization complete, entering read-loop.
[2015-09-21 11:29:39] Exiting normally.
[2015-09-21 11:29:39] collectd: Stopping 5 read threads.
[2015-09-21 11:29:39] rrdtool plugin: Shutting down the queue thread. This may take a while.
[2015-09-21 11:29:39] collectd: Stopping 5 write threads.
[2015-09-21 11:29:39] Initialization complete, entering read-loop.

I'm still not receiving data in InfluxDB. I'll debug a bit further and will update this issue asap.

**Comment by rubenk** [comment]
This is strange, it looks like something is stopping collectd at 11:29:39.
Which rpm are you using? The one from EPEL? How are you starting collectd? Can you check that you have only a single collectd process running?

**Comment by willemdh** [comment]
Hey this is because I restarted it manually, as I made some changes in the config. I think I got it working now. I see several metrics arriving in InfluxDB after changing the port from 8096 to 25826.
My collectd config looks liek this now:

Hostname    "servername"
#FQDNLookup   true
BaseDir     "/var/lib/collectd"
PIDFile     "/var/run/collectd.pid"
PluginDir   "/usr/lib64/collectd"
TypesDB     "/usr/share/collectd/types.db"
AutoLoadPlugin true
CollectInternalStats true
Interval     10
MaxReadInterval 86400
Timeout         2
ReadThreads     5
WriteThreads    5
#WriteQueueLimitHigh 1000000
#WriteQueueLimitLow   800000
#LoadPlugin syslog
LoadPlugin logfile
#LoadPlugin log_logstash

<Plugin logfile>
        LogLevel info
        File STDOUT
        File "/var/log/collectd.log"
        Timestamp true
        PrintSeverity false
</Plugin>

#<Plugin log_logstash>
#       LogLevel info
#       File "/var/log/collectd.json.log"
#</Plugin>

#<Plugin syslog>
#       LogLevel info
#</Plugin>

LoadPlugin cpu
LoadPlugin interface
LoadPlugin load
LoadPlugin memory
LoadPlugin network
LoadPlugin uptime

<Plugin network>
Server "127.0.0.1" "25826"
#       <Server "127.0.0.1" "8096">
#               Interface "ens32"
#       </Server>
</Plugin>

Include "/etc/collectd.d"

And I also changed the port in the influxdb config file:

[collectd]
  enabled = true
  port = 25826
  # bind-address = ""
  database = "db_grafana01"
  typesdb = "/usr/share/collectd/types.db"

So it could be related to changing the port number or going from 

<Plugin network>
      <Server "127.0.0.1" "8096">
               Interface "ens32"
      </Server>
</Plugin>

to

<Plugin network>
Server "127.0.0.1" "25826"
</Plugin>

Grtz and thanks alot for the help!! I'm going to close this issue.

Willem

**Comment by rubenk** [comment]
Ah, great. Just a tip for your next Github issue, you can escape config blocks in Github markdown with triple quotes: \```

This prevents Github from trying to parse your config files and makes issues easier to follow ;)

**Comment by willemdh** [comment]
Well I was just reading on how to that and already updated my answer. Thanks again!

**Comment by rubenk** [comment]
Perfect, thanks!

**Comment by mwaeckerlin** [comment]
I had the same problem and I can confirm: It is the port and you need to change it only in collectd.conf (not in grafana):

```xml
<Plugin network>
  Server "influxdb" "25826"
</Plugin>
```
