### ISSUE TITLE
Collectd Timezone Problem

### ISSUE THREAD

**Issue by hsalahi** [collectd/collectd#1273]
Hi,
I'm collecting system metrics from vagrant box using Collectd and sending it to InfluxDB on my host machine. As I query the data in InfluxDB, it returns data with UTC time while I'm using  local time CEST on both vm and host causing +2 hours offset. I'm just a newbie. Any idea!?

Thanks,

**Comment by rubenk** [comment]
Hi,

Collectd always uses UTC timestamps. You'll have to convert the metrics to local time in InfluxDB.

Please use the [collectd mailing list](http://mailman.verplant.org/listinfo/collectd) or the [#collectd IRC channel](https://webchat.freenode.net/?channels=#collectd).
We'd like to keep the github issue tracker for bugreports and patch reviews.
