### ISSUE TITLE
 Can I use write_kafka plugin to sent data to kafka , when I use a server-client mode collectd?

### ISSUE THREAD

**Issue by nitreason** [collectd/collectd#1278]
Hi,
I have two linux server(A and B)and one windows server(C). A was defined as the collectd server, B and C were defined as the client.
And I configured the write_kafka plugin on host A to send data to kafka , I found that only the data from host A was send to kafka,
the data from host B and C didn't found in kafka.
Is that any issue here ?
My configuration of write_kafka plugin is as follow.

collectd.conf on host A:

\<Plugin network\>

        Listen " IP adress of Server A" "25826"

\</Plugin\>

\<Plugin write_kafka\>
  Property "metadata.broker.list" "CentOS01:9092"
  \#\<Topic "collectd"\>
  \<Topic "collectd1"\>
    Format Graphite
    \#GraphitePrefix "myprefix"
    \#GraphitePostfix "mypostfix"
    GraphiteEscapeChar ","
  \</Topic\>
\</Plugin\>

collectd.conf on host B:
\<Plugin network\>
        Server "IP adress  of  Server A" "25826"
\</Plugin\>

Please help.Thanks.

**Comment by chrifs** [comment]
I have a similar setup and it works perfectly... I suspect a network/firewall issue. Try to debug the collectd server with the unix socket plugin and verify that packets were received from B & C.
```shell
collectdctl listval
```

**Comment by nitreason** [comment]
Hi, @chrifs 
I installed a influxdb on server A , and the config file as follow:
>[collectd]
>  enabled = true
>   bind-address = "Server A:25826"
>   database = "collectd"
>   typesdb = "/opt/collectd/share/collectd/types.db"

The influxdb had the data of Server B. So I don`t think there has network or firewall issues.
I also used the write_kafka plugin to write data source Server A and B , and  there was only data from Server A .
Don`t you have the same problem ? Is there any issues of my configuration ?

**Comment by chrifs** [comment]
@nitreason OK. It seems that there is no network/firewall issues...

Other points :

* In your ``` write_kafka ``` configuration you have used a hostname (not an ip , 127.0.0.1) at 
``` Property "metadata.broker.list"  ```. Can you resolve the hostname on server A ? It should be "CentOS01" after issuing the command ``` hostname ```.

* Do you have any ``` <Chain "PostCache"> ``` config ? If you have such config you should explicitly add the ``` write_kaka ``` as  a default target. 
```
<Target "write">
    Plugin "write_kafka/collectd1"
</Target>
```

By the way, have you looked at the collectd log file ? It should mention if there is any issues...

**Comment by nitreason** [comment]
Hi @chrifs , 
I restart the collectd process and then have a test with this order : "/opt/kafka/bin/kafka-console-consumer.sh --zookeeper localhost:2181 --topic collectd".  And  the config file  informations and collectd.log informations as following. Please help.Thank you.

system version:
Server A:
[root@TEST etc]# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.1 (Maipo)
[root@TEST etc]# 
Server B：
[root@TEST2 ~]# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.1 (Maipo)
[root@TEST2 ~]# 

Install products on the server:
Server A： collectd 5.5.0 +kafka 0.8+librdkafka
Server B:  collectd 5.5.0

configurations:
Server A：
collectd.conf:

#######Global

Hostname    "TEST"
BaseDir     "/opt/collectd/var/lib/collectd"
PIDFile     "/opt/collectd/var/run/collectd.pid"
PluginDir   "/opt/collectd/lib/collectd"
#######kafka
LoadPlugin write_kafka
……
<Plugin write_kafka>
  Property "metadata.broker.list" "localhost:9092"
  <Topic "collectd">
    #Format JSON
    Format Graphite
  </Topic>
</Plugin>
……

########network
<Plugin network>
Listen "10.1.1.101" "25826"
</Plugin>

########logfile
LoadPlugin logfile
<Plugin "logfile">
  LogLevel "info"
  File "/var/log/collectd.log"
  Timestamp true
</Plugin>

Server B:
collectd.conf:
……
Hostname    "TEST2"
……
<Plugin network>
Server "10.1.1.100" "25826"
</Plugin>
……

test:
[root@TEST ~]# 
[root@TEST ~]#  /opt/kafka/bin/kafka-console-consumer.sh --zookeeper localhost:2181 --topic collectd
TEST.cpu-0.cpu-user 215907 1444964905
TEST.cpu-0.cpu-system 72858 1444964905
TEST.cpu-0.cpu-wait 16732 1444964905
TEST.cpu-0.cpu-nice 335 1444964905
TEST.cpu-0.cpu-interrupt 9 1444964905
TEST.cpu-0.cpu-softirq 5509 1444964905
TEST.cpu-0.cpu-steal 0 1444964905


[root@TEST log]# tailf collectd.log
[2015-10-20 10:16:39] Exiting normally.
[2015-10-20 10:16:39] collectd: Stopping 5 read threads.
[2015-10-20 10:16:39] collectd: Stopping 5 write threads.
[2015-10-20 10:16:50] bind: Cannot assign requested address
[2015-10-20 10:16:50] network plugin: network_config_add_server: sockent_server_listen failed.
[2015-10-20 10:16:50] Initialization complete, entering read-loop.
[2015-10-20 10:16:50] write_kafka plugin: created KAFKA handle : rdkafka#producer-0
[2015-10-20 10:16:50] write_kafka plugin: handle created for topic : collectd
[2015-10-20 10:16:50] Initialization complete, entering read-loop.
[2015-10-20 10:16:50] write_kafka plugin: created KAFKA handle : rdkafka#producer-0
[2015-10-20 10:16:50] write_kafka plugin: handle created for topic : collectd
~                                                                                  

[root@TEST ~]# tcpdump -i eno16777736 -p -n -s 1500 udp port 25826
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eno16777736, link-type EN10MB (Ethernet), capture size 1500 bytes
15:31:06.672683 IP 10.1.1.101.36803 > 10.1.1.100.25826: UDP, length 1317
……
……

**Comment by chrifs** [comment]
Hi, @nitreason 

I will suppose that there is a typo error at the **server B** configuration ``` server "10.1.1.100" "25826" ``` because it MUST be  ``` server "10.1.1.101" "25826" ```. (*The same IP/port as Server A*)

Otherwise, I would highly recommend that you install the [collectd unix sock plugin](https://collectd.org/wiki/index.php/Plugin:UnixSock) in the server A so you can be sure that the server B metrics are really present in the server A global cache. After installation you can use this snippet to debug : 
``` echo 'LISTVAL' | nc -U /var/run/collectd-unixsock  ```

You should get something like this if server B metrics are present 
``` 
TEST2/cpu-0/user
TEST2/cpu-0/system
```

Note that my setup is CentOS 6.5 for both, clients and server, and I use JSON as collectd format in the write_kafka plugin.

**Comment by nitreason** [comment]
Hi,@chrifs 
I used the collectd unix sock plugin, but I don't get  the informations of server TEST2  from  Server A.
I use 'echo 'LISTVAL' | nc -U /var/run/collectd-unixsock', and get messages from server A  as follow:
[root@TEST etc]# echo 'LISTVAL' | nc -U /opt/collectd/var/run/collectd-unixsock
27 Values found
1445481239.060 TEST/cpu-0/cpu-idle
1445481239.060 TEST/cpu-0/cpu-interrupt
1445481239.060 TEST/cpu-0/cpu-nice
…………
…………
It means  that Server B didn't send any information to Server A?

**Comment by chrifs** [comment]
@nitreason 

YES. The Server A is **NOT** receiving packets from Server B.

Excluding the fact that there is a firewall issue in Server A, debugging should be at the networking level in Server B (tcpdump, collectd log file, system log, ip address in the collectd plugin network, SELinux, etc.).

**Comment by bbhandari** [comment]
I am trying to activate the write_kafka plugin. But i am getting write_kafka . . . . . no (dependency error) error. I have also installed the librdkafka-0.8.6-1.el7.remi.x86_64.rpm package. Any ideas ?

**Comment by rubenk** [comment]
@bbhandari you're probably missing the development headers. They rpm is  probably called something like rdkafka-devel.

Having said that, please don't hijack someone elses issue for your unrelated problem, and open a new one instead.
