### ISSUE TITLE
dbi plugin DB2 database

### ISSUE THREAD

**Issue by xneo64** [collectd/collectd#1280]
Has anyone had any success with using the dbi plugin to pull data from IBM DB2 databases? Currently evaluating options to pull some metrics from said database (exec, dbi or java connector plugins) - and there isn't much documentation to be found on the libdbi project page with respect to DB2.

**Comment by kalebwalton** [comment]
Would love to hear response to this one. We'll be facing this very soon :)

**Comment by rubenk** [comment]
Hi,

I guess not many people use DB2 here. I don't see any reason why the dbi plugin wouldn't work with it though, thanks to libdbi it should be reasonably database-agnostic.

I guess all I can say is try it :) Please let us know if you encounter any issues in the dbi plugin.
