### ISSUE TITLE
The processes plugin should warn that the length of the process title is limited.

### ISSUE THREAD

**Issue by tomprince** [collectd/collectd#1284]
On linux, at least, the process title can be up to 15 characters (plus a terminating `\0`). I spent some time confused as to why my processes weren't being detected by the plugin.

Or, better, would be if the plugin would correctly detect longer-named processes (based on the basename of the program in the command-line maybe?)

**Comment by mfournier** [comment]
@tomprince wouldn't the `ProcessMatch` option work for you ?

But yes, I agree you shouldn't have to waste time figuring out why long process names don't get matched by collectd. Thanks for reporting this problem !

**Comment by tomprince** [comment]
I think that is what I ended up doing, once I realized what was going on. Thanks.

**Comment by mfournier** [comment]
@tomprince, would you mind taking a look at #1508 ? Thanks !
