### ISSUE TITLE
Trust pkg-config for varnish header files

### ISSUE THREAD

**Issue by ingvarha** [collectd/collectd#1299]
When building collectd's varnish plugin, trust pkg-config's output, that is, do not prefix header files with "varnish/".

This is necessary to build with varnishapi in locations not matching /some/include/dir/varnish, like varnish-plus:

$ pkg-config --cflags varnishapi
-I/usr/include/varnish-plus

**Comment by ingvarha** [comment]
Suggested patch:

http://users.linpro.no/ingvar/collectd/5.5.0/collectd-5.5.0.trust_varnishapi_from_pkg-config.patch

Best regards,
Ingvar Hagelund

**Comment by mfournier** [comment]
Sounds reasonable @ingvarha, thanks !

I'm a bit worried this might have side effects on some of the older distros we're trying to support. Would you mind turning your patch into a pull-request so that our CI system can pick it up and check this point ? Thanks a lot !

**Comment by ingvarha** [comment]
Seems like this was already fixed in commit ec2e074f .

**Comment by mfournier** [comment]
Great, so pending the next release you'll have to build from the master or collectd-5.5 branch.

Thanks !
