### ISSUE TITLE
nfs plugin: Unexpected number of fields for NFSv4 client statistics: 48

### ISSUE THREAD

**Issue by giovtorres** [collectd/collectd#1304]
I saw that b2748f1 fixed field lengths of 42 or 44, but I started getting this entry in the logfile after upgrading from 5.4.1 to 5.5.0 on CentOS 6.7 x86_64.

Here is the output from _/proc/net/rpc/nfs_:

```
# cat /proc/net/rpc/nfs 
net 0 0 0 0
rpc 11829 25 11829
proc2 18 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
proc3 22 0 7875 60 1655 1578 24 416 17 11 0 0 0 11 0 3 0 18 157 0 2 1 0
proc4 48 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
```

**Comment by rquin** [comment]
I've just discovered the same thing with CentOS 6.8 and collectd 5.5.0.

# cat /proc/net/rpc/nfs
net 0 0 0 0
rpc 654228537 4 654240309
proc2 18 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
proc3 22 0 302582048 946937 28836249 66802503 409695 90157357 155742898 4375066 5716 3102 0 1144298 0 3113139 327 0 101 112450 14 7 0
proc4 48 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

**Comment by ConiKost** [comment]
Any news on this? I am also hitting that message :/

Jul 17 11:17:00 [collectd] nfs plugin: Unexpected number of fields for NFSv4 client statistics: 60.

**Comment by rquin** [comment]
I gave up and made an exec.

**Comment by Poil** [comment]
I use this from many years, better than an exec: 
https://github.com/Poil/Collectd-Plugins/blob/master/nfsv4.py 
(https://github.com/Poil/Collectd-Plugins/blob/master/nfsv4.conf)


Le 18/07/2017 à 21:44, rquin a écrit :
