### ISSUE TITLE
Write_kafka plugin isn't working on Ubuntu 12

### ISSUE THREAD

**Issue by shaharharap** [collectd/collectd#1310]
we are not able to use Collectd 5.5 on Ubunto 12.04 with Write kafaka
after installing the collectd and manually  installed librdkafka 
we got this in the log :   collectd[3040]: Available write targets: [none]

**Comment by octo** [comment]
Hi @shaharharap, I'm very sorry that you're having difficulties getting the *write_kafka plugin* up and running, but with virtually no information at hand there is nothing we can contribute to the resolution of this problem. Sorry.

**Comment by pentium10** [comment]
what was the issue here? How did you started to get these issues with RRDTool
