### ISSUE TITLE
Download: RPM Packages includes broken link

### ISSUE THREAD

**Issue by tbielawa** [collectd/collectd#1312]
Under the **RPM Packages** heading on the downloads page [0] there is a link to the collectd package overview page on the Fedora Package Database system [1]. Recently the package database system was overhauled, and as such the old direct links to packages no longer function.
## Expected Results

Clicking the [fedora's package database](https://admin.fedoraproject.org/pkgdb/acls/name/collectd) link brings you to the package overview page.
## Observed Results

Clicking the [fedora's package database](https://admin.fedoraproject.org/pkgdb/acls/name/collectd) link brings you to a `404 Not Found Page`.
## Fix

The link in reference [0](below) needs to be updated to point to the new package database landing page for collectd. The correct URL is given below:
- https://apps.fedoraproject.org/packages/collectd
## References

[0] https://collectd.org/download.shtml#rpm 
[1] https://admin.fedoraproject.org/pkgdb/acls/name/collectd

**Comment by rubenk** [comment]
We should just remove that whole RPM section, since collectd has been in distros and installable with yum / zypper / dnf for ages.

**Comment by octo** [comment]
SGTM, I'll look into that.

**Comment by rubenk** [comment]
Alternatively, the canonical url for the Fedora / EPEL packages, with build status, bug tickets etc, is https://bugz.fedoraproject.org/collectd

**Comment by octo** [comment]
Oh, I updated the page bug forgot to update the issue. Should be fixed now.
