### ISSUE TITLE
NotificationExec: can I pass arguments?

### ISSUE THREAD

**Issue by blysik** [collectd/collectd#1313]
I'm trying to setup NotificationExec.  Is it possible to have that executed notification program get arguments?  for example:
```
LoadPlugin exec
<Plugin exec>
   NotificationExec "nobody" "/usr/bin/collectd_alerta -s https://alerta.company.com"
</Plugin>
```
That gave me an error like:
```
Oct 19 14:38:35 host collectd[34851]: exec plugin: Failed to execute ``/usr/bin/collectd_alerta -s https://alerta.comparny.com'': No such file or directory
```

**Comment by blysik** [comment]
Looks like the same method as 'exec' works:
```
  NotificationExec "nobody" "/usr/bin/collectd_alerta" "-s" "https://alerta.company.com"
```
Should update the documentation to reflect that.  Otherwise, this can probably be closed.  Thanks.

**Comment by octo** [comment]
This is documented as of f4a528f0bc857a568cca1c1af589da8625b19e09.
