### ISSUE TITLE
utils_ignorelist missing in collectd plugin API

### ISSUE THREAD

**Issue by bdrung** [collectd/collectd#1323]
commit 216c6246b73645ac093de15b87aedc9abc6ebc80 moves the collectd daemon files into the src/daemon/ directory, but also silently drops utils_ignorelist. Dropping utils_ignorelist from the daemon has the drawback that it cannot be used by plugins any more and that 16 plugins need to bundle ignorelist.

**Comment by mfournier** [comment]
Hi @bdrung, thanks for reporting this and working on a patch, much appreciated !
I have trouble understanding what the issue actually is though (running 5.5 myself, using ignorelist-related config with some of these 16 plugins, and didn't notice any side-effect). Could you describe the problem from the user perspective please ? A config snippet, which collectd version have you installed, etc, would be helpful too. Thanks !

**Comment by bdrung** [comment]
The problem is that utils_ignorelist is not available for **external** plugins. The shipped plugins bundle utils_ignorelist and therefore work around the problem, but external plugins cannot bundle the source code of utils_ignorelist. We have an inhouse plugin that uses ignorelist, which breaks with collectd 5.5.

The collectd daemon 5.4.1 comes with ignorelist functions, but collectd 5.5.0 drop it.

**Comment by mfournier** [comment]
Ok, I get it, thanks for the explanations @bdrung !

It seems @octo bundled utils_ignorelist in the plugins using it on purpose (cf 216c6246b). So although I agree this is broken, I'll leave your PR open a few more days to give him a chance to comment on this.
Also, a couple of others seem to not be bundled with the daemon anymore, namely: utils_avltree utils_heap and utils_parse_option. Not sure if they should or not.

**Comment by mfournier** [comment]
Closed by 817e080

**Comment by dswarbrick** [comment]
:+1::+1:
