### ISSUE TITLE
plugin_load: Could not find plugin "rrdtool" in /usr/local/lib/collectd

### ISSUE THREAD

**Issue by lola27** [collectd/collectd#1326]
Hi, 
I installed collectd 5.5.0 via command `brew install collectd`. When starting collectd, i get the following error 

```
[2015-10-28 12:19:54] plugin_load: Could not find plugin "rrdtool" in /usr/local/lib/collectd
[2015-10-28 12:19:54] Found a configuration for the `rrdtool' plugin, but the plugin isn't loaded or didn't register a configuration callback. 
```

In the default collectd.conf, the line 'LoadPlugin rrdtool' is commented out with two hash characters. That means the plugin does not exist ??

**Comment by hussainghafoor** [comment]
I also have the same error.Could somebody please help me out on this

**Comment by faxm0dem** [comment]
Either disable the rrdtool plugin in your config, or install the additional package

**Comment by zain5248** [comment]
> Either disable the rrdtool plugin in your config, or install the additional package

What additional packages are you talking about? I am installing CollectD on one machine and it is working but on other, it is giving this error.

**Comment by faxm0dem** [comment]
Sorry I have 0 XP with `brew` or MacOS (after MacOS 8 ;-))
That being said, `collectd` is plugin-based, so all read and write components are optional.
Can you check if the required file is installed ?
For instance, on my Debian GNU/Linux I have:

```
☠ ls -l /usr/lib/collectd/rrd*.so
-rw-r--r--. 1 root root 31280 Jul 14  2021 /usr/lib/collectd/rrdcached.so
-rw-r--r--. 1 root root 35584 Jul 14  2021 /usr/lib/collectd/rrdtool.so
```

If those are missing, there is no way your `rrdtool` config could work, hence the `plugin_load: Could not find plugin "rrdtool" in /usr/local/lib/collectd` warning on startup.
Another reason this could happen is if the `PluginDir` configuration option were pointing to the wrong folder.

**Comment by faxm0dem** [comment]
Yes, `rrdtool.so` is part of collectd.
As an example, on RedHat Linux I need to do the following to have it available : `yum install collectd-rrdtool`

**Comment by zain5248** [comment]
> Yes, `rrdtool.so` is part of collectd. As an example, on RedHat Linux I need to do the following to have it available : `yum install collectd-rrdtool`

But it is not installing the rrdtool.so file in the user/lib/collectd folder. It was doing that before but not it does not anymore.

**Comment by faxm0dem** [comment]
It seems the dependency specified in the *formula* doesn't [require rrdtool](https://formulae.brew.sh/api/formula/collectd.json).
I'm guessing `brew install collectd` will recompile collectd from source, so you would need to have the rrdtool development headers available before doing that. Maybe `brew install rrdtool-dev` or `brew install rrdtool` ?

**Comment by MattHardcastle** [comment]
Homebrew installs a prebuilt collectd package, called bottles in brew's parlance. The collectd bottle wasn't built with rrdtool so it's missing the plugin. You must install rrdtools and then ask Homebrew to install collectd from source to get the rrdtool plugin:
```
brew install rrdtool
brew install --build-from-source collectd
# or...
brew reinstall --build-from-source collectd
```
