### ISSUE TITLE
Missing metrics in CPU samples

### ISSUE THREAD

**Issue by zxwing** [collectd/collectd#1328]
I use CPU plugin with write_http plugin to collect metrics of CPUs on my host.
The host has 4 CPUs, so for every sample there are supposed to be "idle", "user", "system" for each CPU. However, I observed not every sample contained all of those metrics, sometimes there was no "idle" for CPU0, sometimers no "system" for CPU1. 
The interval is 1s. I am not sure it's a bug or a mis-configuration.

In below example, the "idle" and "system" are missing for CPU0, and "user" are missing for CPU0 and CPU1:

<code><pre>
[
    {
        "values": [
            0
        ],
        "dstypes": [
            "gauge"
        ],
        "dsnames": [
            "value"
        ],
        "time": 1446218162.352,
        "interval": 5,
        "host": "yyy",
        "plugin": "cpu",
        "plugin_instance": "1",
        "type": "percent",
        "type_instance": "steal"
    },
    {
        "values": [
            99.1967871485944
        ],
        "dstypes": [
            "gauge"
        ],
        "dsnames": [
            "value"
        ],
        "time": 1446218162.352,
        "interval": 5,
        "host": "yyy",
        "plugin": "cpu",
        "plugin_instance": "1",
        "type": "percent",
        "type_instance": "idle"
    },
    {
        "values": [
            0.4
        ],
        "dstypes": [
            "gauge"
        ],
        "dsnames": [
            "value"
        ],
        "time": 1446218162.352,
        "interval": 5,
        "host": "yyy",
        "plugin": "cpu",
        "plugin_instance": "2",
        "type": "percent",
        "type_instance": "user"
    },
    {
        "values": [
            0.2
        ],
        "dstypes": [
            "gauge"
        ],
        "dsnames": [
            "value"
        ],
        "time": 1446218162.352,
        "interval": 5,
        "host": "yyy",
        "plugin": "cpu",
        "plugin_instance": "2",
        "type": "percent",
        "type_instance": "system"
    },
    {
        "values": [
            0
        ],
        "dstypes": [
            "gauge"
        ],
        "dsnames": [
            "value"
        ],
        "time": 1446218162.352,
        "interval": 5,
        "host": "yyy",
        "plugin": "cpu",
        "plugin_instance": "2",
        "type": "percent",
        "type_instance": "wait"
    },
    {
        "values": [
            0
        ],
        "dstypes": [
            "gauge"
        ],
        "dsnames": [
            "value"
        ],
        "time": 1446218162.352,
        "interval": 5,
        "host": "yyy",
        "plugin": "cpu",
        "plugin_instance": "2",
        "type": "percent",
        "type_instance": "nice"
    },
    {
        "values": [
            0
        ],
        "dstypes": [
            "gauge"
        ],
        "dsnames": [
            "value"
        ],
        "time": 1446218162.352,
        "interval": 5,
        "host": "yyy",
        "plugin": "cpu",
        "plugin_instance": "2",
        "type": "percent",
        "type_instance": "interrupt"
    },
    {
        "values": [
            0
        ],
        "dstypes": [
            "gauge"
        ],
        "dsnames": [
            "value"
        ],
        "time": 1446218162.352,
        "interval": 5,
        "host": "yyy",
        "plugin": "cpu",
        "plugin_instance": "2",
        "type": "percent",
        "type_instance": "softirq"
    },
    {
        "values": [
            0
        ],
        "dstypes": [
            "gauge"
        ],
        "dsnames": [
            "value"
        ],
        "time": 1446218162.352,
        "interval": 5,
        "host": "yyy",
        "plugin": "cpu",
        "plugin_instance": "2",
        "type": "percent",
        "type_instance": "steal"
    },
    {
        "values": [
            99.4
        ],
        "dstypes": [
            "gauge"
        ],
        "dsnames": [
            "value"
        ],
        "time": 1446218162.352,
        "interval": 5,
        "host": "yyy",
        "plugin": "cpu",
        "plugin_instance": "2",
        "type": "percent",
        "type_instance": "idle"
    },
    {
        "values": [
            0.200400801603206
        ],
        "dstypes": [
            "gauge"
        ],
        "dsnames": [
            "value"
        ],
        "time": 1446218162.353,
        "interval": 5,
        "host": "yyy",
        "plugin": "cpu",
        "plugin_instance": "3",
        "type": "percent",
        "type_instance": "user"
    },
    {
        "values": [
            0.200400801603206
        ],
        "dstypes": [
            "gauge"
        ],
        "dsnames": [
            "value"
        ],
        "time": 1446218162.353,
        "interval": 5,
        "host": "yyy",
        "plugin": "cpu",
        "plugin_instance": "3",
        "type": "percent",
        "type_instance": "system"
    },
    {
        "values": [
            0.400801603206413
        ],
        "dstypes": [
            "gauge"
        ],
        "dsnames": [
            "value"
        ],
        "time": 1446218162.353,
        "interval": 5,
        "host": "yyy",
        "plugin": "cpu",
        "plugin_instance": "3",
        "type": "percent",
        "type_instance": "wait"
    },
    {
        "values": [
            0
        ],
        "dstypes": [
            "gauge"
        ],
        "dsnames": [
            "value"
        ],
        "time": 1446218162.353,
        "interval": 5,
        "host": "yyy",
        "plugin": "cpu",
        "plugin_instance": "3",
        "type": "percent",
        "type_instance": "nice"
    },
    {
        "values": [
            0
        ],
        "dstypes": [
            "gauge"
        ],
        "dsnames": [
            "value"
        ],
        "time": 1446218162.353,
        "interval": 5,
        "host": "yyy",
        "plugin": "cpu",
        "plugin_instance": "3",
        "type": "percent",
        "type_instance": "interrupt"
    },
    {
        "values": [
            0
        ],
        "dstypes": [
            "gauge"
        ],
        "dsnames": [
            "value"
        ],
        "time": 1446218162.353,
        "interval": 5,
        "host": "yyy",
        "plugin": "cpu",
        "plugin_instance": "3",
        "type": "percent",
        "type_instance": "softirq"
    },
    {
        "values": [
            0
        ],
        "dstypes": [
            "gauge"
        ],
        "dsnames": [
            "value"
        ],
        "time": 1446218162.353,
        "interval": 5,
        "host": "yyy",
        "plugin": "cpu",
        "plugin_instance": "3",
        "type": "percent",
        "type_instance": "steal"
    },
    {
        "values": [
            99.1983967935872
        ],
        "dstypes": [
            "gauge"
        ],
        "dsnames": [
            "value"
        ],
        "time": 1446218162.353,
        "interval": 5,
        "host": "yyy",
        "plugin": "cpu",
        "plugin_instance": "3",
        "type": "percent",
        "type_instance": "idle"
    },
    {
        "values": [
            0
        ],
        "dstypes": [
            "gauge"
        ],
        "dsnames": [
            "value"
        ],
        "time": 1446218162.352,
        "interval": 5,
        "host": "yyy",
        "plugin": "cpu",
        "plugin_instance": "0",
        "type": "percent",
        "type_instance": "interrupt"
    },
    {
        "values": [
            0.200803212851406
        ],
        "dstypes": [
            "gauge"
        ],
        "dsnames": [
            "value"
        ],
        "time": 1446218162.352,
        "interval": 5,
        "host": "yyy",
        "plugin": "cpu",
        "plugin_instance": "1",
        "type": "percent",
        "type_instance": "system"
    },
    {
        "values": [
            0
        ],
        "dstypes": [
            "gauge"
        ],
        "dsnames": [
            "value"
        ],
        "time": 1446218162.352,
        "interval": 5,
        "host": "yyy",
        "plugin": "cpu",
        "plugin_instance": "0",
        "type": "percent",
        "type_instance": "softirq"
    }
]
</pre></code>

**Comment by mfournier** [comment]
write_http POSTs data when the (configurable) send buffer is full. My guess is that the values you're looking for are part of the previous or next batch.

**Comment by octo** [comment]
When you strip out all whitespace and newline characters, the provided JSON is 3915 bytes long. The default buffer size of the *write_http plugin* is 4096 bytes, so @mfournier's guess seems very likely.
