### ISSUE TITLE
Issue with Chain + Python 

### ISSUE THREAD

**Issue by mimaison** [collectd/collectd#1342]
I'm trying to filter metrics using a Chain. The goal is to send some metrics to my Python plugin and the rest to csv. I ended up building this chain:
```
PostCacheChain "PostCache"
<Chain "PostCache">
        <Rule>
                <Match "regex">
                        Plugin "^cpu$"
                </Match>
                <Target "write">
                        Plugin "python"
                </Target>
        </Rule>
        <Target "write">
                Plugin "csv"
        </Target>
</Chain>
```
When I start collectd I get:
```
collectd[17633]: Filter subsystem: Built-in target `write': Dispatching value to the `python' plugin failed with status 2
```

I saw https://collectd.org/wiki/index.php/Target:Write and checked that I indeed load Python in my config file. Just above the chain, I have:
```
<LoadPlugin python>
        Globals true
</LoadPlugin>
<Plugin python>
        ModulePath "/home/mickael/collectd"
        Import "myplugin"
</Plugin>
```

If I remove the whole chain block, all the metrics are sent to csv and my plugin fine.

Do I need to change anything in my plugin to work in a chain ?

**Comment by octo** [comment]
Hi @mimaison,

the name with which the callback is registered depends on the Python code. If the Python code passes the `name` argument to `collectd.register_write()`, you should use that name here. Otherwise, the *Python plugin* determines an appropriate name from the `__module__` attribute.

```python
collectd.register_write(my_callback, name='foo');
```

FTR, the next version of collectd will print a list of registered write callbacks in this scenario, making debugging hopefully easier.

**Comment by vshlapakov** [comment]
Hi @octo I've encountered with a similar problem, could you please provide correct collectd config for the above-mentioned case where a callback is registered with name = `foo`? 

Also is it possible to use chains with different python callbacks to use different python plugins?

 To be clear I have 2 different python plugins for different purposes:
- one for reading all the metrics
- second - for writing a part of it to csv

All other non-filtered metrics should be passed to `write_graphite` plugin. Thanks in advance. I can create another issue if needed, but these are strongly related.

**Comment by vshlapakov** [comment]
Sorry, nevermind, I have realized that I used collectd 5.4. Everything works well with 5.5. 

For notes, in the case above, you have to use `Plugin "python.foo"` in `Target "write"` section.
