### ISSUE TITLE
tail plug Gauge Average does not match exact values (recursive formula could be not correct)

### ISSUE THREAD

**Issue by toni-moreno** [collectd/collectd#1344]
Hi to everybody.

We are parsing response time ( in nanoseconds) from some log files with this match rule.

```
     <Match>
       Regex ".*SOME INFO **Time: ([0-9]+) ns.*"
       DSType "GaugeAverage"
       Type "time_stats"
       Instance "rt_avg"
     </Match>
```

After some days it seems like not always reporting correct times. When reviewing code to understand how plugin tail is doing the average. I've found this formula.

`````
      value = (gauge_t) strtod (matches[1], &endptr);
       ....
      double f = ((double) data->values_num)
	/ ((double) (data->values_num + 1));
      data->value.gauge = (data->value.gauge * f) + (value * (1.0 - f));
````

https://github.com/collectd/collectd/blob/master/src/daemon/utils_match.c#L106-L111

In a more simplified form: 

```
F=values_num/values_num+1
final_value= (old_value * F) + last_value * (1 -F )

```

It seems to follow the following average recursive formula.

![image](https://cloud.githubusercontent.com/assets/5883405/11209817/f2a8fe0a-8d23-11e5-8e2e-c846820ee252.png)

In this case a ( data->values_num)  should be the number of samples (time window)   in the period of measurement, isn't it?

By example ( if we have found 5 values matching regex in the period -- 60 seconds---). The mean should be  ( val[0] + val[1] + val[2] + val[3] + val[4] ) / 5 , in the previous recursive formula "a" or  "data->values_num" should be 5  for all averaged values in the time window. 

Could anybody told us if data->values_num are always ( for all the period ) the same value? It seems like is a counter auto-incremented on each iteration. In this case the formula could be not correctly applied.

@octo: could you help me to review this issue?

Thank you very much.

**Comment by octo** [comment]
Hey @toni-moreno!

Yes, `values_num` is set to the samples already taken into account but excluding the sample being handled. The `values_num` counter is increased later, in line 132.

As far as I can see the factor `f = values_num / (values_num + 1)` is correct. Why do you think the formula is incorrect?

Online algorithms and floating point numbers have a tendency to amplify errors, so it's quite possible that the result differs a little bit from the "correct" average, but I'd expect the error to be in the order of 10^-9.

Best regards,
—octo

**Comment by toni-moreno** [comment]
Hi @octo, I've build a test case simulating log files with increasing response time (200 ms) each 5 minutes and increasing also 5 matches / minute each 5 minutes. The result in the above screenshot show the expected  result.

![image](https://cloud.githubusercontent.com/assets/5883405/11294695/acb85686-8f65-11e5-8bb9-562af5e8fa28.png)

I'm sorry I was wrong because off a bad interpretation for the recursive formula

This previous formula 

![image](https://cloud.githubusercontent.com/assets/5883405/11209817/f2a8fe0a-8d23-11e5-8e2e-c846820ee252.png)

rewritted with F=1-a

![image](https://cloud.githubusercontent.com/assets/5883405/11296958/855dcb74-8f75-11e5-9a44-44b4cc46406e.png)

But F (and also a)  indeed depends on n  and not the total matches of the averaged period (here my mistake)  

![image](https://cloud.githubusercontent.com/assets/5883405/11296051/f0802c68-8f6f-11e5-916f-1f2c0ebd3a4a.png)


Thank you very much for your patience
