### ISSUE TITLE
plugin memory: wrong story type with absolute config

### ISSUE THREAD

**Issue by lawrency** [collectd/collectd#1347]
Hi,

 *  Collectd version 5.5.
 *  source code: git clone from github with branch master.
 *  Plugins: memory, rrdtool

rrdtool plugin config:

    <Plugin rrdtool>
        DataDir "/opt/collectd/var/lib/collectd/rrd"
        CreateFilesAsync false
        CacheTimeout 120
        CacheFlush   900
        WritesPerSecond 50
    </Plugin>

memory plugin config:

    <Plugin "memory">
        ValuesAbsolute  true
        ValuesPercentage    true
    </Plugin>

but I get this rrdinfo, when i check memory-free.rrd file.

    [longeek@longeek src]$ rrdinfo /opt/collectd/var/lib/collectd/rrd/longeek/memory/memory-free.rrd  | more
    filename = "/opt/collectd/var/lib/collectd/rrd/longeek/memory/memory-free.rrd"
    rrd_version = "0003"
    step = 2
    last_update = 1448010303
    header_size = 3496
    ds[value].index = 0
    ds[value].type = "GAUGE" //BUG!!!
    ds[value].minimal_heartbeat = 4
    ds[value].min = 0.0000000000e+00
    ds[value].max = 2.8147497671e+14
    ds[value].last_ds = "117870592"
    ds[value].value = 1.1787059200e+08
    ds[value].unknown_sec = 0

I check memory.c source:

```c
#define MEMORY_SUBMIT(...) do { \                                               
  if (values_absolute) \                                                      
    plugin_dispatch_multivalue (vl, 0, DS_TYPE_GAUGE, __VA_ARGS__, NULL); \
  if (values_percentage) \                                                    
    plugin_dispatch_multivalue (vl, 1, DS_TYPE_GAUGE, __VA_ARGS__, NULL); \ 
} while (0)
```

I think this is a bug!!! ok?

**Comment by octo** [comment]
Hi @lawrency,

I don't see anything unexpected in the output you provide. What would you have expected differently (and why)?

Best regards,
—octo

**Comment by rubenk** [comment]
Closing due to lack of feedback.
