### ISSUE TITLE
[question] How to convert NaNs to zeroes, or not write them at all?

### ISSUE THREAD

**Issue by AndrejKorshikov** [collectd/collectd#1348]
I collect data with collectd-snmp and write it to InfluxDB using collectd's network plugin.

Collectd-snmp generates 'Not a Number' (NaN) value for OIDs which do not exist. These NaN values break InfluxDB (for example, it's impossible to do SELECT from metrics with NaN values).

How can I convert NaNs to something else before send them to InfluxDB? Maybe I need some sort of proxy between collecd an influxdb?

Can just I discard data points with NaN value, and not send them to influxdb?

**Comment by rubenk** [comment]
Hi,

Please use the [collectd mailing list](http://mailman.verplant.org/listinfo/collectd) or the [#collectd IRC channel](https://webchat.freenode.net/?channels=#collectd).
We'd like to keep the github issue tracker for bugreports and patch reviews.
