### ISSUE TITLE
df plugin: trouble with getting percentage via ValuesPercentage

### ISSUE THREAD

**Issue by mgogoulos** [collectd/collectd#1359]
Hi all, hope we can solve this one. I'm working on a vanilla Debian 8.2 server on GCE and installed version of collectd is 5.4.1

I add this on my collectd.conf

```
LoadPlugin df
<Plugin df>
  MountPoint "/"
  ValuesPercentage true
</Plugin>
```

However I'm still getting absolute values from the df plugin. If I add 
  ValuesAbsolute false

I don't see any data from the plugin anymore. I have experimented with the other parameters of the plugin but without any luck. 

Any idea why this happens?

Thanks and regards,
Markos

**Comment by octo** [comment]
Hi @mgogoulos,

enabling `ValuesPercentage` does not disable `ValuesAbsolute`, so that much is expected.

The percentages are reported as the `percentage` type, not the `df_complex` one. Can you see them?

**Comment by octo** [comment]
FTR, there was some magic with `"/"` being changed to `"root"`, that might interfere here, too.

**Comment by mgogoulos** [comment]
Hi octo, extra amazing response time ;)

I can skip the MountPoint and specify only ValuesPercentage, still no joy. Btw I only see df_complex. Is there something else I need to add on the configuration?
Thanks

**Comment by octo** [comment]
You got lucky ;)

No, that should be all. I just tried with the following config:

```
octo@didactylos:/tmp/collectd$ egrep -v '^(#|$)' etc/collectd.conf 
LoadPlugin logfile
<Plugin logfile>
        LogLevel debug
        File STDOUT
        Timestamp true
        PrintSeverity false
</Plugin>
LoadPlugin df
<Plugin df>
        ValuesAbsolute false
        ValuesPercentage true
</Plugin>
```

And got metrics such as `didactylos/df-home/percent_bytes-used`

**Comment by mgogoulos** [comment]
Thank you very much, most probably this has to do with my configuration on the graphite server receiving the data. 

Btw congratulations for the excellent collectd tool and also for so actively supporting the project.
