### ISSUE TITLE
write_graphite plugin: Connection hangs in CLOSE_WAIT

### ISSUE THREAD

**Issue by sampointer** [collectd/collectd#1365]
When a backend goes away the write_graphite plugin can hang in CLOSE_WAIT. This is due to an incorrect test on the return of `swrite` meaning that `close()` is never called on the socket.

This PR fixes that problem: https://github.com/collectd/collectd/pull/1364

**Comment by throck** [comment]
@sampointer do you think this negates the need to implement #846?

**Comment by sampointer** [comment]
No, that still needs to be implemented. This ensures that close is called on the socket so that write_graphite doesn't end up in CLOSE_WAIT forever. In that sense this is a bug fix and https://github.com/collectd/collectd/pull/846 is a feature.

It would be great to have this fix as a point/patch release to 5.5.

**Comment by sampointer** [comment]
I'd happily test a point-release build.

**Comment by madhurranjan** [comment]
Is this fix available in 5.5.1 ?

**Comment by ricardojsanchez** [comment]
Is there an ETA to commit this? We are seeing this problem in release 5.5.0

**Comment by octo** [comment]
The changes made in #1364 are included in 5.4.3 and 5.5.1.

I just tried to reproduce this problem with the current *master* branch and version 5.5.0 and failed. In both cases the connection was in `CLOSE_WAIT` for a second or two and then got closed. Does anyone have a reliable way of reproducing this problem?

**Comment by sampointer** [comment]
I've some evidence that https://github.com/collectd/collectd/commit/42a62db has fixed this issue. Once I have a version with this code more widely deployed (5.5.2 in my case) I'll post here again. Early testing has been positive.

**Comment by octo** [comment]
Thanks for the update @sampointer!

**Comment by sampointer** [comment]
5.5.2 fixes this problem in our infrastructure.

We have a pair of endpoints behind an EC2 internal ELB configured with a 60s idle timeout and 30s connection draining. We regularly automatically randomly kill nodes both (both running collectd and those behind the ELB to which they connect). We're using `Protocol "tcp"` within the `write_graphite` configuration and a TCP listener on the ELB.

A move to 5.5.2 has stopped collectd hosts hanging in `CLOSE_WAIT` where it would previously otherwise with an identical set-up. We have observed correct behaviour over many hundreds of hosts.

**Comment by octo** [comment]
Thank you so much for the update, @sampointer! I'll close this issue then.
