### ISSUE TITLE
ability to cache values for plugins with different Intervals set

### ISSUE THREAD

**Issue by mgogoulos** [collectd/collectd#1369]
Hi all, 

I have set a default Interval of 5 seconds at the beginning of my collectd.conf. However I run some custom plugins that need more time to run, or I don't want to have them running every 5 minutes since they require heavy resources. Is there a way to set when the plugins will run, but also send caching results on the meanwhile? 

Cheers,
Markos

**Comment by octo** [comment]
Hi @mgogoulos,

you can pass the `Interval` option to `LoadPlugin` like this:
```
  <LoadPlugin df>
    Interval 3600
  </LoadPlugin>
```

Not sure what you mean by caching results …?

Best regards,
—octo

**Comment by mgogoulos** [comment]
Hi, 

If I have Interval 5 at the beginning of my collectd.conf, and then have set Interval 3600 inside a plugin, will collectd send this plugin's data every 5 secs, but only  run the same plugin every 3600 secs? So will it run every 3600 secs but on the meanwhile every 5 secs send the data it has received when it was actually run? This is what would suit me since some plugins take time to run (eg exec a script) so I want them to be run once every 5 minutes for example, but I don't want gaps on the other side (graphite) that is receiving the data. 

Hope my question makes sense!

**Comment by octo** [comment]
When the interval of that plugin is set to one hour, it will be queries once per hour and only one datapoint will be reported per hour.

The metric will include the interval, though, so systems consuming these metrics will know to only expect an update once every 3600 seconds.

Best regards,
—octo

**Comment by mgogoulos** [comment]
Makes sense, thank you very much for the reply
