### ISSUE TITLE
systemd : need specific capability for a few plugins

### ISSUE THREAD

**Issue by gillarda** [collectd/collectd#1444]
Hi, 

I am currently testing  the Collectd CI RPM. I get the following error on startup : 

```
 systemd: Starting Collectd...
collectd[3067]: ceph plugin: cconn_connect: connect(3) failed: error -13
collectd[3067]: ceph plugin: cconn_prepare(name=osd.48,i=0,st=0)=-13
collectd[3067]: Initialization complete, entering read-loop.
```

It looks like collectd cannot connect to the ceph sockets : 

```
ll /var/run/ceph/
total 0
srwxr-xr-x. 1 ceph ceph 0 Dec  2 12:14 ceph-osd.48.asok
srwxr-xr-x. 1 ceph ceph 0 Dec  2 12:15 ceph-osd.49.asok
srwxr-xr-x. 1 ceph ceph 0 Dec  2 12:15 ceph-osd.50.asok
srwxr-xr-x. 1 ceph ceph 0 Dec  2 12:15 ceph-osd.51.asok
srwxr-xr-x. 1 ceph ceph 0 Dec  2 12:16 ceph-osd.52.asok
```

This seems linked to @rubenk work on collectd isolation (e9ad0b8), I have to add the ```CAP_DAC_OVERRIDE``` capability for the connection to occur.

```
# turn this on if you use the ceph plugin
CapabilityBoundingSet=CAP_DAC_OVERRIDE
```

**Comment by rubenk** [comment]
Ah, nice catch! If I understand it correctly, you need CAP_DAC_OVERRIDE because the socket is owned by ceph, not by root.

Are you willing to turn this change into a PR?

**Comment by mfournier** [comment]
Additionnally @obfuscurity reported on IRC the exec plugin needed `CAP_SETGID` and `CAP_SETUID` to properly change uid/gid.

**Comment by mfournier** [comment]
@rubenk may I draw your attention to #1530 ?
