### ISSUE TITLE
Does  Collectd  support  string collection?

### ISSUE THREAD

**Issue by nitreason** [collectd/collectd#1445]
I have a shell script to get the IP address of a linux system. And  I  use exec plugin and write_kafka plugin.  Then I found the result  of kafka topic  as fowlling: 10.1, but my IP an result of shell script is :10.12.2.2.   Does  collectd or its plugins  not  support string collection? Please help. Thanks so much!

My configuration file as follow:
\<Plugin write_kafka>\
  Property "metadata.broker.list" "CentOS01:9092"
  \<Topic "linda">\
    Format Command
  \</Topic>\

my types.db as follow:
ip                      ip:GAUGE:0:U
IPAddress         IPAddress:GAUGE:0:U

my shell script as follow:
#!/bin/bash
IPAddress=`/sbin/ifconfig eth1 | grep "inet addr" | awk '{ print $2}' |awk -F: '{print $2}'`
echo "PUTVAL \"/exec/IPAddress\" interval=60 N:$IPAddress"

**Comment by octo** [comment]
Hi @nitreason,

no, that's not possible per se. In collectd's world metrics are always numeric. You may be able to use [notifications](https://collectd.org/wiki/index.php/Notifications_and_thresholds) to use collectd to send strings though.

HTH,
—octo
