### ISSUE TITLE
Config to send data from collectd to Graylog-server?

### ISSUE THREAD

**Issue by manhdinh** [collectd/collectd#1470]
Hi all. I want to send the data that are collected from collectd to Graylog-server. I try to load all data to a file log of collectd and then i will collect data from this. The problem is i can't find the mechanism to load data of collectd ( like cpu, memory... ) to /var/log/collectd.log, i followed this instruction : https://collectd.org/wiki/index.php/Plugin:LogFile but it seem not correct because i can't find collectd.log in /var/log ?
Any one have the suggestions for my issue or the other way that can help to send data from collectd to Graylog-server.
Thanks !!!

**Comment by michaelsalmon** [comment]
collectd.log is used for information from collectd, not data. I think that the easiest way to get from collectd to graylog is to use the write_http plugin and write a converter. Probably any of the write plugins could be used.

**Comment by manhdinh** [comment]
Hi michaelsalmon ! . I think about write_http before, Can you talk about writing a converter more clearly?

**Comment by michaelsalmon** [comment]
write_http sends the data that would normally be written to an rrd to a URL. The original or COMMAND format was as PUTVAL's but you can also use JSON now.  The PUTVAL format is described here: https://collectd.org/documentation/manpages/collectd-unixsock.5.shtml
I don't think that the JSON format is documented but it contains the same information just broken up into the various components. Each post can contain many rows.

For me the COMMAND format was perfect as I wanted to persist data from a remote machine without using the collectd network server. I think that JSON is better for your case as you probably want to change the format.

I used the following PHP script to examine the data received:

    <?php
        header('HTTP/1.0: 200');
        $txt = file_get_contents('php://input');
        file_put_contents('/tmp/postDump.txt', $txt);
     ?>
