### ISSUE TITLE
SNMP plugin - Add SNMP Timeout configuration option to 'Host Block'

### ISSUE THREAD

**Issue by n00badmin** [collectd/collectd#1472]
Greetings collectd team, 

Is it possible to add the ability to configure an SNMP timeout value to the Host Block in the SNMP plugin?

I am asking because I am looking to move away from cacti/rrdtool to collectd in order to feed splunk with snmp data. 

In my multiple years of using cacti, I have found that there are some devices that take longer to respond to snmp than others. Cacti provides the ability to tweak the snmp timeout (time cacti will wait for response from a device) on a per host basis, which allows you to account for slower responses. 

I am unclear regarding the lower level workings of the snmp plugin with regard to how long it will wait, but the ability to adjust this can solve problems that larger switches/devices may pose, ie a switch with hundreds of interfaces. 

I was chatting with rubenk on the IRC and he suggested this could be an simple enhancement and that I should open a ticket here. 

Thanks!

n00badmin

**Comment by rubenk** [comment]
This should have been easy, since according to its documentation net-snmp provides a timeout parameter on its session object. It does however completely seem to ignore this.

**Comment by cvicente** [comment]
I have the same issue. Some devices produce lots of:

"snmp plugin: host router1.example.net: snmp_sess_synch_response failed: Timeout"

and I'm looking for a Timeout setting. Even a global timeout would help. Any pointers?

**Comment by octo** [comment]
There is a `timeout` field in `struct snmp_session` which appears to control timeout behavior. I'm not sure if fiddling with it is supported behavior, but the `SNMP` Perl module at least provides some precedence.

**Comment by rubenk** [comment]
I did fiddle with it, but at least in my attempts it was completely ignored.

**Comment by octo** [comment]
That's of course very unfortunate. Reading through `snmp_sess_synch_response()` confirms that the `timeout` field is not honored, at least in that function.

**Comment by rubenk** [comment]
Yeah, if I recall correctly it only worked for asynchronous calls. I decided not to pursue that path though.

**Comment by cvicente** [comment]
Would it be possible to implement a timeout mechanism outside of the parameters offered by the net-snmp library itself? I've started looking at how the snmpget, snmpwalk and other tools implement it, but it's a steep learning curve for me. Pointers appreciated.

**Comment by cvicente** [comment]
Contrary to previous comments, our tests suggest that the timeout is indeed used by the net-snmp library. I have submitted the following PR, which adds the configuration options for the Host object:

https://github.com/collectd/collectd/pull/2488

**Comment by cvicente** [comment]
The PR was merged today. Thank you everyone.

**Comment by octo** [comment]
Thanks for that patch and testing, @cvicente!
