### ISSUE TITLE
CPU plugin configuration can't be loaded?

### ISSUE THREAD

**Issue by rindek** [collectd/collectd#1473]
Hi - I'm using collectd 5.5 from `ppa:rullmann/collectd` builds on Ubuntu 14.04 and I want to overwrite cpu plugin configuration, so I'm adding this one to the config file:

```
<Plugin cpu>
  ReportByState true
  ReportByCpu false
</Plugin>
```

(Of course `LoadPlugin cpu` is included in the configuration file.)

However every time I start collectd I see this error message:

```
Found a configuration for the `cpu' plugin, but the plugin isn't loaded or didn't register a configuration callback.
```

It falls back to default behaviour which is not what I want.
It's driving me crazy - Is there something I forgot to do or is this a bug?

**Comment by rindek** [comment]
Nevermind, I had dangling old version of collectd on system

**Comment by korablin** [comment]
I am having the same problem, I didn't get how to solve it without switching to a newer version?

**Comment by rindek** [comment]
Hi @korablin. If I remember correctly, collectd < 5.5 didn't have these options available, thus this error. My issue was that I had two different versions of collectd on system  (one = 5.5 and one < 5.5) and the < 5.5 one was starting up and catching up the file (which failed obvioiusly). So the "fix" was to upgrade it to 5.5 :)

**Comment by korablin** [comment]
@rindek Thank you! I didn't think that there is could be such significant difference between minor releases.. 
I am using 5.4.2, and having issues with configuration of cpu and memory plugins, which are quite basic.

**Comment by rindek** [comment]
@korablin thought so as well! However release 5.5 was pretty big, full changelog can be found here: https://collectd.org/wiki/index.php/Version_5.5, Some entries: "CPU plugin: The plugin is now able to report values as percentages and aggregate values per-state and per-CPU"  (the one I had issue with), and also for memory plugin: "Slab memory reporting on the Linux platform has been added" and "The plugin is now able to report values as percentages."
