### ISSUE TITLE
Could collectd exec-plugin supported one more variables?

### ISSUE THREAD

**Issue by nitreason** [collectd/collectd#1481]
I'd like get the tcpport's status by using  exec-plugin of collectd. Simply to say , if the port is connected, the value is set to 1,otherwise ,the value is 0. But there is a problem troubled me .
I defined the “PUTVAL“ in the shell script as this : 

```sh
echo "PUTVAL \"$HOSTNAME/exec/TcpPort_Status\" interval=$INTERVAL N:$TcpPort_Status"
```

and I can get the resulte  as  follow:

```
time				host	type		value
2015-12-22T03:25:01.534605Z	TEST	TcpPort_Status	0
```

by the way,the defination of types.db as follow:

```
TcpPort_Status          TcpPort_Status:COUNTER:0:U
```

but I changed the "PUTVAL" as follow ,then it seems that there is no value written to the influxdb:

```sh
echo "PUTVAL \"$HOSTNAME/exec/$PORT\" interval=$INTERVAL N:$TcpPort_Status"
```

Is  that the PUTVAL function could not  including two or more variables' defination? If  I want to achieve this function(get the tcpport's status with collectd),how can I do ?

Please help,Thanks so much.

**Comment by nitreason** [comment]
@octo Please help,Thank you.

**Comment by rubenk** [comment]
Hi,

Please use the [collectd mailing list](http://mailman.verplant.org/listinfo/collectd) or the [#collectd IRC channel](https://webchat.freenode.net/?channels=#collectd).
We'd like to keep the github issue tracker for bugreports and patch reviews.
