### ISSUE TITLE
Unable to source Interval from Include file

### ISSUE THREAD

**Issue by obfuscurity** [collectd/collectd#1488]
I've been attempting to set the `Interval` from an `Include`'d configuration file. Other plugin-related settings work fine, but I haven't been able to get this global setting to work unless it's set in collectd.conf.

Is this a bug or a misunderstanding on my part? I don't see anything in the documentation to suggest that global settings can't be read from an `Include` file.

**Comment by obfuscurity** [comment]
Weird, unable to reproduce this issue now. Closing.

**Comment by obfuscurity** [comment]
Correction, my testing yesterday was flawed. I was using 60 and 10 as sample `Interval` sizes without realizing it was falling back on the default 10 setting when I also happened to set it in the include file. Reopening.

**Comment by mfournier** [comment]
This worked for me out of the box. Can you provide more details about your setup please ? collectd version, relevant config snippets, etc. Thanks !

Here is what I tested:

main collectd.conf:
```
[...]
#Interval     2
Include "/tmp/test/*.conf"
[...]
```

/tmp/test/interval.conf:
```
Interval 2
```

**Comment by octo** [comment]
Stale for over a month.
