### ISSUE TITLE
rrdtool plugin: Seg fault on fresh install on 5.4 and 5.4 branch.

### ISSUE THREAD

**Issue by vmahedia** [collectd/collectd#1492]
While installing fresh 5.5 or 5.4, if you don't have collectd.conf (previously used), maintainer's collectd.conf will be installed and it will still seg fault trying to run `collectd -t -C /etc/collectd/collectd.conf`because the code that reads config option for `rrdtool` plugin has a bug where it's passing `datadir` pointer which is `null` to `strlen`.

Also, the case where it's being upgraded from any version to 5.4 and user chooses NOT to overwrite their custom config with Maintainer's Version of Config file, it will work fine.

 5.4 has the same problem as the problematic commit was merged onto 5.4 branch as well.

Breaking Commit : 4ef7c074cdbab9c43cbbfcb918e9ba4f6be6fa1e

Here's the pull request [https://github.com/collectd/collectd/pull/1486] which fixes it on 5.5, if it looks good, I can fix it on other branches as well.

**Comment by mfournier** [comment]
Thanks forthe detailed report @vmahedia !

Closed by 912d03c.
