### ISSUE TITLE
AbsoluteInc missing in tail plugin

### ISSUE THREAD

**Issue by michaelsalmon** [collectd/collectd#1495]
I have started to experiment with using the tail plugin to read apache httpd access_log and I'm pretty happy with using CounterInc as the DSType. Unfortunately when I restart collected I get a big spike which I'm pretty sure is the result of the counter suddenly being 0. I believe that I could fix this by using an absolute value instead of a counter but the tail plugin doesn't support AbsoluteInc or AbsoluteAdd for that matter. I can't see any reason for omitting these DSTypes so I wonder if I haven't missed something.

I could use a gauge and I may even do that but I liked having a rate and absolute is ideally suited for that.

**Comment by mfournier** [comment]
What `Type` are you using alongside `CounterInc` ? `COUNTER`'s would have this sort of behaviour, but `DERIVE`'s won't (yes, this is a bit confusing :-( ... )

Here's an example of what I typically use:

```
<Match>
  Regex "org\\.elasticsearch\\..*Exception"
  DSType "CounterInc"
  Type "derive"
  Instance "exception"
</Match>
```

Take a look at https://collectd.org/wiki/index.php/Data_source for the background.

**Comment by michaelsalmon** [comment]
OK, I'll give that a try.

**Comment by michaelsalmon** [comment]
I've tried it and it works the way I want so I'm happy.

**Comment by mfournier** [comment]
Great, thanks for the feedback !
