### ISSUE TITLE
mqtt plugin

### ISSUE THREAD

**Issue by vincentpan** [collectd/collectd#1498]
I'm trying to use the mqtt plugin for collectd
In log mode debug of collectd  i have got :
mqtt plugin: mosquitto_loop succeeded.

but nothing is writing in influxdb

So nothing is catching by collectd from the plugin ??

**Comment by rubenk** [comment]
How are you talking to InfluxDB?
Did you check that collectd is sending any values out? You might want to try a simpler write plugin first, I.e. the cvs, rrd or write_log plugin.
