### ISSUE TITLE
Meaning of "Values" returned by libvirt/virt_vcpu, libvirt/if_packets-vnet, libvirt/disk_ops 

### ISSUE THREAD

**Issue by pushpendrachaturvedi** [collectd/collectd#1504]
Hello,

I am very new to libvirt and collectd, i could not find or rather understand the meaning in documentation, that is why I am posting my query here, please help

i am monitoring virtual machine's statistics with collectd by saving them on influxdb.
The setup is working perfectly,

I am unable to figure out the meaning of values returned by following series

1. libvirt/virt_vcpu-0
I understand its monitoring data for virtual cpu of the machine but what exactly does the returning 'values' mean?
In my case i am getting values on time series graph like

500G
1.0T
1.5T

so are these CPU cycles or what? please someone explain.

2. libvirt/if_packets-vnet1, 

Again i know it has to do something with network, but not sure what is the meaning of returned values.

Is it showing number of packets transferred?
On time series graph i am getting 'values' like

5.0M
10M
15M

3.libvirt/disk_ops-vda

is it number of disk operations?
The 'values'  are like 
100k
200k
300k
400k
500k

Please explain the basic about above 3 'series' and suggest me if there is some book which i can read to understand this.
I went through collectd and libvirt documentation, but i could not really figure out the meaning of these 'values'

Please please please help asap, i am stuck for past 2 days due to this.

**Comment by rubenk** [comment]
Hi,
if_packets is packets sent / received since the start of the vm.
disk_ops is the number of disk operations since the start of the vm.
vcpu is nanoseconds of cpu time since the start of the vm.

I hope this helps.
