### ISSUE TITLE
Varnish plugin delivers wrong values

### ISSUE THREAD

**Issue by dennisxrow** [collectd/collectd#1507]
Hello,
I have a problem using the varnish plugin as it don't seems to collect the data correctly, or at least not as I expected.

I use collectd and collectd-varnish both on version 5.5.0 installed via yum together with the graphite web interface on an Centos 7 system in a client-server architecture. Varnish is using Version 4.1.0 revision 3041728.

The most important information for me are the varnish hit rates and total requests, (wich I expected to be located in default-cache/cache_result and default-totals/total-requests).
In both cases the RRD files getting created and updated just fine.
But the values for the default-cache/cache_result RRD files always stay at 0.

I dumped an cache_result/hit RRD file with the rrdtool and found out that all values are "NaN".
I directly checked the varnish hits with "varnishstat" wich displayed about 50 hits, so this shouldn't be a problem either.

I also have a problem with the total requests wich just displays me an rapidly increasing value of about 5000 requests. Wich don't match the value in varnishstat either as this is a developement environment and there is nobody who would generate this amount of traffic.

Finally the default-backend/backends/n_backends seems to show me the total requests (about 50) were I would have expected the number of known backends and not the requests.

I already checked the general collectd troubleshooting guide and couldn't find any problems.
I couldn't find any errors in the log either.
Im also using some other plugins on other collectd clients connected to the same collectd server wich all work properly.
I removed most of the plugins from the varnish client for debugging purpose and my configuration for the plugin seems fine too.

**"Client" collectd.conf:**

    Hostname varnish02
    FQDNLookup false
    Interval 10
    Timeout 2
    ReadThreads 5
    AutoLoadPlugin false
    TypesDB "/usr/share/collectd/types.db"

    ## Always load syslog plugin so we can investigate issues
    LoadPlugin syslog

    <Plugin "syslog">
      LogLevel "info"
    </Plugin>

    LoadPlugin logfile

    <Plugin "logfile">
      LogLevel "info"
      File "/var/log/collectd.log"
      Timestamp true
    </Plugin>

    LoadPlugin network

    <Plugin "network">
      Server "192.168.1.99"
    </Plugin>

    LoadPlugin varnish

    <Plugin "varnish">
      <Instance>
        CollectCache       true
        CollectConnections true
        CollectBackend     true
        CollectSHM         true
        CollectESI         false
        CollectFetch       false
        CollectHCB         false
        CollectSMS         false
        CollectTotals      true
        CollectWorkers     false
      </Instance>
    </Plugin>

    #Include "/etc/collectd.d/*.include.conf"

**"Server" collectd.conf:**

    Hostname log01
    FQDNLookup false
    Interval 10
    Timeout 2
    ReadThreads 5
    AutoLoadPlugin false
    TypesDB "/usr/share/collectd/types.db"
    ## Always load syslog plugin so we can investigate issues
    LoadPlugin syslog

    <Plugin "syslog">
        LogLevel "info"
    </Plugin>

    LoadPlugin logfile
    <Plugin "logfile">
      LogLevel "info"
      File "/var/log/collectd.log"
      Timestamp true
    </Plugin>

    LoadPlugin load

    LoadPlugin memory

    LoadPlugin rrdtool

    <Plugin "rrdtool">
        Datadir "/var/lib/collectd/rrd"
    </Plugin>

    LoadPlugin network

    <Plugin "network">
        Listen "0.0.0.0"
    </Plugin>

    LoadPlugin unixsock

    <Plugin unixsock>
        SocketFile "/tmp/collectd.sock" 
        SocketGroup "nagios" 
        SocketPerms "0770" 
     </Plugin>

    LoadPlugin write_graphite

    <Plugin "write_graphite">
      <Node "graphing">
        Host "localhost"
        Port "2003"
        Prefix "collectd."
        EscapeCharacter "_"
        SeparateInstances true
        StoreRates false
        AlwaysAppendDS false
      </Node>
    </Plugin>

    #Include "/etc/collectd.d/*.include.conf"

**Comment by mfournier** [comment]
Could it be that you are looking at an ever-increasing counter ? Shouldn't you use `StoreRates true` ?

**Comment by dennisxrow** [comment]
Hello,
thanks for the reply.
I just set the StoreRates to true for the write_graphite plugin and as general setting on the server and client, but it doesen't changed anything.  I'm not sure if that's what you ment.

**Comment by dennisxrow** [comment]
I still couldn't resolve the issue.

**Comment by mfournier** [comment]
@dennisxrow I just tried to reproduce the problem, but I wasn't able to.

This was using the packages from https://pkg.ci.collectd.org/rpm/collectd-5.5/epel-7-x86_64/ and varnish 4.0.3 from the fedora EPEL repo.

What strikes me now, is that you're using varnish 4.1, but support for this varnish version in collectd is only available in a release (5.5.1) since a couple of weeks ago.

So I'm wondering, which repo did you install the collectd 5.5.0 RPM from ? Also, I'm a bit worried that if collectd's varnish plugin was built against libvarnishapi 4.0.x it could show this sort of awkward behaviour when run against libvarnishapi 4.1.x

Also, you might want to enable the csv plugin on the client machine (which supports the StoreRates parameter), it will make investigating all this much easier.

**Comment by dennisxrow** [comment]
Oh noes,
I think is misunderstood the collectd wiki, I thought it states that the varnish plugin works with Varnish version 4.X, instead theres clearly stated that its for 4.0.
I installed Collectd 5.5.0 from EPEL repository together with varnish 4.1.1, as you already said, this may causes the problem for me.
So an uprage to 5.5.1 would maybe solve the problem?
As we can't downgrade our varnish and we only use packages from EPEL we might have to wait until 5.5.1 made it's way to the EPEL repo, which would be okay for me.
(I will give the CSV plugin a try, although the exported varnish RRD files and the metrics in graphite were already pretty twisted)
Thanks for your advise!

**Comment by dennisxrow** [comment]
The CSV values do not differ from the RRD or graphite values, although store rates true seems to change incredibly high values to more believable, but still not correct ones.
The cache hit miss etc, as well as most of the other metrics values remain unchanged at 0.

**Comment by dennisxrow** [comment]
The upgrade to 5.5.1 solved the problem.
