### ISSUE TITLE
uptime plugin misbehaves on clock shifts

### ISSUE THREAD

**Issue by l29ah** [collectd/collectd#1510]
I have a machine that lacks an RTC so it loads the previously stored time at every bootup and resynchronizes clock via ntp once a network connection gets up. Meanwhile the uptime plugin seems to just substract its startup real time (not a monotonic/CLOCK_MONOTONIC_RAW one) from the current one, resulting in incorrect uptime getting logged after a time shift.

**Comment by augustollenz** [comment]
This issue was fixed in #2034
