### ISSUE TITLE
How to get the informations from Server with ipmi plugin of collectd?

### ISSUE THREAD

**Issue by nitreason** [collectd/collectd#1512]
Hi,
I have a IBM Server with IMM.  I want to get datas like temperature  with collectd's IPMI plugin.  Should I install the collectd client to the IBM Server ? How can I use this plugin? please help.
Thank you so much.

**Comment by rubenk** [comment]
Please use the collectd mailing list or the #collectd IRC channel. We'd like to keep the github issue tracker for bugreports and patch reviews.

**Comment by rpv-tomsk** [comment]
Hi. You may be interested to look into PR #2024.
