### ISSUE TITLE
How to get the hardware information?

### ISSUE THREAD

**Issue by nitreason** [collectd/collectd#1513]
hi,
i want to read hardware sensors from servers by using collectd`s IPMI plugin. should i install the collectd client on the target server? @octo

**Comment by rubenk** [comment]
Yes, you should install collectd on the server and use the ipmi plugin: https://collectd.org/wiki/index.php/Plugin:IPMI

If you need more help with Collectd, please use the collectd mailing list or the #collectd IRC channel. We'd like to keep the github issue tracker for bugreports and patch reviews.
