### ISSUE TITLE
collectd doesn't build reproducibly on armhf

### ISSUE THREAD

**Issue by mfournier** [collectd/collectd#1523]
From https://tests.reproducible-builds.org/rb-pkg/unstable/armhf/collectd.html:

```
-checking for jni.h... found in /usr/lib/jvm/default-java/include
-checking for jni_md.h... found in /usr/lib/jvm/default-java/include
-checking for libjvm.so... found in /usr/lib/jvm/default-java/jre/lib/arm/server
-configure: Building with JAVA_CPPFLAGS set to: -I/usr/lib/jvm/default-java/include -I/usr/lib/jvm/default-java/include -I/usr/lib/jvm/default-java/include
-configure: Building with JAVA_LDFLAGS set to: -L/usr/lib/jvm/default-java/jre/lib/arm/server -Wl,-rpath -Wl,/usr/lib/jvm/default-java/jre/lib/arm/server -L/usr/lib/jvm/default-java/jre/lib/arm/server -Wl,-rpath -Wl,/usr/lib/jvm/default-java/jre/lib/arm/server
+checking for jni.h... found in /usr/lib/jvm/java-1.7.0-openjdk-armhf/include
+checking for jni_md.h... found in /usr/lib/jvm/java-1.7.0-openjdk-armhf/include
+checking for libjvm.so... found in /usr/lib/jvm/java-1.7.0-openjdk-armhf/jre/lib/arm/server
+configure: Building with JAVA_CPPFLAGS set to: -I/usr/lib/jvm/default-java/include -I/usr/lib/jvm/java-1.7.0-openjdk-armhf/include -I/usr/lib/jvm/java-1.7.0-openjdk-armhf/include
+configure: Building with JAVA_LDFLAGS set to: -L/usr/lib/jvm/default-java/jre/lib/arm/server -Wl,-rpath -Wl,/usr/lib/jvm/default-java/jre/lib/arm/server -L/usr/lib/jvm/java-1.7.0-openjdk-armhf/jre/lib/arm/server -Wl,-rpath -Wl,/usr/lib/jvm/java-1.7.0-openjdk-armhf/jre/lib/arm/server
```

A difference between both builds is that the environments used are configured with a different locale. So my assumption is that `find` behaves differently depending on that, and a fix could be as simple as slapping `LC_ALL=C` at the top of `configure.ac`.

What puzzles me though is why only on this platform (amd64 for example builds reproducibly).

If someone has access to an armhf (debian-based) system and could check what the effect of varying `LC_ALL` has on the `find -L /usr/lib/jvm/ -name jni.h -type f` command. That would be of great help !

/cc @tokkee @bzed

**Comment by rubenk** [comment]
I just checked https://tests.reproducible-builds.org/rb-pkg/unstable/armhf/collectd.html and it seems reproducible now?

**Comment by rubenk** [comment]
By the way, I think we should use something else instead of find -L to find Java.
On Solaris we pick up a 32bit libjvm.so when doing a 64bit build for instance.

**Comment by octo** [comment]
The referenced link is dead :(

**Comment by bzed** [comment]
https://tests.reproducible-builds.org/debian/rb-pkg/unstable/armhf/collectd.html - still broken

**Comment by mfournier** [comment]
I'm waiting for an access to a porter machine. I'll take care of this.

**Comment by mfournier** [comment]
So what I can tell is that on armhf with the `C` locale, `find` prints out matches in reverse order than on amd64.
I wasn't able to check with other locales, but as this is one of the noticeable differences between the two build environments, I assume the locale *could* influence the ordering on some architectures. And if not, we'll have to pipe the output to `sort`, something which definetely *is* influenced by the locale.

@bzed, @tokkee: FYI I'm preparing a 5.5.2-2 upload to check this theory. And I plan to get working on packaging 5.6.0 just after :-)

@rubenk totally agreed, this is fragile and unreliable. Can't think of anything better currently though.

**Comment by mfournier** [comment]
Still failing in 5.5.2-2, so I'm going to add a `|sort`, which should do the trick.

In case someone in the audience understands how computers work, I'd be curious to know what drives the sort order of `find`...

**Comment by rubenk** [comment]
finds sort order is filesystem dependent. If you strace find, you'll see it just calls `getdents(2)`. You'll get the same result by running `ls -U`.

If I recall correctly ext3 sorts files by the hash of their filename for instance.
