### ISSUE TITLE
Build RPM failed with notify_nagios plugins

### ISSUE THREAD

**Issue by frostynova** [collectd/collectd#1531]
OS: CentOS 6.7
Collectd: 5.5.1

rpmbuild -ba collectd.rpm

```

extracting debug info from /root/rpmbuild/BUILDROOT/collectd-5.5.1-1.el6.x86_64/usr/lib64/collectd/threshold.so
symlinked /usr/lib/debug/usr/lib64/libcollectdclient.so.1.0.0.debug to /usr/lib/debug/usr/lib64/libcollectdclient.so.debug
symlinked /usr/lib/debug/usr/lib64/libcollectdclient.so.1.0.0.debug to /usr/lib/debug/usr/lib64/libcollectdclient.so.1.debug
6157 blocks
+ /usr/lib/rpm/check-buildroot
+ /usr/lib/rpm/redhat/brp-compress
+ /usr/lib/rpm/redhat/brp-strip-static-archive /usr/bin/strip
+ /usr/lib/rpm/redhat/brp-strip-comment-note /usr/bin/strip /usr/bin/objdump
+ /usr/lib/rpm/brp-python-bytecompile
+ /usr/lib/rpm/redhat/brp-python-hardlink
+ /usr/lib/rpm/redhat/brp-java-repack-jars
Processing files: collectd-5.5.1-1.el6.x86_64
error: File not found: /root/rpmbuild/BUILDROOT/collectd-5.5.1-1.el6.x86_64/usr/lib64/collectd/notify_nagios.so
Executing(%doc): /bin/sh -e /var/tmp/rpm-tmp.X97ANL
```

**Comment by rubenk** [comment]
Hi,

Where did you get the spec file from?
Please post your spec file and complete build output.

**Comment by frostynova** [comment]
I got it from this git repo, what i modified is change mysql-devel to MySQL-devel (our own version)

collectd.spec:

https://gist.github.com/frostynova/1be21f03b4f051aeac4c

build.log:

https://gist.github.com/frostynova/fa7bed16f8676f43c6bc

**Comment by mfournier** [comment]
It looks like you're using the RPM specfile from the `master` branch. If you want to build 5.5.x you must take it from the `collectd-5.5` branch.

**Comment by frostynova** [comment]
@mfournier yes, i use the master code
Spec file from tag 5.5.1 built successfully
A little problem is the version in it is old:

Version: 5.5.0   
should be 
Version: 5.5.1

**Comment by rubenk** [comment]
5.5.1 is not released yet.

**Comment by frostynova** [comment]
@rubenk I found the 5.5.1 news here:

https://collectd.org/wiki/index.php/Version_5.5

**Comment by frostynova** [comment]
@rubenk Sorry, my fault,  did not see   'To be'

**Comment by mfournier** [comment]
@rubenk, 5.5.1 *has* been released. The website hasn't been updated yet though, but the tarball & checksum are available at https://collectd.org/files/ and the git repo has the usual tag.

/cc @octo

**Comment by rubenk** [comment]
Oh wow, I missed that :) Time to update Fedora / EPEL I guess. Thanks!

**Comment by jsumners** [comment]
This should be re-opened. Building against the 5.5.1 tag with "notify_nagios" enabled in the SPEC results in build failure.

The option is defined at https://github.com/collectd/collectd/blob/master/contrib/redhat/collectd.spec#L133

And the file is included at https://github.com/collectd/collectd/blob/master/contrib/redhat/collectd.spec#L1988

But there isn't an RPM definition at https://github.com/collectd/collectd/blob/master/contrib/redhat/collectd.spec#L573

**Comment by mfournier** [comment]
@jsumners notify_nagios isn't part of the collectd-5.5 branch, only master. See https://github.com/collectd/collectd/issues/1531#issuecomment-177089999

**Comment by jsumners** [comment]
Sorry, I must've copied the spec before switching branches. Carry on.
