### ISSUE TITLE
5.5.1 release?

### ISSUE THREAD

**Issue by hnyman** [collectd/collectd#1536]
Version 5.5.1 was tagged 2 weeks ago and the .tar.gz file is also visible in http://collectd.org/files/

But as there has been no official announcement about the release, I wonder if that really is the final 5.5.1 release package, or if the 5.5.1 release is still on hold?

**Comment by mfournier** [comment]
It *is* the official release, please use it ! It's the best collectd release ever ;-)

FYI the debian, ubuntu and fedora distros already have updated their packages.

@octo still needs to update the website. We've discussed putting the static pages of the website in a git repo, so others can also take care of this, but the idea didn't materialize yet (hint, hint!) ;-)

**Comment by hnyman** [comment]
Thanks for info. Good to know that it is the release ;-)

In addition to the website, also here in Github the "Latest release" pointer on the "Releases" page still points to 5.5.0...
https://github.com/collectd/collectd/releases

**Comment by roycec** [comment]
The spec file in the 5.5.1 tar file shows version 5.5.0

**Comment by hnyman** [comment]
Any news on updates to the website and Github releases page?
They still reflect 5.5.0 as the newest release and 5.5.1 release notes are well hidden...

**Comment by kev009** [comment]
This can be closed

**Comment by matteocontrini** [comment]
Still not updated

**Comment by rubenk** [comment]
We're working on it.

**Comment by rubenk** [comment]
@octo just tagged and published 5.5.2, and the release notes for that release are on the website now.

**Comment by octo** [comment]
Superseded by 5.5.2.
