### ISSUE TITLE
Sending metrics failing after VPN re-establish

### ISSUE THREAD

**Issue by ojle** [collectd/collectd#1538]
We have collectd client sending metrics to collectd server via VPN using the Network plugin.
It happens from time to time that VPN breaks (and re-establish itself), but after that collectd client<>server communication 'breaks'.
With tcpdump I can see packets being sent from the client to the server, but nothing is received on the server end.
Only solution here is to restart collectd client service, and it will start 'working' again, packets will be received on the server end.

collectd-5.5.0-2.el7.x86_64
CentOS 7.1

**Comment by rubenk** [comment]
Collectd uses UDP which is a connectionless protocol. The data flow is also unidirectional, from client to server. If the packets leave your client but don't arrive on the server, perhaps some firewall in between is dropping them? If you're using IPTables and connection tracking this might be the case. Iirc connection tracking determines udp connections based on source and destination port, and that might explain why restarting the client will make it work again. New source port => new connection tracking entry.

I'm afraid that from a Collectd point of view there's nothing much we can do about this. Perhaps disabling connection tracking works for you.

**Comment by cbz** [comment]
Stumbled across this while doing the same thing - I think your issue is that you are probably binding collectd to a specific IP address - associated with a virtual device which is disappearing when the openvpn connection is taken down.  Binding to a wildcard IP should fix this, either of these:

Listen 0.0.0.0
Listen "::"
