### ISSUE TITLE
collectd plugin for top command in linux

### ISSUE THREAD

**Issue by rkommine** [collectd/collectd#1541]
Hi,

Recently I started using collectd for monitoring multiple linux servers usage. It is very helpful. But From the documentation I can't find any plugin to collect "top" output from the linux servers.

Is is possible to collect the below command output from collectd:

```
root@ips1:~# top
top - 11:31:49 up 8 days, 21:16,  2 users,  load average: 0.00, 0.01, 0.05
Tasks: 160 total,   2 running, 157 sleeping,   1 stopped,   0 zombie
%Cpu(s):  0.4 us,  0.1 sy,  0.0 ni, 99.5 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem:   4047212 total,  1576504 used,  2470708 free,   244848 buffers
KiB Swap:  4192252 total,        0 used,  4192252 free.   952280 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
    1 root      20   0   33900   4368   2680 S   0.0  0.1   0:02.26 init
    2 root      20   0       0      0      0 S   0.0  0.0   0:00.10 kthreadd
    3 root      20   0       0      0      0 S   0.0  0.0   0:08.32 ksoftirqd/0
    4 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kworker/0:0
    5 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kworker/0:0H
    7 root      20   0       0      0      0 R   0.0  0.0   1:33.62 rcu_sched
    8 root      20   0       0      0      0 S   0.0  0.0   0:00.00 rcu_bh

```

Thanks in advance.

Regards,
Ramakrishna

**Comment by rubenk** [comment]
Not verbatim no, but you can use the 'processes', 'uptime' and 'load' plugins to get something similar.

**Comment by newbeetracy** [comment]
Could you give a specific example of how to use those three combined to accomplish that?

**Comment by rubenk** [comment]
Just enable them and create graphs of the output.

**Comment by rubenk** [comment]
If you need help using collectd, please use the collectd mailing list or the #collectd IRC channel. We'd like to keep the github issue tracker for bugreports and patch reviews.

**Comment by michelgokan** [comment]
I wrote a similar plugin. You can find it here: https://github.com/michelgokan/collectd-top

**Comment by abedegno** [comment]
I have written a similar plugin, except it's native: https://github.com/abedegno/top-collectd
