### ISSUE TITLE
modbus plugin always sets debug mode on libmodbus

### ISSUE THREAD

**Issue by matejv** [collectd/collectd#1554]
modbus plugin seems to call function modbus_set_debug from libmodbus irregardless of debug setting in collectd configuration. This results in a huge amount of logs such as:

> Feb 17 22:02:04 collectd: Waiting for a confirmation... 
Feb 17 22:02:04 collectd: <08><55><00><00><00><07><21><04><04><42><DA><66><66>
Feb 17 22:02:04 collectd: [08][56][00][00][00][06][21][04][09][D6][00][02]

Which is annoying.

Could the modbus plugin observe the collectd debug setting when using libmodbus functions?

**Comment by rubenk** [comment]
I think PR #1561 will fix that.

**Comment by rubenk** [comment]
Fixed by c6ec7654302659415defe4f497384ea0edc15e98
