### ISSUE TITLE
install from source in CentOS 7 doesn't create systemctl files

### ISSUE THREAD

**Issue by lawre** [collectd/collectd#1559]
I downloaded https://collectd.org/files/collectd-5.5.0.tar.gz and followed instructions to configure make make install.  The systemctl service was not created.  i.e. 'systemctl enable collectd|collectd.service' presents this error: "Failed to execute operation: No such file or directory".  collectd seems to work fine by starting with /opt/collectd/sbin/collectd.  I'm on CentOS 7.  thanks

**Comment by rubenk** [comment]
That's correct. You will need to copy the collectd.service file to the right location yourself. (Or just use Collectd from EPEL of course ;))
