### ISSUE TITLE
collectd 5.5.0 netlink plugin does not work on/support openbsd

### ISSUE THREAD

**Issue by jforman** [collectd/collectd#1562]
I'm running collectd-5.5.0 on an amd64 OpenBSD 5.8 machine. I've attempted to enable the netlink plugin below with the following config, but I get the noted error:

```
<Plugin netlink>
        Interface "re0"
        VerboseInterface "re0"
        IgnoreSelected false
</Plugin>
```

Error:
```
Feb 25 06:06:41 openbsd-test1 collectd[24377]: plugin_load: Could not find plugin "netlink" in /usr/local/lib/collectd
Feb 25 06:06:41 openbsd-test1 collectd[24377]: Found a configuration for the `netlink' plugin, but the plugin isn't loaded or didn't register a configuration callback.
Feb 25 06:06:41 openbsd-test1 collectd[24377]: Found a configuration for the `netlink' plugin, but the plugin isn't loaded or didn't register a configuration callback.
Feb 25 06:06:41 openbsd-test1 collectd[24377]: Found a configuration for the `netlink' plugin, but the plugin isn't loaded or didn't register a configuration callback.
```

I tried downloading collectd-5.5.0 from the project website and compiling it myself thinking it was an OpenBSD-packaging issue, but it seems that the module is not configured upon './configure' of the source:

`    netlink . . . . . . . no
`

Is there something I'm missing here? Does support for non-Linux OSen 'simply' need to be added for the netlink plugin? Is there another plugin that would work on OpenBSD to be able to collect network traffic statistics (bytes/sec)?

**Comment by rubenk** [comment]
Netlink is indeed a Linux-specific plugin. Perhaps the 'interface' plugin works for you?

**Comment by jforman** [comment]
I did a bit of digging into the collectd source, and the interface plugin is reporting errors, packets, and octets. For a bit I didn't realize, but it looks like octets is bytes transferred in this case. So it looks like the interface plugin does provide me with the bandwidth metrics I wanted. Is this correct?

**Comment by rubenk** [comment]
Yes, that's right, bytes are sometimes referred to as octets in the networking world. (https://en.wikipedia.org/wiki/Octet_(computing))
