### ISSUE TITLE
amqp_socket_open failed: Bad file descriptor

### ISSUE THREAD

**Issue by Mainframe2008** [collectd/collectd#1568]
When I try to connect to my local rabbitmq server I get:
Feb 26 15:10:02 grafana collectd[18411]: amqp plugin: amqp_socket_open failed: Bad file descriptor
Feb 26 15:10:02 grafana collectd[18411]: amqp plugin: camqp_connect failed. Will sleep for 10.000 seconds.
I have it installed on a CentOS 7 box having the following rpm's installed:
librabbitmq-0.5.2-1.el7.x86_64
collectd-sensors-5.5.1-2.el7.x86_64
collectd-5.5.1-2.el7.x86_64
collectd-amqp-5.5.1-2.el7.x86_64
rabbitmq-server-3.3.5-16.el7.noarch
collectd-dns-5.5.1-2.el7.x86_64

The amqp plugin is configured as follows:

`<Plugin amqp>
  <Subscribe "rabbitmq_collectd">
     Host "grafana.localdomain"
     Port 5672
     VHost "/"
     User "guest"
     Password "guest"
     Exchange "amq.fanout"
     Queue "collectd"
   </Subscribe>
</Plugin>`

**Comment by rubenk** [comment]
Hi,

Thanks for your report.
Could you check:
- If SELinux is enabled and if so, if you have any AVCs in your audit logs
- With netstat if there's something listening on port 5672
- If grafana.localdomain resolves to localhost

**Comment by rubenk** [comment]
Closing due to lack of feedback.
