### ISSUE TITLE
CollectD client in LUA

### ISSUE THREAD

**Issue by shashiranjan84** [collectd/collectd#1590]
Hi,

I would like to send metrics from [Kong](http://getKong.org) to collectD server, so was looking for some example. 
What would be best way to send data to CollectD? 
What are the protocol supported, UDP or HTTP or Both? 

Here client would be written LUA.

Also If I want to develop a plugin for Kong in CollectD, do we have any guide for that?

Thanks
Shashi
Mashape

**Comment by rubenk** [comment]
Hi,

There's some information about the collectd protocol at https://collectd.org/wiki/index.php/Binary_protocol and about the plugin structure at https://collectd.org/wiki/index.php/Plugin_architecture.

We try to keep this issue tracker for bugreports. If you need more help, please try the mailing list or our IRC channel.
