### ISSUE TITLE
Error while doing "make" at write_kafka plugin

### ISSUE THREAD

**Issue by kimbyeonggi** [collectd/collectd#1591]
There is an error while trying to do "make" at write_kafka plugin, which shows rd_kafka_set_logger is deprecated. 

It seems that the line 118 in write_kafka.c should be changed from the function to rd_kafka_conf_set_log_cb. 

Please check it out! Thanks in advance.

**Comment by rubenk** [comment]
Hi, thanks for your report. Your report is a bit light on details.
Please show us the actual error, versions of software used and how you are building.

**Comment by kimbyeonggi** [comment]
I'm using CentOS 7 as OS and the versions of both librdkafka and collectd what I used were master branch. I downloaded both of them via git clone command from https://github.com/edenhill/librdkafka/tree/master and https://github.com/collectd/collectd, respectively.

As the readme document at collectd described, I did execute ./build.sh to get configure file (ofc I needed to download lots of packages in advance since it has several dependencies, e.g., libtool, bison, etc.), and then ./configure, make, make install in order. However, as I mentioned, there was an error which shows write_kafka.c file used deprecated function, "rd_kafka_set_logger", so that it returned error.

**Comment by kimbyeonggi** [comment]
I attached my e-mail that I sent yesterday to collectd mailing list:

-----------------------------------------------------------------------------------------------------------------------------------------
Hello. I'm trying to use write_kafka Plugin in order to send the collected resource data to kafka, but it seems not working correctly. I've met several troubles while trying to use it as below:

The first problem happened at "make" stage of collectd. I downloaded librdkafka and collectd from git respectively, and both of branch were master. I did ./configure, make, and make install for librdkafka and it seems being done correctly, which means there were no errors while doing make & make install.

After that, I did same order for collectd, however, there was an error because the write_kafka.c file used deprecated function, rd_kafka_set_logger at line 118. I tried to either comment it out or change the function to rd_kafka_conf_set_log_cb, which is a configuration alternative of the above one as explained http://docs.confluent.io/2.0.0/clients/librdkafka/rdkafka_8h.html#a4ef59c71fef823375ad77c8313b2d862.

I then execute collectd with enabling write_kafka plugin, but both of ways showed very similar errors. At the first case (commenting out the line 118), the collectd at least worked correctly when the IP/DNS for broker(s) is wrongly set. The collectd tried to reconnect to the wrong IP/DNS repeatedly. However, if the value is set correctly, an error message was shown at /var/log/messages like that:  segfault at 0 ip 00007fd7cf72fa25 sp 00007fd7ca2ba7f0 error 4 in write_kafka.so[7fd7cf72d000+7000]

At the second case, i.e., changing the source code of write_kafka.c as I mentioned, it just showed error like "collectd[24166]: segfault at 180 ip 00007f3d08145fe0 sp 00007f3d07f1ac18 error 6 in librdkafka.so.1[7f3d08126000+55000]". In the both of error cases, collectd was automatically shutdown. 

Any advice or comments would be really helpful. Thanks in advance!

Best regards

**Comment by mfournier** [comment]
It's not the first time this logger build error pops up. Simply using the last released version of librdkafka instead of master solved the problem.

I'm not tracking librdkafka closely but regarding the recent changes in Kafka itself, I'd expect the next librdkafka release (and current master probably too) to also have significant changes.

**Comment by kimbyeonggi** [comment]
Hmm... It's weird. I tried to do it using the branch 0.9.0 of librdkafka, but the same error message was shown at different line as below:

write_kafka.c: In function 'kafka_handle':
write_kafka.c:118:9: error: 'rd_kafka_set_logger' is deprecated (declared at /usr/local/include/librdkafka/rdkafka.h:1800) [-Werror=deprecated-declarations]
         rd_kafka_set_logger(ctx->kafka, kafka_log);
         ^
cc1: all warnings being treated as errors
make[3]: *** [write_kafka_la-write_kafka.lo] Error 1

**Comment by rubenk** [comment]
Not that weird. Try version 0.8. 0.9 was only released in December and we didn't catch up with it yet.

**Comment by kimbyeonggi** [comment]
Ah, I see. It works well now. Thank you!
