### ISSUE TITLE
collectd-exec does not define N

### ISSUE THREAD

**Issue by michaelsalmon** [collectd/collectd#1598]
The man page for collectd-exec does not explain what a time of N is although one example uses it.

**Comment by rubenk** [comment]
I suspect it is just a typo and should be 'U'.

**Comment by michaelsalmon** [comment]
Nope, common.c line 1192:
`if (strcmp ("N", ptr) == 0) vl->time = cdtime ();`
I guess that it means now.

**Comment by rubenk** [comment]
I think you're right:
https://collectd.org/wiki/index.php/Plain_text_protocol#Description_4

**Comment by rubenk** [comment]
Would you like to send a patch?

**Comment by michaelsalmon** [comment]
AFAIK the documentation isn't in github.

**Comment by rubenk** [comment]
It is, at https://github.com/collectd/collectd/blob/master/src/collectd-exec.pod

**Comment by rubenk** [comment]
Thanks for patch, merged!
