### ISSUE TITLE
Write_graphite always add the host ?

### ISSUE THREAD

**Issue by Mqde** [collectd/collectd#1616]
Hello,

I'm actually trying to do exactly the same thing as the exemple data here : 
[https://collectd.org/wiki/index.php/Plugin:Write_Graphite](https://collectd.org/wiki/index.php/Plugin:Write_Graphite)

But without the **myhost_example_com**. Is it possible ?

Thanks

**Comment by rubenk** [comment]
Hi,

No, as far as I know always sends the host in write plugins.

If you need help using collectd, please use the collectd mailing list or the #collectd IRC channel. We'd like to keep the github issue tracker for bugreports and patch reviews.
