### ISSUE TITLE
calculating memory used

### ISSUE THREAD

**Issue by andrew-niaid** [collectd/collectd#1618]
I see discrepancies between collectd and other tools such as dstat on used memory statistics. Under certain workloads and conditions, this can be significant. Collectd seems to under-report used memory. It also appears there are a lot of opinions on how to calculate used memory. For comparison this is how collectd and dstat calculate it:

Collectd:
mem_used = mem_total - (mem_free + mem_buffered + mem_cached + mem_slab_total);

Dstat:
MemUsed = MemTotal - MemFree - Buffers - Cached - SReclaimable + Shmem 

1) collected doesn't differentiate between the two components of Slab (SReclaimable & SUnreclaim). Should it?

2) collectd also doesn't consider shmem when computing used memory, it probably should?

**Comment by rpv-tomsk** [comment]
>1) collected doesn't differentiate between the two components of Slab (SReclaimable & SUnreclaim). 
>Should it? 

http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/filesystems/proc.txt?id=HEAD#l913

Why it should be differentiated? Both SReclaimable and SUnreclaim are _used_ memory, do you agree? With this in mind, Dstat formula becomes wrong as it does not considers SUnreclaim as 'used'.

**Comment by rpv-tomsk** [comment]
>It also appears there are a lot of opinions on how to calculate used memory.

You are completely right in this. 

Interesting reading: https://support.zabbix.com/browse/ZBX-9142
Please note what Collectd does not provide 'Available memory' metric.

**Comment by andrew-niaid** [comment]
Perhaps collectd could provide MemAvailable if available? It seems to be the kernel's modern way of providing some of this information?

**Comment by rpv-tomsk** [comment]
We already have #1499 and #878 about this.

**Comment by andrew-niaid** [comment]
Ok, thanks.

**Comment by shotahino** [comment]
> mem_used = mem_total - (mem_free + mem_buffered + mem_cached + mem_slab_total);

Does `collectd` not count `mem_slab_total` as used memory?
