### ISSUE TITLE
Collectd mailing list is broken

### ISSUE THREAD

**Issue by jkugler** [collectd/collectd#1628]
Sorry to open a "bug" here, but my e-mail to the Collectd list owner is going unanswered.  My e-mail to the collectd list has not gone through, and looking at the archive there have been no posts added since March 3. Can somebody check the moderation queue? Or the mail server on which the list runs?

**Comment by maryamtahhan** [comment]
+1 I'm having the same issue

**Comment by rpv-tomsk** [comment]
@mfournier @rubenk - we need to solve this problem asap.

**Comment by rpv-tomsk** [comment]
What kind of assistance is needed to solve this problem?

**Comment by rubenk** [comment]
afaik @octo is the only one who has access.

**Comment by octo** [comment]
Hi everybody,

after much mucking with Debian's annoying Exim config, it turns out that the mailman process simply died. It's running again and the server is working though several weeks of backlog. Brace yourselves …

Best regards,
—octo

**Comment by jkugler** [comment]
Wooo! Thank you very much!
