### ISSUE TITLE
Failover behaviour for write plugin's nodes

### ISSUE THREAD

**Issue by zdenekpizl** [collectd/collectd#1629]
__Intended purpose__: sometimes it could be fine to have Nodes as a failover nodes. Such nodes should not be used to send data at first but should be used as second/backup set in case the executive ones cannot be reached.

__Scenario__(for write_graphite):

```
<Plugin "write_graphite">
 <Node "ActiveNode">
   Host "node01.domain.com"
   Port "2003"
-->   Role "active"
   ...
 </Node>
 <Node "FirstBackupNode">
   Host "node02.domain.com"
   Port "2003"
-->   Role "failover"
   ...
 </Node>
 <Node "SecondBackupNode">
   Host "node03.domain.com"
   Port "2003"
-->   Role "failover"
   ...
 </Node>
</Plugin>
```

When __ActiveNode__ starts to be unavailable, write plugin switch to next node, the one marked as Role "failover", if also this node is malfunction/not accessible, next failover node should be selected.

__Question__: Is that feature worth or could be this functionality fulfilled in different way?

Thank you, .zp.

**Comment by rubenk** [comment]
I think this is best left out of Collectd and better solved by putting a load balancer in front of your Graphite nodes, like HAProxy or Keepalived

**Comment by xneo64** [comment]
hi @rubenk 

I don't agree that putting a load balancer between your Graphite and Collectd will solve the failover problem. 
If said load balancer fails (similar to a node failing in @zdenekpizl 's scenario) one ends up in the same situation. If however Collectd is capable of fail over on the write plugins, it would be immune to this situation. 

This would be by far a superior solution as opposed to configuring two write plugins sending simultaneously (why waste bandwidth?)

**Comment by zdenekpizl** [comment]
+1 as I am still convinced failover feature would be a stellar functionality of write plugins.

**Comment by xneo64** [comment]
@rubenk can you re-open this issue please?
