### ISSUE TITLE
filecount: User filter

### ISSUE THREAD

**Issue by fcorneli** [collectd/collectd#163]
Sometimes you just want to list the files (under for example /tmp) that are owned by a certain process (for example owned by the jboss user). A "User" plugin attribute that allows you to filter on file ownership would be interesting.

**Comment by sunkuranganath** [comment]
@fcorneli and @tokkee do you see this as relevant still? 
This has been open for a long time, is there still an interest to implement this?

**Comment by fcorneli** [comment]
@sunkuranganath I no longer have a need for this feature, let along time to implement it.

**Comment by sunkuranganath** [comment]
Thanks for the response. We will close the issue.
