### ISSUE TITLE
 http://collectd.org/temp/ContactMe.chef

### ISSUE THREAD

**Issue by lamont-granquist** [collectd/collectd#1632]
So a long time ago it looks like chef-client was hammering collectd.org a heck of a lot and a redirect was put in place to 302 based on the User-Agent in order to block chef-client from doing downloads of the collectd tarball.

We inadvertently bypassed this sometime ago when we screwed up the User-Agent in chef-client:

https://github.com/chef/chef/issues/4074

We then mitigated that problem in Chef 12.6.0 and went back to having the right User-Agent again ( via https://github.com/chef/chef/commit/010392858c2a3a036578b681085704ed1971ab21 although the connection between that fix and the UserAgent follows an incredibly tortured path and won't be obvious from the commit what happened there ).

It looks like the ContactMe.chef file references Miah's version of the collectd cookbook and that cookbook was transferred into ownership of @coderanger a long time ago(?), and at any rate that cookbook is gone now.  I suspect that the issues that were happening were related to bad acting on the part of very old implementations of remote_file in core-chef.

The code in remote_file has used etags and last-modified flags for idempotency for some time now.   Any collectd cookbook running on a halfway modern version of chef-client should download the file once and then only hit the API to see if it changed and get back a lightweight 304 Not Modified instead of a 200 and a download.   If we can even track down the collectd cookbooks that users are using we can also fix that with some appropriate idempotency checks around if the downloaded file exists or not and avoid the need to hit the API to get back the 304.

You should be able to find Knife 12.5.1 clients hitting your API looking something like:

    Chef Knife/12.5.1 (ruby-2.1.6-p336; ohai-8.7.0; x86_64-linux; +https://chef.io)

Those are actually chef-client 12.5.1's hitting the API.  If they're not misbehaving too badly could you considering relaxing the restriction to only older versions of chef-client?

**Comment by lamont-granquist** [comment]
Looks like this is the original mailing list thread from 3 years ago:

http://mailman.verplant.org/pipermail/collectd/2013-February/005611.html

**Comment by lamont-granquist** [comment]
So from @octo's original e-mail there:

```

So, ideally there'd be a check like:

  if not installed(collectd):
    install(collectd)

An alternative might be to keep track of Chef runs and include a
If-Modified-Since header in the request. The web server would then
simply answer with "304 Not Modified" is appropriate.
```

That got done ages ago in core chef in the remote_file resource.  Should have been roughly around the 11.6.0-ish timeframe (I can dig up exactly when it started being stable and working if that becomes necessary).   Since we modified the core resource to do this by default, then every cookbook that used remote_file to download the tarball would have picked up this behavior.

So I think this is basically fixed?

Something like this would probably be a better ban regex:

```
/Chef Client\/(0\.|10\.|11\.[0-5]\.)/
```

We skipped from 0.10.10 to 10.12.0 so you just need to ban these version numbers:

- 0.*
- 10.*
- 11.[0-5].*

**Comment by lamont-granquist** [comment]
feel free to ban as much extra of the chef 11 'versionspace' as you like if it makes your logs look better as well -- those people aren't getting any useful support and need to upgrade anyway.

**Comment by rubenk** [comment]
CC @octo

**Comment by octo** [comment]
Hi @lamont-granquist,

you're right, the problem back in the day was Miah's cookbook that was hammering our server. I was assuming that the Chef community would move on and therefore only put these checks in place for the 5.1.0 gzipped tarball.

In the last 24 hours, there were 3520 requests made by Chef, of which *one* was redirected to the "ContactMe.chef" page. I think it's safe to assume that this protection is no longer needed, so I've just disabled it.

Best regards,
—octo
