### ISSUE TITLE
Collectd with  MySQL Plugin - Database level metrics are same for all.

### ISSUE THREAD

**Issue by tuxmithun** [collectd/collectd#1643]
Collectd with MySQL Plugin when used with Graphite to monitor the MySQL Infrastructure, is returning similar graphs for the metrics on all databases (though the usage activity of the databases are all different).

End Result: The graphs for all the databases are same.

**Comment by tuxmithun** [comment]
![screenshot from 2016-04-01 18 19 37](https://cloud.githubusercontent.com/assets/11497876/14207233/7c951612-f836-11e5-84dc-2c0c424b1c2f.png)

Updated with a screen shot

**Comment by tuxmithun** [comment]
Enclosing the part of the collectd.conf

<Plugin "mysql">
	<Database "stockopedia">
		Host "localhost"
		User "collectd"
		Password "secretpass"
	</Database>

        <Database "stockopedia_prices">
                Host "localhost"
                User "collectd"
                Password "secretpass"
        </Database>


	<Database "stockopedia_archives">
		Host "localhost"
		User "collectd"
		Password "secretpass"
	 </Database>
	
	<Database "stockopedia_archives_international">
		Host "localhost"
		User "collectd"
		Password "secretpass"
	</Database>

</Plugin>

**Comment by rubenk** [comment]
The statistics are the output of "SHOW GLOBAL STATUS" and are not per database.

**Comment by tuxmithun** [comment]
@rubenk Thanks for the quick reply.
 How can i get the metrics for each database, with the collectd then.

**Comment by rubenk** [comment]
You can't. I don't think MySQL provides these statistics per database.

**Comment by tuxmithun** [comment]
@rubenk Thanks. Then, why does the collectd.conf need us to mention the database name in the conf as I mentioned above? Can i get rid rid of them.

**Comment by rubenk** [comment]
The manual says "A Database block defines one connection to a MySQL database.". This is a bit misleading in that is actually defines one connection to a MySQL server instance. In your case you'll only need to define one of them and you can get rid of the rest.
