### ISSUE TITLE
Unable to build my own plugin

### ISSUE THREAD

**Issue by wcarrell** [collectd/collectd#1651]
I'm unable to build my own plugin because when I change configure.ac with a change of no substance, i.e. a blank line, the build yields the following error:

checking atasmart.h presence... no
checking for atasmart.h... no
./configure: line 26641: syntax error near unexpected token `LIBNOTIFY,'
./configure: line 26641: `PKG_CHECK_MODULES(LIBNOTIFY, libnotify,'
make: *** [config.status] Error 2

I get the same error when I try making a change of substance.
I can build the default system by:

/home/wcarrell> rm -rf collectd-5.5.0/
/home/wcarrell> tar jxf collectd-5.5.0.tar.bz2
/home/wcarrell> cd collectd-5.5.0/
/home/wcarrell/collectd-5.5.0> autoconf
/home/wcarrell/collectd-5.5.0> ./configure
lots of configure messages
/home/wcarrell/collectd-5.5.0> automake
/home/wcarrell/collectd-5.5.0> make all
lots of make messages
 
If instead I:

/home/wcarrell> rm -rf collectd-5.5.0/
/home/wcarrell> tar jxf collectd-5.5.0.tar.bz2
/home/wcarrell> cd collectd-5.5.0/
/home/wcarrell/collectd-5.5.0/ emacs configure.ac  ---> adding a blank line at the first blank line
/home/wcarrell/collectd-5.5.0> autoconf
/home/wcarrell/collectd-5.5.0> ./configure
lots of configure messages
/home/wcarrell/collectd-5.5.0> automake
/home/wcarrell/collectd-5.5.0> make all
some make messages
lots of configure messages
...
checking atasmart.h usability... no
checking atasmart.h presence... no
checking for atasmart.h... no
./configure: line 26641: syntax error near unexpected token `LIBNOTIFY,'
./configure: line 26641: `PKG_CHECK_MODULES(LIBNOTIFY, libnotify,'
make: *** [config.status] Error 2

I observe that configure is significantly different after "make all" than it was before.
I'll admit to being new to autoconf and automake, and further to being about 10 years removed from my last encounter with make.  Thus, I might be doing something stupid.  If so, just tell me...

Version information that may be of interest:

/home/wcarrell/collectd-5.5.0> uname -a
Linux wcarrell.fmr.com 2.6.32-573.7.1.el6.x86_64 #1 SMP Tue Sep 22 08:34:17 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
/home/wcarrell/collectd-5.5.0> autoconf --version
autoconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.
/home/wcarrell/collectd-5.5.0> automake --version
automake (GNU automake) 1.14.1
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.

**Comment by rubenk** [comment]
You need to install pkg-config.

**Comment by wcarrell** [comment]
I’m not familiar with it, but, I think it is installed.

/home/wcarrell/collectd-5.5.0> yum list pkg-config
Loaded plugins: security
Error: No matching Packages to list
/home/wcarrell/collectd-5.5.0> yum list pkg*
Loaded plugins: security
Installed Packages
pkgconfig.x86_64 1:0.23-9.1.el6 @anaconda-OracleLinuxServer-201410181705.x86_64/6.6
/home/wcarrell/collectd-5.5.0> which pkg-config
/usr/bin/pkg-config
/home/wcarrell/collectd-5.5.0> sudo find / -name pkg-config
/opt/chef/embedded/bin/pkg-config
/etc/bash_completion.d/pkg-config
/usr/bin/pkg-config
/usr/share/bash-completion/pkg-config/
/home/wcarrell/collectd-5.5.0> man pkg-config  ---> works

WCIII

**Comment by rubenk** [comment]
Can you try running ./build.sh instead of the manual autoconf; automake dance?
Also, we don't really support modifying configure.ac from the tarball. You might have better luck building from git instead.

**Comment by wcarrell** [comment]
I don’t find a build.sh in the tarball.

I’ll move to the git source tree.
I see your point.  Creating a new plug-in is development not configuration.

You can close this case as you see fit.

I’ll open another if I have trouble with the git source tree.

Thanks for your prompt response.

WCIII

**Comment by rubenk** [comment]
Very well, let us know if you need help.
