### ISSUE TITLE
How to retrieve a String data as a return value?

### ISSUE THREAD

**Issue by kimbyeonggi** [collectd/collectd#1652]
Hello.

I'm testing Collectd SNMP Plugin now, and I noticed that the Collectd's types.db defines number values only. 

Is there any way to get some string values as a return value? For example, there are some string values as below:

# snmpwalk -v2c -c redhat localhost system
SNMPv2-MIB::sysDescr.0 = STRING: Linux localhost.localdomain 3.10.0-123.el7.x86_64 #1 SMP Mon May 5 11:16:57 EDT 2014 x86_64
SNMPv2-MIB::sysObjectID.0 = OID: NET-SNMP-MIB::netSnmpAgentOIDs.10
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (101376) 0:16:53.76
SNMPv2-MIB::sysContact.0 = STRING: UNIX Admin <admin@example.com>
SNMPv2-MIB::sysName.0 = STRING: localhost.localdomain
SNMPv2-MIB::sysLocation.0 = STRING: Datacenter, Row 4, Rack 3
[output truncated]

If I want to get the value related to SNMPv2-MIB::sysLocation.0 mib, how collectd.conf should be set?

Thanks in advance!

**Comment by rubenk** [comment]
Hi,

What you want is not possible, Collectd only works with numbers, not with strings.

**Comment by cybafelo** [comment]
This really sucks - this means that the snmp plugin only does half of the work.

**Comment by cybafelo** [comment]
Also - it IS possible its just not coded yet - i understand its all open source and everything - but closing an issue DOES NOT MAKE IT GO AWAY.

**Comment by rubenk** [comment]
Leaving it open for years doesn't make it go away either.

**Comment by feld** [comment]
AIUI the way this would normally work in something like Influx or Prometheus is you'd have the value be something like 0 and you'd embed the string in a label/tag. Unfortunately there is no way to add custom labels/tags unless we extend those write plugins somehow, so I don't see a clear way forward at the moment either

**Comment by eero-t** [comment]
@feld Main things that `collectd-6.0` branch adds, is OpenTelemetry support, metric families, and metric **labels**.

Here's an example of changes required to migrate plugin to v6 API: https://github.com/collectd/collectd/pull/3823/files

For more info, see notes for first v6-rc release _and_ the docs linked by it: https://github.com/collectd/collectd/releases/tag/collectd-6.0.0.rc0
