### ISSUE TITLE
Can collectd-snmp use ifOperStatus to include/exclude an interface for polling?

### ISSUE THREAD

**Issue by gregvolk** [collectd/collectd#1653]
I am experimenting with using collectd as a possible replacement for my current SNMP polling software and want to know if there is a config option to evaluate ifOperStatus (link up/down) as a basis for polling an interface. I have searched through the FAQs and other documentation about this but have come up empty.

I have included a config snippet below that polls a Cisco Nexus router for traffic per-port, NXOS CPU utilization and NXOS Memory utilization.This config works, but it has the unintended result of polling and storing traffic information for all 48 physical interfaces when I am only interested in the data from the six interfaces that are actually link-up.

I looked at the collectd-filter documentation (https://collectd.org/documentation/manpages/collectd.conf.5.shtml#filter_configuration) but I'm having trouble figuring out if that applies to SNMP calls and how I would incorporate ifOperStatus checking into it. 

If ifOperStatus evaluation is possible, can someone post a config example that does that? 

Thank you

```
<Plugin snmp>
   <Data "std_traffic">
        Type "if_octets"
        Table true
        Instance "IF-MIB::ifDescr"
        Values "IF-MIB::ifHCInOctets" "IF-MIB::ifHCOutOctets"
   </Data>
   <Data "cisco_nxos_cpu">
        Type "percent"
        Table false
        Instance "nxos_cpu"
        Values ".1.3.6.1.4.1.9.9.305.1.1.1.0"
   </Data>
   <Data "cisco_nxos_mem">
        Type "percent"
        Table false
        Instance "nxos_mem"
        Values ".1.3.6.1.4.1.9.9.305.1.1.2.0"
   </Data>
   <Host "myrouter">
       Address "myrouter"
       Version 2
       Community "myrocommunity"
       Collect "std_traffic" "cisco_nxos_cpu" "cisco_nxos_mem"
       Interval 60
   </Host>
</Plugin>
```

**Comment by rubenk** [comment]
Hi,

Collectd doesn't have an option for evaluating ifOperStatus and (as you've figured out) indeed polls all ports.
