### ISSUE TITLE
Individual container level resource statistics in collectd

### ISSUE THREAD

**Issue by kpnarayanan** [collectd/collectd#1654]
Hello all,

I am using collectd to gather resource information / data of VMs and the host. I am looking for a plugin in collectd which can provide resource information of individual containers that are running on the host. 

May I kindly know is there a plugin that exist already for collectd? If not, are there any open source plugins which can be integrated in collectd that can provide this information? If yes, can anybody please share their details.

Thanks,
Krishnaprasad

**Comment by rubenk** [comment]
Hi,

There's the cgroups plugin (https://collectd.org/wiki/index.php/Plugin:cgroups). Other than that Collectd has no special support for containers.

**Comment by kpnarayanan** [comment]
Hi,

Thanks for the reply. I see that the cgroups plugin provides information only about the overall cpu / cpu usage. May I know is there a plan to extend / enhance the plugin to provide information about the other resources namely memory,  disk read, write and network IO?

Thanks,
Krishnaprasad

**Comment by rubenk** [comment]
There are a few PR's open for reading memory stats. I'm not aware of anyone working on measuring disk and network I/O.
