### ISSUE TITLE
write_kafka.c:40:18: fatal error: zlib.h: No such file or directory

### ISSUE THREAD

**Issue by bbhandari** [collectd/collectd#1658]
I installed  librdkafka-devel-0.9.0-1.el7.remi.x86_64.rpm. But while  installing the collectd, m getting the following errors.
write_kafka.c:119:6: error: 'rd_kafka_set_logger' is deprecated (declared at /usr/include/librdkafka/rdkafka.h:1800) [-Werror=deprecated-declarations]
      rd_kafka_set_logger(ctx->kafka, kafka_log);
      ^
cc1: all warnings being treated as errors
Any ideas ?

**Comment by rubenk** [comment]
rdkafka 0.9 is too new, you'll need 0.8. See also #1591
