### ISSUE TITLE
collectd with kafka server.

### ISSUE THREAD

**Issue by bbhandari** [collectd/collectd#1659]
write_kafka plugin is throwing the following errors, do i have to make any changes on the kafka server to listen to the client ???
86.52.42.234:9092/bootstrap: Failed to connect to broker at 86-52-42-234:9092: Connection refused

**Comment by rubenk** [comment]
Please use the collectd mailing list or the #collectd IRC channel. We'd like to keep the github issue tracker for bugreports and patch reviews.
