### ISSUE TITLE
utils_avltree.c: 2 * bad assert ?

### ISSUE THREAD

**Issue by dcb314** [collectd/collectd#1660]
1.

[utils_avltree.c:248]: (warning) Logical disjunction always evaluates to true: b_bottom >= -1 || b_bottom <= 1.

Source code is

      assert ((b_bottom >= -1) || (b_bottom <= 1));

And a few lines further down:

[utils_avltree.c:258]: (warning) Logical disjunction always evaluates to true: b_bottom >= -1 || b_bottom <= 1.

gcc compiler flag -Wlogical-op would probably find this problem.

**Comment by rubenk** [comment]
You're looking at old code. This is fixed in master at 0cf5d26c
