### ISSUE TITLE
lt_libltdlc_LTX_preloaded_symbols undefined symbol

### ISSUE THREAD

**Issue by hergla** [collectd/collectd#1661]
Try to build on solaris 11.3 i get the following error:
[collectd_build_error.txt](https://github.com/collectd/collectd/files/208367/collectd_build_error.txt)

Making all in daemon
gmake[3]: Entering directory `/SOURCE/collectd/src/daemon'
  CCLD   collectd
Undefined                       first referenced
 symbol                             in file
lt_libltdlc_LTX_preloaded_symbols   ../../libltdl/.libs/libltdlc.a(libltdlc_la-ltdl.o)
ld: fatal: symbol referencing errors
collect2: error: ld returned 1 exit status

**Comment by rubenk** [comment]
Please share your build commandline, ./configure output and config.log as well.

**Comment by rubenk** [comment]
Closing this due to lack of feedback. Please open a new PR with full buil logs.

**Comment by omerlin** [comment]
Hello,

I have exactly the same issue on a Solaris 11.3
As you asked, please find attached the details.

[collectd-5.5.1_configure_output.txt](https://github.com/collectd/collectd/files/271932/collectd-5.5.1_configure_output.txt)

cheers,

**Comment by omerlin** [comment]
Is it possible to reopen the issue ?

**Comment by rubenk** [comment]
Sure. I can build Collectd successfully with gcc on Solaris 11. I don't have access to Sun Studio however.
Can you retry with gcc?

**Comment by arifcse019** [comment]
I am facing the same issue on a Solaris 11.3 zone. I am using gcc 4.8.2. Attached are

1) ./build.sh output
2) ./configure output anf config.log
3) ) make all install output
[build.sh-output.txt](https://github.com/collectd/collectd/files/341976/build.sh-output.txt)
[config-output.txt](https://github.com/collectd/collectd/files/341977/config-output.txt)
[config.log.txt](https://github.com/collectd/collectd/files/341986/config.log.txt)
[make-all-install-output.txt](https://github.com/collectd/collectd/files/341978/make-all-install-output.txt)

**Comment by rubenk** [comment]
I'm sorry, but I can't reproduce this, not even with Solaris Studio (tried both 12.4 and 12.5).
What are the versions of autoconf, automake, libtool and libltdl? I suspect this is a libtool issue.

**Comment by skrueger8** [comment]
Is it still broken when you do:

```
pkg install library/libtool/libltdl
```

?

**Comment by chbuescher** [comment]
I had the same problem with libtool on Solaris 11.3 - a "gmake V=1" gives the error message:
libtool: link: not configured to extract global symbols from dlpreopened files
The compile succeeded after doing a "pkg install developer/build/libtool".

**Comment by rubenk** [comment]
Closing stale issue.
