### ISSUE TITLE
Name of the CSV file containing power consumption of the server

### ISSUE THREAD

**Issue by kpnarayanan** [collectd/collectd#1663]
Hallo all,

In the IPMI plugin of collectd, can somebody describe the name of the csv file which contains the total power consumed by the server?

May I know is this the name of the file - current-Pwr Consumption system_board (7.1)-2016-04-07 

I am using collectd version 5.5.

Thanks,
Krishnaprasad

**Comment by rubenk** [comment]
Please use the collectd mailing list or the #collectd IRC channel. We'd like to keep the github issue tracker for bugreports and patch reviews.
