### ISSUE TITLE
Digest auth initial 401 causes plugin to be suspended

### ISSUE THREAD

**Issue by druchoo** [collectd/collectd#1666]
The initial HTTP/1.0 401 Unauthorized is seen as a failure and causes the plugin to be suspended.

config:

> LoadPlugin curl_json
> \<Plugin "curl_json"\>
>   Interval 60
>   \<URL "http://localhost:9990/management/core-service/platform-mbean/type/garbage-collector?operation=resource&recursive=true&include-runtime=true&json.pretty=1"\>
>    Instance "jboss-memory"
>    User "admin"
>    Password "password"
>    Digest true
>    \<Key "heap-memory-usage/used"\>
>      Type "gauge"
>    \</Key\>
>   \</URL\>
> \</Plugin\>

Log error:
>Apr 11 17:42:13 10 collectd[18727]: read-function of plugin `curl_json-jboss-garbagecollector-http://localhost:9990/management/core-service/platform-mbean/type/garbage-collector?operation=resource&recursive=true&include-runtime=true&json.pretty=1' failed. Will suspend it for 120.000 seconds.

**Comment by rpv-tomsk** [comment]
Why do you consider this as Collectd problem? Could you please provide more debug info?

As I see, provided 'Log error' and 'config' does not match (Instance name in config - 'jboss-memory' but 'jboss-garbagecollector' in error log), so your problem may be caused by errors in config.

**Comment by druchoo** [comment]
@rpv-tomsk,

Apologies, copied the wrong line from log... Anyway the real issue seems to be when running collectd as a service under collectdmon, configs are loaded twice (#1647). This is most likely causing Digest Auth to act strangely. Closing issue.
