### ISSUE TITLE
SIGSEGV in network_receive (master branch)

### ISSUE THREAD

**Issue by sjcliffe** [collectd/collectd#1667]
collectd server compiled from git clone yesterday crashed as soon as I brought up a collectd client on another machine:

Core was generated by `/packages/collectd/sbin/collectd -C /etc/collectd/collectd.conf `
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007efff5fdac3c in network_receive () at network.c:2504
2504				ent->data = malloc (*ent->data);
 
Both systems running Ubuntu 14.04.4 (x86_64).

**Comment by sjcliffe** [comment]
Looks like #1646 is the culprit - it removed this line:

		memset (ent, 0, sizeof (receive_list_entry_t));

so ent is uninitialized.

**Comment by rubenk** [comment]
I replaced the memset with calloc, which zero-initializes ent, in 8bffdff5ed03031a9d7261476118b7d99a0fcd97. The malloc after it looks suspicious though.
