### ISSUE TITLE
collectd, write_graphite and hostnames

### ISSUE THREAD

**Issue by gameforce** [collectd/collectd#1668]
Is it possible to have the plugin write the hostname and not the fqdn?

For example it writes like this:
collectd.mtl.dfs_mtl_example_com.disk-sda4.disk_octets.write

And I would need it to write like this:
collectd.mtl.dfs.disk-sda4.disk_octets.write

collectd.mtl is my Prefix dfs.example.com is the fqdn

Thanks

**Comment by rubenk** [comment]
You should be able to disable UseFQDN and set Hostname to your short hostname in your collectd.conf

Please use the collectd mailing list or the #collectd IRC channel. We'd like to keep the github issue tracker for bugreports and patch reviews.
