### ISSUE TITLE
Collectd Aggregation Plugin for CPU Not working

### ISSUE THREAD

**Issue by subhashv** [collectd/collectd#1669]
I want to find aggregation for the CPU. Currently i have 16 CPU cores on my machine. I want the data by core and by state and i want to aggregate cpu total (adding all the core cpu avg) by state. Below is the configuration for collectd.
Am I doing something wrong? Please advice.

Collectd Version: 5.5.1
#TypesDB     "/usr/share/collectd/types.db" (Is Commented in collectd.conf)

LoadPlugin cpu

<Plugin cpu>
  ReportByCpu true
  ReportByState true
  ValuesPercentage true
</Plugin>

LoadPlugin aggregation

<Plugin "aggregation">
    <Aggregation>
        Plugin "cpu"
        Type "cpu"
        GroupBy "Host"
        GroupBy "TypeInstance"
        CalculateSum true
        CalculateAverage true
    </Aggregation>
</Plugin>

**Comment by rubenk** [comment]
Please use the collectd mailing list or the #collectd IRC channel. We'd like to keep the github issue tracker for bugreports and patch reviews.
