### ISSUE TITLE
processes: missing definition of cswitch_{vol,invol} in 5.5 branch

### ISSUE THREAD

**Issue by dago** [collectd/collectd#1674]
In the current 5.5 branch the definitions of `cswitch_vol` and `cswitch_invol` is missing:

```
  CC       processes.lo
processes.c: In function ‘ps_read’:
processes.c:2299:6: error: ‘procstat_entry_t {aka struct procstat_entry_s}’ has no member named ‘cswitch_vol’
   pse.cswitch_vol = -1;
      ^
processes.c:2300:6: error: ‘procstat_entry_t {aka struct procstat_entry_s}’ has no member named ‘cswitch_invol’
   pse.cswitch_invol = -1;
```

The full build logs can be inspected at
 * https://buildfarm.opencsw.org/buildbot/builders/collectd-55-solaris10-sparc/builds/0

**Comment by rubenk** [comment]
@mfournier any idea what happened here? mismerge, or is there a backport missing in the 5.5 branch?

**Comment by mfournier** [comment]
@dago is this the first build of the collectd-5.5 branch by the buildbot ? I'm under the impression this would date back from 1f0156c.

**Comment by dago** [comment]
Yes, this is the first build. I just added the 5.5 branch to buildbot. You can look at the log
  https://buildfarm.opencsw.org/buildbot/builders/collectd-55-solaris10-sparc/builds/0/steps/git/logs/stdio
to see the checked out revision c346dc6b18ee4215ccab911c1732c5c39a961baf.

**Comment by mfournier** [comment]
Yes, there was a gross mistake in the code @dago ! Thanks for reporting !

I'll keep track of the next buildbot build to make sure we're good.

By the way, is there a way to get email notifications of broken builds from the opencsw buildbot ? Or even better, have it integrated with the project's jenkins or github hooks ? (ie: build pull-requests on various solaris targets to catch this sort of problem before it gets merged)

**Comment by dago** [comment]
Sure, I already looked at the notification hooks but I haven't gotten around to configuring it. For now I can set up emails, to which address do you want the notification emails?

**Comment by landryb** [comment]
I can confirm that 5.5.1 shipped with https://github.com/collectd/collectd/commit/1f0156c5219ccae789355ac68dd19e8cd455db05 - and the build was broken on OpenBSD.
```
processes.c: In function 'ps_read':
processes.c:2049: error: 'procstat_entry_t' has no member named 'cswitch_vol'
processes.c:2050: error: 'procstat_entry_t' has no member named 'cswitch_invol'
```

Removing the two offending lines fixed the build. Maybe worth backporting 9d81184 to 5.5 branch ?

**Comment by rubenk** [comment]
@landryb 9d81184 was committed to the collectd-5.5 branch on May 2nd.
