### ISSUE TITLE
"service collectd stop" leads to "[collectd] <defunct>"

### ISSUE THREAD

**Issue by dllhlx** [collectd/collectd#1676]
hi, recently I find several machines of mine occurs - collectd became Zombie process after run command "service collectd stop", and the zombie collectd is "[collectd] <defunct>" which can not been killed unless os reboot. I wander why this happened and how to fix that, thx very much.

**Comment by rubenk** [comment]
Hi,

Please provide more details. What version of collectd, your configuration, what distro etc.

**Comment by dllhlx** [comment]
collectd:5.4.1/ Centos 6.7 /  kernel: 2.6.32

**Comment by rpv-tomsk** [comment]
Please provide us minimal Collectd configuration (config-file, simplified as much as possible) with reproducible problem.

**Comment by dllhlx** [comment]
my configure is :

FQDNLookup   false
Interval 30
LoadPlugin cpu
LoadPlugin disk
LoadPlugin interface
LoadPlugin load
LoadPlugin memory
LoadPlugin swap
LoadPlugin df
LoadPlugin tcpconns
LoadPlugin users
LoadPlugin processes
LoadPlugin syslog

LoadPlugin match_regex
<Chain PostCache>
  <Rule>
    <Match regex>
      Plugin "^ipmi$"
      Type "temperature$"
    </Match>
    Target write
  </Rule>

  <Rule>
    <Match regex>
      Plugin "[^(ipmi|tcpconns)$]"
    </Match>
    Target write
  </Rule>

  <Rule>
    <Match regex>
      Plugin "tcpconns$"
      PluginInstance ".*sum.*"
    </Match>
    Target write
  </Rule>
</Chain>

LoadPlugin write_graphite
<Plugin write_graphite>
  <Node "*****">
    Host "*******"
    Port "*****"
    Protocol "udp"
    #LogSendErrors true
    Prefix "h."
    #Postfix "collectd"
    #StoreRates true
    #AlwaysAppendDS false
    #EscapeCharacter "_"
  </Node>
</Plugin>
