### ISSUE TITLE
LVM plugin is undocumented

### ISSUE THREAD

**Issue by rubenk** [collectd/collectd#1679]
There's nothing in collectd.conf(5) that describes the LVM plugin.

**Comment by mfournier** [comment]
It's the case for every plugins which doesn't have any config options.

This isn't the first time someone gets confused about this, so maybe it would be an idea to add a simple line such as "plugin foo collects statistics from XYZ and currently doesn't have any configuration options", for each of them ?

**Comment by rubenk** [comment]
Sounds like a plan :)
