### ISSUE TITLE
LVM plugin: needs IgnoreSelected functionality

### ISSUE THREAD

**Issue by rubenk** [collectd/collectd#1680]
I'd like to exclude some volume groups from reporting, but this is currently not supported.

**Comment by mfournier** [comment]
Meanwhile you can already drop them using the filter chains system ;-)

**Comment by rubenk** [comment]
Heh, yes, I just figured that out ;)

**Comment by rubenk** [comment]
I removed the lvm plugin in 0e73c26f5670b2f11eecfdadaf545bcc7f260658
