### ISSUE TITLE
What does a Proxy do, if it can't reach the server?

### ISSUE THREAD

**Issue by guettli** [collectd/collectd#1683]
What does a collectd proxy do, if it can't reach the server?

1. Client contacts the proxy and wants to give him data
1. Proxy tries to connect to central server, but this fails (network outage)
1. What does the proxy do?

I could not find the answer here: https://collectd.org/wiki/index.php/Networking_introduction

Does the proxy accept the data from the client?

Does the proxy retry to connect the server N seconds later?

My related question an severfault: http://serverfault.com/questions/772023/collectd-elasticsearch-if-remote-host-cant-connect-to-central-elasticsearch

**Comment by rubenk** [comment]
See @mfourniers explanation in https://github.com/collectd/collectd/issues/1543#issuecomment-183049998
