### ISSUE TITLE
can type be hidden when send data to graphite?

### ISSUE THREAD

**Issue by wangxiangyu** [collectd/collectd#1685]
hi
I write my own python module and send data to graphite,  data type(eg. guage) is prefixed before type_instance. Can I hide data type?
<img width="309" alt="2016-04-27 3 24 41" src="https://cloud.githubusercontent.com/assets/3917969/14844792/963320c2-0c8c-11e6-9e56-96a5b96471d4.png">

**Comment by rubenk** [comment]
Hi,

That's hard to tell without seeing the source of your plugin.
Any reason why you don't use Collectd's write_graphite plugin? That one doesn't send the data type afaik.

**Comment by wangxiangyu** [comment]
@rubenk I use exactly the write_graphite plugin

**Comment by rubenk** [comment]
Please show us the source of your plugin then.

**Comment by rubenk** [comment]
Also show us your full configuration.
