### ISSUE TITLE
migrate-4-5.px incorrectly converts ps_code/ps_data to DERIVE

### ISSUE THREAD

**Issue by mgedmin** [collectd/collectd#1687]
I upgraded my collectd from version 4 to version 5, ran the migrate script, and now my syslog is full of these errors:
> Apr 27 16:16:04 fridge collectd[19609]: rrdtool plugin: rrd_update_r (/var/lib/collectd/rrd/fridge.lan/processes-apache2/ps_data.rrd) failed: /var/lib/collectd/rrd/fridge.lan/processes-apache2/ps_data.rrd: not a simple signed integer: '2539245568.000000'
> Apr 27 16:16:04 fridge collectd[19609]: rrdtool plugin: rrd_update_r (/var/lib/collectd/rrd/fridge.lan/processes-apache2/ps_code.rrd) failed: /var/lib/collectd/rrd/fridge.lan/processes-apache2/ps_code.rrd: not a simple signed integer: '67502080.000000'

AFAIU this is because DERIVE requires integers, while GAUGE supports floats.  These files use DERIVE because that's what the migrate script did:
```
$ /usr/lib/collectd/utils/migrate-4-5.px | grep apache2/ps_[cd][oa]
/usr/bin/rrdtool tune "/var/lib/collectd/rrd/fridge.lan/processes-apache2/ps_data.rrd" --data-source-type value:DERIVE --minimum value:0 --maximum value:U
/usr/bin/rrdtool tune "/var/lib/collectd/rrd/fridge.lan/processes-apache2/ps_code.rrd" --data-source-type value:DERIVE --minimum value:0 --maximum value:U
```

/usr/share/collectd/types.db says ps_code and ps_data are supposed to be GAUGE, not DERIVE.

So this looks like a [bug in the migration script](https://github.com/collectd/collectd/blob/db4a13bdf37b1103c2014261458323e26b034eec/contrib/migrate-4-5.px#L107-L108).

Additionally, the [wiki](https://collectd.org/wiki/index.php/V4_to_v5_migration_guide) also incorrectly states that
> Traditionally, collectd supported COUNTER and GAUGE data sources. However, the DERIVE data source type is more appropriate in 99 % of all cases.

and lists
> ps_code
> ps_data

among the types that should be converted to DERIVE.

**Comment by octo** [comment]
The list in the wiki was very likely generated from the migration script. A fix for this is coming up.
