### ISSUE TITLE
The SMART plugin does not build/load, v.5.5.0

### ISSUE THREAD

**Issue by jefferyanderson** [collectd/collectd#1688]
I just built v5.5.0 today after making sure I had libatasmart-dev and libatasmart4 installed on my Debian 8 system.
The output of ./configure shows me 
`"smart......yes"`

I don’t see any smart-related issues when I configure:

```
machine@Ultron:~/collectd-5.5.0$ cat config.log | grep smart
configure:27263: checking atasmart.h usability
configure:27263: checking atasmart.h presence
configure:27263: checking for atasmart.h
configure:27285: checking for sk_disk_open in -latasmart
configure:27310: gcc -o conftest -g -O2     conftest.c -latasmart  -ldl  >&5
ac_cv_header_atasmart_h=yes
ac_cv_lib_atasmart_sk_disk_open=yes
BUILD_WITH_LIBATASMART_LIBS='-latasmart'
```

but when I attempt to use it, I get the following:
```
[2016-04-27 13:53:09] plugin_load: Could not find plugin "smart" in /opt/collectd/lib/collectd
[2016-04-27 13:53:09] Found a configuration for the `smart' plugin, but the plugin isn't loaded or didn't register a configuration callback.
[2016-04-27 13:53:09] Found a configuration for the `smart' plugin, but the plugin isn't loaded or didn't register a configuration callback.
```
and looking in the directory /opt/collectd/lib/collectd does indeed show there is nothing named smart.
Any help/guidance would be much appreciated.

**Comment by rpv-tomsk** [comment]
Please provide all commands you run to build / install collectd. ( configure ; make ; make install and their args)

Thanks.

**Comment by rubenk** [comment]
Just wanted to point out that you can also use the 5.5 repos as described on https://github.com/collectd/collectd-ci.

**Comment by rubenk** [comment]
Closing due to lack of response.

**Comment by rpv-tomsk** [comment]
Hi all.

I have just reproduced this issue on my test Debian 8 env. 
This happens due to missing libudev:

src/Makefile.am has following:

```
if BUILD_PLUGIN_SMART
if BUILD_WITH_LIBUDEV
pkglib_LTLIBRARIES += smart.la
smart_la_SOURCES = smart.c \
       utils_ignorelist.c utils_ignorelist.h
smart_la_CFLAGS = $(AM_CFLAGS) $(BUILD_WITH_LIBATASMART_CPPFLAGS)
smart_la_LDFLAGS = $(PLUGIN_LDFLAGS) $(BUILD_WITH_LIBATASMART_LDFLAGS)
smart_la_LIBADD = $(BUILD_WITH_LIBATASMART_LIBS) -ludev
endif
endif
```

so smart plugin does not compiled at all.

**Comment by rubenk** [comment]
Nice catch @rpv-tomsk. We should detect and warn about this in configure.ac

**Comment by rpv-tomsk** [comment]
Made #1724 for this.

Thanks @jefferyanderson.
