### ISSUE TITLE
Can't build from source on Mac OS X

### ISSUE THREAD

**Issue by ojilles** [collectd/collectd#169]
I get the following after running `./configure` on collectd 5.1.0:

```
config.guess: cannot create a temporary directory in /System/Library/Frameworks/JavaVM.framework/Versions/1.6.0/Home/bin/jar
configure: error: cannot guess build type; you must specify one
configure: error: ./configure failed for libltdl
```

However if I run `./configure -C` everything works fine!

EDIT: Later found the following reference as well: https://github.com/mxcl/homebrew/issues/11651

**Comment by rubenk** [comment]
Is this still an issue? I can build master just fine now on OSX.

**Comment by octo** [comment]
I'd vote for closing it – the autotools, collectd and homebrew all have changed significantly since 2012.

**Comment by rubenk** [comment]
Ok, @ojilles please feel free to reopen this if you're still having issues.
