### ISSUE TITLE
Please add support for rrd version 1.6

### ISSUE THREAD

**Issue by nirgal** [collectd/collectd#1691]
rrdtool version 1.6 was released 11 days ago.
https://github.com/oetiker/rrdtool-1.x/releases

The main change is that librrd_th is gone! One should use librrd.so whether thread safety is needed or not.

collected currently gets confused at configure time, failing to detect thread safe functions:
>     librrd  . . . . . . . yes (warning: librrd is not thread-safe)

I haven't tested, but I believe HAVE_THREADSAFE_LIBRRD will be false. This
will trigger a new set of code being compiled. Hopefully this will only trigger local mutex handling.

What is the proper way to fix this? Maybe
if pkg-config --atleast-version=1.6 librrd
then HAVE_THREADSAFE_LIBRRD should be true while still linking with basic -lrrd.

(Originally reported at https://bugs.debian.org/823012)

**Comment by rubenk** [comment]
This is fixed in https://github.com/collectd/collectd/commit/ef43260cd901847220c2a9de400579ff903ca13e

**Comment by mfournier** [comment]
@rubenk what do you think about cherry-picking ef43260 (and maybe other related patches) to the release branches ?

**Comment by rubenk** [comment]
Sorry for not doing this sooner, but I've just backported them to 5.4 and 5.5.
