### ISSUE TITLE
rrdcached failed with status -1

### ISSUE THREAD

**Issue by pluhmen** [collectd/collectd#170]
Hi!

I've setup servral debian wheezy machines with collectd 5.1. I'm using rrdached on the collecting machine in the datacenter. This machine gives me following error to syslog.

Nov  2 11:41:45 collect02 collectd[4912]: rrdcached plugin: rrdc_update (/var/lib/rrdcached/db/collectd/example.com/df-root/df_complex-free.rrd, [1351852905:5420044288.000000], 1) failed with status -1.
Nov  2 11:41:45 collect02 collectd[4912]: rrdcached plugin: rrdc_update (/var/lib/rrdcached/db/collectd/example.com/df-root/df_complex-reserved.rrd, [1351852905:349962240.000000], 1) failed with status -1.
Nov  2 11:41:45 collect02 collectd[4912]: rrdcached plugin: rrdc_update (/var/lib/rrdcached/db/collectd/example.com/df-root/df_complex-used.rrd, [1351852905:1205501952.000000], 1) failed with status -1.

I've searched for this error, but didn't found any useful, date/time are in sync, same used version, fresh install ...

The sending machines are 64bit installs the collecting ones x86.

Maybe someone can figure out what's wrong here.

Thank you in advance,
Tilo

**Comment by rubenk** [comment]
This seems to be the same issue as #739. As mentioned in https://github.com/collectd/collectd/issues/739#issuecomment-237542233, the df plugin maps both / and /root to the same plugin instance.
