### ISSUE TITLE
turbostat.c  DRAM statistics for additional processors

### ISSUE THREAD

**Issue by puttybug** [collectd/collectd#1711]
Hello,
I use an haswell cpu (id:0x3c) which is able to report DRAM statistic/RAPL values.
Unfortunately turbostat.c is not willing to provide these values due to an  switch(model)  check.

Compared with /usr/src/linux/drivers/powercap/intel_rapl.c: (4.4.8, also 4.5.4)
- some models are not handled in turbostat.c, but in intel_rapl.c
- some models handled in turbostat.c, but not in intel_rapl.c

Unfortunately i´m not able to read the c syntax very well, so it is likely possible i overlooked something.

I´ve attached an experimental version of a patch to discuss.

cheers
putty
[turbostat.c.patch.txt](https://github.com/collectd/collectd/files/268018/turbostat.c.patch.txt)

**Comment by Feandil** [comment]
Ok, this is strange: the upstream for turbostat does not consider that RAPL_DRAM is supported by haswell (0x3C): https://github.com/torvalds/linux/blob/master/tools/power/x86/turbostat/turbostat.c#L2642-L2651

At the same time, looking at the Intel® 64 and IA-32 Architectures
Software Developer’s Manual, volume 3 chapter 35.11, in the middle of table 35-27 indicates that MSR_DRAM_ENERGY_STATUS is supported...

I believe that the patch is wrong (it's enabling RAPL_DRAM for older architectures that do not support it), but a similar patch would work as soon as details are understood.

It may be worth it to open a bug upstream?

**Comment by octo** [comment]
Hi @puttybug and @Feandil!

Unfortunately we don't have the expertise to contribute to this problem. Did you open an upstream bug? Is there anything the *collectd* team can do to help you with this?

Best regards,
—octo

**Comment by Feandil** [comment]
Hi @octo !

Well, I can't reproduce it (I don't have such a system) so it's hard for me to open a bug upstream...
So unfortunately no, there is nothing you or I can do.

@puttybug You should try to reproduce it with the turbostat utility from the kernel and report back to them the issue, if you can reproduce.

Sorry

**Comment by octo** [comment]
No worries, just doing some housekeeping. @puttybug, if you have anything that we could do in *collectd*, please open another bug.

Best regards,
—octo
