### ISSUE TITLE
Collectd Aggregation Plugin for CPU Not working

### ISSUE THREAD

**Issue by hugofoliveira** [collectd/collectd#1715]
I want to find aggregation for the CPU, for that I use this configuration:

LoadPlugin aggregation
LoadPlugin cpu

```xml
<Plugin "aggregation">
  <Aggregation>
    Plugin "cpu"
    Type "system"
    GroupBy "Host"
    GroupBy "TypeInstance"
    CalculateSum true
    CalculateAverage true
  </Aggregation>
</Plugin>
```

But no results are generated.

I'm using the 5.5.0 version.

I try to subscribe in the collectd mailing list (http://mailman.verplant.org/listinfo/collectd) but I don't receive the confirmation mail.

**Comment by carlos-esantos** [comment]
Hello,
I already configure aggregation plugin and I believe that your configuration in wrong. CPU has two types: "cpu" and "percent". If you wanna aggregate only "system" information, you need to filter "TypeInstance" in tuple.

Regards,
Carlos Eduardo dos Santos.

**Comment by octo** [comment]
I think @carlos-esantos is correct and the config is wrong. Please also note that newer versions of *collectd* have specialized options for aggregating CPU metrics.
