### ISSUE TITLE
[Support] yum install collectd is using version 5.4.1

### ISSUE THREAD

**Issue by hijklmno** [collectd/collectd#1716]
Hi,

Not sure if this is the right place to post this, but would like yum to use the lastest collectd version (5.5.1) if possible. 

Right now when i run `yum list collectd --showduplicates`:
Available Packages
collectd.x86_64                                                         5.4.1-1.8.amzn1                                                          amzn-main    
collectd.x86_64                                                         5.4.1-1.10.amzn1                                                         amzn-updates

I am using AWS EC2 AMI (RHEL).

Thank you!

**Comment by rubenk** [comment]
Hi,

It looks like you're using Amazon's repos, so you'll need to talk to them if you need them to get a newer versions in their repositories. You can also use our repos at https://github.com/collectd/collectd-ci

**Comment by hijklmno** [comment]
awesome! somehow i missed your ci tool. will use that instead. thanks!
