### ISSUE TITLE
Redis collector question

### ISSUE THREAD

**Issue by jsbali** [collectd/collectd#1718]
Going through the redis code I see a pattern there are many lines like the below one.
redis_handle_info (rn->name, rr->str, "current_connections", "clients", "connected_clients", DS_TYPE_GAUGE);
So if I want to add a new metric I want published I need to add it and build collectd and deploy again.
My question is why can't this info be read from a file which can comprehend it and then we can keep adding and removing which would require just a restart.

On a broad subject this is not limited to redis only there is a common pattern in many systems where we 
call some monitoring endpoint look for certain key things, somehow figure out the value and then publish.

Can't all this be abstracted out as a general plugin architecture thing. where you have data wranglers which do this.

**Comment by rubenk** [comment]
Of course, everything can be solved by adding another layer of abstraction.
There's no reason why your idea can't work, it's all just code, but someone has to write it.

Rather than discussing ideas, it might help if you opened a PR with actual working code that implements it so we can discuss it.
