### ISSUE TITLE
disk plugin: Incorrect value disk_time when use UdevNameAttr option.

### ISSUE THREAD

**Issue by letonphat1988** [collectd/collectd#1721]
Hi all,
I'm using Disk plugin with UdevNameAttr option to collect my HDD system. But i'm getting incorrect value for disk_time counter which in minutes or more not miliseconds. I tried use sda/sdb instead and everything's correct. 
Note: my system's idle, i haven't run anything yet sothat  highvalue's impossible
this's my config for Disk plugin
![image](https://cloud.githubusercontent.com/assets/16660339/15502289/388853b4-21dd-11e6-9be1-ca06e46769f2.png)
These're the records after i use UdevNameAttr
![image](https://cloud.githubusercontent.com/assets/16660339/15502212/c29cb410-21dc-11e6-99b5-d76d14fdbeae.png)
And these're the records if i use device name (sda, sdb,...)
![image](https://cloud.githubusercontent.com/assets/16660339/15502434/11186aa2-21de-11e6-8e0c-ab68bb4f76a6.png)

Do you think this's a bug ? or please give me some advices to debug.

**Comment by rpv-tomsk** [comment]
`UdevNameAttr` does changes nothing in submitted values, it only affects output-name for block device.

1) Please show output of

udevadm info --query=all --name=/dev/sda

2) If you can, please build debug version of Collectd from sources (with configure --enable-debug) and run built Collectd in minimal configuration (with only required plugins - `disk`, `logfile` and ... plugin you use to submit values to display).

**Comment by rpv-tomsk** [comment]
Issue confirmed.

**Comment by rpv-tomsk** [comment]
> UdevNameAttr "ID_PATH"

Do not use that. It renames different block devices to the same name:

[2016-05-25 00:27:35] disk plugin: renaming sda2 => pci-0000:00:1f.2-scsi-0:0:0:0
[2016-05-25 00:27:35] disk plugin: renaming sda3 => pci-0000:00:1f.2-scsi-0:0:0:0

That causes all issues.

**Comment by letonphat1988** [comment]
Hi rpv-tomsk, sorry about my delay. I missed the github's email notification.
About this case, I checked again and we're having a big conflict between paritions with UdevNameAttr.  But in my system, I only want to get the counters of whole disk and don't need the counters per partitions.
Do you think we can solve this issue by ignoring all partitions ?

**Comment by rpv-tomsk** [comment]
Hi. At current 'disk' plugin implementation 'IgnoreList' option is applied after 'UdevNameAttr' option, so it is impossible to select only disk without partitions in your configuration.
Code needs to be patched to achive this.

**Comment by mrunge** [comment]
Based on the feedback in https://github.com/collectd/collectd/pull/3441 I'm closing this here.

**Comment by AHeinlein** [comment]
> Hi. At current 'disk' plugin implementation 'IgnoreList' option is applied after 'UdevNameAttr' option, so it is impossible to select only disk without partitions in your configuration. Code needs to be patched to achive this.

I just came across this while trying to find out why this is logging nothing:
```
<Plugin disk>
  Disk "sda"
  UdevNameAttr "ID_MODEL"
<Plugin>
```

I guess from the above that also including is done *after* the renaming, so that config actually selects nothing, right?

Would be good to have two lines about that in the man page, please.

**Comment by eero-t** [comment]
> Would be good to have two lines about that in the man page, please.

As this is already closed, could you file a separate ticket or (preferably) a PR for doing that?
