### ISSUE TITLE
default executable path is not the same with init config for 5.5.0 

### ISSUE THREAD

**Issue by Jack47** [collectd/collectd#1728]
default executable path is `/opt/collectd`, not the same with `COLLECTD=/usr/sbin/collectd` in `contrib/redhat/init.d-collectd`. I'm using collectd-5.5.0.tar.bz2

**Comment by mfournier** [comment]
This init script is not ment to be used as-is outside of the scope of the RPM package, for which the specfile is found in the same directory. It has a couple of redhat-specific bits in in too, so not even sure it works on other distros.
