### ISSUE TITLE
can collectd support sql server ?

### ISSUE THREAD

**Issue by dllhlx** [collectd/collectd#1729]
hi,
I find the libdbi-drivers can't support FreeTDS (provides access to MS SQL Server and Sybase) from the  libdbi-drivers driver, so collectd can't support sql server?

**Comment by tokkee** [comment]
According to http://libdbi-drivers.sourceforge.net/ libdbi does provide a driver for FreeTDS. collectd doesn't do anything special about DBI so whatever works with DBI elsewhere is expected to work with collectd as well. Do you see problems that only show up with collectd? If so, please describe those in more detail.

**Comment by dllhlx** [comment]
@tokkee  the problem as below:
```
May 30 09:06:03 l-test collectd[25935]: dbi plugin: `dbi_initialize' could not load any drivers. Please inst
all at least one `DBD' or check your installation.
May 30 09:06:03 l-test collectd[25935]: Initialization of plugin `dbi' failed with status -1. Plugin will be
 unloaded.
```

**Comment by tokkee** [comment]
That looks like DBI cannot find *any* drivers. How did you install DBI?

**Comment by dllhlx** [comment]
@tokkee 
According to http://libdbi-drivers.sourceforge.net/ libdbi does provide a driver for FreeTDS，so the DBI  which are appropriate for MS sql server can not be found and installed. I think so, is this correct?

**Comment by rubenk** [comment]
Yes, the error message clearly says it can't find any DBD drivers. Please answer tokkees question and show us how you installed DBI and the MS SQL drivers.

**Comment by rubenk** [comment]
@dllhlx ping?
