### ISSUE TITLE
OKAY-notification and missing values broken.

### ISSUE THREAD

**Issue by clopez** [collectd/collectd#173]
I have discovered that after a missing notification collectd will never send an OKAY-notification when the value gets received again.

This was working before commit 171a92c968cb41c314736b0d26f5a6ba2ae59666 After that not longer works.

How to test? Simple:

*  Make one of your monitored values to stop sending data and wait until getting the value-missing notification.

* Now make this value to send data back. You will never get the Ok-notification

**Comment by octo** [comment]
A patch for this issue is being discussed in #678.

**Comment by octo** [comment]
Closing this in favor of the PR – no need to have two issues for this.
