### ISSUE TITLE
Docs for resilient setup

### ISSUE THREAD

**Issue by guettli** [collectd/collectd#1734]
Since it came up here several times before, I please you (the experts) to provide some guidance for new comers to the topic "resilient setup"

It's ok, if collectd does not have a perfect solution yet. Please provide some pointers to the current state of the art.

Related:

https://github.com/collectd/collectd/issues/1683

https://github.com/collectd/collectd/issues/1543#issuecomment-183049998

**Comment by rubenk** [comment]
I'm not sure what you expect from us exactly. As you have read in the comments you quoted, there is no such thing as "resilient setup"

**Comment by guettli** [comment]
It is 100% ok if you don't provide resilient setup in collectd. It would help new comers if you provide docs how to get it by using third party tools.

It was just a hint that it might help new comers. Close this issue if you don't care.

**Comment by rubenk** [comment]
Can you explain more precisely then what it is you mean with resilient setup?
Perhaps you'd like to write something about it on our wiki?

**Comment by guettli** [comment]
For me "resilient setup" means:

 * network outages: the network connection between the data creator and the central data server can be down for about three days, and not data gets lost.
 * During network outage the data creator might crash or get rebooted, and not data gets lost.

Conclusion: The data gets queued on a non-volatile way (for example disk)

**Comment by rubenk** [comment]
Collectd doesn't provide those guarantees, you'll need some kind of high available queuing system. They are complex and have their own docs, books, trainings etc. I don't think we're in a good position to document how they work.
