### ISSUE TITLE
Oracle plugin - enable multiple threads?

### ISSUE THREAD

**Issue by natecarlson** [collectd/collectd#1753]
I'm polling a bunch of different DBs, and at a 10s interval, I miss data for them regularly.. digging, I found that the Oracle plugin runs everything in a single thread.

I tried to re-implement this changeset for the Oracle plugin:
https://github.com/collectd/collectd/pull/453/files
..but run into Oracle exceptions; I have a feeling that the OCI interface isn't entirely thread safe.

Anyone interested in helping someone who has a poor understanding of C (like me) get this to work?

**Comment by tokkee** [comment]
/cc @octo who wrote the plugin initially and may have further insights into OCIs multi-threaded behavior.

Can you provide more details about those exceptions? Are these actual errors reported by Oracle or does collectd crash? I have no idea about Oracle's interface and I cannot test it myself but the first step is to find out where things go wrong. Based on that, we can talk about the right solution (e.g. protection concurrent access to data that cannot be shared or adding multiple instances).

**Comment by rubenk** [comment]
Closing stale issue.
