### ISSUE TITLE
help me with set snmp plugin

### ISSUE THREAD

**Issue by mslee89** [collectd/collectd#1754]
hi.

collectd is very good program.

i'm setting snmp plugin. but I want a lot of settings.
about 200 ea.

how do setting snmp plugin?

help me.
thank you.

**Comment by rubenk** [comment]
It's all in the manpage: https://collectd.org/documentation/manpages/collectd-snmp.5.shtml

**Comment by mslee89** [comment]
My question is wrong.

i want a lot of hosts setting..
