### ISSUE TITLE
one more question

### ISSUE THREAD

**Issue by mslee89** [collectd/collectd#1755]
![default](https://cloud.githubusercontent.com/assets/18281890/15880002/435a6cd6-2d64-11e6-978d-d171ca5a2e3a.png)

**Comment by rpv-tomsk** [comment]
It's all in the man page: http://collectd.org/documentation/manpages/collectd-snmp.5.shtml#the_host_block

Also you can use http://collectd.org/documentation/manpages/collectd.conf.5.shtml#include_path_pattern

What is your problem?

**Comment by tokkee** [comment]
Let's keep this open for a few days to provide an easier way for further feedback.

@mslee89 please try to be more specific. What are you trying to do? What do you expect to happen and what happens instead? What is blocking you from doing what you're trying to do?

You say you want to configure a lot of hosts. Do you have problems writing the configuration? Does collectd not keep up with all hosts? …

**Comment by mslee89** [comment]
@tokkee hi

if i'm know to configure a lot of hosts and the <host> block addition settings.
but i need  host settings to about 200 ea 
this settings add manual configure?

**Comment by rpv-tomsk** [comment]
>this settings add manual configure?

You can write simple script (bash,perl, php, etc what you like) for this and generate config from list of your hosts. Collectd has no other way to discover your hosts.

**Comment by mslee89** [comment]
@rpv-tomsk 

thank you to you helped me.
