### ISSUE TITLE
question about Thraeds Value

### ISSUE THREAD

**Issue by mslee89** [collectd/collectd#1757]
hi.

![image](https://cloud.githubusercontent.com/assets/18281890/15915705/984d5b78-2e26-11e6-89b3-461175b5fc2c.png)

i'm settings 10 value to read, write threads.
checked top command to threads value.

![image](https://cloud.githubusercontent.com/assets/18281890/15915737/cf696020-2e26-11e6-8f2a-d2ba37907321.png)

why this threads values  15?

**Comment by rpv-tomsk** [comment]
At least, plugins can create own threads for their needs.

**Comment by rpv-tomsk** [comment]
Why this is a problem for you?

**Comment by mslee89** [comment]
i'm did setting read, write threads 5 values.

but threads runinng total 15 value.

why runinng threads 15 values ?

read threads = 5 value
write threads = 5 value
total(read, write) threads = 10 value



2016-06-09 15:03 GMT+09:00 Pavel Rochnyak <notifications@github.com>:

> Why this is a problem for you?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/collectd/collectd/issues/1757#issuecomment-224807435>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ARb1ooC8PLxyRlnhAnv-lpPXjLmAgCT8ks5qJ6ykgaJpZM4Ixixj>
> .
>

ᐧ

**Comment by rpv-tomsk** [comment]
At least you have +1 thread as 'main' thread. Also plugins can start their own threads for their needs.

**Comment by rubenk** [comment]
@mslee89 anything else we can help you with?

**Comment by mslee89** [comment]
@rubenk @rpv-tomsk  Thank you for the answer.
