### ISSUE TITLE
Skip rows in Table plugin

### ISSUE THREAD

**Issue by pinkra** [collectd/collectd#1761]
I have a file to read like the following and i use the Table plugin. Actually all values from StartTime to Errors are retrieved but the plugin logs some errors because it fails to read comments line (lines before StartTime). How can i avoid those errors? Can i skip comments lines?

```
Reading globbing filelist /tmp/EDO9zcrspj
Local and Remote metadata are synchronized, no sync needed.
Last full backup date: Wed Jun  8 02:00:18 2016
--------------[ Backup Statistics ]--------------
StartTime 1465430405.41 (Thu Jun  9 02:00:05 2016)
EndTime 1465430437.23 (Thu Jun  9 02:00:37 2016)
ElapsedTime 31.82 (31.82 seconds)
SourceFiles 45019
SourceFileSize 542769453 (518 MB)
NewFiles 45019
NewFileSize 542769453 (518 MB)
DeletedFiles 0
ChangedFiles 0
ChangedFileSize 0 (0 bytes)
ChangedDeltaSize 0 (0 bytes)
DeltaEntries 45019
RawDeltaSize 537682221 (513 MB)
TotalDestinationSizeChange 87676517 (83.6 MB)
Errors 0
-------------------------------------------------
```

**Comment by rubenk** [comment]
Hi,

I'm afraid not, the Table plugin doesn't have an option to skip certain lines. It really expects your file to be a valid table. It was mainly created for parsing files from /proc.

**Comment by l1ll1** [comment]
Hi,
Just a note that /proc/slabinfo (the canonical example on how to configure the table plugin) actually contains two rows which should be skipped

$ sudo cat /proc/slabinfo  | head -n 3
slabinfo - version: 2.1
# name            <active_objs> <num_objs> <objsize> <objperslab> <pagesperslab> : tunables <limit> <batchcount> <sharedfactor> : slabdata <active_slabs> <num_slabs> <sharedavail>
kvm_async_pf           0      0    136   30    1 : tunables    0    0    0 : slabdata      0      0      0

/proc/cgroups is in the same category

Annoyingly the first line in slabinfo is not even commented so we really need a config parameter to skip a defined number of lines.

Cheers,
--
Chris.
