### ISSUE TITLE
"sig_chld_action.sa_handler = SIG_IGN;" may leads to collectd Zombie status

### ISSUE THREAD

**Issue by dllhlx** [collectd/collectd#1762]
As the title indicates, if the collectd child process exit after the father process, and meanwhile the SIGCHLD is ignored by the collectd father process, so the collectd may become Zombie status.

**Comment by dllhlx** [comment]
My servers occurs 10+ collectd Zombies cases this week after exec cmd "service q-collectd stop".

**Comment by dllhlx** [comment]
@rubenk @octo  help, thx a lot.

**Comment by rubenk** [comment]
Please show more details: distro, complete configuration, collectd version.

**Comment by dllhlx** [comment]
I use collectd-5.4.1, my machine's version as below:
```
uname -a: Linux 6.32-358.23.2.el6.x86_64 #1 SMP Wed Oct 16 18:37:12 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
cat /etc/redhat-release CentOS release 6.4 (Final)
```
collectd zombie status as screenshot:
![alt text](/path/to/img.jpg)

**Comment by rubenk** [comment]
How do you start Collectd?

**Comment by rubenk** [comment]
Are there any include files in /etc/collectd.d?

**Comment by dllhlx** [comment]
I start collectd with command ```/home/q/collectd/sbin/collectd -C /home/q/collectd/etc/collectd.conf -P /var/run/q-collectd.pid```

**Comment by dllhlx** [comment]
@rubenk 
my collectd configure path as below:
```
[root@dl.liu ~]# ll /home/q/collectd/etc/collectd*
-rw-r--r-- 1 root root  100 Jun 29  2015 /home/q/collectd/etc/collectd.conf

/home/q/collectd/etc/collectd.d:
total 36
-rw-r--r-- 1 root root   918 Jan 26 18:53 base.conf
-rw-r--r-- 1 root root 28916 Jun 29  2015 collectd.conf.sample

[root@dl.liu ~]# cat /home/q/collectd/etc/collectd.conf
# used to override the default collectd.conf file.
Include "/home/q/collectd/etc/collectd.d/*.conf"
```

**Comment by rubenk** [comment]
So you start collectd by hand, and stop it with some kind of init script? What's in this q-collectd script?

Can you upgrade to 5.5.1, just to see if that fixes your issue?

**Comment by rubenk** [comment]
Ping?

**Comment by octo** [comment]
Stale for over a month.
