### ISSUE TITLE
Install collectd from github

### ISSUE THREAD

**Issue by ydaniv** [collectd/collectd#1766]
I'd like to install the latest straight from github (mostly for much needed statsd plugin fixes which aren't merged yet), but couldn't find any documentation for it anywhere.

Is it possible? I see that building the `configure` file is required. Are there instructions anywhere?

Thanks for this awesome tool and all the fish!

**Comment by rubenk** [comment]
Sure, you'll need to run ./build.sh after you clone from github. The instructions are at the bottom of https://github.com/collectd/collectd/blob/master/README

**Comment by ydaniv** [comment]
Oh! <facepalm> thanks. Looks quite intimidating though.
