### ISSUE TITLE
Make issue

### ISSUE THREAD

**Issue by sujithnss** [collectd/collectd#1767]
Hi Team

Im pretty new to collectd, I tried cloning the git project and tried configure/make and make install.
But during make I'm getting the below error

 **_make
Making all in libltdl
make[1]: Entering directory `/home/vagrant/Desktop/collectd/libltdl'
make[1]: *** No rule to make target `all'.  Stop.
make[1]: Leaving directory `/home/vagrant/Desktop/collectd/libltdl'
make: *** [all-recursive] Error 1_**

Any help...

Best Regards
Sujith P V

**Comment by rubenk** [comment]
Hi,

If you're new to collectd, my advice would be to start with the collectd packages provided by your distribution, or, if you must, by downloading the tar file from the website.

Building collectd from a git checkout is a little bit more advanced. You'll need to follow the steps in https://github.com/collectd/collectd/blob/master/README#L943 carefully. My guess is you missed one of those steps, but there's no telling which one.

Please describe, in detail, what you did, and include the output of all the commands you ran.
