### ISSUE TITLE
change the time format?

### ISSUE THREAD

**Issue by mslee89** [collectd/collectd#1768]
Hello.

I want to change the time format to collect.
Can I change the time format?

`[{"values":[3680987825,2462317034],"dstypes":["gauge","gauge"],"dsnames":["rx","tx"],"time":1466413205.133,"interval":10.000,"host":"Switch2","plugin":"snmp","plugin_instance":"","type":"if_octets","type_instance":"Unit: 1 Slot: 0 Port: 47 Gigabit - Level"}]
`

I want to change in the following format:
"time":1466413205.133 --> 2016-06-20T08:52:39.676Z [Local Time]

Have a nice day.

**Comment by rubenk** [comment]
Where do you get this json output from? What write plugin are you using?

**Comment by mslee89** [comment]
@rubenk 

No. i using Kafka Plugin and got to kafka consumers.

**Comment by rubenk** [comment]
So this is output from Kafka? You'll need to change the time format in Kafka then. Afaict Collectd doesn't support changing the time format in the json it sends to Kafka.

**Comment by mslee89** [comment]
@rubenk 

Ok. Thank you for the answer.
