### ISSUE TITLE
virt fails to collect data if one server times out

### ISSUE THREAD

**Issue by soeb** [collectd/collectd#1775]
We've come across an issue where the virt plugin would not provide any useful data, instead returning NaN for all information.

Specifically, if this error came up for any domain
 virt plugin: virDomainMemoryStats failed with status -1.
All guests would have NaN stored in the same batch.

The guest in question would return the following from virsh:
 # virsh dommemstat 7
 error: Failed to get memory statistics for domain 7
 error: Timed out during operation: cannot acquire state change lock

Making collectd ignore the domain in question resolved the issue for all other guests.

**Comment by rubenk** [comment]
Hi,

Looking at the code in question at https://github.com/collectd/collectd/blob/master/src/virt.c#L590, when the api call fails we'll just continue with the next guest, so I'm not seeing how this could be an issue.

When this happens, are only the memory stats for all guests set to NaN or also other stats like cpu?

What version of collectd and libvirt are you running?

**Comment by soeb** [comment]
All stats for all guests are set to NaN, not just memory.

We're running collectd 5.5.0 and libvirt 1.2.8.

**Comment by rubenk** [comment]
I don't understand how this can happen. At least the stats for the domains before the hanging domain in question should have been sent, as well as the cpu stats for the hanging domain.

If you can reproduce this, can you attach gdb and step through lv_read to see what happens?

**Comment by soeb** [comment]
I'll look into getting this to you when possible/I am able to.

**Comment by rubenk** [comment]
Closing stale issue.
