### ISSUE TITLE
write_graphite w/ TCP acts bizarrely in our environment

### ISSUE THREAD

**Issue by jblaine** [collectd/collectd#1779]
The `write_graphite` code in (at least) collectd 5.5.1, using the default setting of `Protocol "tcp"` for the plugin, does not work for us.

Switching to `Protocol "udp"` for the plugin makes things work.

Looking at `collectd.log` while using `Protocol "tcp"` shows repeated plugin write failures. Viewing the data shows it to be erratic at best. It's hard to summarize exactly what does get sent and not sent, but it's pretty broken for us.

Here's a screenshot showing a single host running collectd with `write_graphite` configured for `Protocol "tcp"` vs. random numbers being sent through `nc` (using TCP, not UDP) to our graphite server:

![collectd 5.5.1 broken](https://dl.dropboxusercontent.com/u/15519230/collectd-tcp-graphite-broken.png)

**Comment by rubenk** [comment]
Hi @jblaine 

Would you be able to capture a trace with tcpdump on the sending host while this is happening?

**Comment by rubenk** [comment]
@jblaine any chance you could try to reproduce this with collectd 5.7.1?

**Comment by jblaine** [comment]
I will try it out this coming week

**Comment by rubenk** [comment]
@jblaine any progress?

**Comment by jblaine** [comment]
Building latest collectd now to try it out. Sorry for the silence. Swamped.

**Comment by jblaine** [comment]
I didn't try latest, but used what was in EPEL which is 5.7.1. The problem does not exist anymore for me.

**Comment by jblaine** [comment]
It would be a "nice to have" if someone knows what went wrong. Was there a bug found and fixed?

**Comment by rubenk** [comment]
Thanks for the update. I'm glad to hear it works for you. There have been a few thousand commits between 5.5 and 5.7, so it's hard to tell what fixed it.
