### ISSUE TITLE
How to Enable Internal Stats

### ISSUE THREAD

**Issue by rrpolanco** [collectd/collectd#1784]
I'm running Collectd 5.4 on Ubuntu 14.04. I'm encountering an issue where the process is gobbling up all the available memory on the server. I want to set `WriteQueueLimitHigh` to prevent Collectd from growing but before I do that I'd like to see how many points are queued up. 

Per the [doc](https://collectd.org/documentation/manpages/collectd.conf.5.shtml), I have enabled `CollectInternalStats` in my `collectd.conf`. Now, where do I see this stats? Are they exported/logged somewhere? 

Thanks.

**Comment by rubenk** [comment]
Hi,

Depending on which write plugin you use these are written like any other plugin to csv, rrd etc.

**Comment by redlad** [comment]
Could someone attach a sample config to read internal stats
It is not working for me
