### ISSUE TITLE
plugin_modbus in big-endian with IEEE-754

### ISSUE THREAD

**Issue by stonix82** [collectd/collectd#1786]
Hi,

it looks like the Modbus-Plugin interprets Floating Points Data Registers as little-endian, instead as big-endian.

I configured a ModbusTCP-Server with the same measurement data source and stored the value in 3 kinds of data types: `int`, `float` and `swapped float`. collectd stored the data types `int` and `swapped float` correctly (readable values) in RRDs. But the data types `float` was not readable (suspect values).

Can someone approve my bug (?) report?

collectd Version: 5.4.1-6 on Debian 8.5 (jessie)

Best Regards
Stoni

**Comment by octo** [comment]
The `mb_register_to_float()` function uses the byte order of the host it's compiled on to decode floats, which may differ from the byte order of the device. Unfortunately, I don't know how Modbus normally treats floats. We might change the `Float` option to do the most common byte order (big endian?) and add an appropriate `FloatLE` (or `FloatBE`). Does that sound reasonable?

**Comment by stonix82** [comment]
Hi octo,

i've assay more with the ModbusTCP-Server, collectd, other ModbusTCP-Software and my own ModbusTCP-Stack. I've seen, that all collectors get not readable values from the ModbusTCP-Server if the data point value is configured as standard IEEE (32bit) float. It looks like a bug inside the ModbusTCP-Server - not in collectd. I've should assay this bevor. I think, the `Float` option must not and should not be change into `FloatBE` (it works fine) and this byte order is correct.

This case (#1786) can be closed. Sorry and thank you! 

Best Regards
Stoni

**Comment by rubenk** [comment]
Thanks for looking deeper into this @stonix82, and glad to hear it's not a collectd issue.
