### ISSUE TITLE
What is the best way of modifying plugin_instance's max length?

### ISSUE THREAD

**Issue by liuweichu** [collectd/collectd#1788]
Hello collectd developer/user.

Recently we are running into a problem. When collecting Kafka metrics using GenericJMX Plugin, but the "plugin_instance" field are not long enough to hold the value (since it contains topic names and some topics has long name).

We found that by changing definition of DATA_MAX_NAME_LEN in src/daemon/plugin.h, we can expand the max length and get complete "plugin_instance".

Here we want to ask if it is safe to modify this constant? If you have any advices, please tell us.

Thanks

Liu

**Comment by rubenk** [comment]
Hi,

It should be reasonably safe to do this. Since b4329683a35a886bb0cdd7ce843146eae0d6fd81 you can also override it from the command line when you compile.

There are various open issues about this, please search the issue tracker for more details.

**Comment by liuweichu** [comment]
Hello

Thanks very much for help, and sorry for duplication
