### ISSUE TITLE
Substitute for asprintf should be re-added in write_sensu.c

### ISSUE THREAD

**Issue by dago** [collectd/collectd#1798]
In fact the older Solaris implementations are missing `asprintf`, so the vendor substitute would be good to have. This was already in pull request #912 but probably didn't make it into the release.

**Comment by rubenk** [comment]
I pulled it out in f6b065e5dc862010ee54f14c68ce75d695fdfcbd since it broke FreeBSD.

What do you mean by 'older' implementations? Which Solaris versions?

**Comment by dago** [comment]
`asprintf` was introduced in Solaris 10 Update 11 (the latest kernel/libc update). OpenCSW tries to aim at Update 8 with `libc 1.22.5` which has a reasonable distribution in the field.

**Comment by rubenk** [comment]
@dago could you give #1840 a try?

**Comment by dago** [comment]
Looks good with the exception of the superfluous "," in configure.ac before `asprintf`.

**Comment by rubenk** [comment]
Should be fixed by 	23ac8e5.
