### ISSUE TITLE
SNMP plugin negative value

### ISSUE THREAD

**Issue by avinchakov** [collectd/collectd#1802]
Hello, i am using collectd 5.5.1 (Ubuntu 14.04.4 LTS). my config:

`<Data "asa_memory_free">`
         ` Type "memory_free"`
                `Table false`
                `Values  "CISCO-MEMORY-POOL-MIB::ciscoMemoryPoolFree.1"`
       ` </Data>`
       ` <Host "fw">`
                `Address "172.16.21.1"`
             `   Version 2`
              `  Community "public"`
           `     Collect  "asa_memory_free"        `
  `      </Host>`

But  I get the output negative values:

Tue Jul 19 10:21:20 2016	-1187240922.000000
Tue Jul 19 10:21:30 2016	-1187240922.000000
Tue Jul 19 10:21:40 2016	-1187240922.000000
Tue Jul 19 10:21:50 2016	-1187240922.000000
Tue Jul 19 10:22:00 2016	-1187240922.000000
Tue Jul 19 10:22:10 2016	-1187240922.000000
Tue Jul 19 10:22:20 2016	-1187240922.000000
Tue Jul 19 10:22:30 2016	-1187240922.000000
Tue Jul 19 10:22:40 2016	-1187240922.000000

**Comment by rubenk** [comment]
Hi,

There's no such type as "memory_free" in types.db. Did you define this type yourself?
If you do an snmpget on CISCO-MEMORY-POOL-MIB::ciscoMemoryPoolFree.1, what do these values show?

**Comment by avinchakov** [comment]
I have an custom.db with 
`memory_free ciscoMemoryPoolFree:GAUGE:U:U`

`snmpwalk -v2c -c public 172.16.21.1 CISCO-MEMORY-POOL-MIB::ciscoMemoryPoolFree.1
CISCO-MEMORY-POOL-MIB::ciscoMemoryPoolFree.1 = Gauge32: 3108320294 bytes`

**Comment by rubenk** [comment]
Could you try the existing "memory" type? That one doesn't allow negative values:
memory value:GAUGE:0:281474976710656

**Comment by avinchakov** [comment]
Hi,
I just tried:
        `<Data "asa_memory_free">`
                `Type "memory"`
               ` Table false`
                `Values  "CISCO-MEMORY-POOL-MIB::ciscoMemoryPoolFree.1"`
      `  </Data>`
it don't help me, in graphite:
`whisper-fetch --pretty  memory.wsp`
Wed Jul 20 08:43:30 2016	-1187060698.000000
Wed Jul 20 08:44:00 2016	-1187060698.000000
Wed Jul 20 08:44:30 2016	-1187060698.000000
Wed Jul 20 08:45:00 2016	-1187060698.000000
Wed Jul 20 08:45:30 2016	-1187060698.000000
Wed Jul 20 08:46:00 2016	-1187060698.000000

**Comment by rubenk** [comment]
Just to check that this is also what Collectd sends to Graphite, could use enable the write_log plugin in Collectd and see if it writes the same values to your logfile?

**Comment by avinchakov** [comment]
I can't to find anything about write_log, can you give me any example?

**Comment by rubenk** [comment]
`LoadPlugin write_log` should do it.

**Comment by avinchakov** [comment]
Hmmm,
I just installed new package collectd-dbg and it began to work correctly!!

**Comment by avinchakov** [comment]
Yes, but I only installed collectd-dbg because I did not have a plugin write_log

**Comment by avinchakov** [comment]
Thank you for your help!!

**Comment by rubenk** [comment]
The write_log plugin is in the main collectd-core package. collectd-dbg just contains debug symbols. Anyway, glad to hear you got it fixed.
