### ISSUE TITLE
Build system: Use pkg-config to configure the grpc plugin.

### ISSUE THREAD

**Issue by octo** [collectd/collectd#1817]
The *gRPC plugin* is currently a bit annoying to build: it requires a very recent version of *protoc*, so that you will likely need to compile it manually. At the same time, it only searches `$PATH` for the binaries and does not allow to override the path. And to make it even worse, the check for the headers and libraries does not take a prefix, so you're stuck with manually editing `CPPFLAGS` and `LDFLAGS`.

At the same time, both protobuf and grpc provide a `.pc` file for *pkg-config*. Ideally we'd take the prefix information and other required flags from that config.

**Comment by rubenk** [comment]
Yeah, this can certainly be approved. I can take a stab at it.
I was hoping proto3 would be out of beta at this point and available in a few distros.

Now that pkg-config is not optional anymore I'm going to switch more plugins over to it.

**Comment by octo** [comment]
proto3 was released _yesterday_ – literally hours before I started playing with it ;-)

**Comment by rubenk** [comment]
Nice timing, thanks for letting me know :)

**Comment by rubenk** [comment]
You can override the path to the binaries btw, `./configure PROTOC=/usr/bin/ls GRPC_CPP_PLUGIN=/usr/bin/cat`, but this is not very user friendly.

**Comment by rubenk** [comment]
@octo, @tokkee, please have a look at #1824 

I changed a lot of stuff so I might have missed some things.

**Comment by rubenk** [comment]
One question for @tokkee, should I check for libgrpc++ or libgrpc? It seems to link fine against the latter, but I'm not sure. There are .pc files for both.

**Comment by rubenk** [comment]
I couldn't get the plugin to work by just linking to libgrpc. It needs both libgrpc++ and libprotobuf.
I'll add a check for libprotobuf. Checking for libgrpc++ is more involved, AC_CHECK_LIB needs a global function but afaict all the code in libgrpc++ is namespaced.
