### ISSUE TITLE
netlink plugin's if_octets value drop every now and then

### ISSUE THREAD

**Issue by liyichao** [collectd/collectd#1820]
![image](https://cloud.githubusercontent.com/assets/2576762/17255605/81434a58-55ec-11e6-8c0c-41977c5b6144.png)

Above is a graph of if_octets collected by netlink plugin. The value is near `1063244811824168`,  and increases continually, every now and then, it drops to near value `322268434937`.

In my view, the value is `unit64_t`, and will overrun at `2**64-1=18446744073709551615`, so I do not know why it drops before reaching this value, and why the drop is not periodic, but seems random.

**Comment by rubenk** [comment]
Hi,

Thanks for your report.
Could you share more details? OS version, collectd version, config etc.

**Comment by liyichao** [comment]
Hi, sorry, below are some details:

```
xxx:~$ sudo lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 7.8 (wheezy)
Release:	7.8
Codename:	wheezy
xxx:~$ uname -a
Linux status02 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.7-ckt7-1~bpo70+1 (2015-04-07) x86_64 GNU/Linux
```
collectd is 5.5.1, config is:

```
LoadPlugin netlink
<Plugin netlink>
VerboseInterface "eth0"
VerboseInterface "eth1"
VerboseInterface "eth2"
VerboseInterface "eth3"
VerboseInterface "bond0"
</Plugin>
```
bond0 is a virtual interface that combines the `eth` interfaces.

**Comment by rubenk** [comment]
Thank you. Are you able to capture the raw values around the one point when the drop happens? You should be able to do this with the write_log or csv plugin.

**Comment by MarloweW** [comment]
It's confirmed to be a misconfiguration in our system, please close this issue.
