### ISSUE TITLE
ping: Randomize ping phase for multiple hosts

### ISSUE THREAD

**Issue by matwey** [collectd/collectd#1827]
Hello,

I would like to have the following option for Ping plugin. If it is required, I also can open corresponding issue in liboping repository.

Currently, I use collectd 5.4 with liboping 1.6. I use ping plugin with a number of hosts. Using port mirroring on the network commutator I see that the ping requests are sent in bulks, i.e simultaneously for all monitored hosts. Typical time interval between two subsequent ping request is about 5 microseconds in my case.

I would like that requests be more or less uniformly distributed over ping Interval. As soon as ping results are averaged over collectd measurement time (which is 10 seconds by default), there should not be any additional issues/difficulties.

**Comment by rubenk** [comment]
Hi,

Could you explain why you need these requests spread out?

**Comment by rubenk** [comment]
Closing stale issue.
