### ISSUE TITLE
Current HEAD fails test parse_keys

### ISSUE THREAD

**Issue by dago** [collectd/collectd#1833]
The current HEAD 063a5e75b36173e89ffa18d32d47509f6ef968ec  is failing `parse_keys`:

```
ok 11 - yajl_complete_parse (hndl)
Success.
Testing parse_keys ...
ok 12 - parse_keys (got, sizeof (got), cases[i].str)
not ok 13 - got = "WBThrottle.bytesDirtied.description.bytesWb.description.iosDirtied.description.iosWb", want "WBThrottle.bytesDirtied.description.bytesWb.description.iosDirt"
FAILURE.
FAIL test_plugin_ceph (exit status: 1)
```

Full logs are available at
* https://buildfarm.opencsw.org/buildbot/waterfall?category=collectd
* https://buildfarm.opencsw.org/buildbot/builders/collectd-solaris10-i386/builds/350/steps/shell_3/logs/test-suite.log

**Comment by rubenk** [comment]
Thanks for reporting, I noticed this as well. The Ceph tests make assumptions about the size of DATA_MAX_NAME_LEN, which we just changed from 64 to 128 in https://github.com/collectd/collectd/commit/6fd0d2574fc386c2724c8307d33b12529b30048b

**Comment by octo** [comment]
Duplicate of #1834
