### ISSUE TITLE
Ceph tests have hardcoded assumptions about DATA_MAX_NAME_LEN

### ISSUE THREAD

**Issue by rubenk** [collectd/collectd#1834]
The parse_keys test breaks if you change it.

**Comment by octo** [comment]
Is this fixed by 9521a596cb88b044a2f08db53520edd6e15c8d39?

**Comment by rubenk** [comment]
In 9521a59, I only changed the expected string to 128 bytes instead of 64, to not block the builders for too long. But as soon as someone overrides DATA_MAX_NAME_LEN the test will break again.

**Comment by octo** [comment]
Fixed by 7a65aadcc432d3341f5cca816c6a157b1b9d6116
