### ISSUE TITLE
[Documentation] Need more examples for the Filter mechanism

### ISSUE THREAD

**Issue by sharninder** [collectd/collectd#1872]
Some helpful ones might be where, for example, if the user has configured Generic_JMX plugin to monitor Tomcat, the user can replace the Generic_JMX string with Tomcat in the metric name. We use this technique to monitor elastic search using the curl_json plugin and change the name to elasticsearch. This would be a good example to have for new users.

**Comment by rubenk** [comment]
Hi @sharninder,

If we got you a wiki account, would you be willing to add these examples?

**Comment by sharninder** [comment]
@rubenk Yes, absolutely. Wanted to do this myself but realised I'd need an account

**Comment by rubenk** [comment]
Great, ping us on #collectd on freenode, or on the mailing list, and we'll set you up.
