### ISSUE TITLE
something is wrong when "make all"

### ISSUE THREAD

**Issue by LuckyHawk** [collectd/collectd#1886]
after ./configure when I make all,something is wrong:
" Check whether you have set $PERL_MM_OPT in your environment and try using ./configure --with-perl-bindings="" "

**Comment by octo** [comment]
Hi @LuckyHawk,

We need more information to debug this problem. Can you please provide the file `config.log` that's written by *configure*?

**Comment by rubenk** [comment]
@LuckyHawk the line above the output you pasted should have told what is wrong:
```
Can't locate ExtUtils/MakeMaker.pm in @INC (you may need to install the ExtUtils::MakeMaker module) (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at Makefile.PL line 1.
BEGIN failed--compilation aborted at Makefile.PL line 1.
```

So you'll need to install the ExtUtils::MakeMaker perl module
