### ISSUE TITLE
How can I remove the type from metric name 

### ISSUE THREAD

**Issue by YouMingyang** [collectd/collectd#1895]
Hello, I use Mirantis LMA to monitor Openstack.
I write a collectd python plugin to collect data.But when InfluxDB recevied the data, it always contains the value.type.PS: 
the metric name is proc_num,type is gauge
InfluxDB Measurement is gauge_proc_num
How can I rename it to proc_num?

**Comment by rubenk** [comment]
Hi,

Please use the collectd mailing list or the #collectd IRC channel for questions about the usage of collectd. We'd like to keep the github issue tracker for bugreports and patch reviews.

**Comment by ValiDrv** [comment]
spent a few days looking for this... wish it was posted somewhere

**Comment by rubenk** [comment]
It is, in the README.

**Comment by ValiDrv** [comment]
What section/tag? I seriously can't find it. Even compiled the 5.7 and tried their tags, and was looking to change the code.

**Comment by rubenk** [comment]
https://github.com/collectd/collectd/blob/master/README#L1055
