### ISSUE TITLE
postgresql: db query utils: udb_result_submit: Parsing `' as derive failed.

### ISSUE THREAD

**Issue by mfournier** [collectd/collectd#1905]
*   Version of collectd:
5.5.1, 5.4.2, current master

*   Operating system / distribution:
Debian, not sure which version.
Postgresql versions: at least from 9.1 to 9.5

## Expected behavior

No error in logs, all values properly handled.

## Actual behavior

```
Initialization complete, entering read-loop.
Successfully connected to database postgres (user perf_user) at server
redacted:5432 (server version: 9.5.2, protocol version: 3, pid: 25691)
parse_value: Failed to parse string as derive: .
db query utils: udb_result_submit: Parsing `' as derive failed.
parse_value: Failed to parse string as derive: .
db query utils: udb_result_submit: Parsing `' as derive failed.
parse_value: Failed to parse string as derive: .
db query utils: udb_result_submit: Parsing `' as derive failed.
db query utils: udb_query_handle_result (flurish_etl, row_stats): All
results failed.
postgresql: udb_query_handle_result failed with status -1.
```

(cf https://mailman.verplant.org/pipermail/collectd/2016-June/006803.html)

## Steps to reproduce

Not been able to reproduce in isolation yet.

What @bzed, @mgedmin and myself have figured out so far, on IRC:
* The error message is misleading due to insuffiscient quoting: `parse_value: Failed to parse string as derive: .` The trailing dot is not the problem, it's the fact that an empty string is returned by the SQL query.
* We suspect the queries run against `pg_stat_user_tables` and `pg_statio_user_tables` are those triggering the error message. To be confirmed.
* When running one of these queries against a non-existing database (eg: `psql -U postgres -d template1 -c "SELECT sum(n_tup_ins) AS ins, sum(n_tup_upd) AS upd, sum(n_tup_del) AS del, sum(n_tup_hot_upd) AS hot_upd FROM pg_stat_user_tables;"`), postgresql returns one row of empty values. As opposed to zeros or other numerical values, when run against a real DB.

**Comment by bzed** [comment]
I've added some debug code - unfortunately I forgot to dump the query string, but looking at
```
Sep  2 13:11:49 dbserver collectd[30984]: postgresql: PG_Q_DATA ourdbname (row = 415, col = 1, col_name = relname, value = process_id).
Sep  2 13:11:49 dbserver collectd[30984]: postgresql: PG_Q_DATA ourdbname (row = 415, col = 2, col_name = seq, value = 0).
Sep  2 13:11:49 dbserver collectd[30984]: postgresql: PG_Q_DATA ourdbname (row = 415, col = 3, col_name = seq_tup_read, value = 0).
Sep  2 13:11:49 dbserver collectd[30984]: postgresql: PG_Q_DATA ourdbname (row = 415, col = 4, col_name = idx, value = ).
Sep  2 13:11:49 dbserver collectd[30984]: postgresql: PG_Q_DATA ourdbname (row = 415, col = 5, col_name = idx_tup_fetch, value = ).
Sep  2 13:11:49 dbserver collectd[30984]: parse_value: Failed to parse string as derive: .
Sep  2 13:11:49 dbserver collectd[30984]: db query utils: udb_result_submit: Parsing `' as derive failed.
Sep  2 13:11:49 dbserver collectd[30984]: parse_value: Failed to parse string as derive: .
Sep  2 13:11:49 dbserver collectd[30984]: db query utils: udb_result_submit: Parsing `' as derive failed.
```

its obviously the ```query_plans``` predefined query. Adding some coaleasces in the query should fix the issue.
