### ISSUE TITLE
[RFC] Target:Set: Rename "MetaDataSet" to "MetaData".

### ISSUE THREAD

**Issue by octo** [collectd/collectd#1910]
All options to the *Set target* are simply the field they set, e.g.:

```
<Target set>
  Host "foo"
  Plugin "bar"
</Target>
```

The option name `MetaDataSet` seems to break that schema, because it is not clear what the "Set" suffix is referring to. Only one meta data key is being set, not a "set of keys" and if the "set" operation is intended: that one is already in the plugin's name.

I therefore suggest to drop "Set" from the name – it's cleaner ;-)

```
<Target set>
  MetaData "key" "value"
</Target>
```

**Comment by octo** [comment]
FYI, this is scheduled to be in the 5.6 feature release. We have to change this before 5.6 is released, otherwise this would be a backwards incompatible change.

**Comment by mfournier** [comment]
Makes sense indeed. I can bake a quick PR for this today, as it's a trivial change.

Inviting @ymettier to the conversation, as he's the original author of this patch.
