### ISSUE TITLE
collectd's network plugin listens on all interfaces

### ISSUE THREAD

**Issue by swestlake** [collectd/collectd#1928]
*   Version of collectd: 5.5.2
*   Operating system / distribution: debian

when using the "network" plugin, collectd listens on `0:0:0:0:<random port number> `

```
LoadPLugin "network"

<Plugin "network">
 <Server "10.1.1.1" "620">
   MaxPacketSize 1024
 </Server>
 Forward false
 ReportStats false
</Plugin>
```

**Comment by DanielArmengod** [comment]
Can confirm it happens in my installation as well. Running Debian's stable version (5.4).

collectd.conf:
```
<Plugin network>
        Server "redacted.company.com"
</Plugin>
```
```
netsat -putan | grep collectd
udp        0      0 0.0.0.0:49796           0.0.0.0:*                           63574/collectd

```

**Comment by rubenk** [comment]
This is normal behaviour under Linux, and it isn't actually listening. See #736 for more details.
