### ISSUE TITLE
Builder collectd-solaris10-i386 timing out during "configure".

### ISSUE THREAD

**Issue by octo** [collectd/collectd#1933]
Hi @dago,

it appears that the i386 OpenCSW BuildBot is consistently failing to run `configure`. Could you take a look at this? The false negatives are quite confusing :\

Thanks!
—octo

**Comment by dago** [comment]
Yes, I also noticed. This should be already fixed, the host is hung, maybe it needs a little more memory now that we attached some more build instances.

Best regards -- Dago

**Comment by octo** [comment]
Thanks for following up! One of the recent builds succeeded: https://buildfarm.opencsw.org/buildbot/builders/collectd-solaris10-i386/builds/501

**Comment by dago** [comment]
I also restarted all failed builds in the past, status should be updated in the next few hours.

**Comment by dago** [comment]
The builds finished much faster than I expected. Everything should be fine now.

**Comment by octo** [comment]
Awesome, thank you @dago! :-D
