### ISSUE TITLE
Statsd sampling rate is behaving badly

### ISSUE THREAD

**Issue by raghuteja** [collectd/collectd#1935]
*   Version of collectd: 5.5.0
*   Operating system / distribution: centos-release-7-2.1511.el7.centos.2.10.x86_64

In case of statsd timer if i send 2 requests like this

- latency:1|ms|@0.001
- latency:2|ms|@0.001

In this case average latency should be 1.5ms but the output coming out to be 1.5s
This is because you are dividing latency with sample rate but forgot to increment counters by 1/samplerate (If i am not wrong)

check this code
latency/samplerate : https://github.com/collectd/collectd/blob/master/src/statsd.c#L314
sending entire latency as single value : https://github.com/collectd/collectd/blob/master/src/statsd.c#L333

Have to increment counters by (1/samplerate) 

## Steps to reproduce
Send the above two requests to statsd and check the average value produced

Thanks in advance for your help

**Comment by octo** [comment]
Hi @raghuteja,

you're using timers with a sample rate of 0.001. That is not a standard feature of statsd implementations. collectd applies the sample rate to timers as it applies it to counters: by dividing with that number. Your 1ms and 2ms are converted to 1s and 2s respectively. An average of 1.5s is *working as intended*.

I'm not sure how counters come into play here? Are you also working with a statsd implementation that handles this differently?

Best regards,
—octo

**Comment by raghuteja** [comment]
Hi @octo ,

What does **latency:1|ms|@0.001** signify?
 As far as i understood it means out of 1000 requests we are sending only one request to statsd and latency of that request is 1ms (Correct me if i am wrong)

If i am correct then if latencies are 1ms and 2ms how come the average latency will be 1.5s?

What I expected?
- latency:1|ms|@0.001
- latency:2|ms|@0.001

1000 requests with 1ms latency and another 1000 requests with 2 ms latency
so average will be (1000*(1ms)+1000*(2ms))/(1000+1000) = 1.5ms

If that is not the case what does sample rate signifies?

Thanks for the fast response,

—Raghu Teja

**Comment by octo** [comment]
What `@<value>` signifies is not well defined for timers (`|ms`) and I'd fully expect different implementations to behave differently. *collectd's* implementation will always apply the logic it applies for counters, and that is to divide the metric value by this "scaling". In your example:

*   1ms / 0.001 = 1000ms
*   2ms / 0.001 = 2000ms

The average is therefore: (1000ms + 2000ms) / 2 = 1500ms

The *StatsD plugin* does **not** interpret this as "1000 datapoints measuring 1ms each".

Arguably *collectd* should produce a syntax error when encountering an "@" in a timer metric since this syntax is not documented, but currently things are as described above.

**Comment by raghuteja** [comment]
I checked other Statsd implementations, they implemented as timers as i described
For more info :  Check this [implementation](https://github.com/etsy/statsd)

May be this is your way of implementing timers, I expected the same way as other statsd implementations.

But just do think about it, Since sample rate looks more meaning full with what i told

Thanks for your valuable time @octo 

—Raghu Teja

**Comment by octo** [comment]
Sorry, I'm not invested enough to dig through the Etsy statsd myself.

If this is a feature you need, I'm happy to review a pull request. Our next feature release is planned for December.

Best regards,
—octo
