### ISSUE TITLE
Some plugins are undocumented in collectd.conf(5)

### ISSUE THREAD

**Issue by edigaryev** [collectd/collectd#1937]
Examples:

* users
* entropy

There's probably more to it than that.

**Comment by octo** [comment]
These two plugins don't have an entry in *collectd.conf(5)* because they don't offer any config options. Do you have any suggestions where these plugins should be documented instead?

**Comment by edigaryev** [comment]
>These two plugins don't have an entry in collectd.conf(5) because they don't offer any config options.

Right, but they still go into collectd.conf anyway.

>Do you have any suggestions where these plugins should be documented instead?

How about a different section of collectd.conf(5)?

* GLOBAL OPTIONS
* PLUGINS WITHOUT OPTIONS
* PLUGINS WITH OPTIONS
* THRESHOLD CONFIGURATION
* etc.

**Comment by rubenk** [comment]
Dupe of #1682
