### ISSUE TITLE
RFE: Add plugin name field into plugin context use it to improve error reporting.

### ISSUE THREAD

**Issue by rpv-tomsk** [collectd/collectd#1949]
Many pieces of plugins code duplicates functions provided by core.

Example from netapp.c:

```
if ((ci->values_num != 1) || (ci->values[0].type != OCONFIG_TYPE_STRING))
 {
        WARNING ("netapp plugin: The %s option requires exactly one string argument.",
                         ci->key);
         return;
 }
```

The `cf_util_get_string()` should be used instead in this place, but his error reporting is not informative enough:
`"cf_util_get_string: The %s option requires exactly one string argument."`

Due to this, plugins writers duplicate `cf_util_get_*` code inside their plugins to show plugin name in error messages.

My proposal is to add plugin name field into plugin context and set that name in plugin_load().
So, cf_util_get_\* functions can use that field to build nice error messages.

Comment by @octo: 

> ERROR() aka. plugin_log() could use this also and we could remove a lot of "foo plugin: " prefixes from all over the codebase.

**Comment by octo** [comment]
I like this idea very much and it has the potential to remove a lot of duplication from plugins. The two places that could benefit most are:

* `plugin_log()` could automatically add prefix to log messages. This would go a long way towards unifying this prefix, which is mostly `foo plugin: ` but sometimes just `foo: ` and sometimes missing completely.
* A sane default behavior could be added to `plugin_dispatch_values()` for the case when the `vl.plugin` field is empty. That would remove one line of initialization from nearly every plugin.

**Comment by rpv-tomsk** [comment]
How can we work on this together?

**Comment by rpv-tomsk** [comment]
Hi ! 

I'm working on plugins code cleanup.
- Cleaning code from '%PLUGINNAME% plugin: ' (now)
- Unify configuration functions. (soon)

Additional question: 'c_complain()' ?

**Comment by rpv-tomsk** [comment]
Hi, @octo !

What to do with `match_*.c` and `target_*.c`? These plugins have their own prefixes like `%target% target:` or `%match% match:`, not `%pluginname% plugin`. I left them untouched, but others are 'cleaned'.
