### ISSUE TITLE
RFC: Set vl.host in plugin_dispatch_values()

### ISSUE THREAD

**Issue by octo** [collectd/collectd#1951]
Currently, most plugins do something like the following to submit metrics:

```c
value_list_t vl = VALUE_LIST_INIT;
sstrncpy (vl.host, hostname_g, sizeof (vl.host));
plugin_dispatch_values (&vl);
```

The `sstrncpy()` line is needed, because the `VALUE_LIST_INIT` cannot properly initialize the `char host[128]` field using `hostname_g`:

```
plugin.c:158:2: error: missing braces around initializer [-Werror=missing-braces]
  value_list_t vl = VALUE_LIST_INIT;
  ^
plugin.c:158:2: error: (near initialization for ‘vl.host’) [-Werror=missing-braces]
plugin.c:158:2: error: initialization makes integer from pointer without a cast [-Werror]
plugin.c:158:2: error: (near initialization for ‘vl.host[0]’) [-Werror]
plugin.c:158:2: error: initialization makes integer from pointer without a cast [-Werror]
```

I propose to add code along the lines of:

```c
if (strlen (vl->host) == 0) {
  sstrncpy (vl->host, hostname_g, sizeof (vl->host));
}
```

to `plugin_write_enqueue()`, therefore removing the need for ~115 plugins to initialize this field themselves. Eventually, the same technique could be used to set the `vl.plugin` field, too (see #1949).

**Comment by rpv-tomsk** [comment]
I see no reasons against this improvement.
