### ISSUE TITLE
[REG 5.6] [error] format_graphite: target buffer too small

### ISSUE THREAD

**Issue by iain-buclaw-sociomantic** [collectd/collectd#1953]
In version 5.5, was able to override the buffer size used in the write_graphite plugin by building with `-DWG_SEND_BUF_SIZE=65464` to allow certain custom types to work.  Examples of  such larger types had around 30 or more values associated with them.

Now that `WG_SEND_BUF_SIZE` is no longer configurable, when running version 5.6 there are no stats being written to graphite, and only this error instead.

```
[2016-09-21 16:42:10] [error] format_graphite: target buffer too small
```

While it could work to increase the buffer again, it does appear that actually that isn't necessary.

First, the real reason why this is a problem is that when `format_graphite` returns `-ENOMEM`, `wg_write_messages` just gives up.  What it should be doing is splitting up the work into multiple batches of size `WG_SEND_BUF_SIZE`.

Second, the error itself is just wrong and idiotic.  It *should* be an error in `format_graphite` if no metrics could be written to buffer because of an overflow.  It *should not* be an error if only a partial list was written to buffer.

First bad commit: https://github.com/collectd/collectd/pull/1164/commits/de80d27fe7023c2e377674b4cc341e539388b98e

**Comment by octo** [comment]
Hi @iain-buclaw-sociomantic, thanks for reporting this. I agree, this seems like a regression to me.

CC: @rubenk
