### ISSUE TITLE
Write_HTTP registers flush callback twice under certain circumstances

### ISSUE THREAD

**Issue by charliesignalfx** [collectd/collectd#1955]
*   Version of collectd: 5.6
*   Operating system / distribution: CentOS 7, Ubuntu 14.04

## Expected behavior
Plugin.c shouldn't log that a second attempt was made to register the same.

## Actual behavior
Plugin.c is logging a statement that the same callback was registered twice.  This is because under certain circumstances write_http is registering a call back more than once.

## Steps to reproduce

*   Build collectd from source with debug turned on and run collectd with the following write_http configuration:
```
<LoadPlugin "write_http">
#    FlushInterval 10
</LoadPlugin>
<Plugin "write_http">
  <Node "SignalFx">
    URL "<redacted>"
    User "auth"
    Password "<redacted>"
    Format "JSON"
    Timeout 3000
    BufferSize 65536
  </Node>
</Plugin>
```
*   Look at the log and notice log statements simillar to the line ones below
```
[2016-09-21 15:21:41] plugin_load: plugin "write_http" successfully loaded.
[2016-09-21 15:21:41] write_http: Registering write callback 'write_http/SignalFx' with URL 'https://ingest.signalfx.com/v1/collectd'
[2016-09-21 15:21:41] plugin: register_callback: a callback named `write_http/SignalFx' already exists - overwriting the old entry!
```

## Possible Solution
I noticed that the flush call back is registered on line [823](https://github.com/collectd/collectd/blob/collectd-5.6.0/src/write_http.c#L823) of write_http.c and is conditionally registered a second time on line [832](https://github.com/collectd/collectd/blob/collectd-5.6.0/src/write_http.c#L832).  When line 832 is commented out the log statement is not recorded with the exact same configurations.

**Comment by octo** [comment]
This looks like a bug introduced in adb1603b1fc09b3f19924cc9e5c8949603dae2d4, which first appeared in *collectd-5.6*.
