### ISSUE TITLE
zfs_arc plugin prefetch_metadata-miss value not compatible with storage backends

### ISSUE THREAD

**Issue by lazx888** [collectd/collectd#1963]
-   Version of collectd: 5.6.0
-   Operating system / distribution: Arch Linux
## Expected behavior

zfs_arc plugin's "prefetch_metadata-miss" value should be calculated in a format that is compatible with storage backends
## Actual behavior

Calculated "prefetch_meta-miss" value is not calculated in a format that is compatible with storage backends. For example, when collectd attempts to store "prefetch_meta-miss", the following backends log an error (on every update - so logs are being flooded with the following messages):

1) Log output when using "rrdcached" plugin backed storage:

> Sep 25 13:30:59 x collectd[20687]: parse_value: Failed to parse string as derive: data.
> Sep 25 13:30:59 x collectd[20687]: rrdcached plugin: rrdc_update (/var/lib/collectd/rrd/x/zfs_arc/cache_result-prefetch_metadata-miss.rrd, [1474824660:1418505], 1) failed with status -1.

2) Log output when using "http" plugin and influxdb backed storage:

> Sep 25 17:31:49 x influxd[195]: [collectd] 2016/09/25 17:31:49 Dropping point zfs_arc_value: NaN is an unsupported value for field value

Some other information:
- arcstats seems to have required data to calculate "prefetch_meta-miss":
  
  > grep prefetch_metadata /proc/spl/kstat/zfs/arcstats
  > prefetch_metadata_hits          4    1035971
  > prefetch_metadata_misses        4    1418505
- "prefetch_meta-miss" is being calculated twice?
  https://github.com/collectd/collectd/blob/51bc7c4a5523f2b03c24e32064b28c7c8426534d/src/zfs_arc.c#L305
  https://github.com/collectd/collectd/blob/51bc7c4a5523f2b03c24e32064b28c7c8426534d/src/zfs_arc.c#L310

Thanks!

**Comment by wtps0n** [comment]
I'm using FreeBSD and after upgrade I have the same bahavior. I've checked src/zfs_arc.c file again according to your suggestions.

I've quick patch (removing the second 'za_read_derive (ksp, "prefetch_metadata_misses",...' line), built new version of collectd package. Unfortunatelly every 10 second I receive the same error message in logs. 

OK. I've made the second try with removing first occurance of "prefetch_metadata_misses". Unfortunatelly the same result. So it seems that bug appeared in another place of code.

So we have to investigate that place :-)

**Comment by wtps0n** [comment]
Oops, I was too quickly :-) I have to check it again

**Comment by wtps0n** [comment]
OK. Removing one of this line helped. collectd is working correctly. @lazx888 thanks for your suggestions.

**Comment by octo** [comment]
It appears that 61635f31fe5a9630bf859d6b60b199a929c95609 introduces "prefetch_metadata-miss" a second time.
