### ISSUE TITLE
Java Plugin

### ISSUE THREAD

**Issue by christophedumont5** [collectd/collectd#1965]
-   Version of collectd: 5.1.0
-   Operating system / distribution: Debian Jessie
## Expected behavior

Query metrics about JVM

(Description of the behavior / output that you expected)
## Actual behavior

service collectd restart
[....] Restarting statistics collection and monitoring daemon: collectdERROR: lt_dlopen ("/usr/lib/collectd/java.so") failed: file not found. The most common cause for this problem are missing dependencies. Use ldd(1) to check the dependencies of the plugin / shared object.
Unable to load plugin java.
ERROR: lt_dlopen ("/usr/lib/collectd/java.so") failed: file not found. The most common cause for this problem are missing dependencies. Use ldd(1) to check the dependencies of the plugin / shared object.
Unable to load plugin java.

ldd java.so
        linux-vdso.so.1 =>  (0x00007fff39fb1000)
        libjvm.so => not found
        libiptc.so.0 => /lib/libiptc.so.0 (0x00007f91edc80000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f91eda7c000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f91ed6f0000)
        libip4tc.so.0 => /lib/libip4tc.so.0 (0x00007f91ed4e7000)
        libip6tc.so.0 => /lib/libip6tc.so.0 (0x00007f91ed2df000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f91ee099000)

(Description of the behavior / output that you observed)
## Steps to reproduce
-   step 1
-   step 2
-   step 3

**Comment by octo** [comment]
Hi @christophedumont5,

can you please provide the file `config.log` that is written by the `configure` script? I'd say the linker call is missing the `-rpath` option …

Best regards,
—octo

**Comment by christophedumont5** [comment]
I don't know what you're tlking about (config.log ?). 
The only log file linked to collectd is /var/log/collectd.log 

LoadPlugin load
LoadPlugin interface
LoadPlugin df
LoadPlugin java

<Plugin "logfile">
       LogLevel "info"
       File "/var/log/collectd.log"
       Timestamp true
</Plugin>

**Comment by octo** [comment]
Sorry, I assumed you compiled *collectd* yourself.

Please take a look at `/usr/share/doc/collectd-core/README.Debian.plugins` which tells you which packages you need to install in order to get the *Java plugin* working.

**Comment by BryceCicada** [comment]
I also had this issue while running collectd within a docker container java:openjdk-8-jre based off debian jessie.

    > ldd /usr/lib/collectd/java.so
	linux-vdso.so.1 (0x00007fff649f2000)
	libjvm.so => not found
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f6ec387a000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6ec34ce000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f6ec31c3000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6ec2ec2000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f6ec2ca4000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f6ec4c22000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f6ec2a8e000)

Note the line _libjvm.so => not found_, as in the original report by @christophedumont5.

For me, this was fixed by preloading libjvm with
    
    > export LD_PRELOAD=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so

The path to the correct library will likely vary depending on the java installation.

**Comment by christophedumont5** [comment]
I fixed it by creating an /etc/ld.so.conf.d/xxx.conf file with the lign ~/Java/jre/lib/amd64/server/.

ldd /usr/lib/collectd/java.so
        linux-vdso.so.1 =>  (0x00007fe9d03fe000)
        libjvm.so => ~/Java/jre/lib/amd64/server/libjvm.so (0x00007fe9cf7d5000)
        libiptc.so.0 => /lib/libiptc.so.0 (0x00007fe9cf5d3000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fe9cf3ce000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fe9cf042000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fe9cedc0000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fe9ceba3000)
        libip4tc.so.0 => /lib/libip4tc.so.0 (0x00007fe9ce99b000)
        libip6tc.so.0 => /lib/libip6tc.so.0 (0x00007fe9ce793000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fe9d03ff000)

**Comment by rubenk** [comment]
If Debian indeed strips out the rpath, this is a downstream issue with how libjvm is shipped.
I know the Fedora package has the same problem and this has been an issue for ages (https://bugzilla.redhat.com/show_bug.cgi?id=449456).

**Comment by dernasherbrezon** [comment]
Was able to fix it manually:
`ln -s /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so /usr/lib/libjvm.so`

**Comment by jglapa** [comment]
`sudo apt remove openjdk-11-jre-headless` required
