### ISSUE TITLE
Feature request: simple plugin for generating constant value

### ISSUE THREAD

**Issue by ChrisHeerschap** [collectd/collectd#1966]
*   Version of collectd: any
*   Operating system / distribution: any

## Expected behavior

I use a constant value from collectd to verify that it is logging properly to graphite and use that for dependencies with my Icinga2 monitoring system. I've used an exec to generate the constant, as well as a scale/offset with chains, which all works, but it would be nice to be able to have a plugin which logs a constant value on each interval. I tried my hand at it by modifying some of the simpler plugins, but am not a C programmer so failed.

It would be cool if the value of the constant, and possibly the plugin and instance names, could be customized via parameters to the Plugin block in the config file, but that's not necessary. I'd be perfectly happy with something that logs a value of "1".

Don't know how much call there would be for this beyond my very specific use case.

## Actual behavior

No current plugin for constant values

## Steps to reproduce

*   My workarounds so far: https://medium.com/@db94wookie/generating-a-constant-value-in-collectd-2e5bc9e51abc#.c3so0kedt

**Comment by octo** [comment]
Hi @ChrisHeerschap,

thanks for opening this feature request! I don't think that a fully fledged C plugin is a good fit for collectd, but you should be able to achieve this with one of the existing plugins.

*   You already mentioned the [Exec plugin](https://collectd.org/wiki/index.php/Exec). All you need to do is take the example given in the wiki and replace `do_magic()` with `1`.
*   The [Table plugin](https://collectd.org/wiki/index.php/Plugin:Table) reads values from a file. I guess a file along the lines of

        foo 1

    should do the trick.
*   The [cURL plugin](https://collectd.org/wiki/index.php/Plugin:cURL) can read from local files by specifying `URL "file:///path/to/file"`. The regex could be as simple as `"(1)"`.
*   If it doesn't have to be a *constant* value but rather a dead simple value that's easy to comprehend, the [Uptime plugin](https://collectd.org/wiki/index.php/Plugin:Uptime) might suit your needs.

Best regards,
—octo

**Comment by ChrisHeerschap** [comment]
Yeah, these are all variations on things I've done (except the cURL, clever workaround there!) but thought the option of a static plugin might be a cleaner solution than opening files and exec'ing things just to generate a number. Like I said, it's an edge case so it's not a huge deal if it's not practical. What I'm using right now is the uptime plugin with a combination of scale and offset on the Graphite end to reduce the uptime number to a constant (scale by 0, offset by 1) which gets me what I want. The uptime plugin always seemed essentially useless to me, but I think it's the best solution for this.

**Comment by octo** [comment]
I agree, the *uptime plugin* is mostly useless. I pushed back when it was proposed but some users were adamant that it was useful for them …

I can see the health checking use case, but think that it's easy enough to abuse another metric or piggyback the use-case on a metric that's collected anyway, so that introducing a new plugin is not useful enough.

Best regards,
—octo
