### ISSUE TITLE
df plugin: unable to use matching patterns (glob or regexp) on Device and MountPoint parameters

### ISSUE THREAD

**Issue by ssbarnea** [collectd/collectd#1968]
collectd: 5.5

While I am not sure if pattern matching is supported or not for Device and MountPoint I know for sure that the [documentation of df plugin](https://collectd.org/wiki/index.php/Plugin:DF) does not state anything about these.

This is an essential feature because collectd may generate a huge amount of metrics on systems where partitions are mounted dynamically, like docker!

As an user, I want to be able to filter-out (exclude) these random device or mountpoints in order not to pollute our monitoring.

I do hope that this is in fact already supported which means that fixing this bug would only involve improving the documentation page and the default `df.conf` template in order to include an explanatory example in a comment.

**Comment by rpv-tomsk** [comment]
Hi!

Could you please provide an example of  `cat /proc/mounts` output for partitions which are mounted dynamically in your case?

**Comment by rubenk** [comment]
Pattern matching in the df plugin is supported. for device, mountpoint and fstype. The documentation could certainly use some improvement. Patches welcome!

**Comment by octo** [comment]
Closing stale issue.
