### ISSUE TITLE
"write_kafka" default config leads to all collectds writing to same Kafka partition

### ISSUE THREAD

**Issue by liuweichu** [collectd/collectd#1977]
-   Version of collectd: 5.6.0
-   Operating system / distribution: Ubuntu 14.04
## Expected behavior

`write_kafka` plugin should distribute its write evenly to all Kafka partitions by default, unless explicitly configured.

In 5.5.2, if the `write_kafka - topic - Key` is not set, the partitioning is automatically handled by `librdkafka`, and it works fine.
## Actual behavior

In 5.6.0, With default `write_kafka` configuration (i.e. `write_kafka - topic - Key` field not set), ALL metrics from a single collectd instance will be sent to the same partition. 

What's worse, if there are multiple collectd instances, they will ALL send ALL metrics to the same partition, and leave the other partitions unused. (See the graph below)

Also, in `5.5.x`, if `Key` can be set to `Random` to dispatch metrics randomly. But this code is removed in 5.6.0, and [the manual](https://collectd.org/documentation/manpages/collectd.conf.5.shtml#plugin_write_kafka) is not updated. So not sure if it is deleted unintentionally.
## What is expected in the fix

If `Key` is not set, `write_kafka` should balance its write

A config that enables `Dispatch a metric to a random partition` should be provided. For now, no matter how `Key` is configured, one collectd will always produce all its metrics to the same partition.
## Steps to reproduce
-   step 1
  Create a Kafka cluster with more than one partitions
-   step 2
  Deploy several collectd-5.6.0, configure `write_kafka` but don't set `Key`
-   step 3
  Find that all metrics are going to the same broker
-   Graph of Kafka traffic (topic of collectd) when we upgraded collectd
  [![write-kafka-issue.png](https://s13.postimg.org/ry7glzuh3/write_kafka_issue.png)](https://postimg.org/image/bafyjhzpf/)

**Comment by octo** [comment]
Looks to be a regression introduced in 191323d1938bb92fa376379e41324bf8a2ab26cc.

Before:

```c
if (ctx->has_key)
  key = ctx->key;
else
  key = rand(); /* <!--- */
```

After:

```c
key = ctx->key;
if (key != NULL)
  keylen = strlen (key);
```

Also, the special case for "Random" was removed.
