### ISSUE TITLE
collectd process creates a child process and can't collect the metric with python plugin. After killing the child process, collectd recovers

### ISSUE THREAD

**Issue by hxzhaoyf** [collectd/collectd#1982]
*   Version of collectd: 5.5.0
*   Operating system / distribution: CentOS release 6.5 (Final)

## Expected behavior

I write a collectd python plugin to calculate the load per cpu, the .py file is:
~~~
#!/usr/bin/python
import subprocess
import collectd
from multiprocessing import cpu_count

def dispatch_value(type_instance, value):
    val = collectd.Values(plugin='load_per_cpu')
    val.type = 'gauge'
    val.type_instance  = type_instance
    val.values = [value]
    val.dispatch()

def read_callback():
    get_metrics()

def get_metrics():
    p = subprocess.Popen('uptime', stdout=subprocess.PIPE)
    info = p.stdout.readline().strip("\n")
    loadmsgs = info.split(" ")
    longload = float(loadmsgs[-1])
    midload = float(loadmsgs[-2][:-1])
    shortload = float(loadmsgs[-3][:-1])

    cpucorecount = cpu_count()
    longload = longload / cpucorecount
    midload = midload / cpucorecount
    shortload = shortload / cpucorecount

    dispatch_value("longload", longload)
    dispatch_value("midload", midload)
    dispatch_value("shortload", shortload)

collectd.register_read(read_callback)
~~~

my plugin configure in collectd.conf is like:
~~~
<Plugin network>
#       # client setup:
         Server "xxx.xxx.xxx.xxx" "xxx"
         <Server "xxx.xxx.xxx.xxx" "xxx">
        </Server>
</Plugin>

...

LoadPlugin python
<Plugin python>
       ModulePath "/opt/collectd/lib/collectd/plugins/python"
       LogTraces true
       Import "load_per_cpu"
</Plugin>
~~~
The network transport the metrics into influxdb.

When started the collectd with:
```
sodu service collectd start
```
I get the load_per_cpu metric in influxdb. But after running for some days(sometime for several hours),  the influxdb cannot get load_per_cpu metric while __others metrics still collected well__.

## Actual behavior

* Step 1, I check the /var/log/message, and get nothing message;
* Step 2, I check the process message with ps -ef |grep collectd |grep -v grep:
~~~
$ ps -ef|grep collectd |grep -v grep
root     22639     1  0 Oct08 ?        00:04:42 /opt/collectd/sbin/collectd -C /opt/collectd/etc/collectd.conf
root     27216 22639  0 Oct08 ?        00:00:00 /opt/collectd/sbin/collectd -C /opt/collectd/etc/collectd.conf
~~~
there are two processes working, and PID 27216 is created by 22639.
* Step 3, I check the process message with htop, the status is like:
![collectd](https://cloud.githubusercontent.com/assets/19898590/19233739/0cf3d566-8f1a-11e6-80ba-c748b2213e0f.png)

the process 27216 "RES" and "SHR" statuses are different from it's father process.

* Step 4, Kill the child PID, collectd recovers.

Is there some wrong in my py file, or collectd.conf? Why the father collectd process would create a child process, and recover after the child process?

**Comment by rubenk** [comment]
My guess is you'll need to call .communicate() on your python subprocess, as described in the docs at https://docs.python.org/2/library/subprocess.html#subprocess.Popen.communicate

**Comment by hxzhaoyf** [comment]
@rubenk thank you a lot. 

I saw the docs's warning:
~~~
Warning Use communicate() rather than .stdin.write, .stdout.read or .stderr.read to avoid deadlocks due to any of the other OS pipe buffers filling up and blocking the child process.
~~~
It did not recommend to use stdout.read or write which operation may deadlock due to any of the other OS pipe buffers filling up and blocking the child process. I think it's the reason. I have update the code with reading the /proc file like:
~~~
 with open("/proc/loadavg") as f:
~~~
and it works well up to now.
