### ISSUE TITLE
 processes plugin: wrong disk I/O metric types/values

### ISSUE THREAD

**Issue by rpv-tomsk** [collectd/collectd#1990]
Collectd reports `/proc/PID/io` fields `io_rchar/io_wchar` as `ps_disk_octets` type and `io_syscr/io_syscw` as `ps_disk_ops` type.
The names of these types do not match values they represent. 

1) For `io_rchar/io_wchar` data type should be named as `ps_io_octets`. In Linux, these values represent any I/O of process, not disk I/O only: they include sockets, pipes, console I/O, etc.
The `ps_io_octets` type can be added in addition to the existing `ps_disk_octets` for which values can be obtained from `read_bytes/write_bytes` of /proc/PID/io. These values will be much more correct for reporting as `ps_disk_octets` than existing `io_rchar/io_wchar`. Please note what `read_bytes/write_bytes` is _real_ disk I/O, it does not account file I/O from cache.

2) For `io_syscr/io_syscw` correct type should be named `ps_io_ops`.
Reported values do not match any real disk ops. 

My proposal is to fix these issues.

Related documentation: http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/filesystems/proc.txt?id=HEAD#n1558

**Comment by rpv-tomsk** [comment]
Is these changes will be good to go to 5.7?

**Comment by rpv-tomsk** [comment]
Metric `ps_disk_octets` based on `read_bytes/write_bytes` fully match disk IO metrics:

![disk-traffic](https://cloud.githubusercontent.com/assets/13328211/19716610/f2dbe7a8-9b86-11e6-9499-750b08ce20a3.png)
![ps-disk-octets](https://cloud.githubusercontent.com/assets/13328211/19716611/f2dc44c8-9b86-11e6-97a4-0a0c017129d8.png)

**Comment by octo** [comment]
+1 for reading better metrics from `/proc/<PID>/io`. Changing the types is however a backwards incompatible change and therefore only possible in a new major release, which is not currently planned.

**Comment by rpv-tomsk** [comment]
Hi! 

Why title was changed? Processes plugin already reads I/O metrics from /proc/<PID>/io, so, the title is wrong now: The plugin should not _start reading_ but it should report these existing readings in _correct_ types.

**Comment by rpv-tomsk** [comment]
Plugin declares `ps_disk_io` metric.  
In a fact, values reported in this metric is not a disk IO and this may be considered as a Collectd bug.
Therefore this can be corrected in the nearest release, without waiting for the new major release.
