### ISSUE TITLE
CPU plugin: When starting, give me an error. And the plugin cannot report values as percentages.

### ISSUE THREAD

**Issue by qlianggithub** [collectd/collectd#1993]
*   Version of collectd: Main Branch Code
*   Operating system / distribution: Linux el6.x86_64

## Expected behavior
(1)After adding cpu configuration options in /etc/collectd.conf, collectd restart normally, no error showed.
(2)By setting ValuesPercentage to true, you can request percentage values when both ReportByCpu and ReportByState are set to true.

## Actual behavior
(1)After adding cpu configuration options in /etc/collectd.conf, it give me an error when restarting.
![image](https://cloud.githubusercontent.com/assets/20550290/19471237/f0044fda-9554-11e6-8799-9eca414b17b1.png)

(2)CPU usage is reported as Jiffies, using the cpu type.

## Steps to reproduce

*   step 1 Add cpu configuration options in /etc/collectd.conf, as follows:  
![image](https://cloud.githubusercontent.com/assets/20550290/19471157/b4acb01c-9554-11e6-9e4b-70c0d90dafb5.png)

*   step 2 Start collectd, and query result in cpu_value measurement. It cannot report values as percentages.
*   step 3 Modify cpu.c, move _plugin_register_config()_ to the front of _plugin_register_init()_. After building and re-installing, CPU usage is reported as percentages, using the cpu type, from cpu_percent measurement.

**Comment by rpv-tomsk** [comment]
Please specify option values/options presence in your config:
```
AutoLoadPlugin true / false
LoadPlugin cpu
```

**Comment by qlianggithub** [comment]
Thanks for @rpv-tomsk . Sorry for no error in Main Branch Code. The issue occures in Version 4 of collectd.

**Comment by rubenk** [comment]
The cpu plugin in collectd 4 doesn't support ValuesPercentage. You'll need to upgrade collectd.

**Comment by qlianggithub** [comment]
Ok, thanks @rubenk .
