### ISSUE TITLE
Unable to declare multiple database from the same PostgreSQL instance

### ISSUE THREAD

**Issue by RGFR** [collectd/collectd#2002]
*   Version of collectd: 5.6.0
*   Operating system / distribution: Linux CentOS 7.2

## Expected behavior
We try to use collectd for storing PostgreSQL (9.5) metrics into Graphite.
We have a server with 2 PostgreSQL instances and need to distinguish between the instances.
The aim is the get a directory structure in Graphite like :
```
postgresql --> inst1
                             -->db1
                             -->db2
                  --> inst2
                              --> db1
                              --> db2
```

## Actual behavior
In the configuration file, when we have multiple database declarations with the same "instance" attribute, we get an error in the log file and the database does not appear.

> `[warning] The read function "postgresql-inst1" is already registered. Check for duplicate "LoadPlugin" lines in your configuration!`

## Steps to reproduce

   ```
<Database db1>
    Host "localhost"
    Port "5444"
    User "xxx"
    Password "yyy"
    Instance "inst1"
    Query transactions
    Query queries
    Query disk_io
  </Database>

   <Database db2>
    Host "localhost"
    Port "5444"
    User "xxx"
    Password "yyy"
    Instance "inst1"
    Query transactions
    Query queries
    Query disk_io
  </Database>
```

**Comment by rpv-tomsk** [comment]
Why did you specify equal options `Instance "inst1"` in both `<Database>` blocks?
Their values should be different or does not set at all (database name will be used as plugin instance then).

https://collectd.org/documentation/manpages/collectd.conf.5.shtml#plugin_postgresql
```
Instance name

    Specify the plugin instance name that should be used instead of the database name (which is the default, if this option has not been specified). This allows to query multiple databases of the same name on the same host (e.g. when running multiple database server versions in parallel).
```

**Comment by RGFR** [comment]
Because being a database guy, I thought that "instance" was the name of the PostgreSQL instance !!
I now understand that it is simply an alias for the database name, and has nothing to do with the name of the PostgreSQL instance.
The name "instance" is very misleading in this context.
