### ISSUE TITLE
apt-get install only installs 5.4.0?

### ISSUE THREAD

**Issue by scott-wood-vgh** [collectd/collectd#2019]
*   Version of collectd:
5.4.0
*   Operating system / distribution:
Ubuntu 14.04

sudo apt-get install collectd only installs 5.4.0 - is there any way to use apt-get to install a more recent release of collectd?

**Comment by rubenk** [comment]
Are you sure you are on OSX and not some Debian distro? OSX doesn't support apt-get.

**Comment by scott-wood-vgh** [comment]
My apologies, I am indeed running on a Ubuntu EC2 instance. My host machine is Mac OSX, hence the mistake. Will fix.

**Comment by rubenk** [comment]
To answer your question, we from the upstream collectd project have no control over which version of collectd Ubuntu provides. My guess is you'll need to update to a newer version of Ubuntu.

**Comment by octo** [comment]
… or you could use the Ubuntu packages built by the continuous integration setup: https://collectd.org/download#debian

**Comment by mdubbyap** [comment]
Another option would be https://launchpad.net/~signalfx/+archive/ubuntu/collectd-release
