### ISSUE TITLE
ipmi plugin stop work but other plugin is ok

### ISSUE THREAD

**Issue by dllhlx** [collectd/collectd#2021]
*   Version of collectd: 5.4.1
*   Operating system / distribution: centos 6

## Expected behavior

Ipmi plugin can become normally and all the ipmi sensor's index can be captured
 continuelly after ipmi node'state from IPMI_NODE_BUSY_CC to normal. 

## Actual behavior

Ipmi plugin stop work, the ipmi node remove when ipmi node become busy. After I restart the collectd, the ipmi plugin become normal, but after some time (sometimes servel hours and sometimes servel days),  once  ipmi node become busy (IPMI_NODE_BUSY_CC), the ipmi plugin stop work.

**Comment by rpv-tomsk** [comment]
Did you have any messages in your logs?

In the nearest time I will publish PR with new version of ipmi plugin. Can you compile custom collectd version to make tests?

**Comment by octo** [comment]
Thanks for the bug report @dllhlx! Could you please post the complete error message so we can pinpoint where in the code this is handled? Thanks!

**Comment by rpv-tomsk** [comment]
Please also specify your OpenIPMI library version.
Thanks.

**Comment by dllhlx** [comment]
@octo @rpv-tomsk the error message like that '''ipmi plugin: sensor_read_handler: Removing sensor Fan1A system_board 7.1, because it failed with IPMI error 0xc0.''', after this error happend, the ipmi plugin start remove the sensor and stop work, so no more ipmi data can be collected。My OpenIPMI library version is '''2.0.16-14.el6'''. I find the error code '''0xc0''' means '''IPMI_NODE_BUSY_CC''' from the website '''https://sourcecodebrowser.com/openipmi/2.0.2/ipmi__err_8h.html'''.

**Comment by dllhlx** [comment]
@rpv-tomsk I think the second change in #2024 my resolve my problem.

**Comment by dllhlx** [comment]
@octo @rpv-tomsk  sorry to reopen this topic. After i update my code with the pr from #2024 , I start collectd, and I found the ipmi plugin can not collect data again but other plugins work ok. So I add debug in code, then I find the function ```sensor_read_handler``` not be called after collectd start, no error message print out.

**Comment by rpv-tomsk** [comment]
>sorry to reopen this topic.

Absolutely no problems on this!

You wrote what you have OpenIPMI-2.0.16. That version has a bug - deadlock on timeouts, I have catched the same behaviour like you. Please update to OpenIPMI-2.0.22. I have no problems with that version.

**Comment by dllhlx** [comment]
@rpv-tomsk ok, I will try it. Can I use OpenIPMI-2.0.18 instead of OpenIPMI-2.0.22?

**Comment by rpv-tomsk** [comment]
Hi!

I don't know, I tried OpenIPMI-2.0.22 only and not tried other versions.

**Comment by dllhlx** [comment]
@rpv-tomsk After upgrade OpenIPMI to 2.0.22 and restart q-collectd, I  find a alert from /var/log/message - ```IPMI message handler: Event queue full, discarding incoming events```, did you come across this problem?

**Comment by rpv-tomsk** [comment]
Hi! 

Did you try recent version of IPMI plugin? It has system event log support (#2091), so it can to send notifications in case of events. Maybe that can help you.

If you have no more problem, can we please close this issue?

**Comment by rpv-tomsk** [comment]
I see the `event queue full` is discussed in #2102, so closing this issue.
