### ISSUE TITLE
write_prometheus plugin: Escape labels in the plain text format.

### ISSUE THREAD

**Issue by octo** [collectd/collectd#2035]
*   Version of collectd: *master* / 5.7
*   Operating system / distribution: *n/a*

## Expected behavior

All plugin instances and type instances should be correctly exported.

## Actual behavior

Some characters will cause issues. At least double quotes (`"`) are problematic and likely also an escape character (backslash?).

**Comment by brian-brazil** [comment]
"the backslash, the double-quote, and the line-feed characters have to be escaped as \\, \", and \n, respectively."
