### ISSUE TITLE
Collectd memory leak

### ISSUE THREAD

**Issue by bs-github** [collectd/collectd#2042]
*   Version of collectd: 5.6
*   Operating system / distribution: Linux / Ubuntu precise

## Expected behavior
Memory usage of collectd in forwarding mode should be stable.

## Actual behavior
Memory usage grows.

## Steps to reproduce

*   configure collectd to forward metrics partially to another instance (using the network plugin and the match plugin)
*   lots of traffic
*   oom killer does it's thing

## References

*  As discussed in https://github.com/collectd/collectd/pull/1967 I'll attach the valgrind massif data here. 
*  Another issue that might be the same thing was filed lately: https://github.com/collectd/collectd/issues/2033
[collectd-valgrind-massif.zip](https://github.com/collectd/collectd/files/599275/collectd-valgrind-massif.zip)

**Comment by octo** [comment]
Thanks for filling this @bs-github! Could you share (the smallest possible) config that triggers this behavior? In particular, are forwarding and matching both needed to trigger the leak? I've had trouble reproducing the leak with some very simple setups.

Thanks and best regards!

**Comment by rubenk** [comment]
@bs-github ping?

**Comment by rubenk** [comment]
Closing stale issue.
