### ISSUE TITLE
lvm plugin makes lvmetad segfaulting

### ISSUE THREAD

**Issue by ConiKost** [collectd/collectd#2043]
*   Version of collectd: 5.6.1
*   Operating system / distribution: Gentoo

## Expected behavior

lvmetad does not segfault

## Actual behavior

After start of collectd, lvmetad segfaults:
lvmetad[16020]: segfault at ffffffc0 ip 000000373427d39f sp 00007f8c51927888 error 4 in libc-2.23.so[3734200000+190000]

When I do restart lvmetad after starting collectd, collectd does work fine and collects fine. But with each start of collectd, lvmetad segfaults.

## Steps to reproduce

*   step 1: start collectd with lvm plugin and running lvmetad.
*   step 2: see system log and check, if lvmetad segfaults.

**Comment by octo** [comment]
Hi @ConiKost, thanks for your big report. Could you please add a reference for three big report on LVM's side? Do you know if 5.6.1 is the first version that triggers this?

**Comment by ConiKost** [comment]
Hi @octo, I don't understand. Which three bug reports on LVM's side do you mean? Or do you mean, I should report my report here to upstream?

Version 5.6.1 is not the first version. I already had this with 5.5.x and 5.4.x. On earlier versions, I wasn't using lvm, so I can't say, if it also there was a problem. I also see, that the problem is not specific to one machine. My other 2 Gentoo server with LVM do also segfault.

**Comment by ConiKost** [comment]
Okay, I've found the cause now. My LVM2 is compiled with -O3. If I do a compile with -O2, the segfault is gone and lvmetad does not crash.

**Comment by rubenk** [comment]
I'm glad to hear you found it, and that it's not a collectd issue.
