### ISSUE TITLE
add write_riemann plugin /write_riemann.so to collectd5.6 package

### ISSUE THREAD

**Issue by ninjarocketman** [collectd/collectd#2049]
*   Version of collectd: 5.6.1.29.gdb961f4
*   Operating system / distribution: ubuntu 16

## Expected behavior
write_riemann plugin gets installed with collectd 5.6 debian package

## Actual behavior
The write_riemann.so file is missing. Therefore the plugin cannot be loaded.

## Steps to reproduce
I installed the collectd 5.6 core as followed:

curl http://pkg.ci.collectd.org/pubkey.asc | sudo apt-key add -
echo "deb http://pkg.ci.collectd.org/deb/ trusty collectd-5.6" > /etc/apt/sources.list.d/collectd.list
apt-get update
apt-get upgrade -y
apt-get install -y build-essential \
   libtool \
   pkg-config \
   git \
   protobuf-c-compiler \
   autoconf \
   libjson-c-dev
git clone git://github.com/algernon/riemann-c-client.git
cd riemann-c-client
git checkout tags/debian/riemann-c-client-1.9.1-1
autoreconf -i
./configure && make && make check && make install
apt-mark hold riemann-c-client
mkdir -p /etc/collectd/collectd.conf.d
apt-get install --no-install-recommends -y collectd-core

When I start the service with sudo service collectd start from the /etc/collectd I get the following error message:

Starting statistics collection and monitoring daemon collectd                                                                                                                                           
option = FQDNLookup;
value = true;
option = CollectInternalStats; value = true;
Created new plugin context.
collectd[32]: plugin_load: plugin "syslog" successfully loaded.
collectd[32]: type = syslog, key = LogLevel, value = info
collectd[32]: plugin_load: plugin "cpu" successfully loaded.
collectd[32]: plugin_load: plugin "df" successfully loaded.
collectd[32]: plugin_load: plugin "interface" successfully loaded.
collectd[32]: plugin_load: plugin "load" successfully loaded.
collectd[32]: plugin_load: plugin "memory" successfully loaded.
collectd[32]: plugin_load: plugin "statsd" successfully loaded.
collectd[32]: plugin_load: plugin "swap" successfully loaded.
collectd[32]: plugin_load: plugin "uptime" successfully loaded.
collectd[32]: plugin_load: Could not find plugin "write_riemann" in /usr/lib/collectd
collectd[32]: plugin_load: plugin "logfile" successfully loaded.
collectd[32]: There is a `Node' block within the configuration for the write_riemann plugin. The plugin either only expects "simple" configuration statements or wasn't loaded using `LoadPlugin'. Please check your configuration.
collectd[32]: Found a configuration for the `write_riemann' plugin, but the plugin isn't loaded or didn't register a configuration callback.
collectd[32]: Found a configuration for the `write_riemann' plugin, but the plugin isn't loaded or didn't register a configuration callback.
Error: Reading the config file failed!

When I go into /usr/lib/collectd the write_riemann plugin is indeed not there. When I copy the .so file from the collectd 5.5 installation to the directory it also doesn't work, same error.
Also when I look for it with locate it's not there.

The same problem occurs with the default and full collectd 5.6 version.

I first posted this in the google group, the config file is posed there as well: https://groups.google.com/forum/#!topic/collectd-web-users/e87l4dNnOT0

**Comment by octo** [comment]
Thanks for reporting this, @ninjarocketman!

@mfournier could the CI packages include write_riemann? At least the more modern distros?

**Comment by mfournier** [comment]
For the sake of sanity, we took the decision to only support plugins which are buildable with the libraries provided in each target distribution.

The case of write_riemann is unfortunate as it used to build on most distros in collectd 5.5, but introduced the dependency on libriemann-c-client on 5.6. And only the most recent distribution releases have the required version.

So one option for you would be to upgrade to ubuntu xenial, which has a recent enough libriemann-c-client. Another option would be to get in touch with whoever maintains the libriemann-c-client package in ubuntu and work with him to get version 1.8.1 in the trusty-backports repository.

**Comment by rpv-tomsk** [comment]
Issue outdated.
