### ISSUE TITLE
Install Doesn't Seem to Create a Service?

### ISSUE THREAD

**Issue by scott-wood-vgh** [collectd/collectd#2055]
*   Version of collectd:
5.6
*   Operating system / distribution:
Ubuntu 14.04

## Expected behavior

I pulled down the latest 5.6 binaries and ran the configure script and a make && make install. It seems to have finished successfully (no errors), but I can't actually start the collectd service. 'which collectd' returns nothing, as does 'sudo service collectd status'. I see my installation is in /opt/collectd/sbin/ for both collectd and the collectdmon, but I'm unable to start the service.

I was following the directions here: https://collectd.org/wiki/index.php/First_steps

and all suggestions on starting the service/daemon don't work for me. I've tried executing /opt/collectd/sbin/collectd to no avail, and there is no service in /etc/init.d.

## Steps to reproduce

Install the latest collectd 5.6 from binary on Ubuntu 14.04.

**Comment by rubenk** [comment]
Yes, you'll need to install some kind of init script if you compile from source (I believe Ubuntu 14.04 uses upstart?). There's one in contrib/: https://github.com/collectd/collectd/blob/master/contrib/upstart.collectd.conf

Alternatively, you might want to try the binary packages available at http://pkg.ci.collectd.org/ as described in https://github.com/collectd/collectd-ci
