### ISSUE TITLE
collectd always tries to open /var/log/collectd.log

### ISSUE THREAD

**Issue by rubenk** [collectd/collectd#2057]
*   Version of collectd:

$ rpm -q collectd
collectd-5.6.1-1.el7_2.tilaa.x86_64

*   Operating system / distribution:

CentOS 7

I run SELinux in enforcing mode and found an AVC for collectd:
```
type=AVC msg=audit(1480172857.774:104): avc:  denied  { open } for  pid=1739 comm="collectd" path="/var/log/collectd.log" dev="sda2" ino=160 scontext=system_u:system_r:collectd_t:s0 tcontext=system_u:object_r:var_log_t:s0 tclass=file
```

I was a bit surprised by this, since I told collectd to log to stderr:

```
LoadPlugin logfile

<Plugin logfile>
    LogLevel info
    File stderr
</Plugin>
```

strace confirms that as soon as the logfile plugin is loaded, /var/log/collectd.log is opened:
```
open("/usr/lib64/collectd/logfile.so", O_RDONLY|O_CLOEXEC) = 4
open("/etc/localtime", O_RDONLY|O_CLOEXEC) = 4
open("/var/log/collectd.log", O_WRONLY|O_CREAT|O_APPEND, 0666) = 4
```

**Comment by octo** [comment]
This is likely due to the `INFO()` message that the plugin was loaded successfully. At that moment the callbacks are already registered, but the config for the *logfile plugin* has not yet been parsed.

**Comment by rubenk** [comment]
You're right:

```
$ cat /var/log/collectd.log
[2016-11-28 09:51:47] plugin_load: plugin "logfile" successfully loaded.
```

**Comment by mfournier** [comment]
Doh, this is 9e6395fc0. Sorry about that !

That said, beside this `INFO()` statement there are several `ERROR()` and `WARNING()` ones which would get lost when the default logfile isn't writeable.

This config for example:

```
LoadPlugin logfile
LoadPlugin some_typo

<Plugin logfile>
  LogLevel info
  File "/tmp/logfile"
</Plugin>
```

... leaves the user with this not very helpful and misleading error message:

```
logfile plugin: fopen (/var/log/collectd.log) failed: Permission denied
logfile plugin: fopen (/var/log/collectd.log) failed: Permission denied
Error: Reading the config file failed!
Read the syslog for details.
```
