### ISSUE TITLE
Compile Collectd-oracle-plugin failed

### ISSUE THREAD

**Issue by wpengcheng** [collectd/collectd#2060]
*   Version of collectd: 5.6.1
*   Operating system / distribution: CentOS Linux release 7.2.1511 (Core) 

## Expected behavior

when I compile collectd oracle plugin,./configure return "oci.h not found"

## Actual behavior

cd /m8/collectd/collectd-5.6.1
./configure --prefix=/opt/server/collectd --enable-oracle --with-oracle=/usr/lib/oracle/11.2/client64/

return :
 Libraries:
 oracle  . . . . . . . no (oci.h not found)

 Modules:
oracle  . . . . . . . no (oci.h not found) (dependency error)

**Comment by rubenk** [comment]
Can you share your config.log please?

**Comment by rubenk** [comment]
Closing stale issue.
