### ISSUE TITLE
OpenBSD-current discourages /dev/kmem access, breaking at least processes plugin

### ISSUE THREAD

**Issue by landryb** [collectd/collectd#2061]
*   Version of collectd: 5.5.1
*   Operating system / distribution: OpenBSD

## Expected behavior

processes plugin works

## Actual behavior

processes plugin gets denied access to kvm stats, unless sysctl kern.allowkmem is turned on - off by default.

## Steps to reproduce

Try to run the processes plugin on OpenBSD, it will fail at runtime. Probably the same for swap and tcpconns, as they also try to access those stats.

An option is to try using KVM_NO_FILES when calling kvm_open (being tested) or to switch this code to sysctl() API which doesnt have those limitations.

**Comment by rubenk** [comment]
Thanks for letting us know @landryb.

> An option is to try using KVM_NO_FILES when calling kvm_open (being tested) or to switch this code to sysctl() API which doesnt have those limitations.

If the sysctl api is preferred nowadays, then we should use that.
Since none of us it really familiar with OpenBSD, would you be willing to come up with a patch?

**Comment by landryb** [comment]
Yeah, that's somewhere on my plate.... and well, @pyr should be familiar with OpenBSD :p

**Comment by pyr** [comment]
@landryb Open what?

**Comment by landryb** [comment]
Damn slacker ;)

**Comment by rubenk** [comment]
Hehehe, this made my day ;-)

**Comment by landryb** [comment]
Apparently KVM_NO_FILES fixes swap and processes plugin (at least `collectd -T` doesnt barf out), but not tcpconns as `kvm_nlist()` call fails. Guess it'd be better to move everything to `sysctl()`...

**Comment by sthen** [comment]
I don't know collectd at all (I was directed to this issue), but I'm guessing this is just trying to retrieve a list of TCP connections similar to what netstat would do. kvm_getfiles would be the preferred interface for this on OpenBSD; the function is in libkvm (for historical reasons) but doesn't require peeking in kernel memory as is required when doing this via kvm_nlist, it should also be OK on other *BSDs.

**Comment by rubenk** [comment]
Fixed by f2530ff and b088d09. Thank you both.
