### ISSUE TITLE
write_riemann never recovers from network failure

### ISSUE THREAD

**Issue by faxm0dem** [collectd/collectd#2065]
*   Version of collectd:collectd-5.5.2.20.gaf16be6 (collectd-ci)
*   Operating system / distribution: centos6

## Expected behavior

when destination becomes unavailable (e.g. due to reboot) the write queue fills up, and when it's full collectd begins to drop metrics (`collectd plugin_dispatch_values: Low water mark reached. Dropping 4% of metrics.`). When destination recovers, write_riemann sends metrics and empties queue. Everyone is happy.

## Actual behavior

Queue always full, never empties when destination recovers. write_riemann doesn't send packets (as seen on the wire using tcpdump)

## Steps to reproduce

1. configure write_riemann
1. run `tcpdump tcp port 5555`
1. reboot destination

**Comment by mfournier** [comment]
74e5c6f and 727a4b9 are supposed to fix exactly this, but they're only there since 5.6.0. Time to upgrade Fabien ;-)

**Comment by faxm0dem** [comment]
thanks!
