### ISSUE TITLE
collectd tail plugin ExcludeRegex Not Working

### ISSUE THREAD

**Issue by Dark0096** [collectd/collectd#2075]
*   Version of collectd: 5.5.0
*   Operating system / distribution: Debian:8.4

#### tail.conf
```
LoadPlugin tail

<Plugin "tail">
    <File "/etc/nginx/access.log">
        <Match>
            Regex "HTTP/1..\" 4"
            ExcludeRegex "HTTP/1..\" 404"
            ExcludeRegex "HTTP/1..\" 499"
            DSType "CounterInc"
            Type "counter"
            Instance "4xx-excluded-404-and-499"
        </Match>
    </File>
</Plugin>
```

I have expected to work well when using a lot of ExcludeRegex functions of the tail plugin. But it is not working and only last 'ExcludeRegex 499' is working.

## Actual behavior

When trying to use a lot of ExcludeRegex, it works well.

## Steps to reproduce

*   step 1
#### access.log
```
127.0.0.1 - - [01/Dec/2016:18:44:15 +0900]  "GET /v3/intro HTTP/1.1" 200
127.0.0.1 - - [01/Dec/2016:18:44:15 +0900]  "GET /v3/intro HTTP/1.1" 404
127.0.0.1 - - [01/Dec/2016:18:44:15 +0900]  "GET /v3/intro HTTP/1.1" 499
```

#### tail.conf
```
LoadPlugin tail

<Plugin "tail">
  <File "/etc/nginx/access.log">
    <Match>
      Regex "HTTP/1..\" 4"
      ExcludeRegex "HTTP/1..\" 404"
      ExcludeRegex "HTTP/1..\" 499"
      DSType "CounterInc"
      Type "counter"
      Instance "4xx-excluded-404-and-499"
    </Match>
  </File>
</Plugin>
```

I am using collectd version 5.5.0. 
We then tried to collect the metrics for the status code of the Nginx access log using collectd's tail plugin. 
However, if you try to use ExcludeRegex "HTTP / 1 .. \" 404 and ExcludeRegex "HTTP / 1 .. \" 499 "as above, 'ExcludeRegex "HTTP/1..\" 499"' will work and ExcludeRegex 404 will not work.

*   step 2

#### tail.conf
```
LoadPlugin tail

<Plugin "tail">
  <File "/etc/nginx/access.log">
    <Match>
      Regex "HTTP/1..\" 4"
      ExcludeRegex "healthcheck"
      ExcludeRegex "HTTP/1..\" 499"
      DSType "CounterInc"
      Type "counter"
      Instance "4xx-excluded-404-and-499"
    </Match>
  </File>
</Plugin>
```

Second, I tried to test collectd with the above configuration. This time, I confirmed that Multi line ExcludeRegex is applied well. So, I think that if the same Regex is in it, I suspect that a problem may arise.

I can't understand why this works.

Please help me.

**Comment by octo** [comment]
Hi @Dark0096,

thank you for reporting this. It is, however, expected behavior: there can be only one *ExcludeRegex* setting and if there are more then later ones overwrite the previous settings.

You can use the regex *OR* operator, `|`, so achieve your goal:

```
ExcludeRegex "HTTP/1..\" 404|HTTP/1..\" 404"
```

Or, shorter:
```
ExcludeRegex "HTTP/1..\" (404|499)"
```

Best regards,
—octo

**Comment by Dark0096** [comment]
I don't know how to thank you.

I use collectd to collect system metrics in Coupang company. I am always grateful.

Thanks.
