### ISSUE TITLE
use ipmi plugin report error: "ipmi_smi_setup_con failed: OS: No such file or directory"

### ISSUE THREAD

**Issue by dllhlx** [collectd/collectd#2082]
*   Version of collectd: 5.4.1
*   Operating system / distribution: centos 6

## Expected behavior

no error message occur

## Actual behavior
error log like that:
```
ipmi plugin: ipmi_smi_setup_con failed: OS: No such file or directory
ipmi plugin: thread_init failed.
```

## Steps to reproduce

LoadPlugin ipmi

**Comment by dllhlx** [comment]
use ```service ipmi restart ```  can resolve this problem.
Close..

**Comment by rpv-tomsk** [comment]
>Please close it.

You can close issues by yourself.

**Comment by dllhlx** [comment]
@rpv-tomsk  thanks
