### ISSUE TITLE
collectd's plugin innterface can't calcute network card Flow

### ISSUE THREAD

**Issue by wpengcheng** [collectd/collectd#2086]
*   Version of collectd:5.6.0
*   Operating system / distribution:centos 7.2

## Expected behavior
when I open interface plugin:
LoadPlugin interface
<Plugin interface>
        Interface "eth0"
        IgnoreSelected false
</Plugin>

and restart collectd,

 after login grafana, the only interface_rx and interface_tx,why not have network card flow?

![image](https://cloud.githubusercontent.com/assets/16982786/20975312/0df61bca-bcda-11e6-862b-98905e6fc934.png)

**Comment by rubenk** [comment]
What do you mean with "network card flow"?

**Comment by rubenk** [comment]
Closing stale issue.
