### ISSUE TITLE
Disk plugin can't collect data from HP Raid

### ISSUE THREAD

**Issue by anhnvname** [collectd/collectd#2087]
Hello,

I see collectd on my server can't collect data from disk or I don't know how to config :D 
My server using CentOS and when I use fdisk command it show 
`/dev/cciss/c0d0`

What I need to do  now 

My config is 

```
<Plugin "disk">
  Disk "c0d0"
  IgnoreSelected false
</Plugin>
```

Thanks

**Comment by anhnvname** [comment]
Solved

```
<Plugin "disk">
  Disk "/^cciss/"
  IgnoreSelected false
</Plugin>
```

**Comment by rubenk** [comment]
My guess is you need to either specify the full path (`Disk "/dev/cciss/c0d0"`) or everything after /dev (`Disk "cciss/c0d0"`).
