### ISSUE TITLE
64 character limit in aggregation regex

### ISSUE THREAD

**Issue by faxm0dem** [collectd/collectd#210]
When using regex in aggregation, e.g.

    <Plugin aggregation>
      <Aggregation>
        [...]
        Host "/^(host1|host2|host3|...)/"
        [...]
      </Aggregation>
    </Plugin>
 

The key "Host" if ending in "/" is being interpreted as a regex. Only if the regex exceeds DATA_MAX_NAME_LEN which is currently 64, it doesn't get identified as such because it gets truncated, therefore there's no regex parsing error and no error at all. In the user perspective, no error at all, but the aggregation doesn't work.

Possible solution:

1. Add real Regex key, e.g.

         <Host>
          Regex "/everybody stand back this is a regular expression that is longer than 64 chars/"
         </Host>

2. have Regex increased maximum lenght, as 64 is pretty short for a reasonably complex regex.

**Comment by rubenk** [comment]
Let's track this in #1120
