### ISSUE TITLE
write_plugin SPOF

### ISSUE THREAD

**Issue by faxm0dem** [collectd/collectd#2104]
*   Version of collectd: 5.5.2
*   Operating system / distribution: CentOS7

## Expected behavior

Multiple write plugins are configured, for instance network and write_riemann.
One of the remote servers is failing, for instance riemann.
After some time riemann comes back.

It is expected that only the riemann data has missing points.
The remote collectd does not experience data loss.

## Actual behavior

Both distant servers collectd and riemann experienced data loss.
Even unixsock reports a small fraction of plugins

It seems sane to expect only the riemann server to be missing data, but both collectd and riemann do.
The reason is that collectd's write queue is shared among all write plugins, so when one fails, all fail.

In fact, it's even very hard to kill collectd when the queue is full

## Steps to reproduce

* configure 2 or more write_plugins
* cause failure on one of the destinations
* wait
* experience failure on all write plugins

**Comment by ludmata** [comment]
Same here, I have two write_carbon configured nodes:
`<Plugin write_graphite>
  <Node "node1.example.com">
    Host "5.6.7.8"
    Port "2003"
    Protocol "tcp"
    LogSendErrors true
    Prefix "CL.RL."
    #Postfix "collectd"
    StoreRates true
    AlwaysAppendDS false
    EscapeCharacter "_"
  </Node>
  <Node "node2.example.com">
    Host "1.2.3.4"
    Port "2003"
    Protocol "tcp"
    LogSendErrors true
    Prefix "CL.RL."
    #Postfix "collectd"
    StoreRates true
    AlwaysAppendDS false
    EscapeCharacter "_"
  </Node>
</Plugin>
`
If one of the nodes fail, the other should continue, but unfortunately that is not the case.

**Comment by faxm0dem** [comment]
This has popped up again in production: when a riemann server goes haywire, the collectd server stops getting data. @octo is this a complicated change in core?

**Comment by rpv-tomsk** [comment]
Did you try to use `WriteQueueLimitHigh` and `WriteQueueLimitLow` options?

**Comment by octo** [comment]
The reason for this behavior is that each metric is enqueued once. It is then dequeued by a write thread which calls all write plugins with that one metric sequentially. Presumably, the failed Riemann essentially starved the write threads.

I think the most universal approach would be to use an exponential backoff to skip failing read plugins for a while but still call working write plugins.

**Comment by rpv-tomsk** [comment]
>to skip failing read plugins

You want to say 'write plugins'?

**Comment by octo** [comment]
Yes; d'oh!

**Comment by rpv-tomsk** [comment]
Wow, big change ;-)

**Comment by rpv-tomsk** [comment]
What do you think about to use one write thread per one registered write callback?

Many of write plugins uses a locks (or global or per callback), what does these calls from multiple threads not too expedient (but some are free of locks).

Some while ago I thought about TCP implementation for `network.c`.
TCP will be useful when hub and agents are in distant locations.
Use of TCP will solve the issue with reordered UDP packets.

The connection lose also needs to be handled by an implementation then. 
The idea was to enqueue metrics on agent until connection to hub recovers.

Such a queue can be implemented on plugin level or on core level. 
Implementation at core level can be used for all TCP-based write plugins, that covers this issue too.

One write thread per one registered write callback will be a part of such implementation.

**Comment by rpv-tomsk** [comment]
... for each registered write callback we need to save a reference to a point in writequeue chain.
That is a point where metric should be got to pass to write callback. After a write succeded, we will move a point to a next element of writequeue chain.  So, no personal queues for plugins - reduce used memory.

Writequeue elm will be dequeued when all plugins are succeded or then time to live expired.

**Comment by octo** [comment]
@rpv-tomsk #2480, let's discuss there

**Comment by sunkuranganath** [comment]
This issue was discussed in community bi-weekly call as noted in: https://collectd.org/wiki/index.php/MinutesApr17th20 

Discussion provided:
![image](https://user-images.githubusercontent.com/16784251/79623523-a439e800-80d1-11ea-9158-e9826209bc46.png)

**Comment by eero-t** [comment]
Collectd v6-RC release implements per-write-plugin threading: https://github.com/collectd/collectd/releases/tag/collectd-6.0.0.rc0

Does that fix the issue?

**Comment by octo** [comment]
I think so. WDYT @faxm0dem?

**Comment by faxm0dem** [comment]
Hell yeah !
