### ISSUE TITLE
collectd oracle plugin: example for oracle configuration files

### ISSUE THREAD

**Issue by wpengcheng** [collectd/collectd#2106]
I want monitor oracle through collectd's oracle plugin,but the collectd official website only have 2 example ,
I want monitor more oracle database information,So ,Where there is more configuration oracle file case.

## 
https://www.collectd.org/wiki/index.php/Plugin:Oracle

IO per Tablespace ,DB efficiency,I want to more ...

**Comment by rubenk** [comment]
You can write arbitrary SQL to get the metrics you want. I don't think the collectd wiki is the right place to describe Oracle internals, you'll have to consult Oracle's documentation for that.

Of course it is a wiki so if you have more examples they are always welcome. Ask on irc or the mailing list for a wiki account.
