### ISSUE TITLE
Perl plugin_register(TYPE_READ) doesn't work

### ISSUE THREAD

**Issue by iain-buclaw-sociomantic** [collectd/collectd#2107]
*   Version of collectd: 5.7.0
*   Operating system / distribution: Linux

## Expected behavior

Functions registers from perl to be called in the read-loop.

## Actual behavior

Functions not called at all.

## Steps to reproduce

*   Upgrade from 5.6.2 to 5.7.0
*   Run collectd
*   Observe that stats are no longer sent from perl plugins.

Extremely abridged example plugin/config:
```
sub foo_read {
  plugin_dispatch_values ({
    'time' => time(),
    'plugin' = >'foo',
    'type' => 'gauge',
    'values' => [ 1 ],
  });
}
plugin_register (TYPE_READ, 'foo', 'foo_read');
```
```
LoadPlugin perl
<Plugin perl>
  LoadPlugin foo
</Plugin>
```
This works in collectd version 5.6.2.  Also `plugin_register (TYPE_CONFIG)` is called without incident either.  Haven't tested others, but it appears that it's just `TYPE_READ` that no longer works.

**Comment by rpv-tomsk** [comment]
Hi! 

Did you set up and use recent and correct version of Collectd.pm file?

**Comment by iain-buclaw-sociomantic** [comment]
I was testing inside a build directory:
```
IncludeDir "/collectd/build/bindings/buildperl"
```
I am *fairly* confident that it was a clean 5.7 build.  However I have since been switching between the 5.6 and 5.7 branch in the midst of working out what was wrong.

If `Collectd.pm` is the old version, and didn't get updated, then that might be a build/makefile problem.

I'll try removing `./bindings` and let it regenerate.

**Comment by iain-buclaw-sociomantic** [comment]
Yeah, I've just done a new fresh build, it's not taking it.
```
$ ./src/daemon/collectd -f -C collectd.conf
logfile plugin: fopen (/opt/collectd/var/log/collectd.log) failed: No such file or directory
logfile plugin: fopen (/opt/collectd/var/log/collectd.log) failed: No such file or directory
,,[2016-12-15 11:56:04] plugin_load: plugin "perl" successfully loaded.
[2016-12-15 11:56:04] plugin_load: plugin "write_log" successfully loaded.
[2016-12-15 11:56:04] perl: Initializing Perl interpreter...
[2016-12-15 11:56:04] Initialization complete, entering read-loop.
```
Interval is set to 1, and nothing is being sent to `write_log`.

**Comment by iain-buclaw-sociomantic** [comment]
Actually, now I'm getting results.  :thinking:

I'll just rebuild this again and double check that it's working as expected.

**Comment by iain-buclaw-sociomantic** [comment]
I'll just close this for now.
