### ISSUE TITLE
Failed to parse string as absolute: (null).

### ISSUE THREAD

**Issue by irocks04** [collectd/collectd#2109]
*   Version of collectd: collectd-4.10.9-3.el6.x86_64
*   Operating system / distribution: Rhel

## Expected behavior

I would like to have the string values fetched by dbi plugin to be displayed
## Actual behavior

Fails to parse string . In the typesDb i have defined a custom type for ABSOLUTE which works for numbers but for some reason fails for string and data types.
Can you point me to the type that i need to select for parsing strings returned by dbi.

The query returns 'Success' string but since type is defined as absolute it doesn't work
db query utils: udb_result_submit: Parsing `Success' as absolute failed.
[2016-12-15 11:15:02] db query utils: udb_query_handle_result (XXXXXXX, requestId): All results failed.

(Description of the behavior / output that you observed)

**Comment by rubenk** [comment]
Collectd doesn't support strings.
