### ISSUE TITLE
How to install Netapp plugin?

### ISSUE THREAD

**Issue by avinchakov** [collectd/collectd#2116]
Version of collectd: 5.7.0.15
Operating system / distribution: Ubuntu 14.04

There is no plugin for netapp. There is no netapp.so in /usr/lib/collectd. How to setup it?

**Comment by rubenk** [comment]
You'll need to compile collectd from source against the OnTAP SDK. More details are at https://collectd.org/wiki/index.php/Plugin:NetApp
