### ISSUE TITLE
collectd python plugin not working

### ISSUE THREAD

**Issue by ddimri** [collectd/collectd#2117]
*   Version of collectd:
**collectd 5.6.0**
*   Operating system / distribution:
**centos 7**
## Expected behavior
I have written below custom python plug-in for collectd:
```
import random
import ldap
import collectd
l = ldap.initialize('ldap://localhost')
username = "CN=Directory Manager"
password  = "xxxxx"
l.simple_bind(username, password)

def writer(input_data=None):
#    collectd.info('LDAP replication status write. Data sent: '+ str(input_data))
    collectd.info('LDAP replication status write')
#def configer(confObj):
#    collectd.info('config called')

def init_fun():
    collectd.info('------ init -------')
def config(conf):
    collectd.info('------ config ------')

def read(data=None):
#    collectd.info('------ read ------')
    base = "cn=config"
    searchScope = ldap.SCOPE_SUBTREE
    retrieveAttributes = None
    searchFilter = "objectClass=nsDS5ReplicationAgreement"
    to_dispatch = []
    Data =  l.search_s(base, searchScope, searchFilter, retrieveAttributes)
    for dat in Data:
        val = dat[1]["nsds5replicaLastUpdateStatus"][0]
        if "0" in val: to_dispatch = [0]
        elif "-1" in val: to_dispatch = [-1]
        print to_dispatch
        vl = collectd.Values(type='gauge')
        vl.plugin='python.ipa'
        vl.dispatch(values=to_dispatch)
    #vl = collectd.Values(type='gauge')
    #vl.plugin='python.spam'
    #vl.dispatch(values=to_dispatch)

collectd.register_config(config)
collectd.register_init(init_fun)
collectd.register_read(read)
collectd.register_write(writer)
```
This plugin binds to LDAP and look for nsds5replicaLastUpdateStatus and pushes the output to graphite.  I expect collectd process to start without any error.   my collectd.conf file python stanza is:

```
<Plugin python>
        ModulePath "/usr/lib64/collectd"
        LogTraces true
        Interactive true
        Import "pyPlugin"
        Import "getsigchld"
#
        <Module pyPlugin>
                pyPlugin "input"
        </Module>
</Plugin>
```

 
(Description of the behavior / output that you expected)

I expect collectd to start normally. 

## Actual behavior

python plug-in code does not work in centos 7. collectd process does not start if i enable the python plugin in my collectd.conf.

This is the error i am getting:

> systemctl restart collectd
> Job for collectd.service failed because the control process exited with error code. See "systemctl status collectd.service" and "journalctl -xe" for details.

> Dec 20 08:29:50 ip-172-16-248-9 collectd[4895]: python plugin: Error importing module "pyPlugin".
> Dec 20 08:29:50 ip-172-16-248-9 collectd[4895]: Unhandled python exception in importing module: SERVER_DOWN: {'desc': "Can't contact LDAP server"}
> Dec 20 08:29:50 ip-172-16-248-9 collectd[4895]: Traceback (most recent call last):
> Dec 20 08:29:50 ip-172-16-248-9 collectd[4895]:  File "/usr/lib64/collectd/pyPlugin.py", line 9, in <module>#012    l.simple_bind(username, password)
> Dec 20 08:29:50 ip-172-16-248-9 collectd[4895]:  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 201, in simple_bind#012    return self._ldap_call(self._l.simple_bind,who,cred,RequestControlTuples(serverctrls),RequestControlTuples(clientctrls))
> Dec 20 08:29:50 ip-172-16-248-9 collectd[4895]:  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 99, in _ldap_call#012    result = func(*args,**kwargs)
> Dec 20 08:29:50 ip-172-16-248-9 collectd[4895]: SERVER_DOWN: {'desc': "Can't contact LDAP server"}
> Dec 20 08:29:50 ip-172-16-248-9 collectd[4895]: python plugin: Found a configuration for the "pyPlugin" plugin, but the plugin isn't loaded or didn't register a configuration callback.
> Dec 20 08:29:50 ip-172-16-248-9 collectd: Error: Reading the config file failed!

(Description of the behavior / output that you observed)

## Steps to reproduce

*   install collectd on centos 7 ( i am using AWS centos 7 AMI)
*   enable python plugin in /etc/collectd.conf with the code to bind and do ldapsearch 
*   try to restart the collectd and you should see the error

**Comment by rubenk** [comment]
```
Dec 20 08:29:50 ip-172-16-248-9 collectd[4895]: Unhandled python exception in importing module: SERVER_DOWN: {'desc': "Can't contact LDAP server"}
```

You need to handle exceptions in your plugin.

**Comment by ddimri** [comment]
Thanks @rubenk for the reply. Cant make out why ldap connection is not going through, getting  **Error while binding with LDAP Connection** with below:
```
try:
    l = ldap.initialize('ldap://localhost:389')
except:
    print "Error while initialising connection to localhost"
username = "CN=Directory Manager"
password  = "passw0rd"
try:
    l.simple_bind(username, password)
except:
    print "Error while binding with LDAP Connection"
```
any pointer you could offer would be highly appreciated.

**Comment by rubenk** [comment]
@ddimri I'm sorry, but this has nothing to do with collectd, and I can't help you debug your python code.
