### ISSUE TITLE
mqtt plugin possible resource leak

### ISSUE THREAD

**Issue by nuclearcat** [collectd/collectd#2123]
*   Version of collectd: git latest
*   Operating system / distribution: ubuntu

## Expected behavior
Stable operation

## Actual behavior
After while:
Dec 24 06:25:36 monitor-server collectd[24549]: mqtt plugin: unable to reconnect to broker
Dec 24 06:25:36 monitor-server collectd[24549]: mqtt plugin: publish failed: Connection pending.
Dec 24 06:25:36 monitor-server collectd[24549]: mqtt_connect_broker: mosquitto_connect failed: Lookup error.
Dec 24 06:25:36 monitor-server collectd[24549]: mqtt plugin: unable to reconnect to broker
Dec 24 06:25:36 monitor-server collectd[24549]: mqtt plugin: publish failed: Connection pending.
Dec 24 06:25:36 monitor-server collectd[24549]: mqtt_connect_broker: mosquitto_connect failed: Lookup error.
Dec 24 06:25:36 monitor-server collectd[24549]: mqtt plugin: unable to reconnect to broker
Dec 24 06:25:36 monitor-server collectd[24549]: mqtt plugin: publish failed: Connection pending.
Dec 24 06:25:36 monitor-server collectd[24549]: mqtt_connect_broker: mosquitto_connect failed: Lookup error.

in lsof i can see a lot of:
collectd  24549 24567        root  779u     IPv4          491031328        0t0        TCP localhost:34144->localhost:1883 (CLOSE_WAIT)
collectd  24549 24567        root  780u     IPv4          491036255        0t0        TCP localhost:35194->localhost:1883 (CLOSE_WAIT)
collectd  24549 24567        root  781u     IPv4          491036602        0t0        TCP localhost:36204->localhost:1883 (CLOSE_WAIT)
collectd  24549 24567        root  782u     IPv4          491032276        0t0        TCP localhost:35162->localhost:1883 (CLOSE_WAIT)
collectd  24549 24567        root  783u     IPv4          491036251        0t0        TCP localhost:35184->localhost:1883 (CLOSE_WAIT)

This is clearly resource leak

Also there is possible other bug which trigger this leak (i will debug why it return this error), before leak happening i noticed this error messages:
Dec 23 11:44:02 monitor-server collectd[60403]: mqtt plugin: mosquitto_publish failed: Invalid function arguments provided.
Dec 23 11:44:02 monitor-server collectd[60403]: mqtt plugin: publish failed: Connection pending.
Dec 23 11:44:02 monitor-server collectd[60403]: mqtt plugin: successfully reconnected to broker "localhost:1883"
Dec 23 11:44:02 monitor-server mosquitto[31561]: Client collectd-mqtt already connected, closing old connection.
Dec 23 11:44:02 monitor-server mosquitto[31561]: Client collectd-mqtt disconnected.
Dec 23 11:44:02 monitor-server mosquitto[31561]: New client connected from 127.0.0.1 as collectd-mqtt (c0, k60, u'voice').
Dec 23 11:44:12 monitor-server collectd[60403]: mqtt plugin: mosquitto_publish failed: Invalid function arguments provided.
Dec 23 11:44:12 monitor-server collectd[60403]: mqtt plugin: publish failed: Connection pending.
Dec 23 11:44:12 monitor-server collectd[60403]: mqtt plugin: successfully reconnected to broker "localhost:1883"

## Steps to reproduce

It is hard to reproduce, bug appearing after running mqtt publish on loaded system approx 1-2 times per day.

As i suspect reason might be here (it is possible patch to fix issue):
diff --git a/src/mqtt.c b/src/mqtt.c
index 33785c8..cd7b4ac 100644
--- a/src/mqtt.c
+++ b/src/mqtt.c
@@ -448,6 +449,7 @@ static int publish(mqtt_client_conf_t *conf, char const *topic,
      * measure; we will try to reconnect the next time we have to publish a
      * message */
     conf->connected = 0;
+    mosquitto_disconnect(conf->mosq);
 
     pthread_mutex_unlock(&conf->lock);
     return (-1);

On any publish error (even if it is just invalid topic or payload) it will set connected 0, without actually disconnecting and releasing resources, so following _connect might cause resource leak, because old, still used socket will be overwritten, without being actually closed. I am not certainly sure how libmosquitto handling that, but definitely it is safer to disconnect after setting state value as disconnected.
I'm still testing this patch and searching if this leak maybe happening elsewhere.

**Comment by nuclearcat** [comment]
I found also how this resource leak was triggered. Error possible, because mqtt doesn't allow # and + symbols in topic name and it will fail to publish data if they are present.
In my case it is (debug string i did in publish error):
Dec 25 20:43:20 monitor-server collectd[10519]: attempted to publish 17 bytes '1482691400.450:2' payload '/test/collectd/monitor/dns/dns_qtype-#48' topic

So i believe in format_topic function this symbols should be replaced. I am not sure i can do appropriate coding style, should i try to fix it and submit patch? (i believe it is too tiny fix for all story with pull request)

**Comment by rubenk** [comment]
Yes, please submit a patch.

**Comment by nuclearcat** [comment]
diff --git a/src/mqtt.c b/src/mqtt.c
index 33785c8..a962514 100644
--- a/src/mqtt.c
+++ b/src/mqtt.c
@@ -448,6 +448,7 @@ static int publish(mqtt_client_conf_t *conf, char const *topic,
      * measure; we will try to reconnect the next time we have to publish a
      * message */
     conf->connected = 0;
+    mosquitto_disconnect(conf->mosq);
 
     pthread_mutex_unlock(&conf->lock);
     return (-1);
@@ -461,6 +462,7 @@ static int format_topic(char *buf, size_t buf_len, data_set_t const *ds,
                         value_list_t const *vl, mqtt_client_conf_t *conf) {
   char name[MQTT_MAX_TOPIC_SIZE];
   int status;
+  char *c;
 
   if ((conf->topic_prefix == NULL) || (conf->topic_prefix[0] == 0))
     return (FORMAT_VL(buf, buf_len, vl));
@@ -473,6 +475,10 @@ static int format_topic(char *buf, size_t buf_len, data_set_t const *ds,
   if ((status < 0) || (((size_t)status) >= buf_len))
     return (ENOMEM);
 
+  while((c = strchr(buf, '#')) || (c = strchr(buf, '+'))) {
+       *c = '_';
+  }
+
   return (0);
 } /* int format_topic */

Is it possible to avoid fork & pull stage? :) Because it is time consuming for such trivial issue.
I guess such way is safe, because topic is null terminated.

**Comment by nuclearcat** [comment]
`diff --git a/src/mqtt.c b/src/mqtt.c
index 33785c8..a962514 100644
--- a/src/mqtt.c
+++ b/src/mqtt.c
@@ -448,6 +448,7 @@ static int publish(mqtt_client_conf_t *conf, char const *topic,
      * measure; we will try to reconnect the next time we have to publish a
      * message */
     conf->connected = 0;
+    mosquitto_disconnect(conf->mosq);
 
     pthread_mutex_unlock(&conf->lock);
     return (-1);
@@ -461,6 +462,7 @@ static int format_topic(char *buf, size_t buf_len, data_set_t const *ds,
                         value_list_t const *vl, mqtt_client_conf_t *conf) {
   char name[MQTT_MAX_TOPIC_SIZE];
   int status;
+  char *c;
 
   if ((conf->topic_prefix == NULL) || (conf->topic_prefix[0] == 0))
     return (FORMAT_VL(buf, buf_len, vl));
@@ -473,6 +475,10 @@ static int format_topic(char *buf, size_t buf_len, data_set_t const *ds,
   if ((status < 0) || (((size_t)status) >= buf_len))
     return (ENOMEM);
 
+  while((c = strchr(buf, '#')) || (c = strchr(buf, '+'))) {
+       *c = '_';
+  }
+
   return (0);
 } /* int format_topic */
`

Should be safe, because topic is printed over snprintf and null terminated

**Comment by nuclearcat** [comment]
I submitted pull request

**Comment by mfournier** [comment]
Closed by 98bfe15
