### ISSUE TITLE
Plugin: OpenVPN 2.4.0: Unknown file format openvpn-status.log

### ISSUE THREAD

**Issue by ZdenekBrichacek** [collectd/collectd#2128]
*   Version of collectd:
5.6.2-1
*   Operating system / distribution:
Arch Linux

OpenVPN 2.4.0 is the latest version.

## Collectd startup log
collectd[19594]: openvpn plugin: /var/log/openvpn-status.log: Unknown file format, please report this as bug. Make sure to include your status file, so the plugin can be adapted.
collectd[19594]: openvpn plugin: unable to detect status version, discarding status file "/var/log/openvpn-status.log".

## /var/log/openvpn-status.log
TITLE,OpenVPN 2.4.0 i686-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Dec 28 2016
TIME,Sat Dec 31 15:06:07 2016,1483193167
HEADER,CLIENT_LIST,Common Name,Real Address,Virtual Address,Virtual IPv6 Address,Bytes Received,Bytes Sent,Connected Since,Connected Since (time_t),Username,Client ID,Peer ID
CLIENT_LIST,ntafs,133.2.11.3,10.1.1.8,2002:232:324:12::8,521679042,155407560,Fri Dec 30 13:41:11 2016,1483101671,UNDEF,1,1
CLIENT_LIST,ntgw1,89.103.243.123,10.1.1.1,2002:232:324:3::1,174702344,524013574,Fri Dec 30 13:41:09 2016,1483101669,UNDEF,0,0
CLIENT_LIST,ntgw2,109.42.11.5,10.1.1.2,2002:232:324:3::2,75385422,159641242,Fri Dec 30 13:41:14 2016,1483101674,UNDEF,2,2
HEADER,ROUTING_TABLE,Virtual Address,Common Name,Real Address,Last Ref,Last Ref (time_t)
ROUTING_TABLE,2002:232:324:b32a::faa3C,ntafs,133.2.11.3,Sat Dec 31 15:05:28 2016,1483193128
ROUTING_TABLE,10.1.1.8,ntafs,133.2.11.3,Sat Dec 31 15:06:04 2016,1483193164
ROUTING_TABLE,2002:232:324:12::8,ntafs,133.2.11.3,Sat Dec 31 15:06:04 2016,1483193164
GLOBAL_STATS,Max bcast/mcast queue length,2
END

**Comment by rpv-tomsk** [comment]
Hi, @octo!

What do you think if this plugin will be reworked  to automatic detection of fields position in "HEADER,CLIENT_LIST,..." line?

**Comment by julianbrost** [comment]
I also just ran into this problem. Is there any progress? Why is this labeled pending feedback?

**Comment by rpv-tomsk** [comment]
>Why is this labeled pending feedback?

The 'pending feedback' is a flag what issue requires attention from core team.

>Is there any progress?

There is no progress from me. I do not know about others.
I see no answer to my question here. Personally I'm uninterested to writing patches which will be frozen (which will hang in 'Pull requests' for a months or a year), unless that problem touches me explicitly.

**Comment by rpv-tomsk** [comment]
Hi, @octo!

What do you think if this plugin will be reworked to automatic detection of fields position in "HEADER,CLIENT_LIST,..." line?

@julianbrost, are you can to try patches?

**Comment by rpv-tomsk** [comment]
The plan is:

- Parse OpenVPN status file `HEADER` lines to find the positions of the required fields. That will fix of OpenVPN `status-version 3` format support and allows to support status files from openvpn-2.4 and future versions;
- Change file version detection from configuration phase to read phase;
- Switch to `plugin_register_complex_read`

That will be big rework of plugin, fully backwards-compatible by Collectd configuration. 
@octo, Does that work will have chances to go to 5.8?

**Comment by rpv-tomsk** [comment]
Created a pull-request with an implementation.

Please review/test/use it.
