### ISSUE TITLE
Pre-built collectd python plugin for el-6 incompatible with python 2.7

### ISSUE THREAD

**Issue by matthias50** [collectd/collectd#2131]
*   Version of collectd: 5.6.2.5 installed from here: https://pkg.ci.collectd.org/rpm/collectd-5.6/epel-6-x86_64/
*   Operating system / distribution: Amazon Linux

## Expected behavior
Python 2.7 code will be correctly interpreted by the python plugin. Another way of expressing this is that I expect the python.so to be linked against libpython2.7.so. 

[root@i-0bfc13281eac73d34 collectd-5.6.2]# ldd /opt/collectd/lib/collectd/python.so
                linux-vdso.so.1 =>  (0x00007ffe62ff2000)
->            libpython2.7.so.1.0 => /usr/lib64/libpython2.7.so.1.0 (0x00007fcf5eb4f000)
                libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fcf5e933000)
                libutil.so.1 => /lib64/libutil.so.1 (0x00007fcf5e72f000)
                libm.so.6 => /lib64/libm.so.6 (0x00007fcf5e42d000)
                libdl.so.2 => /lib64/libdl.so.2 (0x00007fcf5e229000)
                libc.so.6 => /lib64/libc.so.6 (0x00007fcf5de66000)
                /lib64/ld-linux-x86-64.so.2 (0x00007fcf5f142000)
## Actual behavior
Python 2.7 plugins crash and dump a stack trace to syslog when 2.7 specific code is encountered. 

Here is what I get from ldd. Note that libpython2.6.so is linked:
[root@i-0119b2e1053b5c9a6 ~]# ldd /usr/lib64/collectd/python.so
                linux-vdso.so.1 =>  (0x00007ffffbcd4000)
                libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f7720ee7000)
                libutil.so.1 => /lib64/libutil.so.1 (0x00007f7720ce4000)
                libm.so.6 => /lib64/libm.so.6 (0x00007f77209e1000)
->            libpython2.6.so.1.0 => /usr/lib64/libpython2.6.so.1.0 (0x00007f772063d000)
                libdl.so.2 => /lib64/libdl.so.2 (0x00007f7720439000)
                libc.so.6 => /lib64/libc.so.6 (0x00007f7720076000)
                /lib64/ld-linux-x86-64.so.2 (0x00007f772131a000)
## Steps to reproduce
* Edit collectd.conf to include a python plugin with 2.7 code
* Restart collectd.

**Comment by rubenk** [comment]
Our packages are built and linked against libpython 2.6, which is the version shipped by Red Hat / CentOS. I take it Amazon Linux ships a newer python version? In that case you'll need to rebuild the packages from source.
