### ISSUE TITLE
DF plugin reports wrong percentage values compared to system df -h command

### ISSUE THREAD

**Issue by kpatronas** [collectd/collectd#2132]
*   Version of collectd: 5.6.0
*   Operating system / distribution: centos-release-7-3.1611.el7.centos.x86_64 Kernel: Linux 3.10.0-514.el7.x86_64

I have the following configuration of the df plugin

```
<Plugin df>
        ValuesPercentage true
</Plugin>
```

i assume that the used bytes percentage should be the same as the df -h command. but csv output of the plugin differs from df -h output:
```
[root@ELK sbin]# cat /var/lib/collectd/csv/ELK/df-mnt-newdisk/percent_bytes-used-2017-01-03 
1483471772.500,2.996459
```
df -h output:
```
[root@ELK sbin]# df -h
Filesystem           Size  Used Avail Use% Mounted on
/dev/sdb1             67G  2.1G   62G   4% /mnt/newdisk
```

**Comment by kpatronas** [comment]
Update: same behaviour to 5.7.0 as well

**Comment by rpv-tomsk** [comment]
Please look into `df` (without any options) output and calculate percentage yourself.

**Comment by rpv-tomsk** [comment]
Any comments? If no, may we assume that issue is solved?

**Comment by kpatronas** [comment]
It can close was a conf error of me
