### ISSUE TITLE
Cannot make df plugin report available disk space for all partitions

### ISSUE THREAD

**Issue by portela-simbiose** [collectd/collectd#2136]
*   Version of collectd: 5.5
*   Operating system / distribution: Ubuntu 16.04

## Expected behavior

I'm using collectd to collect metrics from multiple sources and [Librato](librato.com) for visualization. However, in one of my clusters, I cannot make `df` plugin report all space available from `/` and `/home`.

As you can see, these mount points are in different `ext4` partitions:

```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        20G  1.4G   17G   8% /
devtmpfs        3.9G     0  3.9G   0% /dev
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           3.9G  125M  3.8G   4% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/sda3       1.8T  8.9G  1.7T   1% /home
tmpfs           789M     0  789M   0% /run/user/0

$ cat /etc/fstab
# <file system>	<mount point>	<type>	<options>	<dump>	<pass>
/dev/sda2	/	ext4	errors=remount-ro,relatime	0	1
/dev/sda3	/home	ext4	defaults,relatime	1	2
/dev/sda4	swap	swap	defaults	0	0
proc		/proc	proc	defaults		0	0
sysfs		/sys	sysfs	defaults		0	0
devtmpfs	/dev	devtmpfs	rw	0	0
```

I expected it to report both 17G and 1.7T available for `/` and `/home` respectively.

Here is my current configuration regarding `df`:

```
<Plugin "df">
  MountPoint "/"
  MountPoint "/home"
</Plugin>

...

LoadPlugin "match_regex"

<Chain "PostCache">
    <Rule "ignore_df_reserved_used_metrics">
        <Match "regex">
            Plugin "^df"
            TypeInstance "^(reserved|used)"
        </Match>
        Target "stop"
    </Rule>

    # Default behavior
    Target "write"
</Chain>
```

## Actual behavior

Although I correctly receive the space associated to `root`, it reports about 4GB for `/home`.

**Comment by mfournier** [comment]
5.5 is EOL on our side. Can you check if a current version (ie: 5.7) still has this issue please ?

We have nightly builds for ubuntu xenial, so this should be pretty straightforward: https://pkg.ci.collectd.org/deb/dists/xenial/

**Comment by portela-simbiose** [comment]
Using the last version (5.7.1.6) indeed solved this problem. Thanks for your suggestion.

It must be noticed though that Ubuntu's package is still installing version 5.5.
