### ISSUE TITLE
Cannot add V5.7.0.15 on Ubuntu 16.10 Yakkety using add-apt-repository

### ISSUE THREAD

**Issue by pantaluna** [collectd/collectd#2144]
*   Version of collectd: 5.7.0.15
*   Operating system / distribution:
Ubuntu 16.10 yakkety

## Expected behavior
Adding a valid apt repository for Collectd V5.7.0.15 using the standard Collectd C.I. environment.

## Actual behavior
Error when running ````apt-get update```` (so I cannot install V5.7.0.15 using ````apt-get install````)

Error: E: Failed to fetch http://pkg.ci.collectd.org/deb/dists/yakkety/collectd-5.7/binary-amd64/Packages  404  Not Found

## Steps to reproduce
````
add-apt-repository "deb http://pkg.ci.collectd.org/deb yakkety collectd-5.7"
gpg --recv-keys 3994D24FB8543576
gpg --export -a 3994D24FB8543576 | apt-key add -
apt-get update
````

## Notes
* The procedure works fine for Ubuntu 14.x (trusty) on my other servers.
* The standard Ubuntu 16.10 repo's contain the older version Collectd V5.5.2-1
* I also tried it with collectd-5.6 and collectd-5.5 but the same error.

**Comment by mfournier** [comment]
Indeed, there are no nightliy builds for this ubuntu release. We chose to only target the LTS releases.
