### ISSUE TITLE
Collectd running inside Docker Container

### ISSUE THREAD

**Issue by vsonone** [collectd/collectd#2148]
we have installed collectd inside a docker container. We are using the memory/cpu and graphite write plugin to report the statistics to graphite.

We are noticing that even though collectd is running inside the container, it is reporting the memory/cpu metrics for the Host (on which the container is running). It is not reporting these metrics for the container.

Can you please suggest, if collectd is run inside a container, then there is a way to get the statistics for the container?

**Comment by mfournier** [comment]
You can use this wrapper in contrib/ which catches `fopen()` calls to `/proc` and `/sys` and rewrites them prefixed with `/rootfs/`. Then simply map these directories from the host inside your container. See https://github.com/collectd/collectd/blob/master/contrib/README#L52-L65

**Comment by vsonone** [comment]
Thanks for the prompt reply. I will give this a try.

**Comment by vsonone** [comment]
Will this work with the collectd build that we (5.5) have by just modifying the configuration or do we need a new collectd installable?

**Comment by mfournier** [comment]
Yes, this is pretty generic and should work with older collectd versions too.

**Comment by vsonone** [comment]
It is still giving host metrics...this wrapper is supposed to report container memory cpu etc right? There will be multiple containers running on the same host....if we map /proc folder on host to /rootfs folder in container...then wouldnt it report host metrics itself...how are different container info seperated in /proc and /sys folder?

**Comment by mfournier** [comment]
If you're aiming for per-container cpu and memory counters, indeed this is not the way to go.

There is a python-based collectd plugin somewhere on github which fetches this data from the docker API. Or maybe consider using cadvisor instead of collectd, which is more widely used.
