### ISSUE TITLE
write_prometheus plugin fails when IPv6 is disabled on OS

### ISSUE THREAD

**Issue by msaraf** [collectd/collectd#2149]
*   Version of collectd: 5.7.0.151
*   Operating system / distribution: CentOS Linux release 7.3.1611

## Expected behavior

write_prometheus plugin should bind to the network interface and serve requests

## Actual behavior

write_prometheus plugin fails with the following error:
```
collectd[11578]: write_prometheus plugin: MHD_start_daemon() failed.
collectd[11578]: Initialization of plugin `write_prometheus' failed with status -1. Plugin will be unloaded.
```

## Steps to reproduce

*   Install on RHEL/CentOS 7 Server with IPv6 disabled
*   Configure write_prometheus to load
*   Start collectd and examine logs

## Cause of behavior

_src/write_prometheus.c:759_
In an environment where IPv6 is disabled, the use of the ```MHD_USE_DUAL_STACK``` flag causes MHD_start_daemon() to fail.

**Comment by msaraf** [comment]
I'm implemented a plugin parameter to handle this issue.  The parameter is called ```EnableIPv6``` that defaults to false.  I'll submit a PR if you feel this is the right way to fix the issue.

**Comment by mfournier** [comment]
Thanks for reporting this problem, and working on a fix !

From the end-user point of view, I think it would be nicer to not have to deal with these details by default: enable the plugin, it works, move on to more important stuff.
I didn't look at how this could be done though.

**Comment by mojili** [comment]
I get below log on /var/log/messages:

# write_prometheus plugin: MHD_start_daemon() failed.
# Initialization of plugin `write_prometheus' failed with status -1. Plugin will be unloaded.

checked the /var/log/audit/audit.log and see " avc:  denied  { name_bind } for  pid=xxxxx comm="collectd" src=9103 " for collectd. my selinux mode is enforcing and I solved my problem like this:

# yum -y install policycoreutils-python
# semanage permissive -a collectd_t


# plugin_load: plugin "syslog" successfully loaded.
# plugin_load: plugin "cpu" successfully loaded.
# plugin_load: plugin "interface" successfully loaded.
# plugin_load: plugin "load" successfully loaded.
# plugin_load: plugin "memory" successfully loaded.
# plugin_load: plugin "uptime" successfully loaded.
# plugin_load: plugin "write_prometheus" successfully loaded.
# Initialization complete, entering read-loop.

**Comment by yves-vogl** [comment]
I can confirm this issue for ```collectd-write_prometheus-5.7.1-2.el7.x86_64```


```
Name        : collectd-write_prometheus
Arch        : x86_64
Version     : 5.7.1
Release     : 2.el7
Size        : 40 k
Repo        : installed
From repo   : epel
Summary     : Prometheus output plugin for collectd
URL         : https://collectd.org/
License     : GPLv2
Description : This plugin exposes collected values using an embedded HTTP
            : server, turning the collectd daemon into a Prometheus exporter.
```

**Comment by octo** [comment]
Yeah, for *libmicrohttpd* "dual stack" means "IPv6 (but gracefully allow IPv4, too)" and without IPv6 this will fail. It'd be nice if the library would be a bit more dual-stacky, but for the time being we have to work around this …
