### ISSUE TITLE
Collectd unable to find dpdk.so in the src folder 

### ISSUE THREAD

**Issue by prateek1192** [collectd/collectd#2153]
*   Version of collectd: collectd-5.7.0
*   Operating system / distribution: Fedora 25 64 bit processsor on a 64 bit machine

## Expected behavior

To see the build without any error messages

## Actual behavior

Missing file with message in the end 
File not found: /root/rpmbuild/BUILDROOT/collectd-5.7.0-2.fc25.x86_64/usr/lib64/collectd/dpdk.so

## Steps to reproduce

*   Try compiling collectd on Fedora 25 with dpdk plugin enabled

Some additional details to rule out some cases
 
The following are the gcc, dpdk and dpdk-devel versions installed (16.04). I have confirmed using the following commands

[root@]# gcc --version
gcc (GCC) 6.3.1 20161221 (Red Hat 6.3.1-1)
Copyright (C) 2016 Free Software Foundation, Inc.

[root@]# dnf install dpdk dpdk-devel
Last metadata expiration check: 0:33:26 ago on Wed Jan 25 12:43:00 2017.
Package dpdk-16.04-1.fc25.x86_64 is already installed, skipping.
Package dpdk-devel-16.04-1.fc25.x86_64 is already installed, skipping.

The compilation does not show any errors or warnings 
[config.txt](https://github.com/collectd/collectd/files/728939/config.txt)

[buildlog.txt](https://github.com/collectd/collectd/files/728941/buildlog.txt)

**Comment by rubenk** [comment]
The plugin is dpdkstat.so, not dpdk.so. You're trying to package the wrong file.
