### ISSUE TITLE
RouterOS plugin gives no interface stats.

### ISSUE THREAD

**Issue by darkcloud784** [collectd/collectd#2160]
*   Version of collectd: 5.4.1
*   Operating system / distribution: Ubuntu 14.04

## Expected behavior
Plugin provides stats.

## Actual behavior

Gives no output for any interface.

--------------------------------------

Collectd.conf for plugin.

```
 <Plugin "routeros">
    <Router>
      Host "xx.xx.xx.xx"
      Port "8729"
      User "*****"
      Password "******"
      CollectInterface true
      CollectCPULoad true
      CollectMemory true
    </Router>
  </Plugin>

```

**Comment by rubenk** [comment]
Please add your full config and any logs you have (if possible on debug level). If you could try a packet capture to see if collectd is querying your router that would be good to have too.

**Comment by rpv-tomsk** [comment]
Closed due to lack of response.
Also, described problem not confirmed by tests done by me.
