### ISSUE TITLE
Extend PUTVAL to allow specifying metadata

### ISSUE THREAD

**Issue by CAFxX** [collectd/collectd#2166]
*   Version of collectd: 5.7
*   Operating system / distribution: Ubuntu (collectd built from source)

## Expected behavior

We would like to have `PUTVAL` support the `type:key=value` option already supported by `PUTNOTIF` (https://collectd.org/documentation/manpages/collectd-exec.5.shtml#exec_data_format). This would allow us to specify custom tags (in our EXEC scripts) for use by our downstream monitoring/alerting systems.

## Actual behavior

PUTVAL silently ignores `type:key=value` options

## Steps to reproduce

- From a EXEC plugin emit a `PUTVAL` containing `s:key=value`
- Using a output plugin that supports JSON output, notice that the metadata is not populated with the `key: value`

**Comment by CAFxX** [comment]
@octo I'm not sure what the "Pending feedback" label means... do you need some feedback from us?

**Comment by CAFxX** [comment]
@octo @rubenk would you consider accepting a PR for this? if yes, any feedback on the idea?

**Comment by octo** [comment]
Hi @CAFxX,

that idea LGTM. If your implementation will extend beyond what `PUTNOTIF` already does, please outline your idea in two sentences so have to chance of having a discussion before you send a PR :)

Best regards,
—octo

**Comment by CAFxX** [comment]
@octo The idea would be to allow to do exactly what can be done via PUTNOTIF. Unfortunately it seems that the PUTVAL and PUTNOTIF parsers are completely disjoint in design and implementation, so it's going to be a little harder than I was expecting.

We put this in our backlog, if somebody wants to work on this feel free to go ahead.

**Comment by rpv-tomsk** [comment]
Superseeded: #2726
Superseeded: #3381
