### ISSUE TITLE
write_prometheus should support listening on specific interface

### ISSUE THREAD

**Issue by hasso** [collectd/collectd#2173]
At the moment write_prometheus supports listening on 0.0.0.0 or :: (depends on IPv6 (un)availability) only. That's not the way many users would want it to be, probably. Listening on specific address to specify either an interface or loopback would be preferred in most cases.

**Comment by flyinva** [comment]
I also would like write_prometheus could listen only one interface or address for security reason. The listening port shouldn't be open on production interface but only on admin network.

**Comment by octo** [comment]
FYI, we changed the plugin recently to open tthe socket itself and passing it to the HTTP library (#2466). This opens up the possibility to do this with relative ease.

**Comment by rpv-tomsk** [comment]
Related: #2288
