### ISSUE TITLE
[Feature request] add InfluxDB Line protocol to Kafka Writer

### ISSUE THREAD

**Issue by jeroenjacobs1205** [collectd/collectd#2177]
Hi,

Would it be possible to add the InfluxDB Line protocol to the Kafka writer plugin? In addition to PUTVAL, JSON and Graphite?

**Comment by HariSekhon** [comment]
@jeroenjacobs1205 

Why was this issue closed? Has it been implemented for the Kafka output or did you close it because nobody was working on it?
