### ISSUE TITLE
CentOS 5 pkg-ci builds haven't updated since December 2016

### ISSUE THREAD

**Issue by xyntrix** [collectd/collectd#2183]
*   Version of collectd:
5.7.1.13
*   Operating system / distribution:
CentOS 5 x86_64

## Expected behavior
Packages in the CentOS 5 repos should be same version as packages in the CentOS 6/7 repos

## Actual behavior
Packages in the CentOS 5 repos are not updated since December 2016

## Steps to reproduce

Browse to:
https://pkg.ci.collectd.org/rpm/collectd-5.7/epel-5-x86_64/

Compare:
https://pkg.ci.collectd.org/rpm/collectd-5.7/epel-6-x86_64/
or
https://pkg.ci.collectd.org/rpm/collectd-5.7/epel-7-x86_64/

Latest in cent6/7:
collectd-5.7.1.13.gf7e2d82-1.el7.centos.src.rpm  

Lastest in cent5:
collectd-5.7.0.22.gcdb49f3-2.el5.centos.src.rpm

**Comment by rubenk** [comment]
5.7 is the last release we support on CentOS 5. We stopped building packages for EPEL5 from master around december, but this probably broke the 5.7 builds.

As CentOS 5 will be End Of Life at the end of next month, I don't think it's worth the effort to fix this however.

**Comment by xyntrix** [comment]
Seems reasonable. We'll pass along the expectations around 5.7.0 being the terminating official upstream rpm release for CentOS 5.

Thanks!

**Comment by rubenk** [comment]
Alright! Note that 5.7.1 should build fine from source still, if you need it.
