### ISSUE TITLE
pkg-ci release of ping plugin doesn't run under CentOS 7

### ISSUE THREAD

**Issue by xyntrix** [collectd/collectd#2187]
*   Version of collectd:
```
collectd-5.7.1.13.gf7e2d82-1.el7.centos.x86_64
collectd-curl-5.7.1.13.gf7e2d82-1.el7.centos.x86_64
collectd-disk-5.7.1.13.gf7e2d82-1.el7.centos.x86_64
collectd-dns-5.7.1.13.gf7e2d82-1.el7.centos.x86_64
collectd-ipmi-5.7.1.13.gf7e2d82-1.el7.centos.x86_64
collectd-netlink-5.7.1.13.gf7e2d82-1.el7.centos.x86_64
collectd-ping-5.7.1.13.gf7e2d82-1.el7.centos.x86_64
```
```
# cat /etc/collectd.d/30-ping.conf
LoadPlugin ping
<Plugin ping>
    Host "8.8.8.8"
    Interval 5.0
    Timeout 1.0
    MaxMissed 5
</Plugin>
```
*   Operating system / distribution:
CentOS Linux release 7.3.1611 (Core)

## Expected behavior
Ping plugin loads

## Actual behavior
Feb 21 17:29:55 xxx collectd[29636]: ping plugin: ping_host_add (8.8.8.8) failed: Operation not permitted
Feb 21 17:29:55 xxx collectd[29636]: ping plugin: No host could be added to ping object. Giving up.
(Description of the behavior / output that you observed)

## Steps to reproduce

* Install collectd from pkg-ci release under CentOS 7
* Configure ping module
* Start collectd
* View log and note ping module not loading

Maybe this has similar issue to DNS plugin, where it attempts to bind to a literal interface named "any" and that's not really an interface name (Device)?

**Comment by rubenk** [comment]
Are you running collectd as an unprivileged user?

**Comment by rubenk** [comment]
Ah I just saw your other issue #2186. The same applies here so I'll close this one.
