### ISSUE TITLE
ntpd plugin: time offset loses sign 

### ISSUE THREAD

**Issue by NeilW** [collectd/collectd#2188]
*   Version of collectd:

Name        : collectd
Arch        : x86_64
Version     : 5.7.1
Release     : 1.el7

*   Operating system / distribution:

RH7/EPEL

## Expected behavior

kerninfo negative offsets should display correctly.

## Actual behavior

value is altered to unsigned equivalent value

## Steps to reproduce

graph loop time offset or estimated error where the value is negative and the value will be changed to a high positive value, e.g

for 
```
long ntx_offset = -179801;
long ntx_esterror = 75000;

```
you get

```
info_kernel:
  pll offset    = 4.2947875
  est error     = 7.5e-05

```

**Comment by mfournier** [comment]
Fixed by c0760b142 (5.6 was also affected by the problem, which got introduced by d4da902 in #1314). See also #2189.

Thanks !
