### ISSUE TITLE
How to match  a snmp oid and corresponding type variable in types.db automatically

### ISSUE THREAD

**Issue by dllhlx** [collectd/collectd#2195]
*   Version of collectd: 5.*
*   Operating system / distribution: all os 

## Expected behavior

when I get a snmp oid, we can automatically find corresponding variable from types.db.

**Comment by rubenk** [comment]
I don't understand what you mean, please describe in more detail what you want to accomplish.

**Comment by dllhlx** [comment]
@rubenk , I use snmp plugin to get oid's value remotely, the configure as below:
```
LoadPlugin snmp
<Plugin snmp>
    <Data "InterfaceTraffic">
        `Type "if_octets"`
        Table true
        Instance ".1.3.6.1.2.1.2.2.1.2"
        `Values ".1.3.6.1.2.1.31.1.1.1.6" ".1.3.6.1.2.1.31.1.1.1.10"`
    </Data>
    <Host "1.2.3.4">
        Address "1.2.3.4"
        Version 2
        Community "abcdefg"
        Collect InterfaceTraffic
        Interval 30
    </Host>

</Plugin>
```
but I should try many time to find

**Comment by rubenk** [comment]
This can't be done automatically based on the contents of snmp mibs. An oid can just be an Integer for example, so collectd can't know to what type to map that. You will need to do that yourself.

There are NMS solutions that do this, but they essentially have a huge mapping for all the common vendor MIBs. And if you get new equipment that is not mapped yet, you still need to do it by hand.

**Comment by dllhlx** [comment]
@rubenk  thanks a lot!
