### ISSUE TITLE
dpdkstats forking support

### ISSUE THREAD

**Issue by maryamtahhan** [collectd/collectd#2196]
Hi folks
I just wanted to give you a heads up that the cleanup functionality required for the dpdkstats plugin wasn't implemented for DPDK 17.02 and missed the window for 17.05. which means that the dpdkstats plugin will have the "process forking" behaviour for a while longer. if this is something that is not acceptable to you folks, we can investigate other means of retrieving dpdkstats and metrics through the exec plugin maybe?

Open to your feedback

BR
Maryam

**Comment by rubenk** [comment]
Hey Maryam. No problem, I'm fine with keeping the current behaviour for a while longer.
