### ISSUE TITLE
[ERROR] apt-get install collectd

### ISSUE THREAD

**Issue by lin-credible** [collectd/collectd#2218]
*   Version of collectd: latest
*   Operating system / distribution: `Ubuntu 16.04.1 LTS`

## Expected behavior

Install successfully

## Actual behavior

```
Err:2 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 libgtk-3-0 amd64 3.18.9-1ubuntu3.1
  404  Not Found [IP: 91.189.91.23 80]
...
E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/g/gtk+3.0/libgtk-3-common_3.18.9-1ubuntu3.1_all.deb  404  Not Found [IP: 91.189.91.23 80]

E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/g/gtk+3.0/libgtk-3-0_3.18.9-1ubuntu3.1_amd64.deb  404  Not Found [IP: 91.189.91.23 80]

E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/g/gtk+3.0/libgtk-3-bin_3.18.9-1ubuntu3.1_amd64.deb  404  Not Found [IP: 91.189.91.23 80]

E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/libg/libgd2/libgd3_2.1.1-4ubuntu0.16.04.5_amd64.deb  404  Not Found [IP: 91.189.91.23 80]
```

<img width="841" alt="screen shot 2017-03-15 at 16 23 52" src="https://cloud.githubusercontent.com/assets/3191641/23939481/ced4af4c-099b-11e7-9adc-f761f0255bd1.png">

## Steps to reproduce

*   apt-get install collectd

**Comment by lin-credible** [comment]
I'm trying to update and add option `--fix-missing` : (

**Comment by bzed** [comment]
Doesn't sound like a collectd bug. Running ```apt-get update``` will probably fix that....

**Comment by lin-credible** [comment]
I tried `apt-get update` and I installed the collectd well.   But I can't start collectd

```
~# collectd -C /etc/collectd/collectd.conf
~# echo $?
1
```
I found the reason in `syslog`...

```
collectd[51587]: Looking up "MYSTUPIDHOSTNAME" failed. You have set the "FQDNLookup" option, but I cannot resolve my hostname to a fully qualified domain name. Please fix the network configuration.
```
Then, I changed my hostname to my local IP, and started the collectd successfully.

@bzed Thanks.
