### ISSUE TITLE
"disk" plugin always results in ->`ds->ds_num == vl->values_len' failure

### ISSUE THREAD

**Issue by harisund** [collectd/collectd#2221]
*   Version of collectd: 5.7.1.19.g14d94fb-1~trusty
*   Operating system / distribution: Ubuntu Trusty

## Expected behavior

Not expecting collectd to crash. 

## Actual behavior

Error below.

## Steps to reproduce

Enable the "disk" plugin
Execute "collectd -f"
See this error after a couple of seconds - 

```
option = Hostname; value = IRRELEVANT;

option = FQDNLookup; value = true;

Done parsing `/usr/share/collectd/types.db'

option = Interval; value = 10.000000;

Created new plugin context.

[2017-03-17 18:35:34] plugin_load: plugin "logfile" successfully loaded.

[2017-03-17 18:35:34] type = logfile, key = LogLevel, value = info

collectd: plugin.c:1990: plugin_dispatch_values_internal: Assertion `ds->ds_num == vl->values_len' failed.
Aborted
```

**Comment by rpv-tomsk** [comment]
Could you please show `grep ^disk_ /usr/share/collectd/types.db` output ?

**Comment by harisund** [comment]
@rpv-tomsk 

disk_latency            read:GAUGE:0:U, write:GAUGE:0:U
disk_merged             read:DERIVE:0:U, write:DERIVE:0:U
disk_octets             read:DERIVE:0:U, write:DERIVE:0:U
disk_ops_complex        value:DERIVE:0:U
disk_ops                read:DERIVE:0:U, write:DERIVE:0:U
disk_time               read:DERIVE:0:U, write:DERIVE:0:U
disk_io_time            value:GAUGE:0:U

**Comment by rpv-tomsk** [comment]
The correct line for `disk_io_time` should be:
```
disk_io_time            io_time:DERIVE:0:U, weighted_io_time:DERIVE:0:U
```

**Comment by rpv-tomsk** [comment]
Any comments? If no, may we assume that issue is solved?

**Comment by harisund** [comment]
Thank you, we changed the version but didn't realize the types.db had changed too. Our fault.
