### ISSUE TITLE
flex version 2.6.3 causing problems when building collectd

### ISSUE THREAD

**Issue by johnoloughlin** [collectd/collectd#2224]
*   Version of collectd: 5.7.1
*   Operating system / distribution: Ubuntu 16.04

## Expected behavior
build is successful

## Actual behavior
See logs below:

  LEX      src/liboconfig/scanner.c
  CC       src/liboconfig/scanner.lo
src/liboconfig/scanner.c:416:0: error: "yywrap" redefined [-Werror]
src/liboconfig/scanner.c:73:0: note: this is the location of the previous definition
cc1: all warnings being treated as errors
Makefile:5530: recipe for target 'src/liboconfig/scanner.lo' failed
make[1]: *** [src/liboconfig/scanner.lo] Error 1
make[1]: Leaving directory '/root/dpdk_xstats-collectd'
Makefile:4027: recipe for target 'all' failed
make: *** [all] Error 2

## Steps to reproduce

*   Install flex 2.6.3
*   Install other required dependancies
*   pull collectd
*   ./build.sh
*   ./configure
*   make

## Fix
Revert back to flex 2.6.0

**Comment by octo** [comment]
Hi @johnoloughlin,

Thank you very much for reporting this. As far as I can tell this is caused by a bug in flex, not collectd, though. Could you please send a bug report to the flex team?

Thank you!
—octo

**Comment by johnoloughlin** [comment]
Hi @octo 

It seems that flex have fixed the issue in 2.6.4

— John
