### ISSUE TITLE
Error: collectd is respawning too fast - disabled for 300 seconds

### ISSUE THREAD

**Issue by schoudhary-matterport** [collectd/collectd#2227]
*   Version of collectd:  collectd 5.4.0.git
*   Operating system / distribution:  Ubuntu 14.04

## Expected behavior
I am trying to use datadog collectd plugin to see the collectd metrics on datadog dashboard

## Actual behavior

(Description of the behavior / output that you observed)
this is a part of /var/log/syslog 
Mar 22 21:09:34 st6-metrics-2 collectdmon[19837]: Info: collectd terminated with exit status 0
Mar 22 21:09:34 st6-metrics-2 collectdmon[19837]: Warning: restarting collectd
Mar 22 21:09:45 st6-metrics-2 collectdmon[19837]: Info: collectd terminated with exit status 0
Mar 22 21:09:45 st6-metrics-2 collectdmon[19837]: Warning: restarting collectd
Mar 22 21:09:56 st6-metrics-2 collectdmon[19837]: Info: collectd terminated with exit status 0
Mar 22 21:09:56 st6-metrics-2 collectdmon[19837]: Warning: restarting collectd
Mar 22 21:10:06 st6-metrics-2 collectdmon[19837]: Info: collectd terminated with exit status 0
Mar 22 21:10:06 st6-metrics-2 collectdmon[19837]: Warning: restarting collectd
Mar 22 21:10:17 st6-metrics-2 collectdmon[19837]: Info: collectd terminated with exit status 0
Mar 22 21:10:17 st6-metrics-2 collectdmon[19837]: Error: collectd is respawning too fast - disabled for 300 seconds

## Steps to reproduce

*   step 1 - using https://github.com/truthbk/datadog-collectd-plugin, add dd-collectd.conf in /etc/collectd/collectd.conf.d and add dd-collectd.py in the Module path defined in dd-collectd.conf
*   step 2 - pip install datadog as datadog is being imported by dd-collectd.py
*   step 3 - sudo tail -f /var/log/syslog

**Comment by rubenk** [comment]
Please share your complete configuration.

**Comment by schoudhary-matterport** [comment]
Hi rubenk,

Thanks a lot for reviewing this.
I just heard back from Datadog folks that their integration is broken.
That's why I am facing this issue.
I am closing it now.
