### ISSUE TITLE
Compile error with bind.c

### ISSUE THREAD

**Issue by szechyjs** [collectd/collectd#2228]
*   Version of collectd: 5.7.1
*   Operating system / distribution: RHEL5

## Expected behavior

Compiles successfully

## Actual behavior

```
Error:

    In file included from ./daemon/collectd.h:39:0,
                 from bind.c:38:
/usr/local/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/include-fixed/sys/stat.h:379:16: error: inline function 'mknod' declared but never defined [-Werror]
 __inline__ int mknod (__const char *__path, __mode_t __mode, __dev_t __dev)
                ^
/usr/local/lib/gcc/x86_64-unknown-linux-gnu/4.8.5/include-fixed/sys/stat.h:379:16: error: inline function 'mknod' declared but never defined [-Werror]
cc1: all warnings being treated as errors
gmake[4]: *** [bind_la-bind.lo] Error 1
```

This [SO](http://stackoverflow.com/questions/13120633/how-to-deal-with-warning-inline-function-stat64-declared-but-never-defined) suggests adding `-fgnu89-inline`. I've yet to try that, for now I'm building with `--disable-werror`

**Comment by octo** [comment]
This sounds like a bug in that version of glibc. Disabling `-Werror` is likely the best workaround. Also, it would be great if you could open a bug with the GNU libc team.

Best regards,
—octo

**Comment by octo** [comment]
On second thought, it's suspicious that bind is the first plugin to stumble into this. Could you grep for `STRPTIME_NEEDS_STANDARDS` in `config.h`?

**Comment by szechyjs** [comment]
@octo `config.h` contains

```c
#define STRPTIME_NEEDS_STANDARDS 1
```

**Comment by rubenk** [comment]
I haven't been able to reproduce this with gcc-4.1 that comes with RHEL5. Perhaps this is some interaction between an ancient glibc and a more recent gcc 4.8.

Could you try with the system compiler? Alternatively, use the rpms from https://github.com/collectd/collectd-ci

You're probably aware that RHEL5 is now end of life, as such we won't be able to put much time in this.

**Comment by eero-t** [comment]
> I haven't been able to reproduce this with gcc-4.1 that comes with RHEL5. Perhaps this is some interaction between an ancient glibc and a more recent gcc 4.8.
> 
> You're probably aware that RHEL5 is now end of life, as such we won't be able to put much time in this.

5 years later... As even extended support for RHEL5 ended couple of years ago, I'm closing this.   If this happens on newer distros, please file another bug (referring to this).
