### ISSUE TITLE
Getting always error for collectd logfile plugin: fopen 

### ISSUE THREAD

**Issue by schitransh** [collectd/collectd#2234]
*  collectd 5.7.1:
*   el7.x86_64:

## Expected behavior
it should give error while starting collectd process.

## Actual behavior

whenever i am starting collectd process then it is giving error like 
**
logfile plugin: fopen (/DGdata/chitransh/collectd/collectd/.tmp/var/log/collectd.log) failed: No such file or directory
**
But from collectd conf we have re-point to different location. like
```
LoadPlugin "logfile"
<Plugin "logfile">
  LogLevel "info"
  File "/DGlogs/collectd.log"
  Timestamp true
</Plugin>
```
is that building a issue for collectd? Please help to solve this issue.
But log is also writing in  /DGlogs/collectd.log properly.
but one error also we have observed 
**statvfs(/run/secrets) failed: No such file or directory**

**Comment by rubenk** [comment]
This error is harmless, but I suspect it is fixed by 9cb3abd9449a7f909c3434ec2ff0939939371269.
