### ISSUE TITLE
virt plugin: difference between memory-total and memory-actual_balloon metric

### ISSUE THREAD

**Issue by pszczerx** [collectd/collectd#2237]
Hi,

It seems that the same value is dispatched twice by the plugin - once as _memory-total_ and once as _memory-actual_balloon_. memory-total represents memory used by the domain, which is retrieved from memory member in [virDomainInfo](https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainInfo) structure.  memory-actual_balloon corresponds to [VIR_DOMAIN_MEMORY_STAT_ACTUAL_BALLOON](https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainMemoryStatTags). Based on libvirt documentation is represents:

> Current balloon value

As far as I understand it's exactly the same value. If yes, is there any reason to dispatch the same metric twice? The only difference I found is that VIR_DOMAIN_MEMORY_STAT_ACTUAL_BALLOON was introduced later - in libvirt version 1.3.1.

I'd appreciate if someone could clarify the difference between those metrics for me.

Thanks

**Comment by rubenk** [comment]
You'd have to check the libvirtd source for any differences between the two values. I expect the latter value is only available if the balloon driver is enabled.

**Comment by pszczerx** [comment]
I think that you are right. I glanced at libvirt code for qemu driver and it looks like _virDomainMemoryStats_ API returns memory statistics only if balloon driver is enabled (with exception for RSS):

`if (vm->def->memballoon &&
        vm->def->memballoon->model == VIR_DOMAIN_MEMBALLOON_MODEL_VIRTIO) `

On the other hand, _virDomainGetInfo_ behaves differently as it sets _memory_ member to maximum memory usable by the domain:
> /* if no balloning is available, the current size equals to the current full memory size */

This explains a lot. Given this information I believe it makes sense to dispatch both metrics by the plugin.

Thanks,
Przemek

**Comment by rubenk** [comment]
Right. And now that I think of it libvirt also support containers, where ballooning doesn't work, so in that case it'd make sense too.
