### ISSUE TITLE
[PATCH] -- fixes notifications to nagios's named pipe

### ISSUE THREAD

**Issue by ioannis1** [collectd/collectd#2238]
*   Version of collected: collectd-5.7.0
*   Operating system / distribution: OSX 10.11.6  El Capitan

## Expected behavior

 The <notify_nagios> plugin should be able to notify Nagios via the named pipe designated by Nagios server

## Actual behavior

The <notify_nagios> plugin fails to write to a the named pipe since it assumes it must write to a file

## Steps to reproduce

 
Patch attached.

**Comment by ioannis1** [comment]
This patch was against the latest version of collected available at the time. Was directed to post here since my original email was send to an older collected mailing list.

**Comment by rubenk** [comment]
Please open a pull request with your patch.
