### ISSUE TITLE
collectd-python should give access to data-set information

### ISSUE THREAD

**Issue by LionelCons** [collectd/collectd#2244]
The Python plugins are quite powerful but they miss data-set information.

Therefore it is impossible, from a Python plugin, to convert data to the Collectd JSON format because the  "dstypes" and "dsnames" information is missing.

**Comment by vmytnykx** [comment]
Hi @LionelCons, collectd python plugin has a method to convert value type into dataset "collectd.get_dataset(value-type)". Is it what you are looking for?

**Comment by LionelCons** [comment]
You are right, get_dataset() gives me the information I need. Thanks.

The collectd-python.5 documentation contains:
> Not all aspects of the collectd API are accessible from Python. This includes but is not limited to filters and data sets.

If data sets are indeed fully available, the documentation should be updated accordingly.

**Comment by rubenk** [comment]
Would you be willing to open a Pull Request with a patch for the documentation?

**Comment by LionelCons** [comment]
See https://github.com/collectd/collectd/pull/2253.

**Comment by rubenk** [comment]
Merged as 930fd04795b9dfbee119a3be5787dabef84592e6, thank you @LionelCons.
