### ISSUE TITLE
[new_feature] Get process name from /proc/*/cmdline on Linux

### ISSUE THREAD

**Issue by eighteen14k** [collectd/collectd#2250]
*   Version of collectd: 5.5.3
*   Operating system / distribution: Centos 6

## Expected behavior
When I use the "Processes" plugin, I expect to get the entire process name.

## Actual behavior
Process name is truncated to 15 characters and in some instances, does not represent the "process name" but rather the name of the command run. Processes can change their names...

## Solution
To solve the above problem took a little bit of effort. The idea is as follows:
- Add a new boolean to the config of the Process plugin called "UseProcCmdLine".
- Add a new regex config line called "ProcCmdLineRegex" that is only active if UseProcCmdLine is true

When UseProcCmdLine is set (and there are no ProcCmdLineRegex options present), it causes the Process plugin to copy the first string in /proc/*/cmdline into the process name, overriding the name retrieved earlier. This will mean that instead of collectd thinking that "console-kit-daemon" is called "console-kit-dae", it will see it as "/usr/sbin/console-kit-daemon". That's both good and bad. Good is that you know the full name of the process and that "/usr/sbin/console-kit-daemon" will no longer be confused with "/usr/sbin/console-kit-daeity" :)

To bring the name back to something more useful really requires getting rid of the path at the front. And that may be enough for some, but others might have more interesting command lines. To deal with this situation, I added "ProcCmdLineRegex" that takes two args: (1) is the regex to match a process name with, (2) is how to rewrite the process name. Think of it as something like processname.sub(r(1), r(2)). First match wins.

Putting it together, to get the full name of all processes without the leading path would be like this:
```
UseProcCmdLine true
ProdCmdLineRegex "^([^ ]*].*" "\\1"
ProcCmdLineRegex "^/.*/([^\\/]*)$" "\\1"

```
The double \\ is required because of the quoting present in the config reader. Anyway, back to the above example, this will turn "/usr/sbin/console-kit-daemon" into "console-kit-daemon". Why is the first regex there? Lets come back to that in a minute.

Now why is all that complexity necessary?

The first arg in /proc/*/cmdline can be set from an application, which really means that it is a free text string. Most applications never touch it, but some do. Some will change their name into the instance that they're running, for example, hald. A full "hald" process name might be "hald-addon-input: Listening on /dev/input/event3 /dev/input/event0 /dev/input/event1". That's even less useful than "hald-addon-inpu" and if only the second regex was present, the process name would be "event1" - also not very useful.

In my particular case, applications would rename themselves to something like this:
"<instance> <binary>-<version>"
which is very useful when there are multiple running on one host when you do "ps" and for that, the regex statement to clean that up is:
ProcCmdLineRegex "^([^ ]* [^\\-]*)-.*$" "\\1"
and gives me "<instance> <binary>" in collectd serieses.

The patch is mildly more complex than the one for the "df" plugin and makes me wonder if I should just push the changes I've made back in and request a pull O:_)

Oh, one last thing, processes.c has this little snippet of code:
```
               errno = 0;
               endptr = NULL;
               tmp = strtoll (fields[1], &endptr, /* base = */ 10);
               if ((errno == 0) && (endptr != fields[1]))
```
... there's no need to set errno to 0 or check if it is 0 after strtoll returns. As per the man page for strtoll, the correct way to check if that function call succeeds or fails is to pay attention to how it behaves. (I actually don't think it is possible for strtoll to set errno but what would I know?)

**Comment by eighteen14k** [comment]
Ah, forgot to attach the patch...

[collectd-process.txt](https://github.com/collectd/collectd/files/921952/collectd-process.txt)

**Comment by rubenk** [comment]
Thank you for your contribution. Please open a Pull Request against the master branch, 5.5 is ancient and not supported anymore. Details are in https://github.com/collectd/collectd/blob/master/CONTRIBUTING.md

**Comment by jcdauchy** [comment]
It seems that this enhancement did not make it to master :(

When monitoring java process, this feature is really interesting to gather different java process matching the regexp expression.

**Comment by rpv-tomsk** [comment]
Can you do a PR with enhancement you need?

**Comment by eighteen14k** [comment]
This is the PR with the enhancement required!

________________________________

**Comment by rubenk** [comment]
No this is not a PR, it's an issue. We can't support patches attached to issues. Please read https://github.com/collectd/collectd/blob/master/CONTRIBUTING.md and open a proper pull request.

**Comment by eighteen14k** [comment]
Oh you mean PR = Pull Request, not something else? Why didn't you say so?

________________________________

**Comment by jcdauchy** [comment]
I wish I could contribute, not sure my coding skills would allow it :(

@eighteen14k  Do you think you could merge your modificatione to master or another branch (I am using branch 5.8 on centos).

Thanks

**Comment by rubenk** [comment]
@eighteen14k I did say so in https://github.com/collectd/collectd/issues/2250#issuecomment-294144690

**Comment by eighteen14k** [comment]
I'll have to go back and have a look.

________________________________
