### ISSUE TITLE
Issue while configuring Java plugin (genericJMX) for weblogic 12c  

### ISSUE THREAD

**Issue by mailRavi** [collectd/collectd#2262]
*   Version of collectd: collectd-5.7.1
*   Operating system / distribution: Oracle Linux 7

## Expected behavior

Should connect to the weblogic server and display the heap properties

## Actual behavior

Does not connect to weblogic server, throws an error and does not load java plugin:

 java plugin: cjni_config_load_plugin: FindClass (org/collectd/java/GenericJMX) failed.

 java plugin: Configuration block for `GenericJMX' found, but no such configuration callback has been registered. Please make sure, the `LoadPlugin' lines precede the `Plugin' blocks.

## Steps to reproduce

*  Enable Java plugin after making the below changes to the collectd.conf:, 
	<Plugin java>
		JVMArg "-Djava.class.path=/scratch/gbuora/u00/app/ora_fmw/oracle/Middleware/Oracle_Home/wlserver/server/lib/wljmxclient.jar:/scratch/gbuora/u00/app/ora_fmw/oracle/Middleware/Oracle_Home/wlserver/server/lib/wlclient.jar:/opt/collectd/share/collectd/java/collectd-api.jar:/opt/collectd/share/collectd/java/generic-jmx.jar -Djmx.remote.protocol.provider.pkgs=weblogic.management.remote -Djavax.net.ssl.trustStore=/scratch/gbuora/u00/app/ora_fmw/oracle/Middleware/Oracle_Home/wlserver/server/lib/connectTrust.jks -Djavax.management.builder.initial=weblogic.management.jmx.mbeanserver.WLSMBeanServerBuilder -Djavax.net.ssl.identityStore=/scratch/gbuora/u00/app/ora_fmw/oracle/Middleware/Oracle_Home/wlserver/server/lib/connectIdentity.jks-Djavax.net.ssl.identityStore=/scratch/gbuora/u00/app/ora_fmw/oracle/Middleware/Oracle_Home/wlserver/server/lib/connectIdentity.jks   -Djava.naming.security.principal=weblogic -Djava.naming.security.credentials=welcome123 "
		LoadPlugin "org.collectd.java.GenericJMX"
		<Plugin "GenericJMX">

			<MBean "garbage_collector">
			  ObjectName "java.lang:type=GarbageCollector,*"
			  InstancePrefix "gc-"
			  InstanceFrom "name"

			  <Value>
				Type "invocations"
				Table false
				Attribute "CollectionCount"
			  </Value>

			  <Value>
				Type "total_time_in_ms"
				InstancePrefix "collection_time-"
				Table false
				Attribute "CollectionTime"
			  </Value>
			</MBean>

			<MBean "memory">
			  ObjectName "java.lang:type=Memory"
			  InstancePrefix "memory-"

			  <Value>
				Type "memory"
				Table true
				Attribute "HeapMemoryUsage"
				InstancePrefix "heap-"
			  </Value>

			  <Value>
				Type "memory"
				Table true
				Attribute "NonHeapMemoryUsage"
				InstancePrefix "nonheap-"
			  </Value>
			</MBean>

			<MBean "memory_pool">
			  ObjectName "java.lang:type=MemoryPool,*"
			  InstancePrefix "memory_pool-"
			  InstanceFrom "name"

			  <Value>
				Type "memory"
				Table true
				Attribute "Usage"
			  </Value>
			</MBean>

			<Connection>
			  Host "localhost"
			  ServiceURL "t3://localhost:8001/jndi/weblogic.management.mbeanservers.domainruntime"
			  Collect "memory_pool"
			  Collect "garbage_collector"
			  Collect "memory"
			</Connection>

		</Plugin>
	</Plugin>
* Restart collectd.

**Comment by mailRavi** [comment]
there was an issue with the path, after correcting it, getting the below error:
 java plugin: cjni_create_jvm: JNI_CreateJavaVM failed with status -1.
[2017-05-04 04:23:34] java plugin: cjni_thread_attach: cjni_create_jvm failed.
[2017-05-04 04:23:34] java plugin: Configuration block for `GenericJMX' found, but no such configuration callback has been registered. Please make sure, the `LoadPlugin' lines precede the `Plugin' blocks.
[2017-05-04 04:23:34] java plugin: cjni_init: jvm == NULL
[2017-05-04 04:23:34] Initialization of plugin `java' failed with status -1. Plugin will be unloaded.

**Comment by mailRavi** [comment]
Got this working. There were couple of  issues, 
1. Extra spaces while provilding the jvmargs
2. Paths were incorrect.

**Comment by octo** [comment]
@mailRavi is there anything collectd could have done to make debugging this easier? Maybe a better error message?

**Comment by mailRavi** [comment]
The following things should have been done by the collectd while starting
the service

   1. In The JVMargs, the leading/tailing spaces should be removed
   2. The paths should be scanned  for special characters and  throw a
   meaningful error.

It would be helpful, if we could  have some material (to  start  with) for
accessing weblogic mbean properties.

Thanks
Ravi.

**Comment by manojspring** [comment]
Hi All,
We are facing the below error while loading the java plugin. We removed the leading/tailing spaces from JVMargs. Though we are getting this below exception. Could anyone please help us in fixing this issue.
##Plugin Configuration
<Plugin java>
	JVMArg "-verbose:jni" 
	JVMArg "-Djava.class.path=/usr/share/collectd/java/collectd-api.jar"
</Plugin>

We are getting below error in the logs.
[2017-12-27 20:30:37] [error] java plugin: cjni_init: jvm == NULL
[2017-12-27 20:30:37] [error] Initialization of plugin `java' failed with status                                                                                         -1. Plugin will be unloaded.

Thanks,
Manoj
