### ISSUE TITLE
statvfs(net:[4026532907]) failed: No such file or directory

### ISSUE THREAD

**Issue by dllhlx** [collectd/collectd#2263]
*   Version of collectd: 5.4/5.5
*   Operating system / distribution: centos7

## Expected behavior

df plugin cannot scan some special device such as net[xxxx], Can I  tell the collectd which device  no need to collect info.

**Comment by dllhlx** [comment]
I get a method to solve this problem :
```
Edit configure file as below:
LoadPlugin df
<Plugin df>
    MountPoint "/net/"
    IgnoreSelected true
</Plugin>
```

**Comment by octo** [comment]
Hi @dllhlx,

that's a perfect use case for the `MountPoint` option. On Linux, people often use the file system type to filter out unwanted mount points.

Best regards,
—octo
