### ISSUE TITLE
Wildcard support for sensors plugin?

### ISSUE THREAD

**Issue by simonvanderveldt** [collectd/collectd#2267]
Would it be possible to add wildcard support to the `Sensor` option of the `sensors` plugin?
Currently you have to provide the exact name of the lm_sensor's module and value, which isn't very practical. Being able to use something like `<sensorname>*/fanspeed*` and `<sensorname>*/temperature*` would be a lot nicer.

**Comment by octo** [comment]
You can use regular expressions with the following syntax:

```
Sensor "/^sensorname/"
```

HTH, —octo

**Comment by simonvanderveldt** [comment]
@octo That does indeed work, awesome! Thanks :)
Might be useful to add to the docs? (or is it a generic piece of functionality that I missed when reading the docs?)
