### ISSUE TITLE
Collectd 5.7/EPEL6/x86_64 missing redis

### ISSUE THREAD

**Issue by xyntrix** [collectd/collectd#2271]
*   Version of collectd:
5.7
*   Operating system / distribution:
CentOS 6 x86_64

## Expected behavior
collectd-redis rpm is available at:
https://pkg.ci.collectd.org/rpm/collectd-5.7/epel-6-x86_64/

## Actual behavior
collectd-redis rpm is not available at:
https://pkg.ci.collectd.org/rpm/collectd-5.7/epel-6-x86_64/

It looks like v7 does have the redis rpm:

https://pkg.ci.collectd.org/rpm/collectd-5.7/epel-7-x86_64/
collectd-redis-5.7.1.36.g42b8d75-3.el7.centos.x..> 14-Apr-2017 13:17               18352

CentOS 7 has hiredis 0.12.1 available in epel:
hiredis.x86_64                                                                        0.12.1-1.el7                                                                         

While CentOS 6 has hiredis 0.10.1 available in epel:
hiredis.x86_64                                           0.10.1-3.el6                    

Would there be any compatibility issues preventing collectd-redis rpm from building for CentOS 6?

It would be wonderful if you all could add this to the next pkg-ci build.

Thanks!

**Comment by rubenk** [comment]
Hi

Unfortunately hiredis has been orphaned in EPEL6, and has been removed from the mirrors.

**Comment by xyntrix** [comment]
I get that the EPEL6 Redis package is orpaned, only because no one stepped up to maintain it -- but couldn't the collectd Redis plugin be built against the last release?   

Would it be better to put into the collectd documentation that the collectd Redis module under CentOS6 is no longer supported?

I imagine folks that do want to use that today, are likely going to go grab the hiredis-devel package from epel6 and build against that so I'm just not clear on why we wouldn't go and do what the community is likely already doing..

**Comment by octo** [comment]
Hi @xyntrix,

such distro specific comments don't age well, and we're missing the means to reliably clean up such comments when they become irrelevant.

Best regards,
—octo
