### ISSUE TITLE
curl_json test: "Invalid read of size 4" on FreeBSD

### ISSUE THREAD

**Issue by octo** [collectd/collectd#2282]
*   Version of collectd: *master*
*   Operating system / distribution: *n/a*

## Actual behavior

When CI runs `make check`, the *test_plugin_curl_json* test fails due to a Valgrind error ([example build](https://ci.collectd.org/job/master-build-on-freebsd10-amd64-with-default-toolchain/631/)):

```
==50357== Invalid read of size 4
==50357==    at 0x40C5CF: parse_value (common.c:1024)
==50357==    by 0x402A17: cj_cb_number (curl_json.c:242)
==50357==    by 0x52BFFD9: yajl_do_parse (in /usr/local/lib/libyajl.so.2.1.0)
==50357==    by 0x402B1E: cj_curl_callback (curl_json.c:130)
==50357==    by 0x4021E4: test_setup (curl_json_test.c:58)
==50357==    by 0x4021E4: test_parse (curl_json_test.c:105)
==50357==    by 0x4021E4: main (curl_json_test.c:118)
==50357==  Address 0x800d450 is 0 bytes inside a block of size 3 alloc'd
==50357==    at 0x4C22690: malloc (in /usr/local/lib/valgrind/vgpreload_memcheck-amd64-freebsd.so)
==50357==    by 0x555494F: strdup (in /lib/libc.so.7)
==50357==    by 0x40C5B5: parse_value (common.c:1021)
==50357==    by 0x402A17: cj_cb_number (curl_json.c:242)
==50357==    by 0x52BFFD9: yajl_do_parse (in /usr/local/lib/libyajl.so.2.1.0)
==50357==    by 0x402B1E: cj_curl_callback (curl_json.c:130)
==50357==    by 0x4021E4: test_setup (curl_json_test.c:58)
==50357==    by 0x4021E4: test_parse (curl_json_test.c:105)
==50357==    by 0x4021E4: main (curl_json_test.c:118)
==50357== 
{
   <insert_a_suppression_name_here>
   Memcheck:Addr4
   fun:parse_value
   fun:cj_cb_number
   fun:yajl_do_parse
   fun:cj_curl_callback
   fun:test_setup
   fun:test_parse
   fun:main
}
```

The code at `common.c:1021–1024` is:

```c
  value = strdup(value_orig);
  if (value == NULL)
    return (ENOMEM);
  value_len = strlen(value);
```

My suspicion is that FreeBSD's `strlen()` depends on behavior by the FreeBSD allocator, such as always allocating at least one word (4 bytes), which Valgrind's allocator does not do.

## Steps to reproduce

*   Open https://ci.collectd.org/job/master-build-on-freebsd10-amd64-with-default-toolchain/
*   Under Build Artifacts → collectd-5.7.1… open `test_plugin_curl_json.log`

**Comment by rubenk** [comment]
IIRC we used to suppress this, see 6f8642c6df35a876f2f0bce3557886d45ac41a7a.

**Comment by octo** [comment]
Thanks for the pointer Ruben! The config seems to set the entire call chain, which is of course different for this test. I'll look into suppressing this, too.
