### ISSUE TITLE
plugin amqp can never create an exchange (Publisher)

### ISSUE THREAD

**Issue by mr-f00** [collectd/collectd#2286]
*   Version of collectd: 5.7.1
*   Operating system / distribution: Raspbian (Jessie) Debian / armv71

## Expected behavior

amqp plugin should create a new Exchange on an amqp server when provided the "Exchange" and "ExchangeType" in the "<Publish ...>" config block. 

## Actual behavior

amqp plugin ignores the "ExchangeType" plugin config option in the "<Publish ...>" block and silently never creates an Exchange. Fundamentally the current code prevents "ExchangeType" being specified for the "Publisher" configuration but another part of the code requires both "Exchange" and "ExchangeType" to be specified to create a non-default exchange.

## Steps to reproduce

1.  Configure amqp "Publish" block as follows:

```
LoadPlugin amqp
<Plugin "amqp">
        # send value to AMQP broker
        <Publish "producer">
                Host "pi"
                Port "5672"
                VHost "/"
                User "test"
                Password "test"
                Exchange "collectd.fanout"
                ExchangeType "fanout"
                RoutingKey "collectd"
                Persistent true
                Format JSON
        </Publish>
</Plugin>
```
2. Start collectd and note the following warning on collectd start-up
```
May 16 22:13:15 pi collectd[19553]: amqp plugin: Ignoring unknown configuration option "ExchangeType".

```
3. Note error in amqp server logs (e.g. rabbitmq-server) that a connection attempted to join an exchange which does not exist:
```
=ERROR REPORT==== 16-May-2017::22:13:15 ===
connection <0.2071.0>, channel 1 - soft error:
{amqp_error,not_found,"no exchange 'collectd.fanout' in vhost '/'",
            'basic.publish'}
```
## Possible recommended fix (or work around)

In amqp.c the "ExchangeType" configuration value is only set if the "publish" is set to 0 (indicating a Subscriber config only). Removing this constraint allowed ExchangeType to be set correctly for a Publisher config. Example:
```
<user>@pi:/home/<user>/collectd/collectd-5.7.1/src# diff amqp.c_fixed amqp.c_original
904c904
<     else if ((strcasecmp("ExchangeType", child->key) == 0))
---
>     else if ((strcasecmp("ExchangeType", child->key) == 0) && !publish)
```
Also, in the "camqp_create_exchange" function, the following line silently exits w/o warning if the ExchangeType is not provided. There should probably be some sort of warning.
```
  if (conf->exchange_type == NULL)
    return (0);
```

**Comment by octo** [comment]
Thanks for reporting this issue and your analysis, @mr-f00! The above commit fixes this and will be merged to *master* shortly.

**Comment by mr-f00** [comment]
Your welcome and thank you for the quick response and merge.
