### ISSUE TITLE
python Notification doesn't support Metadata

### ISSUE THREAD

**Issue by maryamtahhan** [collectd/collectd#2297]
Hi 
The python Notification class does not support metadata in the same way as it supports metadata in a Values class.  This pull request addresses this https://github.com/collectd/collectd/pull/2135.

We would need this for integration work with OpenStack Aodh/Vitrage/Congress to be able to send additional information alongside a notification in the same way we do for values.

It would be great to get feedback and input on this Pull Request.

thank you.
Maryam

**Comment by rubenk** [comment]
Did you open this issue by accident? This is not a Pull Request.

**Comment by maryamtahhan** [comment]
This issue? no... I opened this issue to highlight the issue...  the pull request to fix it just happens to be in the body.

**Comment by rubenk** [comment]
Please don't do that. We already get notified on every comment on every Pull Request. Opening extra issues just to highlight the importanceof your PR just increases our workload.

I really appreciate all the work you're doing and trying to upstream it all. The few of us simply can't keep up with the large amount of PRs coming from Intel. We will get to it, eventually, but want to divide our spare time over all issues and PRs equally.

There are some things you can do to speed things up:
First, get the basics right. Spending review time on code style issues is totally avoidable.
The same goes for compiler warnings etc. Please test the code on multiple platforms, run it through scan-build, Coverity etc. And last, we appreciate all the help we can get. Take up some reviews of your own, fix some issues in unrelated areas of Collectd etc.

Thanks for your understanding,

Ruben

**Comment by maryamtahhan** [comment]
fair enough
