### ISSUE TITLE
can't connect to varnish 5.1 using collectd 5.7.1

### ISSUE THREAD

**Issue by Cactusbone** [collectd/collectd#2298]
*   Version of collectd: 5.7.1
*   Operating system / distribution: ubuntu trusty inside docker

I'm getting lots of `varnish plugin: Unable to open connection.` and it never connect to varnish 5.1

You can check the [dockerfile here](https://github.com/F4-Group/docker-varnish/blob/master/Dockerfile). 

I'm not sure what's going wrong.

**Comment by rubenk** [comment]
I'm sorry, but we can't help you debug based on just a docker file.

The first thing to check is if Varnish is actually running. Can you connect to the Varnish port with telnet for example?

**Comment by Cactusbone** [comment]
Yep, i can run varnishstat and varnishlog against it and it's working
normally.

Le jeu. 25 mai 2017 à 13:11, Ruben Kerkhof <notifications@github.com> a
écrit :

**Comment by rubenk** [comment]
> Yep, i can run varnishstat and varnishlog against it and it's working
> normally.

Do these connect over the network? Please try to connect with telnet as I suggested.

**Comment by Cactusbone** [comment]
Which port ? Varnish is serving websites over ports 6080, 6443,6086 and
6449 properly (my configuration)

Le jeu. 25 mai 2017 à 16:57, Ruben Kerkhof <notifications@github.com> a
écrit :

**Comment by rubenk** [comment]
> Yep, i can run varnishstat and varnishlog against it and it's working
> normally.

From inside the container?

> Which port ? Varnish is serving websites over ports 6080, 6443,6086 and
> 6449 properly

 
I assumed collectd talked to varnish over TCP, but I'm not very familiar with Varnish.
Collectd uses the Varnish API, the error returned is here: https://github.com/collectd/collectd/blob/collectd-5.7.1/src/varnish.c#L1013

Any chance you could attach gdb and step through that code to see where the error comes from?

**Comment by rubenk** [comment]
Please also share:
- your collectd.conf, because collectd.conf in that docker image only contains commented out entries
- the way you start your container
- any logs you have

**Comment by Cactusbone** [comment]
Yes, from inside the container for varnishstats and varnishlog. I'll
provide conf and parameters on monday ☺️ any flag I can turn on for logs ?
Because the only log I got was not being able to connect

Le jeu. 25 mai 2017 à 19:00, Ruben Kerkhof <notifications@github.com> a
écrit :

**Comment by Cactusbone** [comment]
logs: 
```logs
[2017-05-24 15:41:51] plugin_load: plugin "logfile" successfully loaded.
[2017-05-24 15:41:51] plugin_load: plugin "write_graphite" successfully loaded.
[2017-05-24 15:41:51] plugin_load: plugin "varnish" successfully loaded.
[2017-05-24 15:41:51] plugin_load: plugin "tcpconns" successfully loaded.
[2017-05-24 15:41:51] varnish plugin: Unable to open connection.
[2017-05-24 15:41:51] Initialization complete, entering read-loop.
[2017-05-24 15:41:51] read-function of plugin `varnish/kro' failed. Will suspend it for 20.000 seconds.
[2017-05-24 15:41:51] tcpconns plugin: Reading from netlink succeeded. Will use the netlink method from now on.
[2017-05-24 15:42:11] varnish plugin: Unable to open connection.
[2017-05-24 15:42:11] read-function of plugin `varnish/kro' failed. Will suspend it for 40.000 seconds.
[2017-05-24 15:42:51] varnish plugin: Unable to open connection.
[2017-05-24 15:42:51] read-function of plugin `varnish/kro' failed. Will suspend it for 80.000 seconds.
[2017-05-24 15:44:11] varnish plugin: Unable to open connection.
[2017-05-24 15:44:11] read-function of plugin `varnish/kro' failed. Will suspend it for 160.000 seconds.
[2017-05-24 15:46:51] varnish plugin: Unable to open connection.
[2017-05-24 15:46:51] read-function of plugin `varnish/kro' failed. Will suspend it for 320.000 seconds.
[2017-05-24 15:52:11] varnish plugin: Unable to open connection.
[2017-05-24 15:52:11] read-function of plugin `varnish/kro' failed. Will suspend it for 640.000 seconds.
[2017-05-24 16:02:51] varnish plugin: Unable to open connection.
[2017-05-24 16:02:51] read-function of plugin `varnish/kro' failed. Will suspend it for 1280.000 seconds.
[2017-05-24 16:24:11] varnish plugin: Unable to open connection.
[2017-05-24 16:24:11] read-function of plugin `varnish/kro' failed. Will suspend it for 2560.000 seconds.
[2017-05-24 17:06:51] varnish plugin: Unable to open connection.
[2017-05-24 17:06:51] read-function of plugin `varnish/kro' failed. Will suspend it for 5120.000 seconds.
[2017-05-24 18:32:11] varnish plugin: Unable to open connection.
[2017-05-24 18:32:11] read-function of plugin `varnish/kro' failed. Will suspend it for 10240.000 seconds.
[2017-05-24 21:22:51] varnish plugin: Unable to open connection.
[2017-05-24 21:22:51] read-function of plugin `varnish/kro' failed. Will suspend it for 20480.000 seconds.
[2017-05-25 03:04:11] varnish plugin: Unable to open connection.
[2017-05-25 03:04:11] read-function of plugin `varnish/kro' failed. Will suspend it for 40960.000 seconds.
[2017-05-25 14:26:51] varnish plugin: Unable to open connection.
[2017-05-25 14:26:51] read-function of plugin `varnish/kro' failed. Will suspend it for 81920.000 seconds.
[2017-05-26 13:12:11] varnish plugin: Unable to open connection.
[2017-05-26 13:12:11] read-function of plugin `varnish/kro' failed. Will suspend it for 86400.000 seconds.
```

collectd.conf with host replaced by <GRAPHITE_HOST>
```conf
LoadPlugin logfile
LoadPlugin write_graphite
LoadPlugin varnish
LoadPlugin tcpconns

Hostname "kro"
FQDNLookup false

<Plugin logfile>
  LogLevel "info"
  File "/var/log/collectd.log"
  Timestamp true
</Plugin>

<Plugin write_graphite>
   <Carbon>
     Host "<GRAPHITE_HOST>"
     Port "2003"
     Prefix "collectd"
     Protocol "tcp"
   </Carbon>
</Plugin>

<Plugin "varnish">
  <Instance kro>
    CollectCache       true
    CollectBackend     true
    CollectBan         true  # Varnish 3 and above
    CollectConnections true
#   CollectDirectorDNS false  # Varnish 3 only
    CollectSHM         true
    CollectESI         true
    CollectFetch       true
    CollectHCB         true
    CollectObjects     true
#   CollectPurge       false # Varnish 2 only
    CollectSession     true
#   CollectSMA         false # Varnish 2 only
    CollectSMS         true
#   CollectSM          false # Varnish 2 only
    CollectStruct      true
    CollectTotals      true
    CollectUptime      true
    CollectVCL         true
    CollectWorkers     true
    CollectVSM         true # Varnish 4 only
  </Instance>
</Plugin>

<Plugin "tcpconns">
  ListeningPorts false
  LocalPort "6080"
  LocalPort "6086"
  LocalPort "6443"
  LocalPort "6449"
</Plugin>
```

**Comment by Cactusbone** [comment]
I'm starting the container with collectd.conf as a volume
with environment variables 
```
CACHE_SIZE=33000960k
VARNISHD_PARAMS=-t 0 -a :6080 -a :6086,PROXY -a :6443 -a :6449,PROXY -p feature=+http2 -p ban_lurker_sleep=0.01 -p workspace_client=1048576 -p workspace_backend=1048576 -p thread_pools=6 -p thread_pool_min=2000 -p thread_pool_max=20000
``

**Comment by rubenk** [comment]
Thank you. This all looks good to me and I'm running out of ideas. The last thing I can think of is that perhaps this is specific for Varnish 5, since it is pretty new and I'm not sure if Collectd has even been tested talking against Varnish 5. Any chance you could try with Varnish 4 to rule that out?

**Comment by Cactusbone** [comment]
We were using varnish 4 without problems before (not in docker though). I'll try that out.
I tried gdb but could not get it to work properly

```
gdb collectd
(gdb) b varnish_read
Function "varnish_read" not defined.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 1 (varnish_read) pending.
(gdb) run -C /etc/collectd.conf
Starting program: /sbin/collectd -C /etc/collectd.conf
During startup program exited normally.
```
what am I missing ?

**Comment by rubenk** [comment]
Missing debug symbols?

**Comment by Cactusbone** [comment]
```
file collectd
collectd: ELF 64-bit LSB  executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=f079945fbbe8fcf5354372c464a19cc4876d997c, not stripped
```
should contains debug symbols. I don't understand the part `During startup program exited normally.` since collectd should be running forever

**Comment by rubenk** [comment]
Perhaps add a -f so it doesn't fork?

**Comment by Cactusbone** [comment]
that was it ! thx ! now to manage to break, I'll post updates

**Comment by Cactusbone** [comment]
It looks like i have the same problem with varnish 4.1.6. Since i know collectd worked with vanirsh 4 before, i'll try to find the latest working version :)

**Comment by Cactusbone** [comment]
I've gone back to varnish 4.0 and collectd 5.5.2 (our previous working configuration, outside docker) and it still won't connect. So it's a docker image related problem. I'll get it working with those versions first and try varnish 5 afterwards.

**Comment by Cactusbone** [comment]
looks like collectd.conf varnish instance name must match the varnish process name (parameter -n )
and defaults for varnish name in docker and out of docker changes. (either the -F parameter, to enable foreground, or maybe the hostname, or something else.)

It could be a good idea to document instance "name" in collectd which must match the process name...
I have no idea why the stats worked but not collectd though, since they use the same api ...

**Comment by Cactusbone** [comment]
I'm setting Hostname in collectd conf, so that might be used as default for varnish connection hostname, but it's not the real container hostname, thus generating a connection mismatch ?

**Comment by Cactusbone** [comment]
anyway, it now works with varnish 5 :)

**Comment by rubenk** [comment]
> I'm setting Hostname in collectd conf, so that might be used as default for varnish connection hostname

No, it uses the Instance name, see https://github.com/collectd/collectd/blob/collectd-5.7.1/src/varnish.c#L996

**Comment by Cactusbone** [comment]
ok :) well anyway, Varnish was using a generated hostname from docker, so the instance name was not matching at all :)

**Comment by rubenk** [comment]
I see. If I read the code correctly you could also use 'localhost' as the Instance name (https://github.com/collectd/collectd/blob/collectd-5.7.1/src/varnish.c#L1165) in which case it doesnt execute line 996 and probably connects to Varnishd's default instance / db whatever.

**Comment by Cactusbone** [comment]
I tried that too, but it dit not connect. neither dit not setting anything by using <Instance>

**Comment by rubenk** [comment]
> It could be a good idea to document instance "name" in collectd which must match the process name...

Well what do you know, it already is documented in collectd.conf(5): https://github.com/collectd/collectd/blob/collectd-5.7.1/src/collectd.conf.pod.

The configuration consists of one or more <Instance Name> blocks. Name is the parameter passed to "varnishd -n". If left empty, it will collectd statistics from the default "varnishd" instance (this should work fine in most cases).

**Comment by Cactusbone** [comment]
Nice ! somehow i always ends up at https://collectd.org/wiki/index.php/Plugin:Varnish when searching for docs :/
Well in that case I'll close the issue. Thanks for all the help !

**Comment by rubenk** [comment]
One thing that could be improved is get a better error message out of that failing VSM_Open call, that would probably have helped too.

**Comment by Cactusbone** [comment]
Maybe, i'm not sure what vsm_diag returns but it seems promising

Le lun. 29 mai 2017 à 19:11, Ruben Kerkhof <notifications@github.com> a
écrit :

**Comment by rubenk** [comment]
In any case, I'm glad you got it working, happy to help!
