### ISSUE TITLE
Start of collectd 5.2.0 log a lot of (minimum one second step) messages

### ISSUE THREAD

**Issue by dhilst** [collectd/collectd#230]
When I start collectd 5.2.0 I got a lot of this messages on log:

```
Jan  4 15:48:24 oracle1 collectd[32250]: rrdtool plugin: rrd_update_r (xxxxxxxxxx.com.br/processes/fork_rate.rrd) failed: xxxxxxxxxxxxxx.com.br/processes/fork_rate.rrd: illegal attempt to update using time 1357321704 when last update time is 1357321704 (minimum one second step)

```

Seems that two submits are running on same second on startup.

How to reproduce:
Compile and install collectd 5.2.0 with rrdtool support.
Enable some log plugin
Enable rrdtool plugin
tail -f /var/log/messages &
Start collect

What I see: A lot of (minimum one second step) messages on log
What I expect: A clen startup.

**Comment by abratnap** [comment]
I am seeing the same issue with collectd 5.5 on linux. Things were working okay for few months. I restarted collectd and since then I am seeing the issue. Is there a fix to this one?

**Comment by rrpolanco** [comment]
I'm also seeing this issue with Collectd 5.4 on Ubuntu 14.04. Is there a temporary workaround?
