### ISSUE TITLE
Collectd SNMP : custom snmp port

### ISSUE THREAD

**Issue by gugansankar** [collectd/collectd#2302]
Version : 
collectd-5.7.1-1.el7.x86_64

OS:
CentOS 7 64bit

Seems there is no option to add custom snmp port in the Host configuration section. Is there any workaround solution for custom snmp port ?.

as far as i am concerned, custom port field is necessary one.

Expected entry:

```
<Host "some.switch.mydomain.org">
  Address "192.168.0.2"
  Version 1
  Community "community_string"
  Collect "std_traffic"
  Interval 120
  Port 1661
</Host>
```

**Comment by rubenk** [comment]
There's currently no support in the code to set a custom port. Why do you feel running snmp on a custom port is necessary?

**Comment by gugansankar** [comment]
as most of the organisation trying to run the service on custom port instead of using it on default one for some security reason.

we've more than 50,000 devices running across world wide. all are running with custom snmp port.

Even all the network monitoring tools does provide custom snmp port add option. Why don't we have this option in collectd+snmp ?. Is there any specific reason ?

**Comment by rubenk** [comment]
Moving SNMPv1 to a different port doesn't offer you any extra security. SNMPv1 still sends community strings in plain text.

My guess is this has never been implemented because nobody ever needed it, and it offers questionable benefits.

I'm not opposed to accepting a patch which adds support for this however.

**Comment by gugansankar** [comment]
Nope, I'm not using SNMP v1 in our organisation. Using only v2 and v3. I just pasted the above configuration from Collectd snmp sample entry docs :) .

its good to have a support for custom port :+1:

**Comment by rubenk** [comment]
Ah ok. Will you be able to send a PR? I'm afraid that otherwise this issue will stay open indefinitely.

**Comment by gugansankar** [comment]
Sorry , I'm not a programmer. Any timeline for this feature ?.

**Comment by rubenk** [comment]
If this is important to you or your organisation, you'll have to learn how to program, or find someone who can. This is open source software, and features are not generally implemented on request, I'm sorry.

**Comment by toni-moreno** [comment]
Hi @gugansankar  , if you would like to test other tools, We have built a snmp collecting tool to get data to put into influxdb database, and you can configure any snmp related configuration per device. You have also a nice web user interface to configure or via REST api if you prefer.

https://github.com/toni-moreno/snmpcollector/wiki/Component:-SNMP-Devices

Feel free to test and give me feedback about your experience.

**Comment by gugansankar** [comment]
Sure thanks, will try this one.

**Comment by rpv-tomsk** [comment]
http://net-snmp.sourceforge.net/dev/agent/structsnmp__session.html

**Comment by rpv-tomsk** [comment]
@gugansankar 

You can specify port in `Address` option.
Example:

```
Address "192.168.0.100:111"
```

**Comment by sbrl** [comment]
I, too, have a use case for this feature. I've got a home server running collectd, and a remote server I'm renting. I've got an ssh tunnel setup to do port forwarding, but I'd like to make homeserver:16161 forward to hostedserver:161 or something instead of setting up a VPN, as I'd like to keep my ssh port-forwarded ports out of the way of the 'privileged' ports to keep things organised.

**Comment by rpv-tomsk** [comment]
@sbrl, please look into last comment before yours.

@rubenk, please close this issue. 
It is obsoleted by merged #2327.

**Comment by sbrl** [comment]
@rpv-tomsk Ah, thanks! And this issue is closed already, I think ([ref](https://github.com/collectd/collectd/issues/2302#event-1118548937))

**Comment by rpv-tomsk** [comment]
Oh, this issue is already closed ;-)
I missed that, sorry ^-)
