### ISSUE TITLE
Documentation or steps to add a new Plugin

### ISSUE THREAD

**Issue by patel-alpesh** [collectd/collectd#2308]
The collectd wiki is not accessible anymore.

I want to modify the KAFKA plugin to add AVRO support. That has dependency on avro-cpp, rdkafka++ and serdes libraries. A couple of these are CPP. Not sure how to go about this

1. How to modify the configure.ac to include the CPP libraries. I see most are C libraries
2. Would collectd compilation work with a mix of C and CPP files?

Any guidance or documentation to go about this?

thanks
alpesh

**Comment by rpv-tomsk** [comment]
>The collectd wiki is not accessible anymore.

What is your problem with Wiki? I see no problems: https://collectd.org/wiki/index.php/Main_Page

**Comment by alpesh-arrcus** [comment]
Hi OCta
Wiki is now accessible. Will look for documentation or recently added plugins for steps to add a new plugin. 

This issue can be closed

Thanks
alpesh
