### ISSUE TITLE
ipmi plugin: ipmi_smi_setup_con failed: Permission denied

### ISSUE THREAD

**Issue by ridhoyp** [collectd/collectd#2312]
*   Version of collectd: collectd-5.7.1-2.el7.x86_64
*   Operating system / distribution: Red Hat Enterprise Linux Server 7.2

## Expected behavior

(Description of the behavior / output that you expected)

## Actual behavior

collectd[12719]: ipmi plugin: ipmi_smi_setup_con failed: Permission denied
collectd[12719]: ipmi plugin: thread_init failed.

## Steps to reproduce

*   yum install -y ipmi
*   service collectd restart
*   service collectd status

![image](https://user-images.githubusercontent.com/28750276/26994488-0e88e9c0-4d92-11e7-9a0d-1ecc5363ee3e.png)

**Comment by rubenk** [comment]
Are you running SELinux in enforcing mode?

**Comment by ridhoyp** [comment]
Hi,

Yea, iam sorry to late update, 

its because the SELinux 

Regards
RidhoYP
