### ISSUE TITLE
rpmbuild rpath problem

### ISSUE THREAD

**Issue by michaelsalmon** [collectd/collectd#2313]
*   Version of collectd:5.7.2
*   Operating system / distribution:centos 6

## Expected behavior

collectd should build

## Actual behavior

check-rpaths complains:

ERROR   0001: file '/usr/bin/collectdctl' contains a standard rpath '/usr/lib64' in [/usr/lib64]
ERROR   0001: file '/usr/bin/collectd-tg' contains a standard rpath '/usr/lib64' in [/usr/lib64]
ERROR   0001: file '/usr/bin/collectd-nagios' contains a standard rpath '/usr/lib64' in [/usr/lib64]

## Steps to reproduce

*   step 1 create simple spec file with make install DESTDIR=%{buildroot}
*   step 2 rpmbuild spec file

I note that on page https://github.com/nmilford/rpm-collectd Nathan recommends turning off check-rpaths when building.

**Comment by rubenk** [comment]
Hi Michael,

If I understand it you are packaging collectd from scratch? In that case you should strip the rpaths in your spec file.

I'm sorry, but I don't think this is a collectd issue.

**Comment by michaelsalmon** [comment]
This was not a problem in 5.7.0 and it is a problem in 5.7.2, at least for those who build rpm's.

I have a workaround now so it doesn't bother me too much but I think that the change should have been included in the release notes.

**Comment by rubenk** [comment]
I can't think of any change between 5.7.0 and 5.7.2 that changed this behaviour. If we changed it, it was not on purpose.

My guess is it has something to do with the libtool script included in the tarball. The tarball is created on Debian, where /usr/lib64 is not in the standard library include path. Fedora / RHEL carry a libtool patch where this directory is added. Running autoreconf -if in your %prep section will update the libtool script to the version from Fedora.

**Comment by rubenk** [comment]
I just checked 5.7.0, the same issue happens there. Not sure why you didn't run into this before.
Perhaps you did build your rpms with mock previously, which doesn't check for rpaths?

**Comment by michaelsalmon** [comment]
I actually built 5.7.0 on a different system and when I tried today it broke the same way.

I'll give auotreconf a try.
