### ISSUE TITLE
ci.collectd.org certificate has expired

### ISSUE THREAD

**Issue by rpv-tomsk** [collectd/collectd#2319]
Please note what ci.collectd.org certificate has expired at 8.06.2017.

**Comment by rubenk** [comment]
cc @mfournier

**Comment by rpv-tomsk** [comment]
My browser complains to expired certificate, and notes what exclude is not possible due to configured HTTP Strict Transport Security (HSTS). 

As result, I'm unable to open CI logs.

Please resolve this issue.

**Comment by rubenk** [comment]
Chrome indeed blocks it. Still works in Firefox.

**Comment by rpv-tomsk** [comment]
No, in my FF (52.2.x) it does not work anymore.

**Comment by rpv-tomsk** [comment]
Thanks for a fix!
