### ISSUE TITLE
ovs_stats / ovs_events "ovs_poll_worker(): poll(): timeout" messages in log

### ISSUE THREAD

**Issue by crab86** [collectd/collectd#2323]
*   Version of collectd: collectd 5.7.1.git (from today 21.06.2017)
*   Operating system / distribution: Ubuntu 16.04.1 LTS

## Expected behavior
Working Plugin without timeout error messages in the log although debug loglevel is set. 

## Actual behavior
Repeating Timeout error messages in debug log of collectd although the ovs_stats and ovs_events are captured correctly. ("ovs_poll_worker(): poll(): timeout")

## Steps to reproduce

*   Install collectd with support for ovs_stats and ovs_events (dependency: libyajl)
*   Configure collectd accordingly:

Interval 60 (globally)
LogLevel debug (logfile plugin)

```
<LoadPlugin ovs_events>
 Interval 60
</LoadPlugin>
<LoadPlugin ovs_stats>
 Interval 60
</LoadPlugin>


<Plugin ovs_events>
#  Port "6640"
#  Address "127.0.0.1"
   Socket "/var/run/openvswitch/db.sock"
#  Interfaces "br0" "veth0"
   SendNotification true
  DispatchValues true
</Plugin>

<Plugin ovs_stats>
#  Port "6640"
#  Address "127.0.0.1"
  Socket "/var/run/openvswitch/db.sock"
#  Bridges "br0" "br_ext"
</Plugin>
```

* ovsdb-server is running with following options:
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root      5900  0.0  0.0  25552  5252 ?        S<   Jun20   0:04 ovsdb-server /etc/openvswitch/conf.db -vconsole:emer -vsyslog:err -vfile:info --remote=punix:/var/run/openvswitch/db.sock --private-key=db:Open_vSwitch,SSL,private_key --certificate=db:Open_vSwitch,SSL,certificate --bootstrap-ca-cert=db:Open_vSwitch,SSL,ca_cert --no-chdir --log-file=/var/log/openvswitch/ovsdb-server.log --pidfile=/var/run/openvswitch/ovsdb-server.pid --detach --monitor

* See the logfile of collectd (e.g. tail -f /opt/collectd/var/log/collectd.log) to see repeatingly:

src/utils_ovs.c:805:ovs_poll_worker(): poll(): timeout

[collectd_ovs.txt](https://github.com/collectd/collectd/files/1091064/collectd_ovs.txt)

**Comment by vmytnykx** [comment]
Hi @crab86,

The "poll(): timeout" message is a debug message and not an error message. Thus, it appears only if you enable log level as a debug. Switching logLevel to lower than debug, will suppress this message.

Thanks and Regards,
Volodymyr

**Comment by crab86** [comment]
hi @vmytnykx,

Thanks for your fast respone :+1: But if its not an error message what does it say then? Timeout appears like a problem for me considering that its permanently reported in the logs. Maybe the message should not be "timeout" ? But that of course depends what the message stands for ... 

BR.
Sebastian

**Comment by rubenk** [comment]
@crab86 poll() timing out is totally normal behaviour. It just means that there's no data available. So nothing to worry about.

**Comment by crab86** [comment]
Ok thanks. Guess i can close it now.
