### ISSUE TITLE
Unable to build on Solaris 10 with redis support.

### ISSUE THREAD

**Issue by rzearreta** [collectd/collectd#2326]
*   Version of collectd: 5.7.2
*   Operating system / distribution: Solaris 10 i386

## Expected behavior

Build succesfully with "redis" and "redis_write" support.

## Actual behavior

Configure error:
write_redis . . . . . no (symbol 'redisCommand' not found)

## Steps to reproduce

The hiredis library is built without error, but using last available binutils and gcc from opencsw.org, the configure script fails setting hiredis support (CFLAGS=-I and LDFLAGS=-L point to hiredis include and library directories, of course).

I'm not sure if this is a hiredis or collectd issue.

Any idea?

**Comment by rubenk** [comment]
What version of hiredis are you using?

Please share your complete config.log.

**Comment by rzearreta** [comment]
Hello, I've tried hiredis 0.13.3 and also current master.

Attached config.log.

[config.log.txt](https://github.com/collectd/collectd/files/1105368/config.log.txt)

Thanks in advance for your interest.

**Comment by rubenk** [comment]
```
configure:24573: result: no
configure:24573: WARNING: hiredis/hiredis.h: accepted by the compiler, rejected by the preprocessor!
configure:24573: WARNING: hiredis/hiredis.h: proceeding with the compiler's result
configure:24573: checking for hiredis/hiredis.h
configure:24573: result: yes
configure:24593: checking for redisCommand in -lhiredis
configure:24618: gcc -o conftest -I/opt/hiredis-0.13.3/include   -L/opt/hiredis-0.13.3/lib  conftest.c -lhiredis   >&5
Undefined			first referenced
 symbol  			    in file
__xnet_connect                      /opt/hiredis-0.13.3/lib/libhiredis.so
__xnet_socket                       /opt/hiredis-0.13.3/lib/libhiredis.so
__xnet_getsockopt                   /opt/hiredis-0.13.3/lib/libhiredis.so
setsockopt                          /opt/hiredis-0.13.3/lib/libhiredis.so
__xnet_getaddrinfo                  /opt/hiredis-0.13.3/lib/libhiredis.so
freeaddrinfo                        /opt/hiredis-0.13.3/lib/libhiredis.so
__xnet_bind                         /opt/hiredis-0.13.3/lib/libhiredis.so
gai_strerror                        /opt/hiredis-0.13.3/lib/libhiredis.so
ld: fatal: Symbol referencing errors. No output written to conftest
configure:24618: $? = 1
```

My guess is you'll need to link libhiredis against libsocket.

**Comment by rzearreta** [comment]
Hello,

linking directly to the libsocket.so library with the flag "-l" worked like a charm.

Thanks a lot.
