### ISSUE TITLE
Python plugin ignores read callback return value

### ISSUE THREAD

**Issue by danielkza** [collectd/collectd#2330]
*   Version of collectd:

5.7

*   Operating system / distribution:

Ubuntu 16.04

## Expected behavior

Explicitly returning a non-zero integer value from a Python read callback should indicate failure, as it would with a C callback.

My use case is a bit peculiar. I'm attempting to monitor Apache Spark. At any given time, there may be zero or more driver programs running in a worker node in different ports, but I do not have an easy way to acquire that list of ports.

Hence, I try all ports in a predefined list. Hence, read callback can fail most of the time if a driver is not running in a given port. I want to be able to signal failure, such that the interval doubling kicks in, without necessarily printing a stack trace.

## Actual behavior

Failure is only signaled if an exception is raised.

## Steps to reproduce

Run the following plugin, and observe how the callback interval never raises, as it would be expected from failures.

```python

import collectd

def read_fail():
    return 1

collectd.register_read(read_fail)
```

**Comment by trenkel** [comment]
Any specific reason why the current implementation of raising an exception doesn't work for you?

**Comment by danielkza** [comment]
Only because it clogs the logs with exception stack traces, and makes it much harder to distinguish between an expected failure and a real problem.

**Comment by trenkel** [comment]
Makes sense. Still, I don't like the idea of a return value. How about a special exception class (collectd.Error or something like that) that you can raise which will never print a stacktrace and just a single log line instead. Would that work for you?

**Comment by danielkza** [comment]
Sure, any way to signal "expected" failure will work just fine.

Em sex, 30 de jun de 2017 18:16, trenkel <notifications@github.com>
escreveu:

**Comment by rpv-tomsk** [comment]
>Still, I don't like the idea of a return value.

Can you please explain to those interested in,  why you don't like the idea of a return value?
That it is not accepted code style in Python, or smth else?

Thanks.

**Comment by rpv-tomsk** [comment]
>Still, I don't like the idea of a return value.

@trenkel,  Can you please explain to those interested in,  why you don't like the idea of a return value?
That it is not accepted code style in Python, or smth else?

Thanks.

**Comment by trenkel** [comment]
Has there ever been a Python function that indicated an error condition by returning a certain value as opposed to throwing an exception? Probably somewhere, but you'd have to search really hard to find it.

**Comment by rpv-tomsk** [comment]
Thanks for explanation, @trenkel !
I got it.

**Comment by octo** [comment]
Does anyone volunteer to implement such a non-stacktrace exception or should I close *working as intended*?

**Comment by rpv-tomsk** [comment]
The non-stacktrace exception was implemented in # 2346.
It was merged, therefore we close this problem.

**Comment by octo** [comment]
@rpv-tomsk awesome, thank you!
