### ISSUE TITLE
Licensing and Documentation (question)

### ISSUE THREAD

**Issue by jerrygb** [collectd/collectd#2332]
*   Version of collectd: 5.5/5.6
*   Operating system / distribution: Ubuntu 16.04

Does collectd have updated documentation with licensing terms (with MIT and GPLv2) and other details? I am specifically interested in collectd core (/src) and plugin architecture, for output plugins such as write_http/write_graphite, etc.

Currently, I am referring to these docs here.
https://collectd.org/wiki/index.php/Plugin_architecture

Could you please point me in the right direction?

Thank you!

**Comment by rubenk** [comment]
Hi!

Not sure what you want to know precisely, but how the code is licensed depends on the plugin.
This is described in https://github.com/collectd/collectd/blob/master/COPYING#L1

**Comment by jerrygb** [comment]
Hi @rubenk,

Thank you for the update. I was referring to the wiki earlier. I believe I had seen the collectd core or daemon to have GPL v2. Maybe I misread it. If the COPYING is the latest update to follow, that is perfect.
