### ISSUE TITLE
Unable to find the collectd-write_prometheus plugin

### ISSUE THREAD

**Issue by nitin02** [collectd/collectd#2335]
I'm using collectd-5.7.1 with the amazon ECS optimized AMI. I'm unable to find collectd-write_prometheus plugin to install from the default package repositories.

Is there any alternative way to install/build the package?

**Comment by rubenk** [comment]
We don't provide packages for Amazon Linux, but you can always install from source or try to build an rpm using https://github.com/collectd/collectd/blob/collectd-5.7.2/contrib/redhat/collectd.spec.
