### ISSUE TITLE
plugins 'smart' and 'filecount' do not support own 'Interval'

### ISSUE THREAD

**Issue by volth** [collectd/collectd#2337]
*   Version of collectd: 5.7.2
*   Operating system / distribution: NixOS 17.09

It would be nice if plugins 'smart' and 'filecount' support own 'Interval' setting.
It is not wise to poll them each 10sec, 'smart' could be recorded daily or even weekly.

**Comment by rpv-tomsk** [comment]
Hi.

```
Options inside a B<LoadPlugin> block can override default settings and
influence the way plugins are loaded, e.g.:

 <LoadPlugin ....>
   Interval 60
 </LoadPlugin>

The following options are valid inside B<LoadPlugin> blocks:
...
=item B<Interval> I<Seconds>

Sets a plugin-specific interval for collecting metrics. This overrides the
global B<Interval> setting. If a plugin provides its own support for specifying
an interval, that setting will take precedence.
```

Does that works for you or not?

**Comment by volth** [comment]
Ah, sorry.
I put it into ```<Plugin>``` instead of ```<LoadPlugin>``` and it worked for few of them who explicitly parse ```Interval```
