### ISSUE TITLE
Fix configure test of https://github.com/collectd/collectd/pull/1649

### ISSUE THREAD

**Issue by dothebart** [collectd/collectd#2342]
hi @maryamtahhan 

As already discussed on https://github.com/collectd/collectd/pull/1649

I've compiled latest collectd on ubuntu 16. 
It had an older version of libdpdk installed:

```
dpkg --list |grep -i DPDK
ii  libdpdk-dev:amd64                   2.2.0-0ubuntu8                                          amd64        Data Plane Development Kit (basic development files)
ii  libdpdk0:amd64                      2.2.0-0ubuntu8                                          amd64        Data Plane Development Kit (runtime libraries)
```

The configure went through without errors, but gave errors then about a missing function `rte_eal_primary_proc_alive`.

Configure which you should check (AC_TRY_COMPILE)  for  that and rule out older versions of the library which its not compatible with.

**Comment by rubenk** [comment]
There's already code in master that should check this:
https://github.com/collectd/collectd/blob/master/configure.ac#L2369. Are you compiling latest master, and if so, could you share your config.log?

**Comment by dothebart** [comment]
hm, I think I was compiling the latest release plus changes to process.c - so if its fixed in git we can close this.
