### ISSUE TITLE
ceph plugin: JSON handler failed with status -1

### ISSUE THREAD

**Issue by f1-outsourcing** [collectd/collectd#2343]
```
collectd.x86_64                  5.7.1-2.el7                 @CentOS7_64-epel
collectd-ceph.x86_64             5.7.1-2.el7                 @CentOS7_64-epel
ceph.x86_64                      1:12.1.0-0.el7              @ceph
ceph-base.x86_64                 1:12.1.0-0.el7              @ceph
ceph-common.x86_64               1:12.1.0-0.el7              @ceph
ceph-mds.x86_64                  1:12.1.0-0.el7              @ceph
ceph-mgr.x86_64                  1:12.1.0-0.el7              @ceph
ceph-mon.x86_64                  1:12.1.0-0.el7              @ceph
ceph-osd.x86_64                  1:12.1.0-0.el7              @ceph
```

```
Jul  4 20:50:37 c01 collectd[26753]: ceph plugin: ds FinisherMonFinisher.completeLatency.avgtime was not properly initialized.
Jul  4 20:50:37 c01 collectd[26753]: last message repeated 125 times
Jul  4 20:50:37 c01 collectd[26753]: ceph plugin: ds FinisherMonFinisher.completeLatency.avgtime was not properly initialized.
Jul  4 20:50:37 c01 collectd[26753]: Available write targets: [none]
Jul  4 20:50:37 c01 collectd[26753]: ceph plugin: JSON handler failed with status -1.
Jul  4 20:50:37 c01 collectd[26753]: Available write targets: [none]
Jul  4 20:50:37 c01 collectd[26753]: Available write targets: [none]
Jul  4 20:50:37 c01 collectd[26753]: ceph plugin: JSON handler failed with status -1.
Jul  4 20:50:37 c01 collectd[26753]: Available write targets: [none]
Jul  4 20:50:37 c01 collectd[26753]: Available write targets: [none]
Jul  4 20:50:37 c01 collectd[26753]: ceph plugin: cconn_handle_event(name=mon.a,i=0,st=4): error 1
Jul  4 20:50:37 c01 collectd[26753]: Available write targets: [none]
Jul  4 20:50:37 c01 collectd[26753]: Available write targets: [none]
Jul  4 20:50:37 c01 collectd[26753]: ceph plugin: cconn_handle_event(name=mon.a,i=0,st=4): error 1
Jul  4 20:50:37 c01 collectd[26753]: Available write targets: [none]
```

## /etc/collectd.d/ceph.conf:

```
LoadPlugin ceph

<Plugin ceph>
#  LongRunAvgLatency false
   ConvertSpecialMetricTypes true

  <Daemon "mon.a">
    SocketPath "/var/run/ceph/ceph-mon.a.asok"
  </Daemon>

</Plugin>
```

**Comment by f1-outsourcing** [comment]
hmmm, I had the network section stored in a file /etc/collectd.d/custom.conf when I moved it back to /etc/collectd.conf I didn't get the write targets errors.

I would assume default behaviour that all configuration files are loaded before any processing of them takes place

**Comment by f1-outsourcing** [comment]
Now I am just left with these


Jul  4 22:45:48 c01 collectd[28174]: ceph plugin: cconn_handle_event(name=osd.3,i=1,st=4): error 1
Jul  4 22:45:58 c01 collectd[28174]: ceph plugin: ds FinisherMonFinisher.completeLatency.avgtime was not properly initialized.
Jul  4 22:45:58 c01 collectd[28174]: ceph plugin: ds FinisherMonFinisher.completeLatency.avgtime was not properly initialized.
Jul  4 22:45:58 c01 collectd[28174]: ceph plugin: JSON handler failed with status -1.
Jul  4 22:45:58 c01 collectd[28174]: ceph plugin: cconn_handle_event(name=mon.a,i=2,st=4): error 1
Jul  4 22:45:58 c01 collectd[28174]: ceph plugin: ds Bluestore.kvFlushLat.avgtime was not properly initialized.
Jul  4 22:45:58 c01 collectd[28174]: ceph plugin: JSON handler failed with status -1.
Jul  4 22:45:58 c01 collectd[28174]: ceph plugin: cconn_handle_event(name=osd.3,i=1,st=4): error 1
Jul  4 22:45:58 c01 collectd[28174]: ceph plugin: JSON handler failed with status -1.
Jul  4 22:45:58 c01 collectd[28174]: ceph plugin: cconn_handle_event(name=mon.a,i=2,st=4): error 1
Jul  4 22:45:58 c01 collectd[28174]: ceph plugin: ds Bluestore.kvFlushLat.avgtime was not properly initialized.
Jul  4 22:45:58 c01 collectd[28174]: ceph plugin: JSON handler failed with status -1.
Jul  4 22:45:58 c01 collectd[28174]: ceph plugin: cconn_handle_event(name=osd.3,i=1,st=4): error 1
Jul  4 22:45:58 c01 collectd[28174]: ceph plugin: ds FinisherPurgeQueue.completeLatency.avgtime was not properly initialized.
Jul  4 22:45:58 c01 collectd[28174]: ceph plugin: JSON handler failed with status -1.
Jul  4 22:45:58 c01 collectd[28174]: ceph plugin: cconn_handle_event(name=mds.a,i=2,st=4): error 1
Jul  4 22:45:58 c01 collectd[28174]: ceph plugin: ds Bluestore.kvFlushLat.avgtime was not properly initialized.
Jul  4 22:45:58 c01 collectd[28174]: ceph plugin: JSON handler failed with status -1.
Jul  4 22:45:58 c01 collectd[28174]: ceph plugin: cconn_handle_event(name=osd.0,i=0,st=4): error 1
Jul  4 22:45:58 c01 collectd[28174]: ceph plugin: ds FinisherPurgeQueue.completeLatency.avgtime was not properly initialized.
Jul  4 22:45:58 c01 collectd[28174]: ceph plugin: JSON handler failed with status -1.
Jul  4 22:45:58 c01 collectd[28174]: ceph plugin: cconn_handle_event(name=mds.a,i=2,st=4): error 1
Jul  4 22:45:58 c01 collectd[28174]: ceph plugin: ds Bluestore.kvFlushLat.avgtime was not properly initialized.
Jul  4 22:45:58 c01 collectd[28174]: ceph plugin: JSON handler failed with status -1.
Jul  4 22:45:58 c01 collectd[28174]: ceph plugin: cconn_handle_event(name=osd.0,i=0,st=4): error 1

**Comment by rubenk** [comment]
Ceph 12.1.0 is the Luminous RC. You might be the first one to use this plugin with that version.
Perhaps the json output changed.

Is there are chance you could try to reproduce this on a Ceph Jewel cluster?

**Comment by f1-outsourcing** [comment]
You can be right about that, I upgraded from Kraken, and I think I did not see to much then.

I also posted something the ceph mailing list. I have an incorrect amount registered of osdBytesUsed. On a test cluster with 994GB used, via collectd I get in influxdb an incorrect 9.3362651136e+10 (93GB) reported and this should be 933GB (or actually 994GB). Cluster.osdBytes is reported correctly 3.3005833027584e+13 (30TB)

1499201873311403849 c01  mon.a    ceph_bytes Cluster.osdBytesAvail                             3.2912470376448e+13
1499201873311399889 c01  mon.a    ceph_bytes Cluster.osdBytesUsed                              9.3362651136e+10
1499201873311396462 c01  mon.a    ceph_bytes Cluster.osdBytes                                  3.3005833027584e+13

**Comment by rubenk** [comment]
Can you open a separate issue to keep track of the incorrect osdBytesUsed?

**Comment by f1-outsourcing** [comment]
I did this, but it is probably related to JSON errors, because now it is even reporting 0. How is it even possible it receives a 0? If there are errors no data should be inserted not? 
I take it you are maintaining the logics no data is better than incorrect data?

**Comment by bh9** [comment]
I get something similar on Jewel: 
```
ceph=10.2.3-0ubuntu0.16.04.2
collectd=5.5.1-1build2

Aug 21 14:21:19 sto-1-2 collectd[3643297]: ceph plugin: JSON handler failed with status -1.
Aug 21 14:21:19 sto-1-2 collectd[3643297]: ceph plugin: cconn_handle_event(name=client.rgw.sto-1-2,i=43,st=4): error 1
Aug 21 14:22:19 sto-1-2 collectd[3643297]: ceph plugin: ds Objecter0x560e195507c0.opActive was not properly initialized.
Aug 21 14:22:19 sto-1-2 collectd[3643297]: ceph plugin: JSON handler failed with status -1.
Aug 21 14:22:19 sto-1-2 collectd[3643297]: ceph plugin: cconn_handle_event(name=client.rgw.sto-1-2,i=37,st=4): error 1
Aug 21 14:23:19 sto-1-2 collectd[3643297]: ceph plugin: ds Objecter0x560e195507c0.opActive was not properly initialized.
```

**Comment by f1-outsourcing** [comment]
Luminous is now LTS available, can someone please address this issue so I can start working on the dashboard?

**Comment by octo** [comment]
CC: @AlexZzz

I think this issue and #2464 might be related.

Reviewing that PR I saw that the callback handling metrics (`node_handler_fetch_data()`) is stateful. That might explain the "avgtime was not properly initialized" errors.

I think having the raw JSON returned by Ceph would be very helpful in tracking this down. Also, complex parsers like the one used by the Ceph plugin really should have a unit test. </wishful_thinking>

**Comment by f1-outsourcing** [comment]
Is working now in the current release
