### ISSUE TITLE
nut plugin: query timeouts on inactive hosts, impacts queries for alive hosts?

### ISSUE THREAD

**Issue by fragtion** [collectd/collectd#2344]
*   Version of collectd: collectd 5.7.1.git
*   Operating system / distribution: Ubuntu 17.04 zesty

## Expected behavior

Better reliability. If a host is down, its timeout should not impact queries of other hosts

## Actual behavior

I am running collectd in a corporate environment, probing multiple user workstations. If some of those workstations are shut down in the evenings, collectd's nut plugin fails for the other hosts too. Data will not be recorded for hosts that are still alive, because some of the other hosts timed out
This also impacts other queries which aren't part of the nut plugin, as a result, causing nulls to be recorded all over the place!

## Steps to reproduce

* Add multiple hosts to nut plugin
* Some of the hosts are inaccessible
* Data for accessible hosts is no longer stored in rrd until the dead hosts come back online

## Possible Solutions

* Multi-threaded querying
* Add configuration option to allow optional pinging of the host before attempting the nut query?
* Shorter timeout (or configurable timeout per UPS host line in the config?) per query
* A possible known workaround that I've somehow missed? Please advise!

**Comment by rpv-tomsk** [comment]
Added an PR about this issue. 

@fragtion, Dimitri, please check.

**Comment by fragtion** [comment]
OK feedback so far

I am still seeing similar issues with graphing unfortunately (most of the UPS's that should be polled are not producing graphs.) But these lines in syslog might explain it perhaps?:

> Jul 10 17:30:37 mail collectd[13308]: The read function "nut/myups" is already registered. Check for duplicate "LoadPlugin" lines in your configuration!
> Jul 10 17:30:37 mail collectd[13308]: nut plugin: UPS name "myups" already used, please choose a different one.
> Jul 10 17:30:37 mail collectd[13308]: The read function "nut/myups" is already registered. Check for duplicate "LoadPlugin" lines in your configuration!
> Jul 10 17:30:37 mail collectd[13308]: nut plugin: UPS name "myups" already used, please choose a different one.
> Jul 10 17:30:37 mail collectd[13308]: The read function "nut/myups" is already registered. Check for duplicate "LoadPlugin" lines in your configuration!
> Jul 10 17:30:37 mail collectd[13308]: nut plugin: UPS name "myups" already used, please choose a different one.
> Jul 10 17:30:37 mail collectd[13308]: The read function "nut/myups" is already registered. Check for duplicate "LoadPlugin" lines in your configuration!
> Jul 10 17:30:37 mail collectd[13308]: nut plugin: UPS name "myups" already used, please choose a different one.
> Jul 10 17:30:37 mail collectd[13308]: The read function "nut/myups" is already registered. Check for duplicate "LoadPlugin" lines in your configuration!
> Jul 10 17:30:37 mail collectd[13308]: nut plugin: UPS name "myups" already used, please choose a different one.
> Jul 10 17:30:37 mail collectd[13308]: The read function "nut/myups" is already registered. Check for duplicate "LoadPlugin" lines in your configuration!
> Jul 10 17:30:37 mail collectd[13308]: nut plugin: UPS name "myups" already used, please choose a different one.
> Jul 10 17:30:37 mail collectd[13308]: The read function "nut/myups" is already registered. Check for duplicate "LoadPlugin" lines in your configuration!
> Jul 10 17:30:37 mail collectd[13308]: nut plugin: UPS name "myups" already used, please choose a different one.
> Jul 10 17:30:37 mail collectd[13308]: The read function "nut/myups" is already registered. Check for duplicate "LoadPlugin" lines in your configuration!
> Jul 10 17:30:37 mail collectd[13308]: nut plugin: UPS name "myups" already used, please choose a different one.
> Jul 10 17:30:37 mail collectd[13308]: The read function "nut/myups" is already registered. Check for duplicate "LoadPlugin" lines in your configuration!
> Jul 10 17:30:37 mail collectd[13308]: nut plugin: UPS name "myups" already used, please choose a different one.
> Jul 10 17:30:37 mail collectd[13308]: The read function "nut/myups" is already registered. Check for duplicate "LoadPlugin" lines in your configuration!
> Jul 10 17:30:37 mail collectd[13308]: nut plugin: UPS name "myups" already used, please choose a different one.
> Jul 10 17:30:37 mail collectd[13308]: The read function "nut/myups" is already registered. Check for duplicate "LoadPlugin" lines in your configuration!
> Jul 10 17:30:37 mail collectd[13308]: nut plugin: UPS name "myups" already used, please choose a different one.
> Jul 10 17:30:37 mail collectd[13308]: The read function "nut/myups" is already registered. Check for duplicate "LoadPlugin" lines in your configuration!
> Jul 10 17:30:37 mail collectd[13308]: nut plugin: UPS name "myups" already used, please choose a different one.
> Jul 10 17:30:37 mail collectd[13308]: The read function "nut/myups" is already registered. Check for duplicate "LoadPlugin" lines in your configuration!
> Jul 10 17:30:37 mail collectd[13308]: nut plugin: UPS name "myups" already used, please choose a different one.
> Jul 10 17:30:37 mail collectd[13308]: The read function "nut/myups" is already registered. Check for duplicate "LoadPlugin" lines in your configuration!
> Jul 10 17:30:37 mail collectd[13308]: nut plugin: UPS name "myups" already used, please choose a different one.
> Jul 10 17:30:37 mail collectd[13308]: The read function "nut/myups" is already registered. Check for duplicate "LoadPlugin" lines in your configuration!
> Jul 10 17:30:37 mail collectd[13308]: nut plugin: UPS name "myups" already used, please choose a different one.
> Jul 10 17:30:37 mail collectd[13310]: The read function "nut/myups" is already registered. Check for duplicate "LoadPlugin" lines in your configuration!
> Jul 10 17:30:37 mail collectd[13310]: nut plugin: UPS name "myups" already used, please choose a different one.
> Jul 10 17:30:37 mail collectd[13310]: The read function "nut/myups" is already registered. Check for duplicate "LoadPlugin" lines in your configuration!
> Jul 10 17:30:37 mail collectd[13310]: nut plugin: UPS name "myups" already used, please choose a different one.
> Jul 10 17:30:37 mail collectd[13310]: The read function "nut/myups" is already registered. Check for duplicate "LoadPlugin" lines in your configuration!
> Jul 10 17:30:37 mail collectd[13310]: nut plugin: UPS name "myups" already used, please choose a different one.
> Jul 10 17:30:37 mail collectd[13310]: The read function "nut/myups" is already registered. Check for duplicate "LoadPlugin" lines in your configuration!
> Jul 10 17:30:37 mail collectd[13310]: nut plugin: UPS name "myups" already used, please choose a different one.
> Jul 10 17:30:37 mail collectd[13310]: The read function "nut/myups" is already registered. Check for duplicate "LoadPlugin" lines in your configuration!
> Jul 10 17:30:37 mail collectd[13310]: nut plugin: UPS name "myups" already used, please choose a different one.
> Jul 10 17:30:37 mail collectd[13310]: The read function "nut/myups" is already registered. Check for duplicate "LoadPlugin" lines in your configuration!
> Jul 10 17:30:37 mail collectd[13310]: nut plugin: UPS name "myups" already used, please choose a different one.
> Jul 10 17:30:37 mail collectd[13310]: The read function "nut/myups" is already registered. Check for duplicate "LoadPlugin" lines in your configuration!
> Jul 10 17:30:37 mail collectd[13310]: nut plugin: UPS name "myups" already used, please choose a different one.
> Jul 10 17:30:37 mail collectd[13310]: The read function "nut/myups" is already registered. Check for duplicate "LoadPlugin" lines in your configuration!
> Jul 10 17:30:37 mail collectd[13310]: nut plugin: UPS name "myups" already used, please choose a different one.
> Jul 10 17:30:37 mail collectd[13310]: The read function "nut/myups" is already registered. Check for duplicate "LoadPlugin" lines in your configuration!
> Jul 10 17:30:37 mail collectd[13310]: nut plugin: UPS name "myups" already used, please choose a different one.
> Jul 10 17:30:37 mail collectd[13310]: The read function "nut/myups" is already registered. Check for duplicate "LoadPlugin" lines in your configuration!
> Jul 10 17:30:37 mail collectd[13310]: nut plugin: UPS name "myups" already used, please choose a different one.
> Jul 10 17:30:37 mail collectd[13310]: The read function "nut/myups" is already registered. Check for duplicate "LoadPlugin" lines in your configuration!
> Jul 10 17:30:37 mail collectd[13310]: nut plugin: UPS name "myups" already used, please choose a different one.
> Jul 10 17:30:37 mail collectd[13310]: The read function "nut/myups" is already registered. Check for duplicate "LoadPlugin" lines in your configuration!
> Jul 10 17:30:37 mail collectd[13310]: nut plugin: UPS name "myups" already used, please choose a different one.
> Jul 10 17:30:37 mail collectd[13310]: The read function "nut/myups" is already registered. Check for duplicate "LoadPlugin" lines in your configuration!
> Jul 10 17:30:37 mail collectd[13310]: nut plugin: UPS name "myups" already used, please choose a different one.
> Jul 10 17:30:37 mail collectd[13310]: The read function "nut/myups" is already registered. Check for duplicate "LoadPlugin" lines in your configuration!
> Jul 10 17:30:37 mail collectd[13310]: nut plugin: UPS name "myups" already used, please choose a different one.
> Jul 10 17:30:37 mail collectd[13310]: The read function "nut/myups" is already registered. Check for duplicate "LoadPlugin" lines in your configuration!
> Jul 10 17:30:37 mail collectd[13310]: nut plugin: UPS name "myups" already used, please choose a different one.
> Jul 10 17:30:37 mail collectd[13310]: nut plugin: nut_read: upscli_list_start (myups) failed: Driver not connected
> Jul 10 17:30:37 mail collectd[13310]: read-function of plugin `nut/myups' failed. Will suspend it for 20.000 seconds.
> Jul 10 17:30:57 mail collectd[13310]: nut plugin: nut_read: upscli_list_start (myups) failed: Driver not connected
> Jul 10 17:30:57 mail collectd[13310]: read-function of plugin `nut/myups' failed. Will suspend it for 40.000 seconds.
> Jul 10 17:31:37 mail collectd[13310]: nut plugin: nut_read: upscli_list_start (myups) failed: Driver not connected
> Jul 10 17:31:37 mail collectd[13310]: read-function of plugin `nut/myups' failed. Will suspend it for 80.000 seconds.
> Jul 10 17:32:57 mail collectd[13310]: nut plugin: nut_read: upscli_list_start (myups) failed: Driver not connected
> Jul 10 17:32:57 mail collectd[13310]: read-function of plugin `nut/myups' failed. Will suspend it for 160.000 seconds.
> Jul 10 17:35:37 mail collectd[13310]: nut plugin: nut_read: upscli_list_start (myups) failed: Driver not connected
> Jul 10 17:35:37 mail collectd[13310]: read-function of plugin `nut/myups' failed. Will suspend it for 320.000 seconds.
> Jul 10 17:40:57 mail collectd[13310]: nut plugin: nut_read: upscli_list_start (myups) failed: Driver not connected
> Jul 10 17:40:57 mail collectd[13310]: read-function of plugin `nut/myups' failed. Will suspend it for 640.000 seconds.
> Jul 10 17:51:37 mail collectd[13310]: nut plugin: nut_read: upscli_list_start (myups) failed: Driver not connected
> Jul 10 17:51:37 mail collectd[13310]: read-function of plugin `nut/myups' failed. Will suspend it for 1280.000 seconds.
> Jul 10 18:12:57 mail collectd[13310]: nut plugin: nut_read: upscli_list_start (myups) failed: Driver not connected
> Jul 10 18:12:57 mail collectd[13310]: read-function of plugin `nut/myups' failed. Will suspend it for 2560.000 seconds.

My config looks as follows:

> <Plugin nut>
>         UPS "myups@pick-old.mycompany.local"
>         UPS "tescom@gateway.mycompany.local"
>         UPS "myups@dimitri.mycompany.local"
>         UPS "myups@reception.mycompany.local"
>         UPS "myups@renesh.mycompany.local"
>         UPS "myups@edmund-lap-w.mycompany.local"
>         UPS "myups@vicky.mycompany.local"
>         UPS "myups@mariette.mycompany.local"
>         UPS "myups@debtors.mycompany.local"
>         UPS "myups@debtors1.mycompany.local"
>         UPS "myups@debtors-spare.mycompany.local"
>         UPS "myups@admin-spare.mycompany.local"
>         UPS "myups@warehouse1.mycompany.local"
>         UPS "myups@warehouse2.mycompany.local"
>         UPS "myups@ssc.mycompany.local"
>         UPS "myups@ssc-admin.mycompany.local"
>         UPS "myups@arms.mycompany.local"
> </Plugin>

Only the first two, UPS "myups@pick-old.mycompany.local", and UPS "tescom@gateway.mycompany.local", are producing graphs

Perhaps it's not working now because all the UPS's have the same name? (Although this wasn't a problem before for graphing, assuming all UPS's were reachable)

It seems unnecessary that each UPS should need a unique name, if the RRD's are stored in folders by hostname.  I decided on the common UPS names as it makes it easier to deploy and maintain

Let me know what you think :)

**Comment by rpv-tomsk** [comment]
Hmm, really. 

Previous version of `nut` plugin does not checks for duplicates.
I was 'impressed' by `openvpn` plugin implementation so added such check into `nut`.

I will update a patch in a minutes.

Thanks for a testing.

**Comment by fragtion** [comment]
Will keep you updated as we go... Really want this to work :)

**Comment by rpv-tomsk** [comment]
The patch is simple

```
diff --git a/src/nut.c b/src/nut.c
index 703f164..589a000 100644
--- a/src/nut.c
+++ b/src/nut.c
@@ -93,7 +93,7 @@ static int nut_add_ups(const char *name) {
     return 1;
   }

-  cb_name = ssnprintf_alloc("nut/%s", ups->upsname);
+  cb_name = ssnprintf_alloc("nut/%s", name);

   status = plugin_register_complex_read(
     /* group = */ "nut",
```

I will amend this change.

**Comment by rpv-tomsk** [comment]
```
<Plugin nut>
         UPS "myups@pick-old.mycompany.local"
         UPS "myups@pick-old.mycompany.local"
</Plugin>
```
Unlike the previous version, it will complain if you have duplicated 'UPS' option value. There was not such check before, but that check is required.

**Comment by fragtion** [comment]
Yes, if the entire line is duplicated then it must be a user error. But same UPS name on different hostname should be possible. Compiling patch now, let's see :)

**Comment by rpv-tomsk** [comment]
I have changed error message / output too.
```
--- a/src/nut.c
+++ b/src/nut.c
@@ -107,9 +107,9 @@ static int nut_add_ups(const char *name) {
   sfree(cb_name);

   if (status == EINVAL) {
-    WARNING("nut plugin: UPS name \"%s\" already used, "
-            "please choose a different one.",
-            ups->upsname);
+    WARNING("nut plugin: UPS \"%s\" already added. "
+            "Please check your configuration.",
+            name);
     return -1;
   }
```

**Comment by rpv-tomsk** [comment]
>For the one that's reporting "[error: Driver not connected]" - Does the suspended time have to increase by so much each time? Now that we are doing multi-threaded polling, it might be better to silently ignore the failure and just keep trying every interval, so that as soon as the UPS is back online, there is no missed data because of the lengthy suspension.... Also, maybe it's this "suspension" on "myups" which is blocking all the other lines from polling?

>Does the suspended time have to increase by so much each time?

Yes, there is internal Collectd implementation of this feature. Please read docs about `MaxReadInterval` option.

> Also, maybe it's this "suspension" on "myups" which is blocking all the other lines from polling?

All 'lines' (`UPS` options) are independent of each other.

**Comment by fragtion** [comment]
```
Jul 11 11:35:18 mail collectd[28445]: plugin_load: plugin "nut" successfully loaded.
Jul 11 11:35:18 mail collectd[28445]: nut plugin: Connection to (pick-old.rapalasa.local, 3493) established.
Jul 11 11:35:18 mail collectd[28445]: nut plugin: Connection is unsecured (no SSL).
Jul 11 11:35:18 mail collectd[28445]: nut plugin: nut_read: upscli_list_start (myups) failed: Driver not connected
Jul 11 11:35:18 mail collectd[28445]: read-function of plugin `nut/myups@pick-old.rapalasa.local' failed. Will suspend it for 20.000 seconds.
Jul 11 11:35:18 mail collectd[28445]: nut plugin: Connection to (gateway.rapalasa.local, 3493) established.
Jul 11 11:35:18 mail collectd[28445]: nut plugin: Connection is unsecured (no SSL).
Jul 11 11:35:18 mail collectd[28445]: nut plugin: Connection to (dimitri.rapalasa.local, 3493) established.
Jul 11 11:35:18 mail collectd[28445]: nut plugin: Connection is unsecured (no SSL).
Jul 11 11:35:18 mail collectd[28445]: nut plugin: Connection to (renesh.rapalasa.local, 3493) established.
Jul 11 11:35:18 mail collectd[28445]: nut plugin: Connection is unsecured (no SSL).
Jul 11 11:35:18 mail collectd[28445]: nut plugin: Connection to (reception.rapalasa.local, 3493) established.
Jul 11 11:35:18 mail collectd[28445]: nut plugin: Connection is unsecured (no SSL).
Jul 11 11:35:18 mail collectd[28445]: nut plugin: Connection to (vicky.rapalasa.local, 3493) established.
Jul 11 11:35:18 mail collectd[28445]: nut plugin: Connection is unsecured (no SSL).
Jul 11 11:35:18 mail collectd[28445]: nut plugin: Connection to (mariette.rapalasa.local, 3493) established.
Jul 11 11:35:18 mail collectd[28445]: nut plugin: Connection is unsecured (no SSL).
Jul 11 11:35:18 mail collectd[28445]: nut plugin: Connection to (edmund-lap-w.rapalasa.local, 3493) established.
Jul 11 11:35:18 mail collectd[28445]: nut plugin: Connection is unsecured (no SSL).
Jul 11 11:35:18 mail collectd[28445]: nut plugin: Connection to (debtors.rapalasa.local, 3493) established.
Jul 11 11:35:18 mail collectd[28445]: nut plugin: Connection is unsecured (no SSL).
Jul 11 11:35:18 mail collectd[28445]: nut plugin: Connection to (debtors1.rapalasa.local, 3493) established.
Jul 11 11:35:18 mail collectd[28445]: nut plugin: Connection is unsecured (no SSL).
Jul 11 11:35:18 mail collectd[28445]: nut plugin: Connection to (debtors-spare.rapalasa.local, 3493) established.
Jul 11 11:35:18 mail collectd[28445]: nut plugin: Connection is unsecured (no SSL).
Jul 11 11:35:18 mail collectd[28445]: nut plugin: Connection to (admin-spare.rapalasa.local, 3493) established.
Jul 11 11:35:18 mail collectd[28445]: nut plugin: Connection is unsecured (no SSL).
Jul 11 11:35:18 mail collectd[28445]: nut plugin: Connection to (warehouse1.rapalasa.local, 3493) established.
Jul 11 11:35:18 mail collectd[28445]: nut plugin: Connection is unsecured (no SSL).
Jul 11 11:35:18 mail collectd[28445]: nut plugin: Connection to (warehouse2.rapalasa.local, 3493) established.
Jul 11 11:35:18 mail collectd[28445]: nut plugin: Connection is unsecured (no SSL).
Jul 11 11:35:18 mail collectd[28445]: nut plugin: Connection to (ssc-admin.rapalasa.local, 3493) established.
Jul 11 11:35:18 mail collectd[28445]: nut plugin: Connection is unsecured (no SSL).
Jul 11 11:35:18 mail collectd[28445]: nut plugin: Connection to (ssc.rapalasa.local, 3493) established.
Jul 11 11:35:18 mail collectd[28445]: nut plugin: Connection is unsecured (no SSL).
Jul 11 11:35:18 mail collectd[28445]: nut plugin: Connection to (arms.rapalasa.local, 3493) established.
Jul 11 11:35:18 mail collectd[28445]: nut plugin: Connection is unsecured (no SSL).
Jul 11 11:35:38 mail collectd[28445]: nut plugin: Connection to (pick-old.rapalasa.local, 3493) established.
Jul 11 11:35:38 mail collectd[28445]: nut plugin: Connection is unsecured (no SSL).
Jul 11 11:35:38 mail collectd[28445]: nut plugin: nut_read: upscli_list_start (myups) failed: Driver not connected
Jul 11 11:35:38 mail collectd[28445]: read-function of plugin `nut/myups@pick-old.rapalasa.local' failed. Will suspend it for 40.000 seconds.
Jul 11 11:36:18 mail collectd[28445]: nut plugin: Connection to (pick-old.rapalasa.local, 3493) established.
Jul 11 11:36:18 mail collectd[28445]: nut plugin: Connection is unsecured (no SSL).
Jul 11 11:36:18 mail collectd[28445]: nut plugin: nut_read: upscli_list_start (myups) failed: Driver not connected
Jul 11 11:36:18 mail collectd[28445]: read-function of plugin `nut/myups@pick-old.rapalasa.local' failed. Will suspend it for 80.000 seconds.
```

Looking way more promising so far! Now to see if the data saves for all hosts as expected throughout (in which case we can call this a success!). I will RTFM on "MaxReadInterval" in the meanwhile and do some testing on "ConnectTimeout" variable shortly

**Comment by fragtion** [comment]
Update:
1) The multithreaded polling is working great.
2) ConnectTimeout is seemingly working too, albeit with some issues:
2.a) Typo:
Line 54 of 	5fe8ee6:
`+                                    "TIMEOUT"};`
Should probably be:
`+                                    "CONNECTTIMEOUT"};`

I compiled as above, and notice the following:
2.b) Value for ConnectTimeout is being interpreted in milliseconds:
```
<Plugin nut>
        ConnectTimeout 25000
        UPS "myups@dead.host.com"
</Plugin>
```
Results in:
```
Jul 11 13:45:44 mail collectd[494]: nut plugin: nut_connect: upscli_connect (dead.host.com, 3493) failed: Unknown error
Jul 11 13:45:44 mail collectd[494]: read-function of plugin `nut/myups@dead.host.com' failed. Will suspend it for 20.000 seconds.
Jul 11 13:45:44 mail collectd[494]: plugin_read_thread: read-function of the `nut/myups@dead.host.com' plugin took 25.022 seconds, which is above its read interval (20.000 seconds). You might want to adjust the `Interval' or `ReadThreads' settings.
```
This might explain why ConnectTimeout values lower than about 600 result in strange error even for alive hosts with working upsd:  "nut plugin: nut_connect: upscli_connect (hostname, 3493) failed: Unknown error"...

That said, I wonder if the timeout option is even necessary now, given that the multithreaded scanning has essentially solved the underlying problem completely!

**Comment by rpv-tomsk** [comment]
>2.a) Typo:
>Line 54 of 5fe8ee6: + "TIMEOUT"};
>Should probably be:  "CONNECTTIMEOUT"};

Thanks. Yes, that option firstly was named as Timeout, but it does not affect 'read timeout', so it was renamed.

**Comment by rpv-tomsk** [comment]
>2.b) Value for ConnectTimeout is being interpreted in milliseconds:

Yes, and that was stated in documentation patch:

```
--- a/src/collectd.conf.pod
+++ b/src/collectd.conf.pod
@@ -5291,6 +5291,11 @@ generate links like the one described above for ALL certs in a given folder.
 Example usage:
 C<c_rehash /path/to/certs/folder>

+=item B<ConnectTimeout> I<Milliseconds>
+
+The B<ConnectTimeout> option sets the connect timeout, in milliseconds.
+By default, the configured B<Interval> is used to set the timeout.
+
 =back

 =head2 Plugin C<olsrd>
```

>That said, I wonder if the timeout option is even necessary now, given that the multithreaded scanning has essentially solved the underlying problem completely!

There is a default value of connect timeout anyway, so an option was added as possibility to tune it. )

**Comment by rpv-tomsk** [comment]
>This might explain why ConnectTimeout values lower than about 600 result in strange error even for alive hosts with working upsd: "nut plugin: nut_connect: upscli_connect (hostname, 3493) failed: Unknown error"...

"The case of the 500-mile email" - https://www.ibiblio.org/harris/500milemail.html
