### ISSUE TITLE
Disk Plugin stop working when python plugin is loaded with Interactive equals to true.

### ISSUE THREAD

**Issue by nunodio** [collectd/collectd#2350]
*   Version of collectd: 5.5.1
*   Operating system / distribution: Ubuntu 16.04.2 LTS

## Expected behavior
- Disk Plugin work normally.
- Custom Python Plugin work normally.

## Actual behavior
- Custom Python plugin works correctly.
- CPU, Load, etc Plugins works correctly.

- **Disk plugin stops working**.

## Steps to reproduce

*   Configure collectd.conf to Load Disk plugin and Python plugin
*   Set **Interactive** to **true**   in Python Plugin configuration.
```
<Plugin python>
        ModulePath "/usr/lib/collectd/python"
        LogTraces true
        Interactive true
        Import "your_python_plugin"

        <Module your_python_plugin>
         #     plugin configurations ....
        </Module>
</Plugin>
```

**Comment by rubenk** [comment]
Can you reproduce this on latest master? 5.5 is rather old by now.

**Comment by nunodio** [comment]
Updated to Collectd **5.7.2.6.g02a2996**. Now, with **Interactive true** none of the plugins works. When changing it to **Interactive false** everything works correctly.
No errors detected in the log file with Log Level=info.

**Comment by rubenk** [comment]
Please share you complete configuration and your plugin code.

**Comment by rpv-tomsk** [comment]
As I understand, `Interactive true` is special option and should not be used in common cases.
So, just do not touch it untill you really know what are you doing.

Feel free to (re)open if needed.
Thanks for using Collectd.
