### ISSUE TITLE
collectd[xxxx]: statvfs(/var/lib/elasticsearch/data) failed: Permission denied

### ISSUE THREAD

**Issue by elkuser2017** [collectd/collectd#2359]
*   Version of collectd:  collectd-5.7.0
*   Operating system / distribution: linux redhat el7/x86_64 64bit

## Expected behavior

I want to monitor the free disk space of my filesystems with the collectd df plugin

## Actual behavior

I have "Permission denied" errors in the runtime logs of collecd for some filesystems.

cat /var/log/collectd/collectd.log: 

```
Jul 11 10:45:12 servername collectd[10600]: statvfs(/run/user/102) failed: Permission denied
Jul 11 16:01:49 servername collectd[31694]: statvfs(/var/lib/elasticsearch/data) failed: Permission denied

```
collectd is runing with user root : 

```
[root@servername ~]# ps -ef | grep collectd
root     31694     1  0 16:01 ?        00:00:00 /usr/sbin/collectd
root     31752 31301  0 16:02 pts/0    00:00:00 grep --color=auto collectd
```

Here are the rights of the directories for which I meet the problem: 

```
[root@servername ~]# ls -lrt /var/lib/elasticsearch/
total 4
drwxr-x--- 3 elasticsearch elasticsearch 4096 Jun 22 11:00 data 

[root@servername ~]# ls -lrt /run/user/
total 0
drwx------ 2 root      root   40 Jun  6 00:00 0
drwx------ 2 admsrv    admsrv 40 Jul 11 15:38 102 

```
Extract of my collectd.conf : 
```
# df
<LoadPlugin df>
  Interval 300
</LoadPlugin>
<Plugin df>
  IgnoreSelected true # monitor all partitions
  ValuesPercentage true
</Plugin>
```

I do not understand the error, knowing that collecd is executed with the root user who have all permissions.

Is it a known problem?  How can I fix it?

Thinks for help.

**Comment by rubenk** [comment]
Please check your audit log for SELinux denials.

**Comment by elkuser2017** [comment]
SELinux is not used : 
```
[root@servername ~]# sestatus -v
SELinux status:              disabled

```

**Comment by rubenk** [comment]
can you paste the output of `systemctl cat collectd.service` here?

**Comment by elkuser2017** [comment]
systemctl cat collectd.service : 

```
[root@servername ~]# systemctl cat collectd.service
# /usr/lib/systemd/system/collectd.service
[Unit]
Description=Collectd statistics daemon
Documentation=man:collectd(1) man:collectd.conf(5)
After=local-fs.target network-online.target
Requires=local-fs.target network-online.target

[Service]
ExecStart=/usr/sbin/collectd
EnvironmentFile=-/etc/sysconfig/collectd
EnvironmentFile=-/etc/default/collectd
ProtectSystem=full
ProtectHome=true

# A few plugins won't work without some privileges, which you'll have to
# specify using the CapabilityBoundingSet directive below.
#
# Here's a (incomplete) list of the plugins known capability requirements:
#   ceph            CAP_DAC_OVERRIDE
#   dns             CAP_NET_RAW
#   exec            CAP_SETUID CAP_SETGID
#   iptables        CAP_NET_ADMIN
#   ping            CAP_NET_RAW
#   turbostat       CAP_SYS_RAWIO
#
# Example, if you use the iptables plugin alongside the dns or ping plugin:
#CapabilityBoundingSet=CAP_NET_RAW CAP_NET_ADMIN
#
# By default, drop all capabilities:
CapabilityBoundingSet=

NoNewPrivileges=true

# Tell systemd it will receive a notification from collectd over it's control
# socket once the daemon is ready. See systemd.service(5) for more details.
Type=notify

# Restart the collectd daemon when it fails.
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

**Comment by rubenk** [comment]
My guess it's either ProtectHome, ProtectSystem or CapabilityBoundingSet that causes trouble.

**Comment by elkuser2017** [comment]
Hello, 

The problem is resolved using :
CapabilityBoundingSet= CAP_DAC_OVERRIDE  
in file  /usr/lib/systemd/system/collectd.service

Thanks for your help.

**Comment by winmillwill** [comment]
This still begs the question: why does the df plugin need more than read-only access to the directories mounted read-only by ProtectHome, and what's the point of recommending that if CAP_DAC_OVERRIDE is the fix?

Also, in my case collectd actually gave me way too much data: it gave me df metrics for every child of `/`, which is a big problem for us since we use df fleet-wide and our metrics service provider charges us by data points per minute.

**Comment by faxm0dem** [comment]
@winmillwill you can list the filesystems you want to monitor by using `IgnoreSelected false`

**Comment by winmillwill** [comment]
@faxm0dem  That's not the point: df thinks all of these are different mountpoints:

* bin
* boot
* lib
* lib64
* sbin
* usr

...and they're not, they're all just normal directories in the fs on the root partition.

**Comment by winmillwill** [comment]
Ok, duh, I clarified this myself -- collectd looks at `/etc/mtab/` which is a link to `/proc/self/mounts`, and the `Protect*` directives make the protected things appear as mounts and only show those things. This isn't a collectd bug, it's just that `ProtectSystem` is a dumb recommendation when the df plugin is involved.
