### ISSUE TITLE
Python plugin not working in CentOS 7

### ISSUE THREAD

**Issue by shayanh** [collectd/collectd#2367]
*   Version of collectd: 5.7.1
*   Operating system / distribution: Linux / CentOS

## Expected behavior

I want to import my Python modules like [this](https://collectd.org/documentation/manpages/collectd-python.5.shtml).

## Actual behavior

But I see this error message every time:

```
Jul 17 23:43:01 collectd[7281]: Unhandled python exception in importing module: ImportError: No module named ceph_pool_plugin
Jul 17 23:43:01 collectd[7281]: python plugin: Found a configuration for the "ceph_pool_plugin" plugin, but the plugin isn't loaded or didn't register a configuration callback.
```

## Steps to reproduce

Here is my Python plugin config:

```
<Plugin python>
    ModulePath "/home/admin/collectd/plugins/"
    Import "ceph_pool_plugin"
    <Module ceph_pool_plugin>
        Verbose "True"
        Cluster "ceph"
        Interval "60"
    </Module>
</Plugin>
```

**Comment by rubenk** [comment]
Please share the plugin code itself.

**Comment by shayanh** [comment]
https://github.com/rochaporto/collectd-ceph/tree/master/plugins

**Comment by shayanh** [comment]
I have the same problem with any other Python script.

**Comment by shayanh** [comment]
I found it was SELinux problem that collectd can't read python files.
I'll close this issue.
