### ISSUE TITLE
Plugins are loaded automatically when the plugin is installed

### ISSUE THREAD

**Issue by sradco** [collectd/collectd#2368]
*   Version of collectd: 5.7.2
*   Operating system / distribution: linux

## Expected behavior
When installing a collectd plugin it should not automatically add a Loadplugin file to /etc/collectd/config.d directory.
The user should be the one that controls what plugins to load, even if he installs the plugin.

## Actual behavior
Some plugins add a Loadplugin file when they are installed.
Example: postgres, virt.

## Steps to reproduce

*   Install collectd and collectd postgresql plugin
*   Check the /etc/collectd/config.d directory

**Comment by rpv-tomsk** [comment]
That is not an issue of Collect project, but a issue of distributive packaging .

**Comment by rubenk** [comment]
And even the Fedora EPEL packages don't use /etc/collectd/config.d.
