### ISSUE TITLE
Adding metadata support to the GRPC plugin

### ISSUE THREAD

**Issue by cramertj** [collectd/collectd#2370]
I'm interested in adding support for writing metric metadata to the existing GRPC plugin. I discussed this privately with @tokkee, and they were concerned about adding the ability to specify metadata externally because metadata was originally intended for in-proc data. Is this a design constraint that collectd's maintainers want to enforce, or would you all be interested in adding support for writing metadata through plugins?

Implementation wise, this should be relatively simple-- I believe all that is required is to modify the existing `ValueList` GRPC proto definition to include metadata, and to modify [marshal_value_list and unmarshal_value_list](https://github.com/collectd/collectd/blob/27d117edf8dd7ae0b0f85772361f3df7ac933ae6/src/grpc.cc#L200) so that they copy metadata from the `value_list_t` to the `collectd::types::ValueList` and vice versa.

**Comment by octo** [comment]
Hi @cramertj,

thank you for reaching out, it's very useful to clear such questions prior to spending time on an implementation. There is precedence for exporting the meta data, e.g. the *Write Riemann* and *Write TSDB* plugins, so I'd be happy to accept such a PR.

Best regards,
—octo

**Comment by cramertj** [comment]
Great! I'll be sure to take a look at those plugins when I implement this.
