### ISSUE TITLE
Get data pull-style

### ISSUE THREAD

**Issue by volth** [collectd/collectd#2372]
All collectd data distribution (```Network``` and ```Write*``` plugins) use push-model.

Is there a way to get data in pull-style?

Something like ```tail -f``` over a socket, which would print all the data for say, last hour (or starting from any custom timepoint) from RRD, then not-yet-flushed data, and then the current data as it appears.

The advantages are:
1. No need to flush RRD, ever.
2. Realtime-graphs using websockets or something like them. Without flush.
3. The data sent to master would not lost on connection failures (as the connection reestablished, the master just ```tail``` from the last timepoint it has or from the beginning if it has nothing). So one collectd instance could have a precise real-time mirror of whole RRD history of a value from another.
4. It is a convenient way to feed the data to load balancers which need to know not only the current value but also some history to make better decisions about backend's health.

**Comment by rubenk** [comment]
Have you looked at the unixsock plugin (https://collectd.org/documentation/manpages/collectd-unixsock.5.shtml)?

**Comment by volth** [comment]
Yes.
It has only ```GETVAL``` to get the current value. My text in some sense is a comparison with ```unixsock``` protocol (and it has the word "unixsock" in the draft), wondering why it has no history queries which would be so useful.

```FLUSH``` + read RRD (or csv) from the disk is the closest (but inefficient) idea

**Comment by rubenk** [comment]
Well, collectd itself doesn't store data, so in that sense there's no way to get historical data out of it without pulling it out of the datastore of one of the write plugins.

**Comment by volth** [comment]
The idea is have access to the not-yet-flushed data (and it would be super-nice if the access method hides the internal details between flushed data, not-yet-flushed data and the current value).

The not-yet-flushed data is definitively resides only in collecd's memory.
Access to the historical data could be provided by additional functions of the plugins which do store the data (```rrdtool``` and ```csv```)

**Comment by rubenk** [comment]
Why don't you send your data to Graphite / Grafana? Those tools are better equipped for you use case.

**Comment by volth** [comment]
No, it is push model with all its problems

1. It would lose the data on network interruptions.
2. It would require a separated machine, which is SPOF and it would route unnecessary data (for example a load balancer could "tail" only interesting values of backend telemetry, this should not go through a centralized storage, actually should not be stored at all)
3. It lacks history before the moment a value has been choosed to be sent to graphite

**Comment by rubenk** [comment]
Most of these can be mitigated or worked around. Graphite can be clustered, you can use TCP so it retransmits in case of packet loss etc.

But to get back to your original question if there's a way to pull data out of Collectd: I'm afraid I can't think of one that would satisfy your requirements.

**Comment by volth** [comment]
Yes, it is about how to add a new feature in a better way.
I need the pull-style only for mirroring of rrd (closer to the consumer, e.g. from a backend to a load balancer), but others may leverage this for a nice hipster frontend or to mitigate flushes or ...

**Comment by rubenk** [comment]
Are you planning to implement such a feature?

**Comment by volth** [comment]
Maybe

**Comment by rpv-tomsk** [comment]
>Something like tail -f over a socket, which would print all the data for say, last hour (or starting from any 
>custom timepoint) from RRD, then not-yet-flushed data, and then the current data as it appears.

You can use `rrdtool` plugins as a basis for your work.
There is a cache implementation in `rrdtool`, which you need to store the data inside of running process (inside of your plugin).
Your new plugin will have own independent copy of data, and should expire it (remove from own cache) yourself.

From other side, you can implement the same in `network` plugin, and also implement TCP connection between Collectd instances. That would be amazing.

**Comment by volth** [comment]
I made a plugin based on ```csv``` plugin and [cantal](https://github.com/tailhook/cantal)

It provides access to the history via HTTP and subscription to the update stream via Websocket but it is not in production-quality yet, there are too many things left to improve (configuration options, richer query language, compress/aggregate/delete old log files, etc)

The code is here https://github.com/volth/collectd/commits/websockets

**Comment by octo** [comment]
Hi @volth, thanks for your work! Please feel free to create a *pull request* so we have a good place to discuss required changes – even if the code is not ready to be merged just yet (just add a "[WiP]" marker in the title.

Best regards,
—octo

**Comment by volth** [comment]
The code is still changing a lot for the reasons irrelevant to ```collecd``` (but relevant to, for example, specific features of the data visualization js-libraries which fetch the data), I will make a PR in few days, as it becomes more stable.

**Comment by octo** [comment]
There's nothing left to do here except wait for the PR, and we don't need to track that.
