### ISSUE TITLE
memcached: Wrong type is used for 'listen_disabled_num' field.

### ISSUE THREAD

**Issue by rpv-tomsk** [collectd/collectd#2386]
memcached.c:
```
if (FIELD_IS("listen_disabled_num")) {
   submit_derive("connections", "listen_disabled", atof(fields[2]), st);
}
```

types.db:
```
connections             value:DERIVE:0:U
```

Choosen data type is incorrect. That is not 'connections rate', but a 'counter how many times limit was reached'. We are unable to know how many connections was lost because of that.

Presense of that metric with type `connections` and type instance `listen_disabled` will break other metrics of `connections` type which could be added:

`rejected` - from field `rejected_connections` which contains  'Conns rejected in maxconns_fast mode'
`opened`  - from field `total_connections` which contains 'Total number of connections opened since the server started running' 

At least, we need to change it's type, but my proposal is to remove that metric. 
If needed, we can add notification instead.

**Comment by octo** [comment]
ACK, `connections` is not the right type. I suggest to use `operations` instead. This is in the gray area between a bug fix and a breaking change, so I'd push this to *master* instead of a version branch.
