### ISSUE TITLE
collectd service ignores /etc/collectd/collectd.conf

### ISSUE THREAD

**Issue by flobeier** [collectd/collectd#2390]
*   Version of collectd: 5.5.1
*   Operating system / distribution: fresh install of Ubuntu 16.04.2 LTS

## Expected behavior
collectd service uses `/etc/collectd/collectd.conf`

I expect the collectd service to use the configuration located at `/etc/collectd/collectd.conf`

## Actual behavior
The configuration seems to be ignored. 

The service starts caching data to `/var/lib/collectd/rrd` even though the plugin isn't activated in `/etc/collectd/collectd.conf` and outputs everything to the syslog even though the loglevel for the syslog plugin is set to `err`.
Even adding `-C /etc/collectd/collectd.conf` to the run command in `/lib/systemd/system/collectd.service` didn't help. 
Manually running collectd by just entering `collectd` works as expected.

## Steps to reproduce

*   install collectd and enable the service
*   check if service respects the configuration located at `/etc/collectd/collectd.conf`

**Comment by rpv-tomsk** [comment]
Please show output of:

`collectd -h`
`/usr/sbin/collectd -h`

And with 'wrong' Collectd started by systemd, please show output of:

`ps uaxf |grep collectd`

**Comment by H4ndl3** [comment]
We tested an older version of collectd, collectd 5.4.3.14.g0b97cf2. This version doesn't show the error, the service is working as expected.

> root@handle ~ # collectd -h
Usage: collectd [OPTIONS]
>
> Available options:
  General:
    -C <file>       Configuration file.
                    Default: /etc/collectd/collectd.conf
    -t              Test config and exit.
    -T              Test plugin read and exit.
    -P <file>       PID-file.
                    Default: /var/run/collectd.pid
    -f              Don't fork to the background.
    -h              Display help (this message)
>
>Builtin defaults:
  Config file       /etc/collectd/collectd.conf
  PID file          /var/run/collectd.pid
  Plugin directory  /usr/lib/collectd
  Data directory    /var/lib/collectd
>
>collectd 5.5.1, http://collectd.org/
>by Florian octo Forster <octo@collectd.org>
>for contributions see `AUTHORS'

>root@handle ~ # /usr/sbin/collectd -h
Usage: collectd [OPTIONS]
>
>Available options:
  General:
    -C <file>       Configuration file.
                    Default: /etc/collectd/collectd.conf
    -t              Test config and exit.
    -T              Test plugin read and exit.
    -P <file>       PID-file.
                    Default: /var/run/collectd.pid
    -f              Don't fork to the background.
    -h              Display help (this message)
>
>Builtin defaults:
  Config file       /etc/collectd/collectd.conf
  PID file          /var/run/collectd.pid
  Plugin directory  /usr/lib/collectd
  Data directory    /var/lib/collectd
>
>collectd 5.5.1, http://collectd.org/
by Florian octo Forster <octo@collectd.org>
for contributions see `AUTHORS'

>root@handle ~ # ps uaxf |grep collectd
root     30464  0.0  0.1  18104  2064 pts/0    S+   11:00   0:00          \_ grep collectd
root     29409  5.4  1.0 978864 22400 ?        Ssl  10:59   0:02 /usr/sbin/collectd

**Comment by rubenk** [comment]
Please share your complete collectd.conf.

**Comment by H4ndl3** [comment]
This is our collectd.conf (comments removed and IP addresses redacted)
```
Hostname "hostname"
FQDNLookup true
Interval 10

LoadPlugin syslog
<Plugin syslog>
	LogLevel info
</Plugin>

LoadPlugin contextswitch
LoadPlugin cpu
LoadPlugin df
LoadPlugin disk
LoadPlugin entropy
LoadPlugin interface
LoadPlugin irq
LoadPlugin load
LoadPlugin memory
LoadPlugin ping
LoadPlugin processes
LoadPlugin protocols

<LoadPlugin python>
	Globals true
</LoadPlugin>

LoadPlugin swap
LoadPlugin uptime
LoadPlugin write_graphite

<Plugin interface>
	Interface "/^l2tp*/"
	IgnoreSelected true
</Plugin>

<Plugin ping>
	Host "1.2.3.4"
	Host "1.2.3.5"
#	...
	Interval 10.0
	Timeout 1.0
	TTL 16
</Plugin>

<Plugin processes>
	Process "named"
	Process "rsyslogd"
	Process "kea-dhcp4"
	Process "bird"
	Process "bird6"
	ProcessMatch "tunneldigger" "tunneldigger"
	Process "collectd"
</Plugin>

<Plugin python>
	ModulePath "/opt/collectd-python/"
	LogTraces true
	Interactive false
	Import "kea"
	Import "ipv4ipv6"
	Import "l2tp"
	Import "sysctl"
</Plugin>

<Plugin write_graphite>
	<Carbon>
		Host "localhost"
		Port "2003"
		Prefix "gateways."
		Postfix ""
		StoreRates false
		AlwaysAppendDS false
		EscapeCharacter "_"
	</Carbon>
</Plugin>

Include "/etc/collectd/filters.conf"
Include "/etc/collectd/thresholds.conf"
```
Right now this config is running fine (= no syslog spamming) with collectd 5.4.1 and Debian 8. I don't know the exact version that starts making trouble, as I pointed out above 5.4.3.14.g0b97cf2 works fine too whereas 5.5.1 doesn't.

**Comment by rubenk** [comment]
Are you running Debian 8 or Ubuntu 16.04?

Did you use this exact same config with a non-working version?

**Comment by H4ndl3** [comment]
@rubenk in the meantime we switched the OS to Debian 8. And yes, that is the exact config I used with the non-working version.
I'm able to reliably reproduce the error given the circumstances above.

**Comment by H4ndl3** [comment]
@rubenk I experienced the problems as reported under Ubuntu 16.04.02.

>How did you see the rrdtool plugin is active?
I didn't see that the plugin was active, I just saw that data was being cached to the folder `/var/lib/collectd/rrd` with the non-working versions and not with the working versions.

>Your config above shows that this is set to info.
It doesn't matter what log level I set, the syslog is always being spammed with everything.

**Comment by rubenk** [comment]
> I didn't see that the plugin was active, I just saw that data was being cached to the folder /var/lib/collectd/rrd with the non-working versions and not with the working versions.

How did you see that?

> It doesn't matter what log level I set, the syslog is always being spammed with everything when using the non-working versions. Therefore the title of this issue, it seems that the config is being (partly) ignored.

Please share these logs.

**Comment by rubenk** [comment]
I installed a clean Ubuntu 16.04 vm, but I can't reproduce this with the collectd 5.5.1 from the Ubuntu repos. Your config works fine.

**Comment by H4ndl3** [comment]
> How did you see that?

The folder was being created and data has been placed inside of it, that didn't happen with the working versions.

>Please share these logs.
>I installed a clean Ubuntu 16.04 vm, but I can't reproduce this with the collectd 5.5.1 from the Ubuntu repos. Your config works fine.

I'll create a new VM with Ubuntu 16.04 and the same software we're using on our other VMs in order to reproduce the error. When I've done that I'll report back. Can you give me your public key? I think it would be easier for you to understand the bug when you can see it for yourself.

**Comment by danielo515** [comment]
Do you have newlines at the end of your config files? For some reason collectd seems to ignore the import of external files if they don't have newlines at the end.

**Comment by flobeier** [comment]
@danielo515 I can't remember but this may have been the issue, thanks for the hint!

I'm closing the issue since I can't reproduce it anymore.

**Comment by yahyakh44** [comment]
i have a question :The amount of data that a Collectd server can handle  ? it can handle a millions of gatways ?
