### ISSUE TITLE
Building collectd --with-libgcrypt fails

### ISSUE THREAD

**Issue by ddaws** [collectd/collectd#2395]
*   Version of collectd: 5.7.1
*   Operating system / distribution: Debian

## Expected behavior

I expect `./configure --with-libgrcrypt && make` to succeed assuming the required deps are properly installed.

## Actual behavior

Upon running make: 

```
...
libcollectdclient/.libs/libcollectdclient.so: undefined reference to `gcry_md_close'
libcollectdclient/.libs/libcollectdclient.so: undefined reference to `gcry_cipher_close'
libcollectdclient/.libs/libcollectdclient.so: undefined reference to `gcry_cipher_setkey'
libcollectdclient/.libs/libcollectdclient.so: undefined reference to `gcry_md_read'
libcollectdclient/.libs/libcollectdclient.so: undefined reference to `gcry_cipher_encrypt'
libcollectdclient/.libs/libcollectdclient.so: undefined reference to `gcry_check_version'
libcollectdclient/.libs/libcollectdclient.so: undefined reference to `gcry_randomize'
libcollectdclient/.libs/libcollectdclient.so: undefined reference to `gcry_md_write'
libcollectdclient/.libs/libcollectdclient.so: undefined reference to `gcry_md_open'
libcollectdclient/.libs/libcollectdclient.so: undefined reference to `gcry_cipher_open'
libcollectdclient/.libs/libcollectdclient.so: undefined reference to `gcry_md_setkey'
libcollectdclient/.libs/libcollectdclient.so: undefined reference to `gcry_cipher_setiv'
libcollectdclient/.libs/libcollectdclient.so: undefined reference to `gcry_control'
libcollectdclient/.libs/libcollectdclient.so: undefined reference to `gcry_cipher_ctl'
libcollectdclient/.libs/libcollectdclient.so: undefined reference to `gcry_md_hash_buffer'
```

## Steps to reproduce

I am attempting to compile collectd 5.7.1 with libgcrypt enabled for secure networking. I initially installed `libgcrypt11 libgcrypt11-dev` via `apt` though could not build because a newer of version of `libgcrypt` is required. I then moved onto install `libgcrypt` from source by running

```
wget https://www.gnupg.org/ftp/gcrypt/libgpg-error/libgpg-error-1.27.tar.bz2
tar -xjf libgpg-error-1.27.tar.bz2
cd libgpg-error-1.27/
./configure
make
make install
cd -
rm libgpg-error-1.27.tar.bz2
rm -r libgpg-error-1.27/

wget https://www.gnupg.org/ftp/gcrypt/libgcrypt/libgcrypt-1.8.0.tar.bz2
tar -xjf libgcrypt-1.8.0.tar.bz2
cd libgcrypt-1.8.0/
./configure
make 
make install
cd -
rm libgcrypt-1.8.0.tar.bz2
rm -r libgcrypt-1.8.0/
```

This installed `libgcrypt.la  libgcrypt.so  libgcrypt.so.20  libgcrypt.so.20.2.0  libgpg-error.la  libgpg-error.so  libgpg-error.so.0  libgpg-error.so.0.22.0` to my `/usr/local/lib`.

I then attempted to build collectd by running 

```
wget https://storage.googleapis.com/collectd-tarballs/collectd-5.7.1.tar.bz2
tar -xjf collectd-5.7.1.tar.bz2
cd collectd-5.7.1
./configure --with-libgcrypt
make
```

This results in the errors posted above.

While running `./configure` this prints to terminal `checking for the default library search path... /lib /usr/lib /usr/local/lib /lib/x86_64-linux-gnu /usr/lib/x86_64-linux-gnu`. It appears that `/usr/local/lib` is on the search path. 

I have tried forcing / ensuring `/usr/local/lib` is linked against via `LDFLAGS=-L/usr/local/lib/ CPPFLAGS=-I/usr/local/lib/ CFLAGS=-I/usr/local/lib/ ./configure --with-libgcrypt` though this has not worked. 

I also noticed the `Makefile.in` contains the following. Maybe these should be set somehow? 

```
GCRYPT_CPPFLAGS = @GCRYPT_CPPFLAGS@
GCRYPT_LDFLAGS = @GCRYPT_LDFLAGS@
GCRYPT_LIBS = @GCRYPT_LIBS@
```

I think it's a bit obvious make isn't my expertise. At this point I am a bit confused and cannot seem to find reference on the matter. Help would be appreciated. 

Thank you in advance!

**Comment by rpv-tomsk** [comment]
>I initially installed libgcrypt11 libgcrypt11-dev via apt though could not build because a newer of version of libgcrypt is required.

```
# dpkg-query -l |grep libgcr
ii  libgcrypt11:i386                      1.5.0-5+deb7u5                    i386         LGPL Crypto library - runtime library
ii  libgcrypt11-dev                       1.5.0-5+deb7u5                    i386         LGPL Crypto library - development files
```
I have this version if `libgcrypt` installed and `collectd-5.7.2` compiles successfully.
What was the issue you found, why you say 'a newer of version of libgcrypt is required'?

**Comment by ddaws** [comment]
I built and attempted to run collectd though received the error `/opt/collectd/sbin/collectd: symbol lookup error: /opt/collectd/lib/collectd/network.so: undefined symbol: gcry_md_hash_buffer`. I then erroneously assumed this was because I was using an outdated version of libgcrypt.

I have switched to using the versions of libgcrypt distributed through apt. 

```
> dpkg-query -l | grep libgcrypt11
ii  libgcrypt11                      1.5.0-3ubuntu0.6                  LGPL Crypto library - runtime library
ii  libgcrypt11-dev                  1.5.0-3ubuntu0.6                  LGPL Crypto library - development files
```

When I run `./configure --with-libgcrypt` I receive the following: 

```
 Libraries:
    ...
    libgcrypt . . . . . . no (symbol gcry_md_hash_buffer not found)
    ...
```

This problem appears to be related to 
- https://lists.gnupg.org/pipermail/gcrypt-devel/2010-June/001606.html
- https://bugs.centos.org/view.php?id=4394

Here (https://lists.gnupg.org/pipermail/gcrypt-devel/2010-June/001617.html) it is suggested that this is a problem with collectd's ability to link against libgcrypt. 

I have confirmed that libgcrypt is present in `/usr/lib/` via 

```
> ls -l /usr/lib/ | grep libgcrypt
-rwxr-xr-x  1 root root      987 Aug  5 22:24 libgcrypt.la
lrwxrwxrwx  1 root root       19 Aug  5 22:24 libgcrypt.so -> libgcrypt.so.20.2.0
lrwxrwxrwx  1 root root       19 Aug  5 22:24 libgcrypt.so.20 -> libgcrypt.so.20.2.0
-rwxr-xr-x  1 root root  3869667 Aug  5 22:24 libgcrypt.so.20.2.0
```

My libgcrypt library does declare the symbol gcry_md_hash_buffer

```
>nm /usr/lib/libgcrypt.so | grep gcry_md_hash_buffer
00000000000244e0 t _gcry_md_hash_buffer
000000000000dde0 T gcry_md_hash_buffer
```

**Comment by rpv-tomsk** [comment]
1) Just try to do `./configure` without `--with-libgcrypt`. IMHO, that option is enabled by default.
Check output if `libgcrypt` will be enabled.
2)If that fail, then do `ln /usr/bin/libgcrypt-config /usr/bin/gcrypt-config` before building Collectd.

That is caused by inconsistency between `gcrypt-config` and `libgcrypt-config` in `configure.ac`.
The last block (which is called by default when you _do not_ use `--with-libgcrypt`) has `libgcrypt-config` while all blocks before has `grcypt-config`. That mismatch real file name, so build fails.

```
--- configure.ac        2017-08-05 20:45:50.000000000 +0700
+++ configure.ac.new    2017-08-09 11:24:33.000000000 +0700
@@ -2330,25 +2330,25 @@
 GCRYPT_LIBS="$GCRYPT_LIBS"
 AC_ARG_WITH(libgcrypt, [AS_HELP_STRING([--with-libgcrypt@<:@=PREFIX@:>@], [Path to libgcrypt.])],
 [
  if test -f "$withval" && test -x "$withval"
  then
         with_libgcrypt_config="$withval"
         with_libgcrypt="yes"
- else if test -f "$withval/bin/gcrypt-config" && test -x "$withval/bin/gcrypt-config"
+ else if test -f "$withval/bin/gcrypt-config" && test -x "$withval/bin/libgcrypt-config"
  then
-        with_libgcrypt_config="$withval/bin/gcrypt-config"
+        with_libgcrypt_config="$withval/bin/libgcrypt-config"
         with_libgcrypt="yes"
  else if test -d "$withval"
  then
         GCRYPT_CPPFLAGS="$GCRYPT_CPPFLAGS -I$withval/include"
         GCRYPT_LDFLAGS="$GCRYPT_LDFLAGS -L$withval/lib"
         with_libgcrypt="yes"
  else
-        with_libgcrypt_config="gcrypt-config"
+        with_libgcrypt_config="libgcrypt-config"
         with_libgcrypt="$withval"
  fi; fi; fi
 ],
 [
  with_libgcrypt_config="libgcrypt-config"
  with_libgcrypt="yes"
 ])
```

**Comment by rubenk** [comment]
@ddaws a few questions:
- What version of Debian are you using?
- Can you share your config.log?
- Is there any reason you try to build from source? Our CI builds packages for Debian (https://github.com/collectd/collectd-ci)
- After installing libgcrypt from source, did you thoroughly remove it? I have a hunch that you have multiple libraries installed and that something goes wrong in detecting this.

**Comment by rubenk** [comment]
@rpv-tomsk I think you're right, and the --with-gcrypt case has never worked properly. As far as I can tell there has never been a gcrypt-config command, resulting in empty GCRYPT_CPPFLAGS and GCRYPT_LDFLAGS.
