### ISSUE TITLE
Making DPDK detection multi-arch compatible by using pkg-config

### ISSUE THREAD

**Issue by cpaelzer** [collectd/collectd#2399]
*   Version of collectd: 5.7.1
*   Operating system / distribution: Debian/Ubuntu

## Expected behavior
- link with DPDK on all architectures

## Actual behavior
- fail to link on all but amd64

## Steps to reproduce

* build against libdpdk-dev as provided in the repositories

## Background

* DPDK is not truly multi-arch in its libs (same file paths differ per arch), so that had to be fixed up
* To do so rte_config is in an per-arch dir now
* a pkg-config is provided to pick up this and more that might be needed
* Currently LIBS and CFLAGS are provided

Upstream DPDK postponsed the creation of an "official" pkg-config until the currently discussed rewrite of the build system so I can't provide this working against upstream.
But that is not an issue as it is fully optional, so if a user sets dpdk flags he wins, likewise if there is no pkg-config for dpdk available nothing changes.
But until upstream has one we can agree upon what we have in Debian and Ubuntu makes it proper multiarch and working for now.

## Fix
* use the provided pkg-config, so I wanted you to consider applying the following change that I provide to use pkg-config accordingly.

**Comment by bluca** [comment]
For the record, here's a reference to the upstream RFC patches to switch build systems, which inclulde generating a pkg-config:
http://dpdk.org/ml/archives/dev/2017-August/072818.html

**Comment by rubenk** [comment]
Merged as  929a7f2, thank you both.
