### ISSUE TITLE
tail plugin internal counter never resets until collectd restart

### ISSUE THREAD

**Issue by smartash25** [collectd/collectd#2401]
*   Version of collectd: 5.4.0
*   Operating system / distribution: Ubuntu 14.04

## Expected behavior

I enabled the tail plugin to tail /var/log/apache2/access.log and match http status codes like 200, 400, etc.  I set DSType to CounterInc. I create some http 400's and see the counter go from 0 to X.  Then on the next interval if I do not create any more http 400's, the value stays at X.  It never resets back to 0 unless I restart collectd.  I expect it to go back to 0 on each interval read.

## Actual behavior

value never resets back to 0 without a collectd restart

## Steps to reproduce

*   step1: enable tail plugin, use config like:
LoadPlugin tail

<Plugin "tail">
   <File "/var/log/apache2/access.log">
      Instance "httpResponseCodes"
      <Match>
        Regex "\" 400"
        DSType "CounterInc"
        Type "counter"
        Instance "400"
      </Match>
      <Match>
        Regex "\" 200 "
        DSType "CounterInc"
        Type "counter"
        Instance "200"
      </Match>
   </File>
</Plugin>

*   step 2: service collectd restart

*   step 3: in my case we are logging our metrics stuff to syslog, so I just tail -f /var/log/syslog and watch the value increase, then never get reset to 0.

**Comment by smartash25** [comment]
sorry, new to this, didn't include my config in any code tags or anything. Here is a better example without the "<" and ">"
<pre>
<Plugin "tail">
   <File "/var/log/apache2/access.log">
      Instance "httpResponseCodes"
      <Match>
        Regex "\" 400"
        DSType "CounterInc"
        Type "counter"
        Instance "400"
      </Match>
      <Match>
        Regex "\" 200 "
        DSType "CounterInc"
        Type "counter"
        Instance "200"
      </Match>
   </File>
</Plugin>
</pre>

**Comment by rpv-tomsk** [comment]
You want to get _rate_ of errors. 
For that, you should use `DeriveInc`, not `CounterInc`. 
Counter will not reset between intervals, and it should not - that is expected and correct behaviour.

**Comment by smartash25** [comment]
Thanks for your comment.  I just tried DeriveInc with type "derive" and the problem is still happening.  I restarted collectd after I made the change.  I created 3 HTTP 400 responses, I see the value increased from 0 to 3.  Then, I waited for the next interval ( 20s ) and the value is still 3.  I waited many more intervals and still set to 3.  I then created 4 more HTTP 400's and the value is now 7 and staying.

**Comment by rpv-tomsk** [comment]
Sorry, I slightly mistook the problem when I wrote my answer.

That change of `counter` to `derive` should not have to help.

>step 3: in my case we are logging our metrics stuff to syslog, so I just tail -f /var/log/syslog and 
>watch the value increase, then never get reset to 0.

Your use-case is not practical one, but a kind of debugging.
All described is expected and correct behaviour, IMHO (you does not provide your syslog configuration / output example).

Try to use your config at practice (build graphs) and all should be ok.

Also, I would recommend you to use Derive instead of Counter for that anyway.
See https://collectd.org/wiki/index.php/Data_source for some details.

**Comment by smartash25** [comment]
If I generate 10 http 400's, what DSType and type combination should I use to see "10" in getval output?  I'm only ever seeing numbers in scientific notation that are nowhere close to 10.   I have looked and am just not finding anything helpful. I'm sorry I'm asking these types of questions in a bug report, but I don't know where else to get help.  I've tried IRC but nobody ever responds there.

**Comment by rpv-tomsk** [comment]
> I'm sorry I'm asking these types of questions in a bug report, but I don't know where else to get help.

AFAIK, that is OK.

>If I generate 10 http 400's, what DSType and type combination should I use to see "10" in getval 
>output? I'm only ever seeing numbers in scientific notation that are nowhere close to 10. I have looked 
>and am just not finding anything helpful.

At first, please show/explain how you get values. 
I see only Collectd config, that is not enough for me to fully understand/reproduce the issue.

**Comment by octo** [comment]
This is expected behavior for `CounterInc` / `DeriveInc`. The behavior of `GaugeInc` is probably closer to what you're trying to achieve.
