### ISSUE TITLE
Unable to view values from write_redis

### ISSUE THREAD

**Issue by dakshinai** [collectd/collectd#2402]
*   Version of collectd: current master
*   Operating system / distribution: Fedora/4.11.12-200.fc25.x86_64

## Expected behavior
I have intel_rdt and Redis setup. I was able to read values from intel_rdt input plugin with unixsock output plugin. I'm unable to see values using write_redis output plugin. I started redis server with default configuration. Then launched collectd. However I see no keys when I read Redis DB using redis-cli
(Description of the behavior / output that you expected)

## Actual behavior
No values when I read Redis DB using redis-cli
(Description of the behavior / output that you observed)

## Steps to reproduce

*   step 1
Enable plugin intel_rdt (ensure libpqos is installed (used latest))
*   step 2
Enable plugin write_redis
*   step 3
Launch redis-server
*   step 4
build.sh, configure, make and make install
*   step 5
Launch redis-cli
*   step 6
keys * returns empty list

**Comment by rubenk** [comment]
Can you share your collectd.conf and your logs?

**Comment by dakshinai** [comment]
I have switched to commit 6d79874 due to the pkg-config error.

The issue was that libhiredis.so.0.13 could not be found. It was installed in /usr/local/lib though ldd could not find it. I had to manually point LD_LIBRARY_PATH to that location.

Also, 
I ran ./configure && make && make install
./configure --enable-intel_rdt --enable-write_redis still leaves the config file untouched. 

I manually edited the config file at /opt/collectd/etc/collectd.conf 
Is this the only way to enable plugins?

**Comment by rubenk** [comment]
> The issue was that libhiredis.so.0.13 could not be found. It was installed in /usr/local/lib though ldd could not find it. I had to manually point LD_LIBRARY_PATH to that location.

Why don't you just install the hiredis-devel rpm?

> I ran ./configure && make && make install
./configure --enable-intel_rdt --enable-write_redis still leaves the config file untouched.

> I manually edited the config file at /opt/collectd/etc/collectd.conf
Is this the only way to enable plugins?

This is by design, make install never overwrites existing configs.

Is your issue fixed now?

**Comment by dakshinai** [comment]
Sorry for the delayed response. Thank you for the clarification. I shall try the rpm way too. My issue is fixed now.
