### ISSUE TITLE
How to make collectd on Centos 6.9 with all plugins

### ISSUE THREAD

**Issue by petarkozic** [collectd/collectd#2415]
*   Version of collectd: 5.7.2
*   Operating system / distribution: Centos 6.9

I configure and make collectd 5.7.2 from source with : 
./configure
make all install

I don't have write_prometheus, apache, nginx, bind ... plugins

How can I enable all plugins in configuration and build ?

**Comment by rpv-tomsk** [comment]
You need to install all required dependency libraries and their development headers.

>I don't have write_prometheus, apache, nginx, bind ... plugins

For this case, you need to install `curl` properly.

**Comment by petarkozic** [comment]
Thank you Pavel. Yes, I founded this information and compile with all
neccesary plugin. Thank you.

**Comment by rpv-tomsk** [comment]
Hi! If you have no problems more, then please close this issue. Thanks.
