### ISSUE TITLE
Can intel_rdt supply readings per core

### ISSUE THREAD

**Issue by dakshinai** [collectd/collectd#2416]
*   Version of collectd: current master
*   Operating system / distribution: Fedora/4.11.12-200.fc25.x86_64

## Expected behavior
I'm trying to get a dump of values supplied by intel_rdt into collectd as csv files. I see only one file per value but these values do not indicate which core they belong to. The configuration looks like
<Plugin “intel_rdt”>Cores “0-15”</Plugin>

(Description of the behavior / output that you expected)
Get values per core
## Actual behavior
Values without any core information

(Description of the behavior / output that you observed)
![image](https://user-images.githubusercontent.com/6013919/29900897-83af3176-8da9-11e7-899d-48c3a881f074.png)

## Steps to reproduce

*   step 1
Enable read plugin intel_rdt, configure core information
*   step 2
Enable write plugin csv
*   step 3
Check output

**Comment by maryamtahhan** [comment]
yes, please see the sample config @ https://gerrit.opnfv.org/gerrit/gitweb?p=barometer.git;a=blob;f=src/collectd/collectd_sample_configs/rdt.conf;hb=HEAD
and https://github.com/collectd/collectd/blob/master/src/collectd.conf.pod 

> If an empty string is provided as value for this field default cores configuration is applied - a separate group is created for each core.

**Comment by maryamtahhan** [comment]
@dakshinai did you resolve the issue you were seeing?

**Comment by dakshinai** [comment]
@maryamtahhan Thank you for your response. The sample file helped a lot and I was able to see readings per core.
