### ISSUE TITLE
MQTT Plugin fails to load with TLS options configured

### ISSUE THREAD

**Issue by nibor-b** [collectd/collectd#2419]
*   Version of collectd: 5.6.2.56.gda4589d
*   Operating system / distribution: Ubuntu Xenial

## Expected behavior

Ability to configure TLS/Certificate options for the MQTT plugin, as described here in the main collectd.conf documentation:
https://collectd.org/documentation/manpages/collectd.conf.5.shtml#plugin_mqtt

NOTE:
These configuration options are NOT specified in the actual MQTT plugin wiki page:
https://collectd.org/wiki/index.php/Plugin:MQTT

## Actual behavior

collectd launches MQTT plugin successfully, but does not appear to recognise the TLS/certificate related configuration options detailed above:

```
Sep  4 21:07:05 collectd[31533]: plugin_load: plugin "mqtt" successfully loaded.
Sep  4 21:07:05 collectd[31533]: mqtt plugin: Unknown config option: TLSProtocol
Sep  4 21:07:05 collectd[31533]: mqtt plugin: Unknown config option: CACert
Sep  4 21:07:05 collectd[31533]: mqtt plugin: Unknown config option: CertificateFile
Sep  4 21:07:05 collectd[31533]: mqtt plugin: Unknown config option: CertificateKeyFile
```

**Comment by octo** [comment]
Can you please provide the relevant configuration? The `TLSProtocol` option is only valid inside `<Publish>` blocks.

Thanks and best regards,
—octo

**Comment by nibor-b** [comment]
That could be the issue then. I’m trying to use the TLS options within the ```<Subscribe>``` block:

```
<Plugin mqtt>
 <Subscribe "AWS-IoT">
  Host "XXX.amazonaws.com"
  Port "8883"
  TLSProtocol "tlsv2"
  ClientId "XXX"
  CACert "/etc/collectd/ssl/ca"
  CertificateFile "/etc/collectd/ssl/cert"
  CertificateKeyFile "/etc/collectd/ssl/key"
  Topic "XXX"
  QoS 0
  CleanSession true
 </Subscribe>
</Plugin>
```

I believe this is required to interact with many online services, including AWS IoT, which is what I’m trying to use in this case...

Here’s the documentation that specifies the authentication method must be ‘Client Certificate’ for the MQTT protocol:

http://docs.aws.amazon.com/iot/latest/developerguide/protocols.html
