### ISSUE TITLE
Incorrect uptime reported for lxc/lxd containers

### ISSUE THREAD

**Issue by zerkms** [collectd/collectd#2424]
*   Version of collectd: master
*   Operating system / distribution: ubuntu 16.04

the `uptime` plugin reads from `"/proc/stat"` on linux, while under lxs/lxd that reports the host machine statistics. How about using `/proc/uptime` (as `uptime` tool does).

**Comment by zerkms** [comment]
Btw, I can contribute the PR if everybody agrees to use `/proc/uptime`, which I think is a proper source for the uptime info.

**Comment by octo** [comment]
SGTM, thanks @zerkms
