### ISSUE TITLE
LVM plugin does not report thin pool usage

### ISSUE THREAD

**Issue by ceecko** [collectd/collectd#2426]
*   Version of collectd: 
*   Operating system / distribution: CentOS 7.3.1611 (Core). Kernel 3.10.0-514.21.1.el7.x86_64

## Expected behavior

It seems that according to https://github.com/collectd/collectd/pull/603 the LVM plugin should report thin-pool free/used metrics.

## Actual behavior

The LVM plugin does not report free/used metrics for thin-pools.

## Steps to reproduce

* Create thin-pool through lvm
* Enable LVM plugin
* Observe metrics

```
# vgs
  VG   #PV #LV #SN Attr   VSize   VFree
  data   1   2   0 wz--n- 100.00g    0
```

```
# lvs
  LV          VG   Attr       LSize  Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  data        data -wi-ao----  9.00g
  docker_thin data twi-aotz-- 90.00g             33.74  6.03
```

**Comment by rpv-tomsk** [comment]
> Version of collectd:
Which version of Collectd are you using?

**Comment by ceecko** [comment]
The version is: `5.7.2.sfx0`
I have managed to resolve the issue by adding more capabilities in systemd
`CapabilityBoundingSet=CAP_SYS_ADMIN`

**Comment by octo** [comment]
Hi @ceecko, thank you very much for your update. `CAP_SYS_ADMIN` seems a bit excessive for the read-only access required by *collectd*. Is there any less privileged capability that will get you there? We should add a capability check to the plugin so users get an informative warning message in case capabilities are missing.

Best regards,
—octo

**Comment by ceecko** [comment]
@octo I have tried only a couple. Since I'm not familiar with the capabilities and I don't mind excessive persmissions. In this case I opted for the `CAP_SYS_ADMIN`. In case less privileges are sufficient, I'll be happy to use them.

**Comment by octo** [comment]
@ceecko I did some a quick search and from what I found it sounds like users with *read* permissions on `/dev/lvm` can read LVM metrics. Can you confirm this? —octo

**Comment by ceecko** [comment]
@octo I'm running CentOS 7 and there's no such file as /dev/lvm
