### ISSUE TITLE
Change Value of Measurements 

### ISSUE THREAD

**Issue by Neru007** [collectd/collectd#2427]
Is it possible to change the Values of Measurements. When I configure plugin it creates default Measurements for every plugin.

CPU_value for CPU plugin 
disk_value for disk plugin.

I want to change the values of these Measurements

**Comment by rpv-tomsk** [comment]
As I understand, you want to change reported `types`. For not-generic plugins that is only possible by source code patch. (If I understand you correctly, your question is not detailed enough).
