### ISSUE TITLE
Very high values on CPU Perc and Context switches on collectd restart. 

### ISSUE THREAD

**Issue by prabhakarms** [collectd/collectd#2428]
*   Version of collectd: 5.5
*   Operating system / distribution: CentOs6

## Expected behavior
Collectd should emit Cpu Perc usage for user and system in % usage. The % usage should not exceed 100% in ideal case:). 
 
## Actual behavior
Collectd on restart emits very high values on CpuPerc both for user and system. Also the number of the context is very high. 

## Steps to reproduce

On CentOs6
-  Collectd config changes to report in % usage on CPU mertrics. 
- Enable CSV plugin. 
- Start the collectd service.
- Stop the service and start the service again. 
- Very high values reported for CPU perc and context switches.

**Comment by octo** [comment]
Unfortunately I was not able to reproduce:

```
$ egrep -v '^(#|$)' etc/collectd.conf
LoadPlugin logfile
<Plugin logfile>
	LogLevel debug
	File STDOUT
	Timestamp true
	PrintSeverity false
</Plugin>
LoadPlugin cpu
LoadPlugin csv
<Plugin cpu>
  ValuesPercentage true
</Plugin>
<Plugin csv>
	DataDir "/tmp/collectd/var/lib/collectd/csv"
	StoreRates false
</Plugin>
```

```
$ cat /tmp/collectd/var/lib/collectd/csv/${HOSTNAME}/cpu-0/percent-{user,system}-2017-10-11
epoch,value
1507702233.941,3.521127
1507702243.941,3.406814
1507702255.198,3.614458
1507702265.198,3.100000
epoch,value
1507702233.941,0.704225
1507702243.941,0.801603
1507702255.198,0.903614
1507702265.198,0.500000
```
