### ISSUE TITLE
statvfs(/proc/sys/fs/binfmt_misc) failed: No such device

### ISSUE THREAD

**Issue by randuhmm** [collectd/collectd#2429]
*   Version of collectd: 5.4.1
*   Operating system / distribution: Raspbian GNU/Linux 8 (jessie)

My syslog is being spammed with the line:

    statvfs(/proc/sys/fs/binfmt_misc) failed: No such device

I am running `collectd` on a Raspberry Pi 3. The only changes that have been done to the config are disabling the `irq` plugin (because of this issue #971) and enabling the `network` plugin.

**Comment by octo** [comment]
Hi @randuhmm,

that sounds like an error the *df plugin* would report. You can use the `Device`, `MountPoint` or `FSType` option to prevent it from trying to stat that particular mount point.

Best regards,
—octo

**Comment by lukahn** [comment]
I had this problem too. Turns out I needed to reboot the Pi 3, as I had previously run an upgrade (including a new kernel) without rebooting.
https://www.raspberrypi.org/forums/viewtopic.php?t=242093
