### ISSUE TITLE
Ability to disable swap io.

### ISSUE THREAD

**Issue by zerkms** [collectd/collectd#2433]
lxc/lxd containers at the moment cannot properly report the swap io. Since the corresponding `/proc/vmstat` are not virtualised. Relevant bug report: https://github.com/lxc/lxcfs/issues/212

It would be ideal if `swap` plugin had a boolean switch to disable swap io in case if it's not needed.

As usually: if you think it's acceptable and a good idea - I might implement it.

Thanks.

**Comment by octo** [comment]
SGTM, thanks @zerkms! `ReportIO` would be a good (i.e. consistent) name for such a config option.
