### ISSUE TITLE
In case of using DSType Counterset, tail plugin failed.

### ISSUE THREAD

**Issue by kazushima** [collectd/collectd#2447]
*   Version of collectd:5.7.1
*   Operating system / distribution: Linux version 4.4.8-20.46.amzn1.x86_64

## Expected behavior
Count result of tail plugin is setted matched count, 
and next time, count return zero.

If in csv plugin result, I expected following:

```
1506406260.549,1   <-- regex matched count
1506406290.549,0
1506406320.549,2   <-- regex matched count 
1506406350.549,0
```

## Actual behavior
I described collectd.conf like following: 

```
<Plugin tail>
  <File "/var/log/test/test.log">
    Instance "error.log"
    Interval 30
    <Match>
      Regex "\\[ERROR\\]"
      DSType "CounterSet"
      Type "counter"
      Instance "ERROR"
    </Match>
  </File>
</Plugin>
```

But, following error message is outputed to collectd.log, and count result of tail plugin is not setted matched count.

> [error] utils_match: match_apply: callback failed.

Is my setting incorrect?

**Comment by rpv-tomsk** [comment]
Hi!

Please clarify, what lines are in your `/var/log/test/error.log`.

I see no subexpression in your `Regex`. 
That is required by 'CounterSet' DSType. 
Maybe you want to use 'CounterInc' instead?

**Comment by kazushima** [comment]
Hi, rpv-tomsk!  Thank you for your responce.

There is a correction. Logfile name is test.log. 
It contains error and info messages. For example, that is following.

```
[ERROR]test
[INFO]test
[INFO]test
[ERROR]test 
```

> That is required by 'CounterSet' DSType.

Thank you, but I don't know that.
If possible, could you give me an example?

> Maybe you want to use 'CounterInc' instead?

I did test by using 'CounterInc', but count result of csv plugin continued to increase.
I did not expect that.

**Comment by octo** [comment]
Hi @kazushima, thanks for reaching out. I think you're missing a **capture group** in your regular expression.

Best regards,
—octo

**Comment by rpv-tomsk** [comment]
What result do you want to get? 
Please, explain that. I'm unable to understand that from your previous description in 'Expected behavior'.

**Comment by kazushima** [comment]
Hi guys. Thank you for your comments.

To: @octo

Thank you. 
But my understandig of  regular expression is cheep...
I will investigate.

To:@rpv-tomsk

Sorry for the not clear description.
For example, when the plugin monitors logfile at an interval of 60 seconds,
I want to know the number of ERRORs output during that 60 seconds

```
[ERROR][17-09-26 16:45:00] error occured
[INFO ][17-09-26 16:47:00] information
[INFO ][17-09-26 16:49:00] information
[INFO ][17-09-26 16:50:00] information
[ERROR][17-09-26 16:50:20] error occured
[ERROR][17-09-26 16:50:30] error occured
[INFO ][17-09-26 16:51:00] information
[INFO ][17-09-26 16:52:00] information
```

In the case of the above log, I expected count of error at each output timing.

```
output timing, count result
17-09-26 16:46:00, 1
17-09-26 16:47:00, 0
17-09-26 16:48:00, 0
17-09-26 16:49:00, 0
17-09-26 16:50:00, 0
17-09-26 16:51:00, 2
17-09-26 16:52:00, 0
```

**Comment by rpv-tomsk** [comment]
Hi! 

Try to use the following config:
```
    <Match>
      Regex "\\[ERROR\\]"
      DSType "DeriveInc"
      Type "errors"
      Instance "ERROR"
    </Match>
```

The `Type` should be something with `DERIVE` dataset (see `types.db` contents) - I found `errors` or `derive` types suitable for your needs.

**Comment by kazushima** [comment]
Hi @rpv-tomsk ! Thanks for your advice.

I tryed your config, but I coudn't get expected result...
Indeed, no error occurred, but error count continued to increase.
This is same result when using 'CounterInc'.

logfile:

```
[ERROR][Tue Sep 26 18:32:57 JST 2017] error occured
[ERROR][Tue Sep 26 18:32:59 JST 2017] error occured
[ERROR][Tue Sep 26 18:33:00 JST 2017] error occured
[INFO ][Tue Sep 26 18:34:52 JST 2017] information
[INFO ][Tue Sep 26 18:35:06 JST 2017] information
[INFO ][Tue Sep 26 18:35:20 JST 2017] information
[ERROR][Tue Sep 26 18:39:25 JST 2017] error occured
[ERROR][Tue Sep 26 18:39:37 JST 2017] error occured
```
csv plugin result（epoch is unix time, so I added JST format by hand）

```
epoch,value
1506418300.591,0 # 2017/09/26 18:31:40 
1506418360.591,0 # 2017/09/26 18:32:40 
1506418420.591,3 # 2017/09/26 18:33:40 
1506418480.591,3 # 2017/09/26 18:34:40 
1506418540.591,3 # 2017/09/26 18:35:40 
1506418600.591,3 # 2017/09/26 18:36:40 
1506418660.591,3 # 2017/09/26 18:37:40 
1506418720.591,3 # 2017/09/26 18:38:40 
1506418780.591,5 # 2017/09/26 18:39:40 
1506418840.591,5 # 2017/09/26 18:40:40 
1506418900.591,5 # 2017/09/26 18:41:40 
```

**Comment by rpv-tomsk** [comment]
I think, you should set `StoreRates true` in `<Plugin csv>` and try to test that config with your charting system.

**Comment by kazushima** [comment]
Thanks for you commnt. My csv plugin config is following:

```
<Plugin csv>
    DataDir "/var/lib/collectd/csv"
    StoreRates false
</Plugin>
```

**Comment by rpv-tomsk** [comment]
>    StoreRates false

I know that.

>I think, you should set StoreRates true in <Plugin csv> and try to test that config with your charting system.

**Comment by kazushima** [comment]
Sorry. I am wrong. I' ll try it.

**Comment by kazushima** [comment]
I tried and  I got near expected result.

But,I think that I cant send this result to cloudwathc by aws labs plugin.
And also, I want to get count, not rate（rate is difficult to understand for me）.

Sorry, Although you gave advice.


```
[ERROR][Tue Sep 26 19:38:49 JST 2017] error occured
[ERROR][Tue Sep 26 19:39:16 JST 2017] error occured
[INFO ][Tue Sep 26 19:40:00 JST 2017] information
[INFO ][Tue Sep 26 19:40:03 JST 2017] information
[ERROR][Tue Sep 26 19:40:49 JST 2017] error occured
```

```
1506422319.512,nan # 2017/09/26 19:38:39
1506422379.500,0.033340 # 2017/09/26 19:39:39
1506422439.500,0.000000 # 2017/09/26 19:40:39
1506422499.500,0.016667 # 2017/09/26 19:41:39
```

**Comment by octo** [comment]
@kazushima you appear to use a 60 second interval. The rates therefore mean:

*   0.033340 [errors/s] × 60 [s] = 2.000400 [errors]
*   0.016667 [errors/s] × 60 [s] = 1.000020 [errors]

This is exactly the result I expected.

The *tail plugin* is creating a `DERIVE` metric for you, it's just converted to a rate by the *csv plugin* because of the `StoreRates true` option. Another output plugin, such as AWS' CloudWatch plugin, are not affected by that setting.

Best regards,
—octo

**Comment by rpv-tomsk** [comment]
>And also, I want to get count, not rate（rate is difficult to understand for me and others）.

Count of events per interval - is a rate of events.

>I will search capture group in comment from @octo .

You need not to use capture groups to count events.

**Comment by kazushima** [comment]
Thanks @octo and @rpv-tomsk.

But, my final purpose are sending error count to clowdwatch by aws labs plugin, and creating cloudwatch charts and alarms.
Using csv plugin is for test, try and error only.

After all, why tail pugin occured error by using 'CounterSet' ?

**Comment by rpv-tomsk** [comment]
>After all, why tail pugin occured error by using 'CounterSet' ?

Because to *set* it needs to extract the value from log line. Your log lines has no such values, and regular expression has no rules (directive) to extract a such.

**Comment by kazushima** [comment]
I see...
In other words, my understanding was wrong.

CounterSet means settings value from matched log line (not count of matched log lines）to internal counter of plugin.

@octo , @rpv-tomsk , Thank you very much for your comments.
I close this issue.

**Comment by akhilnair95** [comment]
@kazushima Using DSType "GaugeInc" gave me the expected behaviour

**Comment by kazushima** [comment]
@akhilnair95 

Sorry for my slow response.
I have no expected behavior of using type "gauge".
I'm using type "count".
