### ISSUE TITLE
Is there plugin for getting count of matched line in logfiles within interval period?

### ISSUE THREAD

**Issue by kazushima** [collectd/collectd#2448]
*   Version of collectd:5.7.1
*   Operating system / distribution:Linux version 4.4.8-20.46.amzn1.x86_64

I am the one who posted issue #2447 .

I'm searching collectd plugin for getting error count in logfiles within interval period.

In case of  logfile like following:

```
[INFO ][Tue Sep 26 18:32:57 JST 2017] information
[ERROR][Tue Sep 26 18:33:40 JST 2017] error occurred
[INFO ][Tue Sep 26 18:34:12 JST 2017] information
[INFO ][Tue Sep 26 18:34:20 JST 2017] information
```
I want to get result like following and send data to aws cloudwatch:

```
check-timing, count of matched [ERROR]
Tue Sep 26 18:33:00 JST 2017,0
Tue Sep 26 18:34:00 JST 2017,1
Tue Sep 26 18:35:00 JST 2017,0
```

It seemed that it could not be realized with the tail plugin.

It may be out of place, but if there is who knows realizable plugin for collectd, 
Could you tell me please ?

**Comment by rpv-tomsk** [comment]
Hi!

Try to use the following config:
```
    <Match>
      Regex "\\[ERROR\\]"
      DSType "GaugeInc"
      Type "gauge"
      Instance "ERROR"
    </Match>
``
For `DSType Gauge` there is internal counter reset on read. So, you should get expected values.

The Type should be something with GAUGE dataset (see types.db contents).
The `gauge` is suitable to make test.

**Comment by kazushima** [comment]
Hi @rpv-tomsk .

Thank you for your comment, this time too.
I tried your config, and got better result than last time!

```
1506477767.114,nan # 2017/09/27 11:02:47
1506477827.114,1.000000  # 2017/09/27 11:03:47
1506477887.114,nan  # 2017/09/27 11:04:47
```

I have on post to warry about this results.
I tried 2 type (gauge and count), and got same results.
When matched lines are not exists in interval , 'nan' returned.

Do you know setting for getting 0 ,when matched lines are not exists in interval ?

**Comment by rpv-tomsk** [comment]
@octo, that is about additional DSType for this usecase?

**Comment by octo** [comment]
`src/daemon/utils_match.c:match_value_reset()` resets all `Gauge*` matches to *NaN*. One could argue that `GaugeInc` should be reset to zero instead, since it's counting occurrences and "no occurrences" should be reported as zero, not NaN.

**Comment by rpv-tomsk** [comment]
Agreed.

**Comment by kazushima** [comment]
If I used current type, I could send data to cloudwatch and create charts.
But, Of cource, it is ideal that 0 is returned.

Thank you for your comments, advices and improvements.

May I close this issue?
I am not used to post issue to github.com...

**Comment by kazushima** [comment]
@octo , Thank you for your merge.

**Comment by jleberre** [comment]
Hi @octo.
I may be mistaken, but I think resetting gauge value to 0 when using `GaugeInc` (https://github.com/collectd/collectd/pull/2452/files#diff-c80a3e820b0e1b707e765a65e6271ff4d1f1a84eb9f5cec650e85ad852022e2fR297) did not fix the issue since `simple_submit_match` still return `NaN` if there has been no match : 
https://github.com/collectd/collectd/blob/1da3305c10c8ff9a63081284cf3d4bb0f6daffd8/src/utils_tail_match.c#L77-L79
