### ISSUE TITLE
disk plugin: UseBSDName doesn't work on Mac OS X 10.7.3

### ISSUE THREAD

**Issue by blysik** [collectd/collectd#245]
I wanted to try the new UseBSDName option in 5.2, so I compiled a new version, and deployed to a host.  With this config:

```
LoadPlugin disk
<Plugin "disk">
  UseBSDName true
</Plugin>
```

I don't get anything at all collected for disks.  From the documentation, this should start processing all the disk devices, right/

**Comment by rubenk** [comment]
I just checked on my Macbook Pro running 10.11 with Collectd 5.5.1.
I get values for 'disk0' with UseBSDName true:

```
[2016-02-27 18:22:03] write_log values:
localhost.disk-disk0.disk_time.read 4717309090 1456593723
localhost.disk-disk0.disk_time.write 979393052 1456593723
```

@blysik can you check if this is still an issue for you?

**Comment by blysik** [comment]
I'm hopeful to roll the latest version of collectd out shortly.  I'll report back soon.

**Comment by rubenk** [comment]
@blysik any luck?

**Comment by rubenk** [comment]
I'm going to close this. Please open a new issue if this is still an issue in the latest version of Collectd.
