### ISSUE TITLE
tcpconns plugin using 100% of CPU

### ISSUE THREAD

**Issue by jruybal** [collectd/collectd#2455]
*   Version of collectd: 4.10.9
*   Operating system / distribution: CentOS 6.8

## Expected behavior

Collectd is supposed to be a lightweight plugin, we're collecting metrics every 10s on some high end webservers, and would like to observer tcp stats without it burdening the server.

## Actual behavior

When tcpconns plugin is enabled, we observe 100% cpu use by collectd on 2 cores through top. When disabled cpu use by collectd is < 1%.

## Steps to reproduce

*   enable tcpconns with the following 

```
LoadPlugin tcpconns

<Plugin "tcpconns">
  ListeningPorts false
  LocalPort "8080"
</Plugin>
```

*   Start collectd
*   Run top command

**Comment by jruybal** [comment]
For the record, collectd CPU monitoring corroborate this. 13:57 was when the tcpconns plugin was disabled.
![screen shot 2017-09-27 at 2 12 18 pm](https://user-images.githubusercontent.com/5640443/30938132-ebca8022-a38d-11e7-933a-1d66f03c893e.png)

**Comment by octo** [comment]
Hi @jruybal,

thanks for reporting this. Unfortunately, version 4.10 is ancient and we're not supporting the 4.x branch anymore. (We stopped support when the last distribution which shipped a binary package of the 4.x branch stopped their support.) Please try upgrading to a more recent version (5.6 and 5.7 are currently supported). If the problem persists this is definitely something that needs to be resolved.

Best regards,
—octo
