### ISSUE TITLE
collectd-virt plugin Array index out of bounds

### ISSUE THREAD

**Issue by antr67** [collectd/collectd#2457]
*   Version of collectd: 5.7.1
*   Operating system / distribution: CentOs 7.4 with libvirt 3.2.0 running qemu vms

## Expected behavior
collectd with virt plugin not logging large amount of messages to /var/log/messages

## Actual behavior
Logs the following to /var/log/messages every 10 seconds.

Sep 27 15:12:19 server1 collectd[23152]: virt plugin: Array index out of bounds: tag_index = 9
Sep 27 15:12:19 server1 collectd[23152]: virt plugin: Array index out of bounds: tag_index = 9
Sep 27 15:12:19 server1 collectd[23152]: virt plugin: Array index out of bounds: tag_index = 9
Sep 27 15:12:19 server1 collectd[23152]: virt plugin: Array index out of bounds: tag_index = 9

## Steps to reproduce
*   install collectd from epel 7.10 repository
*   install collectd-virt from epel 7.10 repository
*   start collectd

**Comment by octo** [comment]
From a quick look it seems that #2168 fixed this. This change is in *master* only, i.e. it will be in the upcoming 5.8 release but not in 5.6 / 5.7.

**Comment by antr67** [comment]
Ok thanks for the info.
