### ISSUE TITLE
varnish plugin: Metrics with invalid data source type.

### ISSUE THREAD

**Issue by octo** [collectd/collectd#2462]
*   Version of collectd: *master*
*   Operating system / distribution: n/a

## Expected behavior

The `varnish_submit_gauge()` helper function should only be called with *types* (the third argument of the function) that are defined as `GAUGE` in `src/types.db`. Inversely, `varnish_submit_derive()` should only be called with `DERIVE` metric types.

## Actual behavior

The following Varnish metrics are passed to `varnish_submit_gauge()` but reference `DERIVE` metric types:

*   `bans_persisted_bytes` (references `total_bytes`)
*   `bans_persisted_fragmentation` (references `total_bytes`)
*   `g_alloc` (references `total_operations`)
*   `req` (references `http_requests`)

The following Varnish metrics are passed to `varnish_submit_derive()` but reference `GAUGE` metric types:

*   `creat` (references `objects`)
*   `destroy` (references `objects`)
*   `exp_mailed` (references `objects`)
*   `exp_received` (references `objects`)
*   `thread_queue_len` (references `queue_length`)

**Comment by octo** [comment]
@dmatetelki You seem to know Varnish metrics quite well; can you help with this?

**Comment by dmatetelki** [comment]
Sure, let me check them.

**Comment by octo** [comment]
Fixed by #2463, thanks @dmatetelki!
