### ISSUE TITLE
ping plugin: Can't ping hostnames with IPv6 addresses without IPv6 connectivity

### ISSUE THREAD

**Issue by lilydjwg** [collectd/collectd#2478]
*   Version of collectd: 5.7.2
*   Operating system / distribution: Arch Linux x86_64

## Expected behavior

ping aur.archlinux.org without issues like the command line ping tool does.

## Actual behavior

No coresponding data collected, log always says
```
ping plugin: host aur.archlinux.org has not answered 10 PING requests, triggering resolve
```

Because it gets an IPv6 address.

I manually add a ping_setopt call in the source code to select AF_INET and it works well.

**Comment by octo** [comment]
Hi @lilydjwg,

thanks for reporting this. If I understand you correctly, you'd like a way to expose

```c
ping_setopt(obj, PING_OPT_AF, AF_INET);
```

via the configuration…?

Best regards,
—octo

**Comment by lilydjwg** [comment]
Yes. Or do you have a better way, like choosing the appropriate address to ping?
