### ISSUE TITLE
[RFC] Per-(write)-plugin threads

### ISSUE THREAD

**Issue by octo** [collectd/collectd#2486]
This issue is supposed to be used to brainstorm / design a change to the *write threads* so that there is one write thread per plugin (or one thread pool per plugin).

In the current implementation, there is a central queue in which all *value lists* are enqueued. Write threads dequeue *value lists* and call all registered write callbacks sequentially. The problem with this implementation is that one typical failure mode of write callbacks is to time out: many establish or use a network connection and when there is a problem it can take several seconds before the appropriate system calls return. All write threads are then stuck in the same write plugin, the queue stalls and eventually overflows and metrics are lost. (#2104)

Most write plugins use locks in fairly central locations, making large parts effectively single-threaded. As determined by @rpv-tomsk:

> Most of write plugins do not intended their write callback to be called from multiple threads and will lock parallel calls.
>
> These will lock and behave as single-threaded: 
>
> `network.c`: will lock at global `send_buffer_lock` (only one callback can be registered)
> `snmp_agent.c`: will lock at global `g_agent->lock` (only one callback can be registered)
> `write_prometheus.c`: will lock at global `metrics_lock` (only one callback can be registered).
>
> Partially locked:
>
> `rrdtool.c`: Global lock at `rrd_cache_insert` after data prepared and `stat()` called, only one callback registered - treat it as a single-threaded.
>
> These will lock and are single-threaded per callback by a fact:
>
> `write_http.c`: has a callback lock (multiple callbacks can be registered)
> `write_sensu.c`: has a callback lock (multiple callbacks can be registered)
> 
> Partially locked (prepare data then do locks) (per-callback lock, multiple callbacks can be registered):
> 
> `write_graphite.c`: format_graphite() then locked send 
> `write_mongodb.c`: wm_create_bson() then locked send 
> `write_redis.c`: Prepare data with format_values() and then do locked send 
> `write_riemann.c`: Prepare data then do locked send  
> `write_tsdb.c`: Prepare messages then do locked send (each message send protected by a cb lock) 
> `amqp.c`: Prepare data, then do locked publish 
> `mqtt.c`: Prepare data, then do locked publish
> 
> No locks:
> 
> `csv.c`: Allows calls from multiple threads to be processed without lock (single callback registered)
> `write_kafka.c`: Allows calls from multiple threads to be processed without lock (multiple callbacks can be registered)
> `write_log.c`: Allows calls from multiple threads to be processed without lock (single callback registered)
> `rrdcached.c`: Allows calls from multiple threads to be processed without lock (single callback registered)

**Comment by octo** [comment]
I the two benefits of this approach (that I can think of) are:

*   Slow write callbacks (difficult network conditions, for example) don't impact fast (local) writes. For example, when the *write_http plugin* is slow, some metrics might get dropped from the queue and the *csv plugin* would never see them despite having available capacity.
*   We could introduce a `DEFER` / "temporary failure" return value: if returned from a write callback, put the metric back to the head of the queue, do wait a bit (→ #2480) and try again. This would allow us to ensure that no values are ever *lost* due to network issues. This was previously not possible, because we didn't keep track of which plugin had seen a certain value and which didn't.

The main drawback is:

*   Each *value list* is copied *n* times, where *n* is the number of write callbacks. Worst case, this means increased memory usage due to each *value list* being enqueued multiple times. Under normal condition, this shouldn't be an issue though.

**Comment by rpv-tomsk** [comment]
>Each value list is copied n times, where n is the number of write callbacks. 

For that case mine proposal was to use chains and store a position in a write callback data.
But then we need to somehow calculate if element was processed by all required write plugins or not.
Chain elements may be of two types (related to this task) - targetted to be written to single plugin or to all plugins. For single plugin that will be easy. But for 'all plugins' ? We can use counter .... but then we need to prohibit? `list_write` changes... ???

**Comment by rpv-tomsk** [comment]
>We could introduce a DEFER / "temporary failure" return value: if returned from a write callback, put the metric *back to the head* of the queue

I think we need to limit queue size by expiry time / number of elements. Keeping metrics order will help in that case, right?

**Comment by rpv-tomsk** [comment]
>The drawbacks (I can think of) are:
>    Currently, plugins can just unlock and do (slow) I/O, safe in the knowledge that the other write threads will continue working while this thread is blocked. This can become a bottleneck with a single thread per plugin.

Of course, the new implementation should have the same behavior - the queue must be unlocked while write is performed by a write thread.

**Comment by octo** [comment]
> I think we need to limit queue size by expiry time / number of elements.

Agreed, the new implementation should keep the behavior controlled by `WriteQueueLimit{High,Low}`.

> the queue must be unlocked while write is performed by a write thread.

I was referring to locking inside the plugin: right now, many plugins add to a (locked) buffer. When the buffer is full, they copy the buffer, unlock the global buffer and then proceed to send out their copy (slow). Meanwhile, other write threads can start adding to the global buffer again. With only *one* write thread, sending and adding to the global buffer is no longer parallel, which *may* or *may not* be an issue.

**Comment by rpv-tomsk** [comment]
>Agreed, the new implementation should keep the behavior controlled by WriteQueueLimit{High,Low}.

The behaviour should differ.  Current implementation simple drops _new_ metrics while new implementation should drop an _old_ one.

**Comment by octo** [comment]
> new implementation *should* drop an old one

"should" as in "this would be the right thing to do" or as in "this is a consequence of your suggestion"?

Crazy idea:

When the queue is full, drop a *random* (uniformly distributed) entry from the queue. This way we would basically lower the granularity / frequency but keep a sample of metrics throughout the problematic period.

**Comment by rpv-tomsk** [comment]
:-) This is a good idea to think about!

**Comment by octo** [comment]
Yes, thanks for surfacing this!
