### ISSUE TITLE
error while loading python docker plugin

### ISSUE THREAD

**Issue by yogeshVU** [collectd/collectd#2487]
*   Version of collectd:
*   Operating system / distribution:

Docker version 17.06.2-ce, build cec0b72
collectd 5.7.2.623.gc870991, http://collectd.org/

Installation from git source.

Ubuntu 16.04

https://github.com/lebauce/docker-collectd-plugin/issues/43
## Expected behavior

(Description of the behavior / output that you expected)
Should load the plugin successfully

## Actual behavior

(Description of the behavior / output that you observed)
```/opt/collectd# ./sbin/collectd -t -C etc/conf.d/docker.conf 
plugin_load: plugin "python" successfully loaded.
python plugin: Error importing module "dockerplugin".
Unhandled python exception in importing module: SyntaxError: invalid syntax (dockerplugin.py, line 217)
python plugin: Found a configuration for the "dockerplugin" plugin, but the plugin isn't loaded or didn't register a configuration callback.
Error: Reading the config file failed!


```
## Steps to reproduce

*   step 1
Clone this in /usr/share/collectd/docker-collectd-plugin
: https://github.com/lebauce/docker-collectd-plugin

or this project : https://github.com/signalfx/docker-collectd-plugin

*   step 2
pip install -r requirements.txt

*   step 3
Create docker.conf

```
TypesDB "/usr/share/collectd/docker-collectd-plugin/dockerplugin.db"
LoadPlugin python

<Plugin python>
  ModulePath "/usr/share/collectd/docker-collectd-plugin"
  Import "dockerplugin"

  <Module dockerplugin>
    BaseURL "unix://var/run/docker.sock"
    Timeout 3
  </Module>
</Plugin>
```

* Step: 4
collectd -t -C docker.conf

**Comment by trenkel** [comment]
except Exception, e:
was bad style in python2 and therefore removed from python3. The correct syntax is
except Exception as e:
I suggest using that instead. I didn't look through the rest of the file if there is other python2 specific code that won't work with python2. If there is yo might want to simple run the code with python2 instead of python3.

**Comment by yogeshVU** [comment]
@trenkel thanks for pointing that out. 
>> If there is yo might want to simple run the code with python2 instead of python3.
How to run this in python2?

**Comment by yogeshVU** [comment]
@trenkel any thoughts? 
My current issue how to enable collectd to run the plugins which work with 2.7 version.
Will I need to recompile collectd with python2.7? if so how can one do that?

**Comment by yogeshVU** [comment]
Replying to my issue here.. 
I got it to compile collectd directly from source by enabling python2 flag. And my plugins python2 work again on the ubuntu 16.04
