### ISSUE TITLE
Feature request: Add GETBULK options to SNMP plugin

### ISSUE THREAD

**Issue by cvicente** [collectd/collectd#2495]
GETBULK operations significantly reduce the impact on the agent and perform much faster when retrieving large tables.

**Comment by rpv-tomsk** [comment]
Your proposal looks interesting.
But, just tried on equipment (network switch), accessible for me:

```
# snmpwalk -v2c -c public 192.168.0.100 IF-MIB::ifDescr
IF-MIB::ifDescr.1 = STRING: GbE_1
[.. cut ..]
IF-MIB::ifDescr.24 = STRING: GbE_24
IF-MIB::ifDescr.604 = STRING: Vlan1

# snmpbulkwalk -v2c -c public 192.168.0.100 IF-MIB::ifDescr
Timeout: No Response from 192.168.0.100
```
Did you tried to do similar tests on your equipment?
Is GETBULK _very_ actual for your setup?

At least, if implemented, this feature should be optional. 
But implementation will require much code refactoring.

---

If you familar with GETBULK, can you please explain `non-repeaters` and `max-repetitions` parameters?
How they work, with short examples, if possible? How should we use them in Collectd?

**Comment by mikec85** [comment]
I would really like this feature to get added as well.

**Comment by nward** [comment]
@rpv-tomsk these days it is very unusual for a device to not support GETBULK, GETBULK is very much a common tool, and is not specific to @cvicente's setup.

- `non-repeaters` is so you can request several single instances, and a table column in one request - i.e. you might request sysUpTime and then a series of IF-MIB columns.
- `max-repetitions` is to indicate how many responses you want, effectively this is used to keep the packets as large as possible but not over the MTU - SNMP response packets have no ACK mechanism.

I think initially, collectd could use this for tables. I don't see a huge value in it for non-table data.
This would be done by setting `non-repeaters` to 0 (which is the default in most command line tools, i.e. net-snmp etc.), and setting `max-repetitions` probably on a per-host basis, with a global setting, and default it to 10. If individual installations want to increase (or decrease) that they can, but the vast majority will not.

Of course, a per-host "supports GETBULK" parameter is important, too, in case there are very old implementations which do not support GETBULK yet.

**Comment by nward** [comment]
I'll note also that GETBULK can be significantly easier on some equipment - often, poorly implemented SNMP agents will not cache data from the hardware (or whatever) and will fetch the full data each request, and then return the specific data in the request. With GETBULK, the number of requests is reduced and so is the number of fetches of data from hardware.
