### ISSUE TITLE
collectd `lvm` plugin compilation fails

### ISSUE THREAD

**Issue by vmytnykx** [collectd/collectd#2500]
*   Version of collectd: master
*   Operating system / distribution: CentOS (centos-release-7-3.1611.el7.centos.x86_64)
*   Version of LVM2 (yum info lvm2-devel): Version - 2.02.166, Release - 1.el7_3.5
*   Changes that caused the issue: https://github.com/collectd/collectd/commit/0fd27c3d33f8729989b00df386cae5b14a34445d

## Expected behavior
 
Collectd master shouldn't fail during collectd compilation

## Actual behavior

```
  CC       src/lvm_la-lvm.lo
src/lvm.c:190:12: error: conflicting types for 'lvm_init'
 static int lvm_init(void) {
            ^
In file included from src/lvm.c:29:0:
/usr/include/lvm2app.h:262:7: note: previous declaration of 'lvm_init' was here
 lvm_t lvm_init(const char *system_dir);
       ^
make[1]: *** [src/lvm_la-lvm.lo] Error 1
```

## Steps to reproduce

*   git clone https://github.com/collectd/collectd.git
*   cd collectd
*   ./build.sh
*   ./configure
*   make

**Comment by vmytnykx** [comment]
Fixed by 2b8904eb81e3eae5e72f1f29e09277e0fef67a2e. Thanks @rpv-tomsk.

**Comment by rpv-tomsk** [comment]
Unfortunately that does not resolve failed CI tests...

**Comment by vmytnykx** [comment]
@rpv-tomsk, are those failed CI tests related to lvm2 plugin? On my machine your fix resolve lvm2 compilation issue.
