### ISSUE TITLE
Collectd-process reporting fault pages in floating points

### ISSUE THREAD

**Issue by StLuke** [collectd/collectd#2508]
*   Version of collectd: collectd-5.7.2-1.el7.x86_64
*   Operating system / distribution: CentOS Linux release 7.4.1708 (Core) 

## Expected behaviour
Fault pages should be reported in decimal point instead of/in addition to floating point.

## Actual behaviour
Currently, we are reporting floating point value for missing memory pages in ps_pagefaults. Not sure how do we acquire this but it seems to me this should be in decimal numbers. Or we need an update of documentation of what does this value represent.

"The number of major and minor page faults."
https://collectd.org/wiki/index.php/Plugin:Processes

## Steps to reproduce

*   step 1
Check collectd stats for specific process, and check ps_pagefaults

**Comment by rpv-tomsk** [comment]
The reported metric is a rate of 'page is missing' events, not the 'raw' value from `/proc/`. 
So, floating point values are normal there.

Wiki page was updated, thanks for reporting!

**Comment by StLuke** [comment]
Can you please explain "rate of 'page is missing' events"?
missing/all, missing/minute what is the formula to count the rate?

**Comment by rpv-tomsk** [comment]
Events per second.
`New reading` - `Previous reading` /  `time delta`.

**Comment by octo** [comment]
@StLuke the kernel reports the total number of page faults since it was booted. That number is fairly meaningless in itself. By calculating the *rate* at which the counter increases (page faults per second) you get a meaningful metric. Look for "DERIVE" in our wiki for more in depth information.

Best regards,
—octo
