### ISSUE TITLE
[RFE] Add collection of IOPS per mount point

### ISSUE THREAD

**Issue by sradco** [collectd/collectd#2509]
*   Version of collectd: 5.7.2
*   Operating system / distribution: centos 7.3

Currently disk plugin collects performance statistics of hard-disks and, where supported, partitions.
We would like to be able to get IOPS data per mount point.

**Comment by rpv-tomsk** [comment]
Hi!

Please, describe your use case more detailed.

**Comment by sradco** [comment]
Hi,

We attach/mount storage devices and would like to get IOPs statistics about them ,in a slimier way to the disk plugin statistics.

**Comment by octo** [comment]
I'm not sure I understand the request. Do you want the metrics the *disk plugin* already exports, but instead reporting it by device name, report it by mount point?

Or are you looking for metrics that are not yet available? In that case, do you know where we could read those metrics?

Best regards,
—octo

**Comment by sradco** [comment]
Disk plugin provides, the statistics for local hard-disks and, where supported, partitions. 

When there are mounted disks we would like to be able to get the same statistics that are available for the local disks, for the mounted disks as well - io_time, weighted_io_time, pending_operations

**Comment by rpv-tomsk** [comment]
How did you differ local and non-local disks?
IMHO, there is no such difference.

Each disk initially is a is a block device (for which OS kernel provides statistics) and only then its filesystem (which contained in block device data) can be mounted. 
Block device also can be used without mounting - at RAID, LVM, as block device for virtual machine and so on. 

So, there is no difference between local and non-local "disks".

**Comment by sradco** [comment]
Hi, Do you think this option makes sense? @rpv-tomsk

**Comment by rpv-tomsk** [comment]
>Is it possible to add an option to concatenate the mount point to the disk name?

Can you describe such algo in details? How such option should work?
Or are you trying to ask me the same questions?

**Comment by rpv-tomsk** [comment]
On mine systems, I use LVM and mountpoint name corellates with LVM volume name.
So, this case is solved by use of LVM.

If use of plain partitions, then this maybe more reasonable.
This is possible to implement such option.

To get this, we need to iterate through mountpoints and compare block device names for each block device. When found, we can replace reported instance name.

But disk plugin is complex, it will be hard to implement such option for each supported OS (Solaris, AIX, FreeBSD), not only Linux. 

Also, technically, one block device can be mounted several times.
Also, block device name from mountpoint stats can differ from name from disk stats. 

All these (and others too) problems needs to be solved when implementing such option.

Example:

```
# cat /proc/mounts |grep var
/dev/mapper/vg-var /var ext3 rw,relatime,errors=continue,user_xattr,acl,barrier=1,data=ordered 0 0
# ls -l /dev/mapper/vg-var
lrwxrwxrwx 1 root root 7 Apr 11 05:17 /dev/mapper/vg-var -> ../dm-1
# cat /proc/diskstats |grep dm-1
 253       1 dm-1 523933 0 80404682 252120 23272294 0 186178352 1109879756 0 739664 1110155708
```

So compare does not looks to be simple.
