### ISSUE TITLE
configure does not report missing flex binary

### ISSUE THREAD

**Issue by trustchk** [collectd/collectd#2515]
*   Version of collectd: git master
*   Operating system / distribution: IBM AIX as well as Gentoo Linux

## Expected behavior

configure reports missing flex tool

## Actual behavior

LEX gets defined as ":", which is the bash Null command. scanner.c cannot be generated during make as ylwrap won't produce scanner.c out of scanner.l as ":" won't do anything useful in this case. It produces a call to ylwrap like this:
```bash
 ./build-aux/ylwrap src/liboconfig/scanner.l .c src/liboconfig/scanner.c -- :
```

## Steps to reproduce
* check out master
* Either move `/usr/bin/flex` or do not install it in the first place
* run configure
* configure runs successfully if bison is installed, but defines LEX as ":"
* make fails when trying to compile scanner.c as it has not been generated.

This does not affect releases, the release tarball seems to contain a pre-generated `scanner.c` (at least in 5.7.2)

**Comment by ffontaine** [comment]
This is now a real issue as since version 5.9.1, archive does not have a pre-generated `scanner.c`.
Some buildroot autobuilders fail on:
```

riscv64-linux-gcc.br_real: error: ./src/liboconfig/scanner.c: No such file or directory
riscv64-linux-gcc.br_real: fatal error: no input files
```

See http://autobuild.buildroot.org/results/cd5/cd5deacbe6f4f97aa0bbc8040ac9aa7860ceaa6e/build-end.log

**Comment by ffontaine** [comment]
OK thanks, I'll use it.

For information, I tried to get the 5.9.2 tarball from https://collectd.org/files/collectd-5.9.2.tar.bz2 but I got an error when running bzcat:
`collectd-5.9.2.tar.bz2 is not a bzip2 file.`

file command displays:
`collectd-5.9.2.tar.bz2: XZ compressed data`

Perhaps the file on collectd.org should be updated or removed if the official release is now given on github.

**Comment by mrunge** [comment]
Right. Unfortunately, I don't have any write permissions there, the file is simply wrong, and tbh, I don't know how it landed there. 

I understand, this is confusing and you can not know this. Basically, you ran into https://github.com/collectd/collectd/issues/3293 , which should be fixed right now and should also be avoided in the future. I'm sorry about that.

**Comment by ffontaine** [comment]
OK, thanks for your help :-)

**Comment by rubenk** [comment]
@octo can you please give Matthias access to collectd.org?

**Comment by mrunge** [comment]
From collectd.org/files the files are linked to external storage, e.g. to https://storage.googleapis.com/collectd-tarballs/collectd-5.9.2.tar.bz2

**Comment by rubenk** [comment]
It could be that our CI has put them there.

**Comment by AdamWill** [comment]
https://collectd.org/files/collectd-5.9.2.tar.bz2 is not bootstrapped. It does not container a `scanner.c`.
