### ISSUE TITLE
Virt-module and oVirt-4.1.6: virt plugin: Array index out of bounds: tag_index = 8

### ISSUE THREAD

**Issue by Poltsi** [collectd/collectd#2532]
*   Version of collectd: -5.7.2-1.el7.x86_64 (from RPM)
*   Operating system / distribution: CentOS7.4

## Expected behavior
No error regarding array index being out of bounds

## Actual behavior
Getting the following errors in /var/log/messages:

> Nov 11 15:24:12 hypervisor collectd[12925]: virt plugin: Array index out of bounds: tag_index = 8
> Nov 11 15:24:12 hypervisor collectd[12925]: virt plugin: Array index out of bounds: tag_index = 9
> Nov 11 15:24:12 hypervisor collectd[12925]: virt plugin: Array index out of bounds: tag_index = 8
> Nov 11 15:24:22 hypervisor collectd[12925]: virt plugin: Array index out of bounds: tag_index = 8
> Nov 11 15:24:22 hypervisor collectd[12925]: virt plugin: Array index out of bounds: tag_index = 9
> Nov 11 15:24:22 hypervisor collectd[12925]: virt plugin: Array index out of bounds: tag_index = 8

## Steps to reproduce
*  Install  oVirt and configure a couple of VMs on it
*   Install collectd  and collectd-virt from centos repo
*   Set up the virt-plugin with the following configuration:

> LoadPlugin libvirt
> 
> <Plugin "virt">
>         Connection "qemu:///system"
>         RefreshInterval 60
>         HostnameFormat "name"
> </Plugin>

*   Observe the output in /var/log/messages

**Comment by octo** [comment]
Hi @Poltsi,

thanks for reporting this. Which version of *libvirt* are you using?

Best regards, —octo

**Comment by Poltsi** [comment]
Name        : libvirt-libs
Version     : 3.2.0
Release     : 14.el7_4.3

This is the one installed by the oVirt

**Comment by octo** [comment]
This problem will be fixed in the upcoming 5.8 release. Details are in #2168.

Best regards,
—octo
