### ISSUE TITLE
IPMI is not installing it's lib. for impi.  missing ipmi.so and smart.so

### ISSUE THREAD

**Issue by Chiragvyas678** [collectd/collectd#2557]
- Version of collectd: 5.7.1-2.el7
- it is reproducible with collectd-5.7.1-2.el7.x86_64 from EPEL

Operating system / distribution:
CentOS 7

## Expected behavior

(Description of the behavior / output that you expected)

## Actual behavior
Nov 20 05:25:59 mnl-os1-c1n1.ctlsdn.io systemd[1]: Failed to start Collectd statistics daemon.
Nov 20 05:25:59 mnl-os1-c1n1.ctlsdn.io systemd[1]: Unit collectd.service entered failed state.
Nov 20 05:25:59 mnl-os1-c1n1.ctlsdn.io systemd[1]: collectd.service failed.
Nov 20 05:25:59 mnl-os1-c1n1.ctlsdn.io systemd[1]: collectd.service holdoff time over, scheduling restart.
Nov 20 05:25:59 mnl-os1-c1n1.ctlsdn.io systemd[1]: start request repeated too quickly for collectd.service
Nov 20 05:25:59 mnl-os1-c1n1.ctlsdn.io systemd[1]: Failed to start Collectd statistics daemon.
Nov 20 05:25:59 mnl-os1-c1n1.ctlsdn.io systemd[1]: Unit collectd.service entered failed state.
Nov 20 05:25:59 mnl-os1-c1n1.ctlsdn.io systemd[1]: collectd.service failed.

**Comment by rpv-tomsk** [comment]
As I understand, these packages are build by a third-party, so you should adress this issue to them.
As a solution, you can try to use packages, which are stored in Collect project repos.
