### ISSUE TITLE
curl_json plugin: curl_easy_perform failed with status 23: Failed writing body

### ISSUE THREAD

**Issue by XavM** [collectd/collectd#256]
When using curl_json plugin and the respons received is "big", the following error occures : 

  curl_json plugin: yajl_parse failed: parse error: premature EOF#012
  curl_json plugin: curl_easy_perform failed with status 23: Failed writing body

I guess it is the same problem as the one reported for the Apache plugin long ago : "Failed writing body" 
Please see
  http://collectd.org/faq.shtml
and
  collectd commit 5c3efb12ed19f99017b8b13943d4a983de040050

May be the buffer size should be increased dynamically for curl_json as well.

Being pretty bad at c, I have not been able to locate the portion of code that relates to this response buffer size.
Being able make it bigger (even statically in source and then re compile) would be great for us -> Any clue any one ?

(The purpose for us is to monitor couchbase metrics that are exposed thru REST but that are "pretty" verbose)

Regards

**Comment by christf** [comment]
I am seeing the same symptom on colectd 5.1
