### ISSUE TITLE
No easy way to configure per python module interval.

### ISSUE THREAD

**Issue by traylenator** [collectd/collectd#2571]
*   Version of collectd: 5.7.1
*   Operating system / distribution: CentOS 7

## Expected behavior
While an interval can be specified the whole of python plugin.

```apache
<LoadPlugin "python">
    Interval 60
    Globals true
</LoadPlugin>
```
It is not possible to specify an interval for a individual python plugin, something like

```apache
<LoadPlugin "python">
    Interval 60
    Globals true
   Import ModuleA
  Import ModuleB
   <Module "ModuleA">
     Interval 22
   </Module>
   <Module "ModuleB">
     Interval 44
   </Module
</LoadPlugin>
```

(Description of the behavior / output that you expected)

That ModuleA and ModuleB would read at their configured intervals.

## Actual behavior

Both run with the python module interval.

It is possible in a python module to configure an interval with the callback.

```python
collectd.register_config(config)
collectd.register_read(read,22)
```
but there is no way at this point to access the configuration so only (easy) option is to hard code 
the interval.

There is some background in  https://github.com/collectd/collectd/issues/717 but that is a very distinct ticket and correctly closed.

**Comment by larsks** [comment]
> but there is no way at this point to access the configuration so only (easy) option is to hard code

Sure there is.  You just call `collectd.register_read` from inside your config callback.  E.g:

```python
    def config_func(config):
        interval = default_interval
        for node in config.children:
            key = node.key.lower()
            val = node.values[0]

            if key.lower() == 'interval':
                interval = val

        collectd.register_read(self.read_func, interval)

    collectd.register_config(config_func)
```

This should do exactly what you want.

**Comment by traylenator** [comment]
Hi @larsks 
Thanks. That does indeed do the job and is clearly super easy.
