### ISSUE TITLE
collectd -T doesn't return with ovs_events and ovs_stats plugin enabled

### ISSUE THREAD

**Issue by mrunge** [collectd/collectd#2574]
*   Version of collectd: 5.8
*   Operating system / distribution: RHEL 7.4

I installed the ovs_events and ovs_stats plugin. While tweaking config, I realized, collectd -T doesn't return any more, and you have to kill -9. It happens with any of these plugins enabled.

For reference, I have a repository with collectd 5.8 builds on RHEL 7.4 and debug enabled here: http://www.matthias-runge.de/fedora/collectd/

**Comment by maryamtahhan** [comment]
Hi @mrunge 
Can you please add more details, configurations/steps to reproduce/version of OVS you are using and whether vanilla or OVS with DPDK... 

Are you configuring or only loading the ovs_events and ovs_stats plugin?

These plugins don't register a read function unless configuration is called first... 

I've been trying to reproduce on a CentOS setup with no joy... with the plugins configured everything seems to run fine...

**Comment by mrunge** [comment]
@maryamtahhan I'm using with ovs-2.6.1, not using dpdk 

`
LoadPlugin ovs_events

<Plugin "ovs_events">
    Socket "/var/run/openvswitch/db.sock"
    SendNotification true
    DispatchValues false
</Plugin>

LoadPlugin ovs_stats

<Plugin "ovs_stats">
    Socket "/var/run/openvswitch/db.sock"
</Plugin>
`

**Comment by mrunge** [comment]
Sigh, the editor swallowed half of it.

http://paste.openstack.org/show/627588/

**Comment by rubenk** [comment]
@mrunge if you put code between triple backticks it formats correctly.

**Comment by maryamtahhan** [comment]
Thanks @mrunge - I managed to reproduce... looking it to this

**Comment by vmytnykx** [comment]
Hi @mrunge, the fix for this issue has been merged already so I think this ticket can be closed.

Could you please checkout the latest 5.8 branch and verify the issue?

Thanks and Regards,
Volodymyr

**Comment by mrunge** [comment]
That fixes the issue.

**Comment by mrunge** [comment]
Thank you!
