### ISSUE TITLE
redhat Specfile missing dependencies

### ISSUE THREAD

**Issue by dothebart** [collectd/collectd#2601]
*   Version of collectd: 5.8.0
*   Operating system / distribution:
Centos 7

bison and flex are missing from the dependencies in the spec file in 
`contrib/redhat/collectd.spec`

**Comment by rubenk** [comment]
Bison and Flex are only needed if you build from git (same for autoconf and automake), and it is expected developers have them installed. The spec file uses a tarball.

**Comment by dothebart** [comment]
ah, ok. Was trying to build in a docker container; as the target was not my regular host os. 
I think I called `build.sh` on my debian host, and afterwards it complained in that autofoo wasn't working right inside it.

I would expect that step to already do all that, and not the regular build break during `make`.

**Comment by rubenk** [comment]
sorry, I don't understand what you mean with "afterwards it complained in that autofoo wasn't working right inside it.". If you're building the rpm from a tarball (the only supported way), autotools are not involved at all.

**Comment by dothebart** [comment]
I mounted the git dir into the container. Bootstrapped that dir, created the tarball, copied the spec file and the tar.bz2 to the folders rpmbuild demands, and compiled. (spec file demands a version older than 5.8 btw - something missing in the release tagging? ;-) 

It also seemed to create a revision name `5.8+` which broke the build again.

**Comment by rubenk** [comment]
So did you have bison and flex installed in the container?

**Comment by dothebart** [comment]
I did after it aborted the rpm build

**Comment by rubenk** [comment]
./configure should abort if bison is missing during the creation of the tarball, but only if parser.c does not exist in the source tree. If parser.c does exist, then bison is not needed.

Can you share the actual commands you ran and the output?

**Comment by dothebart** [comment]
hm, no, don't have it anymore. 
Shouldn't configure just be run on the target? not during the bootstrap phase for a distribution?

**Comment by rubenk** [comment]
You need to have ran ./configure otherwise you wouldn't have been able to create the tarball.

**Comment by rubenk** [comment]
One thing I like to point out is that installing bison and flex is documented in the README.

Sorry, don't think we can do more here without specific logs showing failures.

**Comment by dothebart** [comment]
ok, wasn't clear to me that one would need to run configure once for bootstrapping the tarball. 
In arangodb we also put the bison generated files into git and have a .gitignore for them.
Once you use the release scripts, it gets re-built force-added, and commited - another approach to enable users to build from git without having to install bison etc.

**Comment by rubenk** [comment]
> ok, wasn't clear to me that one would need to run configure once for bootstrapping the tarball.

How else would you create it? There is no Makefile before you run ./configure.

**Comment by dothebart** [comment]
I wasn't aware that it was needed in first place. 

As noted, https://github.com/arangodb/arangodb/blob/devel/arangod/Aql/grammar.y and https://github.com/arangodb/arangodb/blob/devel/arangod/Aql/grammar.cpp are kept in the arangodb source to circumvent this problem; I guess the collectd bison files aren't altered that frequently either? So maybe keeping the autogenerated files in git could be an option too.

**Comment by dothebart** [comment]
oh, and if not keep it in git, `./build.sh` could also invoke bson?

**Comment by rubenk** [comment]
> I wasn't aware that it was needed in first place.
That the tarball was needed? How else would you build the rpm?

This is documented in the spec file by the way.

I don't think requiring developers to install the necessary tools is much to ask, and I'm hesitant to add all kinds of checks for this, or workarounds for missing development tools.
