### ISSUE TITLE
out of source compile doesn't work

### ISSUE THREAD

**Issue by dothebart** [collectd/collectd#2602]
*   Version of collectd: latest master
*   Operating system / distribution: debian stretch

    mkdir build
    cd build
    ../configure 
    .....
    make 
    ....
    ../src/liboconfig/parser.y:30:21: fatal error: oconfig.h: No such file or directory

can be fixed by 

    build# cd src/liboconfig/
    ln -s ../../../src/liboconfig/*.h . 

so most probably the real solution would be to add `-I ${srcdir}/src/liboconfig/` 

The next step missing is the generation of the environment for the perl bindings:

    cd buildperl && /usr/bin/perl Makefile.PL PREFIX=NONE
    /bin/bash: line 0: cd: buildperl: No such file or directory

which can be fixed like this:

    build$ mkdir buildperl
    build/buildperl$ ln -s ../../bindings/perl/Makefile.PL .

**Comment by octo** [comment]
Thanks @dothebart, should be fixed soon :)

**Comment by rubenk** [comment]
Very strange that our CI doesn't catch this. It should, because it does out of tree builds by default (`make dist`).

I'd like to understand why the fix is necessary. Did we regress somewhere?
