### ISSUE TITLE
virt plugin can't show cpu_util

### ISSUE THREAD

**Issue by yusong0926** [collectd/collectd#2615]
*   Version of collectd: master
*   Operating system / distribution: ubuntu 16.04

run collectd as root, I have virt plugin enabled. 
I am not sure if it ran as expected based on the output, but I can't get cpu_util.

my configuration for the virt plugin:

```
LoadPlugin virt
<Plugin virt>
  Connection "qemu:///system"
  RefreshInterval 60
  PluginInstanceFormat name
  ExtraStats "cpu_util"
</Plugin>
```

the error msg in the log:
```
Dec 13 00:16:22 ubuntu-xenial collectd[24262]: libvirt: QEMU Driver error : Requested operation is not valid: cpu affinity is not supported
Dec 13 00:16:22 ubuntu-xenial collectd[24262]: virt plugin: virDomainGetVcpus failed with status -1.
Dec 13 00:16:22 ubuntu-xenial collectd[24262]: virt: Failed to get vcpu stats
```

metrics related to vcpu received from virt plugin of collectd:
```
[{"values":[0.075],"dstypes":["gauge"],"dsnames":["value"],"time":1513124297.164,"interval":10.000,"host":"8999d0a0-4181-4c55-993d-7d478d3cd183","plugin":"virt","plugin_instance":"instance-00000001","type":"percent","type_instance":"virt_cpu_total"}]

[{"values":[2999319.29417029],"dstypes":["derive"],"dsnames":["value"],"time":1513124297.164,"interval":10.000,"host":"8999d0a0-4181-4c55-993d-7d478d3cd183","plugin":"virt","plugin_instance":"instance-00000001","type":"virt_cpu_total","type_instance":""}]
```

```
root@ubuntu-xenial:~# virsh cpu-stats instance-00000001
CPU0:
	cpu_time             5.847732959 seconds
CPU1:
	cpu_time             3.464152462 seconds
CPU2:
	cpu_time             7.866690229 seconds
CPU3:
	cpu_time             2.601652726 seconds
Total:
	cpu_time            19.780228376 seconds
	user_time           16.040000000 seconds
	system_time          0.800000000 seconds
```

**Comment by mmozejkx** [comment]
Hi,
Could you please provide full collectd config and XML config for VM?
It seems like some improper config

**Comment by yusong0926** [comment]
LoadPlugin syslog
LoadPlugin cpu
LoadPlugin memory
LoadPlugin network
LoadPlugin virt
LoadPlugin write_kafka
<Plugin network>
        Server "ff18::efc0:4a42" "25826"
        <Server "239.192.74.66" "25826">
        </Server>
</Plugin>
<Plugin virt>
  Connection "qemu:///system"
  RefreshInterval 60
  HostnameFormat uuid
  PluginInstanceFormat name
  ExtraStats "cpu_util"
</Plugin>
<Plugin write_kafka>
  Property "metadata.broker.list" "localhost:9092"
  <Topic "collectd">
    Format JSON
  </Topic>
</Plugin>

**Comment by yusong0926** [comment]
```
<!--
WARNING: THIS IS AN AUTO-GENERATED FILE. CHANGES TO IT ARE LIKELY TO BE
OVERWRITTEN AND LOST. Changes to this xml configuration should be made using:
  virsh edit instance-00000001
or other application using the libvirt API.
-->

<domain type='qemu'>
  <name>instance-00000001</name>
  <uuid>8999d0a0-4181-4c55-993d-7d478d3cd183</uuid>
  <metadata>
    <nova:instance xmlns:nova="http://openstack.org/xmlns/libvirt/nova/1.0">
      <nova:package version="16.0.4"/>
      <nova:name>test_vm</nova:name>
      <nova:creationTime>2017-12-12 23:36:39</nova:creationTime>
      <nova:flavor name="m1.tiny">
        <nova:memory>512</nova:memory>
        <nova:disk>1</nova:disk>
        <nova:swap>0</nova:swap>
        <nova:ephemeral>0</nova:ephemeral>
        <nova:vcpus>1</nova:vcpus>
      </nova:flavor>
      <nova:owner>
        <nova:user uuid="91274c4715b042008225eec074e2ba45">admin</nova:user>
        <nova:project uuid="12e3d6a5a0f343f4ba0e3704e478f50d">demo</nova:project>
      </nova:owner>
    </nova:instance>
  </metadata>
  <memory unit='KiB'>524288</memory>
  <currentMemory unit='KiB'>524288</currentMemory>
  <vcpu placement='static'>1</vcpu>
  <cputune>
    <shares>1024</shares>
  </cputune>
  <sysinfo type='smbios'>
    <system>
      <entry name='manufacturer'>OpenStack Foundation</entry>
      <entry name='product'>OpenStack Nova</entry>
      <entry name='version'>16.0.4</entry>
      <entry name='serial'>883e680f-836b-4aec-9160-577359566d97</entry>
      <entry name='uuid'>8999d0a0-4181-4c55-993d-7d478d3cd183</entry>
      <entry name='family'>Virtual Machine</entry>
    </system>
  </sysinfo>
  <os>
    <type arch='x86_64' machine='pc-i440fx-zesty'>hvm</type>
    <boot dev='hd'/>
    <smbios mode='sysinfo'/>
  </os>
  <features>
    <acpi/>
    <apic/>
  </features>
  <cpu>
    <topology sockets='1' cores='1' threads='1'/>
  </cpu>
  <clock offset='utc'/>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>destroy</on_crash>
  <devices>
    <emulator>/usr/bin/qemu-system-x86_64</emulator>
    <disk type='block' device='disk'>
      <driver name='qemu' type='raw' cache='none' io='native'/>
      <source dev='/dev/sdc'/>
      <target dev='vda' bus='virtio'/>
      <serial>624018fe-2f1f-40cb-936d-6bcd5b83e7d3</serial>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x04' function='0x0'/>
    </disk>
    <controller type='usb' index='0' model='piix3-uhci'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x01' function='0x2'/>
    </controller>
    <controller type='pci' index='0' model='pci-root'/>
    <interface type='bridge'>
      <mac address='fa:16:3e:71:c1:6f'/>
      <source bridge='qbrbad97b9d-f7'/>
      <target dev='tapbad97b9d-f7'/>
      <model type='virtio'/>
      <driver name='qemu'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x0'/>
    </interface>
    <serial type='pty'>
      <log file='/opt/stack/data/nova/instances/8999d0a0-4181-4c55-993d-7d478d3cd183/console.log' append='off'/>
      <target port='0'/>
    </serial>
    <console type='pty'>
      <log file='/opt/stack/data/nova/instances/8999d0a0-4181-4c55-993d-7d478d3cd183/console.log' append='off'/>
      <target type='serial' port='0'/>
    </console>
    <input type='mouse' bus='ps2'/>
    <input type='keyboard' bus='ps2'/>
    <graphics type='vnc' port='-1' autoport='yes' listen='127.0.0.1' keymap='en-us'>
      <listen type='address' address='127.0.0.1'/>
    </graphics>
    <video>
      <model type='cirrus' vram='16384' heads='1' primary='yes'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x0'/>
    </video>
    <memballoon model='virtio'>
      <stats period='10'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x0'/>
    </memballoon>
  </devices>
</domain>    
```

**Comment by yusong0926** [comment]
@mmozejkx thanks for the reply. The vm is created by openstack(devstack in a vagrant vm). The collectd is running on the openstack host vm. The xml is automatically generated, which I found at /etc/libvirt/qemu/instance-00000001.xml. Do I still need manually create domain based on this xml?

**Comment by yusong0926** [comment]
@mmozejkx 
I have seen the following steps of instructions to create domain. But I thought I already can see the domain, so maybe I don't need those instructions to setup virt.
ubuntu@ubuntu-xenial:~$ sudo virsh list
 Id    Name                           State
----------------------------------------------------
 1     instance-00000001              running


Create domain, based on created XML file:

$ virsh define DOMAIN_CFG_FILE.xml
Start domain:

$ virsh start DOMAIN_NAME
Check if domain is running:

$ virsh list
Check list of available Performance monitoring events and their settings:

$ virsh perf DOMAIN_NAME
Enable or disable Performance monitoring events for domain:

$ virsh perf DOMAIN_NAME [--enable | --disable] EVENT_NAME --live

**Comment by yusong0926** [comment]
I guess the error messages are related to the QEMU. cpu affinity and virDomainGerVcpus might only support for kvm.

the error msg in the log:
Dec 13 00:16:22 ubuntu-xenial collectd[24262]: libvirt: QEMU Driver error : Requested operation is not valid: cpu affinity is not supported
Dec 13 00:16:22 ubuntu-xenial collectd[24262]: virt plugin: virDomainGetVcpus failed with status -1.
Dec 13 00:16:22 ubuntu-xenial collectd[24262]: virt: Failed to get vcpu stats

**Comment by mmozejkx** [comment]
If you see your VM in virsh list --all it means that VM has already been created.
Before enabling any of ExtraStats please ensure that you have it also enabled by virsh perf --enable.
You can also check your QEMU version according to [https://libvirt.org/hvsupport.html](https://libvirt.org/hvsupport.html)

**Comment by maryamtahhan** [comment]
I agree with @mmozejkx What version of libvirt are you using? there's a handy table that maps libvirt stats features available @ http://docs.opnfv.org/en/stable-euphrates/submodules/barometer/docs/release/userguide/feature.userguide.html#virt-plugin

**Comment by mmozejkx** [comment]
This issue is also mentioned here: [https://bugs.launchpad.net/nova/+bug/1691178](https://bugs.launchpad.net/nova/+bug/1691178)
They say that QEMU with TCG does not support cpu affinity
