### ISSUE TITLE
SNMP plugin needs a new schema

### ISSUE THREAD

**Issue by yellowpattern** [collectd/collectd#2636]
*   Version of collectd: 5.5.3
*   Operating system / distribution: CentOS 6

Sometimes it is possible to collect interface statistics using SNMP, in other instances it is done with collectd. Unfortunately the two methods do not present statistics in an aligned name space. To fix this, the SNMP plugin needs to be updated.

In the SNMP configuration, we can setup collecting octet counters like this:

    <Data "Octets">
        Table true
        Type "if_octets"
        #InstancePrefix "octets"
        Instance "MIBNAME::portName"
        Values "MIBNAME::ifInOctets" "MIBNAME::ifOutOctets"
    </Data>

What actually happens is that the SNMP plugin applies the "Instance" name to the "type_instance" field rather than the "instance" field.

What I'd like to suggest is the addition of a new per-Data boolean option "NewSchema" that when set to true, causes collectd to use "instance" rather than "type_instance", will cause "InstancePrefix" to be ignored and add a new configuration option, "TypeInstance" that allows the "type_instance" field to be set.

The goal here is to make it easier to re-use queries and graphs between interface and SNMP statistics. The "type_instance" change is to introduce another 'variable' to use with grafana when doing "GROUP BY".

**Comment by faxm0dem** [comment]
we should probably add support for metadata to snmp

**Comment by rpv-tomsk** [comment]
We can allow to override reported `plugin` value on per-Data basis,
and can add an option `PluginInstance` in addition to existing `Instance`.

All this allow to unify metrics from `interface` and `snmp` plugins.

**Comment by rpv-tomsk** [comment]
This feature was implemented. If you still interested, you can do tests.
Please inform us if you will do this, we will wait for feedback then.
