### ISSUE TITLE
SNMP plugin needs to be able to ignore parts of the MIB table

### ISSUE THREAD

**Issue by yellowpattern** [collectd/collectd#2637]
*   Version of collectd: 5.5.3
*   Operating system / distribution: CentOS 6

When using the SNMP plugin to query a switch for statistics, the switch will quite happily return information ... for all of the interfaces in its MIB. Not all of the interfaces in the MIB will be available. For example, where there are various models of a switch, the MIB may be the same for all models even though some models only have 24 ports and other 96. The end result is that collectd reports a lot of information that is not only not useful not undesired. One switch that I've got has 54 ports but the IF-MID::ifNumber table has 467 entries. Problem.

In such situations there is typically another "table" in the MIB that makes available information about a port's status and this can include "notPresent" - the IF-MIB::ifOperStatus table is a good example of this.

What I'd like to be able to do is have the SNMP plugin query the "IF-MIB::ifOperStatus" table first and have it only return data for interfaces in the "up(1)" or "down(2)" states. FYI, the full list of states for ifOperStatus are: (1) up (2) down (3) testing (4) unknown (5) dormant (6) notPresent.

The mechanism that I think would be useful to see is something like this:

Filter "IF-MIB::ifOperStatus"
FilterType "Integer"
FilterAccept 1, 2

- declare the table that an administrator wishes to use as the "Filter" for what to accept/reject
- indicate what type data will be present after FilterAccept with a view to instructing collectd on how to compare elements in the table with the accept list.

**Comment by rpv-tomsk** [comment]
Sounds reasonable.

>indicate what type data will be present after FilterAccept with a view to instructing collectd on how to compare elements in the table with the accept list.

quite hard to understand (translate) this phrase clearly...

What `FilterType` option values should be supported? Currently I see only `Integer` and `String` values for it.

**Comment by rpv-tomsk** [comment]
The feature was implemented, look into #2819 if interested.

Thanks.

**Comment by Hipska** [comment]
I just saw #2819 referenced from the release changelog and I was wondering if it could be possible to let `FilterAccept` also be a RegEx. This would be useful as well when integer is translated or when the field is a string.
