### ISSUE TITLE
segfault in ceph module

### ISSUE THREAD

**Issue by f1-outsourcing** [collectd/collectd#2639]
Dec 31 21:58:15 c01 collectd: plugin_load: plugin "ceph" successfully loaded.
Dec 31 21:58:15 c01 kernel: reader#2[4534]: segfault at 0 ip 00007f75d3ac28dd sp 00007f75c9ffa6b0 error 4 in ceph.so[7f75d3ac1000+5000]
Dec 31 21:58:15 c01 collectd: plugin_load: plugin "ceph" successfully loaded.
Dec 31 21:58:15 c01 kernel: reader#2[4534]: segfault at 0 ip 00007f75d3ac28dd sp 00007f75c9ffa6b0 error 4 in ceph.so[7f75d3ac1000+5000]
Dec 31 21:58:15 c01 collectd: plugin_load: plugin "ceph" successfully loaded.
Dec 31 21:58:15 c01 collectd: plugin_load: plugin "ceph" successfully loaded.
Dec 31 21:58:15 c01 kernel: reader#3[4549]: segfault at 0 ip 00007f52f33688dd sp 00007f52e97f96b0 error 4 in ceph.so[7f52f3367000+5000]
Dec 31 21:58:15 c01 kernel: reader#3[4549]: segfault at 0 ip 00007f52f33688dd sp 00007f52e97f96b0 error 4 in ceph.so[7f52f3367000+5000]

[x@c01 collectd.d]# cat ceph.conf

LoadPlugin ceph

<Plugin ceph>
  <Daemon "osd.3">
    SocketPath "/var/run/ceph/ceph-osd.3.asok"
  </Daemon>
</Plugin>

[x@c01 collectd.d]# rpm -qa | grep collect
collectd-5.8.0-1.el7.x86_64
collectd-ipmi-5.8.0-1.el7.x86_64
libcollection-0.6.2-27.el7.x86_64
collectd-ceph-5.8.0-1.el7.x86_64

**Comment by rubenk** [comment]
This was fixed in https://github.com/collectd/collectd/commit/de05fb53fad6bc998f585b704ca0caeadc14a035

**Comment by f1-outsourcing** [comment]
i have asked on the irc and bugzilla.redhat.com to update the packages

**Comment by mrunge** [comment]
you may be able to pull the package from centos-opstools SIG. The package been fixed already.

@rubenk CentOS opstools stuff is available at https://github.com/centos-opstools/collectd and I can offer to update the package in EPEL.

The compiled binaries are available from http://mirror.centos.org/centos/7/opstools/x86_64/perfmon/
or if you yum install centos-release-opstools
