### ISSUE TITLE
Recommendation for add validation for certain variable in fopen()

### ISSUE THREAD

**Issue by happyhappiness** [collectd/collectd#2644]
Our team researches on consistent update of Collectd during evolution. And we have figured out several spots that may be missed. 

By mining historical patches, we suggest that log_file, the argument of fopen() should be validated before printing out in logging statement which is under the control dependence wherereturn value of fopen() equals to NULL. One example for recommendation and corresponding patch are listed as follows. 

One example of missed spot:
```
1  static void log_logstash_print(yajl_gen g, int severity,
2  cdtime_t timestamp_time) {
....
83 } else {
84  fh = fopen(log_file, "a");
85  do_close = 1;
86 }
87
88 if (fh == NULL) {
89  char errbuf[1024];
90  fprintf(stderr, "log_logstash plugin: fopen (%s) failed: %s\n", log_file,
91  sstrerror(errno, errbuf, sizeof(errbuf)));
92 } else {
....
}
```

One example of historical patch:
```
1  fh = fopen(log_file, "a");
2  do_close = 1;
3  }
4
5  if (fh == NULL) {
6   char errbuf[1024];
7 - fprintf(stderr, "log_logstash plugin: fopen (%s) failed: %s\n", log_file,
8 + fprintf(stderr, "log_logstash plugin: fopen (%s) failed: %s\n",
9 +            (log_file == NULL) ? DEFAULT_LOGFILE : log_file,
10  sstrerror(errno, errbuf, sizeof(errbuf)));
11 } else {
12 fprintf(fh, "%s\n", buf);
13 if (do_close) {
14  fclose(fh);
15 } else {
```

For more detail, please check the attachment. Thanks for your reading. 

[Collectd-patch-example-1.docx](https://github.com/collectd/collectd/files/1621660/Collectd-patch-example-1.docx)
[Collectd-recommendation-example-1.docx](https://github.com/collectd/collectd/files/1621661/Collectd-recommendation-example-1.docx)

**Comment by rpv-tomsk** [comment]
>For more detail, please check the attachment. Thanks for your reading. 

Please use 'Pull Requests' instead of attachmets, especially of 'docx' format.

**Comment by rpv-tomsk** [comment]
You recommend to do the following change:

```
7 - fprintf(stderr, "log_logstash plugin: fopen (%s) failed: %s\n", log_file,
8 + fprintf(stderr, "log_logstash plugin: fopen (%s) failed: %s\n",
9 +            (log_file == NULL) ? DEFAULT_LOGFILE : log_file,
```

That condition `(log_file == NULL)` will never be true because the full piece of code is:

```
  if (log_file == NULL) {
    fh = stderr;
  } else if (strcasecmp(log_file, "stdout") == 0) {
    fh = stdout;
    do_close = 0;
  } else if (strcasecmp(log_file, "stderr") == 0) {
    fh = stderr;
    do_close = 0;
  } else {
    fh = fopen(log_file, "a");
    do_close = 1;
  }

  if (fh == NULL) {
    char errbuf[1024];
    fprintf(stderr, "log_logstash plugin: fopen (%s) failed: %s\n", log_file,
            sstrerror(errno, errbuf, sizeof(errbuf)));
  }
```

So, if `log_file == NULL` then `fh = stderr`, and that condition `fh == NULL` will not be true and the block will not be executed at all.

Also, that is completely incorrect to print a `DEFAULT_LOGFILE` value if that was not really used in `fopen`.

Please, read the code more carefully.

Thank you for working on Collectd project!

**Comment by rpv-tomsk** [comment]
Closed due to lack of response.
Feel free to reopen if needed. Thanks!
