### ISSUE TITLE
Recommendation for removing check and inner logging statements for return value of yyalloc()

### ISSUE THREAD

**Issue by happyhappiness** [collectd/collectd#2645]
Our team researches on consistent update of Collectd during evolution. And we have figured out several spots that may be missed. 

By mining historical patches, we suggest that check and log of return value about yyalloc() ought to be removed. One example for recommendation and corresponding patch are listed as follows. 

One example of missed spot:
```
1  static void yyensure_buffer_stack (void)
2  {
3  yy_size_t num_to_alloc;
4
5  if (!(yy_buffer_stack)) {
6
7   /* First allocation is just for 2 elements, since we don't know if this
8   * scanner will even need a stack. We use 2 instead of 1 to avoid an
9   * immediate realloc on the next call.
10  */
11  num_to_alloc = 1;
12  (yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
13  (num_to_alloc * sizeof(struct
14  yy_buffer_state*));
15  if ( ! (yy_buffer_stack) )
16   YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
17
18  memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
```
One example of historical patch:
```
1
2    num_to_alloc = (yy_buffer_stack_max) + grow_size;
3    (yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
4    ((yy_buffer_stack),
5    num_to_alloc * sizeof(struct yy_buffer_state*)
6    );
7  - if ( ! (yy_buffer_stack) )
8  -  YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
9
10  /* zero only the new slots.*/
11  memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
12  (yy_buffer_stack_max) = num_to_alloc;
13  }
14  }
```

For more detail, please check the attachment. Thanks for your reading. 
[Collectd-patch-example-0.docx](https://github.com/collectd/collectd/files/1621665/Collectd-patch-example-0.docx)
[Collectd-recommendation-example-0.docx](https://github.com/collectd/collectd/files/1621666/Collectd-recommendation-example-0.docx)

**Comment by rpv-tomsk** [comment]
Please use Github formatting. Please use 'Pull Requests' instead of attachments.

**Comment by rpv-tomsk** [comment]
>By mining historical patches, we suggest that check and log of return value about yyalloc() ought to be removed. 

What is your reasoning?

Ours are: We always should check if memory (re)allocation returns correct value.

**Comment by rpv-tomsk** [comment]
Closed due to lack of response.
Feel free to reopen if needed. Thanks!
