### ISSUE TITLE
liblvm2app deprecated

### ISSUE THREAD

**Issue by cpaelzer** [collectd/collectd#2647]
*   Version of collectd: 5.7.2
*   Operating system / distribution: Ubuntu/Debian

## Expected behavior

Build works as it did before.

## Actual behavior

Since recent updates to libs/headers the build breaks.
This is because -Werror is in use and the use of liblvm2app triggers a warning.

> libtool: compile:  x86_64-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I./daemon -DPREFIX=\"/usr\" -DCONFIGFILE=\"/etc/collectd.conf\" -DLOCALSTATEDIR=\"/var\" -DPKGLOCALSTATEDIR=\"/var/lib/collectd\" -DPIDFILE=\"/var/run/collectd.pid\" -DPLUGINDIR=\"/usr/lib/collectd\" -DPKGDATADIR=\"/usr/share/collectd\" -Wdate-time -D_FORTIFY_SOURCE=2 -I/build/1st/collectd-5.7.2/debian/include -UCONFIGFILE -DCONFIGFILE=\"/etc/collectd/collectd.conf\" -Wall -Werror -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wall -Wno-error=deprecated-declarations -MT lvm_la-lvm.lo -MD -MP -MF .deps/lvm_la-lvm.Tpo -c lvm.c  -fPIC -DPIC -o .libs/lvm_la-lvm.o
> In file included from lvm.c:24:0:
> /usr/include/lvm2app.h:21:2: error: #warning "liblvm2app is deprecated, use D-Bus API instead." [-Werror=cpp]
>  #warning "liblvm2app is deprecated, use D-Bus API instead."

Now getting around that warning being fatal is to some extend a Distribution thing for now, but sooner or later collectd likely should switch from liblvm2app to a non deprecated implementation.

## Steps to reproduce

*   build against liblvm2 2.02.176-4.1 or later

## Related links
* [Debian triggering this issue](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=881641)
* [RH announcing to drop liblvm2app](https://bugzilla.redhat.com/show_bug.cgi?id=1489590)

**Comment by faxm0dem** [comment]
I just ran into this on CentOS7.
What's the recommended course of action here? disable lvm2?

**Comment by rubenk** [comment]
That or build with --no-werror

**Comment by srivasta** [comment]
I ran into this issue on Debian testing today:


>   CC       src/lvm_la-lvm.lo
>  In file included from src/lvm.c:29: 
/>  usr/include/lvm2app.h:21:2: error: #warning "liblvm2app is deprecated, use D-Bus API instead." [-Werror=cpp]
>   #warning "liblvm2app is deprecated, use D-Bus API instead."
>    ^~~~~~~
>  cc1: all warnings being treated as errors
>  make[1]: *** [Makefile:7363: src/lvm_la-lvm.lo] Error 1
>  make[1]: Leaving directory '/usr/local/google/home/srivasta/src/collectd'
>  make: *** [Makefile:4931: all] Error 2

**Comment by srivasta** [comment]
The following invocation does make it work
`make CFLAGS+="-Wno-error"`

**Comment by mrunge** [comment]
The code was removed in https://github.com/collectd/collectd/pull/3309
