### ISSUE TITLE
Failed to start collectd statistics daemon

### ISSUE THREAD

**Issue by mistajay** [collectd/collectd#2655]
*   Version of collectd: 5.8.0
*   Operating system / distribution: Korora 26

## Expected behavior

Running successfully after startup

## Actual behavior

Fails to run in Korora 27 fresh install, yet works fine in Fedora 27 fresh install

## Steps to reproduce

*   step 1  Install Korora in Virtualbox
*   step 2  sudo dnf install collectd
*   step 3  systemctl status collectd

Learning linux distros and wanted to check on the differences between Korora and Fedora. Both fresh installs. Tried it first on Korora, it failed. Repeated the steps in Fedora, works fine and I have no idea what the next step is. I am unskilled on fixing services in Linux but trying to learn.

**Comment by mistajay** [comment]
I reverted to before it was installed, and repeated the steps, to maybe show why a fresh install of collectd on a fresh install of Korora is somehow different than the same thing on a fresh install of Fedora (which Korora is based off of).

![01collectd-install](https://user-images.githubusercontent.com/22755586/35280657-753cf4cc-0016-11e8-8966-6c4b418d8994.png)
![02collectd-status](https://user-images.githubusercontent.com/22755586/35280659-77e3ac7a-0016-11e8-8c99-1469907fc8a1.png)
![03collectd-journal](https://user-images.githubusercontent.com/22755586/35280664-7b24750e-0016-11e8-8a6a-ec85466d005e.png)

**Comment by rpv-tomsk** [comment]
Hi! 

You should look into your logs more carefully.  It has a complain about missing `nut` plugin (or it is unable to load it due to failed dependency). If `nut.so` is present in your system, check for missing dependencies by `ldd nut.so`.

**Comment by rubenk** [comment]
In any case, this is not an upstream issue, but a packaging issue.
