### ISSUE TITLE
Custom Bash Script is not showing up on Write Prometheus Plugin

### ISSUE THREAD

**Issue by Neru007** [collectd/collectd#2658]
*   Version of collectd: 5.8
*   Operating system / distribution: Centos 7.3

## Expected behavior

I'm using a bash script with Exec Plugin to monitor the remote connection on a specific IP and I'm using collectd write prometheus plugin to expose the metrics on a http end point. but I'm not able to see the metrics on http endpoint that write prometheus plugin expose.

**Comment by abays** [comment]
Are you perhaps hitting issue #2715?

That aside, would you be able to share the bash script you are using?

**Comment by rubenk** [comment]
Closing to due no response
