### ISSUE TITLE
Add support for 64 bit register types (int and float) to Modbus plugin

### ISSUE THREAD

**Issue by antvick** [collectd/collectd#2664]
*   Version of collectd: 5.4.1
*   Operating system / distribution: Debian

I have a Modbus device that has int64 and float64 register types that I'd like to read with the Modbus plugin. I've had great success with the plugin as in with 98% coverage for our work (with signed and unsigned 16 bit, 32 bit and float registers). However, we're increasingly finding the need to measure 64 bit registers and it would be really useful to have an implementation of this in the Modbus plugin.

The particular spec of the Modbus applicance that I'd like to read can be found attached, along with the register specs, however many other Modbus appliances may also have 64 bit registers too.
[PM5100_PM5300_ModbusRegisterList.xlsx](https://github.com/collectd/collectd/files/1667799/PM5100_PM5300_ModbusRegisterList.xlsx)

**Comment by rpv-tomsk** [comment]
CC: @pbostley

**Comment by rpv-tomsk** [comment]
@antvick, you can look in recently added #2660 and add a similar PR.

**Comment by antvick** [comment]
@rpv-tomsk, thanks! I'll take a look at this over the coming week with a view to opening a PR.

**Comment by rpv-tomsk** [comment]
Closed by #2670 PR
