### ISSUE TITLE
Compilation of Collectd 5.8.0 & Python < 2.6

### ISSUE THREAD

**Issue by CPS86** [collectd/collectd#2667]
*   Version of collectd: 5.8.0
*   Operating system / distribution: RedHat 5.11

Hello

I'm trying to compile Collectd 5.8.0 with a very old version of python (2.4 or 2.5). Unfortunately without success.

I'm receiving the following:

```
checking for python3-config  ../python-config
checking Python.h usability ... yes
checking Python.h presence ... yes
checking for Python.h ... yes
checking for libpython ... no 
```

What is libpython?
I thought that all necessary information is retrieved from python-config?
Can I somehow provide manually libpython location? Is it e.g. libpython2.4.so file ?

If I try the same with collectd 5.5.2:
```
checking for Python CPPFLAGS ... /python2.5
checking Python.h usability ... yes
checking Python.h presence ... yes
checking for Python.h ... yes
checking for Python LDFLAGS ... /opt/python/lib
checking for Python LIBS ... libpython2.5.a
**checking for PyObject_CallFunction ... no**
```

Why in the world PyObject_CallFunction is not supported?

**Comment by trenkel** [comment]
The Python plugin requires at least Python 2.6, as described in the man page: https://collectd.org/documentation/manpages/collectd-python.5.shtml#description

This has been the case since 2012, see https://github.com/collectd/collectd/issues/1863 for more details.
