### ISSUE TITLE
Disable Local storage if possible

### ISSUE THREAD

**Issue by djadk84** [collectd/collectd#2668]
It's possible to disable collectd BaseDir and send all metrics to a centralized server. The goal is to avoid using CPU and disk space to write to disk when all the metrics are being sent to a centralized server via the network using the network plugin.
I try to set **_BaseDir_**  _**NULL**_ or _**0**_ but no luck and there is no info in the documentation about that also. 
If you remove the local storage directory it will do the trick but when restart you have to do it again 
> rm -rf /var/db/collectd

Note when removed the local storage directory my log file will be full of those error logs

> tail -f /var/log/collectd/collectd.log
[2018-02-02 10:44:33] check_create_dir: mkdir (server1): No such file or directory
[2018-02-02 10:44:33] check_create_dir: mkdir (server1): No such file or directory
[2018-02-02 10:44:33] check_create_dir: mkdir (server1): No such file or directory
[2018-02-02 10:44:33] check_create_dir: mkdir (server1): No such file or directory

If should be possible to disable local storage if not needed.

**Comment by rpv-tomsk** [comment]
Hi!

You just need to disable the plugin (`rrdtool`, for example)  which writes metrics to disk.

**Comment by djadk84** [comment]
@rpv-tomsk, Here is a list of all the plugins I have loaded on almost all servers, I'm only using rrdtool on the central server.

##############################################################################
# LoadPlugin section                                                                                                                        #                                                        
##############################################################################

LoadPlugin cpu
LoadPlugin csv
LoadPlugin interface
LoadPlugin load
LoadPlugin memory
LoadPlugin processes
LoadPlugin swap
LoadPlugin tcpconns
LoadPlugin zfs_arc

##############################################################################
# Custom plugin load                                                         #
##############################################################################

LoadPlugin nginx
LoadPlugin filecount
LoadPlugin curl_json
LoadPlugin tail
LoadPlugin network

**Comment by rpv-tomsk** [comment]
> LoadPlugin csv

You should disable this plugin too. That is the cause.

Feel free to reopen/report new issues if needed.
Thanks for using Collectd!
