### ISSUE TITLE
intel_pmu: core dump if hw event from HardwareEvents is not resolved

### ISSUE THREAD

**Issue by kwiatrox** [collectd/collectd#2675]
*   Version of collectd: 5.8, master
*   Operating system / distribution: Ubuntu 16.04

## Expected behavior

Collectd starts with intel_pmu plugin loaded.

## Actual behavior

Core dump during init of intel_pmu plugin.

## Steps to reproduce

In configuration set first hw event to value that will not be resolved, e.g. some random name.

```
LoadPlugin intel_pmu
<Plugin intel_pmu>
  EventList "/var/cache/pmu/GenuineIntel-6-3F-core.json"
  HardwareEvents "abcd,L2_RQSTS.CODE_RD_HIT"
</Plugin>
```

It causes  core dump during intel_pmu init function.

The problem is in line 408
`el->eventlist_last->group_leader = 1;`
Where eventlist_last is NULL in this case.

The fix is in progress and I'm going to open PR soon.

**Comment by rpv-tomsk** [comment]
The patch was added to collectd-5.8 branch.
