### ISSUE TITLE
Python plugin & two (or more) versions of python installed

### ISSUE THREAD

**Issue by CPS86** [collectd/collectd#2682]
Hello

Let's assume the following situation: 
I compiled Collectd with python plugin enabled ( python 2.6 used ). 
On a client box, it turned out there's python 2.7.2 installed. Whether it's gonna work? 
Or conversely... I compiled Collectd with python 2.7.2, and client has only 2.6 installed...

The next question is, whether I can specify which version of python should be used by collectd if there are more than 1 version of python installed on a server?

**Comment by rubenk** [comment]
It should work, but it depends on if the versions of libpython.so are api-compatible. If they have a different major soname then no and you'll need to recompile.

> The next question is, whether I can specify which version of python should be used by collectd if there are more than 1 version of python installed on a server?

Yes, you can point configure to the right libpython version:
```
collectd > ./configure --help | grep PYTHON
  LIBPYTHON_CPPFLAGS
  LIBPYTHON_LDFLAGS

```

**Comment by torrencj** [comment]
Even when building it with the python libs you'd like to use, collectd still uses the system default.

**Comment by rpv-tomsk** [comment]
1) Find the dir where Collect plugins are located
2) Do `ldd ./python.so`
That will show the library which will be used.

Example:

```
root@hs01:/opt/collectd/lib/collectd# ldd ./python.so
        linux-gate.so.1 (0xb76f8000)
        libpthread.so.0 => /lib/i386-linux-gnu/i686/nosegneg/libpthread.so.0 (0xb76bd000)
        libdl.so.2 => /lib/i386-linux-gnu/i686/nosegneg/libdl.so.2 (0xb76b8000)
        libutil.so.1 => /lib/i386-linux-gnu/i686/nosegneg/libutil.so.1 (0xb76b4000)
        libm.so.6 => /lib/i386-linux-gnu/i686/nosegneg/libm.so.6 (0xb766d000)
        libpython2.7.so.1.0 => /usr/lib/libpython2.7.so.1.0 (0xb739f000)
        libc.so.6 => /lib/i386-linux-gnu/i686/nosegneg/libc.so.6 (0xb71ef000)
        /lib/ld-linux.so.2 (0xb76f9000)
        libz.so.1 => /lib/i386-linux-gnu/libz.so.1 (0xb71d6000)
        libgcc_s.so.1 => /lib/i386-linux-gnu/libgcc_s.so.1 (0xb71b9000)
```

**Comment by rpv-tomsk** [comment]
You can try to use `LD_PRELOAD` to specify required version ...
