### ISSUE TITLE
locale issue back in 5.8.0

### ISSUE THREAD

**Issue by b3niup** [collectd/collectd#2685]
*   Version of collectd: 5.8.0
*   Operating system / distribution: Archllinux

## Expected behavior
Decimal values sent to graphite should be dot separated, e.g. 0.002

## Actual behavior
Decimal values sent to graphite are comma separated instead, e.g. 0,002

## Steps to reproduce

*   install collectd in version 5.8.0 or later
*   export LC_ALL=pl_PL.UTF-8
*   start collectd

Everything worked fine untill upgrade from 5.7.X to 5.8.0.
Working solution is to define systemd override.conf containing locale declaration:
```
[Service]
Environment="LC_ALL="
Environment="LC_NUMERIC=C"
```

**Comment by emeric254** [comment]
I got the same issue on fedora with collectd 5.8.1, but only when loading the java plugin ...

 - Without the java plugin the locale seems to be ignored, values are valid (ie.  3.7988)
 - With java plugin loaded the locale kick in and the values send to graphite are wrong (ie. 3,7988)


Overiding the systemd service to enforce the C locale (as @b3niup wrote above) is working !

**Comment by rpv-tomsk** [comment]
Closed by: #3214
Related: #3181
