### ISSUE TITLE
Plugin df ignores settings

### ISSUE THREAD

**Issue by Neurobion** [collectd/collectd#2693]
*   Client version of collectd: 5.5.1
**   Operating system / distribution: Ubuntu 16.04.3 LTS
*   "Server" version of collectd: 5.5.0
**   Operating system / distribution: Ubuntu 12.04.5 LTS

## Expected behavior
Ignore disk related metrics for defined FSType when IgnoreSelected True

## Actual behavior

RRD files are generated on server side even they should not be:

df-var-lib-docker-containers-bd6d2c1fd19a2a5b5af00393f66940560af69/
df-var-lib-docker-containers-da0e864566194c1f5c42417f4ef40c08064e5/
df-var-lib-docker-containers-f56ea79aac99410e04bf61c9c2b16c1ffafd5/

## Steps to reproduce

Client: (I make config smallest as possible to isolate that problem)

_It works as expected when rrdtool plugin instead of network is used. So do not understand how data on client/server side are proceed when they should be filtered by configuration._

```
FQDNLookup  true
BaseDir     "/var/lib/collectd/rrd"
PIDFile     "/var/run/collectdmon.pid"
PluginDir   "/usr/lib/collectd"
Interval    10
TypesDB     "/etc/collectd/types.db"

LoadPlugin  network
LoadPlugin df

<Plugin "network">
  Server "IP"
  ReportStats true
</Plugin>

<Plugin "df">
  FSType tmpfs
  IgnoreSelected true
</Plugin>
```

Server:
```
FQDNLookup  true
BaseDir     "/var/lib/collectd/rrd"
PIDFile     "/var/run/collectdmon.pid"
PluginDir   "/usr/lib/collectd"
Interval    10
TypesDB     "/etc/collectd/types.db"

LoadPlugin  rrdcached
LoadPlugin  rrdtool
LoadPlugin  network
LoadPlugin  cpu
LoadPlugin  memory
LoadPlugin  load
LoadPlugin  df
LoadPlugin  interface
LoadPlugin  disk
LoadPlugin  logfile
LoadPlugin  processes
LoadPlugin  snmp
<Plugin "network">
 Listen "FQDN" "25826"
  Server "IP"
  ReportStats true
</Plugin>
<Plugin "rrdcached">
 DaemonAddress "unix:/var/run/rrdcached.sock"
 DataDir "/var/lib/collectd/rrd"
 CreateFiles true
</Plugin>
<Plugin "rrdtool">
 WritesPerSecond 80
</Plugin>
<Plugin "logfile">
 LogLevel err
 File "/var/log/collectd.log"
</Plugin>
Include "/etc/collectd/snmp/metrics"
Include "/etc/collectd/snmp/hosts"
<Plugin cpu>
  ValuesPercentage true
</Plugin>
```

PS: Same happened for client's configuration: 

```
<Plugin "interface">
  Interface "lo"
  Interface "/^veth*/"
  Interface "/^docker*/"
  Interface "/^br*/"
  IgnoreSelected true
</Plugin>
```
Thank you for advice

**Comment by rpv-tomsk** [comment]
Hi!

> It works as expected when rrdtool plugin instead of network is used. So do not understand how data on client/server side are proceed when they should be filtered by configuration.

That can't be possible, because ignorelist is applied inside of reading plugin, not on "core" level. 
So, Collectd core will have the same data from reading plugin independently of further metrics destination.

**Comment by rpv-tomsk** [comment]
Closed due to lack of response.
Feel free to reopen if needed.

Thanks for using Collectd.
