### ISSUE TITLE
Is grbuf_size being given an appropriate size?

### ISSUE THREAD

**Issue by mwtzzz** [collectd/collectd#2696]
*   Version of collectd: 5.8.0
*   Operating system / distribution: linux

I'd like to revisit issue https://github.com/collectd/collectd/issues/2208. 

commit 24bdf52 as referenced in that issue looks good, as it explicity sets the buffer sizes to 4096. But looking at the source code for 5.8.0, I see this is not what's happening. What's happening is it gets set to _SC_GETGR_R_SIZE_MAX (which on my system is 1024), or if that value doesn't exist it gets set to the page size, or barring that to 4096. So it appears that v5.8.0 fails to fix the issue. 

Can we take a look at it again and make sure that a sufficiently large buffer size is being assigned to handle hosts that have greater than 1000 groups?

**Comment by rubenk** [comment]
Ah yes, I found https://tomlee.co/2012/10/problems-with-large-linux-unix-groups-and-getgrgid_r-getgrnam_r/ which might explain this:

> "Turns out that the value associated with _SC_GETGR_R_SIZE_MAX is merely “an initial suggested size for buf”

**Comment by mwtzzz** [comment]
Can collectd be updated not to use _SC_GETGR_R_SIZE_MAX, and instead use 4096 ?

**Comment by rubenk** [comment]
I agree this should be fixed, but are you actually hitting this issue?

> Can we take a look at it again and make sure that a sufficiently large buffer size is being assigned to handle hosts that have greater than 1000 groups?

Having more than 1000 groups is not the issue. It's about a single group having more members than can be stored in the buffer. Depending on the length of the user names this can happen pretty soon with 1024 characters.

**Comment by mwtzzz** [comment]
Yes, we are hitting this issue in our environment. We do have some groups with lots of members, for example some of our groups contain everyone in our company. What I'm seeing in the logs are messages like "exec plugin: Failed to get group information for group ``nagios'': Numerical result out of range" and a result our exec plugins are failing to run.

**Comment by rubenk** [comment]
In that case even 4096 bytes might not be enough and we need to dynamically realloc the buffer if we get a ERANGE.

**Comment by mwtzzz** [comment]
Might I suggest an optional command-line argument that allows the user to designate the number of bytes to use?

**Comment by rubenk** [comment]
We should be able to detect how big the buffer should be instead of letting the user guess.

**Comment by mwtzzz** [comment]
Sounds good. Do you need anything from me?

**Comment by rubenk** [comment]
A patch would be great ;-) Unfortunately I don't have a lot of time to write one myself.

**Comment by mwtzzz** [comment]
I understand ;-) ... If you point me in the right direction I'll see what I can come up with.

**Comment by rubenk** [comment]
https://tomlee.co/2012/10/problems-with-large-linux-unix-groups-and-getgrgid_r-getgrnam_r/ has an example that should work.

**Comment by sreedi** [comment]
@rubenk,  
we have run into this same issue due to  _SC_GETGR_R_SIZE_MAX set to  1024 on our systems.
I tried to attempt to fix this as per above suggestion on handling buffer allocation dynamically, incrementing buffer size by  _SC_GETGR_R_SIZE_MAX/_SC_PAGSIZE on each failure. 

Could I get a  +1 on the PR with fix   https://github.com/collectd/collectd/pull/2937
