### ISSUE TITLE
Solaris tcpconns plugin dependency error

### ISSUE THREAD

**Issue by alexlinux** [collectd/collectd#2698]
*   Version of collectd: 5.7.2
*   Operating system / distribution: Solaris

## Expected behavior
Compile with tcpconns enabled

## Actual behavior
Compile with all plugins works but disables tcpconns plugin
Forcing --enable-tcpconns fails with:

configure:55864: result:     tcpconns  . . . . . . no (dependency error)

## Steps to reproduce
Compile collectd on solaris with --enable-tcpconns

Thanks!

[config.log.txt](https://github.com/collectd/collectd/files/1753305/config.log.txt)

**Comment by rubenk** [comment]
The tcpconns plugin doesn't support Solaris.
