### ISSUE TITLE
python plugin fails on Mac OS X 10.7.2

### ISSUE THREAD

**Issue by blysik** [collectd/collectd#27]
From running configure:

checking for Python CPPFLAGS... /System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7
checking Python.h usability... yes
checking Python.h presence... yes
checking for Python.h... yes
checking for Python LDFLAGS... /System/Library/Frameworks/Python.framework/Versions/2.7/lib
checking for Python LIBS... failed with status 0 (output: )

**Comment by rubenk** [comment]
Fixed by f0735d24a2195c8da2657c46a7cb9ceb790b0836
