### ISSUE TITLE
Plugin to read PCIe errors

### ISSUE THREAD

**Issue by kwiatrox** [collectd/collectd#2706]
Hi All,

I plan to add plugin to read PCIe errors. I would like to know about any opinions for such plugin.
There was a PR for a pcie plugin quite a long time ago #2382 but it remained without response, maybe it was to big to review for 5.8 release.
Now I plan to add some smaller version of it. It will be based on pulling the pci config register from /sys/bus/pci/devices/. You can read more about the HL design on https://wiki.opnfv.org/display/fastpath/PCIe+Errors+High+Level+Design.
I'm open for any feedback or comments from community.

Thanks

**Comment by atyronesmith** [comment]
Hi @octo, @rpv-tomsk,
 Can you provide guidance into what we need to do either move along the original PR or to submit a new PR?  Let us know how we can help.

**Comment by kwiatrox** [comment]
New PR opened #2733.

**Comment by rubenk** [comment]
Since there's a PR for this, there's no need to keep this issue open.
