### ISSUE TITLE
turbostat plugin fix unreviewed

### ISSUE THREAD

**Issue by pllopis** [collectd/collectd#2708]
Hello collectd contributors and maintainers,

I wanted to know if I could do something to help regarding Issue #1593. This is affecting all my systems where I would like to collectd data using the turbostat plugin. I have submitted PR #2627 back in December but did not get any feedback.

I tried commenting on the aforementioned issue and on IRC but got no response, so sorry for the noise in the form of a new issue.

Is there any way I can help to get that issue fixed? Thanks!

**Comment by rubenk** [comment]
Hi,

We do appreciate your efforts, but you'll just have to wait until someone reviews your code.
As you can see there are a lot of open issues and pull requests waiting for our attention, and our time is limited. We always appreciate any help to lighten our load.

Opening new issues doesn't help however.
