### ISSUE TITLE
ipmi plugin: new feature, add options to filter SEL events.

### ISSUE THREAD

**Issue by MariuszX** [collectd/collectd#2713]
According to the request from https://github.com/collectd/collectd/pull/2703 we started development of this feature.

Requirements:
- new option 'SELSensor' - to select source of events
- new option 'SELIgnoreSelected' - to ignore events from selected sensors

Functionality will be similar to existing options 'Sensor' and 'IgnoreSelected', which are used now for filtering metrics. New options will allow independent filtering of SEL events.

Should we consider any other requirements?

**Comment by rpv-tomsk** [comment]
This feature was implemented and merged.
