### ISSUE TITLE
uuid plugin can erroneously write past the end of a heap block and corrupt heap metadata

### ISSUE THREAD

**Issue by kwiatrox** [collectd/collectd#2723]
*   Version of collectd: 5.8
*   Operating system / distribution: redhat

## Expected behavior

Collectd up & running.

## Actual behavior

Crash during init. The error can happen in different places, always on malloc of free. Below is an example of backtrace:

```
*** Error in `/opt/collectd/sbin/collectd': corrupted double-linked list: 0x00000000026447d0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7ab54)[0x7fe11db9fb54]
/lib64/libc.so.6(+0x7de72)[0x7fe11dba2e72]
/lib64/libc.so.6(__libc_malloc+0x4c)[0x7fe11dba510c]
/lib64/libc.so.6(open_memstream+0x1a)[0x7fe11db98ada]
/lib64/libc.so.6(__vsyslog_chk+0x7a)[0x7fe11dc1702a]
/lib64/libc.so.6(syslog+0x8f)[0x7fe11dc1758f]
/opt/collectd/sbin/collectd(plugin_log+0xe9)[0x40b609]
/opt/collectd/lib/collectd/intel_pmu.so(+0x2424)[0x7fe11a201424]
/opt/collectd/sbin/collectd(plugin_init_all+0x157)[0x40ea07]
/opt/collectd/sbin/collectd(main+0x1c8)[0x406088]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7fe11db46c05]
/opt/collectd/sbin/collectd[0x4066a4]
```

## Steps to reproduce

*  To reproduce enable a lot of plugins like cpu, load, intel_pmu, intel_rdt, ipmi, turbostat, logfile, syslog, csv and uuid. The set of plugins and configuration can be different depending on system but with uuid disabled it always works.

I traced the issue to init of uuid plugin.
It writes to `hostname_g` directly:

```sstrncpy(hostname_g, uuid, DATA_MAX_NAME_LEN);```

I guess it should use `hostname_set(char const *hostname)` instead. Size of `hostname_g` can be smaller than `uuid`.

**Comment by rpv-tomsk** [comment]
Thanks for reporting this!
