### ISSUE TITLE
collectd 5.8; compile fails on Solaris 11 with "zero-sized struct/union" in src/utils_cmds.h

### ISSUE THREAD

**Issue by skrueger8** [collectd/collectd#2739]
*   Version of collectd: 5.8
*   Operating system / distribution: Solaris 11.4 Beta / SPARC

## Expected behavior

```
./configure
gmake
```

runs fine

## Actual behavior

```
gmake
...
/bin/sh ./libtool  --tag=CC   --mode=compile /opt/developerstudio12.6/bin/cc -DHAVE_CONFIG_H -I. -I./src  -I./src -I./src/daemon -DPREFIX='"/opt/collectd/collectd58"' -DCONFIGFILE='"/opt/collectd/collectd58/etc/collectd.conf"' -DLOCALSTATEDIR='"/opt/collectd/collectd58/var"' -DPKGLOCALSTATEDIR='"/opt/collectd/collectd58/var/lib/collectd"' -DPLUGINDIR='"/opt/collectd/collectd58/lib/collectd"' -DPKGDATADIR='"/opt/collectd/collectd58/share/collectd"' -D_LARGEFILE64_SOURCE -D_XOPEN_SOURCE=600 -D__EXTENSIONS__=1 -D_XPG6 -Wall -m64 -g -Qoption cg -xregs=no%appl -W2,-xwrap_int -xc99=all -KPIC -DPIC -xmemalign=16s -c -o src/utils_cmds.lo src/utils_cmds.c
libtool: compile:  /opt/developerstudio12.6/bin/cc -DHAVE_CONFIG_H -I. -I./src -I./src -I./src/daemon "-DPREFIX=\"/opt/collectd/collectd58\"" "-DCONFIGFILE=\"/opt/collectd/collectd58/etc/collectd.conf\"" "-DLOCALSTATEDIR=\"/opt/collectd/collectd58/var\"" "-DPKGLOCALSTATEDIR=\"/opt/collectd/collectd58/var/lib/collectd\"" "-DPLUGINDIR=\"/opt/collectd/collectd58/lib/collectd\"" "-DPKGDATADIR=\"/opt/collectd/collectd58/share/collectd\"" -D_LARGEFILE64_SOURCE -D_XOPEN_SOURCE=600 -D__EXTENSIONS__=1 -D_XPG6 -Wall -m64 -g -Qoption cg -xregs=no%appl -W2,-xwrap_int -xc99=all -KPIC -DPIC -xmemalign=16s -c src/utils_cmds.c  -KPIC -DPIC -o src/.libs/utils_cmds.o
"src/utils_cmds.h", line 64: zero-sized struct/union
cc: acomp failed for src/utils_cmds.c
gmake[1]: *** [Makefile:5726: src/utils_cmds.lo] Error 1
gmake[1]: Leaving directory '/tmp/collectd-5.8.0'
```

**Comment by rubenk** [comment]
Thanks for the report, but please note that we only test collectd with gcc and clang, and not on Solaris 11. Does it compile with gcc?

**Comment by rubenk** [comment]
Hehehe, thanks for doing that :-)

empty structs are indeed a gcc extension.
This is not really new code so I'm surprised it broke. Perhaps newer versions of Sun Studio got more strict?

Could you try to add '-features extensions' to your CFLAGS? I hope that helps.

**Comment by skrueger8** [comment]
Oh that helps. Strange I thought I'm using `-features extensions` by default... This still breaks `-Werror` though ;)

```
$ cat struct.c
typedef struct { } cmd_listval_t;
int main(void) { return 0; }

$ cc -Wall -m64 -std=c11 struct.c
"struct.c", line 1: zero-sized struct/union
cc: acomp failed for struct.c

$ cc -Wall -m64 -std=c11 -features=extensions struct.c
"struct.c", line 1: warning: zero-sized struct/union
```

So I guess you're not planing to pad `cmd_listval_t` with some dummy member object to make that code comply? Or killing it since it's not really used?

**Comment by rubenk** [comment]
Just noticed you are using -std=c11?  You're free to do so of course but we explicitly use AC_PROG_CC_C99. Not sure if it makes a difference in this case.

> So I guess you're not planing to pad cmd_listval_t with some dummy member object to make that code comply? Or g/c'ing it since it's not really used?

I'm not sure what the best fix is. CC-ing @tokkee since he's more familiar with this piece of code.

**Comment by rpv-tomsk** [comment]
From first look, that type is not used at all. That is a stub for possible future code extension.
It compiles successfully with a patch:
```
diff --git a/src/utils_cmds.h b/src/utils_cmds.h
index 26d5338..9d2ffb5 100644
--- a/src/utils_cmds.h
+++ b/src/utils_cmds.h
@@ -61,8 +61,7 @@ typedef struct {
   identifier_t identifier;
 } cmd_getval_t;

-typedef struct {
-} cmd_listval_t;
+typedef void *cmd_listval_t;

 typedef struct {
   /* The raw identifier as provided by the user. */
```

**Comment by rubenk** [comment]
Unused code is broken code, so let's remove it. @rpv-tomsk can you turn your patch into a PR?

**Comment by rpv-tomsk** [comment]
That's done! )
