### ISSUE TITLE
Process Open FD Metrics are not coming

### ISSUE THREAD

**Issue by yks0000** [collectd/collectd#2759]
*   Version of collectd: 5.8
*   Operating system / distribution: Redhat Linux

## Expected behavior

I am using below config to get Open FD and Context of a process. `nginx` here. This should return OpenFD Metric as per `src/processes.c`

```
<Plugin "processes">
        ProcessMatch "nginx" "nginx"
        CollectFileDescriptor true
        CollectContextSwitch true
</Plugin>
```

## Actual behavior

The metric this is returning is same as of old version of CollectD. It does not return OpenFD.

Metric Returned:

```
ps_code
ps_count
ps_cputime
ps_data
ps_pagefaults
ps_rss
ps_stacksize
ps_vm
```
## Steps to reproduce

* Add below config to collectd.conf

```
LoadPlugin "processes"

<Plugin "processes">
        ProcessMatch "nginx" "nginx"
        CollectFileDescriptor true
        CollectContextSwitch true
</Plugin>
```

Replace nginx with any process which is running

**Comment by yks0000** [comment]
Hey, 

Thanks, I did not tested it yet and going to test it tomorrow. Please feel free to close, I will update the comment as it goes. Also, If you can let me know where to update Documentation or access to `https://collectd.org/wiki/index.php/Plugin:Processes` I can update.

**Comment by rpv-tomsk** [comment]
Documentation updates can be send as patch requests.
To get access to wiki you can ask @octo. 

Or, you can send your patches here, I have access and able to update wiki.

**Comment by yks0000** [comment]
Below worked. Thanks

```
<Plugin "processes">
         <ProcessMatch "name" "regex">
            CollectFileDescriptor false
            CollectContextSwitch true
          </ProcessMatch>
</Plugin>
```

**Comment by rpv-tomsk** [comment]
Thanks for using Collectd!
