### ISSUE TITLE
Memory plugin is not reporting percentage values

### ISSUE THREAD

**Issue by akalbhor** [collectd/collectd#2770]
*   Version of collectd: collectd:amd64/5.8.0.74.g0c85475
*   Operating system / distribution: Ubuntu/16.04

## Expected behavior

Memory plugin report metrics as percentage values.

## Actual behavior

Memory plugin only able to report metrics as absolute value.
Adding `ValuesAbsolute false` ends up with no metrics getting reported at all for memory plugin.

## Steps to reproduce

*   Added following config in `collectd.conf`:

```
<Plugin memory>
        ValuesPercentage true
</Plugin>
```

*   Restart collectd

**Comment by rubenk** [comment]
Sorry but I can't reproduce this with current master.

I have
```
<Plugin memory>
        ValuesPercentage true
</Plugin>
```
and the write_log plugin enabled.

I get metrics like:
```
[2018-05-16 12:03:09] write_log values:
localhost.memory.percent-used 1.79647466903896 1526464989
```
