### ISSUE TITLE
probably inconsistencies collecting data 

### ISSUE THREAD

**Issue by nbari** [collectd/collectd#2780]
*   Version of collectd: 5.8.0
*   Operating system / distribution: Linux / Centos 7 3.10.0-693.11.6.el7.x86_64 #

## Expected behavior

I want to get the total available memory (`sum free|used|cached|buffered`), currently using influxdb 1.5.1 and using thies query on a vm with 4GB ram:

`SELECT sum("value") AS "total" FROM "memory_value" WHERE ("host" =~ /^$host$/ AND "type_instance" =~ /(free|used|cached|buffered)/) AND $timeFilter GROUP BY time($__interval) fill(null)
`

Output is more less consistant:

```
1526473320000000000 4425228288
1526473380000000000 4425228288
1526473440000000000 4425261056
1526473500000000000 4425261056
1526473560000000000 4425261056
1526473620000000000 4425261056
1526473680000000000 4425261056
1526473740000000000 4425261056
1526473800000000000 4425273344
```

## Actual behavior

For an uknow reasons doing same query  in same VM I got some times different values, for example, reports 3.5GB instead of 4.GB

```
1526453700000000000 3567230976
1526453760000000000 3567312896
1526453820000000000 3567312896
1526453880000000000 3811479552
1526453940000000000 4451917824
1526454000000000000 4457213952
 
```

## Steps to reproduce

Current configuration:

```
FQDNLookup   true
Interval     60

LoadPlugin cpu
LoadPlugin df
LoadPlugin disk
LoadPlugin interface
LoadPlugin load
LoadPlugin memory
```

*   step 1

Query the db periodically:

`SELECT sum("value") AS "total" FROM "memory_value" WHERE ("host" = 'my-host' AND "type_instance" =~ /(free|used|cached|buffered)/) AND time > now() -6h Group BY time(1m)
`

**Comment by faxm0dem** [comment]
iirc there are more instances than that. what happens if you remove the type_instance constraint?

**Comment by nbari** [comment]
Hi @faxm0dem  many thanks, removing the type_instance is consistent, issue was not taking into consideration the `slab_recl` and `slab_unrecl`
