### ISSUE TITLE
support reporting individual processes

### ISSUE THREAD

**Issue by yellowpattern** [collectd/collectd#2782]
Collectd 5.7.2

Whaat I would like to do is specify a line like this:

ProcessMatch "msyql.*"

and have collectd provide data on each instance of mysql that is running without the need to have each individual mysql listed with its own ProcessMatch line. At present collectd aggregates all matching processes into a single "big report."

**Comment by rpv-tomsk** [comment]
I see no problem with explicit configuring of `ProcessMatch` directives (and I use this way on my servers).

If you have some automated system which creates MySQL instances, it can be used to configure Collectd too. If you do this by your hands - solution is the same.

Your wish is understandable, but, after short look, it will require significant rework of plugin.
The fastest way of getting results is explicit configuration. 

Patches are always welcome.

**Comment by yellowpattern** [comment]
First patch - remove all of the fields common between procstat_entry_t and procstat_t from procstat_t and put a procstat_entry_t into procstat_t. Change ps_submit_proc_list to accept a procstat_entry_t *.

[processes.c.patch.txt](https://github.com/collectd/collectd/files/2019157/processes.c.patch.txt)

**Comment by rpv-tomsk** [comment]
Sorry, I haven't looked into your patch deeply because it can't be simply applied to master branch.
Can you please use GIT / patch request? That is not to complex task, and will be a more convenient way of discussion.

Please don't forget what `ProcessMatch` can match several processes, their stats should be summarized.
(It looks like you have not forgotten, but 'just for info').

**Comment by yellowpattern** [comment]
All of the data in procstat_t is copied from/summarised from procstat_entry_t.

There is no real benefit from having it split out in procstat_t - it makes maintaining the code harder as a changes to fields (add/remove/change) in procstat_entry_t also needs to be made again in procstat_t.

Yes, I understand the relationship between procstat_t and procstat_entry_t - this patch was just a "preparation patch" that is independent of separate reporting.

Once this is done, it makes it easier to understand how to do both combined and separate reporting of processes.

**Comment by yellowpattern** [comment]
Hmm! Master has become worse! Three structures now with the same fields :(

First patch for this feature reduces the counter fields down into on structure (procstat_entry_t) that is used by procstat_t and process_entry_t.

[processes.c.patch.txt](https://github.com/collectd/collectd/files/2019328/processes.c.patch.txt)

**Comment by yellowpattern** [comment]
All that needs to be done in the next patch is to either send the combined stats in procstat_t (or is it process_entry_t now?) or walk the list of instances and send the stats from each procstat_entry_t. Maybe add a field to procstat_entry_t to say if it has been updated in the last "read" and thus data should be sent (or not).

**Comment by yellowpattern** [comment]
Adding that "ReportSeparately" flag is relatively easy... this patch is applied on top of the first.

I've separated out the patches like this to make it easier to see what is "Feature Code" vs "Cleanup Code". Let me know what you think.

[processes.c.patch-2.txt](https://github.com/collectd/collectd/files/2020414/processes.c.patch-2.txt)

**Comment by rpv-tomsk** [comment]
>All that needs to be done in the next patch is to either send the combined stats in procstat_t (or is it process_entry_t now?) or walk the list of instances and send the stats from each procstat_entry_t. 

Disagreed. We should support a case when several processes will match same mask.Their stats should be aggregated before reporting.

Live example - php-fpm:

```
#ps uaxf
 php-fpm: master process (/etc/php/7.1/fpm/php-fpm.conf)
  \_ php-fpm: pool domain.tld.admin
  ...
  \_ php-fpm: pool domain.tld.admin
  \_ php-fpm: pool domain.tld.user
  ...
  \_ php-fpm: pool domain.tld.user
```

Please create patch request for code review.

**Comment by yellowpattern** [comment]
Exactly what behaviour do you desire?

The code still aggregates statistics in the same fashion as it already does. All that I really changed is what gets reported - either the aggregate (php-fpm) or all of the individuals (pfp-fpm: master, pfp-fpm: pool domain.tld.admin, ...) and made it selectable either globally or locally if you use a line like this:
ProcessMatch "php-fpm" "pfp-fpm:.*"

What behaviour do you desire that is currently not possible?

**Comment by rpv-tomsk** [comment]
Ok, it's possible that I don't understand something about how `procstat_entry_t` entries are filled.

Sorry, I didn't look the code deeply, because there is no patch request.

**Comment by rpv-tomsk** [comment]
Closed due to lack of response or actions.
Feel free to reopen if you have new questions or proposals.

**Comment by yellowpattern** [comment]
Code change was supplied. Consider it a patch request. I don't have time for messing around with git push, etc. Code has been tested and works as advertised.

**Comment by yellowpattern** [comment]
And just for the record, I *can't* reopen the issue.

**Comment by rpv-tomsk** [comment]
>Code has been tested and works as advertised.

Code  has not been tested by CI system.
Code has not been tested for mergeabilty.
I think, there is no documentation updates.
And so on.

>And just for the record, I can't reopen the issue.

Ok, will knew this, thanks.

>I don't have time for messing around ...

Maintainers are ordinary people too.
