### ISSUE TITLE
encryption of passwords in configuration file 

### ISSUE THREAD

**Issue by babyunicorn69** [collectd/collectd#2791]
*   Version of collectd: 5.8.0
*   Operating system / distribution: linux rhel 7.4

I have looked everywhere and couldn't find any way of encrypting passwords in the collectd.conf file.
Right now I have a collectd config file with the Postgres plugin install and loaded, it requires the connection credentials for each database I'm querying.
This means right now i have the password saved in cleartext in the configuration file.

Unless I missed this feature, it should be added to collectd.

**Comment by rpv-tomsk** [comment]
Hi!

Pull requests are welcome.

**Comment by rpv-tomsk** [comment]
Also, I see no reasons for this to be added.
If you have some form of credentials, then you can use them outside of Collectd regardless of they are encrypted or not.

Also you can use `Service` option:

>  Service service_name
           Specify the PostgreSQL service name to use for additional
           parameters. That service has to be defined in pg_service.conf and
           holds additional connection parameters. See the section "The
           Connection Service File" in the PostgreSQL Documentation for
           details.

Maybe it can feet your needs.

If you have another configuration examples, how your proposed feature was implemented in other software, please provide them.

**Comment by rpv-tomsk** [comment]
Closed due to lack of response.
