### ISSUE TITLE
Incorrect memory info reported by the processes plugin

### ISSUE THREAD

**Issue by ashu210890** [collectd/collectd#2798]
*   Version of collectd: 5.4.0
*   Operating system / distribution: Ubuntu 16.04

## Expected behavior
I am trying to monitor the resident memory usage for our Postgres installation. I have added the following to our collectd configuration:
```
 <Plugin processes>
     Process "postgres"
     ProcessMatch "postgres" "postgres:.*"
 </Plugin>
```
The `ps aux| grep -i postres` output (truncated) looks like the following;
```
postgres 15667 23.6  0.2 402536 160436 ?       Ss   07:20 113:51 postgres: 9.5/main: user_name db_name 127.0.0.1(39975) SELECT                                                          
postgres 17964  0.0  0.0 394920 52868 ?        Ss   08:00   0:00 postgres: 9.5/main: user_name db_name 127.0.0.1(40977) idle                                                            
postgres 17973 24.8  0.2 398404 157720 ?       Ss   08:00 109:44 postgres: 9.5/main: user_name db_name 127.0.0.1(40986) SELECT                                                          
postgres 17974 24.7  0.2 400320 160600 ?       Rs   08:00 109:12 postgres: 9.5/main: user_name db_name 127.0.0.1(40987) SELECT                                                          
postgres 18758  0.2  0.2 390920 147572 ?       Ss   May23   3:16 postgres: 9.5/main: checkpointer process                                                                                    
postgres 18759  0.3  0.2 390384 145680 ?       Ss   May23   5:24 postgres: 9.5/main: writer process                                                                                          
postgres 18760  0.1  0.0 389392  9672 ?        Ss   May23   2:44 postgres: 9.5/main: wal writer process
```

The total number of processes is around 800. Summing up the resident memory usage on for postgres processes from `top` output gives about 10GB on a host which has a total memory of 52GB.

I am exporting the collecd output to influxdb and graphing using grafana. When I look at the value of the number of processes (processes_value) being reported, it matches what I see on the host. The value of memory usage reported (like ps_rss and ps_vm) should also match (or at least be near to 10GB) what I see on host.

## Actual behavior
The numbers that I see for ps_rss are way higher than the numbers I see manually, even higher than the total memory on the host. In above situation, the numbers that I see on grafana or influxdb are in range of 80 - 100 GB (where total memory on host is only 52GB). The value of ps_vm is also high in similar proportions.

**Comment by rubenk** [comment]
Please try to reproduce this with a recent version of Collectd. We don't support 5.4 anymore.

**Comment by ashu210890** [comment]
Tried this with 5.5 which is the latest available in Ubuntu and facing the same issue. If 5.5 is also not supported, I'll have to compile a higher version from source.

**Comment by rubenk** [comment]
5.5 is also not supported. We have binary packages available at https://github.com/collectd/collectd-ci so you don't have to compile from source.

**Comment by ashu210890** [comment]
Tried with 5.7; same issue.

**Comment by rpv-tomsk** [comment]
Can you please try 5.8 version? There was changes in `processes` plugin.
