### ISSUE TITLE
virt: allows to build HosthameFormat with information from libvirt metadata

### ISSUE THREAD

**Issue by sileht** [collectd/collectd#2805]
Hi,

Some application that creates libvirt virtual machine, adds some metadata [1] about the instances.

Currently we can only use the "name" or "uuid". It would be nice to use any information from metadata section.

For example, Openstack nova generate this kind of metadata: 

```
  <metadata>
    <nova:instance xmlns:nova="http://openstack.org/nova/instance/1">
      <nova:package version="2014.2.3"/>
      <nova:name>demo1vm</nova:name>
        ....
    </nova:instance>
  </metadata>
```

Add I would like to get the `<nova:instance><nova:name>` attribute into `HostnameFormat`.

Does a contribution that allow this will be accepted ?

Like a new choice for `HostnameFormat` called `metadata` and a new option called `HostnameMetadataXPath` with xpath notation to get the attribute like: 
`/nova:instance/nova:name` ?

Regards,
sileht

[1] https://libvirt.org/formatdomain.html#elementsMetadata

**Comment by atyronesmith** [comment]
Would something like the following be acceptable?

<Plugin "virt">
  Connection "qemu:///system"
  RefreshInterval 3600
  ExtraStats "cpu_util disk_err domain_state fs_info job_stats_background perf vcpupin"
  HostnameFormat "name friendly_name hostname"
</Plugin>

will produce...

"instance-000036e0" "test-gnocchi-3" "compute-01"

**Comment by sileht** [comment]
@atyronesmith  `friendly_name` meaning is not clear, this doesn't mean anything for libvirt. (While I known it's the Openstack nova display_name in our context), so 'openstack' looks clearer for me, but that very specific.

My proposal is more generic and will work with any libvirt upper layer application that use metadata system of libvirt, it will looks like:
```
<Plugin "virt">
HostnameFormat "name metadata hostname"
HostnameMetadataXPath "/nova:instance/nova:name"
</Plugin>
```

And will produce the same output:
`instance-000036e0 test-gnocchi-3 compute-01`

I'm OK with the generic or the specific version.

**Comment by sileht** [comment]
@atyronesmith, yes, we could do something to extract multiple metadata. But remember that in collectd `hostname` is always truncated to 62 chars, so can't really put many of them.

**Comment by atyronesmith** [comment]
Yes. Names may be truncated...

How about going with your suggestion with
HostnameMetadataXPath an optional parameter 
defaulting to  "/nova:instance/nova:name"?
