### ISSUE TITLE
MetaData in write_prometheus plugin

### ISSUE THREAD

**Issue by yanivlavi** [collectd/collectd#2809]
*   Version of collectd: 5.8.0
*   Operating system / distribution: fc

## Expected behavior

Metadata should be added to metrics in write_prometheus format as labels.

## Actual behavior

MetaData is missing.

## Steps to reproduce

*   Setup collectd with write_prometheus plugin
*   Check output

**Comment by octo** [comment]
Closing in favor of #2940 which has a bit more information.
