### ISSUE TITLE
Redis Plugin fails to parse INFO output properly

### ISSUE THREAD

**Issue by Susurrus19** [collectd/collectd#2812]
*   Version of collectd: 5.8.0-3
*   Operating system / distribution: CentOS Linux release 7.4.1708

## Expected behavior
After enabling the plugin and setting the configuration to use <Query "INFO">, `/var/log/messages` would be clear and the metrics would be reported.

## Actual behavior
Most metrics are reported, then a failure to parse appears in the logs.

*notes an inability to parse the '#*
> Jun  8 19:11:46 redis-general001 collectd[13261]: parse_value: Failed to parse string as gauge: "# Server
> redis_version:3.2.3
> redis_git_sha1:00000000
> redis_git_dirty:0
<*snipped*>
> maxmemory_policy:allkeys-lru
> mem_fragmentation_ratio:1.03
> mem_allocator:
> Jun  8 19:11:36 redis-general001 collectd[13261]: redis plugin: Unable to parse field `gauge'.

*then breaks here*

Plugin configuration
```
LoadPlugin redis
<Plugin "redis">
  <Node "dev">
    Host "localhost"
    Port "6379"
    Timeout 2000
    Password "..."
    <Query "INFO">
    </Query>
  </Node>
</Plugin>
```

## Steps to reproduce

*   step 1
Assuming nearly the same environment, install `collectd-redis.x86_64 : Redis plugin for collectd Version     : 5.8.0`
*   step 2
Configure plugin as above
*   step 3
Monitor `/var/log/messages`

**Comment by Susurrus19** [comment]
Hey Pavel!

I am not sure I have the expertise to test it, but I will give it a shot. I have been using the version from the RPM in Cent7. 

As for the plugin itself delivering `INFO`, that was not what I observed. I had the plugin loaded and configured without a `Query` and there was no reporting happening. Then I added the `INFO` query and metrics began flowing.

Let me see what I can get working with your changes, and get back to you here.

**Comment by rpv-tomsk** [comment]
Today I added collection of some more metrics from Redis server.
These include:

CPU usage statistics (from `INFO cpu`, like in memcached plugin)
Commands statistics  (from `INFO commandstats`, details are on https://redis.io/commands/info).

Examples:
CPU usage:
![redis_cpu](https://user-images.githubusercontent.com/13328211/41543065-689a0d0c-7340-11e8-98fe-60f67084566a.png)

Commands rate:
![redis_commands](https://user-images.githubusercontent.com/13328211/41543066-68c9cbd2-7340-11e8-8532-a6a6984d06b5.png)

Commands CPU usage statistics:
![redis_commands_time](https://user-images.githubusercontent.com/13328211/41543067-68f4d37c-7340-11e8-8978-842ceb241b27.png)

**Comment by rpv-tomsk** [comment]
>I am not sure I have the expertise to test it, 

You just have to use it and confirm it us useful and works perfectly. 

If you have questions, feel free to ask.
Thanks.

**Comment by rpv-tomsk** [comment]
Sources can be downloaded from https://github.com/rpv-tomsk/collectd/commits/collectd-master

**Comment by Susurrus19** [comment]
Great!

For something like `INFO commandstats` or `INFO all` for that matter, would I have to use a `Query` block to get those? If not, how does it get access to the 'extra' `INFO` information?

**Comment by rpv-tomsk** [comment]
No, `Query` block is not needed.

New option was added: `ReportCommandStats`.

```
<Plugin redis>
    <Node "example">
        Host "localhost"
        Port "1111"
        ReportCommandStats true
    </Node>
</Plugin>
```

**Comment by rpv-tomsk** [comment]
CPU usage is reported all the time. I will add option for it too, tomorrow,

**Comment by Susurrus19** [comment]
After building and installing, I get
`redis plugin: Option 'ReportCommandStats' not allowed inside a 'Node' block. I'll ignore this option.`
when collectd starts up.

**Comment by Susurrus19** [comment]
On line 7288 it says 

> Server state is requested by sending INFO query.

So I do need the `INFO` query, correct?

**Comment by Susurrus19** [comment]
Ugh... grabbed the wrong branch initially. Rebuilding and installing. My apologies for the confusion.

**Comment by Susurrus19** [comment]
Upon building the correct source: I am getting `INFO` and `CPU` stats as you would expect, and no longer getting the messages in `/var/log/messages`

With my config set as:
```
LoadPlugin redis

<Plugin "redis">
  <Node "info">
    Host "localhost"
    Port "6379"
    Password "[redacted]"
    ReportCommandStats true
  </Node>
</Plugin>
```

I am not getting any command stats, though command line output has:
```
cmdstat_get:calls=2218000,usec=1884925,usec_per_call=0.85
cmdstat_set:calls=1846605,usec=3470604,usec_per_call=1.88
cmdstat_setex:calls=10191079,usec=43005970,usec_per_call=4.22
cmdstat_del:calls=2023063,usec=7065143,usec_per_call=3.49
cmdstat_exists:calls=11,usec=175,usec_per_call=15.91
cmdstat_rpush:calls=208,usec=4778,usec_per_call=22.97
cmdstat_zadd:calls=208,usec=4420,usec_per_call=21.25
cmdstat_select:calls=151,usec=171,usec_per_call=1.13
cmdstat_auth:calls=63579,usec=168392,usec_per_call=2.65
cmdstat_ping:calls=2483,usec=837,usec_per_call=0.34
cmdstat_flushall:calls=1,usec=12744826,usec_per_call=12744826.00
cmdstat_info:calls=117609,usec=5883661,usec_per_call=50.03
cmdstat_slaveof:calls=2,usec=564,usec_per_call=282.00
cmdstat_command:calls=5,usec=2789,usec_per_call=557.80
```

Anything else I should look for?

**Comment by rpv-tomsk** [comment]
Maybe this is related to `types.db` update?
If you send metrics to another Collectd server, Types needs to be updated on all involved Collect instances.

**Comment by Susurrus19** [comment]
The metrics are sent to Graphite directly. Here are the relevant lines from `types.db`

> cat /usr/share/collectd/types.db | grep command
> commands                value:DERIVE:0:U
> ...
> redis_command_cputime   value:DERIVE:0:U

So types.db is updated, but I am not seeing commandstats in Graphite. I have `ps_cputime-children` and `ps_cputime-daemon` as new folders/data points, so the plugin is working.

**Comment by rpv-tomsk** [comment]
Hmm, it becomes hard to help with this. I don't know graphite well.

Are you use `carbon`? Did you check `/var/lib/graphite/whisper/` for metrics?
Did you check logs, related to graphite?

I have Graphite installation, so will check this tomorrow.

**Comment by Susurrus19** [comment]
Yes, `carbon` is in use. 

In `/var/graphite/storage/whisper` I have these values:
```
blocked_clients.wsp
cache_result-hits.wsp
cache_result-misses.wsp
current_connections-clients.wsp
current_connections-slaves.wsp
evicted_keys.wsp
expired_keys.wsp
memory_lua.wsp
memory.wsp
operations_per_second.wsp
ps_cputime-children < directory
ps_cputime-daemon < directory
pubsub-channels.wsp
pubsub-patterns.wsp
records-0.wsp
total_bytes-input.wsp
total_bytes-output.wsp
total_connections.wsp
total_operations.wsp
uptime.wsp
volatile_changes.wsp
```

**Comment by Susurrus19** [comment]
Here's a `tcpdump` snippet:

> redis....	
> info.....
> memory_lua...............@......[...j.....
> volatile_changes..............nA......[...q.....
> total_connections..............XH......[...w.....
> total_operations...............+......[...}m....
> operations_per_second......................[.........
> expired_keys............../.......[....j....
> evicted_keys......................[.........
> pubsub.....
> channels......................[.........
> patterns......................[.........
> current_connections.....
> slaves......................[.........
> cache_result....	
> hits......................[.........
> misses.............!E0......[....N....
> total_bytes....
> input............Z..(......[....7....
> output...............]......[....k....
> ps_cputime.....
> daemon.............&.;`....#.V.......[.........
> children...............................[.... ....
> records.....0...............@......[...U.....
> commands.....
> get.............!........[...d.....
> redis_command_cputime......................[.........
> commands.....
> set..............-M......[....f....
> redis_command_cputime.............4........[.........
> commands....
> setex......................[....Y....
> redis_command_cputime..............8.......[.........
> commands.....
> del......................[.........
> redis_command_cputime.............k.7

I can see the `commandstats` being sent, so somehow they are not arriving in graphite.

**Comment by rpv-tomsk** [comment]
>I can see the commandstats being sent, so somehow they are not arriving in graphite.

So, the problem is outside of Collect, right? )

**Comment by Susurrus19** [comment]
It does appear that way. Looking into what the blocker is.

**Comment by Susurrus19** [comment]
Oof, forgot to reply here...
The problem is as you suspected. I needed to update the `types.db` on Graphite as well. Once that was done, all the metrics began to show up.

**Comment by rpv-tomsk** [comment]
Added new PR, #2838 - you might be interested to check this feature.

Thanks.
