### ISSUE TITLE
liblvm2app used by lvm plugin is deprecated and will be removed

### ISSUE THREAD

**Issue by csonto** [collectd/collectd#2820]
The lvm plugin is using deprecated liblvm2app. This is deprecated and D-Bus API is preferred way to interact with LVM2. Alternatively, CLI with JSON formatted output can be used (see e.g. `lvs --reportformat json`.)

There is no migration guide at the moment. If any help is needed I am happy to assist.

**Comment by rpv-tomsk** [comment]
Closed as duplicate of #2647.

Thanks for reporting!
