### ISSUE TITLE
Is intel_rdt plugin updated to get per PID statistics using libpqos-resctrl interface (kernel version>=4.14)

### ISSUE THREAD

**Issue by dakshinai** [collectd/collectd#2832]
*   Version of collectd:
*   Operating system / distribution:

## Expected behavior
Get LLC usage statistics per running process (pid)
(Description of the behavior / output that you expected)

## Actual behavior

(Description of the behavior / output that you observed)

## Steps to reproduce

*   step 1
*   step 2
*   step 3

**Comment by rubenk** [comment]
I'm sorry, but I don't understand your question. Can you please take a bit more effort to describe your issue?

**Comment by rubenk** [comment]
The plugin uses the version of the library you install yourself, so I guess if you need new functionality you'll need to update your libpqos library. If the plugin actually uses the new functionality I don't know, perhaps you can ask your colleagues from Intel who wrote the plugin?

**Comment by rubenk** [comment]
cc @serhiyx

**Comment by kwiatrox** [comment]
Update is in progress.
Currently intel_rdt plugin doesn't  support statistics per running process (pid).
