### ISSUE TITLE
When is the next release (minor) expected?

### ISSUE THREAD

**Issue by kwiatrox** [collectd/collectd#2835]
Hi,

Is there any high level plan when 5.8.1 will be released with all the fixes merged into 5.8?
I mean something more or less accurate like in two months, half year etc.
Do you have also any thoughts for 5.9? Is there any plan like next year or it is too early to ask?

Thanks for any answer.

@octo @rubenk @rpv-tomsk

**Comment by mrunge** [comment]
I'd be interested in both, 5.8.1 and 5.9 release.

There are like ~70 commits to 5.8 branch since the release and ~300 in master.

What would be required and how can we help?

**Comment by sunkuranganath** [comment]
Thanks @mrunge for bringing this up.
Its been about more than 6 months since the last release. I believe it would be a good timing for next release as there has been much activity. 
Would be happy to help to move this forward.

@octo @rpv-tomsk any comments?

**Comment by mrunge** [comment]
I prepared a changelog to speed up the release process

https://github.com/collectd/collectd/pull/2902
