### ISSUE TITLE
zfs_arc plugin: Reading kstat value "other_size" failed.

### ISSUE THREAD

**Issue by connection-reset** [collectd/collectd#2843]
*   Version of collectd: 5.8.0
*   Operating system / distribution: Arch Linux

## Expected behavior
ZFS on Linux 0.7 no longer has other_size in /proc/spl/kstat/zfs/arcstats, it got replaced with dbuf_size, dnode_size and bonus_size.
https://github.com/zfsonlinux/zfs/commit/25458cbef9e59ef9ee6a7e729ab2522ed308f88f

zfs_arc plugin should read those when other_size is missing.

## Actual behavior
```
parse_value: Failed to parse string as derive: "data".
zfs_arc plugin: `llist_search` failed for key: 'other_size'.
zfs_arc plugin: Reading kstat value "other_size" failed.
```

## Steps to reproduce
*   Install ZFS on Linux >= 0.7
*   LoadPlugin zfs_arc

**Comment by Farfaday** [comment]
The issue disappeared after I upgraded to 5.8.1

**Comment by jplitza** [comment]
It didn't disappear for me, as in my backend (InfluxDB) is still reporting an error every time collectd inserts the values:
```
lvl=info msg="Dropping point" log_id=XXX service=collectd name=zfs_arc error="NaN is an unsupported value for field value
```
