### ISSUE TITLE
write_prometheus: warning issued when starting the plugin

### ISSUE THREAD

**Issue by mrunge** [collectd/collectd#2849]
*   Version of collectd: 5.8.0
*   Operating system / distribution: CentOS 7, collectd-5.8.0-5 from centos-opstools repo

## Actual behavior
When starting up, a warning is printed in logs.

Warning: MHD_USE_THREAD_PER_CONNECTION must be used only with MHD_USE_INTERNAL_POLLING_THREAD. Flag MHD_USE_INTERNAL_POLLING_THREAD was added. Consider setting MHD_USE_INTERNAL_POLLING_THREAD explicitly.

**Comment by rpv-tomsk** [comment]
Patch will be added to Collectd-5.8 branch. 
Thanks for the report!
