### ISSUE TITLE
cross platform conversion from RRD to XML is not required if RRD data send over network?

### ISSUE THREAD

**Issue by sandheepb** [collectd/collectd#2853]
*   Version of collectd: collectd-5.8.0
*   Operating system / distribution: Ubuntu 14.04 and ARM_Linux

## Expected behavior

The RRD files generated on my ARM target board need to be send to Ubuntu machine using Network plugin and these RRD files has to be plotted on Grafana running on same Ubuntu machine. I am trying live update of RRD files of ARM board on my Ubuntu machine.

## Actual behavior

The RRD files generated on ARM target board (Client) is received on Ubuntu machine (Server) when I configured the Client and server as per https://collectd.org/wiki/index.php/Networking_introduction.
I was able to plot the data on Grafana also successfully.

But when I was manually copying these RRD files (rather than using Network plugin), from the ARM target board to Ubuntu PC, I was getting the below error,
ERROR: reached EOF while loading header rrd->ds_def
For solving this error, I had to convert the RRD file to XML file in ARM target board, copy the XML file to Ubuntu machine and then restore the RRD file from the XML file using the rrdtool. I thought the same conversion has to be done when I was doing the live update via 'Network' plugin. I am happy to see, that is not required.
So I just want to confirm that, conversion from RRD to XML and XML to RRD not required when I am sending the collectd data from ARM target to Linux machine via Network plugin?

## Steps to reproduce

NA

**Comment by rpv-tomsk** [comment]
>So I just want to confirm that, conversion from RRD to XML and XML to RRD not required when I am sending the collectd data from ARM target to Linux machine via Network plugin?

When sending collectd data via `network` plugin, data is transferred via internal protocol, without any use of RRD library. So, no conversion is required.

**Comment by sandheepb** [comment]
Hi,
Thanks for confirming it.
