### ISSUE TITLE
ovs_stats plugin does not collect dpdk interface statistics if under bond interface

### ISSUE THREAD

**Issue by mrunge** [collectd/collectd#2858]
*   Version of collectd:
*   Operating system / distribution:
collectd 5.8.0 / CentOS

## Expected behavior

copied from https://jira.opnfv.org/projects/BAROMETER/issues/BAROMETER-92?filter=allopenissues

The ovs stats plugin collects the right set of data in case the dpdk interfaces are mapped directly under the ovs bridge. But for the use case where a bonding interface is needed underneath the ovs bridge, ovs stats cannot pull the dpdk interface statistics.

More copy/pasting from the linked issue:

$ ovs-vsctl show

Bridge "br0"
Port "br0"
Interface "br0"
type: internal
Port dpdkbond <---------- Port Name
Interface "dpdk0" <---------- Associated Interface name
type: dpdk
options: {dpdk-devargs="0000:05:00.0"}
Interface "dpdk1" <---------- Associated Interface name
type: dpdk
options: {dpdk-devargs="0000:05:00.1"}

What I think is happening here is that OVS stats plugin in this case will request stats for the port with name ‘dpdkbond’ (or the uuid associated with the bonded port) rather than requesting stats for the associated interfaces  ‘dpdk0’ or ‘dpdk1’.

If this is the case there are 2 possible solutions for this

1. Extend OVS to provide aggregate statistics for bond ports, would require modification to OVS source. Not sure this is the correct approach as it does not just affect DPDK ports and will susceptible to much larger input and validation for the non DPDK usecases across the OVS community. I think there is also an argument against providing aggregate stats in the case where the bond is in different modes (load balncing, fail over etc). To my mind it would still be preferable to query the associated interfaces for clarity as regards how traffic is balanced or if a failure has occurred that warrants the back up interface being used.
2. Modify the ovs_stats plugin in collectd to detect if a port is a ‘bond’ port, if so then get the associated interfaces and use them when gathering stats (i.e. use interface name/UUIDs instead of port name/UUID). I think this is the better approach. The ovsdb-client already provides the ability to detect if a port is bonded and lists the associated interfaces with ‘ovsdb-client dump Port’, one would only have to parse for an entry in the ‘bond_active_slave’ column and if this is true then it’s a bonded port, parse the interface entries from the ‘interfaces’ column in that row. 

 

I think option number 2 would be the preferred option as it will work with the existing OVS behavior for bonded ports.

**Comment by abays** [comment]
I have addressed this in pull request #2865

**Comment by abays** [comment]
And yet a third version of a fix for this issue: https://github.com/collectd/collectd/pull/2880

...now with support for reporting individual interface statistics in addition to port statistics.

**Comment by rpv-tomsk** [comment]
Closed in #2880.

Thanks for using Collectd.
