### ISSUE TITLE
How we can see the CPU usage of processes as percentage?

### ISSUE THREAD

**Issue by sandheepb** [collectd/collectd#2862]
*   Version of collectd: collectd-5.8.0
*   Operating system / distribution: Ubuntu 14.04 and ARM_Linux

## Expected behavior
I am monitoring the CPU usage of different processes running on the target board (using Processes plugin)
I would like to see the user and system CPU usage of the processes in percentage.

## Actual behavior
The user and system CPU usage of the processes are displayed as some numbers (like MAX = 6.88 K ) in grafana.

How we can see the CPU usage of processes as percentage?

**Comment by rpv-tomsk** [comment]
Hi!

Processes plugin, like other plugins, report `ps_cputime` metric in microseconds of used CPU time.
So, value of 1 000 000 is 100% of one core.
If you need to know percentage related to all available CPU, when you have to divide this value to number of available cores.

Maybe we need to add a metric for number of available cores for simplifier solution of this task.

**Comment by rpv-tomsk** [comment]
>In my case, the interval is set to 20 in the collectd.conf file. So should I divide the value by 20 also?

Default Interval value is 10, but I don't remember we have to divide by 10.
AFAIK, Collectd knows about interval when it produces `DERIVE` values, so, as said before, value is `microseconds of used CPU core per second of real time`.

>Is there any method to get the sum of user and system time of these processes?

AFAIK, Graphana can to do math.?

**Comment by faxm0dem** [comment]
No need to divide by interval.
And to confirm what @rpv-tomsk said: you can either stack the two series in grafana, or your datasource might do the math for you
