### ISSUE TITLE
Collectd reports CPU usage in percentage when both ReportByCpu and ReportByState are false?

### ISSUE THREAD

**Issue by sandheepb** [collectd/collectd#2863]
*   Version of collectd: collectd-5.8.0
*   Operating system / distribution: Ubuntu 14.04 and ARM_Linux

I have few doubts regarding CPU plugin. Part of the collectd.conf is given below.

  Interval 20
  ReportByState = false
  ReportByCpu = false
  ValuesPercentage = true

Query1:
Since the ValuesPercentage  is set to true, I hope the values that I get in the RRD file will be the **percentage** values of CPU usage. Could you please confirm it?
(Because, I read that "This option is only considered when both, ReportByCpu and ReportByState are set to true" from the link https://collectd.org/documentation/manpages/collectd.conf.5.shtml#plugin_cpu)

Query2:
In the config file, the interval is set to 20. So the samples present in the percent-active.rrd/percent-active.xml is average of 20 seconds or is it the value read from the /proc file system at that moment?

			 <row><v>5.5273921209e+00</v></row>
			 <row><v>4.8439373396e+00</v></row>
			 <row><v>5.1920463534e+00</v></row>
			 <row><v>5.9631400248e+00</v></row>
			 <row><v>5.3061693432e+00</v></row>
			 <row><v>4.9525653415e+00</v></row>
			 <row><v>5.3929248831e+00</v></row>

**Comment by faxm0dem** [comment]
Yes using your config, collectd will report percentages. You can see this easily read the *type* is *percent* as opposed to *cpu*.
As for your second question, rrdtool will output aggregated values, which depend on the RRA (rrdtool archive) you're requesting. This might be an average, minimum or maximum or any other *cfunc* (rrdtool concept).

**Comment by rpv-tomsk** [comment]
>Query2:
>In the config file, the interval is set to 20. So the samples present in the percent-active.rrd/percent-active.xml is average of 20 seconds or is it the value read from the /proc file system at that moment?

For DERIVE types Collectd will send delta between previous and next readings.

**Comment by rpv-tomsk** [comment]
UPD: ... divided by interval value.
