### ISSUE TITLE
Out-of-process plugin that receives data from collectd the moment it is generated

### ISSUE THREAD

**Issue by jimis** [collectd/collectd#2866]
I want to write a plugin that opens a connection to a server and sends some
data. Ideally this plugin would run as a different process, mostly for
security because it communicates over the network and because it is considered
untrusted, so I do not want it to have access to collectd's state..

First thought was to create an external process that listens to a unix socket,
communicating with collectd with the **unixsock plugin**. Turns out is not a
viable solution as there is no way for collectd to initiate PUTVALs of the
data as it is generated. And it would be too much resource consuming to do
GETVAL from the plugin every second or so (polling).

Second thought was write an external process listening to a localhost UDP
port, waiting for data from collectd's **network plugin**. It turns out that
the network plugin writes data to a buffer, and flushes the buffer sending an
actual UDP packet only when it is full, so there is no guarantee that the
generated data does not take long to arrive to the external process.

AFAICT the only way for an external process to receive the data immediately is
to enable the CSV plugin and monitor the directory for file changes. Is there
a better way that I don't see?

The most straightforward way to resolve this IMHO would be to have a new
plugin of "write" type that initiates a PUTVAL over a unix socket for each
value generated. How does that sound? Would that be a desirable contribution?
What are your first thoughts regarding issues implementing this?

**Comment by rpv-tomsk** [comment]
Hi!

1) You can write your plugin as generic Collectd plugin (w/o implementing separate daemon), and use your plugin in separate Collectd instance, running with required privileges. You were still going to run a separate daemon...

2) You can use `network` plugin to send metrics from your "core Collectd" to your "write_plugin Collectd".
When there is much metrics, then there will be no problem with buffering.
When there is small amount of metrics, then you can configure options `FlushInterval` and `FlushTimeout` so data does not take long in buffer.

**Comment by jimis** [comment]
Thanks @rpv-tomsk !

Regarding (1) is there an existing example for that? Treating third-party software as untrusted requires running it as non-root, and even running it inside a chroot jail. This probably restricts quite a bit the amount of information that can be collected from that software, so I was hoping that the well established and trusted distro-included version of collectd would do the data collection as root.

Regarding (2) I gave up early on the network plugin idea because of higher complexity. A client for the `unixsock` plugin is by far the easiest to implement (simple text protocol) so I had decided to do polling (GETVAL) every second for new values. I might give the network plugin another try now, but with a custom `flushinterval` of 1 second, thanks for the tip!

> When there is much metrics, then there will be no problem with buffering.

AFAICT there will always be a "tail" of metrics after the last `send()` call, that will be delayed until new metrics come in another 10 seconds. Am I missing something?

**Comment by rpv-tomsk** [comment]
>Regarding (1) is there an existing example for that? 

Example of what? You have Collectd sources, use them.

>I want to write a plugin that opens a connection to a server and sends some
data.

I missed your goals. Do you want to write plugin which receives (and process or relay them onward) or sends data (gathers some info from something and build metrics)?
What is the reasoning to put _your_ code into _separate_ and  _unprivileged_ process?

So, again. Run two Collectd instances. One as privileged, one as unprivileged.
Send metrics between these instances using `network` plugin. It is already implemented, so you don't need to reinvent this part of intercommunication. Use of `network` plugin can't be insecure for you, as you going to run both processes on the same host (otherwise, you can't to communicate them via sockets). You can setup firewall or use loopback interface to avoid external intervention.

**Comment by jimis** [comment]
> Regarding (1) is there an existing example for that?
>> Example of what?

Example of an existing network write plugin using a second unprivileged collectd.

But never mind, I got your point now. I hadn't realised that you suggested both a privileged and an unprivileged process to run on the same host.

>  What is the reasoning to put your code into separate and unprivileged process?
The plugin will be relaying data already gathered from collectd. The reason is security and reliability. A non-bundled collectd plugin is considered *untrusted* for whoever installs it, so restricting its privilege adds some confidence to install it on production servers.

Thanks for the feedback. Feel free to close the question then!

**Comment by rpv-tomsk** [comment]
Thanks for using Collectd,
With best wishes!
