### ISSUE TITLE
Unauthorized error on development articles in collectd website

### ISSUE THREAD

**Issue by sharanm** [collectd/collectd#2870]
Trying to view collectd architecture results in forbidden error.

Website: https://collectd.org/wiki/index.php/Plugin_architecture

Error: 403 Forbidden error
![image](https://user-images.githubusercontent.com/1888689/43032635-a017eeea-8cd9-11e8-91a8-a597151d8589.png)

**Comment by rpv-tomsk** [comment]
Closed as duplicate of #2868.
