### ISSUE TITLE
interval issue with the netapp plugin

### ISSUE THREAD

**Issue by llaurent** [collectd/collectd#288]
I'm using collectd 5.2.1 and the main interval is set to 60.

I've configured the netapp plugin with an interval of 300, I've followed the example from https://collectd.org/wiki/index.php/Plugin:NetApp and used "Interval 300" statements in every blocks (in the Host block as well as in its blocks)

In that case it doesn't collect netapp data every 5 minutes as expected. it constantly skips 1 or 2 interval.
Here's an graph example to illustrate the behavior:  http://imgur.com/wfg2grO

**Comment by sunkuranganath** [comment]
@cdorbell do you still see this as relevant today?

**Comment by sunkuranganath** [comment]
The versions of Collectd mentioned here are not supported anymore.
Please recheck the issue with supported versions of Collectd (5.10 and 5.11).
