### ISSUE TITLE
couldn't get data from virt plugin

### ISSUE THREAD

**Issue by yusong0926** [collectd/collectd#2881]
collectd is running in a centos7 container from barometer project
https://github.com/opnfv/barometer/tree/stable/fraser/docker/barometer-collectd

LoadPlugin virt
<Plugin virt>
        Connection "qemu:///system"
        RefreshInterval 60
        Domain "name"
        BlockDevice "name:device"
        BlockDeviceFormat target
        BlockDeviceFormatBasename false
        InterfaceDevice "name:device"
        IgnoreSelected false
        HostnameFormat name
        InterfaceFormat name
        PluginInstanceFormat name
        Instances 1
        ExtraStats "cpu_util disk disk_err domain_state fs_info job_stats_background pcpu perf vcpupin"
</Plugin>

# virsh -c  qemu:///system list
 Id    Name                           State
----------------------------------------------------
 12    instance-00000005              running
 13    instance-00000003              running
 14    instance-00000004              running
 15    instance-00000001              running
 16    instance-00000002              running
 17    instance-00000007              running

**Comment by sunkuranganath** [comment]
@yusong0926 Its better to submit the issue under Barometer Jira items for Barometer community to help you: https://jira.opnfv.org/projects/BAROMETER/issues/BAROMETER-98?filter=allopenissues
