### ISSUE TITLE
plugin isn't loaded

### ISSUE THREAD

**Issue by MinhKMA** [collectd/collectd#2884]
Hello, 
I used collectd on CentOS7. I enable plugin virt and i receive a line log 
```Found a configuration for the `virt' plugin, but the plugin isn't loaded or didn't register a configuration callback.```

I config virt plugin and use collect 5.8:
```sh
<Plugin virt>
    RefreshInterval 120
    Connection "qemu:///system"
    HostnameFormat "uuid"
    InterfaceFormat "address"
</Plugin>
```
Thank you.

**Comment by rubenk** [comment]
Have you installed the collectd-virt rpm?

**Comment by MinhKMA** [comment]
I think I have not installed it yet. how to install the collectd-virt rpm? 
Could you guide me?

**Comment by MinhKMA** [comment]
if i install  the collectd-virt rpm the i need install collect ?

**Comment by MinhKMA** [comment]
yes. i installed. Thank you for sp
