### ISSUE TITLE
Error with make during installation in CentOS

### ISSUE THREAD

**Issue by ShawnTheCoder** [collectd/collectd#2892]
*   Version of collectd:5.8.0
*   Operating system / distribution:CentOS Linux release 7.4.170

After downloading the source code and run ./configure, there's error message during "make".

`[root@dhcp-10-173-66-167 collectd-5.8.0]# make`
`make  all-am`
`make[1]: Entering directory /usr/share/collectd-5.8.0'`
`  CCLD     python.la`
`/usr/bin/ld: /usr/local/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6m.a(abstract.o): relocation R_X86_64_32S against _Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC`
`/usr/local/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6m.a: error adding symbols: Bad value`
`collect2: error: ld returned 1 exit status`
`make[1]: *** [python.la] Error 1`
`make[1]: Leaving directory /usr/share/collectd-5.8.0'`
`make: *** [all] Error 2`

Thanks in advance.

**Comment by rubenk** [comment]
First please don't compile software as root.

You have a locally installed static libpython in /usr/local/lib and the linker is telling you it can't link against that. This is not a collectd issue and a configuration we support.
