### ISSUE TITLE
MongoDB write plugin failed: undefined symbol: bson_new

### ISSUE THREAD

**Issue by laszlo-laszlo** [collectd/collectd#2900]
*   Version of collectd: 5.8.0
*   Operating system / distribution: CentOS Linux release 7.5.1804 (Core) 

## Expected behavior
Collectd write to MongoDB

## Actual behavior
Collectd can not load mongodb writer plugin because:
collectd[2435]: dlopen ("/usr/lib64/collectd/write_mongodb.so") failed: /usr/lib64/collectd/write_mongodb.so: undefined symbol: bson_new.

## Steps to reproduce

*   Install collectd and collectd-write_mongodb
*   Enable and configure collectd mongodb writer plugin
*   Restart collectd service

**ldd /usr/lib64/collectd/write_mongodb.so**
	linux-vdso.so.1 =>  (0x00007ffec9b6f000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fe49feff000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fe4a04d0000)

**Comment by rpv-tomsk** [comment]
Where did you get packages?
I tried to look in https://mirror.yandex.ru/centos/7.5.1804/ but found no collectd packages at all.

If you can, please provide SRPM/spec for used build.

Thanks for using Collectd.

**Comment by octo** [comment]
Sounds like the package providing *libmongoc* is not installed, which points to a missing dependency of the collectd package. If that's the case, this needs to be fixed by the package maintainer.

**Comment by AnomalousBit** [comment]
I get the same error on Arch Linux when trying to recompile using the TRUNK build from the main repo (see `PKGBUILD` for full build configuration): https://git.archlinux.org/svntogit/community.git/tree/trunk?h=packages/collectd

`./configure` returns success for locating & installing the required libs:
```
libmongoc . . . . . . yes
write_mongodb . . . . yes
libtool: install: /usr/bin/install -c .libs/write_mongodb.so /home/user/src/collectd/trunk/pkg/collectd/usr/lib/collectd/write_mongodb.so                                                   
libtool: install: /usr/bin/install -c .libs/write_mongodb.lai /home/user/src/collectd/trunk/pkg/collectd/usr/lib/collectd/write_mongodb.la 
```

But when starting collectd with the write_mongodb plugin, the logs reveal:
```
plugin_load: Load plugin "write_mongodb" failed with status 1.
dlopen ("/usr/lib/collectd/write_mongodb.so") failed: /usr/lib/collectd/write_mongodb.so: undefined symbol: bson_new.  The most common cause for this problem is missing dependencies. Use ldd(1) to check the dependencies of the plugin / shared object.
```

Following the suggestion from the error presented by collectd, `ldd` doesn't show the `libmongoc-1.0.so` dependency as I would expect but maybe collectd is linking the lib statically into write_mongodb.so? Here's the `ldd` output:
```
[user@computer trunk]# ldd /usr/lib/collectd/write_mongodb.so
        linux-vdso.so.1 (0x00007fffec114000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f1067706000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007f1067908000)
```
Any thoughts? Happy to test things out if there are suggestions? Thanks!

**Comment by rpv-tomsk** [comment]
Added patches to solve this issue.

Thanks for reporting this!
Thanks for using Collectd!

**Comment by rpv-tomsk** [comment]
Now:
```
root@hs01:~/srv01/github/collectd/.libs# ldd ./write_mongodb.so
        linux-gate.so.1 (0xb77b3000)
        libmongoc-1.0.so.0 => /usr/lib/i386-linux-gnu/libmongoc-1.0.so.0 (0xb7742000)
        libssl.so.1.0.0 => /usr/lib/i386-linux-gnu/i686/cmov/libssl.so.1.0.0 (0xb76e7000)
        libcrypto.so.1.0.0 => /usr/lib/i386-linux-gnu/i686/cmov/libcrypto.so.1.0.0 (0xb7525000)
        librt.so.1 => /lib/i386-linux-gnu/i686/nosegneg/librt.so.1 (0xb751b000)
        libbson-1.0.so.0 => /usr/lib/i386-linux-gnu/libbson-1.0.so.0 (0xb74f2000)
        libc.so.6 => /lib/i386-linux-gnu/i686/nosegneg/libc.so.6 (0xb7342000)
        libssl.so.1.1 => /usr/lib/i386-linux-gnu/libssl.so.1.1 (0xb72d3000)
        libcrypto.so.1.1 => /usr/lib/i386-linux-gnu/libcrypto.so.1.1 (0xb7066000)
        libdl.so.2 => /lib/i386-linux-gnu/i686/nosegneg/libdl.so.2 (0xb7060000)
        libz.so.1 => /lib/i386-linux-gnu/libz.so.1 (0xb7047000)
        libpthread.so.0 => /lib/i386-linux-gnu/i686/nosegneg/libpthread.so.0 (0xb702b000)
        libyajl.so.2 => /usr/lib/i386-linux-gnu/libyajl.so.2 (0xb7020000)
        libatomic.so.1 => /usr/lib/i386-linux-gnu/libatomic.so.1 (0xb7019000)
        /lib/ld-linux.so.2 (0xb77b4000)
```

**Comment by AnomalousBit** [comment]
Thanks! This fixed the `write_mongodb` plugin for me.
