### ISSUE TITLE
lm-sensors power measurement not read by sensors plugin

### ISSUE THREAD

**Issue by PhilippWendler** [collectd/collectd#2905]
*   Version of collectd: 5.8.0.119.gca7b906
*   Operating system / distribution: Debian 9.5
*   Version of lm-sensors: 1:3.4.0-4

## Expected behavior

I have servers where running `sensors` shows two power sensors:
```
power_meter-acpi-0
Adapter: ACPI interface
power1:      165.00 W  (interval =   1.00 s)

power_meter-acpi-0
Adapter: ACPI interface
power1:      169.00 W  (interval =  60.00 s)
```

I want collectd to read these measurements and send them to my Graphite instance.  I assumed from seeing #571 that this should be working.

Maybe this is because `sensors` shows the same name for both sensors?
Because both values seem to refer to the total power of my system, it would be acceptable for me if at least one of these values would be read.

## Actual behavior

No power measurements appear in Graphite for my three (identical) servers. The temperature sensors all appear there, however.

There is no entry in the log from the `sensors` plugin (except that it gets successfully loaded on startup).

## Steps to reproduce

*   The servers are Fujitsu Primergy RX2540 M2.
*   Installed Debian with standard lm-sensors package and collectd from its official repository.
*   Put the following in `collectd.conf`:
```
LoadPlugin sensors
<Plugin sensors>
        UseLabels true
</Plugin>
```

**Comment by rpv-tomsk** [comment]
Hi!

I think you have to compile debug version of Collectd at some of this server and try to debug, that happens. Then we can try to patch code to solve your task or to get addititional info.

**Comment by PhilippWendler** [comment]
Ok, I will to do so when I have time.

**Comment by PhilippWendler** [comment]
Can this be reopened as it is a feature request for more lm-sensors readings?
