### ISSUE TITLE
question on the two different intervals in collectd-python

### ISSUE THREAD

**Issue by mwtzzz** [collectd/collectd#2909]
*   Version of collectd: 5.8.0
*   Operating system / distribution: Amzn Linux

Unclear from the man pages. 

In collectd-python, there appear to be two different intervals: one for how often the read_callback is called; a second one passed to Values.dispatch for how often the plugin will aggregate and submit metrics from the data source. 

If dispatch() is called from within my read_callback function, then how do these two intervals interact? I'm unclear as to what will happen if the callback function is called at a faster, or slower, rate than the interval passed to dispatch().

In fact, I'm unclear as to the need for passing an interval to dispatch(). If you give it a different value on subsequent calls for the same data source, how does that affect it? Does the python plugin maintain a single Values instance for a particular data source throughout the life of the plugin? 

---

In an effort to see how this works, I figured I'd enable write_log and take a look at exactly when and how a particular data source metric is being submitted. But write_log doesn't appear to do anything. My understanding is that it should log INFO messages to syslog.

Any help or pointers on the above would be appreciated.

**Comment by rpv-tomsk** [comment]
>In collectd-python, there appear to be two different intervals: one for how often the read_callback is called; 

That is expected to be the same value.

>My understanding is that it should log INFO messages to syslog.

The `write_log` plugin does not logs to syslog. It logs to Collectd logging system, so you have to use `logfile` or `syslog` plugin too.
