### ISSUE TITLE
postgresql plugin: Protocol version 0 error

### ISSUE THREAD

**Issue by dzaczek** [collectd/collectd#2912]
*   Version of collectd: 5.7.1 x64
*   Operating system / distribution:
Centos 6.10 x64
## Expected behavior
I want use collect  wit postgresql plugin to monitoring database 

## Actual behavior
Unfortunately  i can connect to database but when query have alias return information protocol version 0. Is something strange becaouse  connection log return version 3

> collectd[28377]: Successfully connected to database  dba721 (user xxx) at server 127.0.0.1:5432 (server version: 8.4.20, protocol version: 3, pid: 28388)
> collectd[28377]: postgresql: Protocol version 0 does not support parameters.
> collectd[28377]: db query utils: udb_result_prepare_result: The type `pg_blks' requires exactly 0 values, but the configuration specifies 1.
> collectd[28377]: postgresql: udb_query_prepare_result failed with status -1.

## Steps to reproduce
Unable  happens every time

**Comment by rpv-tomsk** [comment]
>but when query have alias

What do you mean by this?

To resolve this issue, I think,  you have to compile Collectd from sources, enable debug and possbile with adding some new lines of debug output. Can you do this?

**Comment by rpv-tomsk** [comment]
Closed due to lack of response.
