### ISSUE TITLE
Rates are not being calculated correctly for counter/derive metrics

### ISSUE THREAD

**Issue by mwtzzz** [collectd/collectd#2927]
I'm running collectd-5.8.0 with collectd-python on Amzn-Linux. I'm using two write plugins: csv and write_graphite.

I created a python plugin that uses `readline()` to get the contents of `/sys/class/net/eth0/statistics/rx_bytes`. I initialize a `Values()` object (`val = collectd.Values()`) and I convert the metric to a float with `val.values = [float(metricvalue)]`.  It then submits this value to collectd via `dispatch()`.

If I submit the value as a GAUGE (`val.type = "gauge"`), it gets written correctly, as you can see in the following csv output. Notice that the number of bytes between calls to `val.dispatch()` is around 100MB:
```
epoch,value
1536934300.383,34234147076610.000000
1536934325.294,34234237430674.000000
1536934350.297,34234338253342.000000
1536934375.295,34234424789588.000000
1536934400.300,34234522270292.000000
1536934425.294,34234612731142.000000

```

Therefore, we expect that, if we use COUNTER or DERIVE instead of gauge, the value that gets written should be around 100MB. But it's not. It's orders of magnitude smaller:. Instead of being 100MB, it's around 3.5MB:
```
epoch,value
1536934513.285,nan
1536934538.204,3805591.885356
1536934563.206,3613157.448816
1536934588.205,3888835.194179
1536934613.205,3499354.159286
1536934638.204,3946403.587505
1536934663.213,3749693.716931
```
I tried different things: using int instead of float, lopping off the leftmost portion of the metric value before submitting it, etc but the results are always the same. It happens with both write plugins, so the problem seems to be internal to collectd and/or the write plugins.

I tried turning on "info" logging to get more information, but it dumps so much stuff that syslog puts a freeze on it (rate limiting), so I wasn't able to learn anything useful.

Any thoughts?

**Comment by trenkel** [comment]
Looking at the GAUGE values, it seems to account for slightly less then 100MB in a 25 second interval. That's slightly less than 4MB per second. When using COUNTER you get an output for slightly less than 4MB per second. That seems to work out just fine as far as I can tell, the values match perfectly.

**Comment by mwtzzz** [comment]
Hang on. I'm dispatching both with the same frequency (25 second intervals). Why would the counter give me a per-second output instead of a per-25-second output?

**Comment by mwtzzz** [comment]
I assumed "counter" meant that two subsequent values were simply subtracted from eachother and that this value was what gets written. But... Are you saying that the two values are subtracted and divided by the interval, thereby always giving a per-second value?

**Comment by faxm0dem** [comment]
yes, that's the way it works

**Comment by mwtzzz** [comment]
Ok, thanks for the clarification. I'll use Graphite's scale() function to multiply by 60 for our graphs.
