### ISSUE TITLE
Support pull data model

### ISSUE THREAD

**Issue by sergeyglazyrindev** [collectd/collectd#2929]
Hello guys!
Would be interesting for you to support pull data model together with push ?
I think it will simplify and make collectd more suitable for collection tasks. Sometimes we need to get data on demand. For such purposes we may use prometheus but I see no reason to use prometheus to implement on demand data collection when we have in our system already collectd.
We may contribute such changeset to support pull model as well. And we may provide a spec for this.

**Comment by sunkuranganath** [comment]
@sergeyglazyrindev this is a very important topic we have an ongoing discussion in the Barometer community. Most of the prometheus users miss to realize importance of infrastructure metrics provided by collectd. How are you suggesting Collectd provide pull data model?

**Comment by mrunge** [comment]
@sergeyglazyrindev In my understanding, you could use the write_prometheus plugin to make data available to prometheus.

Could you describe a bit more, how you would like to use the pull model (and what would you like to pull)?

One issues I often hear about prometheus is, that it requires nodes to be scraped having open ports and listening. Operators are often asking for a push model in prometheus (like we have it in collectd).

**Comment by octo** [comment]
*write_prometheus* should do the trick. The *grpc* plugin should also be able to fix this niche.
