### ISSUE TITLE
Processes - Match space(s) in regex

### ISSUE THREAD

**Issue by CPS86** [collectd/collectd#2930]
Hey,

How to match multiple spaces and only spaces without any other special chars using the ProcessMatch paramter in the processes plugin? 

It seems that standard syntax doesn't work:
\s+
\s*
[:space:]

Version of Collectd 5.52 & 5.8

**Comment by CPS86** [comment]
Ok I managed to do this.
I used following to match spaces:

[   ] +


What about negative lookahead?
Tried all possible options and all that I get is 'compiling the regular expression failed' error... 

Is it possible to use it with collectd?

**Comment by octo** [comment]
We're using the standard POSIX extended regexes, which unfortunately don't have lookaheads / -behinds. Sorry!

**Comment by mhopa** [comment]
Hallo
Can you please explain, why the ProcessMatch does not match space (e.g.: \s+) even if POSIX standard regex is used?
