### ISSUE TITLE
RouterOS plugin is missing

### ISSUE THREAD

**Issue by podorozhny** [collectd/collectd#2931]
*   Version of collectd: 5.5 / 5.8
*   Operating system / distribution: ubuntu xenial

## Expected behavior

RouterOS plugin in default package plugins list.

## Actual behavior

Nope. Either on 5.5 from ubuntu repos or 5.8 from collectd repos.

## Steps to reproduce

*   `sudo apt install collectd`
*   `ls -la /usr/lib/collectd/ | grep -i routeros.so` # nothing

`LoadPlugin routeros` produce error in syslog: `plugin_load: Could not find plugin "routeros" in /usr/lib/collectd`

Any instruction on how to install it?

**Comment by halacs** [comment]
Hi,

I also face with the same issue. Can it happen that this issue is already solved?
It seems this issue is cca 2 years old so I'm so optimistic I will be able to contact my Mikrotik devices with collectd.

Thanks!
