### ISSUE TITLE
memcached: Getting current hitratio is not possible 

### ISSUE THREAD

**Issue by martinm82** [collectd/collectd#2943]
*   Version of collectd: 5.8.0
*   Operating system / distribution: Ubuntu Xenial

Our collectd daemon is pushing memcached metrics to influxdb. When trying to display the current hitratio it is not possible to gather that info from the time series.

I might be not understanding this value entirely but I have the feeling that it is somehow calculated not on the current get and miss rate.

How am I suppose to use the hitratio so that I can print for example in Grafana the current hitratio in total. Basically what I want to achieve is to mimic the phpmemcacheadmin dashboard with Grafana.

Example:
I would expect that hitratio is based on the get_hits/get_misses:

```
memstat --servers=srv01:9211 | grep get
         cmd_get: 84345
         get_hits: 63961
         get_misses: 20384
         get_expired: 0
         get_flushed: 0
```

but looking at the output of influxdb it is not:

```
> select * from memcached_value where host =~ /srv01/ and type_instance = 'hitratio'  order by desc limit 10
name: memcached_value
time                    host            instance        type    type_instance   value
----                    ----            --------        ----    -------------   -----
1539086962075937000     srv01   name            percent hitratio        0
1539086662075635000     srv01   name            percent hitratio        100
1539086542087723000     srv01   name            percent hitratio        100
1539086482066322000     srv01   name            percent hitratio        100
1539086362094875000     srv01   name            percent hitratio        100
1539086302082168000     srv01   name            percent hitratio        100
1539086242073983000     srv01   name            percent hitratio        100
1539086182093148000     srv01   name            percent hitratio        66.66666666666667
1539086122060761000     srv01   name            percent hitratio        50
1539085642096169000     srv01   name            percent hitratio        50
```

**Comment by rpv-tomsk** [comment]
In Collectd code the `hitratio` metric is based on `get_hits` and `cmd_get` values.
In each cycle, `hitratio` calculated as ratio of these values change (delta) per cycle time.

`hitratio = (get_hits - get_hits') / (cmd_get - cmd_get') `

As for me, existing implementation is correct and I get correct `hitratio` metric on my systems.

**Comment by martinm82** [comment]
I looked deeper into it and the problem is not in collectd but in influxdb which is creating the series. Basically the problem is that influxdb stores the get/set/misses/etc. metrics as tags. Doing that means that you cannot run any subquery since they work only on top of fields.

I saw that there is as well the current tag which stores the current items and connections. What about adding there as well the current total hitratio?

**Comment by rpv-tomsk** [comment]
>Don't you think it would make as well sense to provide the current total hitratio? 

![default](https://user-images.githubusercontent.com/13328211/46724480-50606e80-cca4-11e8-9360-eee9121f04ba.png)


No. "Current total hitratio" as `get_hits / cmd_get` has no sence. 
For long-running `memcached` process there will be huge values and hitratio will behave like constant and you will see straight line on chart. I see no practical use of  ' 90% of GET has HIT for last 6 months' value.

**Comment by rpv-tomsk** [comment]
>Maybe worth to document as well the provided metrics and what they actually mean.

We have no metrics documented for any plugins, AFAIK. But you can start this, patches are welcome.

**Comment by rpv-tomsk** [comment]
https://github.com/collectd/collectd/pull/2385

**Comment by martinm82** [comment]
Imagine this situation:
```
1: get_hits: 100  cmd_get: 200
2: get_hits: 101 cmd_get:201  -> 100% hitratio
3: get_hits: 101 cmd_get: 202 ->     0% hitratio
4: get_hits: 102 cmd_get: 203 -> 100% hitratio
```
As you can see you will have in the graph a jump to 0 making the graph not nice.

**Comment by rpv-tomsk** [comment]
>not nice.

But true.

**Comment by octo** [comment]
@martinm82 if you want to smooth the graph you would calculate the rate over, for example, 5 minutes instead the immediately previous data point. I don't know if InfluxDB supports this though.

**Comment by martinm82** [comment]
@rpv-tomsk, thinking longer about this you are actually right. It indeed reflects more the real reality then the total one.

@octo, yes, this is exactly what I did now next to the real hitratio.

Ticket can be closed
