### ISSUE TITLE
Recommendation on correcting static text in logging statement

### ISSUE THREAD

**Issue by niuxu18** [collectd/collectd#2956]
*  Collect-5.8.0:

Our team works on enhance logging practices by learning form historical log revisions.
We find two patches in collectd evolution which modified the typo ("malloc..." -> "calloc...")in log messages.
And we find two missed spots in collectd-5.8.0:

The missed spots are:
1. Line 1194 in  src/virt.c
  `virVcpuInfoPtrvinfo = calloc(nr_virt_cpu, sizeof(vinfo[0]));`
  `if (vinfo == NULL) {`
    `ERROR(PLUGIN_NAME " plugin: malloc failed.");`
   `return -1;`
  `}`
1. Line 1200 in src/virt.c
  `unsigned char *cpumaps = calloc(nr_virt_cpu, cpu_map_len);`
  `if (cpumaps == NULL) {`
    `ERROR(PLUGIN_NAME " plugin: malloc failed.");`
    `sfree(vinfo);`
    `return -1;`
  `}`

Corresponding patches that support our opinion are:
1.  Line 136 in collectd-5.5.3/src/collectd-nagios.c
 	`new_values = (gauge_t *)calloc (match_ds_num_g, sizeof (*new_values));`
 	`if (new_values == NULL)`
 	`{`
`-		fprintf (stderr, "malloc failed: %s\n", strerror (errno));`
`+		fprintf (stderr, "calloc failed: %s\n", strerror (errno));`
`		return (RET_UNKNOWN);`
` 	}`

1. Line 143 in collectd-5.5.3/src/collectd-nagios.c
 	`new_names = (char **)calloc (match_ds_num_g, sizeof (*new_names));`
 	`if (new_names == NULL)`
 	`{`
`-		fprintf (stderr, "malloc failed: %s\n", strerror (errno));`
`+		fprintf (stderr, "calloc failed: %s\n", strerror (errno));`
 		`free (new_values);`
 		`return (RET_UNKNOWN);`
 	`}`
 
Thanks for your reading and we are looking forward to your reply about the correctness of our finding ^^

**Comment by octo** [comment]
Hi @niuxu18,

thank you very much for looking at improving collectd's logs! The above patches look good; do you think you could create a pull request for them?

Thanks and best regards,
—octo

**Comment by niuxu18** [comment]
There is the [pull request](https://github.com/collectd/collectd/pull/2957). And thanks for your reply ^^
