### ISSUE TITLE
disk plugins doesn't seem to work correctly under iscsi booted machines.

### ISSUE THREAD

**Issue by xinminglai** [collectd/collectd#2977]
*   Version of collectd: 5.8.0
*   Operating system / distribution: gentoo

## Expected behavior

with the config which enables disk plugin, It should record disk stats.

## Actual behavior

collectd doesn't write data to /var/lib/collectd/hostname/ directory under iscsi booting system.

[collectd.conf.txt](https://github.com/collectd/collectd/files/2519753/collectd.conf.txt)

```
Hostname    "neptune"
Interval     10

LoadPlugin syslog
LoadPlugin disk
LoadPlugin memory
LoadPlugin rrdtool
LoadPlugin unixsock
<Plugin disk>
  Disk "sda"
  Disk "/^hd/"
  IgnoreSelected false
	# Disk "/^[hs]d[a-f][0-9]?$/"
	# Disk "/^zram[0-9]$/"
	# Disk "/^bcache[0-9]$/"
	# IgnoreSelected true
	# UseBSDName false
	# UdevNameAttr "DEVNAME"
</Plugin>

<Plugin syslog>
       LogLevel info
</Plugin>

<Plugin unixsock>
	SocketFile "/run/collectd/collectd.socket"
	SocketGroup "collectd"
	SocketPerms "0660"
	DeleteSocket false
</Plugin>
```

**Comment by rpv-tomsk** [comment]
In your config you have explicit selection of disks to record stats.

Can you please show output of `cat /proc/diskstats`?

**Comment by xinminglai** [comment]
[diskstats.txt](https://github.com/collectd/collectd/files/2521523/diskstats.txt)

Hi, This is the diskstats in the non-working machine, Please check.

**Comment by xinminglai** [comment]
[collectd-running-fg.log](https://github.com/collectd/collectd/files/2521602/collectd-running-fg.log)
[journalctl-collectd.log](https://github.com/collectd/collectd/files/2521603/journalctl-collectd.log)
[collectd.conf.txt](https://github.com/collectd/collectd/files/2521604/collectd.conf.txt)

Hi, These are the new logs I got. collectd-running-fg.log is log run with `collectd -C /etc/collectd.conf -f`
journalctl-collectd.log is got via journalctl -xef /usr/sbin/collectd
the config is the one I used.
Thanks!

**Comment by rpv-tomsk** [comment]
>Version of collectd: 5.8.0

Please use collectd-5.8.1. That has this issue fixed.
Please close this issue then resolved.

Thanks for using Collectd.

**Comment by xinminglai** [comment]
I found 5.8.1 fixed the issue. So, I'll close the issue.
Thanks a lot!
