### ISSUE TITLE
CPU Usage Report for a single process in %

### ISSUE THREAD

**Issue by DevNtesT** [collectd/collectd#3003]
Hello,

I am using Grafana with Influxdb and collectd to monitor my system.

I know that this is a question that has already been asked multiple times, but i have yet to find a real answer that works.

How can i track the CPU Usage which is given in (milliseconds) as a Percentage for a single process?
I don´t really understand how this can not be a setting in collectd as I am sure this is something that a lot of People would like to know about their systems, or if they test software.

If this only works via adding some calculation in the Grafana Query then it would be nice if someone can explain or show me an easy example on how to do this calculation. 
Or maybe even an example Query from Grafana.
Any help is appreciated!!

Thank you very much!

**Comment by faxm0dem** [comment]
IIRC the processes plugin will give you the value in microseconds so you have to multiply this by `1e8` to get a percentage. You might also have to divide by `nproc`.
