### ISSUE TITLE
collectd fails to compile with new GCC 7 or 8 on Debian

### ISSUE THREAD

**Issue by srivasta** [collectd/collectd#3038]
*   Version of collectd: Git master HEAD
*   Operating system / distribution: Drbian Sid
*   Kernel version (if applicable): 5.18
* gcc version:  (Debian 8.2.0-13) 8.2.0

## Expected behavior
  I expect compilation to succeed even with gcc 8.

## Actual behavior

Collectd fails to compile. The problems all seem to be with string handling. 

###################################################################
Take for example  src/libcollectdclient/network_parse.c: parse_string
 we check to see if payload is greater than the buffer size; but not equals; we are likely trying to steip the trailing nul. Unfortunately, the -Wstringop-truncation warning added in GCC 8.0 via r254630 for bug 81117 is specifically intended to highlight likely unintended uses of the strncpy function that truncate the terminating NUL character from the source string. 

I suggest adding the following pragmas
======================================================
#if defined(__GNUC__) || __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstringop-truncation"
#endif
  strncpy(....)

#if defined(__GNUC__) || __GNUC__
#pragma GCC diagnostic pop
#endif
======================================================
#####################################################

Here is a second one (this is a real bug waiting to happen)
#####################################################
src/collectdctl.c:169

  char hostname[1024];
  char ident_str[1024] = "";

....
    snprintf(ident_str, sizeof(ident_str), "%s/%s", hostname, value);
 So, if value is at least one char wide, we are pushing 1026 bytes into a 1024 byte destination, and there is no check.
#####################################################

## Steps to reproduce

*   step 1 git clone git@github.com:collectd/collectd.git; cd collectd
*   step 2 autoreconf -v -i && ./configure
*   step 3 make -k 

 make -k
make  all-am
make[1]: Entering directory '/usr/local/src/collectd'
  CC       src/libcollectdclient/libcollectdclient_la-network_parse.lo
In function parse_string,
    inlined from parse_identifier at src/libcollectdclient/network_parse.c:169:7,
    inlined from network_parse at src/libcollectdclient/network_parse.c:540:11:
src/libcollectdclient/network_parse.c:161:3: error: strncpy specified bound 64 equals destination size [-Werror=stringop-truncation]
   strncpy(out, in, out_size);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:6729: src/libcollectdclient/libcollectdclient_la-network_parse.lo] Error 1
  CC       src/collectdctl-collectdctl.o
src/collectdctl.c: In function parse_identifier:
src/collectdctl.c:169:50: error: snprintf output may be truncated before the last format character [-Werror=format-truncation=]
     snprintf(ident_str, sizeof(ident_str), "%s/%s", hostname, value);
                                                  ^
src/collectdctl.c:169:5: note: snprintf output 2 or more bytes (assuming 1025) into a destination of size 1024
     snprintf(ident_str, sizeof(ident_str), "%s/%s", hostname, value);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:7555: src/collectdctl-collectdctl.o] Error 1
  CC       src/liboauth_la-utils_oauth.lo
src/utils_oauth.c: In function new_token:
src/utils_oauth.c:353:67: error: %s directive output may be truncated writing up to 1023 bytes into a region of size 959 [-Werror=format-truncation=]
   snprintf(post_data, sizeof(post_data), "grant_type=%s&assertion=%s",
                                                                   ^~
            OAUTH_GRANT_TYPE, assertion);
                              ~~~~~~~~~                             
src/utils_oauth.c:353:3: note: snprintf output between 66 and 1089 bytes into a destination of size 1024
   snprintf(post_data, sizeof(post_data), "grant_type=%s&assertion=%s",
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            OAUTH_GRANT_TYPE, assertion);
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:6764: src/liboauth_la-utils_oauth.lo] Error 1
  CC       src/aggregation.lo
src/aggregation.c: In function agg_lookup_class_callback:
src/aggregation.c:202:20: error: %s directive output may be truncated writing 14 bytes into a region of size between 0 and 127 [-Werror=format-truncation=]
                "%s-%s", tmp_plugin, AGG_FUNC_PLACEHOLDER);
                    ^~
src/aggregation.c:201:7: note: snprintf output between 16 and 143 bytes into a destination of size 128
       snprintf(inst->ident.plugin_instance, sizeof(inst->ident.plugin_instance),
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                "%s-%s", tmp_plugin, AGG_FUNC_PLACEHOLDER);
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/aggregation.c:205:20: error: %s directive output may be truncated writing 14 bytes into a region of size between 0 and 127 [-Werror=format-truncation=]
                "%s-%s", tmp_plugin_instance, AGG_FUNC_PLACEHOLDER);
                    ^~
src/aggregation.c:204:7: note: snprintf output between 16 and 143 bytes into a destination of size 128
       snprintf(inst->ident.plugin_instance, sizeof(inst->ident.plugin_instance),
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                "%s-%s", tmp_plugin_instance, AGG_FUNC_PLACEHOLDER);
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:6455: src/aggregation.lo] Error 1
  CC       src/ovs_stats_la-ovs_stats.lo
src/ovs_stats.c: In function ovs_stats_submit_interfaces:
src/ovs_stats.c:283:49: error: snprintf output may be truncated before the last format character [-Werror=format-truncation=]
     snprintf(devname, sizeof(devname), "%s.%s.%s", bridge->name, port->name,
                                                 ^
src/ovs_stats.c:283:5: note: snprintf output 3 or more bytes (assuming 511) into a destination of size 510
     snprintf(devname, sizeof(devname), "%s.%s.%s", bridge->name, port->name,
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
              iface->name);
              ~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:7009: src/ovs_stats_la-ovs_stats.lo] Error 1
  CC       src/postgresql_la-utils_db_query.lo
src/utils_db_query.c: In function udb_result_submit.isra.4:
src/utils_db_query.c:231:66: error: snprintf output may be truncated before the last format character [-Werror=format-truncation=]
       snprintf(vl.type_instance, sizeof(vl.type_instance), "%s-%s",
                                                                  ^
src/utils_db_query.c:231:7: note: snprintf output 2 or more bytes (assuming 129) into a destination of size 128
       snprintf(vl.type_instance, sizeof(vl.type_instance), "%s-%s",
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                r->instance_prefix, tmp);
                ~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:7065: src/postgresql_la-utils_db_query.lo] Error 1
  CC       src/python_la-python.lo
src/python.c: In function cpy_interactive:
src/python.c:1136:3: error: PyOS_AfterFork is deprecated [-Werror=deprecated-declarations]
   PyOS_AfterFork();
   ^~~~~~~~~~~~~~
In file included from /usr/include/python3.7m/Python.h:134,
                 from src/python.c:27:
/usr/include/python3.7m/intrcheck.h:18:18: note: declared here
 PyAPI_FUNC(void) PyOS_AfterFork(void) Py_DEPRECATED(3.7);
                  ^~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:7079: src/python_la-python.lo] Error 1
  CC       src/protocols.lo
src/protocols.c: In function read_file:
src/protocols.c:157:51: error: %s directive output may be truncated writing up to 4095 bytes into a region of size 256 [-Werror=format-truncation=]
         snprintf(match_name, sizeof(match_name), "%s:%s", key_buffer,
                                                   ^~      ~~~~~~~~~~
src/protocols.c:157:9: note: snprintf output 2 or more bytes (assuming 4097) into a destination of size 256
         snprintf(match_name, sizeof(match_name), "%s:%s", key_buffer,
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  key_fields[i]);
                  ~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:6455: src/protocols.lo] Error 1
  CC       src/threshold.lo
src/threshold.c: In function ut_missing.part.1:
src/threshold.c:693:13: error: %s directive output may be truncated writing up to 767 bytes into a region of size 256 [-Werror=format-truncation=]
            "%s has not been updated for %.3f seconds.", identifier,
             ^~                                          ~~~~~~~~~~
src/threshold.c:693:12: note: assuming directive output of 5 bytes
            "%s has not been updated for %.3f seconds.", identifier,
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/threshold.c:692:3: note: snprintf output between 39 and 1117 bytes into a destination of size 256
   snprintf(n.message, sizeof(n.message),
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            "%s has not been updated for %.3f seconds.", identifier,
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            CDTIME_T_TO_DOUBLE(missing_time));
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:6455: src/threshold.lo] Error 1
cd buildperl && make
make[2]: Entering directory '/usr/local/src/collectd/buildperl'
Manifying 1 pod document
make[2]: Leaving directory '/usr/local/src/collectd/buildperl'
make[1]: Target 'all-am' not remade because of errors.
make[1]: Leaving directory '/usr/local/src/collectd'
make: *** [Makefile:4749: all] Error 2

**Comment by srivasta** [comment]
Here is the failure with gcc-7:

src/ovs_stats.c: In function ovs_stats_submit_interfaces:
src/ovs_stats.c:283:49: error: snprintf output may be truncated before the last format character [-Werror=format-truncation=]
     snprintf(devname, sizeof(devname), "%s.%s.%s", bridge->name, port->name,
                                                 ^
src/ovs_stats.c:283:5: note: snprintf output 3 or more bytes (assuming 511) into a destination of size 510
     snprintf(devname, sizeof(devname), "%s.%s.%s", bridge->name, port->name,
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
              iface->name);
              ~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:7009: src/ovs_stats_la-ovs_stats.lo] Error 1

**Comment by srivasta** [comment]
Hi,

   No luck with gcc-6 either.

======================================================================
src/python.c: In function ‘cpy_interactive’:
src/python.c:1136:3: error: ‘PyOS_AfterFork’ is deprecated [-Werror=deprecated-declarations]
   PyOS_AfterFork();
   ^~~~~~~~~~~~~~
In file included from /usr/include/python3.7m/Python.h:134:0,
                 from src/python.c:27:
/usr/include/python3.7m/intrcheck.h:18:18: note: declared here
 PyAPI_FUNC(void) PyOS_AfterFork(void) Py_DEPRECATED(3.7);
                  ^~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:7103: src/python_la-python.lo] Error 1
make[1]: Leaving directory '/usr/local/src/collectd'
make: *** [Makefile:4767: all] Error 2
=========================================================================

  Manoj

**Comment by mrunge** [comment]
Thank you for your report and proposed fixes. This here might help as well
https://github.com/collectd/collectd/pull/2895

**Comment by JAORMX** [comment]
@mrunge #3021 addresses this specific warning, and yeah, it seems #2895 goes forward to fix other warnings as well. Seems both are needed.

**Comment by kwiatrox** [comment]
It also fails to compile on RHEL 8.
The errors and reason are the same.

- gcc --version
gcc (GCC) 8.2.1 20180905 (Red Hat 8.2.1-3)

```
src/collectdctl.c: In function ‘parse_identifier’:
src/collectdctl.c:169:50: error: ‘snprintf’ output may be truncated before the last format character [-Werror=format-truncation=]
     snprintf(ident_str, sizeof(ident_str), "%s/%s", hostname, value);
                                                  ^
src/collectdctl.c:169:5: note: ‘snprintf’ output 2 or more bytes (assuming 1025) into a destination of size 1024
     snprintf(ident_str, sizeof(ident_str), "%s/%s", hostname, value);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:7927: src/collectdctl-collectdctl.o] Error 1
make[1]: Leaving directory '/opt/APP/utility/collectd-master'
make: *** [Makefile:4830: all] Error 2
```

**Comment by mrunge** [comment]
This has been fixed with https://github.com/collectd/collectd/pull/3153
