### ISSUE TITLE
Bug in Exec: missing environment variables in many of children processes

### ISSUE THREAD

**Issue by giner** [collectd/collectd#3041]
*   Version of collectd: 5.8.1
*   Operating system / distribution: built from source
*   Kernel version (if applicable): not applicable

## Expected behavior

All children processes should have environment variables COLLECTD_INTERVAL and COLLECTD_HOSTNAME accessible

## Actual behavior

Some of children processes are missing COLLECTD_INTERVAL and COLLECTD_HOSTNAME. Which processes are missing variables is always different.

## Steps to reproduce

Configure a number of external programs running with Exec plugin (let it be just a simple shell script echo-ing environment variables to a file) and start collectd.

## Notes
If my reading of the code is correct there is a possibility of race in [fork_child](https://github.com/collectd/collectd/blob/collectd-5.8.1/src/exec.c#L441) when setting ([1](https://github.com/collectd/collectd/blob/collectd-5.8.1/src/exec.c#L497)) and unsetting ([2](https://github.com/collectd/collectd/blob/collectd-5.8.1/src/exec.c#L541), [3](https://github.com/collectd/collectd/blob/collectd-5.8.1/src/exec.c#L565)) environment variables which is likely to be the cause.

**Comment by mkauf** [comment]
This is a regression in collectd 5.8.1, probably caused by this commit: https://github.com/collectd/collectd/commit/0684aea7453186e6f90ce4b6b8c5bcca68f0d1b9#diff-9cbc5881ff6aaa430665290db00a8ea3

**Comment by PhilippWendler** [comment]
I also experience this bug with 5.8.0.145.gca1cb27, which unfortunately is the latest version available from https://pkg.ci.collectd.org/deb/dists/xenial/collectd-5.8/binary-amd64/

**Comment by iain-buclaw-sociomantic** [comment]
This is not fixed in 5.10

**Comment by jasoncodes** [comment]
Ran into this issue with collectd 5.8.1-1.3 in Debian Buster. Upgraded to the backport of 5.9.2.g-1~bpo10+1 and all is good again.

**Comment by iain-buclaw-sociomantic** [comment]
Fix is in 5.11.  What took you so long?

**Comment by iain-buclaw-sociomantic** [comment]
There's not even a mention in the release notes.

**Comment by rpv-tomsk** [comment]
Even new plugins may not be noted in release notes,  not only "small fixes".
New maintainers is coming.

**Comment by kkepka** [comment]
My apologies, it is missing in release notes due to query that was used to build changelog (all merged PR's since previous release date), and it has been merged into master before that time, but after split rc branch.
Will review git tree to check if there is anything more missing and get it fixed soon.
Again sorry about that, it was not intended to skip any contributions. Will improve that path in future releases.
