### ISSUE TITLE
How to enable internal stats

### ISSUE THREAD

**Issue by redlad** [collectd/collectd#3046]
*   Version of collectd: 5.8
*   Operating system / distribution: Red Hat 7.5
*   Kernel version (if applicable):

## Expected behavior
I want to get internal stats from collectd I have set  CollectdInternalStats to true
## Actual behavior
I am not getting any metrics on collectd  

## Steps to reproduce
Run collectd

Regards
Kevin

**Comment by redlad** [comment]
The instructions on how to set up collectd to get internal stats is not clear to me.
I was wondering if someone could provide a sample collectd config file  with internal stats enabled and plugin set up

**Comment by octo** [comment]
I think you mis-typed the config option: it is called `CollectInternalStats`, note the missing "d".

HTH,
—octo
