### ISSUE TITLE
collectd leaking ram, valgrind report included

### ISSUE THREAD

**Issue by dch** [collectd/collectd#307]
After a few days of running collectd SHA: 24f69e4  (origin/collectd-5.3) the agent seems to be leaking a lot of memory. It's launched via upstart, under a non-root user.

e.g. collectd agent on startup consumes:

VIRT 868M, RES 5512B

after several days we hit:

VIRT 2788M, RES 2143M

This is on ubuntu 12.04 x64 in a rackspace vm.

I ran valgrind for a wee while and got this, the full report will be in separate comment.

```
==25015== LEAK SUMMARY:
==25015==    definitely lost: 1,370,893 bytes in 27,180 blocks
==25015==    indirectly lost: 9,537,081 bytes in 513,291 blocks
==25015==      possibly lost: 2,757 bytes in 139 blocks
==25015==    still reachable: 333,756 bytes in 2,412 blocks
==25015==         suppressed: 0 bytes in 0 blocks
==25015== Reachable blocks (those to which a pointer was found) are not shown.
==25015== To see them, rerun with: --leak-check=full --show-reachable=yes
==25015== 
==25015== For counts of detected and suppressed errors, rerun with: -v
==25015== ERROR SUMMARY: 30 errors from 30 contexts (suppressed: 2 from 2)
```

I'll re-test with my previous config and report back if that shows different behaviour.

**Comment by dllhlx** [comment]
@octo @manuelluis  the leak warning 
" ==2481== 1,920 bytes in 1 blocks are definitely lost in loss record 250 of 269
==2481==    at 0x4C2B6CD: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2481==    by 0x4C2B857: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2481==    by 0x408B53: cf_ci_append_children.isra.2 (configfile.c:527)
==2481==    by 0x4093CF: cf_read_generic (configfile.c:826)
==2481==    by 0x409551: cf_read_generic (configfile.c:586)
==2481==    by 0x409E0F: cf_read (configfile.c:1044)
==2481==    by 0x405CDB: main (collectd.c:466)  "
exists in collectd-5.4 when use command " valgrind -v --leak-check=full --show-reachable=yes /home/collectd/sbin/collectd -C /home/collectd/etc/collectd.conf -P /var/run/q-collectd.pid ", is this warning really a leak?
