### ISSUE TITLE
configuration parsing: errors in plugin section not terminating collectd

### ISSUE THREAD

**Issue by rjablonx** [collectd/collectd#3076]
*   Version of collectd: master, also probably on 5.8
*   Operating system / distribution: Linux/ubuntu, CentOS

Today I've discovered that return values of plugin callbacks used for parsing per-plugin configuration options are not propagated at some level (return value of per-plugin file-configuration callbacks is not checked). It is a bit inconsistent now because some errors in main structure of collectd.conf are causing collectd termination and most of the errors in per-plugin sections are only reported in collectd.log and collectd runs happily like nothing happened.
i.e when using following configuration of virt plugin with invalid value for **BlockDeviceFormat** option:

```
<Plugin virt>
       Connection "qemu:///system"
       RefreshInterval 60
       ReportBlockDevices true
       ReportNetworkInterfaces true
       BlockDeviceFormat wrong_target
       ExtraStats "cpu_util disk disk_err domain_state fs_info job_stats_background pcpu perf vcpupin"

       PersistentNotification false
</Plugin>
```

During startup of collectd I can see error message in logfile as expected (and lv_config callback ends with -1):
`[2019-02-15 09:15:58] [error] virt plugin: unknown BlockDeviceFormat: wrong_target `
... but collectd runs normally with this error

## Expected behavior
Collectd should exit with error message like it happens for scenarios when e.g. non-exsiting plugin was declared as plugin to load/parsing error in main collectd.conf structure

## Actual behavior

Error messages can be seen only in logs but collectd runs normally
I am not sure if it should work like this by design but I think that is a bit risky and confusing when plugin runs with invalid configuration.

**Comment by rpv-tomsk** [comment]
>I am not sure if it should work like this by design but I think that is a bit risky and confusing when plugin runs with invalid configuration.

There are many other places like this, when plugin implementation "ignores" invalid configuration.
That makes `-t/-T` options broken, and I think we need to make rules strong and review/fix implementation for all plugins.

**Comment by rubenk** [comment]
We do return the correct error for complex configs, just not for simple ones: https://github.com/collectd/collectd/blob/master/src/daemon/configfile.c#L416

We should just handle the return value of dispatch_value_plugin() there.

**Comment by rpv-tomsk** [comment]
>We do return the correct error for complex configs

IIRC, there are plugins which continue to run while configuration is broken and `ERROR` message was logged by these plugins. So, we need to re-check plugins and fix them to one common behaviour.
When I found a such, I will refer this issue, OK ?
