### ISSUE TITLE
 [error] plugin_load: Could not find plugin "write_prometheus" in /opt/ibm/monitoring/collectd/lib/collectd

### ISSUE THREAD

**Issue by Vincent-Le** [collectd/collectd#3089]
*   Version of collectd: 5.8
*   Operating system / distribution: VERSION="16.04.5 LTS (Xenial Xerus)"
*   Kernel version (if applicable): N/A

## Expected behavior
The plugin should be loaded, however, I checked where collectd is installed and I don't see "write_prometheus.*". For example:

$ find . -name write*
./lib/collectd/write_graphite.a
./lib/collectd/write_graphite.la
./lib/collectd/write_graphite.so
./lib/collectd/write_log.a
./lib/collectd/write_log.la
./lib/collectd/write_log.so
./lib/collectd/write_metric_mtlumberjack.so
./lib/collectd/write_sensu.a
./lib/collectd/write_sensu.la
./lib/collectd/write_sensu.so
./lib/collectd/write_tsdb.a
./lib/collectd/write_tsdb.la
./lib/collectd/write_tsdb.so
./lib/collectd/write_http.so

(Description of the behavior / output that you expected)

## Actual behavior

(Description of the behavior / output that you observed)

## Steps to reproduce

*   step 1
In collectd.conf, define the following:
LoadPlugin write_prometheus
<Plugin "write_prometheus">
  Port "9103"
</Plugin>

*   step 2
Start collectd

*   step 3
Observe the error in collectd.log:
[2019-02-19 01:20:20] [error] plugin_load: Could not find plugin "write_prometheus" in /opt/ibm/monitoring/collectd/lib/collectd
[2019-02-19 01:20:20] [warning] Found a configuration for the `write_prometheus' plugin, but the plugin isn't loaded or didn't register a configuration callback.

It seems like "write_prometheus" plugin is not installed.  Where can I get it to install?  Thank you in advance for your help.

**Comment by rubenk** [comment]
Where did you get the collectd package from?

**Comment by Vincent-Le** [comment]
@rubenk - Thanks for your response.  I've tried:

1)  apt-get update
     apt-get install collectd collectd-utils

2)  cd /tmp
     wget https://collectd.org/files/collectd-5.7.2.tar.bz2 -O collectd-5.7.2.tar.bz2 && tar -jxf collectd-5.7.2.tar.bz2
     ./configure --with-java=/usr/lib/jvm/java-8-openjdk-amd64 && make all install

Looking at ./configure, it looks like there is an opton "--enable-write_prometheus" so let me try that and see.

**Comment by rubenk** [comment]
You said that you were running 5.8 but you downloaded 5.7? Please use the latest version.

* /opt/ibm/monitoring/collectd/lib/collectd does imply that it is not a standard package, did you download something from IBM?

**Comment by Vincent-Le** [comment]
I was just trying both 5.7.2 and 5.8.  The example that I provided as just happen to be trying with 5.7.2. 
 As for `/opt/ibm/monitoring/collectd/lib/collectd`, that's just where collectd was installed (i.e., ./configure --prefix="/opt/ibm/monitoring/collectd" xxxx xxxx xxxx)

BTW, I am seeing dependency errors when I tried `--enable-write_prometheus`, do you know what the dependencies are?  If not, I'll investigate:

   vserver . . . . . . . yes
    wireless  . . . . . . yes
    write_graphite  . . . yes
    write_http  . . . . . no (curl-config failed)
    write_kafka . . . . . no (librdkafka/rdkafka.h not found)
    write_log . . . . . . yes
    write_mongodb . . . . no ('mongo.h' not found)
    **write_prometheus. . . no (dependency error)**
    write_redis . . . . . no (hiredis.h not found)
    write_riemann . . . . no (pkg-config doesn't know libriemann-client)
    write_sensu . . . . . yes
    write_tsdb  . . . . . yes
    xencpu  . . . . . . . no
    xmms  . . . . . . . . no
    zfs_arc . . . . . . . yes
    zone  . . . . . . . . no
    zookeeper . . . . . . yes

configure: error: "Some plugins are missing dependencies - see the summary above for details"

**Comment by rubenk** [comment]
All dependencies are listen in the README, but for write_prometheus it's libmicrohttpd.

**Comment by Vincent-Le** [comment]
@rubenk, thanks.  Yes, I saw  the required "libmicrohttpd", but still seeing issues.  

    write_graphite  . . . yes
    write_http  . . . . . no (curl-config failed)
    write_kafka . . . . . no (librdkafka/rdkafka.h not found)
    write_log . . . . . . yes
    write_mongodb . . . . no ('mongo.h' not found)
    write_prometheus. . . no (dependency error)
    write_redis . . . . . no (hiredis.h not found)
    write_riemann . . . . no (pkg-config doesn't know libriemann-client)
    write_sensu . . . . . yes
    write_tsdb  . . . . . yes
    xencpu  . . . . . . . no
    xmms  . . . . . . . . no
    zfs_arc . . . . . . . yes
    zone  . . . . . . . . no
    zookeeper . . . . . . yes

configure: error: "Some plugins are missing dependencies - see the summary above for details"
root@ubuntu-vl511:~/collectd-5.7.2# apt-get install libmicrohttpd-dev libgcrypt-dev libgnutls28-dev libmicrohttpd10
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'libgcrypt20-dev' instead of 'libgcrypt-dev'
libmicrohttpd-dev is already the newest version (0.9.44+dfsg-1ubuntu2).
libmicrohttpd10 is already the newest version (0.9.44+dfsg-1ubuntu2).
libmicrohttpd10 set to manually installed.
libgcrypt20-dev is already the newest version (1.6.5-2ubuntu0.5).
libgnutls28-dev is already the newest version (3.4.10-4ubuntu1.4).
libgnutls28-dev set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 51 not upgraded.

Let me double check and make sure all the dependencies are installed and try again.

**Comment by rubenk** [comment]
Can you share the complete output of configure? Also please just use 5.8, 5.7 is pretty old now.

**Comment by Vincent-Le** [comment]
@rubenk - Thanks again.  Here is the commands and the ouput (I am now using collectd 5.8.1 - same results):

1) wget https://storage.googleapis.com/collectd-tarballs/collectd-5.8.1.tar.bz2
2) tar xf collectd-5.8.1.tar.bz2
3) cd collectd-5.8.1/
3) ./configure --with-java=/usr/lib/jvm/java-8-openjdk-amd64 --enable-write_graphite --enable-write_prometheus

[output.txt](https://github.com/collectd/collectd/files/2881287/output.txt)

**Comment by rubenk** [comment]
Thanks. I see now that you can't actually tell from the configure output which dependencies write_prometheus needs. We should fix that.

Anyway, from configure.ac:
```
if test "x$have_protoc_c" = "xyes" && test "x$with_libprotobuf_c" = "xyes"; then
  plugin_pinba="yes"
  if test "x$with_libmicrohttpd" = "xyes"; then
    plugin_write_prometheus="yes"
  fi
fi
```

So you'll need some protobuf stuff.

**Comment by octo** [comment]
On Debian/Ubuntu, `protoc-c` is provided by the `protobuf-c-compiler` package.

**Comment by Vincent-Le** [comment]
Thanks @octo.  Yes, I figured that out yesterday and was able to successfully build **write_prometheus**.  Thanks @rubenk for your help.

**Comment by Vincent-Le** [comment]
Hi @rubenk @octo 

I am now seeing the problem with RedHat trying to build collectd-5.8.1 with "--enable-write_prometheus".  Here is the snippet of the output at the end of the "/.configure" command:

    write_graphite  . . . yes
    write_http  . . . . . no (curl-config failed)
    write_kafka . . . . . no (librdkafka/rdkafka.h not found)
    write_log . . . . . . yes
    write_mongodb . . . . no (pkg-config could not find libmongoc)
    *write_prometheus. . . no (dependency error)*
    write_redis . . . . . no (hiredis.h not found)
    write_riemann . . . . no (pkg-config doesn't know libriemann-client)
    write_sensu . . . . . yes
    write_tsdb  . . . . . yes

I've installed *libmicrohttpd* and *protobuf-c*, and *protobuf-c-compiler*, but still seeing a problem.  Please see attached `config.log` output. 

Package libmicrohttpd-0.9.33-2.el7.x86_64 already installed and latest version
Nothing to do

Package protobuf-2.5.0-8.el7.x86_64 already installed and latest version
Nothing to do

Package protobuf-c-1.0.2-3.el7.x86_64 already installed and latest version
Nothing to do

From the output, it appears that it is looking for "libprotobuf-c" package?  I am unable to locate that package if that's needed (appreciate if you can point me to the right direction).

[config.log](https://github.com/collectd/collectd/files/3016255/config.log)

**Comment by rpv-tomsk** [comment]
Hi,

You have to install appropriate '-devel-' packages.

**Comment by Vincent-Le** [comment]
Thanks @rpv-tomsk.

**Comment by sunkuranganath** [comment]
@Vincent-Le could you please update your experience in wiki/documentation so it will make it easy to others? https://collectd.org/wiki/index.php/Plugin:Write_Prometheus 
Appreciate your help.

**Comment by mrunge** [comment]
for reference, and for Red Hat based environments, there is a spec file to build collectd inside the git tree, and the requirement to libmicrohttpd is here: https://github.com/collectd/collectd/blob/master/contrib/redhat/collectd.spec#L921

**Comment by padraigconnolly** [comment]
Installing `libprotobuf-c-dev` and `libprotobuf-dev` solved the issue for me on Ubuntu 18.04 ( `apt install libprotobuf-c-dev libprotobuf-dev` )

**Comment by JoshHilliker** [comment]
I'm using centos 7 latest collectd repo - both protobuf-c & libmicrohttp are showing as YES in the libraries, however write_prometheus. . . no (dependency error) still shows a dependency error.   

I've installed libmicrohttpd-devel protobuf-c-compiler-devel protobuf-c-compiler protobuf-devel

I see above that protoc-c is part of protobuf.   I looked at the configure dependencies above and I believe this meets all 3 dependencies.. what else am I missing?

**Comment by mrunge** [comment]
@JoshHilliker first of all, please open a new issue for a new issue.

From looking at the spec file, write_prometheus only requires libmicrohttpd-devel. If you want to recompile collectd on your own, please add a more detailed configure log.

**Comment by JoshHilliker** [comment]
> @JoshHilliker first of all, please open a new issue for a new issue.
> 
> From looking at the spec file, write_prometheus only requires libmicrohttpd-devel. If you want to recompile collectd on your own, please add a more detailed configure log.

will do..  I'll open a new issue, post out our build info & put in the output  of libraries & plugin status w/ the compile step.     Thank You..
