### ISSUE TITLE
[Feature Request/Version 6.0]: Adding Labels to Collectd Metrics

### ISSUE THREAD

**Issue by srivasta** [collectd/collectd#3094]
*   Version of collectd: Targeted for 6.0
*   Operating system / distribution: Any/All
*   Kernel version (if applicable):

## Expected behavior

The data collected by collectd is essentially a time series (also known as a metric). Metrics have names that identify the time series (usually based on some combination of where they are being 2 we as, like hostname, or what the time series represents, like load average or memory usage). Currently, collectd uses a  fixed 3-5 tuples (three of them are fixed and mandatory, and only two fields are flexible and up to the plugin author) are too inflexible (a service might be better served by sharding metrics by component, or region, or other notional dimensions than the hard coded set in collectd). Using more descriptive, and user defined, set of labels  to create the identity of the metric might be more natural for users.  Labels make selecting, filtering and grouping much easier. Most modern monitoring systems have mechanisms to query for metrics based on arbitrary labels as long as the metrics carry the labels with them. This functionality is currently missing from the collectd data model, and this proposal is aimed at adding that. Examples are detailed in the background section

The proposed change is in a design document at https://docs.google.com/document/d/173gGP3tUD3yfN2NNHxCv0BsKsacfDlSyoaQIn7MqLtQ/edit?usp=sharing

The document is still a work in progress; I am modifying the wire protocol section to be in line with the https://openmetrics.io/ recommendations.

**Comment by srivasta** [comment]
I have updated the design document with a new binary format section using the openmetrics suggested formats, and moved the previous binary protocl segment into the alternative considered section. the openmetrics standard is very much a work in progress, I have considered just the public facing information in this draft.

**Comment by sunkuranganath** [comment]
Thanks Manoj for creating this.

**Comment by srivasta** [comment]
https://docs.google.com/document/d/1RZ7YAO6lWcDDvevzxFGVDgv4UQpdgWoT7OCP9Vpb2CU/edit?usp=sharing

**Comment by srivasta** [comment]
I have an initial stalking horse commit that implements the data structures in the design docs, and has unit tests to the avl tree used in the structures. I think we need some discussion on how to convert the current value_list_t 5-tupples --> name + labels structure in the new format. Also, how should we deal with metadata lists in the new format?

https://github.com/srivasta/collectd/tree/metric-label-support

**Comment by srivasta** [comment]
I have an initial proposal for how to convert from the current value_list_t data structure to the proposed new single data source metrics_t format 

https://docs.google.com/document/d/1B4drbdkPoXvMFrBx57cnKtDgeehQ1zkptq9Ozx7MnG8/edit?usp=sharing

**Comment by srivasta** [comment]
I have added a commit to my metric label support branch that adds conversion from the old value_list_t --> metric_list_t format, This it one milestone along the way to full support, and will be used to convert metrics from unmigrated read plugins.

https://github.com/srivasta/collectd/tree/metric-label-support

**Comment by srivasta** [comment]
Added a commit with utility functions for cloning and freeing the new metric, identity and metadata list head data structures that will be used by the helper functions that enqueue and dequeue from the the future new write queue

**Comment by srivasta** [comment]
Added another commit along the way:

[metric-label-support]: Modify write queue to use metric_t

This commit adds an updated write queue data structure, and updates
the enqueue and dequeue calling paths. Note that while this compiles
and the tests pass, thisis not a functioning collectd by itself, the
caching and networking code is a work in progress.

**Comment by amber-zhang** [comment]
@sunkuranganath @srivasta Adding more labels is what we want now. What's the release plan of this  feature?

**Comment by eero-t** [comment]
Metric label support was merged 1.5 years ago to v6 branch.  I guess this can be closed?
