### ISSUE TITLE
collectd unable to locate libperl (5.14)

### ISSUE THREAD

**Issue by vijaySamanuri** [collectd/collectd#310]
I am  using ubuntu 12.4 . perl version 5.14 .
I wanted to install collectd 5.3.0 from source and use perl plugin to store metrics into remote database.
but when i type ./configure 
.
.
.
checking for perl... yes (/usr/bin/perl)
checking for libperl... no
.
.
libperl   no 
.
.
.
perl   no(needs libperl)

Collectd is unable to locate my libperl even though it is available
$locate libperl

/usr/lib/libperl.a
/usr/lib/libperl.so
/usr/lib/libperl.so.5.14
/usr/lib/libperl.so.5.14.2
/usr/share/doc/libperl-dev
/usr/share/doc/libperl5.14
/usr/share/lintian/overrides/libperl5.14
/var/cache/apt/archives/libperl-dev_5.14.2-6ubuntu2.3_amd64.deb
/var/lib/dpkg/info/libperl-dev.list
/var/lib/dpkg/info/libperl-dev.md5sums
/var/lib/dpkg/info/libperl5.14.list
/var/lib/dpkg/info/libperl5.14.md5sums
/var/lib/dpkg/info/libperl5.14.postinst

i even tried installing lower versions of perl (5.10) using perlbrew but the problem remains.
Any help would be appreciated :)

**Comment by mfournier** [comment]
Merging #390 fixed this problem. collectd 5.5.x, 5.4.2 and 5.3.2 should correctly detect libperl and build the plugin on ubuntu.

**Comment by obfuscurity** [comment]
FWIW, encountered the same problem with CentOS 7. Installing the `perl-ExtUtils-Embed` and `perl-ExtUtils-MakeMaker packages` as mentioned in https://github.com/collectd/collectd/issues/310#issuecomment-20923404 fixed it for me.

**Comment by obfuscurity** [comment]
To clarify, that last comment was regarding collectd 5.5.0.
