### ISSUE TITLE
Chatty messages (write_http)

### ISSUE THREAD

**Issue by jamessevener** [collectd/collectd#3105]
*   Version of collectd: 5.8.1
*   Operating system / distribution: RHEL 6.7

## Expected behavior

collectd (write_http) should only log errors to stderr (or whatever logging plugin you are using) if the loglevel is set to err

## Actual behavior

With the syslog plugin configured to LogLevel err, I see hundreds of these messages in /var/log/messages

{"text":"Success","code":0}

## Steps to reproduce
1. Install collectd
2. configure write_http (in this case sending data to Splunk)
3. restart collectd, since write_http only seems to log these messages when you restart the service

**Comment by jamessevener** [comment]
Trying to come up with a work around for this (we use collectd and the write_http plugin on a 100+ systems), tried to configure filtering with no success. Then tried disabling the syslog plugin altogether, and write_http still spams var/log/messages.

And because I didn't tie this to the previous conversation...

> I think you're problem is separate. Looks like _libcurl_ defaults to writing the response to `STDOUT`. Setting the `CURLOPT_WRITEFUNCTION` option should fix that. Could you open a separate issue for that please?
> 
> Thanks and best regards,
> —octo

**Comment by tscheuren** [comment]
I can confirm hundreds of {"text":"Success","code":0} in /var/log/syslog
on Debian buster (4.19.0-5-amd64), with collectd 5.8.1-1.3

**Comment by duckfez** [comment]
I am starting on a PR for this.  One question I have is what should be done with the responses?  I'm thinking something like:

- Always log whole response at DEBUG log level
- Log non-200 responses at ERROR log level

This will solve the Splunk use case (which is what @jamessevener and @tscheuren are both seeing, as am I) but does it cause any breakage for others?
