### ISSUE TITLE
PowerDNS plugin Bug : unreachables

### ISSUE THREAD

**Issue by apandiyan** [collectd/collectd#3112]
*   Version of collectd: collectd-5.8.1-1.el7.x86_64 (Epel)
*   Operating system / distribution: CentOS 7.6.1810
*   Kernel version (if applicable): 3.10.0-957

## Expected behavior

PowerDNS plugin should send statistics to InfluxDB

## Actual behavior

PowerDNS plugin doesn't send statistics to InfluxDB and it provides info in the log that

Feb 22 18:39:50 ns1 collectd[18738]: powerdns plugin: submit: Not found in lookup table: unreachables = 34677;

## Steps to reproduce

*   Install PDNS (pdns-4.1.6-1pdns.el7.x86_64) from Epel
*   Install collectd (collectd-5.8.1-1.el7.x86_64) from Epel
*   Configure powerdns plugin as mentioned in wiki document (https://collectd.org/wiki/index.php/Plugin:PowerDNS)

**Comment by rubenk** [comment]
Please share your configuration here

**Comment by apandiyan** [comment]
Hi,

This is my configuration.

--xx--

Hostname    "localhost"
BaseDir     "/var/lib/collectd"
PIDFile     "/var/run/collectd.pid"
PluginDir   "/usr/lib64/collectd"
TypesDB     "/usr/share/collectd/types.db"
LoadPlugin syslog
LoadPlugin cpu
LoadPlugin cpufreq
LoadPlugin cpusleep
LoadPlugin df
LoadPlugin disk
LoadPlugin ethstat
LoadPlugin interface
LoadPlugin load
LoadPlugin memory
LoadPlugin network
LoadPlugin powerdns
LoadPlugin processes
LoadPlugin protocols
LoadPlugin swap
LoadPlugin uptime
LoadPlugin users
<Plugin network>
        Server "INFLUXDB_SERVER" "PORT"
</Plugin>
<Plugin "powerdns">
  <Server "auth_dns">
    Collect "latency"
    Collect "udp-answers" "udp-queries"
    Collect "recursing-answers" "recursing-questions"
    Collect "packetcache-hit" "packetcache-miss"
    Collect "query-cache-hit" "query-cache-miss"
    Collect "packetcache-size" "qsize-q"
    Collect "corrupt-packets" "servfail-packets"
    Collect "tcp-answers" "tcp-queries"
    Collect "udp4-answers" "udp4-queries"
    Collect "udp6-answers" "udp6-queries"
    Collect "deferred-cache-inserts" "deferred-cache-lookup"
    Socket "/var/run/pdns.controlsocket"
  </Server>
</Plugin>
Include "/etc/collectd.d"

--xx--

**Comment by apandiyan** [comment]
Attached configuration file and thanks in advance.
[collectd.conf.txt](https://github.com/collectd/collectd/files/2898987/collectd.conf.txt)

**Comment by rpv-tomsk** [comment]
>PowerDNS plugin doesn't send statistics to InfluxDB and it provides info in the log that

PowerDNS does not send anything into InfluxDB. That does another 'write_xxx' plugin.
'Not found in lookup table' message does not prohibits sending other metrics. Your problem caused by misconfiguration, not by plugin bug/imperfection.

However, plugin will be updated to support 'unreachables' reporting.
