### ISSUE TITLE
Collectd 5.9 release preparation

### ISSUE THREAD

**Issue by sunkuranganath** [collectd/collectd#3115]
Hi Maintainers @octo @mrunge @rpv-tomsk @rubenk @mfournier 

In relation to impending Collectd 5.9 release coming up for mid-March 2019, we would like to do relevant preparation and check to see how we can help in the release process.

What are you expecting from individual contributors who have done bug fixes, new features and/or documentation updates?

I presume creating a change log is a long and tedious process. What would help simplify the process for you?

Thanks,
Sunku

**Comment by kkepka** [comment]
Initiated [Changelog gathering for 5.9](https://www.collectd.org/wiki/index.php/Version_5.9). Please add info about your contributions, will be much appreciated.

**Comment by kkepka** [comment]
Kudos to @anaudx & @rjablonx for filling [changelog on wiki](https://www.collectd.org/wiki/index.php/Version_5.9) with content.

**Comment by sunkuranganath** [comment]
Thanks @anaudx and @rjablonx for carefully adding the details in 3 categories - new features, bugsfixes/cleanups/refactoring & documentation. Appreciate your help.

**Comment by sandrobonazzola** [comment]
anything else needed? @sradco can you please review?

**Comment by pllopis** [comment]
Would #3037 be included for the 5.9 release? I recently saw the 5.9 tag being added to that issue. Please let me know if there's anything you need for that to happen, e.g. adding it to the changelog wiki

**Comment by mrunge** [comment]
@pllopis I don't see #3037 merged.
