### ISSUE TITLE
Collectd crashes with coredump once vm is powered off

### ISSUE THREAD

**Issue by rom-stratoscale** [collectd/collectd#3119]
It cased by a crash in the libvirt plugin I guess:

gdb /usr/sbin/collectd -c /var/log/cores/core.reader#0.42204.stratonode2.node.strato.1551691078

Missing separate debuginfos, use: debuginfo-install collectd-5.8.0.74.g0c85475-8.el7.centos.x86_64

Program terminated with signal 11, Segmentation fault.#0 0x00007fc62dd19815 in virObjectIsClass (anyobj=anyobj@entry=0x1ffffffff, klass=0x55ee2643bef0) at util/virobject.c:544544 if (VIR_OBJECT_NOTVALID(obj))Missing separate debuginfos, use: debuginfo-install collectd-5.8.0.74.g0c85475-8.el7.centos.x86_64(gdb) bt#0 0x00007fc62dd19815 in virObjectIsClass (anyobj=anyobj@entry=0x1ffffffff, klass=0x55ee2643bef0) at util/virobject.c:544#1 0x00007fc62dec2758 in virDomainGetName (domain=0x1ffffffff) at libvirt-domain.c:1652#2 0x00007fc62e213861 in lv_read () from /usr/lib64/collectd/virt.so#3 0x000055ee230a9f43 in plugin_read_thread ()#4 0x00007fc63e04cdd5 in start_thread () from /lib64/libpthread.so.0#5 0x00007fc63d96cead in clone () from /lib64/libc.so.6

To reproduce: Stop / start vms using libvirt while virtplugin is enabled

**Comment by mrunge** [comment]
iirc, this is fixed in 5.8.1, could you please give that a try?

**Comment by rom-stratoscale** [comment]
Thank @mrunge .
I will update

**Comment by rom-stratoscale** [comment]
Ignore. I missed that we override the types.db file. Recheking.

**Comment by rom-stratoscale** [comment]
@mrunge works great! Thanks.
Although this installation brings some extra default plugins enabled.
Any ETA to be merged to the centos official collectd?

**Comment by rubenk** [comment]
There's no CentOS official collectd package, but if you mean EPEL, the EPEL packages have been on 5.8.1 for a while.
