### ISSUE TITLE
Collectd/curl plugin doesn't understand exponential format numbers

### ISSUE THREAD

**Issue by james-masson** [collectd/collectd#3122]
*   Version of collectd: collectd 5.8.1
*   Operating system / distribution: debian:buster-slim
*   Kernel version (if applicable):

## Expected behavior

Using Curl plugin to scrape a http page

```
        <Match>
            Regex "^aeron_driver_file_size (.*)$"
            DSType "CounterSet"
            Type "counter"
            Instance "aeron_driver_file_size"
        </Match>
```

where the HTTP looks like

```
# HELP aeron_driver_file_size Total file size of the Driver directory
# TYPE aeron_driver_file_size gauge
aeron_driver_file_size 1.12119808E8
```

Collectd/curl plugin should understand the exponential number format

## Actual behavior

Collectd records the value  as "1"

## Steps to reproduce

*   Have a HTTP endpoint serving an exponential-format number
*   Scrape it with the curl plugin
*   Notice the number recorded is not what it should be.

**Comment by rpv-tomsk** [comment]
Counter is integer type, and exponential form is double precision form. 
So, in Collectd all works as designed, and that design decision looks good.

I think, exponential form is not good choose for file/directory sizes, so you should fill bugreport at another place.

For gauges, Collectd uses `strtod` which supports exponential form.
https://www.gnu.org/software/libc/manual/html_node/Parsing-of-Floats.html

**Comment by faxm0dem** [comment]
I concur: you shall use Gauge: Counter doesn't make sense for exponential noted values, neither does it make sense for a file size.

**Comment by james-masson** [comment]
Agreed - just a mismatch between what i've asked collectd to scrape.
