### ISSUE TITLE
Collectd Stickers

### ISSUE THREAD

**Issue by sunkuranganath** [collectd/collectd#3124]
All,
This is a bit of unique question to ask here but figured this is a good place to.
I am looking to print bunch of Collectd stickers through my organization's support and looking to distribute them at upcoming conferences.
Could you please provide a feedback on the design so I can order them through: Which of the 2 choices would the community prefer:
Choice 1: 
![image](https://user-images.githubusercontent.com/16784251/54229720-1947f080-44c2-11e9-931b-11bd5837a7bd.png)
Choice 2:
![image](https://user-images.githubusercontent.com/16784251/54229782-4399ae00-44c2-11e9-9a3e-4cfb4fa8abc3.png)

I am looking to have these available at upcoming OpenNetworkingSummit on April 3rd so we could distribute at Linux Foundation demo booth. If no responses, I would go ahead with 'Choice 1'.

**Comment by faxm0dem** [comment]
choice 1!
choice 2 will be preferred in a few years when 10 billion people will know collectd

**Comment by mrunge** [comment]
Thank you for doing this! I'd prefer the option 1, it is more clear.

**Comment by sunkuranganath** [comment]
That's great. Thanks for the responses. Will go ahead with choice 1.

And agree with you @faxm0dem :)

**Comment by sunkuranganath** [comment]
The stickers just arrived! Looking forward to distribute as many as I can!
They are a bit smaller than what I expected, but hey, we have Collectd stickers now!

![CollectdStickerBox](https://user-images.githubusercontent.com/16784251/56166513-aa5f2b00-5f8a-11e9-8365-5e2167b95292.jpg)
![CollectdStickers](https://user-images.githubusercontent.com/16784251/56166520-ae8b4880-5f8a-11e9-9db4-2e8260e5a0a8.jpg)

**Comment by mrunge** [comment]
Congrats! This is great, and thank you for sharing this!
