### ISSUE TITLE
compilation error on ubuntu 18.04

### ISSUE THREAD

**Issue by yogeshVU** [collectd/collectd#3130]
*   Version of collectd: git
*   Operating system / distribution: ubuntu 18.04
*   Kernel version (if applicable): 4.15.0-46-generic

## Expected behavior
```make```
should compile successfully
(Description of the behavior / output that you expected)

## Actual behavior
```  
CC       src/daemon/collectd-utils_complain.o
src/daemon/plugin.c: In function ‘plugin_init_all’:
src/daemon/plugin.c:838:34: error: ‘%llu’ directive output may be truncated writing between 1 and 10 bytes into a region of size 9 [-Werror=format-truncation=]
     snprintf(name, sizeof(name), "writer#%" PRIu64,
                                  ^~~~~~~~~~
src/daemon/plugin.c:838:42: note: format string is defined here
     snprintf(name, sizeof(name), "writer#%" PRIu64,
src/daemon/plugin.c:838:34: note: directive argument in the range [0, 4294967295]
     snprintf(name, sizeof(name), "writer#%" PRIu64,
                                  ^~~~~~~~~~
In file included from /usr/include/stdio.h:862:0,
                 from src/daemon/collectd.h:49,
                 from src/daemon/plugin.c:31:
/usr/include/i386-linux-gnu/bits/stdio2.h:64:10: note: ‘__builtin___snprintf_chk’ output between 9 and 18 bytes into a destination of size 16
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/daemon/plugin.c:649:34: error: ‘%llu’ directive output may be truncated writing between 1 and 10 bytes into a region of size 9 [-Werror=format-truncation=]
     snprintf(name, sizeof(name), "reader#%" PRIu64, (uint64_t)read_threads_num);
                                  ^~~~~~~~~~
src/daemon/plugin.c:649:42: note: format string is defined here
     snprintf(name, sizeof(name), "reader#%" PRIu64, (uint64_t)read_threads_num);
src/daemon/plugin.c:649:34: note: directive argument in the range [0, 4294967295]
     snprintf(name, sizeof(name), "reader#%" PRIu64, (uint64_t)read_threads_num);
                                  ^~~~~~~~~~
In file included from /usr/include/stdio.h:862:0,
                 from src/daemon/collectd.h:49,
                 from src/daemon/plugin.c:31:
/usr/include/i386-linux-gnu/bits/stdio2.h:64:10: note: ‘__builtin___snprintf_chk’ output between 9 and 18 bytes into a destination of size 16
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CC       src/daemon/collectd-utils_llist.o
  CC       src/daemon/collectd-utils_random.o
cc1: all warnings being treated as errors
Makefile:7394: recipe for target 'src/daemon/collectd-plugin.o' failed
make[1]: *** [src/daemon/collectd-plugin.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/ubuntu/collectd'
Makefile:4543: recipe for target 'all' failed
make: *** [all] Error 2


```
(Description of the behavior / output that you observed)

## Steps to reproduce

*   step 1 git clone
*   step 2 sh build.sh 
*   step 3 ./configure 
*   step 4 make

**Comment by rubenk** [comment]
This is https://github.com/collectd/collectd/issues/3038

Either build with --disable-werror or even better, send us some patches :-)

**Comment by Villjoie** [comment]
I have this problem by run make-j  32
someone has a solution please


examples/mnist/convert_mnist_data.cpp: In function ‘void convert_dataset(const char*, const char*, const char*)’:
examples/mnist/convert_mnist_data.cpp:25:6: warning: ‘__builtin___snprintf_chk’ output may be truncated before the last format character [-Wformat-truncation=]
 void convert_dataset(const char* image_filename, const char* label_filename,
      ^~~~~~~~~~~~~~~
In file included from /usr/include/stdio.h:862:0,
                 from /usr/include/c++/7/cstdio:42,
                 from /usr/include/c++/7/ext/string_conversions.h:43,
                 from /usr/include/c++/7/bits/basic_string.h:6361,
                 from /usr/include/c++/7/string:52,
                 from /usr/include/c++/7/stdexcept:39,
                 from /usr/include/c++/7/array:39,
                 from /usr/include/c++/7/tuple:39,
                 from /usr/include/c++/7/bits/stl_map.h:63,
                 from /usr/include/c++/7/map:61,
                 from /usr/include/google/protobuf/text_format.h:41,
                 from examples/mnist/convert_mnist_data.cpp:10:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:65:44: note: ‘__builtin___snprintf_chk’ output between 9 and 11 bytes into a destination of size 10
        __bos (__s), __fmt, __va_arg_pack ());
                                            ^
