### ISSUE TITLE
Question: how to set the sampling interval in milliseconds

### ISSUE THREAD

**Issue by yogeshVU** [collectd/collectd#3132]
What is the resolution on the sampling interval supported by collectd? Can one measure less than 1 second? millisecond? microsecond?
I might have overlooked it, but can anyone point me to the source document where this is mentioned. thanks!

**Comment by rubenk** [comment]
It's in seconds, see man collectd.conf under Interval: https://collectd.org/documentation/manpages/collectd.conf.5.shtml

**Comment by rubenk** [comment]
Actually it's a double internally so you should be able to set 0.1 for instance. I don't think many people do that however, so there might be dragons.

**Comment by yogeshVU** [comment]
I wanted to use it to measure at the level of milliseconds for real time tasks.. so wanted to know if it has been utilized at finer resolutions...

**Comment by rubenk** [comment]
I don't know anyone who does, I personally use 10 seconds. I see no reason why it shouldn't work though.

Perhaps you could ask on the mailing list. We'd like to use this issue tracker strictly for bugs.

**Comment by yogeshVU** [comment]
> 
> 
> Actually it's a double internally so you should be able to set 0.1 for instance. I don't think many people do that however, so there might be dragons.

Where is this in the codebase?

**Comment by rubenk** [comment]
grep for 'interval' and you'll find it

**Comment by mrunge** [comment]
For reference, I've seen the request to  set an interval to below 1s, especially in NFV environments.

**Comment by rubenk** [comment]
@mrunge you've seen the request, or have you seen it work?

**Comment by sunkuranganath** [comment]
Agree with @mrunge. NFV environments do ask for sub second data collection intervals, especially for metrics that affect the latency.
In the process of running few experiments and verify what works.

**Comment by beguy** [comment]
Same question: Are collectd write plugins interval can't be less than 1 second for version 5.7.2?

My try:
I need collect cpu once in 200 Milliseconds. I patch default cpu plugin like this for accepting interval:
```c
 plugin_register_complex_read (
          /* group    = */ "cpu",
          /* name     = */ "cpu",
          /* callback = */ cpu_read,
      // watch https://collectd.org/wiki/index.php/High_resolution_time_format
          /* interval = */ MS_TO_CDTIME_T(interval_ms),
          /* userdata = */ NULL);
 } /* void module_register */
```
 and then patch format_graphite for showing timestamp in milliseconds:
 ```c
 if ((flags & GRAPHITE_TIMESTAMP_IN_MILLIS))
     {
       message_len =
         (size_t)ssnprintf(message, sizeof(message), "%s %s %lu\r\n", key, values,
                           CDTIME_T_TO_MS(vl->time));
     }
     else
     {
       message_len =
         (size_t)ssnprintf(message, sizeof(message), "%s %s %u\r\n", key, values,
                           (unsigned int)CDTIME_T_TO_TIME_T(vl->time));
     }
```
 Then i'll get metrics:
```
kovi.cpu-0.percent-user 5.10204081632653 1576854524969
...48 lines here...
kovi.cpu-5.percent-idle 94 1576854524969
kovi.cpu-0.percent-user 5.10204081632653 1576854525969
...48 lines here...
kovi.cpu-5.percent-interrupt 0 1576854525969
```
where you can see, that time interva between sends `1576854525969-1576854524969 == 1000millis == 1 second`.

**Comment by beguy** [comment]
@sunkuranganath, what're the results of the tests?

**Comment by Grandmother** [comment]
In code some high resolution time type exists and used exactly for the networking sensors as I understood: `TYPE_INTERVAL_HR`. It had been introduced 12 years ago [here](https://github.com/collectd/collectd/commit/2c23a06de59e9cdb91ad9f72dc379733970e7a33#diff-420a69ba47edc53afe487912490483732ca59ff0a3d3979c5151dd0407e1e029R54):
> libcollectdclient: Update to the high-resolution time format.

**Comment by Grandmother** [comment]
Found this feature request: https://github.com/collectd/collectd/issues/3361, no need to beat this dead horse :D

**Comment by eero-t** [comment]
I've been using (one of the new plugins in) `collectd v6.0-rc`, and subsecond intervals work fine for that.

Do you see the same problem when using v6.0-rcX?   Because if you see it, I think it's a bug in specific plugin, not collectd in general...
