### ISSUE TITLE
How to ignore network fileystems in the df plugin?

### ISSUE THREAD

**Issue by saurabhnanda** [collectd/collectd#3133]
*   Version of collectd: 5.7.2.git
*   Operating system / distribution: 
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
```
*   Kernel version (if applicable):  `4.15.0-42-generic`

## Expected behavior

`df` stats for networked filesystems, especially NFS, should be ignored.

## Actual behavior

`df` stats for networked filesystems are still being reported.

## Steps to reproduce

```
<Plugin df>
	IgnoreSelected true

	FSType rootfs
	FSType sysfs
	FSType proc
	FSType devtmpfs
	FSType devpts
	FSType tmpfs
	FSType fusectl
	FSType cgroup
       
       #########
       # Tried the following, but doesn't seem to work...
       #########
	FSType nfs
	FSType nfsv4

	ValuesAbsolute false
	ValuesPercentage true
	Interval 300
</Plugin>
```

**Comment by rpv-tomsk** [comment]
Hi,

What `cat /proc/mounts` shows?

**Comment by saurabhnanda** [comment]
@rpv-tomsk relevant section from `cat /proc/mounts`:

```
[IPv4-REDACTED]:/zfs/logs /nfs/logs nfs4 rw,noatime,nodiratime,vers=4.2,rsize=1048576,wsize=1048576,namlen=255,soft,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=[IPv4-REDACTED],local_lock=none,addr=[IPv4-redacted] 0 0
```

Should I be used `nfs4` instead of `nfsv4` in the collectd config?

**Comment by rpv-tomsk** [comment]
I think yes.

**Comment by saurabhnanda** [comment]
@rpv-tomsk tried `nfs4`  -- doesn't seem to be working.

**Comment by rpv-tomsk** [comment]
Hi,

I see no other way than add some debug lines into Collectd source code and see actual values.

**Comment by saurabhnanda** [comment]
scary doing this on production. What's the underlying kernel/C library function that this calls? probably I can write a small C program to see what that returns, which will not mess with my collectd installation on production.

**Comment by rpv-tomsk** [comment]
I'm doing the same. )

You can install source-built Collectd into another directory and run it in foreground.
To do not mess with system-wide installation you can do compile and install by unprivileged user and its homedir. If needed, you can then run Collectd with root privileges from these user dirs.

If you want to dig, then look into `cu_mount_getlist` implementation and `src/config.h` for defines.

**Comment by saurabhnanda** [comment]
Could this be the reason why this isn't working as expected - https://github.com/collectd/collectd/blob/87f8f66a84e78fd37dd2767c032ce74924d31dfd/src/utils/mount/mount.c#L753-L764 ?

**Comment by rpv-tomsk** [comment]
No, it should not be.

**Comment by rpv-tomsk** [comment]
Closed due to no response. 
Feel free to (re)open if needed.
Thanks for using Collectd.

**Comment by bendilley** [comment]
For me, it worked when I used `nfs4` as the FSType.
