### ISSUE TITLE
df is wrong when using systemd

### ISSUE THREAD

**Issue by btoneill** [collectd/collectd#3134]
*   Version of collectd: 5.8
*   Operating system / distribution: CentOS 7
*   Kernel version (if applicable):

## Expected behavior
df module should include mounted filesystems

## Actual behavior

df module includes all mounted filesystems as well as also including /etc and /usr as mounted filesystems, even if they aren't.

## Steps to reproduce

*   Run collectd with df module
*    See output

**Comment by btoneill** [comment]
The cause of this is known, but, not sure what the proper fix is.

In CentOS 7, /etc/mtab is a symlink to /proc/self/mounts.
The systemd service file for collectd has "ProtectSystem=full"
ProtectSystem=full causes /etc and /usr to be mounted ro for the process and shows up as a ro mount in /proc/${PID}/mounts for the collectd pid
collectd parses /etc/mtab, which then gives us the systemd protected filesytem mounts.

Not sure what the best option to fix this is.

Maybe have it look for /proc/1/mounts instead of /etc/mtab? That is pretty ugly tho...
Maybe an option to use a different file for COLLECTD_MNTTAB as an option to the df module?

**Comment by btoneill** [comment]
Or, the other option is remove ProtectSystem=full, not sure if that's a better solution or note. It gets around the problem, but, it does get rid of the added little bit of security that systemd gives you.

**Comment by btoneill** [comment]
Looks like not all that much actually uses this value on CentOS 7 at least.

$ grep -R ProtectSystem .
./multi-user.target.wants/NetworkManager.service:ProtectSystem=true
./multi-user.target.wants/collectd.service:ProtectSystem=full
./dbus-org.bluez.service:ProtectSystem=full
./bluetooth.target.wants/bluetooth.service:ProtectSystem=full
./dbus-org.freedesktop.NetworkManager.service:ProtectSystem=true

**Comment by rubenk** [comment]
> df module includes all mounted filesystems as well as also including /etc and /usr as mounted filesystems, even if they aren't.

Are you sure they aren't? I think systemd mounts them in a private mount namespace. I think collectd does what it's supposed to do here. You can always exclude /etc/ and /usr.

**Comment by btoneill** [comment]
I don't think we want it to add in /etc and /usr. If I change ProtectSystem=false in the collectd.service file it no longer mounts /etc and /usr and collectd no longer adds them. 

Doing Mountpoint /etc and doing an ignore of that doesn't work as I'm telling it already to only do ext4/xfs/zfs with IgnoreSelected=false. 

$ ls -la /etc/mtab
lrwxrwxrwx 1 root root 17 Apr  3 11:50 /etc/mtab -> /proc/self/mounts
$ ps -p 1329
  PID TTY          TIME CMD
 1329 ?        00:00:54 collectd
$ grep xfs /proc/1329/mounts
/dev/mapper/VolGroup00-Root / xfs rw,relatime,attr2,inode64,noquota 0 0
/dev/sda1 /boot xfs ro,relatime,attr2,inode64,noquota 0 0
/dev/mapper/VolGroup00-Temp /tmp xfs rw,relatime,attr2,inode64,noquota 0 0
/dev/mapper/VolGroup00-Root /etc xfs ro,relatime,attr2,inode64,noquota 0 0
/dev/mapper/VolGroup00-Root /usr xfs ro,relatime,attr2,inode64,noquota 0 0
$ grep xfs /proc/self/mounts
/dev/mapper/VolGroup00-Root / xfs rw,relatime,attr2,inode64,noquota 0 0
/dev/sda1 /boot xfs rw,relatime,attr2,inode64,noquota 0 0
/dev/mapper/VolGroup00-Temp /tmp xfs rw,relatime,attr2,inode64,noquota 0 0

**Comment by rubenk** [comment]
What do you suggest we do?

**Comment by btoneill** [comment]
I think we just remove the "ProtectSystem=false" from the collectd.service file. Very few things seem to use it, at least on CentOS 7. Not sure what other things might also be impacted that we haven't noticed from the sandboxing attempt that systemd is doing.

**Comment by mrunge** [comment]
@btoneill Where did you get the package from? I can not find `ProtectSystem=false` here https://src.fedoraproject.org/rpms/collectd/blob/epel7/f/collectd.service or here: https://github.com/centos-opstools/collectd/blob/master/collectd.service

**Comment by btoneill** [comment]
I've using the service file in the collectd contrib directory. 
https://github.com/collectd/collectd/blob/master/contrib/systemd.collectd.service

**Comment by mrunge** [comment]
Thank you, that's a file I didn't see there.
