### ISSUE TITLE
Failing to parse ceph json values 

### ISSUE THREAD

**Issue by ki4rbc** [collectd/collectd#3154]
## Software Versions
*   Version of collectd:                         5.8.0.145.gca1cb27
*   Operating system / distribution:     16.04.6 LTS (xenial)
*   Kernel version (if applicable):           4.4.0-145-generic
*   Ceph version:                                 13.2.5-1xenial (mimic)

## Expected behavior

No errors log and values parsed into data files

## Actual behavior

The following errors are presented in logs
```
[2019-05-14 19:51:25] [info] Initialization complete, entering read-loop.
[2019-05-14 19:51:25] [error] ceph plugin: ds Client.reply.avgtime was not properly initialized.
[2019-05-14 19:51:25] [error] ceph plugin: JSON handler failed with status -1.
[2019-05-14 19:51:25] [warning] ceph plugin: cconn_handle_event(name=mgr.a,i=0,st=4): error 1
[2019-05-14 19:51:25] [error] ceph plugin: ds FinisherMonFinisher.completeLatency.avgtime was not properly initialized.
[2019-05-14 19:51:25] [error] ceph plugin: JSON handler failed with status -1.
[2019-05-14 19:51:25] [warning] ceph plugin: cconn_handle_event(name=mon.a,i=0,st=4): error 1
[2019-05-14 19:51:25] [error] ceph plugin: ds Filestore.journalLatency.avgtime was not properly initialized.
[2019-05-14 19:51:25] [error] ceph plugin: JSON handler failed with status -1.
[2019-05-14 19:51:25] [warning] ceph plugin: cconn_handle_event(name=osd.1,i=1,st=4): error 1
[2019-05-14 19:51:25] [error] ceph plugin: ds Filestore.journalLatency.avgtime was not properly initialized.
[2019-05-14 19:51:25] [error] ceph plugin: JSON handler failed with status -1.
[2019-05-14 19:51:25] [warning] ceph plugin: cconn_handle_event(name=osd.5,i=2,st=4): error 1
[2019-05-14 19:51:25] [error] ceph plugin: ds Filestore.journalLatency.avgtime was not properly initialized.
[2019-05-14 19:51:25] [error] ceph plugin: JSON handler failed with status -1.
[2019-05-14 19:51:25] [warning] ceph plugin: cconn_handle_event(name=osd.8,i=3,st=4): error 1
```
Corresponding data points in RRD file are reporting `nan`

## Steps to reproduce

*   Create a ceph cluster 
*   install and configure collectd with Plugin ceph loaded

**Comment by ki4rbc** [comment]
ceph perf dump snippets
mgr.a
```json
    "client": {
        "reply": {
            "avgcount": 0,
            "sum": 0.000000000,
            "avgtime": 0.000000000
        }
```
mon.a
```json
    "finisher-mon_finisher": {
        "queue_len": 0,
        "complete_latency": {
            "avgcount": 0,
            "sum": 0.000000000,
            "avgtime": 0.000000000
        }
    }
```
ods.1
```json
    "filestore": {
        "journal_queue_ops": 0,
        "journal_queue_bytes": 0,
        "journal_ops": 159,
        "journal_bytes": 4083712,
        "journal_latency": {
            "avgcount": 29671630,
            "sum": 46371.329031084,
            "avgtime": 0.001562817
        },
        "journal_wr": 29205726,
        "journal_wr_bytes": {
            "avgcount": 29205726,
            "sum": 703751950336
        },
        "journal_full": 0,
        "committing": 0,
        "commitcycle": 82837,
        "commitcycle_interval": {
            "avgcount": 82837,
            "sum": 417514.226888356,
            "avgtime": 5.040190094
        },
        "commitcycle_latency": {
            "avgcount": 82837,
            "sum": 3322.271552838,
            "avgtime": 0.040106130
        },
        "op_queue_max_ops": 50,
        "op_queue_ops": 0,
        "ops": 29671630,
        "op_queue_max_bytes": 104857600,
        "op_queue_bytes": 0,
        "bytes": 618443680940,
        "apply_latency": {
            "avgcount": 29671630,
            "sum": 54230.675375644,
            "avgtime": 0.001827694
        },
        "queue_transaction_latency_avg": {
            "avgcount": 29671630,
            "sum": 1106.741051846,
            "avgtime": 0.000037299
        },
        "sync_pause_max_latency": 10.000214368
    }
```

**Comment by rpv-tomsk** [comment]
Hi,

I don't use `ceph` so my help on this issue will be very small.

As per http://docs.ceph.com/docs/emperor/dev/perf_counters/

you/we need to dump schema and look further.

```
ceph --admin-daemon /var/run/ceph/ceph-osd.0.asok perf schema
ceph --admin-daemon /var/run/ceph/ceph-osd.0.asok perf dump
```

**Comment by ki4rbc** [comment]
@rpv-tomsk Thanks Pavel, Please see attached.. Ignore the spelling error in the zip file name (perd=perf)

[ceph-perd-data.zip](https://github.com/collectd/collectd/files/3182985/ceph-perd-data.zip)

**Comment by rpv-tomsk** [comment]
>Also, keep in mind that I'm using mimic; the dev perf_counters page reads slightly different.

Don't understand this ..... 

Looking into your provided files does not helps me to understand causes.
I think you have to work on this issue debugging.
You have to study how collectd ceph plugin works and add some debug output into your logs (via `ERROR()`) by comiling Collectd from sources in your environment.

First point, IMHO, is to add something like
```
ERROR("ceph DEBUG: ds_num = %d; name=%s; type=%d; ds_name=%s.", d->ds_num, name, type, ds_name);
```
into `ceph_daemon_add_ds_entry()` before sstrncpy and see for values.

**Comment by ki4rbc** [comment]
Unfortunately, I'm installing the package from the collectd.org repo. I previously tried to turn on debug but got the error about needing to compile with the flag.

It may be a few days before I can do a compile on this.

**Comment by rpv-tomsk** [comment]
I saw no his commets for a long.

**Comment by ki4rbc** [comment]
--bump--

**Comment by ki4rbc** [comment]
Working on getting collectd compiled on the server.

**Comment by mrunge** [comment]
Any change here? It looks like you are using a git snapshot. There have been changes in the ceph plugin over 5.8.x release timeframe to support both older and never ceph versions.

**Comment by ki4rbc** [comment]
Yes, thanks. I've have used the latest version of collectd and was able to get the values.
