### ISSUE TITLE
Allow including time in tail plugin regex

### ISSUE THREAD

**Issue by clarfon** [collectd/collectd#3165]
Right now, the tail plugin always checks match 0 for the value, and uses the local time as the timestamp. For example, my nginx logs start with `[$time_iso8601/$status/$body_bytes_sent]` and so I have the rule:

```
<Match>
Regex "^\[[^\]+/\d+/(\d+)\]"
DSType "CounterAdd"
Type "bytes_counter"
Instance "body-bytes-sent"
</Match>
```

I wish I were able to do:

```
<Match>
Regex "^\[([^\]+)/\d+/(\d+)\]"
TimeFrom 0
ValueFrom 1
DSType "CounterAdd"
Type "bytes_counter"
Instance "body-bytes-sent"
</Match>
```

Note that the `tail_csv` plugin currently allows using a `TimeFrom` option. Unfortunately, I can't make my nginx logs properly output CSV (URLs can contain commas), but I can use the tail plugin instead.

**Comment by rpv-tomsk** [comment]
What is the problem you try to solve?

`TimeFrom` and setting time of metric to not localtime breaks things, and should not be used.

**Comment by clarfon** [comment]
I figure it's good for fault tolerance, in case either collectd crashes and isn't restarted immediately or nginx crashes and/or doesn't write logs quickly when a particularly long request is made. In either case, it may look like a large spike of requests happened when in reality that's not what actually happened.

Another thing to note is that I use socket activation for nginx, so on boot the requests are queued by systemd immediately and it could be a minute or even two before both nginx and collectd have both started and paid attention, even if the logs might state that requests had been happening the entire time.

Maybe I'm just thinking way too much into this, but it seems weird that reading timestamps from logs instead of using the local time would be bad for anything other than the extra time spent parsing. I'm also 80% certain the timestamps in the log will be monotonic as well, if that's the larger issue.

**Comment by rpv-tomsk** [comment]
>or doesn't write logs quickly when a particularly long request is made. In either case, it may look like a large spike of requests happened when in reality that's not what actually happened.

If you have long request, that it anyway will be displayed wrong - log record will be placed into one 'interval' while request traffic is sent during many. So, there is no benefits from 'TimeFrom'.

>in case either collectd crashes and isn't restarted 

That should not happen at all )

**Comment by rpv-tomsk** [comment]
```
<Match>
Regex "^\[[^\]+/\d+/(\d+)\]"
DSType "CounterAdd"
Type "bytes_counter"
Instance "body-bytes-sent"
</Match>
```

I think you had to use `DeriveAdd` and `bytes_counter` should be defined as `DERIVE` in types.db (like `apache_bytes`).

**Comment by clarfon** [comment]
> If you have long request, that it anyway will be displayed wrong - log record will be placed into one 'interval' while request traffic is sent during many. So, there is no benefits from 'TimeFrom'.

That's true, but this is recording the time the requests were initiated, not the time during which they took place. If 1000 people request a 1 MiB file in one second, and it takes 10 minutes to resolve that, that's very different from 1000 people requesting a 1 MiB file over the course of ten minutes, where the request is resolved nearly instantly. It may look similar in terms of bytes transferred, but it indicates a completely different type of traffic. 

> That should not happen at all

Every service can crash, and it isn't always the service's fault. No software is without bugs, and even though collectd is extremely fault-tolerant, it doesn't hurt to take precaution either way.

> I think you had to use `DeriveAdd` and `bytes_counter` should be defined as `DERIVE` in `types.db` (like `apache_bytes`).

This makes... a lot of sense. I will do this in the future.

**Comment by clarfon** [comment]
I still am a bit confused how the architecture of collectd makes it seem either wrong or difficult to account for a `TimeFrom` field, especially one that's monotonic, but assuming that this is the case, I think that `tail_csv` shouldn't have one for these reasons. I tried looking into why that was added but wasn't very fruitful in that.

**Comment by rpv-tomsk** [comment]
>That's true, 

>but this is recording the time the requests were initiated, not the time during which they took place. If 1000 people request a 1 MiB file in one second, and it takes 10 minutes to resolve that, that's very different from 1000 people requesting a 1 MiB file over the course of ten minutes, where the request is resolved nearly instantly. It may look similar in terms of bytes transferred, but it indicates a completely different type of traffic.

It is good that we agree that you have incorrect chars, regardless of  availability of `TimeFrom`.

>Every service can crash

You try to design system where Collectd crashes at each hour, while it works for years.
We have nothing to discuss here.

**Comment by rpv-tomsk** [comment]
>especially one that's monotonic

Tail plugin intended to do realtime parsing.
When you have realtime logs, they have real time value.
And Collectd also has same real time and should use that, not time from log.

There is absolutely no problem to use real time, and for your case too.

With 'TimeFrom' option, even if your log is not monotonic, you can still expect Collectd will pass time from log to ... destinations. That will not happen, as it is not supported by Collectd internals and possibly not supported by metric storages. For `tail_csv`, requirement of monotonic time value it is not documented, but it is present.

Collectd is not always sample of good engineering solutions and forethought.
If we add TimeFrom into tail plugin, then somebody will want to add the same into other plugins, such as  'curl', 'memcachec', 'dbi', etc. We see this on your example. But such is wrong by design.

You can add and use in your local fork. I do the same for my 'HUP patch', which implements Collectd reload of types.db on HUP signal. That is useful patch, but it don't pass requirements to go to upstream.

>I tried looking into why that was added but wasn't very fruitful in that.
You looked for:
https://github.com/collectd/collectd/commits/master?after=d1a010b0eb6dd725fc23f44a17da08fb535c792a+34&path%5B%5D=src&path%5B%5D=tail_csv.c

What is somehow related to Snort.
