### ISSUE TITLE
collectd fails to build with Python 3.8

### ISSUE THREAD

**Issue by stratakis** [collectd/collectd#3166]
*   Version of collectd: 5.8.1
*   Operating system / distribution:  Fedora Rawhide

Currently on Fedora we are testing rebuilding the distro against Python 3.8 and collectd is one of the packages that failed to build from source.

This happens when the --enable-python option is given, due to `python3-config --libs` [invocation](https://github.com/collectd/collectd/blob/dfb17826ceb8223cca9009b7b9f4194252ff994d/configure.ac#L4774) requiring also the `--embed` flag, with Python 3.8, in order to link the application to libpython.

As this is applicable only for 3.8, using the same flag on lesser versions will make the compilation fail as well, so a conditional would be required there. [More info](https://docs.python.org/3.8/whatsnew/3.8.html#debug-build-uses-the-same-abi-as-release-build).

Full build log attached.

[build.log.gz](https://github.com/collectd/collectd/files/3248966/build.log.gz)

**Comment by rpv-tomsk** [comment]
Thanks for your report!
Patches are welcome.
