### ISSUE TITLE
Version 5.9.0 will not build as x86 system

### ISSUE THREAD

**Issue by Roland-F** [collectd/collectd#3179]
By building collect 5.9.0 with cross-compiling (Buildroot), it works for an x86_64 system.
But when i try this for an x86 system i will get during the build the following faults:
src/daemon/plugin.c: In function 'plugin_init_all':
src/daemon/plugin.c:838:34: error: '%llu' directive output may be truncated writing between 1 and 10 bytes into a region of size 9 [-Werror=format-truncation=]
     snprintf(name, sizeof(name), "writer#%" PRIu64,
                                  ^~~~~~~~~~
src/daemon/plugin.c:838:42: note: format string is defined here
     snprintf(name, sizeof(name), "writer#%" PRIu64,
src/daemon/plugin.c:838:34: note: directive argument in the range [0, 4294967295]
     snprintf(name, sizeof(name), "writer#%" PRIu64,
                                  ^~~~~~~~~~
src/daemon/plugin.c:838:5: note: 'snprintf' output between 9 and 18 bytes into a destination of size 16
     snprintf(name, sizeof(name), "writer#%" PRIu64,
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
              (uint64_t)write_threads_num);
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/daemon/plugin.c:649:34: error: '%llu' directive output may be truncated writing between 1 and 10 bytes into a region of size 9 [-Werror=format-truncation=]
     snprintf(name, sizeof(name), "reader#%" PRIu64, (uint64_t)read_threads_num);
                                  ^~~~~~~~~~
src/daemon/plugin.c:649:42: note: format string is defined here
     snprintf(name, sizeof(name), "reader#%" PRIu64, (uint64_t)read_threads_num);
src/daemon/plugin.c:649:34: note: directive argument in the range [0, 4294967295]
     snprintf(name, sizeof(name), "reader#%" PRIu64, (uint64_t)read_threads_num);
                                  ^~~~~~~~~~
src/daemon/plugin.c:649:5: note: 'snprintf' output between 9 and 18 bytes into a destination of size 16
     snprintf(name, sizeof(name), "reader#%" PRIu64, (uint64_t)read_threads_num);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

I suggest that this problem come up as by the src/daemon/plugin.c now will be set some parts for pure x86_64 system (PRIu64; unit64_t) and they will be not available as x86 system.

Best regards,
Roland Franke

**Comment by mrunge** [comment]
Hi,

what do you mean here: does it work or doesn't it? Are you cross-compiling on non x86 systems?

Please also add info in the used c-compiler, as  I suspect that to be the issue here.

**Comment by Roland-F** [comment]
My builder is an x86_64 system.
Buildroot works with uclibc and gcc/g++ as compiler.
During the build, i be getting the shown fault-messages and so the compile is stopped.
But i will be at the test with an other solution, as the kernel-modules be not build at the moment.
And this may be a point, why the x86 build gone fault. 
Will inform here what happened when i restart the build from collectd, after the kernel-modules be build ready.

**Comment by Roland-F** [comment]
My build will stuck at the same errors as informed at my first information.
More as this is not known from me.
Only as hint: With the same cross-compile system, but with target as x86_64 system the build will work.
Additional was the version V5.8.1 working for me also at the same system. Only after updating the version to 5.9.0, the build stock in the x86 variant.

**Comment by mrunge** [comment]
Hmm, it works on or koji-type builder https://review.rdoproject.org/r/#/c/21124/

I assume, you're running into an incarnation of https://github.com/collectd/collectd/issues/3038

**Comment by Roland-F** [comment]
Please get the information, that gcc is in version 7.3.0.
Will just try to update gcc to version 7.4.0 and look then what happend.
An feedback can be given tomorrow (06/18/2019) here.

**Comment by Roland-F** [comment]
Sorry. No change. Building still leaks with identical messages from my first post here.

**Comment by Roland-F** [comment]
Hello,
with the following patch the build will work for me for an x86_64 and x86 system

diff -purN collectd-5.9.0_org/src/daemon/plugin.c collectd-5.9.0/src/daemon/plugin.c
--- collectd-5.9.0_org/src/daemon/plugin.c	2019-06-13 11:13:42.551364463 +0200
+++ collectd-5.9.0/src/daemon/plugin.c	2019-06-19 23:03:00.111842000 +0200
@@ -645,7 +645,7 @@ static void start_read_threads(size_t nu
       return;
     }
 
-    char name[THREAD_NAME_MAX];
+    char name[THREAD_NAME_MAX + 2];
     snprintf(name, sizeof(name), "reader#%" PRIu64, (uint64_t)read_threads_num);
     set_thread_name(read_threads[read_threads_num], name);
 
@@ -834,7 +834,7 @@ static void start_write_threads(size_t n
       return;
     }
 
-    char name[THREAD_NAME_MAX];
+    char name[THREAD_NAME_MAX + 2];
     snprintf(name, sizeof(name), "writer#%" PRIu64,
              (uint64_t)write_threads_num);
     set_thread_name(write_threads[write_threads_num], name);

**Comment by LeSpocky** [comment]
FWIW,

> Hmm, it works on or koji-type builder https://review.rdoproject.org/r/#/c/21124/
> 
> I assume, you're running into an incarnation of #3038

What happens here is running a new compiler with better "analysis power". It's independent from architecture. If `THREAD_NAME_MAX` is e.g. 16 and you want to write "writer#12345" to it, and 12345 is supposed to be an unsigned 64 integer, the maximum theoretical possible value would be "writer#18446744073709551615" with 7 + 20 digits (without null termination), which is clearly longer than the provided string buffer. `snprintf()` would truncate the resulting string and that's what the warning is about.

**Comment by LeSpocky** [comment]
However I would not cast `write_threads_num` from size_t to uint64_t, but use the '%zu' format specifier instead or tweak `THREAD_NAME_MAX` or both.

**Comment by LeSpocky** [comment]
The other question here is, who sets `-Werror`. Is it collectd, buildroot or the modified buildroot of fli4l? :wink:

**Comment by LeSpocky** [comment]
I saw commit abaa1c8a24e8eff5632dd6052b1da5f6535caf19 in master which seems not to be part of the 5.9 branch, which "solves" that problem by introducing a wrapper around `snprintf()` … :astonished:

**Comment by Roland-F** [comment]
Hello,
version 5.9.1 from GitHub will also not work for me  original.
I have now change in src/daemon/plugin.c two more lines from snprintf to ssnprintf 
and then the build on the x86 system will work.
changes will be:

@@ -645,7 +645,7 @@ static void start_read_threads(size_t nu
     }

     char name[THREAD_NAME_MAX];
-    snprintf(name, sizeof(name), "reader#%" PRIu64, (uint64_t)read_threads_num);
+    ssnprintf(name, sizeof(name), "reader#%" PRIu64, (uint64_t)read_threads_num);
     set_thread_name(read_threads[read_threads_num], name);

     read_threads_num++;
@@ -834,7 +834,7 @@ static void start_write_threads(size_t n
     }

     char name[THREAD_NAME_MAX];
-    snprintf(name, sizeof(name), "writer#%" PRIu64,
+    ssnprintf(name, sizeof(name), "writer#%" PRIu64,
              (uint64_t)write_threads_num);
     set_thread_name(write_threads[write_threads_num], name);



Best regards,
Roland Franke
