### ISSUE TITLE
LVM plugin breaks with russian locale

### ISSUE THREAD

**Issue by Self-Perfection** [collectd/collectd#3181]
*   Version of collectd: 5.8.1
*   Operating system / distribution: Arch linux

## Expected behavior

Collectd should collect data regardless of locale.

## Actual behavior

When running with LANG=ru_RU.UTF-8 in envirnoment and enabling LVM plugin collectd can't create rrd files for LVM plugin data. 

## Steps to reproduce

*   Make sure there is no rrd files for LVm plugin
*   uncomment LVM plugin in config and run collectd as `LANG=ru_RU.UTF-8 collectd`
*   Observe in logs something like:
```
июн 19 00:43:29 lvm[15599]: Filter subsystem: Built-in target `write': Dispatching value to all write plugins failed with status -1.
июн 19 00:43:29 lvm[15599]: rrdtool plugin: rrd_create_r (localhost.localdomain/lvm-vg01/df_complex-root.rrd) failed: parsing min val - Converted '0,000000' to 0,000000, but cannot convert ',000000'
июн 19 00:43:29 lvm[15599]: cu_rrd_create_file: srrd_create (localhost.localdomain/lvm-vg01/df_complex-root.rrd) returned status -1.
```

Looks like locale-aware function is used somewhere to dispatch value from LVM plugin,

**Comment by rpv-tomsk** [comment]
Solution: Don't start Collectd with russian locale.

**Comment by Self-Perfection** [comment]
I'd rather say this is a workaround. I'd like to stress that user might quite easily bump into this issue with normally configured system. Setting system-wide locale is [a standard and documented practice](https://wiki.archlinux.org/index.php/Locale#Setting_the_system_locale). And systemd passes `LANG` environment variable to running daemons (one may check with `strings /proc/$(pidof collectd)/environ`).

So I had to add extra config to avoid this:

```
cat /etc/systemd/system/collectd.service.d/override.conf
[Service]
# collectd lvm plugin seems to break on number format with russian locale
# See https://github.com/collectd/collectd/issues/3181

UnsetEnvironment=LANG
```

**Comment by rpv-tomsk** [comment]
>I'd rather say this is a workaround.

Ok, patches are welcome.

**Comment by rpv-tomsk** [comment]
The cause was found: https://github.com/collectd/collectd/commit/865f2eb31e8264edd9337bc63ac59f6c2fa3b5a7#diff-67e997bcfdac55191033d57a16d1408a and patch will be applied soon.

Thanks for reporting this.
Thanks for using Collectd.

**Comment by rpv-tomsk** [comment]
As I see, Team committed my PR.

Unfortunately, they don't care about this issue so it was not closed. :-(

**Comment by Self-Perfection** [comment]
All right, let's close this, if you believe that fix is committed.

**Comment by Self-Perfection** [comment]
Yup, indeed fixed. Could not reproduce with collectd 5.9.2
