### ISSUE TITLE
limited info shows up in snmpwalk

### ISSUE THREAD

**Issue by lsh0209** [collectd/collectd#3183]
Hi I am new to snmp, I am currently want to use the collectd to monitor the snmp from SAN device. However when I try run the snmpwalk, I only got very limited MIB shows up. 

SNMPv2-MIB::sysDescr.0 = STRING: NetApp Release 9.3P2: Fri Mar   02 01:02:58 UTC 2018
--
SNMPv2-MIB::sysObjectID.0   = OID: SNMPv2-SMI::enterprises.XXX.X.X |   |  
DISMAN-EVENT-MIB::sysUpTimeInstance =   Timeticks: (649745691) 75 days | 4:50:56.91 |   |   |   |   |   |  
SNMPv2-MIB::sysContact.0   = STRING: Technology Service Delivery Storage Support |  
SNMPv2-MIB::sysName.0   = STRING: XXXXX.XX |   |  
SNMPv2-MIB::sysLocation.0   = STRING: XXXXX |   |   |   |  
SNMPv2-MIB::sysServices.0   = INTEGER: 72 |   |   |   |  

Besides, when I try run the MIB I want to monitor 

snmpwalk –v 1 -c <community string> <ipaddress> ifInErrors
 
It shows No Such Object available on this agent at this OID.

**Comment by rpv-tomsk** [comment]
Hi,

That is not related to Collectd itself, but to SNMP.

In my try `snmpwalk -v 1 -c public 192.168.0.1` gives me all available OIDs.
If that is not your case, try to find and read your device guide or refer to vendor to get correct OIDs.

Thanks for using Collectd.
