### ISSUE TITLE
Collectd stops when local drive fails

### ISSUE THREAD

**Issue by kazeborja** [collectd/collectd#3184]
*   Version of collectd: 5.8.1
*   Operating system / distribution: RedHat

## Expected behavior

We use collectd to monitor drive failures, however when one of the drives fails it stops the fs-local.target triggering also a stop of Collectd and avoiding the metrics/notifications to be issued.

What we will expect is Collectd to continue running unless a critical drive (i.e OS related one) is failing.

## Actual behavior

Collectd is stopped following the systemd dependency tree whenever fs-local.target service is stopped.

This is caused by the line https://github.com/collectd/collectd/blob/master/contrib/systemd.collectd.service#L5

**Comment by faxm0dem** [comment]
Thanks for identifying this issue.
What would you suggest to correct the behaviour?

**Comment by kazeborja** [comment]
Well, that's a hard question... from my side I think removing that line in the service will be enough to prevent it restarting when any drive fails. Then of course if Collectd can't write to disk because the drive that failed is the main one I guess it will just crash.

I'm not 100% aware of the full implications it might have on the process not being able to write to disk, that's also why I reported here the issue to get some expert knowledge on the matter :D. I guess that line was added there for some reason.

**Comment by faxm0dem** [comment]
My first idea was this line is present to ensure at least collectd's config fine is readable, not to mention its binary and libraries :-)

**Comment by kazeborja** [comment]
That should still be supported by the After... but yes in case there is an issue while the process is running the behaviour there will be probably a hard crash VS a clean stop

**Comment by faxm0dem** [comment]
I think most people would want to keep the current behaviour.
Moreover, the systemd unit file ist kept in the contrib folder, and package maintainers are free to adapt it to their needs. In your case, I'd suggest adding a systemd dropin file to change its behaviour to your use-case. This would also not be overwritten when updating collectd. Would that "workaround" suit your needs?

**Comment by kazeborja** [comment]
I had that in mind was just a bit worried of possible unexpected outcomes, but that should work for us.

**Comment by faxm0dem** [comment]
I suggest that you either close this, or propose a possible fix (ideally in the form of a PR) which can then be discussed further

**Comment by kazeborja** [comment]
We tested a fix on our side, following the suggestion to keep it as something outside from upstream I guess the best is to close it as it's.
