### ISSUE TITLE
ignorelist_create is not exported any more

### ISSUE THREAD

**Issue by bdrung** [collectd/collectd#3185]
* Version of collectd: 5.8.1-1.3
* Operating system / distribution: Debian testing

## Expected behavior

I want to be able to write an external plugin that uses the `ignorelist_` functions which are present in `/usr/include/collectd/core/utils_ignorelist.h`.

## Actual behavior

Building the external module works, but collectd will fail to start:

```
collectd: dlopen ("/usr/lib/collectd/myplugin.so") failed: /usr/lib/collectd/myplugin.so: undefined symbol: ignorelist_create. The most common cause for this problem is missing dependencies. Use ldd(1) to check the dependencies of the plugin / shared object.
collectd: ERROR: dlopen ("/usr/lib/collectd/myplugin.so") failed: /usr/lib/collectd/myplugin.so: undefined symbol: ignorelist_create. The most common cause for this problem is missing dependencies. Use ldd(1) to check the dependencies of the plugin / shared object.
```

**Comment by rpv-tomsk** [comment]
I don't know how you build your plugin, but in `collectd/Makefile.am` we have something like this:

```
if BUILD_PLUGIN_CGROUPS
pkglib_LTLIBRARIES += cgroups.la
cgroups_la_SOURCES = src/cgroups.c
cgroups_la_LDFLAGS = $(PLUGIN_LDFLAGS)
cgroups_la_LIBADD = libignorelist.la libmount.la
endif
```

Maybe you need something similar.

**Comment by bdrung** [comment]
We build our external plugin in a Debian package which build depends on collectd-dev. collectd-dev does not contain the .la files. Therefore this does not work for us.

**Comment by rpv-tomsk** [comment]
What was the latest version which works for you?

**Comment by rpv-tomsk** [comment]
>I would prefer if I could dynamically link against those functions instead of static linking.

Patches are welcome.

**Comment by bdrung** [comment]
The last know working version is 5.7.1.

Hints how to solve this issue are welcome. I tried adding `libignorelist.la` to `collectd_LDADD`, but this did not work.

**Comment by rpv-tomsk** [comment]
I can confirm, collectd-5.6 binary has these functions in `sbin/collectd`,  while in collectd-5.9 they are in each plugin.

**Comment by rpv-tomsk** [comment]
#1323

**Comment by dswarbrick** [comment]
Let's do the time warp, again 🎵

**Comment by rpv-tomsk** [comment]
As a maintainer without code writing privilege, I can't / willn't write PR to fix this issue.
So, anybody should do this and I should wait for PR which will update `collectd/Makefile.am:230`.

#2958

https://github.com/orgs/collectd/teams/trusted-contributors/discussions/1

**Comment by rpv-tomsk** [comment]
That is by design: see comment for https://github.com/collectd/collectd/commit/4dedfa46272ffa0c52e426b3051fddd0b8d0bea2 commit:

```
The collectd daemon isn't using the "ignorelist" functionality itself --
it was only linked in to provide it to loaded plugins. Since the code is
under the GPL, this interfers with our intend of having an MIT licensed
daemon.

This patch changes the build system to link plugins with the ignorelist
directly instead of expecting the symbols to be in the daemon.
```

**Comment by rpv-tomsk** [comment]
>We build our external plugin in a Debian package which build depends on collectd-dev. collectd-dev does not contain the .la files. 

Also want to notice, Debian package  for collectd-5.9 will not provide `utils_ignorelist.h` too (see https://github.com/collectd/pkg-debian/blob/master/debian/collectd-dev.install)

**Comment by rpv-tomsk** [comment]
>We build our external plugin in a Debian package which build depends on collectd-dev. collectd-dev does not contain the .la files. Therefore this does not work for us. I would prefer if I could dynamically link against those functions instead of static linking.

I think, you should include ignorelis.c/h into your codebase.
