### ISSUE TITLE
collectd crashes with assertion "ce->values_num == ds->ds_num"

### ISSUE THREAD

**Issue by tainguyennc** [collectd/collectd#3186]
*   Version of collectd:
Version 5.8.0

*   Operating system / distribution:
Linux

*   Kernel version (if applicable):
Linux  4.1.15-224375-g84a8551b04d2 #1 SMP PREEMPT Wed Jun 5 19:44:05 UTC 2019 armv7l GNU/Linux

## Expected behavior

(Description of the behavior / output that you expected)
collectd doesn't crash

## Actual behavior

(Description of the behavior / output that you observed)
Collectd crashed with the message
collectd: src/daemon/utils_cache.c:336: uc_update: Assertion `ce->values_num == ds->ds_num' failed

## Steps to reproduce

This issue doesn't happen frequently and we can't reproduce it at will

**Comment by rpv-tomsk** [comment]
What is your configuration?

**Comment by rpv-tomsk** [comment]
Closed due to no response.
Thanks for using Collectd.
