### ISSUE TITLE
Documentation on how to compile with python3? 

### ISSUE THREAD

**Issue by josh-byster** [collectd/collectd#3192]
*   Version of collectd: 5.9.0
*   Operating system / distribution: Linux/Ubuntu
*   Kernel version (if applicable):

## Expected behavior
It would be very nice to have an idea of how to build `collectd` or run it using a version of Python other than 2.7 (>= 3.0). I know that it's included as part of `libpython2.7` on `apt` but there isn't any documentation or explanation on what steps one would take to use a custom version of Python as part of build process. Is there some outline of what flags and valuews to pass in to perform this alternate compilation, or, even better, being able to run it with `python3` using a [distributed](https://packages.ubuntu.com/bionic/collectd) already-built binary?

**Comment by mrunge** [comment]
like this

    ./configure
          ....
           --with-python=/usr/bin/python3
          ....

E.g. see here: https://src.fedoraproject.org/rpms/collectd/blob/master/f/collectd.spec#_656
