### ISSUE TITLE
DF plugin: ReportReserved not working anymore

### ISSUE THREAD

**Issue by sbarrier** [collectd/collectd#3208]
*   Version of collectd: 5.9.0
*   Operating system / distribution: Linux / Centos
*   Kernel version (if applicable): 3.10

* Error messages :
```
collectd[47518]: Plugin `df' did not register for value `ReportReserved'.
collectd: Error: Parsing the config file failed!
```

* collectd.conf section for DF plugin :
```
<Plugin df>
       MountPoint "/"
       IgnoreSelected false
       ReportByDevice false
       ReportInodes false
       ReportReserved false
</Plugin>
```
Removing ReportReserved from configuration worked.
Does something changed between collectd 5.8 and 5.9 ?

**Comment by faxm0dem** [comment]
Yes this is probably related to 3b9c7b21b4ddfcf59a0147bc9e91e8889ca78d56 which introduced stricter checking. The `ReportReserved` option was removed a long time ago it seems (5.0.0).
