### ISSUE TITLE
problem in compile write_prometheus plugins

### ISSUE THREAD

**Issue by NingLee** [collectd/collectd#3210]
*   Version of collectd: 5.8.1
*   Operating system / distribution: centos
*   Kernel version (if applicable):

## Expected behavior
I compile collectd and I found write_prometheus plugins requires libmicrohttpd, and I installed it.

configure can find libmircrohttpd library and check ok
    libmicrohttpd . . . . yes
but in `Modules` write_prometheus is not included.
    write_prometheus. . . no

and I manually modified the Makefile, and found `prometheus.pb-c.h` file is not found. I googled and don't know where to find this.

**Comment by rpv-tomsk** [comment]
You need protobuf-compiler (or some similar named) package installed.
On my Debian system I have one:
```
# dpkg-query -l |grep protobuf-c-compiler
ii  protobuf-c-compiler                   1.0.2-1                           i386         Protocol Buffers C compiler (protobuf-c)
```
