### ISSUE TITLE
FPM status metrics not collected

### ISSUE THREAD

**Issue by autodeck** [collectd/collectd#3215]
*   Version of collectd: 5.8.0
*   Operating system / distribution: AWS Linux 2018.03
*   Kernel version (if applicable): 4.14.104-78.84.amzn1.x86_64

## Expected behavior
FPM status metrics are collected

## Actual behavior
Error in log:
`There is a 'URL' block within the configuration for the curl_json plugin. The plugin either only expects "simple" configuration statements or wasn't loaded using 'LoadPlugin'. Please check your configuration.`

## Steps to reproduce
See attached config files
[collectd_fpm.txt](https://github.com/collectd/collectd/files/3386746/collectd_fpm.txt)

**Comment by rpv-tomsk** [comment]
```# tail -n 2 /var/log/collectd.log```

Look into your logs carefully.

**Comment by autodeck** [comment]
As can be seen in the attached file, I have the following set in /etc/collectd.conf:
`LoadPlugin curl_json`

I'm not sure what is meant by 
`"simple" configuration statements` 

I see no reference to it in the documentation:
[https://collectd.org/wiki/index.php/Plugin:cURL-JSON/phpfpm](url)

**Comment by rpv-tomsk** [comment]
In most of cases, "The plugin either only expects "simple" configuration statements or wasn't loaded using 'LoadPlugin'" message says about plugin was not loaded successfully.

That possible due to missing deps. Check for deps by `ldd /usr/lib/collectd/curl_json.so` command.
You should get no "not found" messages. If they present, you had to install missing libs.

**Comment by rpv-tomsk** [comment]
You have " plugin_load: plugin "python" successfully loaded." message.
You should have same for "curl_json" plugin. But I think, you have similar about "Load plugin failed", or do something other in a wrong way.

**Comment by dago** [comment]
@autodeck This looks strange, you do not load the Python plugin, but there is a line in the log saying that it was loaded, but there are no lines about curl_json. Were you able to resolve the issue?
