### ISSUE TITLE
Disable suspend on "read-function of plugin `snmp' failed."-errors

### ISSUE THREAD

**Issue by n1els** [collectd/collectd#3218]
*   Version of collectd: 5.8.1
*   Operating system / distribution:CentOS 7
*   Kernel version (if applicable):3.10.0-957.21.3.el7

## Expected behavior

(Description of the behavior / output that you expected)
We are monitoring a few hundred routers using the snmp plugin. When a router is down, the snmp plugin will fail and the monitoring system receives null, thus showing the router as down.
When data is once again received, the monitoring will display bandwidth and other metrics again.

## Actual behavior

(Description of the behavior / output that you observed)
Jul 15 13:32:09 collectd collectd[1181]: read-function of plugin `snmp-routername' failed. Will suspend it for 2560.000 seconds.

The actual outage lasted for quite a bit, but the incremental suspend rate that (this version of) collectd seems to apply makes the outage seem much much longer.

Is there a way to either disable the suspend setting, or to limit it to a certain amount of time? The behavior displayed would make my outage seem over 40 minutes longer than it would have been had I not manually restarted the service.

## Steps to reproduce

*   step 1 - Add device with snmp (or any other plugin I think) in collectd config.
*   step 2 - Create downtime on device. tail log and wait for increments to appear.
*   step 3 - Resolve downtime on device, you now have to wait for the suspend time to be over before you start receiving data despite the device being up already.

**Comment by rpv-tomsk** [comment]
>Is there a way to either disable the suspend setting, or to limit it to a certain amount of time?

Please, read the docs. `MaxReadInterval` option.

**Comment by n1els** [comment]
Thanks! I was searching for words like suspend and couldn't find it... must have overlooked it.

Implementing it now...
