### ISSUE TITLE
Build of test_plugin_network is lacking -lnsl on Solaris

### ISSUE THREAD

**Issue by dago** [collectd/collectd#3220]
The current `master` introduced a new error that it is lacking `-lnsl` (which is needed on Solaris in addition to `-lsocket` for `inet_pton`) during linkage:

```
/bin/bash ./libtool  --tag=CC   --mode=link /opt/solarisstudio12.4/bin/cc -std=c99   -module -avoid-version -export-symbols-regex '\<module_register\>'    -o test_plugin_network src/test_plugin_network-network_test.o src/test_plugin_network-utils_fbhash.o src/daemon/test_plugin_network-configfile.o src/daemon/test_plugin_network-types_list.o libavltree.la liboconfig.la libplugin_mock.la libmetadata.la -L/opt/csw/lib -lgcrypt -lgpg-error 
libtool: link: /opt/solarisstudio12.4/bin/cc -std=c99 -o test_plugin_network src/test_plugin_network-network_test.o src/test_plugin_network-utils_fbhash.o src/daemon/test_plugin_network-configfile.o src/daemon/test_plugin_network-types_list.o  ./.libs/libavltree.a ./.libs/liboconfig.a -ll ./.libs/libplugin_mock.a -lpthread -lrt -lsocket -lkstat -ldevinfo ./.libs/libmetadata.a -L/opt/csw/lib -lgcrypt -lgpg-error
Undefined                       first referenced
 symbol                             in file
inet_pton                           src/test_plugin_network-network_test.o  (symbol belongs to implicit dependency /lib/libnsl.so.1)
inet_ntop                           src/test_plugin_network-network_test.o  (symbol belongs to implicit dependency /lib/libnsl.so.1)
ld: fatal: symbol referencing errors. No output written to test_plugin_network
```

**Comment by dago** [comment]
I think the issue is that in
  https://github.com/collectd/collectd/blob/master/configure.ac#L857
only `-lsocket` is checked to be required for `socket()` where at least for Solaris another check would be needed that also tests for the requirement of `-lnsl` being linked as documented in `socket(3socket)`:
```
NAME
     socket - create an endpoint for communication

SYNOPSIS
     cc [ flag ... ] file ... -lsocket  -lnsl  [ library ... ]
     #include <sys/types.h>
     #include <sys/socket.h>

     int socket(int domain, int type, int protocol);
```

**Comment by dago** [comment]
The test program `test_plugin_network` is built with this rule in `Makefile.am` and adds the library
```
if BUILD_WITH_LIBSOCKET
network_la_LIBADD += -lsocket
endif
```

The corresponding test for BUILD_WITH_LIBSOCKET  is In `configure.ac`:
```
AC_CHECK_FUNCS([socket],
  [],
  [
    AC_CHECK_LIB([socket], [socket],
      [socket_needs_socket="yes"],
      [
        AC_CHECK_LIB([gnu], [rpl_socket],
          [socket_needs_gnulib="yes"],
          [AC_MSG_ERROR([cannot find socket() in libsocket])]
        )
      ]
    )
  ]  
)  
AM_CONDITIONAL([BUILD_WITH_LIBSOCKET], [test "x$socket_needs_socket" = "xyes"])
```
There should probably a dedicated test if `inet_ntop` requires both libs `-lsocket -lnsl`.

**Comment by rubenk** [comment]
I'm wondering why it just fails here. We use inet_ntop in network.c and that file seems to compile fine.

But anyway, yes, we should probably have a compile test that tries to call inet_ntop.

**Comment by dago** [comment]
The linked pull request fixes the issue.

**Comment by mrunge** [comment]
Thank you! The fix has been merged.

**Comment by rubenk** [comment]
@dago Does OpenCSW still target Solaris 10, and for how long? I'd like to do some testing on Solaris, but I'd rather use Solaris 11 at this point.

**Comment by dago** [comment]
Forever? ;-) We have also machines with Solaris 11 for additional testing, if you want I can connect these to CI to give you an account.

**Comment by rubenk** [comment]
Hahaha ok :-) Having Solaris 11 in CI would be great.

**Comment by dago** [comment]
@rubenk The buildbot infrastructure at the OpenCSW buildfarm is still in place and at some point in time there was a hook in GitHub active for CollectD to trigger that on Commits and PRs, however IIRC it has been taken out due to compile errors on Solaris for some time where I hadn't fixed all issues. Maybe you can discuss that with the team if that could be reenabled - would definitely be fine with me!
