### ISSUE TITLE
Plugin iptables failed to handle option Chain, return code: 1

### ISSUE THREAD

**Issue by Whissi** [collectd/collectd#3235]
*   Version of collectd: 5.9.1
*   Operating system / distribution: Gentoo
*   Kernel version (if applicable): 4.9.186

## Expected behavior

Plugin should load.

## Actual behavior

Plugin doesn't load and collectd will log the error
```
Plugin iptables failed to handle option Chain, return code: 1
```

## Steps to reproduce

*   Compile collectd with iptables plugin
*   Create a chain in iptables
*   Try to load iptables plugin like
```
<Plugin "iptables">
        Chain filter "mychain"
</Plugin>
```

**Comment by faxm0dem** [comment]
also a duplicate of #3232

**Comment by faxm0dem** [comment]
Please verify that https://github.com/collectd/collectd/pull/3237 fixes this

**Comment by Whissi** [comment]
This seems to be working with the fix.

**Comment by mrunge** [comment]
Should be fixed by https://github.com/collectd/collectd/pull/3237
