### ISSUE TITLE
RDT compile issue

### ISSUE THREAD

**Issue by mrunge** [collectd/collectd#3242]
*   Version of collectd: 5.9.1

## Expected behavior
compiles fine

## Actual behavior

```
  CCLD     hugepages.la
  CC       src/intel_rdt_la-intel_rdt.lo
In file included from src/utils/common/common.h:33,
                 from src/intel_rdt.c:32:
In function ‘strlisttoarray’,
    inlined from ‘oconfig_to_ngroups’ at src/intel_rdt.c:424:11,
    inlined from ‘rdt_config_ngroups’ at src/intel_rdt.c:516:7,
    inlined from ‘rdt_config’ at src/intel_rdt.c:1149:16,
    inlined from ‘rdt_config’ at src/intel_rdt.c:1100:12:
./src/daemon/plugin.h:394:20: error: ‘%s’ directive argument is null [-Werror=format-overflow=]
  394 | #define ERROR(...) plugin_log(LOG_ERR, __VA_ARGS__)
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/intel_rdt.c:328:7: note: in expansion of macro ‘ERROR’
  328 |       ERROR(RDT_PLUGIN ": Duplicated process name \'%s\' in group \'%s\'",
      |       ^~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:7116: src/intel_rdt_la-intel_rdt.lo] Error 1
make[1]: Leaving directory '/home/mrunge/work/collectd'
make: *** [Makefile:4892: all] Error 2
```

## Steps to reproduce

*  Use master branch
*  ./configure --enable-intel-rdt
*   make

**Comment by mrunge** [comment]
The change breaking this was https://github.com/collectd/collectd/commit/7f6e8b79ab4bf40d08c8955e1feb67416f2dc358#diff-b4176ac9051daca66fe2917e4f4fa5f6

**Comment by anaudx** [comment]
hi Matthias,
which OS and version of gcc do you use?
I could not reproduce this issue on Ubuntu 16.04 with gcc 5.4.0 , nor on Ubuntu 18.04 with gcc 7.3.0, where collectd builds without any error.

**Comment by mrunge** [comment]
Hi,

that was seen on Fedora and on RHEL 8. I used gcc-9.1. 

From looking at the code https://github.com/collectd/collectd/blob/master/src/intel_rdt.c#L328-L329, it is most likely to have str_list to be NULL. The linked fix here could use some improvement.
