### ISSUE TITLE
Attach collectd-5.9.1.tar.bz2 to release

### ISSUE THREAD

**Issue by drnic** [collectd/collectd#3255]
Previously, github release included collectd-5.9.0.tar.bz2 file; e.g. https://github.com/collectd/collectd/releases/tag/collectd-5.9.0

Currently https://github.com/collectd/collectd/releases/tag/collectd-5.9.1 does not have this file. Our CI pipeline is sad.

Could 5.9.1 please have the file attached, and future releases continue to include the .tar.bz2 asset? Thanks!

**Comment by mrunge** [comment]
Thank you for your report. I understand. It is on the todo-list for 5.9.2 for me. 5.9.1 is somewhat broken, and I would suggest not to use it.

**Comment by drnic** [comment]
Thanks for suggestion on skipping 5.9.1

**Comment by lurkr2** [comment]
postgresql plugin broken in 5.9.1, #https://github.com/collectd/collectd/issues/3259

**Comment by mrunge** [comment]
Closing this for now, I'll keep attaching tarballs to github in mind, same for tarball naming and directories (github does some weirdness with them). Next one will be "as usual".
