### ISSUE TITLE
[bug] in src/postgresql.c: connection parameters are not taken

### ISSUE THREAD

**Issue by lurkr2** [collectd/collectd#3259]
*   Version of collectd: >=5.9.1
*   Operating system / distribution: debian stretch
*   Kernel version (if applicable): any

## Expected behavior
`<Plugin postgresql>
...
</Query>
	<Database ...>
		Host "example"
		User "postgres"
...
	</Database>
</Plugin>
`
hostname **example** and username **postgres** must be accepted

## Actual behavior
Error processing connection parameters.
The connection parameters specified in the config were not processed correctly, and therefore were not taken into account.
The snprintf function returns the number of bytes of a string, unlike
ssnprintf which returns bool.
Bug in processing connection parameters.
Connection parameters specified in the config were not taken into account

## Steps to reproduce

*   configure plugin postgresql with user=postgres and host=localhost
*   restart collectd daemon
*   check log and make sure the username is incorrect (root instead postgres)

`
Failed to connect to database  (): FATAL:  role "root" does not exist
`

**Comment by lurkr2** [comment]
#3258 fix it

**Comment by mrunge** [comment]
Already fixed by https://github.com/collectd/collectd/commit/c80ef3c943ed11f49d8d2c0440823d43ef0d7cd5
