### ISSUE TITLE
Debian 10 can't build collectd lvm2 support

### ISSUE THREAD

**Issue by izghitu** [collectd/collectd#3262]
*   Version of collectd: 5.9.0
*   Operating system / distribution: Debian 10
*   Kernel version (if applicable):

## Expected behavior

lvm . . . . . . . . . yes

## Actual behavior

lvm . . . . . . . . . no (lvm2app.h not found) (dependency error)

## Steps to reproduce

*   apt-get install liblvm2-dev
*   ./configure --enable-all-plugins --enable-debug
*   Support for lvm2app.h was deprecated in past lvm2 releases and is now completely removed in lvm2 2.03 so collectd will not be able to find it.

Please let me know how I can fix this and compile collectd with lvm support.
Thanks in advance

**Comment by zebity** [comment]
Hi @izghitu ,

I came across lvm issue when trying to build collectd on Ubuntu 19.04 (https://github.com/collectd/collectd/pull/3153).

here is my note from this:

> NOTE: lvm module compiles with error due to "deprecated warning" in /usr/include/lvm2app.h
> 
> #warning "liblvm2app is deprecated, use D-Bus API instead."
> I commented out warning in system header file to get around warning.
> see: #2820
> 

So issue was that underlying liblvm2app header was causing collectd build to fail, which is why it got deprecated I believe. Would this underlying deprecation problem not also surface on Debian ?

You can easy check for this by looking at the lvm2app.h header file...

Just providing pointer, as you might get tripped up like I did...

Cheers,

zebity.

**Comment by izghitu** [comment]
@zebity on Debian 10 I do not get a warning because lvm2app.h is not deprecated but is completely removed and missing. So the error is about collectd configure script not being able to find the headers and unable to compile lvm2 support.

Please let me know how to proceed

**Comment by mrunge** [comment]
what about adding `--disable-lvm` to configure?

That won't magically solve this.

When you are using `--enable-all-plugins`, the build process will try to build all plugins. Just removing that parameter will only build the plugins where you have the corresponding header files installed on your system. In this case, you don't have the header files for lvm2 installed. In Fedora, the package is called lvm2-devel.

**Comment by izghitu** [comment]
@mrunge but I need lvm support, why would I disable it?

I have the headers installed for lvm2 but the lvm2 on Debian 10 no longer contain lvm2app.h because it was deprecated and removed from lvm2

**Comment by mrunge** [comment]
Understood. That is tracked in https://github.com/collectd/collectd/issues/2820 , so this is a duplicate.

The question is: what is the alternative. The underlying library has changed. If you want this feature, port it to use the D-bus API.
