### ISSUE TITLE
Collectd battery plugin fails 

### ISSUE THREAD

**Issue by cnnaik** [collectd/collectd#3267]
*   Version of collectd: 5.8.1
*   Operating system / distribution: Ub16.04
*   Kernel version (if applicable):

## Expected behavior
collecd should start without any errors.

## Actual behavior
When collectd service is started, battery plugin fails with below error:
collectd[12129]: read-function of plugin `battery' failed. Will suspend it for 640.000 seconds.
collectd[12129]: battery plugin: All available input methods failed.

## Steps to reproduce

*   Install collectd
*   Start collectd service

By default the battery plugin is enabled in the configuration on Ubuntu. Does this needs to be changed?

**Comment by rubenk** [comment]
Well, do you have a battery?

**Comment by cnnaik** [comment]
No. 
So the default config will have the plugin enabled always ?

**Comment by rubenk** [comment]
In what package? If Ubuntu enables it you should talk to them.

**Comment by cnnaik** [comment]
Observed it for integration of collectd exporter with collectd.

**Comment by rubenk** [comment]
Please be more specific. What package did you install and from where?

**Comment by cnnaik** [comment]
@rubenk'
i have built collectd-exporter from source at - https://github.com/prometheus/collectd_exporter.

And was trying to integrate it with collectd,  as collectd-exporter is exporting metrics from existing collectd setups.

I have installed collected from repo - sudo apt-get install -y collectd

**Comment by rubenk** [comment]
> I have installed collected from repo - sudo apt-get install -y collectd

Which repo?

**Comment by cnnaik** [comment]
I meant the one that is available in Ubuntu distribution.

**Comment by rubenk** [comment]
Ok, can't help you then.

**Comment by mrunge** [comment]
We talked about this on IRC.
