### ISSUE TITLE
[wiki] kcollectd page

### ISSUE THREAD

**Issue by aerusso** [collectd/collectd#3268]
The wiki page for [kcollectd](https://collectd.org/wiki/index.php/Kcollectd) shows the old (and dead for about a decade) upstream. I have recently taken over (forked) the package, and made a few [releases](https://gitlab.com/aerusso/kcollectd/-/tags), most importantly porting it to qt5.

Would it be possible to update the wikipedia to reference my [fork](https://gitlab.com/aerusso/kcollectd)?

**Comment by rpv-tomsk** [comment]
31.08.2019 21:40, Antonio Russo пишет:
>
> The wiki page for kcollectd 
> <https://collectd.org/wiki/index.php/Kcollectd> shows the old (and 
> dead for about a decade) upstream. I have recently taken over (forked) 
> the package, and made a few releases 
> <https://gitlab.com/aerusso/kcollectd/-/tags>, most importantly 
> porting it to qt5.
>
> Would it be possible to update the wikipedia to reference my fork 
> <https://gitlab.com/aerusso/kcollectd>?
>

Hi,

Send me PM with required text and I will do update.

**Comment by aerusso** [comment]
@rpv-tomsk Thanks! Please just update the "See Also" to point to

https://gitlab.com/aerusso/kcollectd

instead of the old site.

**Comment by rpv-tomsk** [comment]
31.08.2019 23:17, Antonio Russo пишет:
>
> @rpv-tomsk <https://github.com/rpv-tomsk> Thanks! Please just update 
> the "See Also" to point to
>
> https://gitlab.com/aerusso/kcollectd
>
> instead of the old site.
>
Updated, please check.

**Comment by aerusso** [comment]
Perfect, thank you!
