### ISSUE TITLE
src/sysevent.c fails to compile with strncpy warning

### ISSUE THREAD

**Issue by srivasta** [collectd/collectd#3272]
*   Version of collectd: 5.9.1 master HEAD
*   Operating system / distribution: Debian testing
*   Kernel version (if applicable):

## Expected behavior

(Description of the behavior / output that you expected)
Compilation succeeds

## Actual behavior
 >  CC       src/sysevent_la-sysevent.lo
> src/sysevent.c: In function ‘read_socket’:
> src/sysevent.c:475:53: warning: argument to ‘sizeof’ in ‘strncpy’ call is the same expression as the source; did you mean to use the size of the destination? [-Wsizeof-pointer-memaccess]
>        strncpy(ring.buffer[ring.head], buffer, sizeof(buffer));
                                                     ^

(Description of the behavior / output that you observed)
 Fails to compile 

## Steps to reproduce

*   step 1 git clone git@github.com:collectd/collectd.git && cd collectd
*   step 2 autoreconf -i -v && ./configure
*   step 3 make

**Comment by rpv-tomsk** [comment]
cc @abays

**Comment by mrunge** [comment]
Sorry, I missed this issue here. This has been fixed by https://github.com/collectd/collectd/pull/3277, follow-up discussion ongoing there.
