### ISSUE TITLE
Unreachable SNMP Host should produce some down metrics in prometheus output

### ISSUE THREAD

**Issue by samsk** [collectd/collectd#3275]
*   Version of collectd: 5.8.1
*   Operating system / distribution: CentOS Linux release 7.6.1810
*   Kernel version (if applicable): 3.10.0-957.el7.x86_64

## Expected behavior
I'm using snmp plugin with prometheus write plugin, to load basic metrics to prometheus.
If some Host monitored using snmp plugin is unreachable, or misconfigured (bad ip, community, protocol), than some sort of indicator metric should appear in prometheus output ie.

```
collectd_snmp_up{instance="unreachable-host-1"} 0 1568378887441
```

## Actual behavior
There is no trace of unreachable host in prometheus output, it looks like the there was no such host configured. There only appears an error in syslog.
Now the status of unreachable, misconfigured or not-configured host, are equivalent.

## Steps to reproduce

*   enable Prometheus plugin
*   enable snmp plugin
*   configure invalid hosts (or simply take config from snmp plugin page)
*   restart collectd
*   do: ```curl http://localhost:9103 | grep _snmp_```
*   no _snmp_ metrics will appear, nothing indicates that some configured snmp hosts are down...

**Comment by rpv-tomsk** [comment]
>some sort of indicator metric should appear in prometheus

No, it should not. None of Collectd plugins generate such metrics and that is not supported by design.

**Comment by mrunge** [comment]
Changing this the way you proposed would also break alerting in Prometheus. You'll get metrics there as long as the host is up, once it's down, you don't. (Obvious). That stale metrics can be used to detect nodes down. If we are starting to send "fake" metrics, all the detection would have to be changed.
The behaviour in collectd is consistent with the ones from prometheus exporters.
