### ISSUE TITLE
HPUX 11.31

### ISSUE THREAD

**Issue by udan08** [collectd/collectd#3281]
*   Version of collectd:5.9
*   Operating system / distribution:hpuc 11.31
*   Kernel version (if applicable):

## Expected behavior

(Description of the behavior / output that you expected)
While Running make  it gives this error 
src/libcollectdclient/libcollectdclient_la-client.lo
gcc: : No such file or directory
gcc: : No such file or directory
gcc: : No such file or directory
gcc: : No such file or directory
gcc: : No such file or directory
gcc: : No such file or directory
*** Error exit code 1
I am using Ansi C 
./configure doesn't give any error.

## Actual behavior

(Description of the behavior / output that you observed)

## Steps to reproduce

*   step 1
*   step 2
*   step 3

**Comment by udan08** [comment]
OS version HPUX 11.31

**Comment by udan08** [comment]
make
        make  all-am
  CC       src/libcollectdclient/libcollectdclient_la-client.lo
gcc: : No such file or directory
gcc: : No such file or directory
gcc: : No such file or directory
gcc: : No such file or directory
gcc: : No such file or directory
gcc: : No such file or directory
*** Error exit code 1

Stop.
*** Error exit code 1

 Don't see libcollectdclient_la-client.lo in   src/libcollectdclient/libcollectdclient_la-client.lo

**Comment by rubenk** [comment]
Sorry, we don't support HPUX
