### ISSUE TITLE
Fixed a typo in error report when java object is not properly constructed

### ISSUE THREAD

**Issue by sanel** [collectd/collectd#3285]
*   Version of collectd: (latest git)
*   Operating system / distribution: (Ubuntu 16.04.4 LTS)
*   Kernel version (if applicable):

## Expected behavior

In java plugin, when object is not created, it will report: `java plugin: cjni_config_load_plugin: Could create a new ... object.`

## Actual behavior

There is a typo in error string. It should be stated: `java plugin: cjni_config_load_plugin: Could not create a new ... object.`

Since change is small, I'm attaching a patch instead of creating full PR.

```patch
diff --git a/src/java.c b/src/java.c
index 41f49092..4da73bbb 100644
--- a/src/java.c
+++ b/src/java.c
@@ -2076,7 +2076,7 @@ static int cjni_config_load_plugin(oconfig_item_t *ci) /* {{{ */
     class->object = NULL;
   if (class->object == NULL) {
     ERROR("java plugin: cjni_config_load_plugin: "
-          "Could create a new `%s' object.",
+          "Could not create a new `%s' object.",
           class->name);
     cjni_thread_detach();
     free(class->name);
```

**Comment by mrunge** [comment]
Thank you for your report. Addressed in https://github.com/collectd/collectd/pull/3286
