### ISSUE TITLE
[Regression] Plugin exec no longer reads from all configured entries

### ISSUE THREAD

**Issue by iain-buclaw-sociomantic** [collectd/collectd#3289]
*   Version of collectd: 5.9.1
*   Operating system / distribution: Linux
*   Kernel version (if applicable):

## Expected behavior

All configured Plugin exec entries to have their values read and sent.

## Actual behavior

Only a small random number of exec entries work.  Downgrading to 5.8 fixes the problem.

## Steps to reproduce
```
LoadPlugin exec

<Plugin exec>
	Exec "user" "/path/to/script" "--instance" "A"
	Exec "user" "/path/to/script" "--instance" "B"
	Exec "user" "/path/to/script" "--instance" "C"
	Exec "user" "/path/to/script" "--instance" "D"
	Exec "user" "/path/to/script" "--instance" "E"
</Plugin>
```

Restarting or Stop/Starting collectd will cause some entries to have metrics collected, others not, but never all to be collected, despite all entries showing up in `ps faux`.

**Comment by mrunge** [comment]
In general, 5.9.1 should not be used.

**Comment by iain-buclaw-sociomantic** [comment]
I haven't tried 5.9.0 yet, I skipped that version, though I can trigger a build and test it.

**Comment by mrunge** [comment]
I was hoping to get to tag 5.9.2 today.

**Comment by iain-buclaw-sociomantic** [comment]
Just tried 5.9.0, and it looks like the same problem, so some sort of bisect between 5.8.1 and 5.9.0 is required.

**Comment by mrunge** [comment]
IMHO we should be clear with https://github.com/collectd/collectd/pull/3290

**Comment by mrunge** [comment]
could you please give 5.9.2 (on the releases page) a try? Ideally that'd get picked up from distributions as well.

**Comment by iain-buclaw-sociomantic** [comment]
Built and running on one server.  I'll leave it till tomorrow to test other configurations.

**Comment by iain-buclaw-sociomantic** [comment]
Nope, still happens, although I've gotten further in finding out what the precise problem is.

Metrics are being collected and sent over the network, however the `COLLECTD_HOSTNAME` is either getting lost, or is not exported properly before forking.  I've found a new metric called `localhost.xxx.yyy` - which is the default hostname used if none is provided to the exec script.

Working version is 5.8.0, I've noticed that 5.8.1 exists, and I can reproduce the problem there as well, so hopefully that means there's very little between the two that could be the problem.

**Comment by iain-buclaw-sociomantic** [comment]
Possibly useful information from configure which might narrow down where to look.
```
checking for setenv... yes
```

**Comment by iain-buclaw-sociomantic** [comment]
0684aea7453186e6f90ce4b6b8c5bcca68f0d1b9 is the first bad commit.

**Comment by iain-buclaw-sociomantic** [comment]
Updated title to match what I think is going on based off the change that caused this.

**Comment by iain-buclaw-sociomantic** [comment]
The problem is the call to `unset_environment()` in the case where `pid > 0`.

I've looked at the comments in the commit, the argument about allocating memory is not convincing to me, so I think just ripping this out and using execve() is what should have been done instead of modifying global state in multiple threads.

**Comment by mkauf** [comment]
This issue has already been reported, please see #3041 . I made a PR for it: #3138

**Comment by iain-buclaw-sociomantic** [comment]
#3138 does not fix the problem regression still exists.

**Comment by pathomiq** [comment]
+ we are seeing the problem with exec plugin ...

**Comment by vaibhavkhanduja** [comment]
Any workaround with this?
