### ISSUE TITLE
Is there a command line limit for ProcessMatch in processes plugin

### ISSUE THREAD

**Issue by craigh1015** [collectd/collectd#3297]
*   Version of collectd: collectd 5.6.3.2.gcb966fc
*   Operating system / distribution: Ubuntu 16.04
*   Kernel version (if applicable): 4.4.0-87-generic

## Expected behavior
ProcessMatch can match any part of the entire command line reported by ps -ef

## Actual behavior
I have a tomcat server where the command line as reported by ps -ef is 7291 characters long 
starting with "/usr/java/default/bin/java ..."
ending with "... org.apache.catalina.startup.Bootstrap start"

When I use:
   Process "java"
The process is matched

When I use
    ProcessMatch "tomcat", "org.apache.catalina.startup.Bootstrap"
The process is not matched

The ProcessMatch config is pushed out by Puppet to over 200 other servers where other tomcat processes are matching

**Comment by rpv-tomsk** [comment]
1) Please, look into `/proc/[pid]/stat` contents for your process. That is the source for all data, gathered by Collectd. Is there is full command line?
2) The  `ps_read_process()` in `processes.c` implementation has limit of 1024 bytes for `/proc/[pid]/stat` contents.
3) PROCSTAT_NAME_LEN defined to 256.

So, only first 256 bytes from process name are checked by Collectd.

**Comment by craigh1015** [comment]
The full command line is stored in /proc/[pid]/cmdline does this also have a limit on length read and used for regex matching?

**Comment by craigh1015** [comment]
It appears behavior is governed by CMDLINE_BUFFER_SIZE which defaults to 4096 if not set.

Is this overidable at runtime?
Or would I need to have my syseng recompile and somehow set this flag?

**Comment by craigh1015** [comment]
This is expected behaviour - I will work around with an alternative in the regex
