### ISSUE TITLE
rrd DataDir has incorrect permission

### ISSUE THREAD

**Issue by surajbora1** [collectd/collectd#3304]
*   Version of collectd: collectd-5.5.3 
*   Operating system / distribution: CentOS 6.10
*   Kernel version (if applicable):

## Expected behavior
rrd Data directory should get created with 755 permissions.
# ls -lrt /var/lib/collectd/
total 0
drwxr-xr-x. 3 root root 26 Oct 13 20:20 rrd

## Actual behavior
rrd Data dir has 750 permission.

[root@XXX collectd]# ls -lrt /var/lib/collectd/
total 4
drwxr-x---. 3 root root 26 Oct 13 17:07 rrd

## Steps to reproduce
1. Installed collectd and rrdtool rpms
2. restart collectd service

**Comment by mrunge** [comment]
Thank you for this report. This is beyond what upstream can provide. 

Please report this bug with your distributor.
