### ISSUE TITLE
Compilation issue. on ubuntu - 12.04. mongodb driver is installed.

### ISSUE THREAD

**Issue by sseshachala** [collectd/collectd#331]
libtool: link: gcc -Wall -Werror -g -O2 -o .libs/collectd-nagios collectd_nagios-collectd-nagios.o  libcollectdclient/.libs/libcollectdclient.so -L/usr/lib -L/lib/x86_64-linux-gnu -lgcrypt -ldl

write_mongodb.c:77:3: error: implicit declaration of function ‘bson_create’ [-Werror=implicit-function-declaration]
write_mongodb.c:77:7: error: assignment makes pointer from integer without a cast [-Werror]
write_mongodb.c: In function ‘wm_write’:
write_mongodb.c:246:3: error: implicit declaration of function ‘bson_dispose’ [-Werror=implicit-function-declaration

Can some one shed some light?

**Comment by octo** [comment]
This latest patch adds compatibility for (at least) *mongo-c-driver* **0.8.1** and **0.7.1**. However, the driver has been completely rewritten it seems, with even more API and ABI changes. This will be a matter for a new feature release, though.
