### ISSUE TITLE
tokyotyrant configury providing wrong -L value

### ISSUE THREAD

**Issue by efuss** [collectd/collectd#3311]
*   Version of collectd: 5.8.0
*   Operating system / distribution: NetBSD
*   Kernel version (if applicable):

## Expected behavior

--with-libtokyotyrant=/usr/pkg working

## Actual behavior

--with-libtokyotyrant=/usr/pkg not working

## Steps to reproduce

configure --with-libtokyotyrant=/usr/pkg

configure.ac reads `with_libtokyotyrant_ldflags="-L$withval/include"` which obviously should read `with_libtokyotyrant_ldflags="-L$withval/lib"`.

**Comment by rubenk** [comment]
Good catch. This again shows that unexercised code is broken code, and that nobody builds with libraries in custom locations. Would you mind sending a PR?

**Comment by efuss** [comment]
In fact, I _did_ use a custom location. I didn't find this through code inspection only.
See #3329. I hope I didn't mix anything up (I'm more familiar with sending patches than Pull Requests).

**Comment by mrunge** [comment]
The corresponding patch has been merged already.
