### ISSUE TITLE
libupsclient detection failure

### ISSUE THREAD

**Issue by efuss** [collectd/collectd#3312]
*   Version of collectd: 5.8.0
*   Operating system / distribution: NetBSD
*   Kernel version (if applicable):

## Expected behaviour

`--with-libupsclient=/usr/pkg` working

## Actual behaviour

`--with-libupsclient=/usr/pkg` not working

## Steps to reproduce

`configure --with-libupsclient=/usr/pkg`

configure.ac, in the libupsclient section, tests `test -x "$withval"`, which succeeds if `$withval` is a (searchable) directory; configure then tries to execute that directory, which fails. This obviously should read `test -f "$withval" && test -x "$withval"`.

**Comment by rubenk** [comment]
I'd welcome a PR to fix this.

**Comment by efuss** [comment]
#3328. I hope I didn't mix anything up (I'm more familiar with sending patches than Pull Requests).

**Comment by dago** [comment]
#3328 has been successfully merged.
