### ISSUE TITLE
$< used in non-suffix rules

### ISSUE THREAD

**Issue by efuss** [collectd/collectd#3313]
*   Version of collectd: 5.8.0
*   Operating system / distribution: NetBSD
*   Kernel version (if applicable):

## Expected behavior

Building grpc working with non-GNU make

## Actual behavior

Building grpc plugin fails with protoc being called with no input files.

## Steps to reproduce

Build grpc plugin with bmake.

Makefile.ac, for the `collectd.grpc.pb.cc` and `collectd.pb.cc` targets, uses `$<` (implied source) in the rule calling protoc, which is only valid for suffix (inference) rules. That should be `$>` (all sources) or spelled out.

**Comment by rubenk** [comment]
If you could send a PR which doesn't break building with Gnu Make I'd be willing to accept it.

**Comment by efuss** [comment]
#3330. I hope I didn't mix anything up (I'm more familiar with sending patches than Pull Requests).
