### ISSUE TITLE
Plugin curl_json: any way to set curl options?

### ISSUE THREAD

**Issue by Mito173** [collectd/collectd#3319]
*   Version of collectd: 5.7.2.git
*   Operating system / distribution: Ubuntu 18.04.3 LTS
*   Kernel version (if applicable): 4.15.0-65-generic

## Question background

Our apartments heating system (AlphaEOS) allows to query its current status by using a web service call which returns JSON. To track temperatures and the heating times over time, I'd like to collect this status information frequently over Collectd using the curl_json plugin.

## Problem

The plugin fails with the following log message:

_collectd[6429]: curl_json plugin: curl_easy_perform failed with status 18: transfer closed with 240 bytes remaining to read (http://alphaeos.mydomain.net/getCurrentDeviceValues.php)
collectd[6429]: read-function of plugin `curl_json-AlphaEOS-http://alphaeos.mydomain.net/getCurrentDeviceValues.php' failed. Will suspend it for 20.000 seconds._

The _status 18 error_ also occurs when I use curl from command line directly - though, the JSON output is complete and usable.

## Solution?

After some Google-investigation I believe that the root cause of this behavior is most likely a non-perfect implementation of the web service on the AlphaEOS controller which I can't change.

According to a [discussion on StackOverflow](https://stackoverflow.com/questions/1759956/curl-error-18-transfer-closed-with-outstanding-read-data-remaining), the only possible fix on my local side is to set curl options as follows:
`curl_setopt($curl, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_0);`

So far so good - I could do this if I had some own PHP code which I execute.
**But how can I solve this in the Collectd context? Is there any way to set curl options for the plugin?**

I'd be happy for every help in this matter
Thanks a lot in advance!

Kind regards,
Michael

**Comment by rpv-tomsk** [comment]
IMHO, you have to solutions:
1) Patch Collectd yourself (maybe, opening PR here)
2) Write required plugin on any supported by Collectd high-level language (Python, Lua, Perl, Java)

**Comment by Mito173** [comment]
@rpv-tomsk : Thanks for the hint - I finally wrote my own (and first) Python Plugin. Was much more easy than I thought. The only tricky thing: my code was only running with Python 3 but CollectD always tried to run it with Python 2.7. Had to compile Collect on my own with LD path pointing to Python 3.6. This worked fine.

By the way: I was not able to compile version 5.9.2 from the tar archive downloaded from collect.org - there seemed to be a file missing. Version 5.8.1 was compiling instantly on the same machine (Ubuntu 18.04.3 LTS).
