### ISSUE TITLE
source tarball collectd-5.9.2.tar.bz2 has wrong file extension

### ISSUE THREAD

**Issue by ncopa** [collectd/collectd#3326]
*   Version of collectd: 5.9.2
*   Operating system / distribution: Alpine Linux
*   Kernel version (if applicable):

## Expected behavior

Source tarball file extension should match the actual content.

## Actual behavior

Source tarball is named `collectd-5.9.2.tar.bz2` but is not a bzip2 archive. it is an XZ archive.

## Steps to reproduce

```console
$ wget https://collectd.org/files/collectd-5.9.2.tar.bz2
Connecting to collectd.org (62.128.13.221:443)
saving to 'collectd-5.9.2.tar.bz2'
collectd-5.9.2.tar.b 100% |********************************| 1535k  0:00:00 ETA
'collectd-5.9.2.tar.bz2' saved
$ file collectd-5.9.2.tar.bz2 
collectd-5.9.2.tar.bz2: XZ compressed data
```

This breaks Alpine Linux build system which will use bzip2 to decompress tar archive when file has `.bz2` as suffix.

**Comment by hnyman** [comment]
Duplicate.  Discussion in #3293, especially starting from https://github.com/collectd/collectd/issues/3293#issuecomment-538666840

Fixes for the next releases (5.10+) forthcoming in #3318 and discussion also in #3223

**Comment by mrunge** [comment]
Yes, sorry you are hit by this issue. I made a mistake in preparing this file (wrong extension) and that got propagated to collectd.org/files/...
Unfortunately, I don't have any ability to replace the file there (it is not bootstrapped either). The file on https://github.com/collectd/collectd/releases/download/collectd-5.9.2/collectd-5.9.2.tar.bz2 is fixed.

I am expecting collectd 5.10.0 very soon.

**Comment by arekm** [comment]
Could http://collectd.org/files/collectd-5.9.2.tar.bz2 also get fixed?

**Comment by mrunge** [comment]
See https://github.com/collectd/collectd/issues/3326#issuecomment-549156086

**Comment by arekm** [comment]
Ah, ok.
