### ISSUE TITLE
More "sys/sysctl.h" errors with Ubuntu 19.10 / Linux 5.3.0-19-generic

### ISSUE THREAD

**Issue by zebity** [collectd/collectd#3338]
*   Version of collectd: 5.9.2 / 5.10
*   Operating system / distribution: Ubuntu 19.10
*   Kernel version (if applicable): 5.3.0-19-generic

## Expected behavior

NOTE: This is build issue so behaviour relates to building of collectd not it execution.

Successful full and complete build of collectd and its plugins.

## Actual behavior

Build failure due to pending deprecation of "sys/sysctl.h"

  CC       src/cpu_la-cpu.lo
In file included from src/cpu.c:64:
/usr/include/x86_64-linux-gnu/sys/sysctl.h:21:2: error: #warning "The <sys/sysctl.h> header is deprecated and will be removed." [-Werror=cpp]
   21 | #warning "The <sys/sysctl.h> header is deprecated and will be removed."
      |  ^~~~~~~
cc1: all warnings being treated as errors

(Description of the behavior / output that you observed)

## Steps to reproduce

*   step 1 - Install Ubuntu 19.10
*   step 2 - Install collectd build tools and plugin library dependencies
*   step 3 - clone repository
*   step 4 - cd collectd, ./build.sh, ./configure, make
*   step 5 - ./build.sh, ./configure, make

NOTE: This issues was reported with src/contextswitch.c in this pull request https://github.com/collectd/collectd/pull/3298 by @rubenk the problem appears to propagate across additional modules:

find . -name "*.c" -exec grep -l 'sys/sysctl.h' {} \; 
./src/cpufreq.c
./src/tcpconns.c
./src/cpu.c
./src/memory.c
./src/swap.c
./src/contextswitch.c
./src/processes.c
./src/uuid.c
./src/uptime.c
./src/zfs_arc.c

Each of which includes the "sys/sysctl.h" file with the pending deprecation warning.

I have not looked beyond identifying potential sources of problem, as expect the fix requires more that just conditional inclusion check, as even if there is conditional inclusion, it might be that there has to be code variation dependent on the collectd build release / linux kernel version target.

Not good news for my first Ubuntu 19.10 test build :-(

**Comment by rubenk** [comment]
Again another instance where this is just a harmless warning but because we build with -Werror by default everyone seems to think this is a real issue.

Just build with --disable-werror or send patches.

**Comment by zebity** [comment]
Hi @rubenk yes, happy to address,  but it is important that raise explicit issue, so can ensure any pull requests have clear area of focus.
BTW when you found issue with src/contextswitch.c what OS were you building on ?
I am going to setup Fedora and FreeBSD build's as I think it is helpful to tackle these and other OS impact issues a bit more wholistically.

Cheers,

Zebity

**Comment by rubenk** [comment]
There already is a PR that reported this: https://github.com/collectd/collectd/pull/3234, so it's a known issue and I'm going to close this one.

I build on Fedora Rawhide.

**Comment by zebity** [comment]
Hi @rubenk I do not understand how you can close this when PR:
https://github.com/collectd/collectd/pull/3234  - was merged "26 Days ago" &
https://github.com/collectd/collectd/pull/3234 - is yet to be marge and address the same instance as https://github.com/collectd/collectd/pull/3234 (src/contextswitch.c)

Thanks for info on Fedora, I did test build with Fedora 31 and is failed at exactly the same place my Ubuntu 19.10 test. (src/cpu.c) .

I have also looked at code for cpu.c and it already has some conditional checks for existence of "sys/sysctl.c" but it gets picked up as found, while for some reason your conditional check results in the opposite (I am not sure exactly why this is but I am sure you can work it out...).

@kraj as you are looking at this and potential ./configure based solution (as per suggestion) could you also look at the "More" part of my issue.

Also to test I did Fedora build check with removal of the offending file (renamed sys/sysctl.h to get it out of the way), which I expect might happen with future glibc, and all built ok. I will do same test with Ubuntu but also test the resulting package run ok on server.

Finally thanks @rubenk for pointing out other PR.

Cheers

**Comment by rubenk** [comment]
I closed this because  I feel having both an issue and an open PR for the same thing is not needed. @kraj reported the same issues in the same plugins, I saw them too. We don't need more people reporting this, we need patches.

Saying "I am not sure exactly why this is but I am sure you can work it out..." is not really helpful. If you really want to help, come up with a proper PR.

**Comment by zebity** [comment]
@rubenk i raised the issue as was in the process of determining how to best address it. Hence why I also was having a look at Fedora build as I did not want to put in a Ubuntu 19.10 fix if it then broke another distribution build.

As per earlier discussion on other thread by @kraj in time the problem will just go away as sys/shysctl.h vanished completely as per similar liblvm2app deprecation case: https://github.com/collectd/collectd/issues/2820

More constructively can you possiblely advise why this (from contextswitch.c), appears to result in sys/sysctl.h not being included when the file is definitely on system and available (which means the test must be resolving to false) and sys/sysctl.h is not being included.

```
#if defined(HAVE_SYSCTLBYNAME) && defined(HAVE_SYS_SYSCTL_H)
#include <sys/sysctl.h>
/* no global variables */
/* #endif HAVE_SYSCTLBYNAME */

#elif KERNEL_LINUX
/* no global variables */
/* #endif KERNEL_LINUX */

#elif HAVE_PERFSTAT
#include <libperfstat.h>
#include <sys/protosw.h>
/* #endif HAVE_PERFSTAT */

#else
#error "No applicable input method."
#endif

```
And yet this from cpu.c, which already has a conditional test in it, must be resolving to true as sys/sysctl.h is being included (and build failing):

```
> #if (defined(HAVE_SYSCTL) && HAVE_SYSCTL) ||                                   \
>     (defined(HAVE_SYSCTLBYNAME) && HAVE_SYSCTLBYNAME)
> #ifdef HAVE_SYS_SYSCTL_H
> #include <sys/sysctl.h>
> #endif
> 
> #ifdef HAVE_SYS_DKSTAT_H
> #include <sys/dkstat.h>
> #endif
> 
> #if !defined(CP_USER) || !defined(CP_NICE) || !defined(CP_SYS) ||              \
>     !defined(CP_INTR) || !defined(CP_IDLE) || !defined(CPUSTATES)
> #define CP_USER 0
> #define CP_NICE 1
> #define CP_SYS 2
> #define CP_INTR 3
> #define CP_IDLE 4
> #define CPUSTATES 5
> #endif
> #endif /* HAVE_SYSCTL || HAVE_SYSCTLBYNAME */
```

This is where I got to in looking at the "More ..." part of my initial raised issue, with aim toward looking for resolution.

@rpv-tomsk could you possibly cast you sharp eyes on this ?

**Comment by rubenk** [comment]
If I had the time to look more into this I would, and I would have fixed it by now. But again, it's not a major issue and we have 336 other issues open.

If you really want to help, get your feet wet, dive into the code and fix it yourself.
