### ISSUE TITLE
processes plugin: I only get syst CPU usage from a process, no user CPU time

### ISSUE THREAD

**Issue by FlorinAndrei** [collectd/collectd#3343]
*   Version of collectd: 5.5.0
*   Operating system / distribution: CentOS 6
*   Kernel version (if applicable): 2.6.32-754.6.3.el6.x86_64

Data gathered by collectd is injected into Graphite and visualized with Grafana.

## Expected behavior

I've enabled the processes plugin and I told it to track httpd and mysqld:

```
LoadPlugin processes
<Plugin "processes">
  ProcessMatch "mysqld" "mysqld"
  ProcessMatch "httpd" "httpd"
</Plugin>
```

Looking at the ps_cputime metric for httpd, I get both syst and user for those processes.

I expected to get the same for mysqld.

## Actual behavior

I only get syst for mysqld.

I've also tried this but it makes no difference (because just "mysqld" could also match the wrapper):

`ProcessMatch "mysqld" "/usr/libexec/mysqld"`

**Comment by dago** [comment]
How is the process shown with `ps`? You cannot just pick something similar, the name must match exactly the name, either directly or via the regular expression.

**Comment by FlorinAndrei** [comment]
I don't have access to that environment anymore, I'm not sure I can continue to make meaningful comments to this issue, sorry.

**Comment by dago** [comment]
Okay, I am closing this for now, feel free to reopen if you have a chance to take a look at the issue again.
