### ISSUE TITLE
Collectd - slack channel

### ISSUE THREAD

**Issue by mkobyli** [collectd/collectd#3354]
What do you think about create slack channel for Collectd? I know that IRC channel exist but afaik it dosen't keep history, so in my opinion we lost a lot of useful knowledge

**Comment by rpv-tomsk** [comment]
There is no really interested persons left in active Collectd development.
Don't waste your time, project lives his last days - watch on latest commits and on bunch of abandoned / unfinished pull requests (you already find one of them).

Infrastructure is already dead. Website has errors (find "[an error occurred while processing this directive]" message which lasts over year). CI repeatedly failing, daily packages are not built for more than two years. Just look on https://pkg.ci.collectd.org/deb/dists/ -  latest Collectd is 5.8 and is not actual.... 

Find more useful mission to spent your time.
I'm saying these words as a person, who already spent much time on Collectd.

**Comment by mkobyli** [comment]
Hi @rpv-tomsk,
Thanks for your opinion. I think about slack channel like a place for future grooming older tasks (I know that one grooming session is planned on the collectd meetup), quick chat for developers eg developers who will be happy to help but don't have that huge knowledge of collectd like you. I think that it will be place where they can ask you or other experienced developers: about older PRs during review, issues, etc.

**Comment by rpv-tomsk** [comment]
I don't find nothing good having "fast" communication channel while having tied hands on project (due to failing CI, missing merge permissions, etc).

**Comment by rubenk** [comment]
Please no. I dislike Slack with a passion and I think it is horrible for Open Source projects. Depending on a single American company for all communication is not a good thing to do.
If you want history, communicate on the mailing list, or setup an irc bot to log irc to somewhere.

I agree with Pavel, we need people fixing issues, not more ways to communicate.

**Comment by sunkuranganath** [comment]
In light of this thread, i have initiated https://github.com/collectd/collectd/issues/3356

**Comment by mrunge** [comment]
Thank you for this proposal. However, I can only second Rubens sentiment and I would not join a slack channel.
