### ISSUE TITLE
Convert documentation to Markdown files

### ISSUE THREAD

**Issue by mkobyli** [collectd/collectd#3355]
I have found this request #3051 and I think that we can convert all documentation to Markdown files and "Read the Docs". I can start convert/refresh our documentation :) but before starting,  I'd be grateful for you feedback about this idea :)

**Comment by mrunge** [comment]
Hi there,

thank you for your kind offer!

We talked about this about a year ago. Back at the time, it was seen as a too high barrier for contributors. If you have some cycles to work on documentation, then please go directly to the wiki.

**Comment by mkobyli** [comment]
Hi @mrunge,
thanks for feedback :)

**Comment by kkepka** [comment]
a followup question - do you think this is not a good idea at all, or just not so urgent like other efforts, but maybe still could provide some value in the future?
By "too high barrier for contributors" you mean switch/convert effort of whats already there (as could spent those cycles e.g. on code reviews)? or also additional steps needed afterwards for providing changes? (simple edit on wiki vs PR to docs on repo)?
