### ISSUE TITLE
virt plugin: Array index out of bounds: tag_index

### ISSUE THREAD

**Issue by jagauthier** [collectd/collectd#3364]
*   Version of collectd: collectd 5.8.1.git
*   Operating system / distribution: Debian 10
*   Kernel version (if applicable): Linux delta 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5+deb10u1 (2019-07-19) x86_64 GNU/Linux

## Expected behavior
Monitoring of virtual machines

## Actual behavior
Error message in log:
```
[2020-01-11 17:01:35] Notification: severity = OKAY, host = Plex, plugin = virt, plugin_instance = Plex, type = domain_state, message = Domain state: the domain is running. Reason: normal startup from boot
[2020-01-11 17:01:35] virt plugin: Array index out of bounds: tag_index = 10
[2020-01-11 17:01:35] virt plugin: virDomainGetFSInfo failed: -1
[2020-01-11 17:01:35] virt: Failed to get file system info
```

## Steps to reproduce
Install debian 10, along with libvirt, and collectd. Added the virt config:

```

<Plugin virt>
        Connection "qemu:///system"
        RefreshInterval 60
        Domain "Plex"
        BlockDevice "name:device"
        BlockDeviceFormat target
        BlockDeviceFormatBasename false
        InterfaceDevice "name:device"
        IgnoreSelected false
        HostnameFormat name
        InterfaceFormat name
        PluginInstanceFormat name
        Instances 1
        ExtraStats "cpu_util disk disk_err domain_state fs_info job_stats_background pcpu perf vcpupin"
</Plugin>
```

Libvirt: 5.0.0

**Comment by rpv-tomsk** [comment]
You should update to Collectd-5.9 to get `virt plugin: Array index out of bounds: tag_index = 10` fixed. 
To fix `virt: Failed to get file system info` message you should remove `fs_info` from `ExtraStats`. Update to 5.9 will also fix this issue as new Collectd became smart to disable unsupported `ExtraStats` options.

However, `virt` plugin code needs to be updated as new Memory Statistics Tags was introduced in libvirt-5.4.0 (released 2019-06-03).

**Comment by jagauthier** [comment]
Thank you!  I did install collectd 5.9 from debian backports and that allows me to monitor them.
