### ISSUE TITLE
examples/mnist/convert_mnist_data.cpp: In function ‘void convert_dataset(const char*, const char*, const char*)’:

### ISSUE THREAD

**Issue by Villjoie** [collectd/collectd#3365]
I have this problem by run make-j 32
someone has a solution please

examples/mnist/convert_mnist_data.cpp: In function ‘void convert_dataset(const char*, const char*, const char*)’:
examples/mnist/convert_mnist_data.cpp:25:6: warning: ‘__builtin___snprintf_chk’ output may be truncated before the last format character [-Wformat-truncation=]
void convert_dataset(const char* image_filename, const char* label_filename,
^~~~~~~~~~~~~~~
In file included from /usr/include/stdio.h:862:0,
from /usr/include/c++/7/cstdio:42,
from /usr/include/c++/7/ext/string_conversions.h:43,
from /usr/include/c++/7/bits/basic_string.h:6361,
from /usr/include/c++/7/string:52,
from /usr/include/c++/7/stdexcept:39,
from /usr/include/c++/7/array:39,
from /usr/include/c++/7/tuple:39,
from /usr/include/c++/7/bits/stl_map.h:63,
from /usr/include/c++/7/map:61,
from /usr/include/google/protobuf/text_format.h:41,
from examples/mnist/convert_mnist_data.cpp:10:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:65:44: note: ‘__builtin___snprintf_chk’ output between 9 and 11 bytes into a destination of size 10
__bos (__s), __fmt, __va_arg_pack ());

**Comment by rpv-tomsk** [comment]
How this relates to Collectd code?

**Comment by Villjoie** [comment]
the solution was this, instead run make-j 32, I executed all of the following and that solved the problem

sudo make clean
sudo make all -j $ (($ (nproc) + 1))
sudo make test -j $ (($ (nproc) + 1))
export CUDA_VISIBLE_DEVICES = 0
sudo make runtest -j $ (($ (nproc) + 1)

**Comment by Villjoie** [comment]
the solution was this, instead run make-j 32, I executed all of the following and that solved the problem

sudo make clean
sudo make all -j $ (($ (nproc) + 1))
sudo make test -j $ (($ (nproc) + 1))
export CUDA_VISIBLE_DEVICES = 0

sudo make runtest -j $ (($ (nproc) + 1)
