### ISSUE TITLE
Collectd installation fails on Operating systems with glibc version >=2.30

### ISSUE THREAD

**Issue by jkanhir** [collectd/collectd#3369]
*   Version of collectd: 5.10
*   Operating system / distribution: Fedora 31
*   Kernel version (if applicable): 5.4.8-200.fc31.x86_64

## Expected behavior
Complete the Installation without any error

## Actual behavior
Installation fails by showing below error.
error: #warning "The <sys/sysctl.h> header is deprecated and will be removed."

## Steps to reproduce

1. Install Fedora 31 in a server
2. git clone https://github.com/collectd/collectd.git
3. cd ~/collectd
4. ./build.sh
5. ./configure
6. make -j && make install  --> Observe that, Installation is not complete and shows the error.

**Comment by rubenk** [comment]
./configure --disable-werror

**Comment by jkanhir** [comment]
Hi Ruben,
This seems to be a workaround and not a fix. In that sense, we cannot say issue is resolved ? Also Please allow the submitter to close the issue.
Thanks, Jabir

**Comment by dago** [comment]
This has already been fixed with #3342

**Comment by jkanhir** [comment]
@dago Thanks for pointing out the Fix ! It works.
