### ISSUE TITLE
utils_taskstats : errors running from LXC

### ISSUE THREAD

**Issue by Farfaday** [collectd/collectd#3370]
*   Version of collectd:   5.9.2.g-1
*   Operating system / distribution:  debian/ubuntu
*   Kernel version (if applicable): 5.3.0-26-generic

## Expected behavior
no errors in the log
## Actual behavior
Currently, running collectd from an LXC container, we get following error 

```
collectd[118]: utils_taskstats: CTRL_CMD_GETFAMILY("TASKSTATS"): No such file or directory
collectd[118]: utils_taskstats: get_family_id() = No such file or directory
collectd[118]: processes plugin: Creating taskstats handle failed.
```

**Comment by rpv-tomsk** [comment]
>no errors in the log

There is no errors, but a warning only. So, expected behaviour is observed and there is no issue.

Further reading: search "taskstats netlink container".
