### ISSUE TITLE
changed apache server signature - collectd upset

### ISSUE THREAD

**Issue by ifelsefi** [collectd/collectd#3374]
Hi

I changed my apache server signature using mod security.  Though now collectd isn't happy.  These messages are polluting syslog.

```
collectd[3125]: apache plugin: Unknown server software: https://youtu.be/UjCdB5p2v0Y

```

Does the plugin not support custom server signatures?

**Comment by mrunge** [comment]
Apparently, it does not. However, it will assume the server to be apache in this case. The message is a warning, in that case you may want to turn warnings off?

**Comment by ifelsefi** [comment]
Thank you @mrunge
