### ISSUE TITLE
[wiki] kcollectd page (another update)

### ISSUE THREAD

**Issue by aerusso** [collectd/collectd#3383]
Hello, I'm the maintainer for kcollectd.  I recently made a new release, and [webpage](https://www.antonioerusso.com/projects/kcollectd), Could you please update the [wiki page for kcollectd](https://collectd.org/wiki/index.php/Kcollectd) to point to that website, instead of the [GitLab](https://gitlab.com/aerusso/kcollectd) page? (I'd also appreciate touching the time-stamp, so people know it's not abandoned).

**Comment by rpv-tomsk** [comment]
Done!

**Comment by aerusso** [comment]
Perfect, thank you!
