### ISSUE TITLE
Release tag missing

### ISSUE THREAD

**Issue by bzed** [collectd/collectd#3400]
@mrunge please push the release tag.

**Comment by mrunge** [comment]
Hi,
what release tag is missing? 5.11 is not released yet...

**Comment by ashie** [comment]
Hmm, `./version-gen.sh` points `5.9.2.550.g62ae49f` while 5.10.0 is [already released](https://collectd.org/wiki/index.php/Version_5.10).

It seems that the tag name for 5.10.0 is wrong:

```
$ git tag

5.10.0
collectd-2.0.1
collectd-3.10.0
...
collectd-5.9.2
svn-trunk
```

(`collectd-5.10.0` is missing, there is `5.10.0` instead)

See also: #3293

**Comment by mrunge** [comment]
> Hmm, `./version-gen.sh` points `5.9.2.550.g62ae49f` while 5.10.0 is [already released](https://collectd.org/wiki/index.php/Version_5.10).
> 

see https://github.com/collectd/collectd/blob/collectd-5.10/version-gen.sh ?


I'll cherry-pick the changes to master as well.

**Comment by mrunge** [comment]
Sorry for the delay here, we'll fix the missing tag later today while we do the release for 5.11.0.

**Comment by mrunge** [comment]
The tag https://github.com/collectd/collectd/tree/collectd-5.10.0 has been pushed, along with collectd-5.11.0.
