### ISSUE TITLE
Failure to put hostname in double quotes causes cryptic failure

### ISSUE THREAD

**Issue by pneumaticdeath** [collectd/collectd#3404]
*   Version of collectd: 5.8.1
*   Operating system / distribution: CentOS 7
*   Kernel version (if applicable):

## Expected behavior

Errors in the config file are properly called out in logging during startup

## Actual behavior

Some syntax errors causes silent config parsing failure.

## Steps to reproduce

1) Create config file entry that reads 
`Hostname foo`
2) restart collectd 
3) will fail with "Error parsing config file" type error, but it won't specify where the error is.

**Comment by jkanhir** [comment]
@pneumaticdeath Have you tried to get more details on the logs by enabling the logfile plugin ? will that solve this issue ?
```bash
LoadPlugin logfile
<Plugin logfile>
        LogLevel info
        File "/var/log/collectd.log"
        Timestamp true
        PrintSeverity false
</Plugin>
```

**Comment by pneumaticdeath** [comment]
Yes I tried that and got no errors.

**Comment by jkanhir** [comment]
@pneumaticdeath As of now, The community supports only one version down to the current version of collectd as mentioned in the release process document here. https://docs.google.com/document/d/1Ha9zPyKa_1pBar58LUPRf4EV2ap1sMcrOtRz3qauogo/edit
So, Is it possible to upgrade your collectd version and see this issue still reproducible ?
Also, please use 'Labels' to label this issue accordingly.

**Comment by rpv-tomsk** [comment]
Running config with hostname without double quotes shows me the following output:

```
# ./run_client_fg
option = PIDFile; value = /var/run/collectd-client.pid;
configfile: Global option `Hostname' needs exactly one argument.
option = FQDNLookup; value = false;
option = Interval; value = 10.000000;
Created new plugin context.
[2020-03-17 11:32:54] plugin_load: plugin "logfile" successfully loaded.
[2020-03-17 11:32:54] plugin = logfile, key = LogLevel, value = debug
[2020-03-17 11:32:54] plugin = logfile, key = File, value = STDOUT
-...[2020-03-17 11:32:54] plugin_load: plugin "syslog" successfully loaded.
[2020-03-17 11:32:54] plugin = syslog, key = LogLevel, value = info
[2020-03-17 11:32:54] plugin_load: plugin "network" successfully loaded.
[2020-03-17 11:32:54] Done parsing `/opt/collectd/share/collectd/types.db'
Error: Parsing the config file failed!
```

So, error message is "configfile: Global option `Hostname' needs exactly one argument."
Plugins like `syslog` or `logfile` are not loaded yet in that moment, and error reporing goes to stderr (see `plugin_log()` implementation).

>Expected behavior: Errors in the config file are properly called out in logging during startup

So, I don't see any problems with error reporting. 
Anybody can/should start Collectd in foreground if it experiencing similar problem (when parsing failed before logging plugin loaded).

Syntax of config file is also documented well:

>         .... Values can either be
>        an unquoted string, a quoted string (enclosed in double-quotes) a
>        number or a boolean expression. Unquoted strings consist of only
>        alphanumeric characters and underscores ("_") and do not need to be
>        quoted. Quoted strings are enclosed in double quotes (""").

If your hostname has only alphanumeric characters and underscores (so, has no dots and other symbols) - config parse succeeds.
