### ISSUE TITLE
missing critical fixes from 5.9 in master

### ISSUE THREAD

**Issue by faxm0dem** [collectd/collectd#3434]
It seems at least one fix for 5.9 hasn't been merged to master:

https://github.com/collectd/collectd/pull/3351

Has 5.9 been merged at all?

**Comment by faxm0dem** [comment]
also not in 5.10 and 5.11

**Comment by rpv-tomsk** [comment]
Nobody cares. New maintainers don't know these rules, old maintainers now has no permissions to do that yourself like it was done before.

**Comment by rpv-tomsk** [comment]
Yes, nobody cares also to close issue when it's solved.

People prefer to scratch their tongue.

**Comment by mrunge** [comment]
This has been solved.
