### ISSUE TITLE
[wiki] Plugin:SNMP Config update

### ISSUE THREAD

**Issue by vitkabele** [collectd/collectd#3437]
Hi,
I recently created a file with data definitions for SNMP Plugin [here](https://www.github.com/vitkabele/dsm-snmp-collectd) , to monitor the Synology NAS storages. It was not something really complex, but It can save a little time to someone.

Would You mind to add a link to the repository to the [Plugin:SNMP Config](https://collectd.org/wiki/index.php/Plugin:SNMP/Config) wiki page?

Sorry for posting the wiki update request here, but I don't consider this so important to post to the mailing list.

Best regards, 
VK

**Comment by jkanhir** [comment]
@vitkabele I have added the link in 'See also' section. is that good enough ?

**Comment by mrunge** [comment]
Thank you @vitkabele and also thank you @jkanhir for solving this.

@vitkabele if this is not solved for you, please re-open this issue.
