### ISSUE TITLE
Unable to import Python modules

### ISSUE THREAD

**Issue by adl1995** [collectd/collectd#3453]
*   Version of collectd: 5.10.0.git
*   Operating system / distribution: Arch Linux

I'm writing a Collectd plugin that calls an external API. For this I wish to use the `requests` Python library. In my `collectd.conf file` I added:

```
LoadPlugin python
<Plugin python>
ModulePath "/usr/lib/collectd/"
Import "module_name"
<Module module_name>
...
</Module>
</Plugin>
```
In my Python file I imported the modules:

```
import collectd
import requests
```

But I am faced with this error when I start Collectd:

```
Apr 23 17:51:30 home collectd[100272]: python plugin: Error importing module "module_name".
Apr 23 17:51:30 home collectd[100272]: Unhandled python exception in importing module: ImportError: dynamic module does not define module export function (PyInit_email)
```

This is what I get from my `sys.version` and `sys.path`:

```
3.8.1 (default, Jan 22 2020, 06:38:00) [GCC 9.2.0]
['/usr/lib/collectd/', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/usr/lib/python3.8/site-packages']
```

Is this a compatibility issue with the Python version? It seems that `PyInit_*` errors occur when importing Python 2 modules in Python 3.

**Comment by mrunge** [comment]
where did you place your python plugin? Is that located in "/usr/lib/collectd/" ?

**Comment by adl1995** [comment]
Yes, it was located in `/usr/lib/collectd/`. I just moved the script to `/usr/lib/collectd/python/` and now the import is working.

Out of curiosity, do you know why I couldn't import external packages from `/usr/lib/collectd/`?
(Please feel free to close this issue.)

**Comment by mrunge** [comment]
The python plugin is a bit picky about file names. There is another python plugin issue open about using/re-using names/symbols of other external libraries; at the end they will clash. At a quick search, I couldn't find the issue here again.
