### ISSUE TITLE
No libperl on RH8 with collectd-5.11

### ISSUE THREAD

**Issue by ralphM78** [collectd/collectd#3462]
Hello,

I have tried to compile collectd-5.11.0 on RH8 but configure doesn't detect libperl.
perl-libs, ExtUtils-Embed and ExtUtils-MakeMaker are installed. I have tried it with gcc8 and gcc9.

config.log :

`configure:103861: checking for perl`
`configure:103879: found /usr/bin/perl`
`configure:103891: result: /usr/bin/perl`
`configure:103912: checking for libperl`
`configure:103942: gcc -o conftest -g -O2  -I/usr/lib64/perl5/CORE    conftest.c  -Wl,--enable-new-dtags -Wl,-z,relro -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -Wl,-z,relro -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -fstack-protector-strong -L/usr/local/lib  -L/usr/lib64/perl5/CORE -lperl -lpthread -lresolv -ldl -lm -lcrypt -lutil -lc >&5`
`/opt/rh/gcc-toolset-9/root/usr/bin/ld: /tmp/ccHSKa1o.o: relocation R_X86_64_32 against .rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC`
`/opt/rh/gcc-toolset-9/root/usr/bin/ld: final link failed: nonrepresentable section on output`
`collect2: error: ld returned 1 exit status`
`configure:103942: $? = 1`

Any suggestions to solve the problem ?

Ralph

**Comment by ralphM78** [comment]
Looks like

` CFLAGS="-fPIC"  ./configure`

does the trick.

Ralph

**Comment by mrunge** [comment]
Glad you found a solution on your own. For reference, my spec file for building collectd on CentOS8/RHEL8 looks like this: https://github.com/centos-opstools/collectd/blob/master/collectd.spec
