### ISSUE TITLE
ModuleNotFoundError: No module named 'Queue'

### ISSUE THREAD

**Issue by tenox7** [collectd/collectd#3465]
*   Version of collectd: collectd 5.11.0.git
*   Operating system / distribution: debian/sid
*   Kernel version (if applicable):

## Expected behavior

(Description of the behavior / output that you expected)
collectd python module to work, no error

## Actual behavior

(Description of the behavior / output that you observed)
```
Traceback (most recent call last):
  File "/var/lib/collectd/plugins/myplugin.py", line 18, in <module>
    import collectd
  File "/usr/local/lib/python3.8/dist-packages/collectd.py", line 8, in <module>
    from Queue import Queue, Empty
ModuleNotFoundError: No module named 'Queue'
```

## Steps to reproduce

*   step 1
write a python plugin that imports collectd python package
*   step 2
pip3 install collectd
*   step 3
run the plugin

According to Stackoverflow in Python3 Queue is renamed to queue lowercase hence the issue.
https://stackoverflow.com/questions/33432426/importerror-no-module-named-queue

**Comment by mrunge** [comment]
Is this a bug report for https://pypi.org/project/collectd/ ? That is hosted here: https://github.com/appliedsec/collectd and is apparently dead?
