### ISSUE TITLE
src/libcollectdclient/client.c compile warning

### ISSUE THREAD

**Issue by ymettier** [collectd/collectd#347]
Hello,

While compiling (on Solaris 11 with sunstudio but this does not matter), I have this warning :

`
libtool: compile:  cc -DHAVE_CONFIG_H -I. -I../../src -I../../src/libcollectdclient/collectd -I../../src -m64 -g -c client.c  -KPIC -DPIC -o .libs/libcollectdclient_la-client.o
"client.c", line 1105: warning: argument #4 is incompatible with prototype:
        prototype: pointer to function(pointer to const void, pointer to const void) returning int : "/usr/include/iso/stdlib_iso.h", line 126
        argument : pointer to void
`
Check file `src/libcollectdclient/client.c` :
* A short fix is to cast as `(int)` instead of `(void *)` line 1105 for arg 4 of `qsort()` (pointer on `lcc_identifier_compare()`).
* A better fix would be to change the prototype of `lcc_identifier_compare()` in order to fit with qsort.

Regards,
Yves

**Comment by rubenk** [comment]
Should be fixed by e906ccd
