### ISSUE TITLE
configure links to system netsnmp on MacOS, ignoring --with-libnetsnmp 

### ISSUE THREAD

**Issue by minfrin** [collectd/collectd#3472]
*   Version of collectd: master
*   Operating system / distribution: MacOS Mojave
*   Kernel version (if applicable):

## Expected behavior

After building collectd as follows:

CFLAGS="-g -O0" ./configure --prefix=/tmp/collectd --without-java --with-librrd=/opt/local --enable-rrdtool --with-libssl=/tmp/collectd --with-libnetsnmp=/tmp/collectd

It is expected that snmp.so is linked to /tmp/collectd/lib/libnetsnmp.35.dylib

## Actual behavior

snmp.so is linked to /usr/lib/libnetsnmp.25.dylib instead:

Little-Net:collectd minfrin$ otool -L /tmp/collectd/lib/collectd/snmp.so 
/tmp/collectd/lib/collectd/snmp.so:
	/usr/lib/libnetsnmp.25.dylib (compatibility version 26.0.0, current version 26.2.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)

snmp plugin fails with an out of memory error, as the version 36 header files are used against the 25 library.
## Steps to reproduce

*   Build using ./configure as above.
*   Check library link with otool -L

**Comment by craiggowing** [comment]
I came across this same problem, issue appears to be that the wrong flag is set in the LD flags in the configure script

https://github.com/collectd/collectd/blob/1da3305c10c8ff9a63081284cf3d4bb0f6daffd8/configure.ac#L3938-L3940

`with_libnetsnmp_ldflags` should use the `-L` flag, not `-I`
