### ISSUE TITLE
RFC: Repo location for 'Python' based plugins

### ISSUE THREAD

**Issue by sunkuranganath** [collectd/collectd#3473]
During recent bi-weekly community call, there was a discussion about hosting Python plugins in a separate repo [1] similar to what we have for Go based plugins today [2].

Could we create a repo for Python based plugins so we can host Python based plugins?
We see good interest for Python based plugins and creating this repo would help interested folks to contribute their Python plugins.

Comments, feedback?

[1] https://collectd.org/wiki/index.php/Minutes_from_2020-05-15 
[2] https://github.com/collectd/go-plugins

**Comment by NikolayTsvetkov** [comment]
Hi there,

Yes, it has been discussed in the context of the newly created Go repo that there could be similar one for the Python plugins. 
I think the idea was well accepted and we can go forward with it.
I can take care to create the repo as proposed during the call.
Please let me know if you have any further comments or ideas !

Cheers!

**Comment by NikolayTsvetkov** [comment]
In fact I don't have rights doing it. @octo do you think we can go forward with this repo ?

**Comment by octo** [comment]
Done: https://github.com/collectd/python-plugins

**Comment by octo** [comment]
I just read in the meeting minutes that you discussed using the MIT license. I have initialized the repository with the ISC license, which is functionally equivalent – it just simplifies the language by removing no longer needed legalese. If that doesn't work for you, feel free to replace it with the MIT license while the repository is still empty.

**Comment by sunkuranganath** [comment]
Thanks @octo for creating this.

Understand ISC is simplified version of MIT, but came to know not many know of ISC and raises more questions than what we intend for. Would it help for any one else to move it to MIT?

**Comment by NikolayTsvetkov** [comment]
Sorry for the late reply but I needed some time to clarify on our side. 
I think we might not be able to reach common licence agreement on all the plugins in the repo and each plugin should be licences separately. 
In general there should not be constraints for other people/companies/organisations contributing afterwards. I know the ISC is light and permissive but different people might have different requirements. In our case it for example it seems the one that should be used in fact is GPLv3.
Do you think it could be organised that way or prefer having the licence set on the repo ?

**Comment by sunkuranganath** [comment]
This is interesting proposition. Agree with the point about making it easy for others contributing to the repo.
However, need to figure out the implications of each plugin having a different license under the repo while Collectd daemon is of MIT.
Or even the fact that python plugin repo being GPLv3 while Collectd daemon & other plugins being MIT! 
Any license experts like to provide feedback?

**Comment by NikolayTsvetkov** [comment]
Collectd is under both MIT and GPL licences, as some of the plugins are under GPL.
Agree that we need somebody with more licensing experience to clarify the options.

**Comment by octo** [comment]
My intention was that plugins can either adopt the repository-wide default license, or ship their own LICENSE file. I put the following into the README:

> collectd <strike>Go</strike> Python plugins are licensed under the ISC License, **unless otherwise stated.**

(There is a typo in the current version so that it sill talks about Go plugins.)

According to the FSF, [the MIT license and GPL are compatible](https://www.gnu.org/licenses/license-list.en.html#X11License), so I'm not too worried about that interaction causing issues.

**Comment by sunkuranganath** [comment]
Ok, while the default is ISC, its up to the user to indicate the license they want (MIT or GPL) for a specific python plugin. So, nothing to do here then?

**Comment by NikolayTsvetkov** [comment]
@octo thanks for the clarification ! That's very good, so it would work for everyone :)
Cheers !
