### ISSUE TITLE
Compilation fails on Solaris 11: struct ip6_ext undefined

### ISSUE THREAD

**Issue by ymettier** [collectd/collectd#348]
Hello,

On Solaris 11, with Sunstudio as the compiler, I have some compilation problems.
Source file : `src/utils_dns.s`

```
libtool: compile:  cc -DHAVE_CONFIG_H -I. "-DPREFIX=\"/opt/collectd\"" "-DCONFIGFILE=\"/opt/collectd/etc/collectd.conf\"" "-DLOCALSTATEDIR=\"/opt/collectd/var\"" "-DPKGLOCALSTATEDIR=\"/opt/collectd/var/lib/collectd\"" "-DPIDFILE=\"/opt/collectd/var/run/collectd.pid\"" "-DPLUGINDIR=\"/opt/collectd/lib/collectd\"" "-DPKGDATADIR=\"/opt/collectd/share/collectd\"" -m64 -g -c utils_dns.c  -KPIC -DPIC -o .libs/utils_dns.o
"utils_dns.c", line 478: incomplete struct/union/enum ip6_ext: ext_hdr
"utils_dns.c", line 490: undefined struct/union member: ip6e_nxt
"utils_dns.c", line 491: undefined struct/union member: ip6e_len
"utils_dns.c", line 544: warning: pointer to void or function used in arithmetic
"utils_dns.c", line 845: warning: statement not reached
"utils_dns.c", line 916: warning: statement not reached
cc: acomp failed for utils_dns.c
*** Error code 1
```

For the lines 478, 490 and 491, I noticed in `/usr/include/netinet/ip_compat.h` that `ip6_ext` will compile if the macro `SOLARIS2` is defined (and on Solaris 11, should be defined to 11).

If I compile with `-DSOLARIS2=11`, here is what I get :
```
"utils_dns.c", line 544: warning: pointer to void or function used in arithmetic
"utils_dns.c", line 845: warning: statement not reached
"utils_dns.c", line 916: warning: statement not reached
```
Yeah, fixed ! Those are warnings only.

However, line 544, I suggest to replace
```
    memcpy(buf, (void *) ip + offset, len - offset);
```
with
```
    memcpy(buf, (void *) (ip + offset), len - offset);
```

Because the never reached statements lines 845 and 916 are documented in the code, I do not think it is useful to fix anything for those warnings.

Now, back to `-DSOLARIS2=11`, does anybody knows where/who should define it ?
My goo^Hsearch engine shows that other ask the same question but nobody answers.

Should we add a check in `configure.in` for `struct ip6_ext` ? And define if necessary the macro `SOLARIS2` ?

Regards,
Yves

**Comment by dago** [comment]
The necessary definitions of `ip6_ext` are not available on Solaris 10:
http://openvswitch.org/pipermail/discuss/2014-April/013800.html
The definition may never make it into Solaris 10, so a workaround is needed.
