### ISSUE TITLE
segfault perl plugin

### ISSUE THREAD

**Issue by ajayraghuraj** [collectd/collectd#3484]
*   Version of collectd:4.9.1-1
*   Operating system / distribution:CentOS5.8
*   Kernel version (if applicable):2.6

## Expected behavior

no segfault

## Actual behavior

collectd[19596]: perl: Initializing Perl interpreter...
collectd[19597]: Initialization complete, entering read-loop.
collectd[19597]: Exiting normally.
collectd[19597]: collectd: Stopping 5 read threads.
kernel: collectd[19597]: segfault at 0000000000000000 rip 00000032a2a79ba0 rsp 00007fff86ea9438 error 4

## Steps to reproduce

Enable perl module , /etc/init.d/collectd stop produces the segfault

[root@host collectd]# /etc/init.d/collectd start
Starting collectd:                                         [  OK  ]
[root@host collectd]# /etc/init.d/collectd stop
Stopping collectd:                                         [  OK  ]

here is my **/etc/collectd.conf**

```
FQDNLookup   false
Interval     10
LoadPlugin syslog
LoadPlugin cpu
LoadPlugin interface
LoadPlugin load
LoadPlugin memory
LoadPlugin network
LoadPlugin perl
<Plugin network>
        Server "x.x.x.x" "25826"
</Plugin>
<Plugin perl>
        IncludeDir "/usr/lib/perl5/site_perl/5.8.8"
        BaseName "Collectd::Plugins"
        LoadPlugin OpenVZ
</Plugin>
```

**Comment by sunkuranganath** [comment]
@ajayraghuraj This version of Collectd is not supported anymore by the community. Could you try updating to latest Collectd version?

**Comment by ajayraghuraj** [comment]
I could get only as far as version 5.1.0. I still see the same errors with the perl plugin.  Beyond 5.1.0, make terminates with Python related errors as it expects version 2.6

Appreciate if someone could help me with resolving the 'segfault' issue. Thanks

**Comment by mrunge** [comment]
CentOS 5 is also not supported anymore. Please consider upgrading.
