### ISSUE TITLE
write_prometheus binds to all network interfaces

### ISSUE THREAD

**Issue by jmooo** [collectd/collectd#3513]
The plugin looks like it lets you specify a port, but doesn't appear to let you bind to a specific address such as the private network only? Specifically we'd like to stop it from binding to any IPs that may be public addresses so we don't also have to manage it at the firewall level

```
<Plugin "write_prometheus">
  Port "9103"
</Plugin>
```
```
Netid   State    Recv-Q   Send-Q      Local Address:Port     Peer Address:Port  Process                                                                         
tcp     LISTEN   0        16                      *:9103                *:*      users:(("ld-2.23.so",pid=3231420,fd=3))  
```

**Comment by randombk** [comment]
I was curious what it would take to add this in, and it looks like there's an [undocumented config "Host" that may work](https://github.com/collectd/collectd/blob/1da3305c10c8ff9a63081284cf3d4bb0f6daffd8/src/write_prometheus.c#L872). It looks like it should pass the option through to the underlying call to `bind(2)`.

I'm not currently in a position to test this, but it's worth a try.

**Comment by mrunge** [comment]
Actually, the option is not *that* undocumented, see https://github.com/collectd/collectd/blob/main/src/collectd.conf.pod#plugin-write_prometheus

**Comment by randombk** [comment]
Nice! I missed the github wiki. I was originally going by this site: https://collectd.org/wiki/index.php/Plugin:Write_Prometheus
