### ISSUE TITLE
Missing important fixes from 5.11 in main and 5.12

### ISSUE THREAD

**Issue by kwiatrox** [collectd/collectd#3542]
It seems that some fixes originating from 5.10 and later merged to 5.11 are still missing in main and are therefore not present in 5.12 branch.
#3413
#3449
#3459
Additionally #2470 was merged to master instead of main and is also missing in 5.12 branch.

**Comment by kwiatrox** [comment]
@sunkuranganath I think that merge would be better than cherry-pick to not change commit ids. We need it in 5.12 branch, but putting it also in main is a good idea imho.

**Comment by octo** [comment]
I merged #2470 into *main* with 70296d5aac75111ebc7a334fa88eae4701a5343c

The other PRs you mentioned have already made their way into *collectd-5.12* via *collectd-5.11*.
