### ISSUE TITLE
Netapp plugin: Reconnection behavior broken.

### ISSUE THREAD

**Issue by llaurent** [collectd/collectd#356]
Hi
I'm using collectd 5.3.0 with the netapp plugin to collect from 3 netapp filers.
Every 2 or 3 days I discover it's stopped collecting for 1 or 2 filers.

It looks like it's not trying to reconnect to filers after a connect error.
Logs tell Jun 19 08:21:58 log-01 collectd[10975]: netapp plugin: cna_handle_volume_snap_us
age: na_server_invoke_elem for volume "amqp_01" on host wazoo.nas failed with error 5: Can't connect to host (err=5).

**Comment by octo** [comment]
Sorry we couldn't figure this one out. Please open another issue if this is still a problem with current versions of *collectd*.
