### ISSUE TITLE
Missing statistic for dropped packets of a VF

### ISSUE THREAD

**Issue by gpanouts** [collectd/collectd#3568]
*   Version of collectd:  5.12.0
*   Operating system / distribution: Ubuntu 18.04.2 LTS
*   Kernel version (if applicable): 5.4.0-45-generic
*  2 x XXV710 25GbE network interfaces
*  Driver i40e version: 2.12.6

## Expected behavior

Hi all,
I’m using plugin netlink in order to retrieve statistics for VFs under specified PFs. There are 2 PFs and I have
configured one VF per PF. The 2 VFs are used from a VM sending and receiving traffic. The statistic that I’m more
interested in is the dropped packets.

When I retrieve statistics using ethtool I get:
```
$ethtool -S  <enpX-PF1> | grep vf000
     vf000.rx_bytes: 933001945820
     vf000.rx_unicast: 14578155350
     vf000.rx_multicast: 0
     vf000.rx_broadcast: 13
     vf000.rx_discards: 144076
     vf000.rx_unknown_protocol: 0
     vf000.tx_bytes: 874634580760
     vf000.tx_unicast: 14577242919
     vf000.tx_multicast: 0
     vf000.tx_broadcast: 0
     vf000.tx_discards: 0
     vf000.tx_errors: 0
```
The statistic vf000.rx_discards was increasing and I believe this is an indicator for dropped packets.
(Note that to get these statistics with ethtool I had to use driver i40e version: 2.12.6)

When I use collectd’s plugin netlink to retrieve the statistics I would expect a statistic for VF dropped packets as defined here
https://github.com/collectd/collectd/blob/collectd-5.12.0/src/netlink.c#L110.

## Actual behavior

However, when I use collectd’s plugin netlink to retrieve VF statistics I get:
```
localdomain/netlink-<enpX-PF1>_vf0_<MAC-addr>/vf_broadcast
localdomain/netlink-<enpX-PF1>_vf0_<MAC-addr>/vf_bytes
localdomain/netlink-<enpX-PF1>_vf0_<MAC-addr>/vf_link_info-link_state
localdomain/netlink-<enpX-PF1>_vf0_<MAC-addr>/vf_link_info-max_tx_rate
localdomain/netlink-<enpX-PF1>_vf0_<MAC-addr>/vf_link_info-min_tx_rate
localdomain/netlink-<enpX-PF1>_vf0_<MAC-addr>/vf_link_info-number
localdomain/netlink-<enpX-PF1>_vf0_<MAC-addr>/vf_link_info-qos
localdomain/netlink-<enpX-PF1>_vf0_<MAC-addr>/vf_link_info-rss_query_en
localdomain/netlink-<enpX-PF1>_vf0_<MAC-addr>/vf_link_info-spoofcheck
localdomain/netlink-<enpX-PF1>_vf0_<MAC-addr>/vf_link_info-trust
localdomain/netlink-<enpX-PF1>_vf0_<MAC-addr>/vf_link_info-tx_rate
localdomain/netlink-<enpX-PF1>_vf0_<MAC-addr>/vf_link_info-vlan
localdomain/netlink-<enpX-PF1>_vf0_<MAC-addr>/vf_multicast
localdomain/netlink-<enpX-PF1>_vf0_<MAC-addr>/vf_packets
```

There is no statistic for dropped packets.

## Steps to reproduce

*   Use driver i40e version: 2.12.6
*   Create VFs with SRIOV and use them in a VM
*   Install collectd 5.12.0
*   Use the following configuration:
```
LoadPlugin logfile
<Plugin logfile>
        LogLevel info
        File STDOUT
        Timestamp true
        PrintSeverity false
</Plugin>
LoadPlugin cpu
LoadPlugin interface
LoadPlugin load
LoadPlugin netlink
LoadPlugin network
LoadPlugin turbostat
LoadPlugin unixsock
LoadPlugin virt
<Plugin netlink>
        Interface "All"
        VerboseInterface "All"
        CollectVFStats true
</Plugin>
<Plugin network>
        Server "ff18::efc0:4a42" "25826"
        <Server "239.192.74.66" "25826">
        </Server>
</Plugin>
<Plugin unixsock>
        SocketFile "/opt/collectd/var/run/collectd-unixsock"
        SocketGroup "collectd"
        SocketPerms "0770"
        DeleteSocket true
</Plugin>
<Plugin virt>
</Plugin>
```
*  Observe the statistics:
```
echo "LISTVAL" | sudo socat - UNIX-CLIENT:/opt/collectd/var/run/collectd-unixsock | grep netlink
```

Should I make any other action to retrieve VF dropped packets from netlink or any other plugin?

@kwiatrox I would really appreciate your feedback since you added this feature for VFs stats.

Thank you,
Georgia

**Comment by kwiatrox** [comment]
Your versions of driver and ethtool support rx_dropped. But the netlink plugin is using netlink protocol. The netlink protocol on Ubuntu does not support dropped packets. It was added to mainline kernel some time ago: [commit](https://github.com/torvalds/linux/commit/c5a9f6f0ab4054082dd5ce9bbdaa8e8ff05cf365), but the Ubuntu flavor for some reason still does not support it.
I'm not sure if there is any other solution than manually updating the kernel.

**Comment by gpanouts** [comment]
@kwiatrox thanks for the clarification!
