### ISSUE TITLE
Be able to prepend a Graphite prefix for any single SNMP Node

### ISSUE THREAD

**Issue by diskfix** [collectd/collectd#367]
The snmp plugin actually puts a host name that way (using the default "collectd." write_graphite plugin prefix):
collectd.[hostname].snmp

Having a "graphite_prefix" or similar option to prepend to the hostname on the on the SNMP Node definition would be neat because it would allow to nest and organize the queried nodes.

collectd.router.site1.[hostname].snmp
collectd.switch.[hostname].snmp
collectd.appliance.[hostname].snmp

**Comment by shib4u** [comment]
@zaibach Can you please post an example Replace Targets config
