### ISSUE TITLE
Receiving notification of missing items but they are present (gauge item over the network)

### ISSUE THREAD

**Issue by zbal** [collectd/collectd#370]
I have items that are received over the network, the item type is Gauge, and the value never really fluctuate when successful (Haproxy status - 2).

Whenever I make the status change (by disabling one of the backend), I receive shortly after a notification of Warning, then Failure (this is expected.) When I put the backend node up again, the Okay notification is triggered and I receive the according message. 

However, whenever the data is good (value = 2), I keep on receiving notification about missing item (for interval * timeout time). I tried to increase the timeout, it just reduce the frequency of the notifications...

What could cause this behavior ?
- item sent over the network? (delay in the reception?)
- gauge item that receive over and over (every 10s) the same data (=2)? (being then considered as not updating?)
- side effect of the identifier name ? (server/haproxy-app-pool/haproxy_status-node1_80 -- server named "server", plugin haproxy, instance app-pool, type haproxy_status, instance node1_80)

I'm kinda struggling here and can't find any guidance online.

**Comment by rubenk** [comment]
Hi @zbal, can you please check if you can still reproduce this?
