### ISSUE TITLE
Plugin Processes webpage has syntax error

### ISSUE THREAD

**Issue by matthewvon** [collectd/collectd#3767]
*   Version of collectd:
October 13, 2020:
     https://collectd.org/documentation/manpages/collectd.conf.5.shtml#plugin_processes

*   Operating system / distribution:
NA
*   Kernel version (if applicable):
NA
## Expected behavior

Webpage closes the ProcessMatch block with /Process.  The proper close is /ProcessMatch

## Actual behavior

collectd rejects the /Process block close

## Steps to reproduce

click on web link above
read

**Comment by mrunge** [comment]
Thank you for the report.

The code or config file itself is fixed already, see https://github.com/collectd/collectd/blob/main/src/collectd.conf.pod#plugin-processes but this has not been propagated to the linked man page.

Unfortunately, it may take some time to fix the web page.
