### ISSUE TITLE
documentation not reflecting latest release on collectd.org website

### ISSUE THREAD

**Issue by fhriley** [collectd/collectd#377]
The latest changes to the write_graphite plugin are documented in the collectd.conf man page, but they are not in the 5.3. branch. Here is the man page:

http://collectd.org/documentation/manpages/collectd.conf.5.shtml#plugin_write_graphite

Note the inclusion of "Protocol" and "LogSendErrors".

Here is the master branch, which contains the options:

https://github.com/collectd/collectd/blob/master/src/write_graphite.c

And the 5.3 branch, with the changes missing:

https://github.com/collectd/collectd/blob/collectd-5.3/src/write_graphite.c

Either the documentation needs to be fixed, or the changes included in the 5.3 branch.

**Comment by octo** [comment]
I've updated the manpages on the homepage to the latest release, 5.5.2.
