### ISSUE TITLE
Read NVMe values running collectd as non-privileged user

### ISSUE THREAD

**Issue by mcharriere** [collectd/collectd#3788]
*   Version of collectd: 5.12.0
*   Operating system / distribution: Gentoo

## Expected behavior
Run collectd as non-privileged user and be able to read NVMe smart data. https://github.com/collectd/collectd/pull/3510

## Actual behavior
It seems that the Smart plugin can only read NVMe smart data with collectd running as root. 
With a non-privileged user and the capabilities properly set I still get this error:

```
[2020-12-07 15:21:23] ioctl for NVME_IOCTL_ADMIN_CMD failed with Permission denied
[2020-12-07 15:21:23] smart plugin: smart_read_nvme_disk failed, -1
```
## Steps to reproduce

* Enable the smart plugin in /etc/collectd.conf and ensure, at least one NVMe is included
* Run collectd as other user then root
* Check logs for errors.
* Run collectd as root.
* Inspect logs.

**Comment by faxm0dem** [comment]
Could you please specify which Linux capability is needed here ?

**Comment by mcharriere** [comment]
I'd expect cap_sys_rawio=ep to do the trick, since the nvme implementation uses ioctl, but that didn't work.

**Comment by faxm0dem** [comment]
### Binary's capabilities

```
sudo setcap cap_sys_rawio=ep /tmp/collectd/sbin/collectd
```

### Config

```
PluginDir "/tmp/collectd/lib/collectd"
LoadPlugin smart
LoadPlugin csv
<Plugin smart>
  Disk "sda"
  Disk "nvme0n1"
  IgnoreSelected false
</Plugin>
```

### Log

Both nvme and regular disks complain:

```
smart plugin: unable to open /dev/sda.
smart plugin: unable to open /dev/nvme0n1.
```
