### ISSUE TITLE
FAIL test_plugin_smart (exit status: 1) since 5.12.0

### ISSUE THREAD

**Issue by bzed** [collectd/collectd#3791]
*   Version of collectd: 5.12.0
*   Operating system / distribution: debian unstable

## Expected behavior

test_plugin_smart should be successfull on all architectures.

## Actual behavior

Since 5.12.0 test_plugin_smart fails on
* s390
* sparc64
* powerpc
* ppc64
* hppa

with
```
Testing x ...
not ok 1 - ret = 34432, want 32902
FAILURE.
FAIL test_plugin_smart (exit status: 1)
```
## Steps to reproduce

See the failed logs on

https://buildd.debian.org/status/logs.php?pkg=collectd

**Comment by bzed** [comment]
Failing part is

```
  ret = get_vendor_id(CORRECT_DEV_PATH, "stub");
  EXPECT_EQ_INT(VENDOR_ID, ret);
```

(the next one with VENDOR_ID = 0x0; just works fine).

```
%  ./test_plugin_smart                                                        
Testing x ...
not ok 1 - ret = 34432, want 32902
FAILURE.
```

**Comment by mrunge** [comment]
I have seen that bug on s390x as well. Thank you for your report and also for the fix! This is excellent. Let's see how to get it merged.
