### ISSUE TITLE
Turbostat plugin fails to read MSR at offset 0x630, config suggests I file a bug report

### ISSUE THREAD

**Issue by jarredglickstein** [collectd/collectd#3792]
This bug report is for two systems which both fail to read Intel CPU stats via the turbostat plugin. In both cases running "turbostat" from OS repositories works and produces some data, however collectd reports an issue reading from MSR offsets. On both systems the collectd turbostat plugin configuration is the same, left as default as per instructions in the comments: 

##### Turbostat Config in collectd.conf (comment lines removed for terseness):
<Plugin turbostat>
        TCCActivationTemp "100"
        CoreCstates "392"
        PackageCstates "396"
        SystemManagementInterrupt true
        DigitalTemperatureSensor true
        PackageThermalManagement true
        RunningAveragePowerLimit "7"
</Plugin>

##### Logfile output: 

[2020-12-09 17:35:05] turbostat plugin: MSR offset 0x630 read failed
[2020-12-09 17:35:05] turbostat plugin: Unable to read MSR_PKG_C8_RESIDENCY
[2020-12-09 17:35:05] read-function of plugin `turbostat' failed. Will suspend it for 1920.000 seconds.

##### System 1
*   CPU model: Intel i7-4790K
*   Version of collectd: 5.7.1-1.1
*   Operating system / distribution: Debian 9
*   Kernel version (if applicable): 4.9.0-3-amd64

##### System 2
*   CPU model: Intel i7-3820
*   Version of collectd: 5.7.2-2ubuntu1.2
*   Operating system / distribution: Linux Mint 20
*   Kernel version (if applicable): 4.15.0-54-generic

##### Other information
Here is some output from running turbostat on system 2: [https://pastebin.com/9AQuFdTc](url)

**Comment by mrunge** [comment]
Please update collectd to a recent version. There is a bugfix on 5.10, or 5.11 for the turbostat plugin.
