### ISSUE TITLE
Perl plugin not build in Fedora33. 

### ISSUE THREAD

**Issue by ff-100** [collectd/collectd#3798]
*   Version of collectd: any
*   Operating system / distribution: Fedora 33
*   Kernel version (if applicable): 5.9.16-200

## Expected behavior

Build perl plugin after run configure and make.

## Actual behavior
I'm trying build colletd in Fedora 33. After configuration stage I see, that libperl is not found.
In config.log I see next lines:
...
configure:100637: gcc -o conftest -g -O2  -I/usr/lib64/perl5/CORE    conftest.c  -Wl,--enable-new-dtags -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld  -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib64/perl5/CORE -lperl -lpthread -lresolv -ldl -lm -lcrypt -lutil -lc >&5
/usr/bin/ld: /tmp/ccwCnuHL.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
collect2: error: ld returned 1 exit status
...

I solve this problem by replace next string in configure.ac file 

diff -r 9ec762c7d0cd configure.ac
--- a/configure.ac      Wed Dec 30 19:46:57 2020 +0300
+++ b/configure.ac      Wed Dec 30 19:48:01 2020 +0300
@@ -4249,9 +4249,8 @@
SAVE_CFLAGS="$CFLAGS"
SAVE_LIBS="$LIBS"
dnl ARCHFLAGS="" -> disable multi -arch on OSX (see Config_heavy.pl:fetch_string)
\-  PERL_CFLAGS=\`ARCHFLAGS="" $PERL -MExtUtils::Embed -e perl_inc\`
\+ PERL_CFLAGS=\`ARCHFLAGS="" $PERL -MExtUtils::Embed -e ccopts\`
PERL_LIBS=\`ARCHFLAGS="" $PERL -MExtUtils::Embed -e ldopts\`
CFLAGS="$CFLAGS $PERL_CFLAGS"
LIBS="$LIBS $PERL_LIBS"

**Comment by mrunge** [comment]
I have proposed a PR against Fedora to build collectd-5.12. In my tests, that works without modification.
https://src.fedoraproject.org/rpms/collectd/pull-request/7

**Comment by ff-100** [comment]
What OS was used to build the project? I tried to do this exactly on Fedora 33.

**Comment by mrunge** [comment]
This is built in the fedora build system.

**Comment by ff-100** [comment]
Ok, what OS is used in build servers? I doubt that the build servers use Fedora 33.

**Comment by mrunge** [comment]
As you see, this was done on fedora 34, https://koji.fedoraproject.org/koji/taskinfo?taskID=59138729
I am expecting this to merge soon and also to have it updated across Fedora releases.

**Comment by ff-100** [comment]
In my opinion, the main problem is in the flags returned by the **ldopts** function when running the **perl -MExtUtils :: Embed -e ldopts** command. In my case, the following line is returned 
-Wl, - enable-new-dtags -Wl, -z, relro -Wl, - as-needed -Wl, -z, now -specs = /usr/lib/rpm/redhat/redhat-hardened-ld -Wl, -z, relro -Wl, - as-needed -Wl, -z, now -specs = /usr/lib/rpm/redhat/redhat-hardened-ld -fstack-protector-strong -L / usr / local / lib -L / usr / lib64 / perl5 / CORE -lperl -lpthread -lresolv -ldl -lm -lcrypt -lutil -lc.
The content of file **/usr/lib/rpm/redhat/redhat-hardened-ld** is follow
\* self_spec:
\+% {! static:% {! shared:% {! r: -pie}}}
This means that if the **-static, -shared, -r** options were not passed to the linker, the **-pie** option is added to the current linker options, which in this case results in an error. Solves the problem is using the **ccopts** option in configure.ac file, because in this case the necessary **-fPIE** flag for compilation is added to gcc.
In my case, the **perl -MExtUtils :: Embed -e ccopts** command returns the following:
-D_REENTRANT -D_GNU_SOURCE -O2 -flto = auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror = format -security -Wp, -D_FORTIFY_SOURCE = 2 -Wp, -D_GLIBCXX_ASSERTIONS -specs = / usr / lib / rpm / redhat / redhat-hardened-cc1 -fstack-protector-strong -specs = / usr / lib / rpm / redhat / redhat -annobin-cc1 -m64 -mtune = generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fwrapv -fno-strict-aliasing. 
As you can see, the option **-specs = /usr/lib/rpm/redhat/redhat-annobin-cc1** is used here.
The content of file **/ usr/lib/rpm/redhat/redhat-annobin-cc1** is follow
\* cc1_options:
\+% {! r:% {! fpie:% {! fPIE:% {! fpic:% {! fPIC:% {! fno-pic: -fPIE}}}}}}
This means that if the **-r, fpie, fPIE, fpic, fPIC, fno-pic** options were not passed to gcc, the **-fPIE** option will be added, which is necessary for the correct test build.
Unfortunately, I don't have access to Fedora koji. I can try to run a local build through mock, but for this I need a config file, for repeat the configuration where your build was performed.

P.S. Sorry for my English.
