### ISSUE TITLE
[wiki/web] kcollectd reference

### ISSUE THREAD

**Issue by aerusso** [collectd/collectd#3800]
Hello, I'm the maintainer of kcollectd, and I'm checking back in again---I'd like to make sure that people do not mistakenly believe that the project is abandoned.  I very recently released a new version, and I was hoping to "touch" the date stamp on the [wiki page for kcollectd](https://collectd.org/wiki/index.php/Kcollectd).

Also, the homepage for collectd includes a link directly to the very old original (and dead) kcollectd site.  In the interest of increasing visibility for my maintained fork of kcollectd, would it be possible to change that link to [my site](https://www.antonioerusso.com/projects/kcollectd)?

As a final, very minor, note:  the wiki page includes a link to the [old Debian QA tracker for kcollectd](http://packages.qa.debian.org/k/kcollectd.html)---could you please update it to point to the [newer version](https://tracker.debian.org/pkg/kcollectd)?

Thanks!

**Comment by mrunge** [comment]
Hi Antonio, thank you for getting in touch. I've updated the wiki page. Is there anything else you would like to get covered?

**Comment by aerusso** [comment]
Thanks!  The other thing is on the [front page](https://collectd.org), in the "Limitations" section: "Take a look at kcollectd, an X frontend"---the link there may be what many people find first.

**Comment by mrunge** [comment]
I've updated the "new" page, see https://github.com/collectd/website/commit/7c1445243bc44ac6c9339ed2242e18c21def97a4
Unfortunately, I can not say, when this is going to go live.

**Comment by aerusso** [comment]
Thanks, that's perfect!
