### ISSUE TITLE
Remove container:collectd/ci:el6_x86_64 from collectd CI

### ISSUE THREAD

**Issue by minfrin** [collectd/collectd#3882]
## Expected behavior

Travis / Cirrus CI runs successfully.

## Actual behavior

Travis / Cirrus CI is failing for the now obsolete RHEl6.

## Steps to reproduce

*   Submit PR, for example: https://github.com/collectd/collectd/pull/3803
*   CI fails, for example: https://github.com/collectd/collectd/pull/3803/checks?check_run_id=2148524935

Request from mailing list to @octo to fix/disable travis:

https://www.mail-archive.com/collectd@verplant.org/msg04199.html

**Comment by elfiesmelfie** [comment]
I believe this is addressed by https://github.com/collectd/collectd/pull/3784

**Comment by minfrin** [comment]
Thank you for this.
