### ISSUE TITLE
Wiki rendering errors 

### ISSUE THREAD

**Issue by andrewchambers** [collectd/collectd#3902]
## Expected behavior

At https://collectd.org/wiki/index.php/Binary_protocol the wiki should display image thumbnails.

## Actual behavior

The wiki displays: 

```
Error creating thumbnail: /bin/bash: /usr/bin/convert: No such file or directory

Error code: 127
```

**Comment by elfiesmelfie** [comment]
The page has been updated, it appears that there's an issue converting to thumbnail, or resizing images in anyway. 

I've updated the formatting to use frame instead, which should provide the same formatting as thumbnail (a floating block, with a caption, and not inline), but without the expected size reduction.

There's a [diff](https://collectd.org/wiki/index.php?title=Binary_protocol&type=revision&diff=5104&oldid=4547), showing the chanegs made, and you should be able to see the update on the [original page](https://collectd.org/wiki/index.php/Binary_protocol )

**Comment by mrunge** [comment]
since this has been fixed, we can close this issue.

@elfiesmelfie thank you for looking at this and also for confirming that this is fixed.
