### ISSUE TITLE
Collectd 5.12.0 version RPM packages

### ISSUE THREAD

**Issue by SrinivReddy** [collectd/collectd#3908]
Hi Team,

Unable to find Collectd 5.12.0 offical RPM packages.

And link is not working given at https://collectd.org/download.shtml#rpm

 Could you please help me to get offical RPM packages for 5.12.0 version.

   Version of collectd: 5.12.0
*   Operating system / distribution: Cent0s 7
*   Kernel version (if applicable):

**Comment by elfiesmelfie** [comment]
On CentOS, the official packages are provided by [OpsTools](http://wiki.centos.org/SpecialInterestGroup/OpsTools).

You can install using:

```
yum install -y centos-opstools-release
yum provides collectd
yum install -y collectd
```

For CentOS 7, collectd-5.10 is the latest version.

To get newer versions, you will need CentOS 8.
For CentOS 8, the current tested/released version is collectd-5.11, however, you can enable the opstools testing repo to get collectd-5.12 (tagged as testing).

```
dnf install -y centos-release-opstools
dnf --enablerepo=centos-opstools-testing install -y collectd
```

I will update the wiki to reflect this.

**Comment by mrunge** [comment]
Personally, I'd be looking for packages at my distribution. There may or may not be packages produced from any project; the distribution would see packages from a project as third party. If you are buying support from anyone, installing third party software may void your contract then.

If you are building collectd for yourself, there is a spec file https://github.com/collectd/collectd/blob/main/contrib/redhat/collectd.spec
which can be used like
``
rpmbuild -ba collectd.spec
``
or you'd use the ones provided by the CentOS Opstools SIG the way @elfiesmelfie described.

**Comment by mrunge** [comment]
Finally, I have pushed a change to the website repo https://github.com/collectd/website/commit/1201d33b6847e1222596530b1bd41e88337e56d3

Unfortunately, I can not figure out why this fails in (another and different) CI.
