### ISSUE TITLE
plugin_load: Could not find plugin "nut" in /usr/lib/collectd

### ISSUE THREAD

**Issue by MiXFiX** [collectd/collectd#3915]
Linux 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64
Debian 11

Cant enable nut plugin. Error: 
collectd[148512]: plugin_load: Could not find plugin "nut" in /usr/lib/collectd

Collectd version: collectd 5.12.0.git, http://collectd.org/

**Comment by mrunge** [comment]
Are you trying to install from Debian package repositories, or is this self-compiled?

**Comment by MiXFiX** [comment]
> Are you trying to install from Debian package repositories, or is this self-compiled?

From Debian package (apt install collectd)

**Comment by mrunge** [comment]
Please file a bug with your distribution. Please understand this is nothing we (as upstream can fix); There may even be a subpackage to install the missing plugin.

This is what Google found for me: https://packages.debian.org/bullseye/collectd-core

**Comment by mrunge** [comment]
The changelog in debian lists that building the nut plugin was disabled beginning with collectd-5.9, see https://metadata.ftp-master.debian.org/changelogs//main/c/collectd/collectd_5.12.0-7_changelog

**Comment by davidandreoletti** [comment]
Yet it continued to receive updates v5.11.0 (2020-03-15).

**Comment by bzed** [comment]
For those missing nut:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1023530
is the bug in the nut package, help to fix it and once nut is fixed I'll enable the plugin again.

**Comment by dwilliss** [comment]
From that thread, it sounds like the nut plugin is failing unit tests because the unit test is invalid.
Is there an ETA on getting this fixed? I kinda need it.

**Comment by mrunge** [comment]
> From that thread, it sounds like the nut plugin is failing unit tests because the unit test is invalid. Is there an ETA on getting this fixed? I kinda need it.

There is no timeline nor a fix for this. You are welcome to provide a fix.

**Comment by bzed** [comment]
@dwilliss that would need to be fixed in nut, feel free to provide a patch in the mentioned bug report in debian. please note that bookwork will ship without nut if this doesn't get fixed soon.

**Comment by bzed** [comment]
@dwilliss actually - its fixed in Debian since two days ago, I'll enable the nut plugin again.

Please note that you can install collectd from bullseye-backports, it comes with the nut plugin enabled.
