### ISSUE TITLE
Missing collectd_5.11.0-7.debian.tar.xz

### ISSUE THREAD

**Issue by akasharya** [collectd/collectd#3957]
*   Version of collectd: collectd_5.11.0-7
*   Operating system / distribution: debian
*   Kernel version (if applicable):

## Expected behavior
http://archive.ubuntu.com/ubuntu/pool/universe/c/collectd/collectd_5.11.0-7.debian.tar.xz to exist.

(Description of the behavior / output that you expected)
We are using collectd_5.11.0-7.debian.tar.xz and seems like it was available on repository till yesterday and now it is not.

(Description of the behavior / output that you observed)
http://archive.ubuntu.com/ubuntu/pool/universe/c/collectd/collectd_5.11.0-7.debian.tar.xz returns 404.

**Comment by mrunge** [comment]
This is a distribution issue, there is nothing we can do about this. Please contact your distribution directly.
