### ISSUE TITLE
iptables plugin can't get/write info

### ISSUE THREAD

**Issue by sbocquet** [collectd/collectd#3961]
*   Version of collectd: 5.12
*   Operating system / distribution: Debian 10
*   Kernel version (if applicable): 5.10

## Expected behavior

Some data in the disk files

## Actual behavior

Nothing is collected or written on disk

## Steps to reproduce

I have added the iptables plugin to my collectd working configuration, in order to get iptables statistics.
According to the collectd docs, the configuration file should be something like this :
```
root@home-server:/# cat /etc/collectd/collectd.conf.d/iptables.conf
LoadPlugin iptables
<Plugin "iptables">
  Chain "filter" "INPUT"
  Chain "filter" "OUTPUT"
</Plugin>
```

Here are some infos from my iptables :
```
root@home-server:/# iptables -L -n -v --line-numbers
# Warning: iptables-legacy tables present, use iptables-legacy to see them
Chain INPUT (policy ACCEPT 559 packets, 392K bytes)
num   pkts bytes target     prot opt in     out     source               destination
1     194M  182G ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate ESTABLISHED
2     150K   27M ACCEPT     all  --  lo     *       0.0.0.0/0            0.0.0.0/0
3        0     0 ACCEPT     icmp --  *      *       192.168.1.0/24       0.0.0.0/0
...
29    316K   56M DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
num   pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 560K packets, 37M bytes)
num   pkts bytes target     prot opt in     out     source               destination
1     315M  694G ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate ESTABLISHED
2     150K   27M ACCEPT     all  --  *      lo      0.0.0.0/0            0.0.0.0/0
```

Restarting the collectd demon is fine :
```
[2022-01-11 23:42:06] Exiting normally.
[2022-01-11 23:42:06] collectd: Stopping 5 read threads.
[2022-01-11 23:42:06] collectd: Stopping 5 write threads.
[2022-01-11 23:42:06] plugin_load: plugin "cpu" successfully loaded.
[2022-01-11 23:42:06] plugin_load: plugin "df" successfully loaded.
[2022-01-11 23:42:06] plugin_load: plugin "disk" successfully loaded.
[2022-01-11 23:42:06] plugin_load: plugin "interface" successfully loaded.
[2022-01-11 23:42:06] plugin_load: plugin "ipmi" successfully loaded.
[2022-01-11 23:42:06] ipmi plugin: Legacy configuration found! Please update your config file.
[2022-01-11 23:42:06] plugin_load: plugin "iptables" successfully loaded.
[2022-01-11 23:42:06] plugin_load: plugin "load" successfully loaded.
[2022-01-11 23:42:06] plugin_load: plugin "memory" successfully loaded.
[2022-01-11 23:42:06] plugin_load: plugin "rrdcached" successfully loaded.
[2022-01-11 23:42:06] plugin_load: plugin "smart" successfully loaded.
[2022-01-11 23:42:06] plugin_load: plugin "syslog" successfully loaded.
[2022-01-11 23:42:06] plugin_load: plugin "unixsock" successfully loaded.
[2022-01-11 23:42:06] plugin_load: plugin "uptime" successfully loaded.
[2022-01-11 23:42:06] Systemd detected, trying to signal readiness.
[2022-01-11 23:42:06] Initialization complete, entering read-loop.
[2022-01-11 23:42:08] ipmi plugin: sensor_list_add: Ignore sensor ` unspecified (0.0)` of `main`, because it isn't readable! Its type: (0xc, memory).
```

Unfortunatly, no data are collected/writen in the data directory (should have some iptables_filter_* directories from what I know)
```
root@home-server:/var/lib/rrdcached/db/localhost# ls
total 160
drwxr-xr-x 40 root root 4096 Dec 14 18:58 .
drwxr-xr-x  3 root root 4096 Jul 30  2020 ..
drwxr-xr-x  2 root root 4096 Jan  2 21:45 cpu-0
drwxr-xr-x  2 root root 4096 Jan  2 21:45 cpu-1
drwxr-xr-x  2 root root 4096 Jan  2 21:45 cpu-10
drwxr-xr-x  2 root root 4096 Jan  2 21:45 cpu-11
drwxr-xr-x  2 root root 4096 Jan  2 21:45 cpu-2
drwxr-xr-x  2 root root 4096 Jan  2 21:45 cpu-3
drwxr-xr-x  2 root root 4096 Jan  2 21:45 cpu-4
drwxr-xr-x  2 root root 4096 Jan  2 21:45 cpu-5
drwxr-xr-x  2 root root 4096 Jan  2 21:45 cpu-6
drwxr-xr-x  2 root root 4096 Jan  2 21:45 cpu-7
drwxr-xr-x  2 root root 4096 Jan  2 21:45 cpu-8
drwxr-xr-x  2 root root 4096 Jan  2 21:45 cpu-9
drwxr-xr-x  2 root root 4096 Jan  2 21:45 df-root
drwxr-xr-x  2 root root 4096 Jan  2 21:45 df-srv-dev-disk-by-label-Backups
drwxr-xr-x  2 root root 4096 Jan  2 21:45 df-srv-dev-disk-by-label-Datas
drwxr-xr-x  2 root root 4096 Jan  2 21:45 disk-md0
drwxr-xr-x  2 root root 4096 Jan  2 21:45 disk-nvme0n1
drwxr-xr-x  2 root root 4096 Jan  2 21:45 disk-sda
drwxr-xr-x  2 root root 4096 Jan  2 21:45 disk-sdb
drwxr-xr-x  2 root root 4096 Jan  2 21:45 disk-sdc
drwxr-xr-x  2 root root 4096 Jan  2 21:45 disk-sdd
drwxr-xr-x  2 root root 4096 Jan  2 21:45 disk-sde
drwxr-xr-x  2 root root 4096 Jan  2 21:45 interface-enp1s0f0
drwxr-xr-x  2 root root 4096 Jan  2 21:45 interface-enp1s0f1
drwxr-xr-x  2 root root 4096 Jan  2 21:45 interface-enp35s0
drwxr-xr-x  2 root root 4096 Jan  2 21:45 interface-enp36s0
drwxr-xr-x  2 root root 4096 Jan  2 21:45 interface-lo
drwxr-xr-x  2 root root 4096 Jan  2 21:45 ipmi
drwxr-xr-x  2 root root 4096 Jan  2 21:45 load
drwxr-xr-x  2 root root 4096 Jan  2 21:45 memory
drwxr-xr-x  2 root root 4096 Jan  2 21:45 rrdcached
drwxr-xr-x  2 root root 4096 Jan  2 21:45 smart-nvme0n1
drwxr-xr-x  2 root root 4096 Jan  2 21:45 smart-sda
drwxr-xr-x  2 root root 4096 Jan  2 21:45 smart-sdb
drwxr-xr-x  2 root root 4096 Jan  2 21:45 smart-sdc
drwxr-xr-x  2 root root 4096 Jan  2 21:45 smart-sdd
drwxr-xr-x  2 root root 4096 Jan  2 21:45 smart-sde
drwxr-xr-x  2 root root 4096 Jan  2 21:45 uptime
```

Does anyone have any idea of what the problem is ?

Thanks

Stéphane

**Comment by mrunge** [comment]
I have seen issues with the iptables plugin lately, because it relies on some old data structure and library. (iptc). For CentOS 9, there is no iptables plugin in collectd anymore, because of that.

**Comment by sbocquet** [comment]
Thx Matthias for the info.

Maybe someone could confirm the status for the Debian releases ? I hope it is still supported.

**Comment by mrunge** [comment]
I can not confirm or deny a status for distributions (other to the one I have some influence in). Sorry!

**Comment by sbocquet** [comment]
By chance, maybe you know who I can get in touch for the Debian distro ?

**Comment by mrunge** [comment]
uhm, I'd look at https://packages.debian.org/en/sid/collectd

@tokkee , @mfournier , or @bzed I know that all of you are really busy and not much involved anymore: do you have an idea, or could answer the question?

@sbocquet The term "supported" here is probably misleading, as it's not commercially supported by Debian, but there may be other organizations where one could buy support from?

**Comment by bzed** [comment]
Wild guess: the iptables plugin most likely is using iptables-legacy, the shown iptables output is from iptables (which wraps the new nftables).
That won't work, you'll have to use iptables-legacy ONLY if you want to do stuff with collectd.

As far as I can tell, there is not nftables plugin for collectd.

**Comment by mrunge** [comment]
Thank you @bzed .

That's my understanding as well: what collectd-iptables uses seems to be legacy, and I haven't seen a nbtables plugin.

**Comment by sbocquet** [comment]
From what I can see, there should be some iptables-legacy tables... or maybe I'm misunderstanding. 

```
root@home-server:/var/log# iptables -S
# Warning: iptables-legacy tables present, use iptables-legacy to see them
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-A INPUT -m conntrack --ctstate ESTABLISHED -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -s 192.168.1.0/24 -p icmp -j ACCEPT
...
-A INPUT -p tcp -j LOG --log-prefix "IPTables: "
-A INPUT -j DROP
-A OUTPUT -m conntrack --ctstate ESTABLISHED -j ACCEPT
-A OUTPUT -o lo -j ACCEPT
```

**Comment by bzed** [comment]
@sbocquet No. Please read what you've actually posted.

```
root@home-server:/var/log# iptables -S
# Warning: iptables-legacy tables present, use iptables-legacy to see them
```

iptables is most likely a symlink to iptables-nft.

**Comment by bzed** [comment]
> That's my understanding as well: what collectd-iptables uses seems to be legacy, and I haven't seen a nbtables plugin.

Correct.
A plugin written in Python should not be too hard to do, though.
https://wiki.nftables.org/wiki-nftables/index.php/Counters

**Comment by sbocquet** [comment]
@bzed You're right. It's nftables with Debian 10.

At the moment, I'm experiencing a new approach:
1 - Log the iptables traffic in a log file
2 - Use the collectd tail plugin to parse the log file... but a nftables plugin would be great for sure.

**Comment by sbocquet** [comment]
> @bzed You're right. It's nftables with Debian 10.
> 
> At the moment, I'm experiencing a new approach: 1 - Log the iptables traffic in a log file 2 - Use the collectd tail plugin to parse the log file... but a nftables plugin would be great for sure.

Well... It seems that I'm stuck as the tail plugin of collects v5.12 needs glibc >= v2.29 and Debian 10 has glibc v2.28.
No solution in sight :(

**Comment by bzed** [comment]
@sbocquet this is a bug tracker, not a place to learn basic IT knowledge.

But here are some last hints:
- learn about the reason behind your glibc error and that you just don't install random new packages on old systems.
- use debian backports, where you'll find 5.11 for buster, or just use debian 11
- logging firewall traffic into log files is usually a bad idea. if you are using nftables, I've pointed to some example python code already. writing a python plugin should be easy.
- iptables is dead, if you start something new, us nftables.

**Comment by sbocquet** [comment]
OK, you're right and I don't want to bother you anymore.
Just for the info, I'm aware of all that you said (package, backports,..) as It my daily job, but unfortunatly I'm not a python dev ;)
I was just searching for some solution, and it's probably not the right place.

Thx for the help.

**Comment by sbocquet** [comment]
Just for help for others, if you need Collectd 5.12 (ipmi plugin with support of nvme for me).

So , you can have collectd 5.12 running in Debian 10, with the tail plugin running too...

1 - Download the Debian 11 package and install it with "dpkg -i". Yes, it works fine ;)
2 - Download collectd src (http://collectd.org/files/collectd-5.12.0.tar.bz2) and follow https://collectd.org/wiki/index.php/First_steps to compile. Then take the tail.so file generated in the .libs directory and put it in your /usr/lib/collectd directory.
3 - Restart Collectd deamon.
4 - Enjoy ;)

**Comment by bzed** [comment]
@sbocquet please don't give such ill advise. The Package in Debian 11 was not  compiled to work on Buster. Create a proper backport instead (or wait until one is available).

**Comment by bzed** [comment]
@sbocquet you know you can build packages locally? these things are actually documented.
