### ISSUE TITLE
Collectd service is using huge memory which is also filling up disk space

### ISSUE THREAD

**Issue by Zorrom** [collectd/collectd#3978]
*   Version of collectd: 5.11.0
*   Operating system / distribution: Centos
*   Kernel version (if applicable): 4.18.0-348.7.1.el8_5.x86_64

## Expected behavior
Collectd to use proper memory and not load the system memory and storage
(Description of the behavior / output that you expected)

## Actual behavior
1. We are running calls at 20K+ tps in our system and it is found that collectd is using huge amount of memory and it just keeps growing every minute
Below is the output of collectd service status and please check the memory part
```
[root@myvm01~]# service collectd status
Redirecting to /bin/systemctl status collectd.service
● collectd.service - Collectd statistics daemon
   Loaded: loaded (/etc/systemd/system/collectd.service; disabled; vendor preset: disabled)
   Active: active (running) since Wed 2022-02-16 15:14:20 UTC; 22h ago
     Docs: man:collectd(1)
           man:collectd.conf(5)
 Main PID: 61290 (collectdmon)
    Tasks: 122 (limit: 823192)
   Memory: 32.5G
   CGroup: /system.slice/collectd.service
           ├─  61290 /usr/sbin/collectdmon -P /var/run/collectdmon.pid -c /usr/sbin/collectd -- -C /etc/collectd.conf
           ├─  61300 /usr/sbin/collectd -C /etc/collectd.conf -f
           ├─  61390 /usr/sbin/collectd -C /etc/collectd.conf -f
           ├─  61391 /usr/sbin/collectd -C /etc/collectd.conf -f
           ├─  61392 /usr/sbin/collectd -C /etc/collectd.conf -f
           ├─  61393 /usr/sbin/collectd -C /etc/collectd.conf -f
           ├─  61394 /usr/sbin/collectd -C /etc/collectd.conf -f
           ├─  61395 /usr/sbin/collectd -C /etc/collectd.conf -f
           ├─  61396 /usr/sbin/collectd -C /etc/collectd.conf -f
           ├─  61397 /usr/sbin/collectd -C /etc/collectd.conf -f
           ├─  61398 /usr/sbin/collectd -C /etc/collectd.conf -f
           ├─  61399 /usr/sbin/collectd -C /etc/collectd.conf -f
           ├─  61400 /usr/sbin/collectd -C /etc/collectd.conf -f
           ├─  61401 /usr/sbin/collectd -C /etc/collectd.conf -f
           ├─  61402 /usr/sbin/collectd -C /etc/collectd.conf -f
           ├─  61403 /usr/sbin/collectd -C /etc/collectd.conf -f
           ├─  61404 /usr/sbin/collectd -C /etc/collectd.conf -f
           ├─  61405 /usr/sbin/collectd -C /etc/collectd.conf -f
           ├─  61406 /usr/sbin/collectd -C /etc/collectd.conf -f
           ├─  61407 /usr/sbin/collectd -C /etc/collectd.conf -f
           ├─  61408 /usr/sbin/collectd -C /etc/collectd.conf -f
           ├─  61409 /usr/sbin/collectd -C /etc/collectd.conf -f
           ├─  61410 /usr/sbin/collectd -C /etc/collectd.conf -f
           ├─  61411 /usr/sbin/collectd -C /etc/collectd.conf -f
           ├─  61412 /usr/sbin/collectd -C /etc/collectd.conf -f
           ├─  61413 /usr/sbin/collectd -C /etc/collectd.conf -f
           ├─  61414 /usr/sbin/collectd -C /etc/collectd.conf -f
           ├─  61415 /usr/sbin/collectd -C /etc/collectd.conf -f
           ├─  61416 /usr/sbin/collectd -C /etc/collectd.conf -f
           ├─  61417 /usr/sbin/collectd -C /etc/collectd.conf -f
           ├─  61418 /usr/sbin/collectd -C /etc/collectd.conf -f
           ├─  61419 /usr/sbin/collectd -C /etc/collectd.conf -f

```           
The memory as shown above 32.5 GB but what we also noticed is that it is adding more and more storage on the system
The storage on the / directory was at 40GB used when the collectd memory was at 30 GB as showing below 
```
[root@myvm01 stats]# df -h /
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda2        94G   40G   50G  45% /

```

However as time passes the collectd memory keeps growing and when the memory reached 32.5 GB, it is increasing the storage on the system as shown below 

```
[root@myvm01 stats]# df -h /
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda2        94G   42G   48G  47% /
```

To put it more simple it is behaving like this 

```
If collectd memory is 11 GB , then df -h / is 16 GB
If collectd memory is 12 GB , then df -h / is 17 GB
If collectd memory is 13 GB , then df -h / is 18 GB


```
However it is verified that collectd is not physically storing any files on the system. Meaning there are no new files added on the system but still the storage keeps increasing as soon as collectd memory usage increase

(Description of the behavior / output that you observed)

I'd like to know how collectd is using huge RAM and filling up the system storage

## Steps to reproduce

*   step 1
Run calls on your system at 20K+ tps over 12 hours

**Comment by eero-t** [comment]
Collectd project does not provide "collectd.service" file that would start collectdmon, so the contents of your collectd.service come from somewhere else than collectd project (e.g. your distribution).  And with systemd restart functionality, AFAIK there should not be any need to run collectdmon, just run collectd directly and tell systemd to restart it like any other service.  See for example:  https://github.com/collectd/collectd/blob/main/contrib/systemd.collectd.service

Collectdmon should be just restarting terminating collectd, not running multiple instances of it, but it looks like you have multiple collectd instances running for some reason.  If you keep adding new collectd instances, each one naturally takes some memory, but that is not not a leak in collectd itself.

Please provide:
* Your collectd configuration (enabled plugins determine how collectd actually behaves)
* Your systemd "collectd.service" file content and packaging system info of where it came from
* "pstree" output, to see which processes are parents for the collectd processes (is collectdmon the parent)
* "ps ax | grep collecd" to see what is their status (are they e.g. in zombie state although collectdmon is using waitpid())

**Comment by Zorrom** [comment]
Hi @eero-t 
   This problem got resolved after we restarted our collectd service. And it is found that, there are bunch of our collectd stats files which are deleted on the system, but still collectd was holding on to them and was contantly increasing their memory
   Once we did a service restart, things came down and collectd dropped its memory usage and also released all the storage spaces it was holding
   
   
```
[root@vm01 ~]# lsof +L1 | grep -i collectd
collectd  1390996   root   16w   REG    8,2 10496329     0   4461279 /var/broadhop/stats/my-stats.10.csv (deleted)
collectd  1390999   root   16w   REG    8,2 10496329     0   4461279 /var/broadhop/stats/my-stats.10.csv (deleted)
collectd  1391002   root   16w   REG    8,2 10496329     0   4461279 /var/broadhop/stats/my-stats.10.csv (deleted)
collectd  1391003   root   16w   REG    8,2 10496329     0   4461279 /var/broadhop/stats/my-stats.10.csv (deleted)
collectd  1391005   root   16w   REG    8,2 10496329     0   4461279 /var/broadhop/stats/my-stats.10.csv (deleted)
collectd  1391009   root   16w   REG    8,2 10496329     0   4461279 /var/broadhop/stats/my-stats.10.csv (deleted)
```

So any idea why Collectd was doing this behaviour

Regards,
Azhar

**Comment by eero-t** [comment]
When you're saying "collectd", I assume you are talking about the behavior of the cgroup for your (unknown) "collectd" service file, which creates all these collectd instances (with unknown configuration and unknown state).

For all I know, it might not be reaping the processes if they end up in Zombie state (so that resources associated with the collectd processes would actually go away when given process dies), but without the data I asked for, it's impossible to say whether collectd, collectdmon, your service file (or some other component) is causing it.

**Comment by mrunge** [comment]
Interesting! Glad you figured this out.
