### ISSUE TITLE
Unable to get accurate graphs

### ISSUE THREAD

**Issue by Pocketpac** [collectd/collectd#3988]
*   Version of collectd: collectd 5.9.2.g-1ubuntu5
*   Operating system / distribution: Ubuntu 20.04 LTS
*   Kernel version (if applicable):

## Expected behavior

To show actual values.

## Actual behavior

Shows weird values that end with `m`, aka 140.2m

## Steps to reproduce

I am using Curl_JSON to hit an api and using CGP for a front end, but I can't get it to show right. For example this is supposed to be showing api hits:

<URL "***">
    Instance "***"
    <Key "apiHits">
      Type "Absolute"
    </Key>
  </URL>

when I manually check the url results it shows correctly, lets say 53 for the api hits but CGP shows the following ![image](https://user-images.githubusercontent.com/10564428/160156266-7d6cb99c-342e-412a-9579-31fedbe9020b.png)

It always shows something like 140.0m instead of what it should show. Its always something ending with 'm' and is always way off what I want it to show. I have tried Absolute, Counter, Guage, all of them I can find but I am at a loss. I'm not sure if this is a collectd issue or a CGP issue so any guidance would be appreciated.

**Comment by mrunge** [comment]
I'm sorry, without a little more context, we are unable to help.
Collectd-5.9 is unsupported, as of now. The next suggestion you'd get is to try to reproduce with a more recent version. 

My gut feeling here is that you'll get metrics reported as a number, divided per time.

In any case, if there is a bug, it is unlikely to be fixed and backported to collectd-5.9. I'm going to close this here.
