### ISSUE TITLE
CollectInternalStats true reports 'UNKNOWN plugin: plugin_get_interval: Unable to determine Interval from context'

### ISSUE THREAD

**Issue by ConiKost** [collectd/collectd#3991]
*   Version of collectd: 5.12.0
*   Operating system / distribution: Gentoo
*   Kernel version (if applicable): 5.17.1

## Expected behavior
Log message ```[collectd] UNKNOWN plugin: plugin_get_interval: Unable to determine Interval from context.``` is not being written

## Actual behavior
Log message ```[collectd] UNKNOWN plugin: plugin_get_interval: Unable to determine Interval from context.``` is being written.

## Steps to reproduce

*   Set ```CollectInternalStats``` to ```true```
*   Restart collectd
*   Above message is being logged.

**Comment by LHozzan** [comment]
I think, this is duplicate, see https://github.com/collectd/collectd/issues/3920 .

**Comment by mrunge** [comment]
Thank you for the report.

Yes, this is a duplicate. Closing this issue here.
