### ISSUE TITLE
Collectd-python rpm responsible for python.so is binded to Python 3.6 instead of Python 3.9

### ISSUE THREAD

**Issue by Zorrom** [collectd/collectd#3997]
*   Version of collectd: 5.11
*   Operating system / distribution: AlmaLinux release 8.5 (Arctic Sphynx)
*   Kernel version (if applicable): 4.18.0-348.20.1.el8_5.x86_64

## Expected behavior
Collectd to bind to python 3.9 site-packages instead of 3.6 site-packages. 
(Description of the behavior / output that you expected)

## Actual behavior
Collectd-python rpm is creating python.so file which is binding to python 3.6 libraries instead of python 3.9
(Description of the behavior / output that you observed)
The collectd-python rpm  is creating /usr/lib64/collectd/python.so and that is binding itself to python 3.6 libraries

```
[root@az-01 ~]# ldd /usr/lib64/collectd/python.so 
        linux-vdso.so.1 (0x00007fffcabfa000)
        libpython3.6m.so.1.0 => /lib64/libpython3.6m.so.1.0 (0x00007fe032b6a000)    # Binded to python 3.6
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fe03294a000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fe032746000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00007fe032542000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fe0321c0000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fe031dfb000)
        libcrypto.so.1.1 => /lib64/libcrypto.so.1.1 (0x00007fe031912000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fe0332c0000)
        libz.so.1 => /lib64/libz.so.1 (0x00007fe0316fb000)
[root@az-01 ~]# 
```
My system has both python 3.6 and python 3.9 and my python defaults are set to Python3.9. However installing collectd and collectd-python are binding itself to python 3.6 libraries instead of 3.9
Becuase of collectd binding itself to python 3.6, my collectd python module is not able to load the modules and packages which are installed in python3.9/site-packages

```
[root@az-01~]# /usr/sbin/update-alternatives --list  | grep -i python
python                  auto    /usr/libexec/no-python
python3                 auto    /usr/bin/python3.9
```
## Steps to reproduce

```
*  Install the below rpms in your system which have both python3.6 and python 3.9
[root@az-01~]# rpm -qa | grep -i collectd
collectd-disk-5.11.0-1.el8.x86_64
libcollectdclient-5.11.0-1.el8.x86_64
collectd-5.11.0-1.el8.x86_64
collectd-ping-5.11.0-1.el8.x86_64
collectd-python-5.11.0-1.el8.x86_64
```

Run the following command to see that python.so is using python3.6 libraries
`[root@az-01 ~]# ldd /usr/lib64/collectd/python.so `

**Comment by mrunge** [comment]
Please report this to your distribution, there is nothing upstream can do about this.

On a side-note, you can have only one python 3 version inside the repositories. If you are mixing python 3.6 and python 3.9  without doing things like modularization, that is going to create major headaches.

In CentOS 8 (Stream) and CentOS 9, we are building only against the distro provided python version.

**Comment by Zorrom** [comment]
@mrunge Thanks for your response. For now we just softlinked the respective modules from our Python3.9 to Python 3.6  and that fixed our problem
But just to add, I dont think collectd-python will take Python3.9 when there is a 3.6 on the system, even with Python3.9 set to default. This is a problem which I dont find an answer still. Anyways thanks for your help

**Comment by mrunge** [comment]
How did you install python 3.9?

The collectd-python-plugin is built against a given python. You'll have to rebuild it yourself, I assume. The specs file is open, you'd have to adjust the spec for the different python, you could use something like https://src.fedoraproject.org/rpms/collectd/blob/rawhide/f/collectd.spec#_685
