### ISSUE TITLE
How to obtain rrdtool.so plugin for FreeBSD 13

### ISSUE THREAD

**Issue by smileymattj** [collectd/collectd#4000]
*   Version of collectd: collectd5-5.12.0_4 
*   Version of rrdtool: rrdtool-1.7.2_6
*   Operating system / distribution: FreeBSD 13.0-RELEASE
*   Kernel version (if applicable):

## Expected behavior

Run collectd server on FreeBSD; output to rrdtool

## Actual behavior

Can't start collectd due to missing rrdtool plugin

**Console Output:**
Starting collectd.
Created new plugin context.
Error: Parsing the config file failed!
/usr/local/etc/rc.d/collectd: WARNING: failed to start collectd

**/var/log/messages:**
There is configuration for the `rrdtool' plugin, but the plugin isn't loaded. Please check your configuration.
/usr/local/etc/rc.d/collectd: WARNING: failed to start collectd

## Steps to reproduce

pkg install collectd5 rrdtool

uncomment "LoadPlugin rrdtool" in /usr/local/etc/collectd.conf

rrdtool pkg includes the following libraries:
    /usr/local/lib/librrd.a
    /usr/local/lib/librrd.so.8.2.1
    /usr/local/lib/librrd.so.8
    /usr/local/lib/librrd.so

**Comment by kev009** [comment]
FreeBSD pkgs are built with default options, while the port (https://cgit.freebsd.org/ports/tree/net-mgmt/collectd5/Makefile#n64) has the majority of available options available but not set.  You will need to build your own package to use this plugin.

**Comment by mrunge** [comment]
Please file a bug with your distribution. Collectd upstream has unfortunately little to no influence there.
