### ISSUE TITLE
collectd network.so failed: ld.so.1: collectd: 

### ISSUE THREAD

**Issue by dmitriklein** [collectd/collectd#4001]
*   Version of collectd: 5.12.0,REV=2021.11.22
*   Operating system / distribution: SunOS 5.10
*   Kernel version (if applicable):

## Expected behavior

# ldd -d network.so
        libsocket.so.1 =>        /lib/libsocket.so.1
        libgcrypt.so.20 =>       /opt/csw/lib/i386/libgcrypt.so.20
        libgcc_s.so.1 =>         /opt/csw/lib/i386/libgcc_s.so.1
        libc.so.1 =>     /lib/libc.so.1
        libnsl.so.1 =>   /lib/libnsl.so.1
        libgpg-error.so.0 =>     /opt/csw/lib/i386/libgpg-error.so.0
        libmp.so.2 =>    /lib/libmp.so.2
        libmd.so.1 =>    /lib/libmd.so.1
        libscf.so.1 =>   /lib/libscf.so.1
        librt.so.1 =>    /lib/librt.so.1
        libintl.so.8 =>  /opt/csw/lib/i386/libintl.so.8
        libdoor.so.1 =>  /lib/libdoor.so.1
        libuutil.so.1 =>         /lib/libuutil.so.1
        libgen.so.1 =>   /lib/libgen.so.1
        libaio.so.1 =>   /lib/libaio.so.1
        libiconv.so.2 =>         /opt/csw/lib/i386/libiconv.so.2
        libm.so.2 =>     /lib/libm.so.2
# 

## Actual behavior

# ldd -d /opt/csw/lib/collectd/network.so
        libsocket.so.1 =>        /lib/libsocket.so.1
        libgcrypt.so.20 =>       /opt/csw/lib/i386/libgcrypt.so.20
        libgcc_s.so.1 =>         /opt/csw/lib/i386/libgcc_s.so.1
        libc.so.1 =>     /lib/libc.so.1
        libnsl.so.1 =>   /lib/libnsl.so.1
        libgpg-error.so.0 =>     /usr/lib/libgpg-error.so.0
        libmp.so.2 =>    /lib/libmp.so.2
        libmd.so.1 =>    /lib/libmd.so.1
        libscf.so.1 =>   /lib/libscf.so.1
        libdoor.so.1 =>  /lib/libdoor.so.1
        libuutil.so.1 =>         /lib/libuutil.so.1
        libgen.so.1 =>   /lib/libgen.so.1
        libm.so.2 =>     /lib/libm.so.2
# 

May  9 13:39:58 collectd[12623]: [ID 702911 daemon.error] dlopen("/opt/csw/lib/collectd/network.so") failed: ld.so.1: collectd: fatal: relocation error: file /opt/csw/lib/collectd/network.so: symbol gcry_cipher_close: referenced symbol not found. The most common cause for this problem is missing dependencies. Use ldd(1) to check the dependencies of the plugin / shared object.

## Steps to reproduce

*   step 1
*   step 2
*   step 3

**Comment by dmitriklein** [comment]
Following four libraries are not required and not linked by network.so for some reason:

# ls -la /lib/librt.so.1
-rwxr-xr-x   1 root     bin        48984 Jul  4  2011 /lib/librt.so.1
you have mail
# 
# ls -la /opt/csw/lib/i386/libintl.so.8
lrwxrwxrwx   1 root     root          16 May  9 12:01 /opt/csw/lib/i386/libintl.so.8 -> libintl.so.8.1.1
# 
# ls -la /lib/libaio.so.1
-rwxr-xr-x   1 root     bin        51108 Jan 14  2013 /lib/libaio.so.1
# 

lrwxrwxrwx   1 root     root          17 Apr 28 16:04 /opt/csw/lib/i386/libiconv.so.2 -> libiconv.so.2.5.1
# 
 
which leads to error: May 9 13:39:58 collectd[12623]: [ID 702911 daemon.error] dlopen("/opt/csw/lib/collectd/network.so") failed: ld.so.1: collectd: fatal: relocation error: file /opt/csw/lib/collectd/network.so: symbol gcry_cipher_close: referenced symbol not found. The most common cause for this problem is missing dependencies. Use ldd(1) to check the dependencies of the plugin / shared object.

**Comment by dago** [comment]
The linker output you describe is unrelated to the error message you get. Also I notice that you are running the 32 bit version of collectd. This is most certainly not what you want because almost all x86 platform run a 64 bit Solaris kernel and to access the metrics you should be running 64 bit collectd. Please verify your configuration with `/opt/csw/sbin/amd64/collectd -T`.

**Comment by dmitriklein** [comment]
Fixed by installing additional package CSWlibgpg-error0. Thank you!


# ldd -d /opt/csw/lib/amd64/collectd/network.so
        libsocket.so.1 =>        /lib/64/libsocket.so.1
        libgcrypt.so.20 =>       /opt/csw/lib/amd64/libgcrypt.so.20
        libgcc_s.so.1 =>         /opt/csw/lib/amd64/libgcc_s.so.1
        libc.so.1 =>     /lib/64/libc.so.1
        libnsl.so.1 =>   /lib/64/libnsl.so.1
        libgpg-error.so.0 =>     (file not found)
        libmp.so.2 =>    /lib/64/libmp.so.2
        libmd.so.1 =>    /lib/64/libmd.so.1
        libscf.so.1 =>   /lib/64/libscf.so.1
        libdoor.so.1 =>  /lib/64/libdoor.so.1
        libuutil.so.1 =>         /lib/64/libuutil.so.1
        libgen.so.1 =>   /lib/64/libgen.so.1
        libm.so.2 =>     /lib/64/libm.so.2
# 

# pkgadd -d libgpg_error0-1.20,REV=2015.11.20-SunOS5.10-i386-CSW.pkg

The following packages are available:
  1  CSWlibgpg-error0     libgpg_error0 - GNU gpg related library, libgpg-error.so.0
                          (i386) 1.20,REV=2015.11.20

Select package(s) you wish to process (or 'all' to process
all packages). (default: all) [?,??,q]: 


Installation of <CSWlibgpg-error0> was successful.
# 
# ldd -d /opt/csw/lib/amd64/collectd/network.so
        libsocket.so.1 =>        /lib/64/libsocket.so.1
        libgcrypt.so.20 =>       /opt/csw/lib/amd64/libgcrypt.so.20
        libgcc_s.so.1 =>         /opt/csw/lib/amd64/libgcc_s.so.1
        libc.so.1 =>     /lib/64/libc.so.1
        libnsl.so.1 =>   /lib/64/libnsl.so.1
        libgpg-error.so.0 =>     /opt/csw/lib/amd64/libgpg-error.so.0
        libmp.so.2 =>    /lib/64/libmp.so.2
        libmd.so.1 =>    /lib/64/libmd.so.1
        libscf.so.1 =>   /lib/64/libscf.so.1
        librt.so.1 =>    /lib/64/librt.so.1
        libintl.so.8 =>  /opt/csw/lib/amd64/libintl.so.8
        libdoor.so.1 =>  /lib/64/libdoor.so.1
        libuutil.so.1 =>         /lib/64/libuutil.so.1
        libgen.so.1 =>   /lib/64/libgen.so.1
        libaio.so.1 =>   /lib/64/libaio.so.1
        libiconv.so.2 =>         /opt/csw/lib/amd64/libiconv.so.2
        libm.so.2 =>     /lib/64/libm.so.2
# 

# ldd /opt/csw/lib/collectd/network.so
        libsocket.so.1 =>        /lib/libsocket.so.1
        libgcrypt.so.20 =>       /opt/csw/lib/i386/libgcrypt.so.20
        libgcc_s.so.1 =>         /opt/csw/lib/i386/libgcc_s.so.1
        libc.so.1 =>     /lib/libc.so.1
        libnsl.so.1 =>   /lib/libnsl.so.1
        libgpg-error.so.0 =>     /opt/csw/lib/i386/libgpg-error.so.0
        libmp.so.2 =>    /lib/libmp.so.2
        libmd.so.1 =>    /lib/libmd.so.1
        libscf.so.1 =>   /lib/libscf.so.1
        librt.so.1 =>    /lib/librt.so.1
        libintl.so.8 =>  /opt/csw/lib/i386/libintl.so.8
        libdoor.so.1 =>  /lib/libdoor.so.1
        libuutil.so.1 =>         /lib/libuutil.so.1
        libgen.so.1 =>   /lib/libgen.so.1
        libaio.so.1 =>   /lib/libaio.so.1
        libiconv.so.2 =>         /opt/csw/lib/i386/libiconv.so.2
        libm.so.2 =>     /lib/libm.so.2
you have mail
#

**Comment by dago** [comment]
Looks like a missed dependency to CSWlibgpg-error0 in CSWcollectd, thanks for noticing!
