### ISSUE TITLE
write_prometheus plugin: Opening a listening socket failed.

### ISSUE THREAD

**Issue by shari0311** [collectd/collectd#4010]
*   Version of collectd: 5.8.1
*   Operating system / distribution: ubuntu:16.04
*   Kernel version (if applicable):

## Expected behavior
The write_prometheus plugin should start normally when I run "/opt/collectd/sbin/collectd".

(Description of the behavior / output that you expected)

## Actual behavior
The write_prometheus plugin fails when I restart the collectd service:

[2022-06-02 15:18:59] plugin_load: plugin "write_prometheus" successfully loaded.
[2022-06-02 15:18:59] write_prometheus plugin: Opening a listening socket failed.
[2022-06-02 15:18:59] write_prometheus plugin: MHD_start_daemon() failed.
[2022-06-02 15:18:59] Initialization of plugin `write_prometheus' failed with status -1. Plugin will be unloaded.
[2022-06-02 15:18:59] plugin_unregister_read: No such read function: write_prometheus

**Comment by eero-t** [comment]
What port number you've configured for it i.e. is it a privileged one (<1000) and if yes, did you add the necessary privileges for collectd?

Also, how did you verify that the port is not already taken by some other process?

**Comment by mrunge** [comment]
in some cases it helps to specify the ip address to be used.

**Comment by Delicious-Bacon** [comment]
Is there any update on this? I have it as well.

collectd Version: 5.12
Operating Sytem: Rocky Linux 9

```
$ sudo systemctl status collectd
● collectd.service - Collectd statistics daemon
     Loaded: loaded (/usr/lib/systemd/system/collectd.service; enabled; vendor preset: disabled)
     Active: active (running) since Fri 2022-09-16 11:07:48 CEST; 10min ago
       Docs: man:collectd(1)
             man:collectd.conf(5)
   Main PID: 5021 (collectd)
      Tasks: 11 (limit: 202197)
     Memory: 1.8M
        CPU: 80ms
     CGroup: /system.slice/collectd.service
             └─5021 /usr/sbin/collectd

Sep 16 11:07:48 Rocky collectd[5021]: plugin_load: plugin "load" successfully loaded.
Sep 16 11:07:48 Rocky collectd[5021]: plugin_load: plugin "memory" successfully loaded.
Sep 16 11:07:48 Rocky collectd[5021]: plugin_load: plugin "write_prometheus" successfully loaded.
Sep 16 11:07:48 Rocky collectd[5021]: Systemd detected, trying to signal readiness.
Sep 16 11:07:48 Rocky systemd[1]: Started Collectd statistics daemon.
Sep 16 11:07:48 Rocky collectd[5021]: write_prometheus plugin: Opening a listening socket for [localhost]:9103 failed.
Sep 16 11:07:48 Rocky collectd[5021]: Initialization of plugin `write_prometheus' failed with status -1. Plugin will be unloaded.
Sep 16 11:07:48 Rocky collectd[5021]: plugin_unregister_read: No such read function: write_prometheus
Sep 16 11:07:48 Rocky collectd[5021]: Error: one or more plugin init callbacks failed.
Sep 16 11:07:48 Rocky collectd[5021]: Initialization complete, entering read-loop.
```
As @eero-t asked to check for ports, here are the occupied ports:
```
$ sudo lsof -i -P -n | grep LISTEN
systemd      1       root  381u  IPv4  20745      0t0  TCP *:111 (LISTEN)
systemd      1       root  383u  IPv6  11991      0t0  TCP *:111 (LISTEN)
rpcbind   1036        rpc    4u  IPv4  20745      0t0  TCP *:111 (LISTEN)
rpcbind   1036        rpc    6u  IPv6  11991      0t0  TCP *:111 (LISTEN)
cupsd     1172       root    7u  IPv6  32164      0t0  TCP [::1]:631 (LISTEN)
cupsd     1172       root    8u  IPv4  32165      0t0  TCP 127.0.0.1:631 (LISTEN)
sshd      1177       root    3u  IPv4  23404      0t0  TCP *:22 (LISTEN)
sshd      1177       root    4u  IPv6  23406      0t0  TCP *:22 (LISTEN)
mariadbd  1203      mysql   21u  IPv4  34133      0t0  TCP *:3306 (LISTEN)
mariadbd  1203      mysql   23u  IPv6  34134      0t0  TCP *:3306 (LISTEN)
prometheu 1327 prometheus    8u  IPv6  37897      0t0  TCP *:9090 (LISTEN)
```

And here's the configured port in `/etc/collectd.conf`:
```
LoadPlugin write_prometheus
<Plugin "write_prometheus">
    Port "9103"
</Plugin>
```

**Comment by eero-t** [comment]
@Delicious-Bacon Checking just LISTEN ports is not enough.

Please check also which networking syscall fails in your setup:
`strace -e socket,bind,listen ./collectd -T -f`

As failures in each can have different reasons.

PS. I added PR (to v6 branch) to log which network function in listen socket creation chain fails.  That should help debugging these issues in future.

**Comment by Delicious-Bacon** [comment]
@eero-t , right, I have updated the `lsof` output in the previous comment.

Here's the `strace` output (I have edited the command to "collectd" instead of "./collectd").
```
$ strace -e socket,bind,listen collectd -T -f
socket(AF_UNIX, SOCK_DGRAM|SOCK_CLOEXEC, 0) = 4
socket(AF_NETLINK, SOCK_RAW|SOCK_CLOEXEC, NETLINK_ROUTE) = 3
bind(3, {sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, 12) = 0
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 5
socket(AF_INET6, SOCK_DGRAM|SOCK_CLOEXEC, IPPROTO_IP) = 3
socket(AF_NETLINK, SOCK_RAW|SOCK_CLOEXEC, NETLINK_ROUTE) = 3
bind(3, {sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, 12) = 0
socket(AF_INET6, SOCK_STREAM|SOCK_CLOEXEC, IPPROTO_IP) = 3
bind(3, {sa_family=AF_INET6, sin6_port=htons(9103), sin6_flowinfo=htonl(0), inet_pton(AF_INET6, "::", &sin6_addr), sin6_scope_id=0}, 28) = 0
listen(3, 16)                           = 0
+++ exited with 0 +++
```

**Comment by eero-t** [comment]
@Delicious-Bacon That seems to have worked fine, as I do not see any error either from the network syscalls, _or_ from `write_prometheus`.

To find out what issue your host has, output for your _failing_ collectd config is needed.  I.e. use same `-C <conffile>` option as with your failing case.

PS. Add `-f` option also for `strace` (in case there are multiple threads).

**Comment by Delicious-Bacon** [comment]
@eero-t my brother hinted it's Security-Enhanced Linux (SELinux) that's preventing `collectd` to open the socket, and he was right. Setting `setenforce 0` (disabling SELinux temporary) enables me to restart the `collectd` service without any issues.

Is there a way to set it up without disabling SELinux?

**Comment by mrunge** [comment]
on Red Hat based versions, you can use
`sudo setsebool -P collectd_tcp_network_connect=on`

setenforce 0 will switch SELinux into permissive mode; if you disable selinux temporarily, you'd have to relabel your file system; permissive mode is not disabling.

**Comment by Delicious-Bacon** [comment]
> on Red Hat based versions, you can use `sudo setsebool -P collectd_tcp_network_connect=on`
This did not change anything. I restarted `collectd` service, did a reboot and it's still failing to open the :9103 socket.

**Comment by mrunge** [comment]
At least, you should be able to find a message in `/var/log/audit/audit.log`. Confirming the policy is really named `collectd_tcp_network_connect` via `getsebool -a | grep collectd` may be helpful as well.

**Comment by Delicious-Bacon** [comment]
Not sure what should I be looking for in the `audit.log`, but here's something I've found that mentions `collectd`:
```
type=AVC msg=audit(1663321112.756:52): avc:  denied  { listen } for  pid=1314 comm="collectd" lport=9103 scontext=system_u:system_r:collectd_t:s0 tcontext=system_u:system_r:collectd_t:s0 tclass=tcp_socket permissive=0
type=SYSCALL msg=audit(1663321112.756:52): arch=c000003e syscall=50 success=no exit=-13 a0=3 a1=10 a2=1c a3=7ffc524241d4 items=0 ppid=1 pid=1314 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="collectd" exe="/usr/sbin/collectd" subj=system_u:system_r:collectd_t>
type=PROCTITLE msg=audit(1663321112.756:52): proctitle="/usr/sbin/collectd"
```

Policy exists:
```
$ getsebool -a | grep collectd
collectd_tcp_network_connect --> on
```

**Comment by mrunge** [comment]
> Not sure what should I be looking for in the `audit.log`, but here's something I've found that mentions `collectd`:
> 
> ```
> type=AVC msg=audit(1663321112.756:52): avc:  denied  { listen } for  pid=1314 comm="collectd" lport=9103 scontext=system_u:system_r:collectd_t:s0 tcontext=system_u:system_r:collectd_t:s0 tclass=tcp_socket permissive=0
> type=SYSCALL msg=audit(1663321112.756:52): arch=c000003e syscall=50 success=no exit=-13 a0=3 a1=10 a2=1c a3=7ffc524241d4 items=0 ppid=1 pid=1314 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="collectd" exe="/usr/sbin/collectd" subj=system_u:system_r:collectd_t>
> type=PROCTITLE msg=audit(1663321112.756:52): proctitle="/usr/sbin/collectd"
> ```
> 
> Policy exists:
> 
> ```
> $ getsebool -a | grep collectd
> collectd_tcp_network_connect --> on
> ```

That'd be a bug. Please understand, this is nothing the collectd project can fix or is responsible for. Please file a ticket with your distribution.

I am also not sure if this selinux issue is what @shari0311 initially saw. I'm going to close this for now since this is not a collectd bug nor something we can fix. @shari0311 please open another issue, if you happen to hit this again.

**Comment by pixelsoccupied** [comment]
Also ran into the same issue (collectd 5.9.0 + rhel-8)..."write_prometheus plugin: Opening a listening socket for... [::]:9103 failed". 

Had to modify selinux from `Enforcing` to `Permissive` to finally get it to work. To check your current config with `getenforce`
