### ISSUE TITLE
statsd plugin: calculate more info about timers

### ISSUE THREAD

**Issue by mfournier** [collectd/collectd#402]
For timer/latency metrics, the reference nodejs implementation calculates much more information than just the average, namely:

* min/max values received during the interval
* sum of these values
* number of values received, and also how many per second
* the median value and the standard deviation

The node.js version will also calculate the timers min/max/sum/avg/median of the Nth percentile(s).

Also something that could be awesome, would be an option to count the amount of timer hits above/below a certain threshold (a feature the statsd plugin doesn't offer AFAIK).

**Comment by octo** [comment]
@mfournier Is there still something to do here or can we close this feature request?

**Comment by mfournier** [comment]
Not everything I mentioned is implemented, but it was more of a wishlist than an actual need.

Let's close it now. We can always open new issues if needed.
