### ISSUE TITLE
`algernon/riemann-c-client` got removed

### ISSUE THREAD

**Issue by chenrui333** [collectd/collectd#4021]
it looks like `algernon/riemann-c-client` repo got removed for whatever reason. Just raising it in here since [there are some dependency on it](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/collectd.rb#L43).

also relates to https://github.com/Homebrew/homebrew-core/pull/105468

**Comment by jirutka** [comment]
It has been moved to https://git.madhouse-project.org/algernon/riemann-c-client.

**Comment by chenrui333** [comment]
Ah, I see, thanks!
