### ISSUE TITLE
Collected data showing different value in perf table in Log analyics workspace 

### ISSUE THREAD

**Issue by azmonuser** [collectd/collectd#4064]
*   Version of collectd:5.10.0
*   Operating system / distribution: Red Hat Enterprise Linux(cpe:/o:redhat:enterprise_linux:7.9:GA:server)
*   Kernel version (if applicable): Linux 3.10.0-1160.80.1.el7.x86_64

## Expected behavior
![image](https://user-images.githubusercontent.com/119419698/205030016-698d98ed-3264-4182-a17c-bc6311054bc8.png)

(Description of the behavior / output that you expected)
In the server we can see correct values as expected
## Actual behavior
![image](https://user-images.githubusercontent.com/119419698/205030362-6d185d29-3827-4d95-8c5a-50a948b3bed9.png)

(Description of the behavior / output that you observed)
We have noticed in the perf table in loganalytics we can see different values(floating) compare to the server values

Please find collectd configuration file 
/etc/collectd.conf
![image](https://user-images.githubusercontent.com/119419698/205031601-28897e05-94df-4b1e-9789-d5ea8063214f.png)

Could you please have a look into it and update.

## Steps to reproduce

*   step 1
*   step 2
*   step 3

**Comment by mrunge** [comment]
Thank you for your report. Just to make sure I understand this correctly: you are collecting data from some device and export the data via snmp? Can you please provide a little more info on how to reproduce the issue?

**Comment by bacchus21** [comment]
> Thank you for your report. Just to make sure I understand this correctly: you are collecting data from some device and export the data via snmp? Can you please provide a little more info on how to reproduce the issue?

Yes, your understanding is correct.  The below is traffic flow. Any idea or comments, please share.

OnPrem                                                           Azure
---------------------------------------------------||--------------------------------------------------
Network devices -> Cacti server -> forwarding data -> Azure Log Analytic Workspace.

**Comment by bacchus21** [comment]
@mrunge Could you please advise what I can do next? Any opinions/comments are welcomed. Thank you in advance.

**Comment by Alan-Lee-JP** [comment]
@pyr , @octo , @tokkee, @mrunge , @jkohen , @sunkuranganath , @kwiatrox , @bkjg ,

Dear collectd members, 
We need your advice and support on this issue. Our team has been working on this issue for over a month but still have no glue on how to resolve this data discrepancy issue betwen 'snmp' folder and Azure Pref table as descripted above. Please let us know if anything we can check or extra information you need.

Please help.

Best regadrs,
Alan

**Comment by mrunge** [comment]
it is still unclear where the data comes from. I see snmp mentioned here, is there some kind of transformation included?
SNMP would not be my first preference to begin with. In order to debug things, I would suggest you start with collecting metrics and e.g write it out to csv by using the write_scv plugin. that way we could narrow down the issue to some component (or exclude components) from the list.

**Comment by Alan-Lee-JP** [comment]
Hi Runge, Thank you for your reply. Let us get back to you tomorrow on this, our engineer is on leave today.

**Comment by bacchus21** [comment]
Setting storerates as it is resolved the issue. This issue can be closed.

**Comment by mrunge** [comment]
thank you for the feedback.
