### ISSUE TITLE
DBI plugin can't be build for el9

### ISSUE THREAD

**Issue by Rohlik** [collectd/collectd#4067]
*   Version of collectd: latest
*   Operating system / distribution: Centos 9 Stream

## Expected behavior

Collectd DBI RPM package can be created.

## Actual behavior

RPM package of Collectd DBI plugin cannot be build as there is missing build [dependencies](https://src.fedoraproject.org/rpms/collectd/blob/rawhide/f/collectd.spec#_139
) `libdbi-devel` in upstream el9 EPEL repository and there is [no plan](https://bugzilla.redhat.com/show_bug.cgi?id=2149985#c1) to add it there 😢.
## Steps to reproduce

*   Try build this SPEC file https://src.fedoraproject.org/rpms/collectd/blob/rawhide/f/collectd.spec

**Comment by mrunge** [comment]
see https://github.com/collectd/collectd/issues/4068
