### ISSUE TITLE
collectd-iptables cannot be build for el9

### ISSUE THREAD

**Issue by Rohlik** [collectd/collectd#4068]
*   Version of collectd: 5.9.2
*   Operating system / distribution: Centos 9 Stream

## Expected behavior

collectd-iptables RPM package can be build.

## Actual behavior

`collectd-iptables` package cannot be build as el9 package `iptables-devel` doesn't provide `pkgconfig(libiptc)` which is needed during the build and was included in el8. Even with `--without-libiptc` build is crashing with dependency error:
> iptables  . . . . . . no (dependency error)

## Steps to reproduce

*   Try build collectd-iptables RPM package for el9

**Comment by mrunge** [comment]
IPtables is more or less dead. The plugin should be migrated to nftables (and/or better renamed to nftables)
