### ISSUE TITLE
build rpm with src package failed

### ISSUE THREAD

**Issue by lremember** [collectd/collectd#4071]
*   Version of collectd: collectd-5.9.0-5.el8.src.rpm
*   Operating system / distribution: openeuler
*   Kernel version (if applicable): 5.10.0-60.18.0.50.oe2203.aarch64

When I build collectd rpm with src rpm, But some failed. The error as follows:

`
Configuration:
  Build:
    Platform  . . . . . . Linux
    Compiler vendor . . . gnu
    CC  . . . . . . . . . gcc
    CFLAGS  . . . . . . . -Wall -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/generic-hardened-cc1 -fasynchronous-unwind-tables -fstack-clash-protection
    CXXFLAGS  . . . . . . -Wall -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/generic-hardened-cc1 -fasynchronous-unwind-tables -fstack-clash-protection -fexceptions
    CPP . . . . . . . . . gcc -E
    CPPFLAGS  . . . . . . 
    GRPC_CPP_PLUGIN . . . 
    LD  . . . . . . . . . /usr/bin/ld
    LDFLAGS . . . . . . . -Wl,-z,relro   -Wl,-z,now -specs=/usr/lib/rpm/generic-hardened-ld
    PROTOC  . . . . . . . /usr/bin/protoc
    YACC  . . . . . . . . bison -y
    YFLAGS  . . . . . . . 

  Libraries:
    intel mic . . . . . . no (MicAccessApi not found)
    libaquaero5 . . . . . no (libaquaero5.h not found)
    libatasmart . . . . . yes
    libcurl . . . . . . . yes
    libdbi  . . . . . . . yes
    libdpdk . . . . . . . no (rte_config.h not found)
    libesmtp  . . . . . . no (libesmtp.h not found)
    libganglia  . . . . . no (gm_protocol.h not found)
    libgcrypt . . . . . . yes
    libgps  . . . . . . . no (gps.h not found)
    libgrpc++ . . . . . . no (pkg-config could not find libgrpc++)
    libhiredis  . . . . . no (hiredis.h not found)
    libi2c-dev  . . . . . no (symbol i2c_smbus_read_i2c_block_data not found - have you installed libi2c-dev ?)
    libiokit  . . . . . . no
    libiptc . . . . . . . yes
    libjevents  . . . . . no (jevents.h not found)
    libjvm  . . . . . . . no (jar not found)
    libkstat  . . . . . . no (Solaris only)
    libkvm  . . . . . . . no
    libldap . . . . . . . yes
    liblua  . . . . . . . yes
    liblvm2app  . . . . . no (lvm2app.h not found)
    libmemcached  . . . . yes
    libmicrohttpd . . . . yes
    libmnl  . . . . . . . yes
    libmodbus . . . . . . no (pkg-config doesn't know libmodbus)
    libmongoc . . . . . . yes
    libmosquitto  . . . . no (mosquitto.h not found)
    libmysql  . . . . . . yes
    libnetapp . . . . . . no (netapp_api.h not found)
    libnetsnmp  . . . . . yes
    libnetsnmpagent . . . yes
    libnotify . . . . . . yes
    libnvidia-ml  . . . . no
    libopenipmi . . . . . yes
    liboping  . . . . . . no (oping.h not found)
    libowcapi . . . . . . no (owcapi.h not found)
    libpcap . . . . . . . yes
    libperfstat . . . . . no (AIX only)
    libperl . . . . . . . yes (version 5.34.0)
    libpq . . . . . . . . yes
    libpqos . . . . . . . no (pqos.h not found)
    libprotobuf . . . . . no (libprotobuf not found)
    libprotobuf-c . . . . yes
    libpython . . . . . . yes
    libqpid-proton .  . . no (proton/proactor.h not found)
    librabbitmq . . . . . yes
    libriemann-client . . yes
    librdkafka  . . . . . yes
    librouteros . . . . . no (routeros_api.h not found)
    librrd  . . . . . . . yes
    libsensors  . . . . . yes
    libsigrok   . . . . . no (pkg-config could not find libsigrok)
    libssl  . . . . . . . yes
    libstatgrab . . . . . no (pkg-config doesn't know libstatgrab)
    libtokyotyrant  . . . no (tcrdb.h not found)
    libudev . . . . . . . yes
    libupsclient  . . . . no (pkg-config doesn't know libupsclient)
    libvarnish  . . . . . yes
    libvirt . . . . . . . yes
    libxenctrl  . . . . . no (xenctrl.h not found)
    libxml2 . . . . . . . yes
    libxmms . . . . . . . no
    libyajl . . . . . . . yes
    oracle  . . . . . . . no (ORACLE_HOME is not set)
    protobuf-c  . . . . . yes
    protoc 3  . . . . . . yes

  Features:
    daemon mode . . . . . yes
    debug . . . . . . . . no

  Bindings:
    perl  . . . . . . . . yes (INSTALLDIRS=vendor)

  Modules:
    aggregation . . . . . yes
    amqp    . . . . . . . yes
    amqp1   . . . . . . . no (disabled on command line)
    apache  . . . . . . . yes
    apcups  . . . . . . . yes
    apple_sensors . . . . no (disabled on command line)
    aquaero . . . . . . . no (disabled on command line)
    ascent  . . . . . . . yes
    barometer . . . . . . no (disabled on command line)
    battery . . . . . . . yes
    bind  . . . . . . . . yes
    ceph  . . . . . . . . yes
    cgroups . . . . . . . yes
    chrony. . . . . . . . yes
    conntrack . . . . . . yes
    contextswitch . . . . yes
    cpu . . . . . . . . . yes
    cpufreq . . . . . . . yes
    cpusleep  . . . . . . yes
    csv . . . . . . . . . yes
    curl  . . . . . . . . yes
    curl_json . . . . . . yes
    curl_xml  . . . . . . yes
    dbi . . . . . . . . . yes
    df  . . . . . . . . . yes
    disk  . . . . . . . . yes
    dns . . . . . . . . . yes
    dpdkevents. . . . . . no (disabled on command line)
    dpdkstat  . . . . . . no (disabled on command line)
    drbd  . . . . . . . . yes
    email . . . . . . . . yes
    entropy . . . . . . . yes
    ethstat . . . . . . . yes
    exec  . . . . . . . . yes
    fhcount . . . . . . . yes
    filecount . . . . . . yes
    fscache . . . . . . . yes
    gmond . . . . . . . . no (disabled on command line)
    gps . . . . . . . . . no (disabled on command line)
    gpu_nvidia  . . . . . no (disabled on command line)
    grpc  . . . . . . . . no (disabled on command line)
    hddtemp . . . . . . . yes
    hugepages . . . . . . yes
    intel_pmu . . . . . . no (disabled on command line)
    intel_rdt . . . . . . no (disabled on command line)
    interface . . . . . . yes
    ipc . . . . . . . . . yes
    ipmi  . . . . . . . . yes
    iptables  . . . . . . yes
    ipvs  . . . . . . . . yes
    irq . . . . . . . . . yes
    java  . . . . . . . . no (jar not found) (dependency error)
    load  . . . . . . . . yes
    logfile . . . . . . . yes
    log_logstash  . . . . yes
    lpar  . . . . . . . . no (disabled on command line)
    lua . . . . . . . . . yes
    lvm . . . . . . . . . no (disabled on command line)
    madwifi . . . . . . . yes
    match_empty_counter . yes
    match_hashed  . . . . yes
    match_regex . . . . . yes
    match_timediff  . . . yes
    match_value . . . . . yes
    mbmon . . . . . . . . yes
    mcelog  . . . . . . . yes
    md  . . . . . . . . . yes
    memcachec . . . . . . yes
    memcached . . . . . . yes
    memory  . . . . . . . yes
    mic . . . . . . . . . no (disabled on command line)
    modbus  . . . . . . . no (disabled on command line)
    mqtt  . . . . . . . . no (disabled on command line)
    multimeter  . . . . . yes
    mysql . . . . . . . . yes
    netapp  . . . . . . . no (disabled on command line)
    netlink . . . . . . . yes
    network . . . . . . . yes
    nfs . . . . . . . . . yes
    nginx . . . . . . . . yes
    notify_desktop  . . . yes
    notify_email  . . . . no (disabled on command line)
    notify_nagios . . . . yes
    ntpd  . . . . . . . . yes
    numa  . . . . . . . . yes
    nut . . . . . . . . . no (disabled on command line)
    olsrd . . . . . . . . yes
    onewire . . . . . . . no (disabled on command line)
    openldap  . . . . . . yes
    openvpn . . . . . . . yes
    oracle  . . . . . . . no (disabled on command line)
    ovs_events  . . . . . yes
    ovs_stats . . . . . . yes
    pcie_errors . . . . . yes
    perl  . . . . . . . . yes
    pf  . . . . . . . . . no (disabled on command line)
    pinba . . . . . . . . yes
    ping  . . . . . . . . no (disabled on command line)
    postgresql  . . . . . yes
    powerdns  . . . . . . yes
    processes . . . . . . yes
    protocols . . . . . . yes
    python  . . . . . . . yes
    redis . . . . . . . . no (disabled on command line)
    routeros  . . . . . . no (disabled on command line)
    rrdcached . . . . . . yes
    rrdtool . . . . . . . yes
    sensors . . . . . . . yes
    serial  . . . . . . . yes
    sigrok  . . . . . . . no (disabled on command line)
    smart . . . . . . . . yes
    snmp  . . . . . . . . yes
    snmp_agent  . . . . . yes
    statsd  . . . . . . . yes
    swap  . . . . . . . . yes
    synproxy  . . . . . . yes
    syslog  . . . . . . . yes
    table . . . . . . . . yes
    tail_csv  . . . . . . yes
    tail  . . . . . . . . yes
    tape  . . . . . . . . no (disabled on command line)
    target_notification . yes
    target_replace  . . . yes
    target_scale  . . . . yes
    target_set  . . . . . yes
    target_v5upgrade  . . yes
    tcpconns  . . . . . . yes
    teamspeak2  . . . . . yes
    ted . . . . . . . . . yes
    thermal . . . . . . . yes
    threshold . . . . . . yes
    tokyotyrant . . . . . no (disabled on command line)
    turbostat . . . . . . no (disabled on command line)
    unixsock  . . . . . . yes
    uptime  . . . . . . . yes
    users . . . . . . . . yes
    uuid  . . . . . . . . yes
    varnish . . . . . . . yes
    virt  . . . . . . . . yes
    vmem  . . . . . . . . yes
    vserver . . . . . . . yes
    wireless  . . . . . . yes
    write_graphite  . . . yes
    write_http  . . . . . yes
    write_kafka . . . . . yes
    write_log . . . . . . yes
    write_mongodb . . . . yes
    write_prometheus. . . yes
    write_redis . . . . . no (disabled on command line)
    write_riemann . . . . yes
    write_sensu . . . . . yes
    write_stackdriver . . yes
    write_syslog . .  . . yes
    write_tsdb  . . . . . yes
    xencpu  . . . . . . . no (disabled on command line)
    xmms  . . . . . . . . no (disabled on command line)
    zfs_arc . . . . . . . yes
    zone  . . . . . . . . no (disabled on command line)
    zookeeper . . . . . . yes

configure: error: "Some plugins are missing dependencies - see the summary above for details"

`

**Comment by elfiesmelfie** [comment]
```
java . . . . . . . . no (jar not found) (dependency error)
```

This is the issue. You need to update the specfile to add ``--disable-plugin-java`` to the ``%build`` section. 
Or
Update a ``BuildRequires: ....`` to add the correct dependencies for the java plugin (i.e. the package that provides ``libjvm``)

If that doesn't help, I'll take a look in the new year.

**Comment by lremember** [comment]
Thanks for you help! I got it.
