### ISSUE TITLE
Data being sent in every 30 second gets reflected after 4-5 minute in Monitoring table

### ISSUE THREAD

**Issue by bacchus21** [collectd/collectd#4088]
*   Version of collectd: 5.10.0
*   Operating system / distribution: Red Hat Enterprise Linux(cpe:/o:redhat:enterprise_linux:7.9:GA:server)
*   Kernel version (if applicable): Linux 3.10.0-1160.80.1.el7.x86_64

## Expected behavior
Setting on collectd.conf
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
   <Host "XXXXGW2">
       Address "10.XX.XX.11"
       Version 2
       Community "XYZ111111"
       Collect "cisco_cpu"  "ifmib_if_octets32" "ifmib_if_octets64" "ifmib_if_packets32" "ifmib_if_packets64" "ifmib_if_errors32" "ifmib_if_errors64" "uptime"  "cisco_memory_used" "std_traffic"  "allocated_disk" "HW_SW_cpu_Used0" "HW_SW_cpu_Used1"
       Interval 30
           Timeout 10
           Retries 1
   </Host>
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

## Actual behavior

Even if the interval in collectd.conf is set as 30 seconds, actual interval on Azure LAW shows around 4 mins. 
First 
![first'](https://user-images.githubusercontent.com/57207755/216295828-5660d026-f159-49a6-b168-116f97baa6d0.png)

Second
![second'](https://user-images.githubusercontent.com/57207755/216295650-1196abc1-6f55-405a-946e-785d8c921be0.png)

## Steps to reproduce

*   step 1
*   step 2
*   step 3

If anyone has this kind of experiences/issues, please feel free to share. Highly appreciated.

**Comment by octo** [comment]
With the provided information I am unable to diagnose this issue. My recommendation would be to capture the network traffic, e.g. with tcpdump, to see whether collectd is slow to send requests, or if responses are slow.

Closing due to the age of the issue. Feel free to reopen with more information.
