### ISSUE TITLE
Is there any plans to have python3 as the default for collectd python plugin?

### ISSUE THREAD

**Issue by tkumark** [collectd/collectd#4097]
*   Version of collectd: 5.8.1
*   Operating system / distribution: amazon linux 2
*   Kernel version (if applicable):

## Expected behavior

Python plugin should use python 3 version as default instead of python 2. Python 2 has reached the end of life. Or there is be option to select interperter as part of the configuration. What ever search I have done it ask that we recompile collectd to accompdate python3 which is not desirable.

## Actual behavior

Python plugin uses python 2

**Comment by eero-t** [comment]
> * Version of collectd: 5.8.1

Collectd 5.8.1 is from **2018**.  You should consider upgrading.  Old plugin versions do not support newer (kernel and library version) interfaces.

> Python plugin should use python 3 version as default instead of python 2. Python 2 has reached the end of life.

It does default to Python3, already in v5.8: https://github.com/collectd/collectd/blob/collectd-5.8/configure.ac#L4632

If you do not want `collectd` to use Python 2, do not build it with **only** Python 2 present.  As you said, it's already EOL.

> Python plugin uses python 2
> ...
> Operating system / distribution: amazon linux 2

=> You should have filed this bug against your distro, not here.

**Comment by eero-t** [comment]
@mrunge I think this can be closed

**Comment by mrunge** [comment]
right, even in 2018, one could use python3 for the collectd python plugin.
