### ISSUE TITLE
The collectd_virt_if_errors_rx_total, collectd_virt_if_errors_tx_total metrics of Virt plugin are not collected

### ISSUE THREAD

**Issue by Saicharanreddyext** [collectd/collectd#4099]
*   Version of collectd: 5.12.0
*   Operating system / distribution: SUSE Linux Enterprise Server 15 SP3
*   Kernel version (if applicable): 

## Expected behavior
By loading Virt plugin into collectd.conf it should collect statistics(CPU, network interface and block device usage) about virtualized guests directly from the hypervisor on a host system.

(Description of the behavior / output that you expected)
Even though if there are 0 rx_errors/tx_errors on the vNIC interfaces it should collect the if_errors metrics and provide the output as it is giving for if_packets/if_dropped metrics.

Compute2:~ # virsh list --all
 Id   Name                State
-----------------------------------
 4    instance-0000000a   running
 5    instance-0000000d   running

Compute2:~ # virsh domiflist instance-0000000a
 Interface        Type        Source                            Model    MAC
--------------------------------------------------------------------------------------------
 vhu0478be01-ad   vhostuser   /run/openvswitch/vhu0478be01-ad   virtio   fa:16:3e:51:66:73

Compute2:~ # virsh domifstat instance-0000000a vhu0478be01-ad
vhu0478be01-ad rx_bytes 2845040
vhu0478be01-ad rx_packets 67689
vhu0478be01-ad rx_drop 0
vhu0478be01-ad tx_bytes 2497776
vhu0478be01-ad tx_packets 46822
vhu0478be01-ad tx_errs 0
vhu0478be01-ad tx_drop 0

Compute2:~ # virsh domiflist instance-0000000d
 Interface        Type        Source                            Model    MAC
--------------------------------------------------------------------------------------------
 vhu4d9ead1c-c1   vhostuser   /run/openvswitch/vhu4d9ead1c-c1   virtio   fa:16:3e:25:2b:8b

Compute2:~ # virsh domifstat instance-0000000d vhu4d9ead1c-c1
vhu4d9ead1c-c1 rx_bytes 2853680
vhu4d9ead1c-c1 rx_packets 67911
vhu4d9ead1c-c1 rx_drop 10
vhu4d9ead1c-c1 tx_bytes 2502518
vhu4d9ead1c-c1 tx_packets 46980
vhu4d9ead1c-c1 tx_errs 0
vhu4d9ead1c-c1 tx_drop 0

Compute2:~ # curl Compute2.k2.domain.se:9103 |grep virt_if_dropped |grep fa:16:3e

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  261k  100  261k    0     0  36.4M      0 --:--:-- --:--:-- --:--:-- 36.4M
collectd_virt_if_dropped_rx_total{virt="fa:16:3e:25:2b:8b",instance="5b82451f-5819-49c2-98c4-11f2d26706d3:f6e188f64dd348328d9e942a06298da7"} 10 1678451019353
collectd_virt_if_dropped_rx_total{virt="fa:16:3e:51:66:73",instance="4c587f59-daa4-4f68-9cf0-173c79ed8899:f6e188f64dd348328d9e942a06298da7"} 0 1678451019362
collectd_virt_if_dropped_tx_total{virt="fa:16:3e:25:2b:8b",instance="5b82451f-5819-49c2-98c4-11f2d26706d3:f6e188f64dd348328d9e942a06298da7"} 0 1678451019353
collectd_virt_if_dropped_tx_total{virt="fa:16:3e:51:66:73",instance="4c587f59-daa4-4f68-9cf0-173c79ed8899:f6e188f64dd348328d9e942a06298da7"} 0 1678451019362

## Actual behavior

Compute2:~ # curl Compute2.k2.domain.se:9103 |grep virt_if_errors |grep fa:16:3e 

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  261k  100  261k    0     0  63.8M      0 --:--:-- --:--:-- --:--:-- 63.8M

The expected behaviour is if_error metric should collect the metrics similar to other Virt metrics(if_packets/if_dropped).

**Comment by Saicharanreddyext** [comment]
Could someone please help us on this issue.

**Comment by Saicharanreddyext** [comment]
Could someone assign and provide some solution to the issue mentioned.

**Comment by hzozo** [comment]
Can a solution be expected for this issue in the near future, next year or at all? I'd like to understand where this lands in your backlog.

**Comment by eero-t** [comment]
> Can a solution be expected for this issue in the near future, next year or at all? I'd like to understand where this lands in your backlog.

I'm not collectd developer, but I think it's unlikely unless somebody using this plugin contributes PR.  Virt plugin has CI breaking unit test issues on some distros that may need to be fixed first  (see https://github.com/collectd/collectd/issues/4018), but they've languished for a long time without a fix.

**Comment by mrunge** [comment]
@hzozo @Saicharanreddyext Let me be very blunt here: This is worked on by people on their private time. If you need a fix for this, please pay someone to do it.
