### ISSUE TITLE
collectd 5.9.0 keep reporting the "virt plugin: Array index out of bounds: tag_index = 11/12"

### ISSUE THREAD

**Issue by jerryleon007** [collectd/collectd#4105]
*   Version of collectd: 5.9.0
*   Operating system / distribution: Kylin Linux Advanced Server release V10 (arch64)
*   Kernel version (if applicable): 4.19.90-17.ky10.aarch64 gcc version 7.3.0
*   Libvirtd version: 6.2.0

## Actual behavior
Use the syslog and info level, the information "virt plugin: Array index out of bounds: tag_index = 11" & "virt plugin: Array index out of bounds: tag_index = 12" consistently appears in the /var/log/message.

## Steps to reproduce

*   start collectd service, run the vms, the message pop up.

According to virDomainMemoryStatTags from https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainMemoryStatTags
the message is about HugePage, and check the HugePage info by using "cat /proc/meminfo |grep HugePage"
AnonHugePages:  11534336 kB
ShmemHugePages:        0 kB
HugePages_Total:      20
HugePages_Free:       20
HugePages_Rsvd:        0
HugePages_Surp:        0

**Comment by jerryleon007** [comment]
cat /proc/meminfo |grep Huge
AnonHugePages:         0 kB
ShmemHugePages:        0 kB
HugePages_Total:      20
HugePages_Free:       20
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:     524288 kB
Hugetlb:        10485760 kB

**Comment by eero-t** [comment]
You need this change: https://github.com/collectd/collectd/pull/3948

Which is in collectd "main", v5.11 & v5.12 (bugfix), and v5.13 (next) branches.   There's no release with it yet though. 

@mrunge, any comments on when there would be new bugfix release for the old versions, or a new release?

**Comment by mrunge** [comment]
I have seen distributors cherry-picking patches from newer collectd releases. At this point, I would not bother with backporting and releasing a new collectd 5.9 version. When 5.9 was released, libvirt 6.2 was not a thing.

Ideally we'd sync the main branch with the current 5.13 branch and release the main branch as 5.13 in not so distant future.

**Comment by eero-t** [comment]
Ok, so this can be closed once there's a new release with the fix.  Any idea of ETA for the next release?

**Comment by mrunge** [comment]
Ugh, already 3 1/2 months later, and it slipped. I'll try to make it a priority
