### ISSUE TITLE
"uc_update: Value too old flood" in log

### ISSUE THREAD

**Issue by RubberCthulhu** [collectd/collectd#4119]
*   Version of collectd: 5.12.0
*   Operating system / distribution: Ubuntu 22.04
*   Kernel version (if applicable):

## Expected behavior

We have a huge number of metrics collected per second in our software and it pushes them to collectd via unixsock plugin. So each "push" includes 10 per-second values for each metric. Values are sent in order from the erliest epoch to the last. I expect that collectd will just take the PUTVAL commands and route values to an appropriate plugin.

## Actual behavior

collectd takes PUTVAL commands and send values to appropriate plugin, however it writes a lot of messages to the log:
`Jun 05 07:26:41 collectd[3859]: uc_update: Value too old: name = hostname/plugin-name/if_rx_octets; value time = 1685949992.000; last cache update = 1685950000.000;`

I tried to send metric values in both single
PUTVAL "<id>/if_rx_octets" interval=10 1685945973:281000 1685945974:562000 1685945975:562000 1685945976:843000 1685945977:843000 1685945978:843000 1685945979:843000 1685945980:843000

and multiple putval commands
PUTVAL "<id>/if_rx_octets" interval=1 1685945973:281000
PUTVAL "<id>/if_rx_octets" interval=1 1685945974:562000
PUTVAL "<id>/if_rx_octets" interval=1 1685945975:562000
PUTVAL "<id>/if_rx_octets" interval=1 1685945976:843000
PUTVAL "<id>/if_rx_octets" interval=1 1685945977:843000
PUTVAL "<id>/if_rx_octets" interval=1 1685945978:843000
PUTVAL "<id>/if_rx_octets" interval=1 1685945979:843000
PUTVAL "<id>/if_rx_octets" interval=1 1685945980:843000

and in both cases we face a flood of "Value too old" log messages which costs us a lot of disk space.
The only way I found to avoid the warnings is to send a single value each second.

Do I use putval commands correctly? Why are warnings happening though the points are ordered by the epoch? Is this behavior a bug? Is there a way to avoid "Value too old" warnings? 

## Steps to reproduce

*   Send multiple values in a single or multiple putval commands at once.

**Comment by eero-t** [comment]
@mrunge ?

**Comment by octo** [comment]
I have been unable to reproduce this issue. Sending metrics via the *unixsock plugin* every second did not produce any duplicates.

According to the message, there is an 8 second difference between the metric in the cache and the new metric. For metrics collected every second this is a huge time difference. The timestamp does not have any decimal places. These things considered, I think the most likely cause is that the same script was running twice.

With the provided details it is not possible for me to investigate other plugins that might create these duplicate metrics.

If the problem persists, please re-open and provide more information.
