### ISSUE TITLE
Plugin hddtemp not working under Debian Bookworm

### ISSUE THREAD

**Issue by danielkr123** [collectd/collectd#4147]
*   Version of collectd: 5.12.0
*   Operating system / distribution: Debian 12 (bookworm)
*   Kernel version (if applicable): 6.1.0-13-amd64

## Expected behavior

- hddtemp is installed on my system and works (querying the temperature of the hdd's via `hddtemp /dev/sd?` or `telnet localhost 7634` returns the HDD temperatures)

- I enable the hddtemp plugin in /etc/collectd/collectd.conf by:
  - Uncommenting `LoadPlugin hddtemp`
  - Configuring the plugin:
```
  <Plugin hddtemp>
        Host "127.0.0.1"
        Port 7634
  </Plugin>
```
- Collectd should now query the HDD temperatures

## Actual behavior

- After enabling the hddtemp plugin as described above, I restart the collectd service: `systemctl restart collectd.service`
  Output:
```
  Job for collectd.service failed because the control process exited with error code.
  See "systemctl status collectd.service" and "journalctl -xeu collectd.service" for details.
```

- Looking into the details: `journalctl -xeu collectd.service`
  Output:
```
  (...)
  Nov 05 00:34:19 server collectd[3169677]: plugin_load: Could not find plugin "hddtemp" in /usr/lib/collectd
  (...)
  There is configuration for the `hddtemp' plugin, but the plugin isn't loaded. Please check your configuration.
```

- **Apparently, the hddtemp plugin is not included in Debian Bookworm**
  See also this post from Dec. 2021: https://groups.google.com/g/linux.debian.bugs.dist/c/PqwmLJXx6as

**Comment by octo** [comment]
This is working as intended, see [debian#1001954](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1001954). The [SMART plugin](https://github.com/collectd/collectd/wiki/Plugin-SMART) also reports temperature and may be a good replacement for you.
