### ISSUE TITLE
collectd tells the init system it's ready before it actually is

### ISSUE THREAD

**Issue by josephcsible** [collectd/collectd#4152]
*   Version of collectd: Git cfdfe4a
*   Operating system / distribution: Debian bookworm
*   Kernel version (if applicable): N/A

## Expected behavior

collectd should notify upstart or systemd that it's ready after `do_init` is finished, here: https://github.com/collectd/collectd/blob/cfdfe4aa3f6dae65d9b7c9265993c74610d85c62/src/daemon/collectd.c#L426

## Actual behavior

collectd notifies upstart or systemd that it's ready at the beginning of `main`, well before `do_init`, here: https://github.com/collectd/collectd/blob/cfdfe4aa3f6dae65d9b7c9265993c74610d85c62/src/daemon/cmd.c#L183

## Steps to reproduce

* Start collectd with upstart or systemd
* Immediately after, spike the CPU for a few milliseconds
* Observe that collectd didn't notice the CPU usage

**Comment by octo** [comment]
Thanks for reporting this @josephcsible! I have a patch for this in #4164. Do you have the means to test it?
