### ISSUE TITLE
statsd plugin: retain dots in metric names

### ISSUE THREAD

**Issue by rolandkool** [collectd/collectd#419]
The metrics that are usually pushed to statsd contain a lot of dots to create a nice hierarchy in Graphite.
However, when using the statsd plugin in collectd, the write_graphite translates all dots to underscores. This causes you to loose your hierarchy in Graphite.
A workaround is to change the EscapeChar parameter from underscore to dot, but perhaps there is a better way to keep the dots in the metrics name? This will also benefit tools like JCollect.

**Comment by zerthimon** [comment]
+1

**Comment by dlmarion** [comment]
+1, two years old. wow.

**Comment by alex-mercer** [comment]
+1

**Comment by axos88** [comment]
+1

**Comment by kan-quixey** [comment]
+1

**Comment by IgnasD** [comment]
+1

**Comment by jimleroyer** [comment]
+1

**Comment by zerthimon** [comment]
Just ping....
Can we have this implemented in 5.7 ?

**Comment by octo** [comment]
Quick show of hands (thumbs up/down): should a *PreserveSeparator* option keep dots in the hostname too (thumbs up) or should the hostname be exempt (thumbs down)?
