### ISSUE TITLE
Document the “Write StackDriver” plugin

### ISSUE THREAD

**Issue by FranklinYu** [collectd/collectd#4193]
As of now, the only documentation is [the Wiki](https://github.com/collectd/collectd/wiki/Plugin-Write-Stackdriver), which misses many options. The default configuration has some more information:

https://github.com/collectd/collectd/blob/3a282cc4f430640dcdab197b1bb2cfee9c881cb6/src/collectd.conf.in#L2109-L2117

However, it still doesn’t explain what is the Email and Resource. In addition, if the Resource has a label `project_id`, how is that different from Project?

This plugin is also missing from [`collectd.conf(5)`](https://collectd.org/documentation/manpages/collectd.conf.5.shtml). I’d highly appreciate if we can have more documentation about this.

That said, thank you for creating collectd.

**Comment by octo** [comment]
Hi @FranklinYu, thanks for raising this.

The plugin is documented in *collectd.conf(5)*, but the HTML export on the homepage is dated. This will soon be replaced with a new page, including an export of the manpage: https://collectd.github.io/documentation/manpages/collectd.conf.html#plugin-write_stackdriver

The `Project` and `Email` settings specify the service account used for authentication. In most cases you'll want to only set `CredentialFile` which also contains this information.

The `Resource` blocks specifies a "[Monitored Resource](https://cloud.google.com/monitoring/api/resources)". The [global](https://cloud.google.com/monitoring/api/resources#tag_global) resource expects one label called "project_id".

I have opened up the wiki so you should be able to improve the plugin page as needed.
