### ISSUE TITLE
collectd-6.0 regression, logs "uc_update" errors

### ISSUE THREAD

**Issue by eero-t** [collectd/collectd#4200]
*   Version of collectd: `collectd-6.0` branch HEAD
*   Operating system / distribution: Ubuntu 22.04

## Expected behavior

Like with earlier `collectd-6.0` code, no errors logged from collectd with `gpu_sysman` plugin input being queried through `write_prometheus` plugin HTTP endpoint.

## Actual behavior

Collectd logs errors like this:
```
uc_update: Value too old: name = collectd_gpu_sysman_frequency_mhz{resource:host.name="5e22ae14c686",resource:service.name="unknown_service:collectd",dev_file="card2",function="max",location="gpu",pci_bdf="0000:93:00.0",type="request"}; value time = 1703013964.867; last cache update = 1703013964.867;
uc_update: uc_update_metric failed: Error #-1; Additionally, strerror_r failed.
```

### Notes

I'm not sure when this regressed.  Last time I'm sure it worked, was after this fix: https://github.com/collectd/collectd/pull/4103

For some reason I get these only for frequency metric, not for the others.  Frequency is the first metric submitted on each read cycle.

If I increase interval to >1s, this log spam seems to go away.

This is the config I'm using:
```
Interval 10

LoadPlugin write_prometheus
<LoadPlugin gpu_sysman>
  Interval 0.5
</LoadPlugin>

<Plugin write_prometheus>
  Port 9103
</Plugin>

<Plugin gpu_sysman>
  Samples 8
</Plugin>
```

But getting enough metrics requires discrete Intel GPU, and Sysman plugin to be built & running with latest kernel + distro user-space drivers, or drivers installed according to instructions here (for LTS distros): https://dgpu-docs.intel.com/

**Comment by eero-t** [comment]
@octo Any comments on these `uc_update` issues (previously fixed for 6.x in https://github.com/collectd/collectd/pull/4103)?

Issue https://github.com/collectd/collectd/issues/4119 for 5.x is potentially related.

**Comment by eero-t** [comment]
@octo Thanks, you found it really fast!  (From my own code which was embarrassing, but I guess one is somewhat blind to own code)

I'll close this and updated the title as it was not in collectd core code.

**Comment by octo** [comment]
You're welcome :) Such bugs are much easier to find with a fresh pair of eyes.

**Comment by eero-t** [comment]
This: `uc_update: uc_update_metric failed: Error #-1; Additionally, strerror_r failed.`

Seems to be due to` uc_update()` unconditionally calling `STRERROR()` on `uc_update_metric()` fails, although only positive error numbers are valid `errno` values, whereas return value in this case was `-1`.
