### ISSUE TITLE
v6 regression: resource labels break metrics reporting to Prometheus

### ISSUE THREAD

**Issue by eero-t** [collectd/collectd#4204]
*   Version of collectd: collectd v6 HEAD
*   Operating system / distribution: Ubuntu 22.04 LTS

## Expected behavior

Prometheus reports metrics from collectd.

## Actual behavior

No metrics with HEAD version, only with older v6 collectd versions.

## Steps to reproduce

See https://github.com/collectd/collectd/issues/4200.

## Notes

Resource labels use characters that are invalid for Prometheus data; double colon is invalid in label names, and dot is invalid both in metric and label names:
https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels

Querying collect directly provides metrics:
```
# HELP collectd_gpu_sysman_energy_ujoules_total Total energy consumption since boot (in microjoules)
# TYPE collectd_gpu_sysman_energy_ujoules_total counter
collectd_gpu_sysman_energy_ujoules_total{resource:host.name="collectd-gpu-plugin-ntgc9",resource:service.name="unknown_service:collectd",dev_file="card0",pci_bdf="0000:03:00.0",pci_dev="0x4905"} 2055559623779 1703086702571
collectd_gpu_sysman_energy_ujoules_total{resource:host.name="collectd-gpu-plugin-ntgc9",resource:service.name="unknown_service:collectd",dev_file="card1",pci_bdf="0000:0a:00.0",pci_dev="0x4905"} 1845199992736 1703086702573
...
```

But when I e.g. try to relabel resource labels in `serviceMonitor` config, Prometheus complains about resource labels being invalid:
```
level=info ts=2023-12-20T15:14:02.029Z caller=main.go:979 msg="Loading configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
level=error ts=2023-12-20T15:14:02.043Z caller=main.go:756 msg="Error reloading config" err="couldn't load configuration (--config.file=\"/etc/prometheus/config_out/prometheus.env.yaml\"): parsing YAML file /etc/prometheus/config_out/prometheus.env.yaml: \"resource:host.name\" is not a valid label name"
```

So I assume same to be reason also why metrics do not work as-is with resource labels (although there are no errors about that at default log level).

**Comment by eero-t** [comment]
Built `collectd` commit just before resource labels were added (488a1f58e05621213a0315556489dc601f62acf0), and Prometheus shows Sysman metrics fine with that => it's indeed resource labels that broke metrics exporting to Prometheus.

**Comment by eero-t** [comment]
https://github.com/collectd/collectd/pull/4206 fixed this => closing.

However, those resource labels only _duplicate_ the information _that Prometheus already adds to the metrics_ it gets from `write_prometheus` plugin.

**Comment by octo** [comment]
@eero-t Can you tell me more about the issues caused by the resource labels? Having duplicate data is not ideal.

**Comment by eero-t** [comment]
How current resource labels info matches to the labels already (automatically) added to metrics by Prometheus:
* Label value for the (k8s) pod name, is the same as for the hostname resource label, because hostname within containers (of a pod), **is** the pod name
* While kubernetes service name for the pod can differ from the resource label "service name", it's the one that's actually relevant to the users

Extra labels do not cause any immediate failures, but when they're added to _every_ metric in the cluster, and their values differ (between nodes) [1], they can bloat Prometheus memory usage noticeably, which *can* then fail (e.g. on collectd update) due to its container memory limits, or because node itself runs out of memory [2].

[1] https://prometheus.io/docs/practices/naming/#labels states following:
> CAUTION: Remember that every unique combination of key-value label pairs represents a new time series, which can dramatically increase the amount of data stored. Do not use labels to store dimensions with high cardinality (many different label values), such as user IDs, email addresses, or other unbounded sets of values.

[2] Which based on googling, does not seem to have been that uncommon for larger clusters.  After event like that, maintainer starts to prune the number of configured metrics & their labels, how frequently they're collected, and how long retained, if telemetry node RAM cannot be easily increased.

(That's one of the reasons why Sysman plugin has separate config option for each metric type, and output variant.)

**Comment by octo** [comment]
Thanks for the detail. Let's move the conversation to #4213
