### ISSUE TITLE
Disk plug-in failed to load and plug-in interface did not register for value uniquename

### ISSUE THREAD

**Issue by Kiba87** [collectd/collectd#4255]
Hi Team, 

Disk plug-in failed to load and plug-in interface did not register for value uniquename.

I got two issues while doing a RH7 to RH8 upgrade when installing collectd 5.9 on RH8 machine collectd failed to start with below error message. 

```
 collectd[47460]: ] plugin_load: plugin "df" successfully loaded.
collectd[47460] plugin_load: Could not find plugin "disk" in /usr/lib64/collectd

  Plugin `interface' did not register for value `UniqueName'.
 collectd[40670]: Error: Parsing the config file failed!
```

**Comment by eero-t** [comment]
Please file collectd packaging & upgrade issues against your distribution bug tracker, especially for such very old releases.

(Latest collectd stable version is 5.12, with new release hopefully coming out soon.)

**Comment by Kiba87** [comment]
Thanks

**Comment by eero-t** [comment]
Btw. Link to your distro ticket would be appreciated!

**Comment by octo** [comment]
As Eero mentioned: version 5.9 is ancient and no longer supported by us. If the problem persists with 5.12, please re-open with the new information.

**Comment by Kiba87** [comment]
I am not finding collectd 5.12 rpm for redhat 8...could you please share me the link.
