### ISSUE TITLE

Disk plug-in failed to load and plug-in interface did not register for value uniquename -- after upgraded to 5.12 we got the same issue

### ISSUE THREAD

**Issue by Kiba87** [collectd/collectd#4280]
Hi Team, 

Disk plug-in failed to load and plug-in interface did not register for value uniquename.

I got two issues while doing a RH7 to RH8 upgrade before we had collectd 5.9 on RH8 machine after the tech team suggested we upgraded to 5.12 on rh8 still we are getting same message for collectd.

```
 collectd[47460]: ] plugin_load: plugin "df" successfully loaded.
collectd[47460] plugin_load: Could not find plugin "disk" in /usr/lib64/collectd

  Plugin `interface' did not register for value `UniqueName'.
 collectd[40670]: Error: Parsing the config file failed!
``

**Comment by eero-t** [comment]
These are both errors in your distro setup, not `collectd` issues.

> Disk plug-in failed to load and
> ...
> `collectd[47460] plugin_load: Could not find plugin "disk" in /usr/lib64/collectd`

Most of the collectd plugins seem to be in separate packages on RHEL, including disk one: https://koji.fedoraproject.org/koji/buildinfo?buildID=1411042

I.e. you need to install collectd disk plugin package.

If this issue happened on upgrade, i.e. your distro had split plugins to separate packages in newer distro version, but did not handle that transition properly on distro-upgrade, you should file a bug against that version of your distro (of dist-upgrade not pulling in split-out plugin packages when collectd package is upgraded).  @mrunge, any comments on this?

> plug-in interface did not register for value uniquename.
> ...
> ```
> Plugin `interface' did not register for value `UniqueName'.
> collectd[40670]: Error: Parsing the config file failed!
> ```

As the documentation states, `UniqueName` is specific to Solaris OS (`kstat` API), but you are running on RHEL OS: https://github.com/collectd/collectd/pull/1416/files

What's weird, is that it was added already in collect-5.6: https://github.com/collectd/collectd/releases/tag/collectd-5.6.0

And already then plugin either accepted the option name (if on Solaris OS), **or** gave a warning that collectd plugin was not compiled for Solaris (API).

Is your collectd interface plugin for older collectd version than v5.6???

**Comment by Kiba87** [comment]
Thanks, we have installed collectd-disk package.. what would be the configuration for rhel 8 on collectd conf file.. should we remove UniqueName?

  how can we check interface plugin version?

Current setup : 

<plugin interface>
     Interface "lo"
     IgnoredSelected true
     ReportInactive false
     UniqueName false
</plugin>

**Comment by eero-t** [comment]
Yes, you should remove `UniqueName` from interface plugin config section (as you're not using Solaris OS).

> Current setup

Valid plugin config values are listed in the `collectd` configuration manual.  RHEL RPM package should install docs matching your `collectd` version, but latest one on in git is probably also fine for `interface` plugin: https://github.com/collectd/collectd/blob/main/src/collectd.conf.pod#L4093

> how can we check interface plugin version?

Same as with any other system binary installed on your OS; ask the OS package manager.

(I've never used RHEL OS, or collectd `interface` plugin, but I guess you can start with `man rpm` and options for listing package info, verifying that files on disk match package checksums, and checking that your plugin package version matches collectd daemon package version.  If they do, check that daemon is actually using plugin file from the location listed by RPM, e.g. from `/proc/$(pidof collectd/maps` file, and not some random location.)

Closing the issue as it's about distro maintenance and not something that collectd project could fix.
