### ISSUE TITLE
Online documentation: add linkable anchors to headings

### ISSUE THREAD

**Issue by jaskij** [collectd/collectd#4297]
## Expected behavior

A colleague will be implementing statistics we can read with a generic plugin. I want to send him a link to the plugin's documentation so he can see if there is anything special he needs to do. It's not one of the plugins that has it's own page.

## Actual behavior

If there is an option to do it, I do not know how to do it. Iirc it was possible on the old wiki.

## Comments

A lot of websites simply add anchors to headings. The first example that comes to mind is the [`systemd.unit` manual](https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html). Notice how when you mouse over any heading a small ¶ is displayed, and when you click on it, the address in your browser is changed to include the anchor for that heading. If you don't care about the "appear only on mouseover" effect, this can be done in pure HTML, with no JS.

**Comment by hdost** [comment]
Should this be in https://github.com/collectd/collectd.github.io?

**Comment by jaskij** [comment]
Probably, I wasn't aware the documentation is maintained in a separate repository, thank you.
