### ISSUE TITLE
Please use pkg-config instead of libgcrypt-config to locate libgcrypt

### ISSUE THREAD

**Issue by bzed** [collectd/collectd#4315]
Forwarded from https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1070905

Please switch from using libgcrypt-config to pkg-config to locate
libgcrypt. libgcrypt-config will be dropped in the next libgcrypt major
release.

(Please do not switch from collectd's handwritten detection code to
AM_PATH_LIBGCRYPT() unless you invoke AM_PATH_GPG_ERROR() first. The
former currently requires the latter to work without libgcrypt-config.
Just go for pkg-config instead.)

**Comment by eero-t** [comment]
Could you make also a PR for that?

**Comment by bzed** [comment]
> Could you make also a PR for that?

no.

**Comment by xnox** [comment]
Duplicate of https://github.com/collectd/collectd/issues/4310

**Comment by eero-t** [comment]
> Duplicate of #4310

Thanks, closing this one (both were reported by @bzed).
