### ISSUE TITLE
Some build generated files shipped in release archives

### ISSUE THREAD

**Issue by mohammadshamma** [collectd/collectd#439]
I have downloaded collectd verison 5.4 from the following location: http://collectd.org/files/collectd-5.4.0.tar.bz2. I noticed there are some files included in the release that are generated by the build process. These files need not be in the release file.

The build generated files are:

src/collectd-email.5
src/collectd-exec.5
src/collectd-java.5
src/collectd-nagios.1
src/collectd-perl.5
src/collectd-python.5
src/collectd-snmp.5
src/collectd-unixsock.5
src/collectd.1
src/collectd.conf.5
src/collectdmon.1
src/types.db.5

**Comment by rubenk** [comment]
We intentionally ship the generated manpages. We do this so you don't have to have pod2man installed.
