### ISSUE TITLE
pinba plugin enabled on incomplete autoconf check

### ISSUE THREAD

**Issue by biot** [collectd/collectd#442]
The pinba plugin apparently requires protobuf support, and is automatically compiled if this is available.

However the autoconf check for this is broken: it really needs both protoc-c and the protobuf headers, but in fact the check succeeds on protoc-c alone. So the -dev or -devel package not being installed will still enable pinba support, and the compile fails.

**Comment by rubenk** [comment]
I think I fixed this up a while ago (perhaps 22f79bfb91033789ac305f261475f527fe3d8c19). Can you please check if this is still an issue?

**Comment by rubenk** [comment]
This works correctly now on current master.
