### ISSUE TITLE
When being run --with-librrd option, configure script fails to determine if rrd supports threads

### ISSUE THREAD

**Issue by young-druid** [collectd/collectd#447]
INPUT:
I got sources from here:
http://collectd.org/files/collectd-5.4.0.tar.gz

I ran the following script:
```
./configure --disable-all-plugins --enable-rrdtool --with-librrd=<path to librrd>
```

OUTPUT:
```
libpthread  . . . . . yes
librrd  . . . . . . . yes (warning: librrd is not thread-safe)
```
POSSIBLE SOLUTION:
I suppose in configure.in the following code should be changed from
```
[with_librrd="yes"
	 librrd_ldflags="$librrd_ldflags -lrrd_th -lm"
	],
```
to
```
[with_librrd="yes"
	 librrd_ldflags="$librrd_ldflags -pthread -lrrd_th -lm"
	],
```
But it is probably valid only for Debian (or Linux) but not for Solaris.

**Comment by rubenk** [comment]
Hi,

What platform was this on?
Does this still happen with current master?

**Comment by rubenk** [comment]
Closing due to lack of feedback.
