### ISSUE TITLE
Problem with writing to rrdcached

### ISSUE THREAD

**Issue by rubenk** [collectd/collectd#450]
My collectd log on my collectd server is full with:
[2013-10-08 12:49:40] rrdcached plugin: rrdc_update (/collectd/rrd/gate2b.tilaa.nl/vmem/vmpage_number-page_table_pages.rrd, [1381229318:892.000000], 1) failed with status -1.

I checked with the latest Wireshark that packets from my clients are arriving from the network in the right order, and that the high-precision timestamps in the packets are in the right order too.

Looking at the timestamp from the logs, the failing update is written to the rrdcached socket at 12:48:38

[ruben@evbu001 ~]$ date -d '@1381229318'
Tue Oct  8 12:48:38 CEST 2013

I strace'd rrdcached simultaneously, and see that it receives 2 updates in the wrong order:

12420 12:49:40.635721 read(24, "update /collectd/rrd/gate2b.tilaa.nl/vmem/vmpage_number-page_table_pages.rrd 1381229378:892.000000\n", 8192) = 99
12420 12:49:40.635797 write(24, "0 errors, enqueued 1 value(s).\n", 31) = 31
12420 12:49:40.636503 read(24, "update /collectd/rrd/gate2b.tilaa.nl/vmem/vmpage_number-page_table_pages.rrd 1381229318:892.000000\n", 8192) = 99
12420 12:49:40.636578 write(24, "-1 illegal attempt to update using time 1381229318.000000 when last update time is 1381229378.000000"..., 127) = 127
so rrdtool rejects the second one, which has a timestamp before the first one.

(By the way, I'm not sure if this is an issue in collectd or in rrdtool, but collectd only logs the status -1, and the error message is lost somewhere along the way. This made debugging quite hard.)

My uneducated guess is that the default 5 write threads are racing to write to the socket somehow. To test my hypothesis, I set WriteThreads to 1, and my error log is now empty.

Let me know if you need more details.

**Comment by octo** [comment]
Closing this in favor of #987
