### ISSUE TITLE
Help compiling with netapp plugin

### ISSUE THREAD

**Issue by johwes** [collectd/collectd#455]
I'm sorry to post this here, but didnt know where to ask.
I'm trying to compile the netapp plugin with collectd 5.4.0 but i cant get the configure script to accept my dependencies.

I've followed the documentation of the netapp sdk and am providing the files that netapp says i should. The following files.

libnetapp.so
libadt.so
libxml.so
They also require crypto/ssl libs with the following symlinks created.
ln -s libcrypto.so libcrypto.so.1.0.1
ln -s libssl.so libssl.so.1.0.1

I run the configure script like this:
configure LIBNETAPP_LIBS=/usr/lib64/netapp --with-libnetapp=./include/netapp_api.h --enable-netapp
Where i have copied the .so files + symlinks into the /usr/lib64/netapp directory and i've copied the entire include directory from the sdk

However my output (cut lines for netapp only)
    libnetapp . . . . . . ./include/netapp_api.h
    netapp  . . . . . . . no (dependency error)

If i remove the --enable-netapp the configure runs fine.
Any tips from anyone? I'm doing something wrong, but what?

Regards
/J

**Comment by VBSingh** [comment]
Hello Johwes,

I am in the similar situation as yours and i am glad that you solved it. Can you please expain your directory structure as i am not able to compile my code. 

Thanks
Bhushan

**Comment by johwes** [comment]
I'm sorry i left the client i did this for 2 years ago so i no longer remeber.
