### ISSUE TITLE
Memcached plugin doesn't resolve hostnames anymore

### ISSUE THREAD

**Issue by josqu4red** [collectd/collectd#458]
When upgrading from 5.1 to 5.4, memcached plugin stopped doing name resolution.
With such config:
```
LoadPlugin "memcached"

<Plugin memcached>
  <Instance "port_11211">
    Host "10.11.11.11"
    Port "11211"
  </Instance>
</Plugin>
```
* on 5.1, rrds were stored under <rrd_dir>/hostname/memcached-port_11211/
* after upgrade to 5.4, rrds are stored under <rrd_dir>/10.11.11.11/memcached-port_11211/

FQDNLookup is still set to true.

We already had multi-instance support in 5.1 since the patch comes from us.

**Comment by octo** [comment]
With the new configuration syntax, e.g.

```
<Plugin memcached>
  <Instance "port_11211">
    Host "10.11.11.11"
    Port "11211"
  </Instance>
</Plugin>
```

"10.11.11.11" will be used as the hostname of metrics. This is *working as intended*. Please voice your opinion in #905 if you require more control over the hostname being used.

Best regards,
—octo
