### ISSUE TITLE
statsd plugin: please be more flexible with parsing

### ISSUE THREAD

**Issue by its-not-a-bug-its-a-feature** [collectd/collectd#461]
With version 5.4 , I see many messages from my test setup saying that statsd messages cannot be parsed : 

<pre>
Nov  5 18:45:20 hostname collectd[8236]: statsd plugin: Unable to parse line: "object-server.REPLICATE.timing:0.399112701416|ms|@0.1"
Nov  5 18:45:20 hostname collectd[8236]: statsd plugin: Unable to parse line: "object-server.REPLICATE.timing:0.399112701416|ms|@0.1"
Nov  5 18:45:20 hostname collectd[8236]: statsd plugin: Unable to parse line: "object-server.REPLICATE.timing:0.375986099243|ms|@0.1"
Nov  5 18:45:20 hostnam collectd[8236]: statsd plugin: Unable to parse line: "object-server.REPLICATE.timing:0.375986099243|ms|@0.1"
</pre>

I understand that the extra field ( after  the type field "ms") are unnecessary for timing messages.

Within the plugin statsd.c , in statsd_parse_line() we return -1 if there is extra data for non-counters:

```c
  /* extra is only valid for counters */
  if (extra != NULL)
    return (-1);
```

Other statsd parsers would allow this, would you mind please making your code more flexible - maybe just removing the two lines above ?

Thanks

**Comment by mfournier** [comment]
This was fixed in collectd 5.4.2. Closing. Thanks to everyone for reporting and tracking this down !
