### ISSUE TITLE
Complete build options for Pthread API

### ISSUE THREAD

**Issue by elfring** [collectd/collectd#470]
Would you like to add the configuration script "[AX_PTHREAD](http://www.gnu.org/software/autoconf-archive/ax_pthread.html "How to build C programs using POSIX threads?")" to [your build specification](https://github.com/collectd/collectd/blob/23a9e650caa712012d696de3d64dfe2a2517e268/configure.in#L3350 "configuration checks")?

**Comment by rubenk** [comment]
@elfring could you comment on why we should do that? We do our own pthread detection. If we do this wrong, I'd love to know about it.

**Comment by elfring** [comment]
* How do you think about to reuse the checks from the GNU Autoconf Archive generally?
* Would you like to specify any extensions that this software might need?

**Comment by rubenk** [comment]
As for your first question, it depends. If they fix actual issues I'm all for it, but in my experience the checks from the Autoconf Archive are not without bugs either.

I don't understand your second question. What extensions are you referring to?

**Comment by elfring** [comment]
Do you miss any checks that are performed by the collectd approach by the configuration script "AX_PTHREAD"?

**Comment by rubenk** [comment]
I haven't compared the two, but afaik our pthread detection works fine.

Please convince us as to why we should use the AX_PTHREAD macro and what actual issue this solves.

**Comment by elfring** [comment]
Would it make sense to combine both approaches?

**Comment by rubenk** [comment]
I don't understand what you mean with 'both approaches'. Please be more concrete in what you want to accomplish.

**Comment by elfring** [comment]
I propose just to integrate the configuration script "AX_PTHREAD" into the build process for the software "collectd".

**Comment by rubenk** [comment]
Yes, but why?

**Comment by elfring** [comment]
One reason is that this script might be better known just because it is a part of the GNU Autoconf Archive for a while.

**Comment by rubenk** [comment]
Just because it is in the autoconf archive it doesn't mean that it doesn't have bugs. I know from experience that it had it's share.

I'll ask one last time, what concrete issue are you seeing that this will solve?

**Comment by elfring** [comment]
I would generally appreciate if the checking for parallel programming interfaces will become safer and more widely used.
I imagine that it would be usual to move some autoconf code to a known software library.

**Comment by rubenk** [comment]
I appreciate your effort to do that, however, our current autoconf code has been tested and debugged extensively over the years. Switching to another library is not without its risks and costs, and unless these are offset by some measurable improvement I don't think we can justify this.
