### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [collectd/collectd#471]
I guess that a different program design will be needed for your signal handling functions.
* The variable "loop" should [use the data type "sig_atomic_t"](https://www.securecoding.cert.org/confluence/display/seccode/SIG31-C.+Do+not+access+shared+objects+in+signal+handlers "Do not access shared objects in signal handlers"). The use of the post-increment operator is questionable [in this context](https://github.com/collectd/collectd/blob/6d85a198dd90fb5af963ad847d9dbff7b8025c46/src/collectd.c#L62 "Correct 'loop' modification").
* A function like "[pthread_create](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_create.html "thread creation")" does not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/seccode/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers "Call only asynchronous-safe functions within signal handlers.").

**Comment by rubenk** [comment]
I think you're right and this can certainly be improved. Would you like to submit a PR?

**Comment by elfring** [comment]
Would you like to consider other software design options?
* [sigwaitinfo()](http://pubs.opengroup.org/onlinepubs/9699919799/functions/sigwaitinfo.html "wait for queued signals")
* [Self-pipe trick](http://cr.yp.to/docs/selfpipe.html "Use case description by Daniel J. Bernstein")
* [Signal-safe locks](http://locklessinc.com/articles/signalsafe_locks/ "lock-free algorithms")

**Comment by rubenk** [comment]
As long as they work on all platforms we support, and don't unnecessarily complicate the code.

**Comment by elfring** [comment]
Would it be better to keep this issue open until the affected implementation details will be fixed?

**Comment by rubenk** [comment]
Just as I explained in your other issues, no, that wouldn't be better.
