### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [collectd/collectd#472]
I have looked at a few source files for your current software. I have noticed that some checks for return codes are missing.

Would you like to add more error handling for return values from functions like the following?
- [pthread_mutex_init](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html "initialise a mutex") ⇒ [fbh_create](https://github.com/collectd/collectd/blob/9b022ebf40a1a49bedf5992e6542c1c0b6a62c13/src/utils_fbhash.c#L199)
- [fprintf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fprintf.html "print formatted output") ⇒ [pidfile_create](https://github.com/collectd/collectd/blob/6d85a198dd90fb5af963ad847d9dbff7b8025c46/src/collectd.c#L365)

**Comment by rubenk** [comment]
Of course, more error handling is always good :) Patches are always welcome.
I'll close this issue, please open individual PRs for any fixes you have.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.

Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by rubenk** [comment]
I don't think this is the place for discussing which software development model we should use. For that, IRC or our mailing list are more appropriate.

**Comment by elfring** [comment]
Would it be better to keep this issue open until the affected implementation details will be fixed?

How are the chances to clarify the different views more by other communication possibilities?

**Comment by rubenk** [comment]
I'm not trying to be rude, and appreciate your input, but as you might have noticed we have a lot of open issues already. We are also suffering a bit from lack of manpower these days. I'm not saying that the points you mention are not important, but I'm afraid this request will linger indefinitely without someone stepping up and doing the actual coding. In my opinion there's lots that can be done to improve the existing codebase before we even venture into the territory of aspect-oriented programming.

**Comment by elfring** [comment]
Would you like to delegate any software maintenance tasks to dedicated development tools?

**Comment by rubenk** [comment]
I have no idea what you're saying. Please be more specific.

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2FC.2B.2B "Tools for static code analysis") also for your software?

Do you find information sources like the following useful?
* Article "[A Reusable Aspect for Memory Allocation Checking](https://web.archive.org/web/20090808093257/http://research.msrg.utoronto.ca/ACC/Tutorial#A_Reusable_Aspect_for_Memory_All "AspectC Tutorial")"
* Document "[Aspect-Oriented Software Development - An Introduction](https://web.archive.org/web/20130512025224/http://www.info.ucl.ac.be/~jbrichau/courses/introductionToAOSD.pdf "AOSD")" by Johan Brichau and Theo D'Hondt
* Paper "[On Typesafe Aspect Implementations in C++](http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.125.2164 "AspectC++")" by Daniel Lohmann and Olaf Spinczyk

**Comment by rubenk** [comment]
We know what static source code analysis is, and we already use it. You can help this project by fixing or reporting actual bugs. Sending us links to software development papers is not helping, please stop wasting our time with this.

**Comment by elfring** [comment]
* Are you aware on how much aspect-oriented development could also help with improvements for this software?
* Would you like to filter source code so that appropriate reactions can be automatically connected to return values from various function calls?
