### ISSUE TITLE
Allow includes from within <Plugin> scope

### ISSUE THREAD

**Issue by jbergstroem** [collectd/collectd#476]
I'm checking in my collectd configs and would like to avoid including passwords (mysql, etc). A pretty common pattern is to include a .gitignore'd file, which will generate this error:

```
[2013-11-16 17:38:41] mysql plugin: Option `Include' not allowed here.
```

**Comment by jbergstroem** [comment]
Does anyone have suggestions to this? Pre-parser in the init scripts?

**Comment by zerthimon** [comment]
+1 to this request

**Comment by tokkee** [comment]
Would any of you be willing to suggest a patch? If we want it at all, it should be in the core imho and not in the init script. I'd think having a PR would be more likely to get feedback and I'm now slightly tending towards agreeing with the request ;-)

**Comment by octo** [comment]
If the tree is constructed (by scanning for and handling `Include` statements) before any branch is passed to the config callback of a plugin, I don't think plugins can notice.

I'd be happy to review a PR adding this feature.

**Comment by towolf** [comment]
I think this would also solve my chains problem from the mailing list. I could just include more rules within a chain.

https://mailman.verplant.org/pipermail/collectd/2017-October/007088.html

**Comment by octo** [comment]
Closing feature request due to inactivity. You can repeat `<Plugin "foo">` blocks in multiple files, which should allow you to work around this limitation with most plugins.
