### ISSUE TITLE
ntpd plugin sometimes returns NaN

### ISSUE THREAD

**Issue by zbuckholz** [collectd/collectd#509]
I am using collectd with the ntpd plugin to send metrics to logstash. Most of the time I get proper data, but randomly I will get a NaN value which causes logstash to crash.

I have already opened an issue with logstash, hopefully the logstash code can handle the exception better in the future.

Here is a link to the logstash issue that shows the verbose output:

https://logstash.jira.com/browse/LOGSTASH-1763

**Comment by mfournier** [comment]
See #1174 for arguments around NaN values.
