### ISSUE TITLE
Please update EPEL to Collectd 5.X release

### ISSUE THREAD

**Issue by tewner** [collectd/collectd#514]
Good morning, All!

Can you please update collectd in EPEL to a version which supports Graphite (at least 5.1)? 

Thank you for the great tool!
-Mike

**Comment by kiranos** [comment]
when will this be reconsidered? the graphite write plugin is pretty good and not available before 5.1

**Comment by aamerik** [comment]
def need 5.1 package in EPEL.

**Comment by Strekerud** [comment]
+1

**Comment by rubenk** [comment]
Sorry guys, not going to happen. You can't have a long term stable enterprise distro with the newest version of everything. FWIW I didn't make those rules, they're EPEL policy. If you disagree, feel free to discuss them on the epel mailing list, not here.

**Comment by Poil** [comment]
You can easily build the RPMs for EL5 via Mock on an EL6/EL7

But without the needed libraries you would not be able to build some of the newer Collectd plugins

Here is a backup of my build http://web.quakelive.fr/collectd/test/

**Comment by rakotomandimby** [comment]
@Poil , thank you for you share. Did you just blindly follow https://github.com/collectd/collectd/blob/master/contrib/redhat/collectd.spec to build your?

**Comment by Poil** [comment]
@rakotomandimby Yep, the src.rpm is provided in each OS-release folder :)

**Comment by RichieB2B** [comment]
I found this useful URL with several recent collectd RPMs for RHEL6: https://copr-be.cloud.fedoraproject.org/results/stevenmerrill/collectd5/
