### ISSUE TITLE
[collectd 5.4.0]rrdtool plugin: rrd_update_r problem :Problem with postgresql plugin

### ISSUE THREAD

**Issue by ssobob** [collectd/collectd#528]
Hello,

I have the following log error message when I am using postgresql plugin.

```
[2014-01-30 09:06:17] rrdtool plugin: rrd_update_r (/opt/collectd/var/lib/collectd/rrd/borisPerfPgsql/postgresql-boris/pg_db_size.rrd) failed: /opt/collectd/var/lib/collectd/rrd/borisPerfPgsql/postgresql-boris/pg_db_size.rrd: illegal attempt to update using time 1391069177 when last update time is 1391069177 (minimum one second step)
```

I am using collectd 5.4.0 release on a Centos 6.4
I checked process on my server with ps aux | grep collectd. Only one collectd process is running.

```
[root@borisPerfPgsql ~]# ps aux | grep collectd
root      1863  0.0  0.0   6120   320 ?        Ss   Jan29   0:00 /opt/collectd/sbin/collectdmon -P /opt/collectd/var/run/collectdmon.pid -c /opt/collectd/sbin/collectd -- -C /opt/collectd/etc/collectd.conf
root      1864  0.0  0.0 978996  8648 ?        SLl  Jan29   0:41 /opt/collectd/sbin/collectd -C /opt/collectd/etc/collectd.conf -f
root      7571  0.0  0.0 100944   600 pts/0    S+   08:59   0:00 tail -f /opt/collectd/var/log/logfile
root      7673  0.0  0.0 103256   832 pts/1    S+   09:08   0:00 grep collectd
```

About my clocks server, ntp is well configured with a cron.

Last point, the collectd doesn't generate rrd_update error for other rrd files like cpu, memory or df rrd files. So I don't think its a clock problem.

Is someone has the same problem with postgresql plugin ?
(I will try to have a look at the source code)

```
vi /opt/collectd/etc/collectd.conf
<Plugin postgresql>
        <Query disk_usage>
                Statement "SELECT pg_database_size($1) AS size;"
                Param database
                <Result>
                        Type pg_db_size
                        ValuesFrom "size"
                </Result>
    </Query>
        <Database boris>
                Host "localhost"
                Port "5432"
                User "boris"
                Password "boris"
                Query disk_usage
        </Database>
</Plugin>
```

Thanks a lot for your help

**Comment by stephenrjohnson** [comment]
I'm hitting the same problem as well, has this every need looked into?

**Comment by hassonofer** [comment]
Got the same problem, also using:
```
Statement "SELECT pg_database_size($1) AS size;"
Param database

Type pg_db_size
ValuesFrom "size"
```

**Comment by hassonofer** [comment]
I understand the problem now.  
By naming a query with same name as query in the (postgresql_default.conf) [https://github.com/collectd/collectd/blob/d6f0273b2ebae6995d69c7701838825b96e4f424/src/postgresql_default.conf], it does not overwrite it, the collectd daemon attempts to run both of them, and collusion occur.

To avoid this bug, rename your queries.

**Comment by rubenk** [comment]
Indeed, this is not just specific to the postgres plugin. The rrdtool plugin doesn't like duplicate names. @ssobob does renaming your queries solve your issue?

**Comment by rubenk** [comment]
closing stale issue.

**Comment by ady080808** [comment]
I got this error : collectd[7515]: rrdtool plugin: rrd_update_r (/var/lib/collectd/rrd/localhost/interface-ppp0/if_dropped.rrd) failed: /var/lib/collectd/rrd/localhost/interface-ppp0/if_dropped.rrd: illegal attempt to update using time 1533021476 when last update time is 1533021476 (minimum one second step)
