### ISSUE TITLE
AutoLoadPlugin doesn't play well with aggregation plugin

### ISSUE THREAD

**Issue by faxm0dem** [collectd/collectd#535]
The config below yields the following error message in the log:

    plugin_value_list_clone: Unable to determine interval from context for value list "global/aggregation-num/memory". This indicates a broken plugin. Please report this problem to the collectd mailing list or at <http://collectd.org/bugs/>.

```
#
AutoLoadPlugin true
Interval 2
TimeOut  2

<LoadPlugin memory>
  Interval 2
</LoadPlugin>

<Plugin aggregation>
  <Aggregation>
    Type memory
    CalculateNum true
  </Aggregation>
</Plugin>
```

Moreover, when specifying aggregation's `LoadPlugin` explicitly, one sometimes gets the following:
```
uc_update: Value too old:
```

Rerunning sometimes makes it go away, sometimes not. It's quite unpredictable.

Last but not least, the actual value returned by aggregation (should be equal to 4 in theory) is quite unpredictable too: sometimes 0, sometimes 4, sometimes 8. Worse, if the interval of `aggregation` is N times larger than the interval of `memory`, the resulting `num` is 4N.

Am I doing something obvious very wrong?

**Comment by mfournier** [comment]
Closing as #539 was superseded by f596915, amd the race issue was fixed by #676. The only issue left is #297.
