### ISSUE TITLE
Allow to define threshold configuration block in several files

### ISSUE THREAD

**Issue by adrianlzt** [collectd/collectd#551]
I'm using puppet to configure collectd, and my idea is to have in the same file plugin  and threshold configuracion.
Something like:
``foo.conf:``
```
<Plugin foo>
  param bla
</Plugin>
<Plugin threshold>
  <Type "abc">
    FailureMax 1
  </Type>
</Plugin>
```

But if two different blocks of "threshold" are defined, this error is shown when collectd is restarted:
``Starting collectd: plugin: register_callback: a callback named `threshold' already exists - overwriting the old entry!``

Using the same file to define all thresholds is complicated to manage.
Any chance to implement this?

**Comment by michaelsalmon** [comment]
I think that it is more appropriate to fix this in plugin.c. It should quietly ignore updating a callback with the same value.

My reasoning is that plugin.c knows already that a callback has been registered and if it is fixed here then it will never have to be fixed elsewhere.

On the other side it wastes cycles..

I think that I could have come to grips with the problem faster if I had known which callback was being overwritten. Perhaps the error message could include that information.

**Comment by octo** [comment]
@michaelsalmon I'd argue that the duplicate check is a start-up cost and therefore negligible for the overall runtime performance.

**Comment by michaelsalmon** [comment]
I don't want to remove the check, just the error when the callback is the same.

I have submitted pull requests for both plugin.c & threshold.c that address this problem.
