### ISSUE TITLE
Powerdns improvments

### ISSUE THREAD

**Issue by julien51** [collectd/collectd#555]
Hi!
When running the latest version of the powerdns recursor along with the latest version of collectd, our syslog has the following messages:
```
Feb 16 06:26:13 dns collectd[3680]: powerdns plugin: submit: Not found in lookup table: throttled-outqueries = 371;
Feb 16 06:26:13 dns collectd[3680]: powerdns plugin: submit: Not found in lookup table: unreachables = 1025;
Feb 16 06:26:13 dns collectd[3680]: powerdns plugin: submit: Not found in lookup table: case-mismatches = 0;
Feb 16 06:26:13 dns collectd[3680]: powerdns plugin: submit: Not found in lookup table: edns-ping-matches = 0;
Feb 16 06:26:13 dns collectd[3680]: powerdns plugin: submit: Not found in lookup table: edns-ping-mismatches = 0;
Feb 16 06:26:13 dns collectd[3680]: powerdns plugin: submit: Not found in lookup table: ipv6-outqueries = 0;
Feb 16 06:26:13 dns collectd[3680]: powerdns plugin: submit: Not found in lookup table: no-packet-error = 1139817;
Feb 16 06:26:13 dns collectd[3680]: powerdns plugin: submit: Not found in lookup table: noedns-outqueries = 1849909;
Feb 16 06:26:13 dns collectd[3680]: powerdns plugin: submit: Not found in lookup table: noping-outqueries = 0;
Feb 16 06:26:13 dns collectd[3680]: powerdns plugin: submit: Not found in lookup table: over-capacity-drops = 0;
Feb 16 06:26:13 dns collectd[3680]: powerdns plugin: submit: Not found in lookup table: packetcache-entries = 285514;
Feb 16 06:26:13 dns collectd[3680]: powerdns plugin: submit: Not found in lookup table: packetcache-hits = 277503;
Feb 16 06:26:13 dns collectd[3680]: powerdns plugin: submit: Not found in lookup table: packetcache-misses = 1166411;
Feb 16 06:26:13 dns collectd[3680]: powerdns plugin: submit: Not found in lookup table: uptime = 4398;
```

When looking in the code for `powerdns plugin: submit: Not found in lookup table` I found:

> Please note that up to that point collectd doesn't know what values are
available on the server and values that are added do not need a change of the
mechanism so far. However, the values must be mapped to collectd's naming
scheme, which is done using a lookup table that lists all known values. If
values are added in the future and collectd does not know about them, you will
get an error much like this:

>   powerdns plugin: submit: Not found in lookup table: foobar = 42

> In this case please file a bug report with the collectd team.

So, here I am! Please, let me know if I can help further or if I can easily fix this! I tried version hacks, but none seemed to work :/

**Comment by mfournier** [comment]
It seems #965 handles part of the metrics you pointed out. @rubenk, any comments on this issue maybe ?

**Comment by rubenk** [comment]
I'm planning on updating the stats for the recursor soon too.
