### ISSUE TITLE
How can I install the write_mongodb plugin?

### ISSUE THREAD

**Issue by catamphetamine** [collectd/collectd#583]
Hello.
I downloaded the sources and configure them like this:

```
./configure --with-libmongoc=/usr/local/lib/libmongoc-1.0.so --enable-write_mongodb
```

but it says "write_mongodb . . . . no (dependency error) ... Some plugins are missing dependencies - see the summary above for details".

The full summary can be found here: http://pastebin.com/raw.php?i=K7nwdYcX

Is it the correct command to install the write_mongodb plugin?
(i just tried to run this plugin for fun, no urgency on this issue)

**Comment by ppoornima** [comment]
Hi kuchumovn,
I am having the same issue. I would like to know if you were able to resolve this issue. If, can you please post the solution?

Thanks

**Comment by kuchumovn** [comment]
I don't remember if I tried the comment posted above.
Anyway, we've written our own collector through HTTP.
So I don't confirm if the issue is resolved.

**Comment by ppoornima** [comment]
Thanks for the reply
