### ISSUE TITLE
why  is commented the "type" replace  Target ? What side effects if uncomment ?

### ISSUE THREAD

**Issue by toni-moreno** [collectd/collectd#590]
I would like to replace some types before to send data to a graphite backend.

but I can see this errors.

```
[2014-03-25 12:10:24] [error] Target `replace': The `Type' configuration option is not understood and will be ignored.
[2014-03-25 12:10:24] [error] Target `replace': The `Type' configuration option is not understood and will be ignored.
[2014-03-25 12:10:24] [error] Target `replace': The `Type' configuration option is not understood and will be ignored.
[2014-03-25 12:10:24] [error] Target `replace': The `Type' configuration option is not understood and will be ignored.
```

In the code I've seen that the code exists at src/target_replace.c , but is commented. 

```
struct tr_data_s
{
  tr_action_t *host;
  tr_action_t *plugin;
  tr_action_t *plugin_instance;
  /* tr_action_t *type; */
  tr_action_t *type_instance;
};

...
#if 0
    else if (strcasecmp ("Type", child->key) == 0)
      status = tr_config_add_action (&data->type, child,
          /* may be empty = */ 0);
#endif

...
```

After uncomment myself I've seen a "Type" validation error in graphite plugin.

```
[error] write_graphite plugin: DS type does not match value list type
```

but it seems only a simple validation on code src/write_graphite.c

```
    if (0 != strcmp (ds->type, vl->type))
    {
        ERROR ("write_graphite plugin: DS type does not match "
                "value list type");
        return -1;
    }

```

I would like to know if it is possible to uncomment  ( I can do myself I everybody is alright) and no other unwanted side effects.

Thanks a lot!

**Comment by ChristianTacke** [comment]
I have another use case:

I get some metrics over the network and they just have the wrong type (which is missing from types.db). So I want to set a type that actually exists in types.db.

Could you reconsider adding this? Possibly put a big warning in the docs?
