### ISSUE TITLE
curl plugin: Enable multi-line matching.

### ISSUE THREAD

**Issue by mnlipp** [collectd/collectd#614]
The curl plugin doesn't take into account that data obtained from e.g. a web site isn't necessarily line oriented. I want to collect data from a page that has two similar structured lines with a "Frequency ..." value in different contexts. The lines look the same. One, however is preceded by some other line containing "Downstream", the other is preceded by a line containing "Upstream". As regular expression matching is restricted to a single line, I cannot distinguish those entries.

A simple solution to this problem would be to allow the user to suppress the REG_NEWLINE to be passed to regcomp. Then I can specify a regular expression that spans several lines and finds the "Frequency" of interest in the specified context only.

**Comment by octo** [comment]
IIuc, with the `REG_NEWLINE` flag set, you _can_ match on newlines, just not with a period (`.`). A regular expression such as `Downstream\nFrequency ([0-9]+)` *should* work.
