### ISSUE TITLE
varnish plugin doesn't work with Varnish 4.0

### ISSUE THREAD

**Issue by rubenk** [collectd/collectd#618]
collectd 5.4.0 in Fedora Rawhide FTBFS because it cannot find varnishapi.h

configure.ac checks for varnishapi.h but looking at the Varnish source this header got dropped somewhere in 2011.

Unfortunately I'm not familiar enough with Varnish or its api to propose a fix.

**Comment by tokkee** [comment]
Wee! Thanks Marc.

**Comment by lenineto** [comment]
Hi guys, 
I'm trying to apply the #783 patch to the master branch but it fails. I get error: patch failed: on every file.

I'm new to git, so there is a good chance I'm doing something wrong here.

Any help is appreciated.

Thanks
