### ISSUE TITLE
many many syslog messages like "0 Success: 1 value has been dispatched"

### ISSUE THREAD

**Issue by putty12** [collectd/collectd#664]
I´m using collectd 5.4.1 on gentoo 64bit.
I have written some exec plugins in bash.

Problem: i receive a lot of "0 Success: 1 value has been dispatched" messages which fills my syslog (systemd journal).

It seems that these message comes from "src/utils_cmd_putval.c:" but not 100% shure.

How can I disable that ?
Is it a feature ?

Thank you...
..regards putty12

**Comment by kaos** [comment]
+1, would also like to see this resolved.

**Comment by blysik** [comment]
Any idea how to quiet this message?

**Comment by martbhell** [comment]
Same in 5.5.0-2 on CentOS7.
Getting rid of collectd in /var/log/messages by adding this to a file in /etc/rsyslog.d/: 

if $app-name contains 'collectd' then {
   stop
}

**Comment by octo** [comment]
There are currently written to `STDOUT`, which should normally hooked up to `/dev/null`. Are you starting *collectd* with one of these newfangled init systems kids [*] are using these days?

[*] Get off my lawn! ;-)

**Comment by octo** [comment]
I think there is a lot of overlap with #1327: in both cases logging of the `PUTVAL` commands received by the *exec plugin* are not done as expected.

**Comment by gsauthof** [comment]
I can confirm this issue with CentOS 7 and Collectd 5.5.

(Where the Collectd package comes from the EPEL repository. The EPEL repository contains backports of Fedora packages to RHEL, maintained by the Fedora community.)

I can also confirm that collectd is started via systemd on such systems.

It is started like this (when using the default systemd startup file):

    /usr/sbin/collectd -C /etc/collectd.conf -f

(where `-f` is documented as 'collectd will also not close standard file descriptors')

Looking at `lsof` stdout and stderr are thus hooked up with journald:

    collectd 1322 root    1u  unix 0xffff88040842e580      0t0   5702647 socket
    collectd 1322 root    2u  unix 0xffff88040842e580      0t0   5702647 socket

Where `ss -xp` tells us:

    u_str  ESTAB 0 0 * 5702647  * 5702648 users:(("collectd",1322,2),("collectd",1322,1))
    u_str  ESTAB 0 0 /run/systemd/journal/stdout 5702648  * 5702647 users:(("systemd-journal",484,16))

**Comment by aerusso** [comment]
My pull request #1553 should address this issue. I'd appreciate comments on that patch.

**Comment by rubenk** [comment]
This should be fixed by 10b10a6

**Comment by Geraden07** [comment]
This fix is in the process of being pulled into Fedora's repository version. See bug ticket here:

https://bugzilla.redhat.com/show_bug.cgi?id=1343863
