### ISSUE TITLE
5.1 Build failure for Solaris 10

### ISSUE THREAD

**Issue by jblaine** [collectd/collectd#70]
:(

<pre>collectd-5.1.0:cairo> uname -a
SunOS cairo.our.org 5.10 Generic_144488-17 sun4u sparc SUNW,Sun-Fire-280R
collectd-5.1.0:cairo> echo $PATH
/usr/bin:/bin:/usr/sfw/bin:/usr/ccs/bin:/sbin:/usr/sbin
collectd-5.1.0:cairo> ./configure --prefix=/usr/rcf-tools/collectd-5.1.0 --enable-all-plugins
...
collectd-5.1.0:cairo> make 2>&1 | tee make.log
...
nfs.c: In function `nfs_read_kstat':
nfs.c:335: warning: passing arg 2 of `get_kstat_value' discards qualifiers from pointer target type
*** Error code 1
make: Fatal error: Command failed for target `nfs.lo'
...
</pre>

**Comment by rubenk** [comment]
It doesn't matter. const is a type qualifier, char is a type specifier, and the ordering is not specified afaik.
