### ISSUE TITLE
tcpconns plugin: conn_read_netlink: Received error -95.

### ISSUE THREAD

**Issue by ConiKost** [collectd/collectd#704]
I am running collectd 5.4.1 on my gentoo box. The tcpconns plugins seems to work, but it's printing on each start:

tcpconns plugin: conn_read_netlink: Received error -95.
tcpconns plugin: Reading from netlink failed. Will read from /proc from now on.

How can be this fixed? What does error -95 mean? Netlink is on my system enabled and available..

**Comment by ConiKost** [comment]
Okay, there options makes netlink for tcpconns work:

CONFIG_INET_DIAG
CONFIG_INET_UDP_DIAG
CONFIG_INET_RAW_DIAG

**Comment by octo** [comment]
Thanks for your research @ConiKost! I think we should be able to improve the error message with this.

**Comment by xiaomacdut** [comment]
What do these parameters mean? @ConiKost

**Comment by xiaomacdut** [comment]
The plugin "tcpconns" successfully loaded,but it print:
 tcpconn_read_netlink: sendmsg(2) failed: Connection refused
 tcpconns plugin: Reading from netlink failed. Will read from /proc from now on.

**Comment by ConiKost** [comment]
@xiaomacdut 
Do you mean the CONFIG_INET_* options? Those are options, when you do compile the kernel. Those are needed, when you want to use NETLINK.

But "sendmsg(2) failed: Connection refused" sounds more like a permission problem. Did you try running collectd as root and check, if this also happens?

**Comment by xiaomacdut** [comment]
My operating system:Red Hat Enterprise Linux Server release 5.3 (Tikanga).I run collectd as root ,the error will happen.If run on Red Hat Enterprise Linux Server release 6.5 (Santiago),it's ok. @ConiKost

**Comment by octo** [comment]
Do you start collectd manually? Some init systems will drop capabilities, so you might run as UID 0 and still don't have permission …

**Comment by xiaomacdut** [comment]
yes,I start collectd manually.
So,the problem is about permission?

**Comment by ConiKost** [comment]
Closing here, since it's not an issue in collectd.
