### ISSUE TITLE
network plugin: parse_part_string: Output buffer too small

### ISSUE THREAD

**Issue by lamont** [collectd/collectd#724]
Hello,

I'm attempting to relay about 1 million collectd metrics a minute from a legacy 4.10 (patched) install (where we stored data with rrdcached) via udp to a new 5.4.1 install writing via the write_graphite plugin to localhost (also via udp).  There are no other output plugins running on this instance, just a network Listen and a write_graphite output.

I'm seeing the following message constantly while operating my collectd->write_graphite setup under heavy load:

Sep  4 18:50:48 app001 collectd[24745]: network plugin: parse_part_string: Output buffer too small.
Sep  4 18:50:50  collectd[24745]: last message repeated 499 times
Sep  4 18:50:50 app001 rsyslogd-2177: imuxsock begins to drop messages from pid 24745 due to rate-limiting
Sep  4 18:50:54 app001 rsyslogd-2177: imuxsock lost 1067 messages from pid 24745 due to rate-limiting

About 5k metrics/second are making it into graphite, but I have not been able to determine if the messages above refer to metric sending to write_graphite being denied due to volume or due to particulars of those individual metrics.  From the gaps in my graphite data, I assume the messages or packets being called out by the error message (and its repeats) are being subsequently dropped rather than resent.

This is a 5.4.1 install where I've changed DATA_MAX_NAME_LEN from 64 to 256 (we have some absurdly long metric names and I was mimicing the changes made to the 4.10 install with a comment that they were needed for jcollectd sent long names)

Is this the result of my change to the DATA_MAX_NAME_LEN?  Is that change even necessary to support long sent metric names? 

This is a redhat 6.4 box. I could get the specifics of the config I'm using on monday but I only pasted the errors in my notes this evening.  I was hoping someone could shed light on under what circumstances that log message would show up so frequently and what the implications were.

Thank you for your time and very useful software.

**Comment by julien51** [comment]
@octo We're seeing a similar problem. Our log is full of 

```
May 13 07:41:08 stats collectd[8878]: network plugin: parse_part_string: Output buffer too small.
May 13 07:41:11 stats collectd[8878]: network plugin: parse_part_string: Output buffer too small.
May 13 07:41:12 stats collectd[8878]: network plugin: parse_part_string: Output buffer too small.
May 13 07:41:13 stats collectd[8878]: network plugin: parse_part_string: Output buffer too small.
May 13 07:41:14 stats collectd[8878]: network plugin: parse_part_string: Output buffer too small.
May 13 07:41:16 stats collectd[8878]: network plugin: parse_part_string: Output buffer too small.
```

Could you clarify how to use Wireshark to debug this?

Thanks!

**Comment by lamont** [comment]
tshark -r somePcapFileWithCollectdTraffic.gz -T fields -e collectd.len

In my case it turns out I'd not actually increased the DATA_MAX_NAME_LEN beyond the 64 byte default. (I'd forgotten to call the patch from the rpm spec file)
