### ISSUE TITLE
df plugin does strange things when existing / and /root filesystem. 

### ISSUE THREAD

**Issue by toni-moreno** [collectd/collectd#739]
I'm working on a debian wheezy/sid .

When df plugin  has auto-discover mount points , it seems to forget "/" or "/root"  ( one of them)

![image](https://cloud.githubusercontent.com/assets/5883405/4317049/f568a122-3f0e-11e4-8ce4-6146000bbbd7.png)

```

root@nono:~# df -h | grep -v rootfs  | sort -k6
Filesystem                                              Size  Used Avail Use% Mounted on
/dev/disk/by-uuid/dcf7d369-c7d8-4296-bfb0-dc270bcdb11b  7.2G  6.2G  707M  90% /
udev                                                    3.0G  4.0K  3.0G   1% /dev
/dev/sdb3                                               2.0G  1.4G  549M  72% /opt
/dev/sdc1                                               2.0G  785M  1.2G  41% /opt/IBM
/dev/sdc2                                               2.0G  954M  960M  50% /opt/graphite
/dev/sdb1                                               4.0G  1.4G  2.5G  35% /root
tmpfs                                                   598M  804K  597M   1% /run
none                                                    5.0M     0  5.0M   0% /run/lock
none                                                    3.0G     0  3.0G   0% /run/shm
/dev/sdc3                                               4.0G  3.3G  502M  87% /soft
/dev/sdb2                                               2.0G  269M  1.7G  14% /var/cache
```

I've filterered rootfs( as code does ) and ordered by name to compare with next picture

![image](https://cloud.githubusercontent.com/assets/5883405/4317009/6f8acaee-3f0e-11e4-80e1-8f482ef6a18b.png)

As you can see sometimes reported "root" %used is like /root in df ( aprox 35% ) and sometimes is like  "/" ( aprox %90), but indeed the %used from both filesystems "/" and "/root" are not changing.

**Comment by davewongillies** [comment]
I'm experiencing this issue too on Debian Wheezy with the packages from https://pkg.ci.collectd.org/deb/dists/wheezy/master/binary-amd64/. Up until version `5.5.0.195.gc4da209-1~wheezy` `/` is reported but with versions `5.5.0.211.g817e080-1~wheezy`, `5.5.0.326.g0657d95-1~wheezy` & `5.5.0.806.g9c8f311-1~wheezy`.

Here's the df config I'm using:

```
LoadPlugin df
<Plugin "df">
  FSType rootfs
  FSType sysfs
  FSType proc
  FSType devtmpfs
  FSType devpts
  FSType tmpfs
  FSType fusectl
  FSType cgroup
  IgnoreSelected true
</Plugin>
```

With version `5.5.0.195.gc4da209-1~wheezy`
```
# collectdctl listval |grep df
receive: <-- 1453088471.781 my_server/df-root/df_complex-free
receive: <-- 1453088471.781 my_server/df-root/df_complex-reserved
receive: <-- 1453088471.781 my_server/df-root/df_complex-used
my_server/df-root/df_complex-free
my_server/df-root/df_complex-reserved
my_server/df-root/df_complex-used
```

With version `5.5.0.195.gc4da209-1~wheezy`:
```
# collectdctl listval |grep df
<no output>
```

**Comment by rubenk** [comment]
@toni-moreno, can you confirm that 573db6c fixes this for you?

**Comment by octo** [comment]
I think this is a different issue: both mount points, "/" and "/root" are mapped to the same plugin instance, "root". Since both metrics are read at the same time, one of them wins the race and the other one is deduplicated.

This is annoying in this particular situation, but changing the behavior of the "/" mount point is not an option. If you enable the `ReportByDevice` option the metrics will be reported with the device name rather than the mount point, which should be unique.

HTH, best regards,
—octo

**Comment by nagukothapalli** [comment]
@octo 

Is Device  support regex ?

**Comment by C-Duv** [comment]
I also have boot `/` and `/root` mountpoints:
```
/dev/sda2 / ext4 rw,...
/dev/vg/usr /usr ext4 rw,...
/dev/sda1 /boot ext4 rw,...
/dev/mapper/vg-root /root ext4 rw,...
/dev/mapper/vg-home /home ext4 rw,...
/dev/mapper/vg-tmp /tmp ext4 rw,...
/dev/mapper/vg-var /var ext4 rw,...
```
And collected only reports usage for `/root` (if there is a race between `/` and `/root` I'd say `/root` always wins).

Is there a (new) solution to this problem?
Because enabling `ReportByDevice` gives less expressive names: 
* mapper_vg-home
* mapper_vg-root
* mapper_vg-tmp
* mapper_vg-var
* overlay
* sda1
* sda2
* vg_usr

**Comment by rpv-tomsk** [comment]
Explanation:

In `df` plugin, `/var` mountpoint metrics, for example,  are reported as `df` plugin and `var`  plugin instance metrics. Using this scheme, `/` mountpoint metrics had to be reported with `df` plugin and "" (empty) plugin instance values. As this is unacceptable (each mountpoint should have plugin instance filled), root mountpoint `/` is reported with `root` plugin instance value.

As you already understand, your `/root` mountpoint - is also reported as `df` plugin and `root`  plugin instance, so conflict occurs.

**Comment by C-Duv** [comment]
I get the corresponding line is 
https://github.com/collectd/collectd/blob/ccf9586cbd6b6a2ab0dfe2075992c71561a6910d/src/df.c#L225-L226:

Could something like https://github.com/C-Duv/collectd/commit/54db6b6fdb7f7ebb29270af48457168b482965b9 be an acceptable change?

```Diff
diff --git a/src/df.c b/src/df.c
index 5b3fbd2..ec621f8 100644
--- a/src/df.c
+++ b/src/df.c
@@ -48,9 +48,13 @@

 static const char *config_keys[] = {
     "Device",         "MountPoint",   "FSType",         "IgnoreSelected",
-    "ReportByDevice", "ReportInodes", "ValuesAbsolute", "ValuesPercentage"};
+    "ReportByDevice", "ReportInodes", "ValuesAbsolute", "ValuesPercentage",
+    "RootDirName"};
 static int config_keys_num = STATIC_ARRAY_SIZE(config_keys);

+/* Plugin instance for "/" mountpoint */
+static char *rootdirname = "root";
+
 static ignorelist_t *il_device;
 static ignorelist_t *il_mountpoint;
 static ignorelist_t *il_fstype;
@@ -123,6 +127,13 @@ static int df_config(const char *key, const char *value) {
       values_percentage = false;

     return 0;
+  } else if (strcasecmp(key, "RootDirName") == 0) {
+    if (rootdirname != NULL)
+      free(rootdirname);
+    if ((rootdirname = strdup(value)) == NULL)
+      return 1;
+    else
+      return 0;
   }

   return -1;
@@ -223,7 +234,7 @@ static int df_read(void) {
       }
     } else {
       if (strcmp(mnt_ptr->dir, "/") == 0)
-        sstrncpy(disk_name, "root", sizeof(disk_name));
+        sstrncpy(disk_name, rootdirname, sizeof(disk_name));
       else {
         sstrncpy(disk_name, mnt_ptr->dir + 1, sizeof(disk_name));
         size_t len = strlen(disk_name);
```
