### ISSUE TITLE
collectd, write_graphite and openvpn

### ISSUE THREAD

**Issue by rtkmhart** [collectd/collectd#743]
I have collectd running on remote nodes that connect back to my network where graphite lives using OpenVPN, and use the write_graphite plugin to forward stats via TCP to graphite. If I define two VPN servers, OpenVPN will happily reconnect to the second VPN server if the first goes away, but the side effect is that the node in question suddenly has a new IP address in a new subnet. collectd doesn’t appear to register the IP change, as both it and carbon-cache still claim to have a valid TCP connection open with the old IP. 

I think the reason that collectd ignores that there’s no ACK on the packets once the IP changed is due to it ignoring EAGAIN in swrite() (https://github.com/collectd/collectd/blob/master/src/daemon/common.c#L281). I don't know if that's entirely true or what the correct tcp-level programming should be, if this isn't correct. Thoughts?

Short of restarting collectd when openvpn reconnects (which is possible but feels dirty) are there any other suggestions?

cheers
mike

**Comment by rubenk** [comment]
Closing due to lack of response.
