### ISSUE TITLE
Unable to compile on Solaris 10

### ISSUE THREAD

**Issue by digitalrinaldo** [collectd/collectd#745]
I was able to get Solaris 11 to compile with the following

./configure CFLAGS='-m64 -DSOLARIS2=11  -D__EXTENSIONS__ '

On Solaris 10 I get the following issues

./configure CFLAGS='-DSOLARIS2=11 o-D__EXTENSIONS__ '

-Wno-error'  made no difference

libtool: link: ranlib .libs/libltdlc.a
libtool: link: rm -fr .libs/libltdlc.lax
libtool: link: ( cd ".libs" && rm -f "libltdlc.la" && ln -s "../libltdlc.la" "libltdlc.la" )
make381[2]: Leaving directory `/tmp/collectd-5.4.1/libltdl'
make381[1]: Leaving directory `/tmp/collectd-5.4.1/libltdl'
Making all in src
make381[1]: Entering directory `/tmp/collectd-5.4.1/src'
/localtools/sparc/bin/make381  all-recursive
make381[2]: Entering directory `/tmp/collectd-5.4.1/src'
Making all in libcollectdclient
make381[3]: Entering directory `/tmp/collectd-5.4.1/src/libcollectdclient'
/localtools/sparc/bin/make381  all-am
make381[4]: Entering directory `/tmp/collectd-5.4.1/src/libcollectdclient'
  CC     libcollectdclient_la-client.lo
  CC     libcollectdclient_la-network.lo
  CC     libcollectdclient_la-network_buffer.lo
network_buffer.c:124: parse error before `have_gcrypt'
cc1: warnings being treated as errors
network_buffer.c:125: warning: return-type defaults to `int'
network_buffer.c: In function `have_gcrypt':
network_buffer.c:126: syntax error before `result'
network_buffer.c:127: syntax error before `need_init'
network_buffer.c:129: `need_init' undeclared (first use in this function)
network_buffer.c:129: (Each undeclared identifier is reported only once
network_buffer.c:129: for each function it appears in.)
network_buffer.c:130: `result' undeclared (first use in this function)
make381[4]: *** [libcollectdclient_la-network_buffer.lo] Error 1
make381[4]: Leaving directory `/tmp/collectd-5.4.1/src/libcollectdclient'
make381[3]: *** [all] Error 2
make381[3]: Leaving directory `/tmp/collectd-5.4.1/src/libcollectdclient'
make381[2]: *** [all-recursive] Error 1
make381[2]: Leaving directory `/tmp/collectd-5.4.1/src'
make381[1]: *** [all] Error 2
make381[1]: Leaving directory `/tmp/collectd-5.4.1/src'
make: *** [all-recursive] Error 1

**Comment by rubenk** [comment]
I did manage to build on Solaris 10 with packages from OpenCSW, using something like
```
./configure MAKE=gmake RANLIB=/opt/csw/bin/granlib AR=/opt/csw/bin/gar CFLAGS="-m64"  LDFLAGS="-L/opt/csw/lib/64 -R/opt/csw/lib/64" PKG_CONFIG_PATH="/opt/csw/lib/64/pkgconfig" --with-libgcrypt=/opt/csw/bin/amd64/libgcrypt-config  --with-libcurl=/opt/csw/bin/amd64/curl-config
```

OpenCSW also does automatic builds on each commit, see https://buildfarm.opencsw.org/buildbot/waterfall?category=collectd and has packages for collectd.
