### ISSUE TITLE
cpu rehaul makes aggregation not add up to 100%

### ISSUE THREAD

**Issue by faxm0dem** [collectd/collectd#746]
https://github.com/collectd/collectd/pull/734 breaks https://github.com/collectd/collectd/pull/679

Also, when using the following config, the cpu usage, the values do not add up to a constant value
![2014-09-24-140233_742x162_scrot](https://cloud.githubusercontent.com/assets/112638/4387828/b7fe9e4e-43e2-11e4-9222-e1883797ef44.png)

```
<Plugin "cpu">
   ReportByCpu false
</Plugin>
```

**Comment by ranjanmanish** [comment]
Hey @faxm0dem , when I tried using this plugin feature on Ubuntu 14.04 and collectd 5.4 , it threw me message in collectd log as 

"Found a configuration for the `cpu' plugin, but the plugin isn't loaded or didn't register a configuration callback".
