### ISSUE TITLE
redis plugin: unable to connect to node

### ISSUE THREAD

**Issue by DanHoerst** [collectd/collectd#755]
I've installed collectd with the redis plugin on one of my redis servers. When starting the collectd service I receive the following error:

    collectd[31964]: redis plugin: unable to connect to node `Logstash-Redis' (127.0.0.1:6379).

In addition to `127.0.0.1` I've also tried `localhost` and the both the public and private ip of the server. That said, it does not appear that the host is the problem since in the redis logs I find the following (both messages come through immediately as the collectd service is restarted):

    [31934] 02 Oct 02:41:29.674 - Accepted 127.0.0.1:35857
    [31934] 02 Oct 02:41:29.675 - Client closed connection

I've also tried recompiling collectd to make sure that credis was installed, and the compile messages read as:

    libcredis . . . . . . yes
    redis . . . . . . yes

I'll also mention that I can connect to the redis-cli at `127.0.0.1:6379` on the same server.

Any idea what the issue could be here?

Thanks.

**Comment by rubenk** [comment]
Collectd now uses hiredis instead of credis since 5.5.1. I'll assume this is fixed now, but please holler if you're still having issues.

**Comment by lkx007** [comment]
I have installed collectd and redis in centos 7 from epel rpms;
[root@localhost ~]# rpm -qa|grep collectd
collectd-redis-5.6.0-1.el7.x86_64
collectd-5.6.0-1.el7.x86_64
[root@localhost ~]# 
[root@localhost ~]# rpm -qa|grep redis
collectd-redis-5.6.0-1.el7.x86_64
redis-2.8.19-2.el7.x86_64
hiredis-0.12.1-1.el7.x86_64
[root@localhost ~]# 
My collectd redis plugin config is as follows:
LoadPlugin redis
<Plugin redis>
  <Node "example">
      Host "127.0.0.1"
      Port "6379"
      Timeout 2000
  </Node>
</Plugin>

I got the same problem in syslog as follows:
[root@localhost ~]# tailf /var/log/messages 
Nov  3 03:29:34 localhost collectd[11866]: collectd: Stopping 5 write threads.
Nov  3 03:29:34 localhost systemd: Stopping Collectd statistics daemon...
Nov  3 03:29:34 localhost systemd: Starting Collectd statistics daemon...
Nov  3 03:29:34 localhost collectd[12165]: plugin_load: plugin "syslog" successfully loaded.
Nov  3 03:29:34 localhost collectd[12165]: plugin_load: plugin "network" successfully loaded.
Nov  3 03:29:34 localhost collectd[12165]: Systemd detected, trying to signal readyness.
Nov  3 03:29:34 localhost collectd[12165]: Initialization complete, entering read-loop.
Nov  3 03:29:34 localhost collectd: plugin_load: plugin "redis" successfully loaded.
Nov  3 03:29:34 localhost systemd: Started Collectd statistics daemon.
Nov  3 03:29:34 localhost collectd[12165]: redis plugin: unable to get info from node `example'.
^C
[root@localhost ~]# 

I checked that my redis is running and the port is listening:
[root@localhost ~]# ps -fe|grep redis
root     12132     1  0 03:25 ?        00:00:00 redis-server 127.0.0.1:6379
root     12250 12099  0 03:38 pts/0    00:00:00 grep --color=auto redis
[root@localhost ~]# 
[root@localhost ~]# netstat -antp|grep 6379
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      12132/redis-server  
[root@localhost ~]# 
[root@localhost ~]# 
How can I solve this problems?
Thanks a lot.
