### ISSUE TITLE
Ping plugin's values not updated in time when number of hosts is greater than 50 hosts

### ISSUE THREAD

**Issue by hanynowsky** [collectd/collectd#756]
We have more than 600 Hosts to ping using the collectd ping plugin.
We use the Threshold plugin as a notifier using the Type *ping_droprate*
- The notifications are correctly updated when we have less than 50 hosts or alike. Yet, once we increase the number of hosts to reach some hundreds, then the plugin starts to send incorrect values.
In other words, servers that are pingable from the CLI may appear DOWN for several cycles.
But one thing which is still correct is that servers that are really DOWN,  return the correct value.
Some other guy face the same problem: 
- Source: http://serverfault.com/questions/579784/collectd-ping-plugin-fail-randomly-on-medium-high-number-of-hosts

- I do not know if this patch was integrated into liboping: http://mailman.verplant.org/pipermail/collectd/2011-July/004640.html   (http://mailman.verplant.org/pipermail/collectd/attachments/20110723/cfb6767c/attachment-0001.patch)

Environment:
- Latest collectd
- Centos 6.5 with liboping 1.5

Conf:
<Plugin "ping">
        Interval 5
        Timeout 4.9
        Host "serv123.foodomain.net"
        Host "serv142.foodomain.net"
        .......
</Plugin>

Thanks

**Comment by octo** [comment]
Moved to octo/liboping#11
