### ISSUE TITLE
Extract formatting functions from network.c to allow a common interface

### ISSUE THREAD

**Issue by ifesdjeen** [collectd/collectd#767]
Hi, 

First of all, thanks a lot for the great library! It's working very well, and is easily configurable and extensible. 

I wanted to make a small suggestion: to take the formatting, currently available in `network.c`: https://github.com/collectd/collectd/blob/collectd-5.4/src/network.c#L2768-L2836 and `utils_format_json.c` https://github.com/collectd/collectd/blob/collectd-5.4/src/utils_format_json.c and:

  * include `utils_format_json.c` into the distribution by default (or at least configurable via some flag), since currently it's only being included when http or amqp plugins are being built.
  * make `utils_format_network.c` and move the functions related to network formatting there, to allow custom transports via plugins to use same binary message format.

That would allow plugin developers to rely on the existing serialisation mechanisms and message formats.

I could even help out and work on that, if you think that this feature may make sense.

**Comment by rubenk** [comment]
Hi @ifesdjeen,

Thanks for kind words!

utils_format_json.c is included in the distribution, and there's now utils_format_json.h which exports its functions.

As for network formatting functions, if you have a plugin that needs them we can certainly move them into a separate file. I prefer to not do that before there's a plugin that needs it though.

Kind regards,

Ruben
