### ISSUE TITLE
Include extended statistics in Disk plugin

### ISSUE THREAD

**Issue by tsndqst** [collectd/collectd#770]
Provide an option to include extended statistics in Disk plugin. The extended statistics I'm interested in can be seen using 'iostat -x'.

Here is the list of columns.
Device:         rrqm/s   wrqm/s     r/s     w/s   rsec/s   wsec/s avgrq-sz avgqu-sz   await  svctm  %util

**Comment by rubenk** [comment]
Fixed in 2188e501bf6c31737ad81a8ca0f70aa7e6c8f31b
