### ISSUE TITLE
Multiple Destinations for write_http plugin not working

### ISSUE THREAD

**Issue by beanieboi** [collectd/collectd#821]
Hey,

we encounter some problems with multiple (2) destinations for the `write_http` plugin.
according to the documentation, you have to specify a URL block for each destination.
`Each destination you want to post data to needs to have one URL block`

This is our custom configuration in `/etc/collectd/collectd.conf.d/custom.conf`
```
LoadPlugin "write_http"
LoadPlugin "ping"

<Plugin ping>
  Host "google.com"
</Plugin>

<Plugin "write_http">
  <URL "https://custom-metrics.com/api/v1/metrics">
   Format "JSON"
   User "user"
   Password "password"
  </URL>

  <URL "https://collectd.librato.com/v1/measurements">
    Format "JSON"
    User "user"
    Password "password"
  </URL>
</Plugin>
```

our collectd version (using official Ubuntu trusty Pacakge):
```
ii  collectd                         5.4.0-3ubuntu2                   amd64        statistics collection and monitoring daemon
ii  collectd-core                    5.4.0-3ubuntu2                   amd64        statistics collection and monitoring daemon (core system)
```

Using only 1 URL block works for both configurations independently. Configuring 2 URLs only sends the metrics to the URL configured last.

we see the following line twice in the syslog after starting collectd.

`plugin: register_callback: a callback named 'write_http' already exists - overwriting the old entry!`

What is the correct way to specify multiple destinations for the writte_http plugin?

thanks for your help.

**Comment by mfournier** [comment]
@beanieboi, I can confirm this issue. It seems this plugin was forgotten when migrating from the 4.x to the 5.x way of sending data to concurrent destinations.

So your usage of the plugin is correct but I'm afraid there's no real workaround. The good news is that it should be fairly easy to fix.

**Comment by beanieboi** [comment]
Cool! Is there anything I can help with?

**Comment by mfournier** [comment]
@beanieboi yes, if you have a way to test the patch referenced above with your setup, it would be great !

NB: the patch is against collectd-5.3. It applies fine on collectd-5.4.0 though. Use whatever version is more convenient for you, write_http.c is exactly the same in both.

Let me know if you need help building from the source code !

**Comment by mfournier** [comment]
@beanieboi, also take a look at #902, which is IMHO the proper way to move forward with this plugin.
