### ISSUE TITLE
Enable option to prevent persistent connections in write_graphite

### ISSUE THREAD

**Issue by Gajillion** [collectd/collectd#832]
From the write_graphite plugin documentation: "The plugin aims to be very efficient. It keeps the TCP connection to Carbon open in order to minimize the connection handshake overhead." The problem is, if a node dies, the load-balancer will (as expected) distribute the traffic to the remaining nodes in the cluster. However, because the connections are persistent, it doesn't rebalance them once the dead node comes back on-line. This leaves the rest of the nodes in an over-worked state, and the revived node almost completely unused.

**Comment by revett** [comment]
+1

Can this PR (https://github.com/collectd/collectd/pull/846) please be merged?

**Comment by octo** [comment]
#846 has been merged.
