### ISSUE TITLE
utils_dns.c does not support some DNS qtypes

### ISSUE THREAD

**Issue by wtps0n** [collectd/collectd#859]
Hi,
I've just setup collectd5 monitoring on bind 9.10 dns server. Some of qtypes are not included in utils_dns.c They are defined in /usr/include/arpa/nameser.h. The problem is with:
44 - SSHFP
48 - DNSKEY
52 - TLSA
99 - SPF

I've checked other my boxes (older versions) and that definitions are absent. But I think it is good idea to add these codes to utils_dns.c. I hope I will attach a patch for support.

**Comment by octo** [comment]
LGTM

@rubenk could you please reference the PR, that you presumably created, here? Thanks :)

**Comment by rubenk** [comment]
Oops, lost that while squashing, sorry.

**Comment by octo** [comment]
PR in #1857
