### ISSUE TITLE
Master doesn't compile on Mac OS X

### ISSUE THREAD

**Issue by ifesdjeen** [collectd/collectd#862]
Currently, when trying to build Master on Mac OS X, I get: 

```
cpu.c:235:2: error: use of undeclared identifier 'cpu_temp_retry_max'
        cpu_temp_retry_max = 86400 / CDTIME_T_TO_TIME_T (plugin_get_interval ());
        ^
```

(actually I can't really find that defined anywhere, either)...

**Comment by ryan-williams** [comment]
Hi, I ran into this one building `master` () on OSX. `git checkout origin/collectd-5.3 && ./build.sh && ./configure && ./make` did get a little bit further, but failed on something else:

```
In file included from aggregation.c:32:
./common.h:255:20: error: expected ')'
unsigned long long ntohll (unsigned long long n);
                   ^
/usr/include/sys/_endian.h:140:25: note: expanded from macro 'ntohll'
#define ntohll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/usr/include/libkern/_OSByteOrder.h:78:30: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
                             ^
./common.h:255:20: note: to match this '('
/usr/include/sys/_endian.h:140:25: note: expanded from macro 'ntohll'
#define ntohll(x)       __DARWIN_OSSwapInt64(x)
                        ^
...
```

[Here is a gist of the full output](https://gist.github.com/ryan-williams/e931712fdb144381148c). Let me know if you have any ideas for fixing this?

**Comment by mfournier** [comment]
@ryan-williams, this looks unrelated to the initial issue. Could you please open a new issue with the details?

Also, I'm surprised others didn't already hit this problem. Could you give some detail about your build environment? Does this only happen with the collectd-5.3 branch? Or are collectd-5.4 and master also affected?

**Comment by ifesdjeen** [comment]
@ryan-williams just re-run configure. Autoconf already knows to to handle `ntohll`. That probably happened after migrating to Yosemite, although re-configuring and compiling from scratch should help (helped me at least).

`ntohll` is a widespread issue, almost every compiled project had same problem..

**Comment by ryan-williams** [comment]
@ifesdjeen hm, I tried a few permutations of re-configuring / re-build.sh-ing / wiping out the workspace and starting over. Still seeing the same error:
```
network_buffer.c:154:17: error: expected ')'
static uint64_t htonll (uint64_t val) /* {{{ */
                ^
/usr/include/sys/_endian.h:141:25: note: expanded from macro 'htonll'
#define htonll(x)       __DARWIN_OSSwapInt64(x)
                        ^
```
etc.

Any ideas? Not sure what other "re-configuring" to attempt.

**Comment by ryan-williams** [comment]
@mfournier the above was on `origin/collectd-5.3` / ba55ad9ae41052b665d008f20f4b7076983446e2

When I try on `origin/master` / 359b83ce244738d87827712e85a9b5ed7ef6adbf, I get:
```
cpu.c:235:2: error: use of undeclared identifier 'cpu_temp_retry_max'
        cpu_temp_retry_max = 86400 / CDTIME_T_TO_TIME_T (plugin_get_interval ());
        ^
```
[full gist](https://gist.github.com/ryan-williams/4c395aa7196716d22425)

that is the error this issue started with. Let me know if you want me to file a different one for `collectd-5.3` not compiling (only on Yosemite I guess?)

**Comment by ifesdjeen** [comment]
@ryan-williams perfect, if that works, you can just comment that line and compile (or define that variable). I didn't need that plugin to work, so I didn't check how that affects functionality.

**Comment by ryan-williams** [comment]
per [this comment](https://github.com/collectd/collectd/pull/885#issuecomment-69114050) on #885, I believe that `origin/master` is once again failing on Yosemite with new errors that have not been otherwise fixed; could be worth re-opening this
