### ISSUE TITLE
write_graphite Connection refused

### ISSUE THREAD

**Issue by japrescott** [collectd/collectd#866]
I am trying to setup collectd within a docker project but I've been out of luck as collectd/carbon is acting up on me saying
"write_graphite plugin: send to localhost:2003 ((null)) failed with status -1 (Connection refused)"

I've triple checked that carbon-cache.py is fired up and I've been looking at everything from graphite, collectd to the source-code of the write_graphite plugin itself and I am not able to get collectd and carbon to talk with eachother. Carbon's own stats are saved to the whisper files but things sent via network to the 25826 port cause the "connection refused" error described above.

I've seen your comment in the docs saying it could be due too many open file descriptors but haven't seen the errors you describe.

Any help in any direction would be greatly appreciated!
Thank you

**Comment by lextoumbourou** [comment]
@mfournier thanks, man! :heart:

**Comment by imthegod** [comment]
@mfournier thank for the tip.
I'm new to linux(ubuntu) and have the same issue. Can some one tell me what to do next?
@japrescott  @lextoumbourou how did you guys solve the issue

**Comment by bbhandari** [comment]
Guys, can you please help me out with this, it gets connected successfully, and right after that, it fails ?
Mar 15 14:21:54 forwarder collectd[17247]: write_graphite plugin: Successfully connected to 52.32.76.219:10001 via tcp.
Mar 15 14:22:14 forwarder collectd[17247]: write_graphite plugin: send to 52.32.76.219:10001 (tcp) failed with status -1 (Broken pipe)

**Comment by mojili** [comment]
I get below log on /var/log/messages:

write_prometheus plugin: MHD_start_daemon() failed.
Initialization of plugin `write_prometheus' failed with status -1. Plugin will be unloaded.

checked the /var/log/audit/audit.log and see " avc: denied { name_bind } for pid=xxxxx comm="collectd" src=9103 " for collectd. my selinux mode is enforcing and I solved my problem like this:

yum -y install policycoreutils-python
semanage permissive -a collectd_t

plugin_load: plugin "syslog" successfully loaded.
plugin_load: plugin "cpu" successfully loaded.
plugin_load: plugin "interface" successfully loaded.
plugin_load: plugin "load" successfully loaded.
plugin_load: plugin "memory" successfully loaded.
plugin_load: plugin "uptime" successfully loaded.
plugin_load: plugin "write_prometheus" successfully loaded.
Initialization complete, entering read-loop.

**Comment by ady080808** [comment]
I got this error :collectd[859]:   apache: curl_easy_perform failed: Failed connect to localhost:80; Connection refused  and  collectd[859]: apache plugin: The configuration option "URL" is not allowed here. Did you forget to add an <Instance /> block around the configuration? from collectd-apache-5.8.0-4.el7.x86_64.rpm. 
I did not get this error from older version.

**Comment by fsanyee** [comment]
> I get below log on /var/log/messages:
> 
> write_prometheus plugin: MHD_start_daemon() failed.
> Initialization of plugin `write_prometheus' failed with status -1. Plugin will be unloaded.
> 
> checked the /var/log/audit/audit.log and see " avc: denied { name_bind } for pid=xxxxx comm="collectd" src=9103 " for collectd. my selinux mode is enforcing and I solved my problem like this:
> 
> yum -y install policycoreutils-python
> semanage permissive -a collectd_t
> 
> plugin_load: plugin "syslog" successfully loaded.
> plugin_load: plugin "cpu" successfully loaded.
> plugin_load: plugin "interface" successfully loaded.
> plugin_load: plugin "load" successfully loaded.
> plugin_load: plugin "memory" successfully loaded.
> plugin_load: plugin "uptime" successfully loaded.
> plugin_load: plugin "write_prometheus" successfully loaded.
> Initialization complete, entering read-loop.

There is a boolean for that:
setsebool -P  collectd_tcp_network_connect 1

**Comment by hariszaman** [comment]
Guys, can you please help me out with this, it gets connected successfully, and right after that, it fails ?
Mar 15 14:21:54 forwarder collectd[17247]: write_graphite plugin: Successfully connected to 52.32.76.219:10001 via tcp.
Mar 15 14:22:14 forwarder collectd[17247]: write_graphite plugin: send to 52.32.76.219:10001 (tcp) failed with status -1 (Broken pipe)

@bbhandari did you find out whether that was a problem or it is the expected behaviour. I am facing the same problem.

**Comment by mrunge** [comment]
there are quite a couple of issues mixed together here.

@hariszaman Please open a new issue instead of jumping on already closed ones (with different topics).
When filing a new issue, please provide a bit more context, thank you.
