### ISSUE TITLE
Segfaults when using absolute_t with plugin_dispatch_multivalue

### ISSUE THREAD

**Issue by ifesdjeen** [collectd/collectd#867]
Hi,

I'm using `absolute_t` with `asbolute` type with `plugin_dispatch_multivalue`: 

```
asbolute_t ram_value         = (asbolute_t) memory.ram;

plugin_dispatch_multivalue (&vl, 0,
                            "ram"         , ram_value,
                            ...
                            NULL);          
```

Although that always results into segfault. 
The minute I change `asbolute_t` to `gauge_t` everything works smoothly. Although that's not a gauge, that's an absolute value. 

Any ideas what could possibly cause that?

**Comment by mfournier** [comment]
Thanks a lot @ifesdjeen ! Closing as your patch got merged the other day.

**Comment by ifesdjeen** [comment]
Ah right! Totally forgot thanks @mfournier !
