### ISSUE TITLE
ping_init() called multiple times on Solaris

### ISSUE THREAD

**Issue by julianrct** [collectd/collectd#869]
On Solaris when the kstat chain is updated it looks like ping_init() (and possibly other plugin _init() functions) are called again. In the case of ping_init() this causes the plugin to fail, since it tries for a second time to create the read thread.

The following simple patch fixes the issue:

```
--- src/ping.c.orig     2014-01-26 08:09:14.000000000 +0000
+++ src/ping.c  2014-12-17 09:52:19.363630000 +0000
@@ -437,7 +437,10 @@
         "Will use a timeout of %gs.", ping_timeout);
   }

-  if (start_thread () != 0)
+  /* ping_init() can be called more than once if the kstat chain is updated,
+     so guard against creating multiple read threads. */
+
+  if (ping_thread_loop == 0 && start_thread () != 0)
     return (-1);

   return (0);
```

Regards,
Julian

**Comment by octo** [comment]
When called again, *start_thread()* returns non-zero, causing the init function to signal failure, which causes *plugin_unregister_read()* to be called for that plugin.

The simplest possible fix is to return gracefully, i.e. a zero, in that case.
