### ISSUE TITLE
Statsd + Network: instance type is truncate

### ISSUE THREAD

**Issue by duylong** [collectd/collectd#872]
Hi, 

I use statsd and network plugins with collectd (5.4.1) and I have a issue.

I send this instance "logs.aaa-aaaaaa-aaa01_aa_aa-aaaaa-aaaa_aa.collectd.severity.informational" to collectd, but when it receive the data, I get to the output this instance "logs.aaa-aaaaaa-aaa01_aa_aa-aaaaa-aaaa_aa.collectd.severity.inf" (63 chars)

Do you know this issue ?

My config:

```
<Plugin statsd>
  Host "::"
  Port "8125"
  DeleteCounters false
  DeleteTimers   false
  DeleteGauges   false
  DeleteSets     false
  TimerPercentile 90.0
</Plugin>

<Plugin network>
    <Server "XXXX" "25826">
    </Server>
    MaxPacketSize 1452
</Plugin>
```

Cordialy,

**Comment by duylong** [comment]
This limit is short when we have a FQDN with 40/50 characters. Associated with the program name, the limit is quickly exceeded.

**Comment by Dinoshauer** [comment]
What is the reasoning for limiting these things? Would it be safe to build collectd myself with an increased limit?
I'm running into a similar wall with the StatsD plugin and it gets pretty hard to know what you're looking at when you don't have control of what the name of the metrics are.

**Comment by tokkee** [comment]
I suppose the original reason for a static limit was to avoid lots of temporary memory allocations. Ultimately, I think we should change that.

Anyway, for now, it *should* be safe to increase the size but, afaik, nobody tried it yet, so there's some chance that things may break because parts of the code could assume the current limit.

**Comment by Dinoshauer** [comment]
Thank you for your quick response, I might give it a try. Some of these names are several hundred characters long it seems

**Comment by throck** [comment]
@Dinoshauer were you able to try increasing DATA_MAX_NAME_LEN, and if so, any issues?

**Comment by Dinoshauer** [comment]
Yes, we did, we haven't run into any issues so far. It's been running on a bunch of machines for the past few months.

**Comment by falzm** [comment]
I ran into this "issue" a few days ago, too. It would indeed be nice to raise the metric name length.

**Comment by mre** [comment]
+1 This would be very useful for us as well. See https://github.com/collectd/collectd/pull/1120

**Comment by rubenk** [comment]
DATA_MAX_NAME_LEN was increased to 128 in 6fd0d2574fc386c2724c8307d33b12529b30048b, and can now also be potentially overridden with `./configure --with-data-max-name-len[=VALUE]`
