### ISSUE TITLE
5.5 release timing

### ISSUE THREAD

**Issue by skottler** [collectd/collectd#880]
First off thanks so much for all your hard work. We run collectd as our primary metrics collection agent on many thousands of machines at DigitalOcean and have found it be reliable and extensible.

Currently we run a custom build which is 5.4.1 plus a relatively large number of patches from master. We've also used our build as a testing ground for patches like adding I/O to the disk plugin, or support for `MemAvailable` in the memory plugin. That being said, we'd like to completely get rid of our custom build and instead use the work which has been upstreamed since the 5.4.1 release. Is there a timeline for the 5.5 release?

Additionally, DigitalOcean would be happy to sponsor any test machines you need. I personally would also be willing to help setup some kind of CI pipeline for collectd if you all are interested in that.

Thanks again!

**Comment by mfournier** [comment]
Thanks for the feedback & contributions @skottler ! Thrilled to learn you're using collectd at digitalocean !

There are a couple more details I'd like to have in before 5.5, but I don't think there will be any other major changes in master before the release. So if you feel like it, I'd say that running master is now pretty safe (quite a few other people do). But to answer your question, no formal release date has been discussed AFAIK.

About CI, this has been discussed a couple of times (on IRC at least) in the past, so your offer for help is very welcome. On my side, I've done a bit of work towards making nightly debs/rpms out of master but nothing really finished yet. I'm going to open a separate issue to talk about this topic.

**Comment by mfournier** [comment]
@rubenk, by the way do you have a schedule date for the Fedora 22 branch ? No promises, but this could be a good reason to get 5.4.2 published soon.

**Comment by rubenk** [comment]
Hi @mfournier, the branch date as it is now is 2015-02-10: https://fedoraproject.org/wiki/Releases/22/Schedule

**Comment by kiranos** [comment]
getting close :)

**Comment by txaj** [comment]
:+1:

**Comment by hnyman** [comment]
Is there going to be a release in near future? 
5.5 might be nice, but also the older 5.4 branch might benefit from an update. It has now been 13 months since the last release :-(

And the current repo organisation of this project is rather confusing as the main collectd.org site still points to the old separate git (git.verplant.org), which has not been updated for months. Apparently all development now happens here, but that is not reflected on the main site... ????

**Comment by mazzystr** [comment]
Any update on 5.5 release date?

**Comment by cruatta** [comment]
WOO CLOSE IT!

**Comment by skottler** [comment]
Yay! Closing.
