### ISSUE TITLE
Add arbitrary attributes to write_riemann

### ISSUE THREAD

**Issue by blalor** [collectd/collectd#892]
Can `write_riemann`be extended to support arbitrary attributes?  It currently has `Tag` (which I'm assuming can be specified multiple times).  It would be nice to be able to also add key/value pairs (supported by Riemann's events), as well.

/cc @mfournier @pyr

**Comment by mfournier** [comment]
Yes, this feature already exists in master. Expect it in 5.5.

**Comment by blalor** [comment]
Sweet!  When can we expect 5.5? :-)

**Comment by mfournier** [comment]
No ETA defined, but soon I hope :-)
