### ISSUE TITLE
Is write_http leaking memory when network is unavailable?

### ISSUE THREAD

**Issue by kuchumovn** [collectd/collectd#913]
We have collectd 5.4.0.git installed.
It sends collected data to a local gateway through the write_http plugin.
When network is unavailable it starts leaking memory (up to several gigabytes).
And restarting it is also slow:

```
 * Restarting statistics collection and monitoring daemon collectd   . . . .      [ok]
```

Do you have any clues on the possibility of write_http leaking memory when the destination is unreachable?

```
probe@Probe:~$ ping 10.60.1.1
PING 10.60.1.1 (10.60.1.1) 56(84) bytes of data.
From 10.60.1.3 icmp_seq=1 Destination Host Unreachable
From 10.60.1.3 icmp_seq=2 Destination Host Unreachable
```

**Comment by mschenck** [comment]
I often hear complaints that `collectd` has memory leaks, only to uncover that [WriteQueueLimitHigh and WriteQueueLimitLow](http://www.collectd.org/documentation/manpages/collectd.conf.5.shtml#writequeuelimithigh_highnum) were left the (default) _unlimited_ value. 

Can you confirm that you have set this to acceptable upper-bounds and are _still_ seeing a memory leak?

**Comment by kuchumovn** [comment]
Guess what?
Obviously I never knew these even existed.
I've searched through the docs a bit, even studied the write_http source code a bit, but these two parameters didn't cross my search.
Thanks for pointing that out for me.
I'll try them today at work.

**Comment by kuchumovn** [comment]
I'm gonna close the issue for now since the testing will take several days, etc.

**Comment by mschenck** [comment]
No rush, but please ping back if you still have memory leaks.

these are globally applied configuration settings, so they won't be referenced in the `write_http` module code, and should be applied in your primary config (likely `/etc/collectd/collectd.conf`)

**Comment by kuchumovn** [comment]
Ok.
We've done some tests and I guess that it resolved the issue

```
WriteQueueLimitHigh 20000
WriteQueueLimitLow 20000
```

It keeps collectd memory at 17 megabytes (two days passed).

**Comment by mschenck** [comment]
I'm *so* happy to hear that these solved your issues!  Thanks for following up.

**Comment by kuchumovn** [comment]
Oh, yeah, thank you for your help, Michael : )

**Comment by blockjon** [comment]
I just had my whole fleet of servers crash due to this issue. I wish this was set to a sane default with the option setup to have a person willingly set it to zero.
