### ISSUE TITLE
IPMI HP DLxxx PowerSupply

### ISSUE THREAD

**Issue by DawgTool** [collectd/collectd#928]
Another Power Supply that is discrete on an HP DL385.

[2015-02-05 21:42:37] [info] ipmi plugin: sensor_list_add: Ignore sensor Memory system_board (7.8), because I don't know how to handle its type (0xc, memory). If you need this sensor, please file a bug report.
[2015-02-05 21:42:37] [info] ipmi plugin: sensor_list_add: Ignore sensor Power Supplies power_supply (10.3), because I don't know how to handle its type (0x8, power_supply). If you need this sensor, please file a bug report.
[2015-02-05 21:42:37] [info] ipmi plugin: sensor_list_add: Ignore sensor Power Supply 2 power_supply (10.2), because I don't know how to handle its type (0x8, power_supply). If you need this sensor, please file a bug report.
[2015-02-05 21:42:37] [info] ipmi plugin: sensor_list_add: Ignore sensor Power Supply 1 power_supply (10.1), because I don't know how to handle its type (0x8, power_supply). If you need this sensor, please file a bug report.
[2015-02-05 21:42:37] [info] ipmi plugin: sensor_list_add: Ignore sensor Sys. Health LED system_chassis (23.2), because I don't know how to handle its type (0xc0, invalid). If you need this sensor, please file a bug report.
[2015-02-05 21:42:37] [info] ipmi plugin: sensor_list_add: Ignore sensor UID Light system_chassis (23.1), because I don't know how to handle its type (0xc0, invalid). If you need this sensor, please file a bug report.

ipmitool sensor
UID Light        | 0x0        | discrete   | 0x0080| na        | na        | na        | na        | na        | na
Sys. Health LED  | 0x0        | discrete   | 0x0080| na        | na        | na        | na        | na        | na
Power Supply 1   | 115        | Watts      | ok    | na        | na        | na        | na        | na        | na
Power Supply 2   | 125        | Watts      | ok    | na        | na        | na        | na        | na        | na
Power Supplies   | 0x0        | discrete   | 0x0180| na        | na        | na        | na        | na        | na
Fan 1            | 29.400     | percent    | ok    | na        | na        | na        | na        | na        | na
Fan 2            | 29.400     | percent    | ok    | na        | na        | na        | na        | na        | na
Fan 3            | 37.240     | percent    | ok    | na        | na        | na        | na        | na        | na
Fan 4            | 55.664     | percent    | ok    | na        | na        | na        | na        | na        | na
Fan 5            | 55.664     | percent    | ok    | na        | na        | na        | na        | na        | na
Fan 6            | 14.112     | percent    | ok    | na        | na        | na        | na        | na        | na
Fans             | 0x0        | discrete   | 0x0180| na        | na        | na        | na        | na        | na
Temp 1           | 15.000     | degrees C  | ok    | na        | na        | na        | na        | 41.000    | 45.000
Temp 2           | 29.000     | degrees C  | ok    | na        | na        | na        | na        | 75.000    | 80.000
Temp 3           | 27.000     | degrees C  | ok    | na        | na        | na        | na        | 75.000    | 80.000
Temp 4           | 31.000     | degrees C  | ok    | na        | na        | na        | na        | 87.000    | 92.000
Temp 5           | 31.000     | degrees C  | ok    | na        | na        | na        | na        | 87.000    | 92.000
Temp 6           | 30.000     | degrees C  | ok    | na        | na        | na        | na        | 87.000    | 92.000
Temp 7           | 28.000     | degrees C  | ok    | na        | na        | na        | na        | 87.000    | 92.000
Temp 8           | 32.000     | degrees C  | ok    | na        | na        | na        | na        | 90.000    | 95.000
Temp 9           | 28.000     | degrees C  | ok    | na        | na        | na        | na        | 90.000    | 95.000
Temp 10          | 39.000     | degrees C  | ok    | na        | na        | na        | na        | 90.000    | 95.000
Temp 11          | 35.000     | degrees C  | ok    | na        | na        | na        | na        | 70.000    | 75.000
Temp 12          | 23.000     | degrees C  | ok    | na        | na        | na        | na        | 60.000    | 65.000
Temp 13          | 35.000     | degrees C  | ok    | na        | na        | na        | na        | 77.000    | 82.000
Temp 14          | 41.000     | degrees C  | ok    | na        | na        | na        | na        | 90.000    | 95.000
Temp 15          | 31.000     | degrees C  | ok    | na        | na        | na        | na        | 70.000    | 75.000
Temp 16          | 27.000     | degrees C  | ok    | na        | na        | na        | na        | 70.000    | 75.000
Temp 17          | 34.000     | degrees C  | ok    | na        | na        | na        | na        | 70.000    | 75.000
Temp 18          | 26.000     | degrees C  | ok    | na        | na        | na        | na        | 70.000    | 75.000
Temp 19          | 64.000     | degrees C  | ok    | na        | na        | na        | na        | 105.000   | 110.000
Temp 20          | 35.000     | degrees C  | ok    | na        | na        | na        | na        | 60.000    | 65.000
Temp 21          | 30.000     | degrees C  | ok    | na        | na        | na        | na        | 70.000    | 75.000
Temp 22          | 32.000     | degrees C  | ok    | na        | na        | na        | na        | 70.000    | 75.000
Temp 23          | 32.000     | degrees C  | ok    | na        | na        | na        | na        | 70.000    | 75.000
Temp 24          | 32.000     | degrees C  | ok    | na        | na        | na        | na        | 70.000    | 75.000
Temp 25          | na         |            | na    | na        | na        | na        | na        | 70.000    | 75.000
Temp 26          | na         |            | na    | na        | na        | na        | na        | 70.000    | 75.000
Temp 27          | na         |            | na    | na        | na        | na        | na        | 70.000    | 75.000
Temp 28          | na         |            | na    | na        | na        | na        | na        | 70.000    | 75.000
Memory           | 0x0        | discrete   | 0x4080| na        | na        | na        | na        | na        | na
Power Meter      | 284        | Watts      | ok    | na        | na        | na        | na        | na        | na

**Comment by rubenk** [comment]
Thanks for the report. This is a known issue and reported in #735. Closing this.
