### ISSUE TITLE
lvm: segfault on i386

### ISSUE THREAD

**Issue by mfournier** [collectd/collectd#941]
Running current master, I get the following segfault irregularly (2-3 times per hour, collectd configured with default `Interval` setting) on debian stable (which comes with liblvm2app2.2-2.02.95-8). Curiously, I never observed this on 64bit machines running the same version of collectd.

```
[...]
Program terminated with signal 11, Segmentation fault.
#0  0xb7484c3b in dm_pool_alloc_aligned () from /lib/i386-linux-gnu/libdevmapper.so.1.02.1
(gdb) bt
#0  0xb7484c3b in dm_pool_alloc_aligned () from /lib/i386-linux-gnu/libdevmapper.so.1.02.1
#1  0xb7484ceb in dm_pool_alloc () from /lib/i386-linux-gnu/libdevmapper.so.1.02.1
#2  0xb74b58ca in ?? () from /lib/i386-linux-gnu/liblvm2app.so.2.2
#3  0xb74af0c1 in ?? () from /lib/i386-linux-gnu/liblvm2app.so.2.2
#4  0xb74e75e3 in ?? () from /lib/i386-linux-gnu/liblvm2app.so.2.2
#5  0xb74a7f13 in lvm_list_vg_names () from /lib/i386-linux-gnu/liblvm2app.so.2.2
#6  0xb7570e16 in lvm_read () at lvm.c:173
#7  0x08058c1a in plugin_read_thread (args=0x0) at plugin.c:516
#8  0xb7722c39 in start_thread () from /lib/i386-linux-gnu/i686/cmov/libpthread.so.0
#9  0xb768197e in clone () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
```

For the record, `lvm_read () at lvm.c:173` was there at the plugin inception and never got modified since.

/cc @cmalfait @bgilbert FYI

**Comment by octo** [comment]
@mfournier can you still reproduce this problem?

**Comment by mfournier** [comment]
Unfortunately the last i386 machines of our fleet are now gone.

As the stacktrace refers mainly to liblvm stuff, I'm under the impression the problem is out of reach for us anyways. Closing this issue.
