### ISSUE TITLE
memory leak in write_mongo

### ISSUE THREAD

**Issue by eremenko** [collectd/collectd#956]
need next patch

```diff
diff -rpu collectd-5.2.0/src/write_mongodb.c collectd-5.2.0-fixed/src/write_mongodb.c
--- collectd-5.2.0/src/write_mongodb.c  2012-11-18 02:23:21.000000000 +0400
+++ collectd-5.2.0-fixed/src/write_mongodb.c    2013-09-16 22:37:58.966065563 +0400
@@ -220,6 +220,7 @@ static int wm_write (const data_set_t *d
   pthread_mutex_unlock (&node->lock);

   /* free our resource as not to leak memory */
+  bson_destroy (bson_record);
   bson_dispose (bson_record);

   return (0);
```

**Comment by octo** [comment]
It appears that `bson_dispose()` has been removed from the library entirely. I've therefore changes this to call `bson_destroy()` only. Does this seem correct?

**Comment by octo** [comment]
I've done some more reading up on the (ever changing) API of *mongo-c-driver* and think that this latest patch should deinitialize and deallocate the buffer as required. It compiled, I couldn't do any *real* testing though. Please reopen if the problem persists with this patch applied.

**Comment by eremenko** [comment]
OK, thanks Florian. I'll tring testing, but in real client environment it's can take many time.
