### ISSUE TITLE
CPU plugin ValuesPercentage support...working or not?

### ISSUE THREAD

**Issue by daniel-middleton** [collectd/collectd#969]
ValuesPercentage support for the CPU plugin seems to have been merged in to master but the documentation doesn't reflect this and it doesn't seem to work, there's also no default config section for the plugin, at least in 5.4.0 from the Ubuntu repos. Could you please shed some light on this as it's a pretty critical stat to have available, unless there's a nice way to reliably convert from jiffies for use in Grafana.

https://github.com/collectd/collectd/commit/fdfc8dc0e165088350f7c92972234cea142cd131?diff=unified

Thank you.

**Comment by daniel-middleton** [comment]
Bump?

**Comment by mfournier** [comment]
@daniel-middleton it's pending the 5.5 release, which is to be expected pretty soon. There's no plan to backport this to the 5.4 line, but I'd love to see packages for 5.5 available for ubuntu soon after the release.
