### ISSUE TITLE
StatsD timers with long names generate uc_update warnings

### ISSUE THREAD

**Issue by mark-5** [collectd/collectd#970]
Whenever a StatsD timer is sent with a metric name longer than 61 chars, collectd will consistently generate the warning `uc_update: Value too old`.

If you are using a StatsD plugin that is listening on localhost:8125, you can trigger this warning from the command line with
`echo 'i_am_writing_a_really_long_string_with_over_sixty_one_characters:1|ms' | nc -w 1 -u localhost 8125`

**Comment by yogeswaran** [comment]
I see this problem too

**Comment by mark-5** [comment]
I looked into this some more, and it turns out the timer percentiles and averages, which normally append additional identifiers to the name, were getting truncated. This caused all of these metrics to write to the same cache entry.

**Comment by jewzaam** [comment]
My project is using hystrix which includes a prefix, the string "HystrixCommand", the actual command name, and then the metric name as what is published to statsd.  We get some unfortunate truncation and merging of metrics.  For example, the following metrics:
* lightblue_HystrixCommand_mongodb:InsertCommand_latencyExecute_percentile_5
* lightblue_HystrixCommand_mongodb:InsertCommand_latencyExecute_percentile_25
* lightblue_HystrixCommand_mongodb:InsertCommand_latencyExecute_percentile_75
* lightblue_HystrixCommand_mongodb:InsertCommand_latencyExecute_percentile_90
* lightblue_HystrixCommand_mongodb:InsertCommand_latencyExecute_percentile_95
* lightblue_HystrixCommand_mongodb:InsertCommand_latencyExecute_percentile_995

Are truncated to:
* lightblue_HystrixCommand_mongodb:InsertCommand_latencyExecute_p

If we strip the string "HystrixCommand_" from the metric we're still close to the limit at 62 characters.  We could also strip the prefix "lightblue_".  This is just one example, I'm assuming there are other longer metric names published by Hystrix.  Having this fixed would be great.

**Comment by octo** [comment]
Should be fixed by #1120
