### ISSUE TITLE
IRQ plugin sending a null value

### ISSUE THREAD

**Issue by brookst** [collectd/collectd#971]
My install of collectd is spamming syslog with messages of the form:

    collectd[]: parse_value: Failed to parse string as derive: (null).

By process of elimination I determined it is coming from the IRQ plugin. I can't seem to find anyone else with the same issue. If it helps, this system is a Raspberry Pi.

**Comment by magenbrot** [comment]
I've the same problem. It's also on a Raspberry Pi (2).

**Comment by rubenk** [comment]
Can you guys give this patch a try?

**Comment by jcberthon** [comment]
Hi guys,

On my Raspberry Pi 2 I have the same issue, if I deactivate the plugin irq, I'm not "spammed" by the above mentioned error message. I'm running Raspbian Jessie with collectd 5.4.1. My problem is that I can't easily figure out if the mentioned patch is part of my release or not. And in the case it isn't, in which release is this patch merged?

If you let me know, I can give it a try.

**Comment by octo** [comment]
Ruben's fix for this, 91fbf283d2c180105c4729907ea9d2079c6d93f7, is in 5.4.3, 5.5.1 and later.
