### ISSUE TITLE
log_logstash generates legacy logstash json format

### ISSUE THREAD

**Issue by mfournier** [collectd/collectd#974]
I just realised this plugin generates an outdated format. This is an example of notification & log message:

```
{"@message":"Host foobar, plugin load type load: Data source \"shortterm\" is currently 0.040000. That is below the failure threshold of 1.000000.","@fields":{"host":"foobar","plugin":"load","type":"load","severity":"failure"},"@level":"info","@timestamp":"2015-03-17 14:17:48Z"}
{"@message":"plugin: plugin_write: Writing values via network.","@level":"debug","@timestamp":"2015-03-17 14:17:48Z"}
```

Logstash's default event format was changed in release 1.2.0 (released in september 2013), see https://logstash.jira.com/browse/LOGSTASH-675

Comparing the examples from http://logstash.net/docs/1.1.1/tutorials/getting-started-simple with http://logstash.net/docs/1.2.1/tutorials/getting-started-simple gives an idea of how events now look like.

I would recommend updating log_logstash to generate the newer format, and simply drop the older format, as this isn't part of any collectd release yet.

@pyr, I can take care of this if you agree.

**Comment by pyr** [comment]
yup, this would be a great addition.
