### ISSUE TITLE
Complex config with multiple entries

### ISSUE THREAD

**Issue by DawgTool** [collectd/collectd#975]
Hi All,

I'm wondering if anyone has setup a complex config using repeating keys, essentially building a hash and/or array.

Example:

<Plugin X>
  <Parent>
    Child ABC
    Child ZXY
 </Parent>
</Plugin>

Child = [ABC, ZXY]
Any thoughts?

Thanks,
-- Dallin

**Comment by rubenk** [comment]
Hi there,

Please come by on IRC, #collectd on freenode, perhaps we can help you there.

We'd like to keep the issue tracker for bug reports and patch reviews.
