### ISSUE TITLE
compile error on collect-tg on solaris 11 / sparc

### ISSUE THREAD

**Issue by xtra-be** [collectd/collectd#978]
when compiling master on solaris 11.2 / sparc
compile fail's on collectd-tg

```
Making all in daemon
  CC     collectd_tg-collectd-tg.o
collectd-tg.c: In function â€˜get_boundet_randomâ€™:
collectd-tg.c:138:3: error: implicit declaration of function â€˜randomâ€™ [-Werror=implicit-function-declaration]
   return (min + ((int) (((double) range) * ((double) random ()) / (((double) RAND_MAX) + 1.0))));
   ^
collectd-tg.c: In function â€˜create_value_listâ€™:
collectd-tg.c:184:3: error: implicit declaration of function â€˜snprintfâ€™ [-Werror=implicit-function-declaration]
   snprintf (vl->identifier.host, sizeof (vl->identifier.host),
   ^
collectd-tg.c:184:3: error: incompatible implicit declaration of built-in function â€˜snprintfâ€™ [-Werror]
collectd-tg.c:192:7: error: format â€˜%liâ€™ expects argument of type â€˜long intâ€™, but argument 4 has type â€˜intâ€™ [-Werror=format=]
       "ti%li", random ());
       ^
cc1: all warnings being treated as errors
*** Error code 1
The following command caused the error:
echo "  CC    " collectd_tg-collectd-tg.o;gcc -DHAVE_CONFIG_H -I.  -I./daemon -DPREFIX='"/opt/collectd"'  -DCONFIGFILE='"/opt/collectd/etc/collectd.conf"'  -DLOCALSTATEDIR='"/opt/collectd/var"'  -DPKGLOCALSTATEDIR='"/opt/collectd/var/lib/collectd"'  -DPIDFILE='"/opt/collectd/var/run/collectd.pid"' -DPLUGINDIR='"/opt/collectd/lib/collectd"'  -DPKGDATADIR='"/opt/collectd/share/collectd"' -I../src/libcollectdclient/collectd -I../src/libcollectdclient/collectd  -Wall -Werror -g -O2 -MT collectd_tg-collectd-tg.o -MD -MP -MF .deps/collectd_tg-collectd-tg.Tpo -c -o collectd_tg-collectd-tg.o `test -f 'collectd-tg.c' || echo './'`collectd-tg.c
make: Fatal error: Command failed for target `collectd_tg-collectd-tg.o'
Current working directory /root/collectd-master/src
*** Error code 1
The following command caused the error:
fail= failcom='exit 1'; \
for f in x $MAKEFLAGS; do \
  case $f in \
    *=* | --[!k]*);; \
    *k*) failcom='fail=yes';; \
  esac; \
done; \
dot_seen=no; \
target=`echo all-recursive | sed s/-recursive//`; \
list='libcollectdclient liboconfig daemon'; for subdir in $list; do \
  echo "Making $target in $subdir"; \
  if test "$subdir" = "."; then \
    dot_seen=yes; \
    local_target="$target-am"; \
  else \
    local_target="$target"; \
  fi; \
  (CDPATH="${ZSH_VERSION+.}:" && cd $subdir && make  $local_target) \
  || eval $failcom; \
done; \
if test "$dot_seen" = "no"; then \
  make  "$target-am" || exit 1; \
fi; test -z "$fail"
make: Fatal error: Command failed for target `all-recursive'
Current working directory /compile/collectd-master/src
*** Error code 1
make: Fatal error: Command failed for target `all'
```

**Comment by xtra-be** [comment]
including stdlib.h fixes this issue

**Comment by octo** [comment]
@xtra-be The file `src/collectd-tg.c` already includes `<stdlib.h>` — where is it missing?

**Comment by octo** [comment]
@xtra-be ping?

**Comment by xtra-be** [comment]
hi 
sorry i did not yet have the time to recheck my configuration to see what what was wrong
but i think we also changed the c flags to compile in 64bit
i will update next week when my build environment is back available

**Comment by octo** [comment]
There appear to be (at least) two undeclared functions, `random(3)` and `snprintf(3)`. Both, `<stdlib.h>` and `<stdio.h>` are included, so according to POSIX they should be there. My guess is that the quite strict POSIX version selection at the top of the file somehow confuses Solaris and keeps it from declaring the functions.

**Comment by dago** [comment]
Well, `/usr/include/stdlib.h` contains
```
#if defined(__EXTENSIONS__) || !defined(__XOPEN_OR_POSIX) || defined(_XPG4_2)
...
extern long random();
...
#endif
```
I guess it would be best to see if `random()` requires `-D__EXTENSIONS__`, I'll prepare a pull request.

**Comment by dago** [comment]
The definitions taken out confuse the include system of Solaris, if they are defined *then* `-D__EXTENSIONS__` is needed. Not defining them directly in the source fixes the issue on Solaris.

**Comment by octo** [comment]
@dago the build still appears to fail with the above patch: https://buildfarm.opencsw.org/buildbot/builders/collectd-solaris10-amd64/builds/29/steps/shell_2/logs/stdio
Would it be possible to call `make` with `V=1` so I can see the CFLAGS and CPPFLAGS passed to the compiler?

I think I'll "fix" this issue by removing those defines altogether, as per your patch. Fix in quotes because I think we're working around a bug in Solaris here.

**Comment by dago** [comment]
Yes, taking the definitions our is IMHO the right way. *If* they are defined *then* `__EXTENSIONS__` would be needed. I already wrote a check for that before I noticed that taking out is better.

**Comment by octo** [comment]
This patch has been merged to *master*.
