### ISSUE TITLE
MySQL - Open table statistics

### ISSUE THREAD

**Issue by ekilby** [collectd/collectd#979]
It would be helpful to monitor open table stats in MySQL using the plugin.

The following statistics are returned by show status, which the plugin currently calls, and could be sent:

Open_table_definitions - GAUGE
Open_tables - GAUGE
Opened_table_definitions - Counts up over time, resets on server start
Opened_tables - Counts up over time, resets on server start

Having positive values for opened_tables in particular is often indicative of a mistuned table cache.

(this is meant as a feature request FYI)

**Comment by nickrobinson** [comment]
Submitted a pull request to address this feature request: https://github.com/collectd/collectd/pull/1694

**Comment by octo** [comment]
Closing in favor of #1694
