### ISSUE TITLE
if no network while write_graphite plugin is working，can we store the info in local file when network is on the info can be sent out 

### ISSUE THREAD

**Issue by dllhlx** [collectd/collectd#981]
I read the source code but I can not find the logic to avoid info lost case by bad network 。
I think we can take rsyslogd's interrelated logic as a reference : if the netwok is bad, the write_* plugins can't work correctly, at that time collectd should store info in local storage to avoid info loss, when network become ok, collectd send out the storage info。Can the collectd do that?

**Comment by rubenk** [comment]
No, collectd doesn't store info in a local file when it can't use the network. It buffers some data in memory up to WriteQueueLimit.
