### ISSUE TITLE
"%error-verbose syntax error" while running make install

### ISSUE THREAD

**Issue by utkarshcmu** [collectd/collectd#994]
Stack Trace : 

make[3]: Entering directory `/root/collectd/src/liboconfig'
  YACC     parser.c
byacc: e - line 77 of "/root/collectd/src/liboconfig/parser.y", syntax error
%error-verbose
^
make[3]: *** [parser.c] Error 1
make[3]: Leaving directory `/root/collectd/src/liboconfig'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/root/collectd/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/root/collectd/src'
make: *** [all-recursive] Error 1

**Comment by skottler** [comment]
That's not a stack trace, it's just a few lines of build failure. Which platform are you trying to build on?

**Comment by utkarshcmu** [comment]
I am trying to build it on Amazon Linux / Centos 6.

**Comment by tokkee** [comment]
You will need bison (instead of byacc) when building from a Git checkout.
